### ISSUE TITLE
Make it easier/explicit to access/modify folders using the API

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#10630]
Right now it's not very clear from an API perspective how you access/modify folders. This issue should solve that.

In general, the folder API should wrap the dashboard API and hide the technical implementation of folders.

# Tasks
- [x] Validate if trying to access/modify a dashboard thru the folder API
- [x] `GET /api/folders`
- [x] `GET /api/folders/:uid`
- [x] `POST /api/folders`
- [x] `PUT /api/folders/:uid`
- [x] `DELETE /api/folders/:uid`
- [x] `GET /api/folders/id/:id`
- [x] `GET /api/folders/:uid/permissions`
- [x] `POST /api/folders/:uid/permissions`
- [x] Use new folder API in Grafana frontend
- [x] Rename `GET /api/dashboards/id/:id/acl` to `GET /api/dashboards/id/:id/permissions` and update docs
- [x] Rename `POST /api/dashboards/id/:id/acl` to `POST /api/dashboards/id/:id/permissions` and update docs
- [x] Create folder and permission api docs

Postponed until later
- Validate if trying to access/modify a folder thru the dashboard API (#10987)
- Use new folder permission API in Grafana frontend (#10987)
