### ISSUE TITLE
React Panels Support  

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#12759]
This is an overview issue of that will likely spawn many other smaller issues. 

### Main problems we are trying to solve/improve. 
- Make it possible to easily change panel (visualization) type while in edit mode & keep queries & thresholds settings. 
- Make writing new panels in react possible 
- Reduce duplication between panels (thresholds, value -> text, text -> value mapping, drilldown links)

# Design of react panels
Most panels should be stateless. The react component will get data & options & dashboard interation callbacks via props.  The query & data & state management can be handled by a higher order function component (DataPanel). There will be no "base" component like it is today with angular where panels either extend QueryCtrl or MetricsQueryCtrl. For react all panels will have the option to have queries, but they wont interact with the data source themeselvs but get query response data from props. 

Todos
- [x] Initial poc of react panels & new edit mode
- [x] Merge to master (branch react-panels)
  - [x] Make angular panels & react panels edit mode similar enough so you can switch between them more easily.
  - [x] Issue with panel height when first adding / rendering graph
  - [x] Panel height issues for legacy panels (when in edit / view mode)
  - [x] Regression testing
  - [x] Panel size passed via props 
- [x] Panel Header Menu 
  - [x] Add Duplicate, Share, Remove, Fix Edit/View, View Panel Json
  - [x] Do now show panel header menu when dragging header  
  - [ ] Expore option in panel menu
- [ ] Panel Header 
  - [x] Show timeshift and relative time override
  - [x] Show panel errors & open panel inspector
  - [x] Show Panel Links popover
  - [x] Show Panel Description
  - [x] Tooltip auto width not working (too narrow)
- [x] Panel Options
  - [x] POC panel common options (title, description) 
  - [x] POC panel plugin options component, (make change that propagate to panel) 8 
- [x] Panel option defaults
- [x] Panel option migrations 
- [x] Panels with no data queries
- [ ] Pass drilldown links to panel
- [x] Support Solo Route (embedd & image rendering)
- Flesh out DataPanel 
  - [x] Time series support
  - [x] Calculate interval
      - [ ] Interpolate variables
  - [x] Table data support
  - [ ] Annotations support
  - [ ] Streaming (rxjs Observable) support
  - [x] Support snapshots
- [x] Templating
  - [x] Variables via props (optional)
  - [x] Scoped variables via props (optional)
  - [x] Interpolate strings via func passed to panels via props
- [x] Hover over panel shortcuts should work
- Edit mode
  - [x] UX mockups for visualuzation tab & option layout
  - [x] General panel options (name / description, etc)
  - [x] Panel drilldown links 
  - [x] Time range overrides
  - [x] Alerting
  - [x] Make queries tab work 100%
    - [x] Make Query Inspector work (or hide it until we fix it)
    - [x] Make add query work

**Comment by torkelo** [comment]
Closing this and moving remaining issues to General Frontend Roadmap , https://github.com/grafana/grafana/issues/15990
