### ISSUE TITLE
Migrate Search To React Epic

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#13226]
There are many steps involved in migrating this as there are many components, pages & use cases to cover. 

I would try to do this in a few smaller steps rather than one big migration step. 

# Current components & pages

* The current search components & services are used in 3 locations, dashboard search that is used from dashboard (also accessible from every page using f shortcut). 
* Manage dashboards  (this view you can select dashboards & folder to do batch operations) 
* Folder dashboards 

All use searchSrv and mutable state, and most rely on angular digest dirt checking to detect changes
https://github.com/grafana/grafana/blob/master/public/app/core/services/search_srv.ts

All use this underlying search result component that mostly just handles showing items and expand toggle: 
https://github.com/grafana/grafana/blob/master/public/app/core/components/search/search_results.ts

Dashboard search has this as the main component: 
https://github.com/grafana/grafana/blob/master/public/app/core/components/search/search.ts

Manage dashboards:
https://github.com/grafana/grafana/blob/master/public/app/core/components/manage_dashboards/manage_dashboards.ts 

Folder dashboards:
https://github.com/grafana/grafana/blob/master/public/app/features/folders/FolderDashboardsCtrl.ts 

We previously made an attempt to migrate manage dashboards to react & redux all at once, and made it quite far:
https://github.com/grafana/grafana/pull/13397 the problem with that PR was that it was hard to reuse it for the normal dashboard search. It was too specific to manage dashboards and could not be easily made more general without a major refactor/rewrite and at the time we did not have time to do that and it was abandoned. 

It's important to understand that the main search that you can access from every page (ttps://github.com/grafana/grafana/blob/master/public/app/core/components/search/search.ts) only supports dashboard results currently but the plan is in the future to be able to show other types there as well (alert rules). So it's important to have the search result type a bit more generic and not link everything too strictly to dashboard items. 

# Where to start

- [x] Try to migrate the SearchResults component to react and use it [from angular](https://github.com/grafana/grafana/blob/master/public/app/core/angular_wrappers.ts) - #22847 

- [x] Refactor the actions section from the manage dashboards search #23057.

- [x] When needed to communicate state changes instead of angular dirty checking using appEvents to communicate when things need to update (and trigger react re-render with forceUpdate), or use react component state if possible
- [x] Next try to migrate the [main dashboard search component](https://github.com/grafana/grafana/blob/master/public/app/core/components/search/search.ts), still use searchSrv and the existing mutable search result items models (but might need to use appEvents to communicate state changes, not sure, or use react component state if possible) #23239.
- [x] Try to migrate the manage dashboards & folder views to react #23423.
- [x] Update Dashboard search to open/close on query params change #23641 
- [x] Cleanup unused Angular files #23667
- [x] Introduce redux state for a generic search result state & actions and try to make this reusable between manage dashboards and main search

## Using react-window

- [x] There is a lot of performance issues with the current one so a virtualized list would great #23620 

This is just a suggested way to approach it to make it more manageable and in order to do it in smaller PRs. After starting if shortcuts or better approaches can be found then they are welcome!

**Comment by Clarity-89** [comment]
@torkelo I think all the epic tasks are done, what's left are some bug fixes and UI improvements, but that's not search migration per se.

**Comment by torkelo** [comment]
Amazing job one this!
