### ISSUE TITLE
New Panel Edit UX

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#14184]
The goal for this issue is to get the panel-edit-in-react branch mergable to master, so some polish and further changes we can do in a later phase.

TODO
* [x] Fix sidemenu icons so they work in white & dark theme or seperate icons 
* [x] Add sidemenu icon for an "Advanced" section. Here we can put a drilldown links & templating here. Title & Description is here currently as well but (and tab i named Basic Options) but we can change that later and find better locations for these things.
* [x] Fix white theme for new panel edit ux
* [ ] Explore UX for "Going back to dashboard" without modifying dashboard toolbar. How should it look in edit mode and in panel "view" fullscreen. What can we do now an in a later phase? Explore mockups, but for the short term I want to keep it simple so no panel title editing in dashboard navbar. We can explore that after merge. Might want to explore both a "back to dashboard" ux option, and a "discard" and "save" option.
* [x] Query inspector needs to work fully.
* [x] Move time range tab options into the Queries Tab toolbar "options" subview (where we have min interval & max data points).

**Comment by torkelo** [comment]
closing this, easier to keep track of must fix todos in the develop branch PR
