### ISSUE TITLE
Explore: Code refactorings

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#14279]
Explore has been under feature toggle and developed with some less strict guidelines in order to move more quickly and explore possible features via POCS & conference demos. But  we soon plan to remove the feature toggle and make this a headline v6 feature, so would be good to discuss some ideas for code cleanup & refactoring.

* [ ] Sass is just one big file with everything from react table overrides to everything else, could be broken up at least a bit into separate components. 
* [x] Saas file contains a lot of nesting. For example, all the log related classes are under .explore. Not sure this is best practice. 
* [x] Explore.tsx main container has too much state detail logic, would be nice to figure out ways to refactor and break it apart. Try using redux for some of this state
* [x] QueryRow styling to align with the other query editors 
* [ ] Graph component could be refactored to use viz/Graph component and the new time series types & transforms. A bit of a moving target right now, but maybe Explore can help make this component move forward and shape it. Afraid that the longer we wait the harder the migration is going to be and we will end up with 3 graph components. 
* [ ] Table component could be rewritten to use react-virtualized and made into a generic viz component, a good foundation for the angular table panel migration to react? This is not a refactoring task really. Just a thought. Want to experiment with react-virtualized and get rid of the big pagination footer in react-table. 

any other suggestions @davidak @sunker @peterholmberg? Anything that is Prometheus specific that we need to rethink or move from Explore into the data source?

**Comment by peterholmberg** [comment]
Splitting `Explore.tsx` and move parts to more files/components would go a long way.
