### ISSUE TITLE
CSS refactoring and implementation of 8pt grid

### ISSUE THREAD

**Issue by Ijin08** [grafana/grafana#14549]
Currently the CSS all over the place. To be able to have a consistent design we are going to implement a 8pt grid. We are also going to implement strict use of variables. The variables will be more general than today. We should pixels instead of rems, today we use both.

- [ ] Remove all unused variables
- [ ] Remove all rems.
- [ ] Build a library of universal variables that fulfils our needs

More to come...

**Comment by bulletfactory** [comment]
This is great - I want involved as we make things more consistent, to help find new efficiencies. Looking forward getting this cleaned up!

**Comment by torkelo** [comment]
moved todo to Grafana styling epic #15342
