### ISSUE TITLE
Migrate Singlestat to Gauge

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#14554]
* [x] Thresholds are not working fully
* [x] Move ValueMappings to grafana/ui/components
* [x] Defaults are not being applied (until edit mode is opened)
* [x] Template variables used in prefix/suffix needs to be supported
* [x] $__name in prefix/suffix  (series name) 
* [x] Table data support
* [ ] Singlestat supports sanitized html (line breaks/imgs) in prefix and suffix. To migrate singlestats to gauge without causing breaking changes we might need this. Not sure if it's a good idea to support it. 
* [x] Singlestat drilldown link makes whole panel clickable. Need something similar for this panel. 
* [x] Support embedded/server side rendering mode (related to react panel support so no work needed in gauge panel)
* [ ] Singlestat to Gauge migration

below update from @ryantxu 
In 6.4, I propose we take a step towards removing the Gauge panel from SingleStat.

I think we should:
1. keep any existing panel config working as is
2. remove the option to configure gauge options from editor.html
3. If an panel is already configured with a gauge, we can add a big CTA button that would migrate the panel to Gauge

The one thing that would be lost in this migration is the sparkline overlay.  
-------

If migrating today we have current breaking changes
* [ ] No sparkline 
* [ ] No suffix / prefix in new Gauge panel
   - suffix could be part of the 'format'  (mostly that is what it is used for).  Maybe something like #16038.  No clear path for prefix
* [ ] No support for panel links that make the whole panel clickable 
   - panel links should migrate to DataLink and the gauge should support them
* [ ] Table column option (specifies which column to use for value)
    - gauge should get a 'picker' to select fields out of the DataFrame

Think sparkline I am fine with removing, prefix & suffix also but borderline, will be a bigger breaking change but not a total break. Table column we have to have some migration path to make the panel work. Panel links not making whole panel clickable are also too big a breaking change as it will remove panels activating as drill-down links.

**Comment by peterholmberg** [comment]
Should Singlestat things be in its own epic? Why mix that in the Gauge panel?

**Comment by torkelo** [comment]
not sure what you mean, to fully complete the migration and remove gauge feature from singlestat panel we need to support those features to not break existing dashboards. 

The singlestat features listed above are features the Gauge panel needs.

**Comment by peterholmberg** [comment]
Ok, I might have misunderstood then.

**Comment by peterholmberg** [comment]
Should we add scale text in Gauge, prefix/value/unit/suffix to this epic? Right now you can have ridiculously long text inside a Gauge.

**Comment by torkelo** [comment]
The defaults need to be applied when the data panel loads , think about a dashboard with a simple json and only the panel type specified , should load with gauge defaults applied

**Comment by torkelo** [comment]
Think it should scale automatically based on text length

**Comment by Jordan-sl** [comment]
Is the table data support for singlestat or gauge panels?

**Comment by ryantxu** [comment]
If anyone is working on gauge issues, be sure to check #15925 -- it changes the structure so bar gauge and gauge share much more code.  It also disconnects value formatting from the gauge/bar components

**Comment by piotr-signalfx** [comment]
What about support for data streams in gauge panels?
Right now I get "e.data is undefined" when trying to replace a singlestat panel with a gauge in such a case.
See: https://github.com/grafana/grafana/blob/5e4875086815593599924dfa3c463f7c8b5b77ed/public/app/features/panel/metrics_panel_ctrl.ts#L179

**Comment by ryantxu** [comment]
Check: https://github.com/grafana/grafana/pull/16059

lots to do, but the goal is that all panels will work as expected

**Comment by Dieterbe** [comment]
Not sure what is the right place to put this, but...
IMHO singlestat sparkline is vastly inferior to graph panel.  we should add an option to add a "summary stat" in a graph panel and deprecate the singlestat panel
singlestat lacks so many options to make the sparkline viz actually useful in the majority of cases, options that the graph panel already has. e.g. #13800

**Comment by daenney** [comment]
I don't know if this should be, or is expected to be, part of this, but the aesthetics of singletstat-gauge vs gauge are also very different right now.

![singlestat-vs-gauge](https://user-images.githubusercontent.com/569574/60507748-81b91880-9cd1-11e9-8a24-e6928367308e.png)

It would be nice to have those things unified, same font sizes, outer and inner rings being the same width, the arc reaching the same height etc. It's a bit jarring when you have both next to each other.

**Comment by torkelo** [comment]
can't you make both use the new panel? the new panel has automatic font size handling and tweaked styling. The old singlestat panel is going to be deprecated

**Comment by daenney** [comment]
Sure I can, I just didn't have any reason yet to go in and change all the others b/c singlestat-gauge is enough for 80% of my use cases. But if it's going away I'll do that. I was under the impression it would be sticking around.

**Comment by daenney** [comment]
One thing though, when you swap from singlestat-gauge to gauge you lose the thresholds and the colours you had defined so far. Makes migrating it through the UI rather annoying.

**Comment by daenney** [comment]
Another thing I'm missing on Gauge which I do get with singlestat-gauge is the sparkline.

**Comment by torkelo** [comment]
We are not going to support sparkline in the Gauge panel, makes very little sense to mix them that way, looks pretty bad and it's almost a bug that you can combine them in the current singlestat panel

**Comment by daenney** [comment]
I'd have to disagree. The sparkline is extremely useful for sensor readings. You almost always only care about the current value, like current temperature, humidity or power usage, but it's super handy to be able to see the trend in that same gauge. I can always see it by spawning an extra graph, but it ruins the "is everything OK at a glance" nature of the gauge+sparkline.

**Comment by torkelo** [comment]
That is what the singlestat panel is for, the gauge + sparkline is not supposed to work which is why it looks awful

**Comment by daenney** [comment]
The singelstat-sparkline doesn't convey thresholds, nor how close you are to them, which is something valuable you do get from the gauge. Though it indeed looks a bit crude, it conveys useful information I can't get in any other single pane.

### singlestat spark
![Screenshot_20190706_122305](https://user-images.githubusercontent.com/569574/60754408-28126000-9fe9-11e9-9fe8-24931dec133e.png)

This one is by and large useless. I could enable colouring the value to see the threshold but it really doesn't tell me much. I can't see the thresholds, how close I am to crossing over etc. Doesn't really manage to convey much useful information.

### gauge
![Screenshot_20190706_122456](https://user-images.githubusercontent.com/569574/60754426-627bfd00-9fe9-11e9-83c3-8e0fe5776bb3.png)

This one is much more useful, I can see thresholds, when I'm about to meet them etc. But I can't see a trend of current usage, which is handy. It's less useful for things like temperature or precipitation, but for power usage it's surprisingly nice to have.

### singlestat gauge sparkline
![Screenshot_20190706_122430](https://user-images.githubusercontent.com/569574/60754409-28aaf680-9fe9-11e9-95a6-380237436195.png)

Though visually a bit bonkers, it provides the most useful overview of a sensor, current value, thresholds and trend

**Comment by torkelo** [comment]
We will soon allow you to share data (query results) between panels, so you could setup a graph and gauge from the same query

**Comment by yellowpattern** [comment]
If it was possible to turn of the colored arc then gauge would be ok as a substitute for singlestat.

**Comment by yellowpattern** [comment]
in the enumeration of multiple instances to satisfy variables, it would be nice if there was an option for it to be a panel per output rather than squeezing multiple graphs into a single panel.

I use this for filesystems and some hosts have one, some have 5. The size of the graph for a volume on a host with one is readable, when it is five, it is not. there may need to be some more drawing enhancements to widen panels or something.

**Comment by patricktokeeffe** [comment]
Hi, I came to express my disappointment at SingleStat being deprecated. 😢 I've come to appreciate the particular information density I get:
* easily readable value
* visual context for current value in/out of OK range 
* thumbnail historical trend view

I agree the colored backgrounds are ugly but disagree that spark lines are a "bug". Consider this min/latest/max display for monitoring batteries of a solar array. Sure I could use a separate graph panel but it's unnecessary because spark lines convey enough info. 
![image](https://user-images.githubusercontent.com/1348834/65345859-1d02b100-db90-11e9-8961-37fc0611e164.png)

I understand this ship may have sailed due to backend constraints. Hopefully the Graph panel catches up to the features previously available in SingleStat.

**Comment by gitgia** [comment]
Hi, I found an additional bug in the Singlestat (and Singlestat Math) - panel: if you increase the font size >=50% and have anything but the low line _ in the postfix (even the space) before the text it produces value overlays. 
I need a postfix for a custom unit, because the unit is not on the list.

![image](https://user-images.githubusercontent.com/41324844/67775665-8c0cd880-fa5f-11e9-874a-1afe48bd4e67.png)

**Comment by vanducng** [comment]
> Hi, I came to express my disappointment at SingleStat being deprecated. cry I've come to appreciate the particular information density I get:
> 
>     * easily readable value
> 
>     * visual context for current value in/out of OK range
> 
>     * thumbnail historical trend view
> 
> 
> I agree the colored backgrounds are ugly but disagree that spark lines are a "bug". Consider this min/latest/max display for monitoring batteries of a solar array. Sure I could use a separate graph panel but it's unnecessary because spark lines convey enough info.
> ![image](https://user-images.githubusercontent.com/1348834/65345859-1d02b100-db90-11e9-8961-37fc0611e164.png)
> 
> I understand this ship may have sailed due to backend constraints. Hopefully the Graph panel catches up to the features previously available in SingleStat.

Totally agree.

**Comment by yellowpattern** [comment]
I use spark lines with just the plain text for network interface counters. The current value goes in the middle and underneath you get historical. If I want more detail on the interface counters then I click on the graph and it takes me to another dashboard that provides more detail.

Singlestat is perfect for what it does/represents. It is simple to use, simple to view and powerful in what it represents. Replacing it with a gauge/graph combination seems to be making life more complex for ... what exactly?

**Comment by torkelo** [comment]
We are not removing single stat, it will be replaced with a new and improved stat panel.

Just the gauge mode we are migrating to a standalone gauge panel

**Comment by sbrooke** [comment]
I know it's been several months and as someone else said, that ship has sailed.  I also make use of the old sparklines to better convey the range of a stat.  I have limited space on my dashboard and can't afford to have multiple tiles taking up space for something I used to have in one tile.  I'm going through a rebuild right now and was greatly disappointed to find this feature was removed.  The main reason, it seems, is because the devs decided it doesn't look good.  Sorry, but that's for me to decide.  You shouldn't punish me for having what you've decided is bad taste.
![Screen Shot 2020-03-14 at 9 02 24 AM](https://user-images.githubusercontent.com/11140298/76682420-89f08400-65d2-11ea-9cef-0530b062e7ad.png)

**Comment by Leviathan09** [comment]
I also want the old way back to have a gauge and sparklines in one panel.
I only have a 7" tablet for my small grafana view so there isn't much space and it would be much more nicer to have the stuff all in one panel.
Please bring it back!

**Comment by jrachwal** [comment]
I cannot begin to tell you how disappointing this is.  Maybe you don't think it "looks nice", but it's unbelievably useful.  Having to create yet another chart, takes up valuable screen space that we use on our displays, that we have up for all of our team to see.

You are discounting how valuable the ability to have multiple metrics available in one grouping is to us and many other organizations.

Very disappointed.

**Comment by ryantxu** [comment]
I think a good solution is to move the old behavior to a plugin -- this way that behavior can continue, but not be supported first class.

The main issue with the current single stat panel is that it supports soooooo many options and is super hard to maintain.  Splitting the features into multiple panels makes it more plausible to support this panel.

**Comment by jrachwal** [comment]
That works.  Thank you.

**Comment by lesinigo** [comment]
My use case is that I have more than 90% of my Singlestat panels showing both gauge and sparklines, for the same reasons outlined in comments above. Bigger one being able to give an exact value (for me that's usually the average or the current value) _and_ a rough idea of how it changed in the selected time period. This is great for "birds eye" dashboard and I usually add panel links to more specific dashboards where I have full graphs to drill down on what was displayed on the Singlestat sparklines.

Doing gauge without sparklines or the other way around is not gonna produce a useful dashboard for the users and using two separate panels is wasting too much real estate.

I do understand development and maintenance issues and don't get me wrong I'm super thankful to the Grafana project and all the people involved for this great piece of open source software. But I would have liked for the devs to move the Singlestat panel to an external plugin, ready to be installed, and possibly abandon it to community support if that's the case. This way I would have had a (community supported or completely unsupported) upgrade path instead of just an (upstream supported) features regression.

My current workaround is to stop upgrading Grafana to not get hit by this regression until I will be able to find a way to have the same "information density" on my dashboards. I will be keeping an eye on external/community plugins and/or course corrections of Grafana itself.

**Comment by rvdheij** [comment]
I miss the sparkles, but admit it was for recreational purpose only. I notice that the automatic font size does not work when you come out of edit (they remain the size they were in the bloated panel while editing). Takes a reload of the page or resize of the panel to trigger it.

**Comment by rpelletierrefocus** [comment]
Agreed this was a decision that makes no sense. There was nothing wrong with how the spark lines looked. And if some people did not like it, they did not have to use them. Why the devs would make this decision is beyond me.

**Comment by yellowpattern** [comment]
Devs are often arrogant people that don't care about individual users. What they want to do is all that matters.

**Comment by ryantxu** [comment]
I am very happy to support anyone who wants to maintain the angular singlestat panel as a plugin.

**Comment by wizbowes** [comment]
Another one in favour of the Sparkline.  I've upgrade to 7 but am leaving my panels un-migrated because they are far less functional without the sparkline.  It's such a waste of space to have a gauge and a separate graph - who on earth would want that?  

My use cases are network performance metrics & weather tracking etc.  Both useful to see the current value and the historic performance.

**Comment by scaytrase** [comment]
Same here. We've used a lot's of gauges with sparklines for performance metrics

**Comment by alexppg** [comment]
While I understand for @torkelo to have thought it made sense to drop spark lines (mixing types of visualization might be weird at first glance), it's now obvious there's a lot of people that don't agree and not only see they're useful, but indispensable, as explained in above comments. 

Is there any technical detail that makes it difficult to maintain it? I'd like to understand if there's any other argument that you don't want it to have support for them.

If there's no more argument that personal taste, I'd like you to reconsider this.

**Comment by philomory** [comment]
@mellieA I'm not sure why this issue got the `area/alerting` and `area/alerting-ng` labels? It doesn't seem particularly related to alerting.

**Comment by leeoniya** [comment]
i caught this yesterday in a couple issues i work on and pinged her. we figured out that she accidentally applied the labels to a bunch of issues when trying to only filter by them :(, she's got some cleanup to do :)

**Comment by madeinoz67** [comment]
Just became aware of this now as I was building a new dashboard and wondering why I couldn't find the spark line in my gauge.  

I want to express my disappointment in the removal of the spark lines, IMHO, these are what actually make Grafana...well   Grafana,  Like others have mentioned above, they add the extra time dimension as well as a range dimension to any metric. so 3 information representations for the price of 1 

Without the sparklines this indicator look flat and unimpressive on a dashboard.

**Comment by rvdheij** [comment]
But we have sparkles in the "Stat" visualization. 
![image](https://user-images.githubusercontent.com/11174694/107633221-f69f5300-6c67-11eb-9e6d-7dc7a87b8fdf.png)

**Comment by yellowpattern** [comment]
Does the "Stat" visualisation have all of the other characteristics of "SingleStat"?

**Comment by torkelo** [comment]
yes

**Comment by yellowpattern** [comment]
Which raises the question, why didn't Stat replace SingleStat and something new with less features become what SingleStat is now? Why make life difficult for people that use grafana?

**Comment by ryantxu** [comment]
> why didn't Stat replace SingleStat

Mainly that the Stat panel is no single :)  it shows multiple stats!

**Comment by torkelo** [comment]
>  why didn't Stat replace SingleStat 

It will  (sort of has you cannot create new singlestat panels), but singlestat will go away in v8 

> and something new with less features become what SingleStat is now? Why make life difficult for people that use grafana?

not sure I follow what you mean. How are we making it difficult to use Grafana? the new stat panel has more feature and is easier to use. We sometimes will remove edge case features to make Grafana easier to use and maintain, but SUPER DUPER rarely

**Comment by yellowpattern** [comment]
Looks like I will be staying with version 6.7 for some time then.

I don't have the time to go through all of the dashboards I've written and work out which ones are using SingleStat and are now broken (v7) and simply fail to load/work (v8).

If Stat is the replacement for SingleStat and SingleStat is something new then there should be a tool to automate this.

**Comment by torkelo** [comment]
Of course we will automate this, we would never break existing dashboards, in extreme edge cases dashboards might change ever so slightly as we tweak and change visualizations options but we always try to be as backward compatible as possible

**Comment by rvdheij** [comment]
> Of course we will automate this, we would never break existing dashboards, in extreme edge cases dashboards might change ever so slightly as we tweak and change visualizations options but we always try to be as backward compatible as possible

I think the approach of "existing still works, but can't do new ones" is effective, even though sometimes frustrating when you don't have time to study the new release. I wouldn't like magic conversion unless maybe as an option when you go edit the panel or an extra per-dashboard option. I would be unhappy to see the new version suddenly change all my existing dashboards during startup (and keep me from bringing up the old container image with the same data mounted in).

Actually, my manager was asking last week whether Grafana releases would keep us busy running after things that changed, and I responded that it has been very rare over the past 4 years to see disruptive changes that broke things. Sure, bugs do happen sometimes, but overall you're doing a very good job in keeping things upward compatible. It might make sense to paint an overall strategy on how long deprecated functions are still tested and kept alive.
