### ISSUE TITLE
Grafana UI Library Roadmap

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#14582]
Design goals:

- Promote more reusable components 
- A collection of Form/Option components
- A collection of visualization components that panels use 
- A library of services & utils that transforms data to be usable by visualizations  components 
- Typescript typings published to npm for plugins to use
- Make it easier to develop frontend plugins (external & internal)
- Might be usable as a standalone lib in the future far away

* [x] Getting starting moving basic components & types
* [x] Plugin related types (PanelProps etc)
* [x] Initial work on getting started with storybook 
* [x] Figure out how to handle styled (js styled) components (emotion, styled components)
* [x] Figure out how to do theming, and get theme & theme color variables available to js 
* [x] Publish to npm 
* [x] Initial poc for how to handle documentation (https://github.com/grafana/grafana/pull/15905)
* [x] Public docs published
* [x] Public storybook
* [ ] A good set of base Form and Panel option components
* [x] Plugin boilerplate generator cli tool #15166
