### ISSUE TITLE
React Graph

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#14789]
- [x]  Move react color picker components (components/colorpicker) from app/core/components to @grafana/ui
- [x] Move unit formats (https://github.com/grafana/grafana/pull/14716) 
- [ ] Move Legend components from angular graph component to @grafana/ui/src/visualizations/Legend/ might require type changes from TimeSeries to TimeSeriesVM (new interface imutable type for react panels). will probably need to add unit type to TimeSeriesVM.  We have an option to copy this code as well so the React Graph and angular graph do not share the same legend component. 
- [ ] Need to merge react Graph tooltip PR and copy or move code to @grafana/ui/src/visualizations/GraphTooltip and find a way to integrate it into the React Graph panel

**Comment by dprokop** [comment]
Closing in favor of https://github.com/grafana/grafana/pull/27572
