### ISSUE TITLE
Enhanced Drilldown links

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#15130]
The current panel drilldown link feature is too hard to use and does not adequately solve the “drilldown” use cases it names suggest.  

## Main problems
* It does not allow per series drill down links. For example from a graph legend. 
* Cannot set variables on current dashboard
* Setting variables on another dashboard, while possible, requires undocumented or poorly documented and hard to use raw url params input. Like `var-server=$server`. This Url Params input is very small, can only refer to variables not to query result series names or labels and the user gets no help on what variables are actually available on the target dashboard or current dashboard. 

Providing better & easier ways to filter current dashboard or link to another dashboard with variables preset is a highly requested feature. Example is this feature request to extend the Graph legend to include drilldown links, https://github.com/grafana/grafana/issues/1232 

The current drilldown link feature only adds a panel description tooltip containing the links. The singlestat has special integration and makes the whole singlestat panel clickable. 

# Todo

* [ ] Replace panel links edit UI to just be a URL field and "open in new tab" switch. 
* [x] Make edit field a slate field with syntax highlighting
  * [ ] Create an abstraction & reusable input field with syntax highlighting and variable auto complete?
* [x] Auto compete for built-in variables 
* [x] New built-in variables to be used only in this context (the old checkboxes)
  * [x] $__allVariables
  * [ ] $__timeRange
* [ ] New variables for per series drilldown
  * [x] $__seriesName
  * [ ] $__dataPointTime
* [x] Migration for old options model to url with variables 
* [ ] Check for data point drilldown in graph panel and apply it on data point click
* [ ] Check for series drilldown in graph panel and add legend link icon

**Comment by torkelo** [comment]
So the input mode would look this I think:

```ts

interface DrilldownLink {
  type: 'dashboard' | 'absolute' | 'set variable on current dashboard'; // dropdown or
  uri?: string; // link to dashboard or absolute url (not shown in UI)
  dashboardName: string; // if dashboard link we need to show this
  title: string; // link title / name
  params: DrilldownLinkUrlParam[];
}

interface DrilldownLinkUrlParam {
  type: 'time' | 'all variables' | 'custom url params'| 'set-variable';
  key?: 'string'; // variable name (in case of type = set variable)
  value: string; // value for custom url param input or metric ref or tag name
}

```

One idea, not sure it's a good idea would to model the UI a bit like the series overrides:
![image](https://user-images.githubusercontent.com/10999/54814398-ece55e80-4c8f-11e9-87eb-a07a2c88efa1.png)

So you would have something like:

type: Dashboard, x Dashboard: Dash1, title: Go to server dashboard
Parameters; x include current time range, x set variable: server=$__metricName, x set variable=datasource=$ds1

We would need a way to specify multiple variables and reference either a series name or tag name.

**Comment by ryantxu** [comment]
What about putting the link options on the Field interface?  Something like:
```
export interface FieldLink {
  type: 'dashboard' | 'absolute' | 'set-variable';
  title?: string; // use template variables -- show in tooltip
  uri?: string; // absolute URL
  dashboardId?: string; // if dashboard link we need to show this
  params?: {[key:string]:string};
  includeTime?:boolean; // Add the time range parameters
  includeVars?:boolean; // Add the current vars
}

export interface Field {
  ... all existing stuff
  link?: FieldLink;
}
``` 

It is a bit weird since it is more about the display than the data, but I like that it ties the behavior to each Field configuration and will force us to make a nice interface for specifying the option either from: data, datasource, or panel

should a field have multiple links?  I think one is typically enough.

**Comment by narc-Ontakac2** [comment]
IMHO there should also be a possibility to drill down by clicking on the graph. I am using grafana on apache logs and I frequently miss the option to view details (may be the raw logs) by clicking on the graph to see what has actually happened there.

**Comment by narc-Ontakac2** [comment]
Just wanted to point out that a **very detailed drill down** is highly useful. The world map panel allows html in the geoname string. So I was able to add a drill down link in its little pop up bubbles. This reduces the data to a rather small number of requests and is thereby highly useful. As an I can easily see that the surprisingly high number of requests from Lund in Denmark is only an attempt to exploit wordpress vulnerabilities.

**Comment by savukadoo** [comment]
I would agree with @narc-Ontakac2 as a drill-down should be contextual to the data it is highlighting or showcasing. Classic example of this not working at the moment in the pie chart grafana plugin which has no drill down capability and this really limits the usefulness of the plugin as yu end p having to create another panel just to show the data.

**Comment by holgerbrandl** [comment]
Is there a followup-issue to track the implementation of panel links for other types than series? E.g. it would be great if this could work on barplots as well.

**Comment by rahuljoshi897** [comment]
Do we have any default graph in Grafana that has drill down capability. If we have to achieve this how can we do the same.
