### ISSUE TITLE
Support listing and logout of user's signed in devices/sessions

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#15250]
Given a user X is signed in to Grafana it should be possible for user X to show a list of his/her signed in devices/sessions. From that list: 
* user X should be able to logout from all his/her signed in devices/sessions
* user X should be able to logout from a single signed in device/session, except the current active device/session in use

Given a user Y with Grafana Admin permissions it should be possible for user Y to show a list of any given user's signed in devices/sessions. From that list: 
* user Y should be able to logout from all his/her signed in devices/sessions
* user Y should be able to logout from a single signed in device/session

**Discourse example:**
![image](https://user-images.githubusercontent.com/1668778/52268556-22322900-293c-11e9-803e-c297ec9543a5.png)
**Github example:**
![image](https://user-images.githubusercontent.com/1668778/52268643-57d71200-293c-11e9-9873-6f4eed98ae8d.png)

### Tasks
- [x] Support list and revoke of user auth tokens in HTTP API #15836
- [x] Parse OS, device, browser from useragent stored for each user auth token #16222
- [x] Support list and revoke of user auth tokens in UI #16223
- [ ] Document revoke of user sessions #17723

**Comment by marefr** [comment]
Closed by #15836, #16222, #16223
