### ISSUE TITLE
Grafana styling

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#15342]
- [ ] Model and implement new, limited theme for Grafana 
- [x] Enable TS based theme files to be used in SASS (https://github.com/grafana/grafana/pull/15235, https://github.com/grafana/grafana/pull/15404)
- [x] Enable emotion or styled-components (https://github.com/grafana/grafana/issues/15438)
- [x] Store theme object in app/config Settings instead of relying on `theme.type` checks. May require custom linter not to allow config usage in React files directly.
- [x] Think about introducing `isLight/isDark` on theme interface, as this is sth that we actually care about with current theme usage
- [ ] Implement theme aware version of `getColorFromHexRgbOrName` for easier usage in Angular

# Theme
- [x] New spacing variables 
- [x] Remove all unused variables
- [ ] Remove all rems.
- [ ] Build a library of universal variables that fulfils our needs

**Comment by yesoreyeram** [comment]
I am working on custom theme designer/ theme switcher for grafana with [Boom Theme Panel](https://github.com/yesoreyeram/yesoreyeram-boomtheme-panel). I am not sure how this aligns with the roadmap.  Any feedback appreciated.

@torkelo - What's the plan / Roadmap for custom themes ?
