### ISSUE TITLE
Remove meta & pluginExports from DataSourceApi

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#15475]
Will require something similar to the PanelPlugin type but for data sources. 

* [ ] Create type for config.datasources
* [ ] After data source srv loads a data source set the exports on the config.datasources item
* [ ] Create a function on data source srv to get datasource plugin info (the config.datasource[ds]) instance to get meta info & plugin exports.

Reasons:
* Having pluginExports on DataSourceApi creates a circular dependency that forces DataSourceApi to be defined in same file as PluginExports which is very messy.

 Made a tentative start here: 
https://github.com/grafana/grafana/tree/remove-plugin-exports-from-datasource-api
