### ISSUE TITLE
Self-organization through dashboard-, folder- and team-permissions

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#15590]
By making it possible for editors to own the dashboards, folders, and teams they create we make it possible for self-organizing teams and companies to operate within Grafana. 

## Proposed solutions
- Introduce an ownership concept in Grafana for dashboards, folders, and teams
  - Owners would have permissions equal to an admin for what they create
  - Ownership can be removed by an Org Admin
  - Ownership can be transferred by the owner or an Org Admin
  - (Existing dashboards and) dashboards without an owner will have the same behaviour as before ownership was introduced
- Make it possible for editors to create teams
  - The Owner and Org admin can manage the team (add members, delete it, rename)
  - Teams are visible to Org admin, members and owner

## Tasks
- [x] Feature toggle
- [x] Database changes and migrations scripts?
- [x] Api changes?
- [x] Team guardian
- [x] Move out Server Admin to Side Menu
- [x] Make teams and plugins accessible for Admins and Editors
- [x] A user should be able to see which team she/he is a member of in the profile page
- [x] A user should be able to see which team she/he is a owner of in the profile page
