### ISSUE TITLE
Front-end build performance improvements

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#15936]
We would like to research and improve the dev experience when working with webpack:

- [ ] Bump Webpack and Jest versions
- [ ] Research possible ways to limit the scope of tests being run when modifying single file / test
- [ ] Try out https://github.com/mzgoddard/hard-source-webpack-plugin 
- [ ] See how CircleCI stats can help us tracking improvements impact

**Comment by torkelo** [comment]
Closing this as we have made some progress on this front
