### ISSUE TITLE
Explore UX improvements

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#15996]
The Explore section has a couple of missing features that would make the experience immediately better. 

- [ ] Add Explore Auto-Refresh Options #15192  (wait until the new time picker is complete and used) 
- [x] A way to Refresh Loki Labels in labels dropdown #15402
- [x] Explore: cannot use backward/forward (browser) actions #14301
- [x] Explore: Allow to close left side in split view #15995
- [x] Keep query in the URL #15862
