### ISSUE TITLE
General Frontend Roadmap Q2 2019

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#15990]
This contains a rough roadmap for things we want to do in Q1 to Q2 2019. Not in priority order. 

General frontend roadmap for the next 1-3 months. This does not contain issues relating to Explore yet. It will come, but probably in a separate roadmap issue. 

# Continue / Finish work we started

* [x] New shared time picker #15343
  * [x] Used in Explore
  * [ ] Used in Dashboard #16805
* [x] New Refresh picker 
  * [x] Used in Explore #15192 (PR: #16273)
  * [x] Used in Dashboard #16361
* [ ] Remaining Gauge Panel Issues #14554
  * [ ] Drilldown links support
  * [x] Table data support
  * [ ] Migration for singlestat gauge -> gauge panel 
  * [ ] $__name support
* [x]  Bar Gauge out of alpha
  * [x] Finalize display modes (Simple, gradient, LCD)
  * [x] Refactor code (very poc state now)
  * [x] Solid tests & story book
* [x] Repeat visualization
  * [x] Add series name to repeated Gauge
  * [x] Add series name to repeated Bar Gauge
* [x] JS styling, emotion integration, #14887
* [ ] Dashboard search -> react migration #13397
* [x] Theme variable clean-up & refactor 

# React Panels Remaining issues
* [x] Data Streaming support
* [x] Drilldown links
* [ ] Annotations #17763

# React Data sources
* [x] Simple Query editors [#14749]
* [x] Add query responee & error to react query editors #16233
* [x] Query Editors that support getCollapsedText() #16308
* [x] DataSourcePlugin type that wrap exported components (like ReactPanelPlugin). 
* [x] Support for React Config component #16307

# Chores / Refactor / Lib upgrades
* [x] Remove meta & pluginExports from DataSourceApi #15475
* [x] Improve webpack & jest performance #15936
* [x] Fix all noImplicitAny issues #14714 [dashboard to track progress](https://play.grafana.org/d/VEy5UXjmk/grafana-ci-code-stats?orgId=1&from=now-7d&to=now)
* [ ] Create a window size store/reducer #15403
# RA
* [x] Drilldown links per metric #1232
  * [ ] Option model
  * [ ] UX design #15130
  * [x] Support in graph legend
  * [ ] Support in repeated bar gauge
  * [ ] Support in repeated gauge
* [x] Graphite Query editor breaks queries when editing (using graphite with tags) #15237
* [x] Graphite function parameter is always quoted when using template variables #2078
* [ ] Row expand status in dashboard url #13098
* [ ] Clickable folder in dashboard title #14739

# @grafana/ui lib
seperate roadmap #14582 

* [ ] Docs
* [ ] Forms
* [ ] Graph
* [x] Improved panel props & query editor props
* [x] Improved or unified panel data model  

# Explore
See seperate roadmap issue #15999

# Data sources
* [x]  Elasticsearch v7.x support #15622

**Comment by lpic10** [comment]
> Elasticsearch v7.x support #16538

Shouldn't be #15622 ?

**Comment by fbarl** [comment]
> React Panels Remaining issues

Is there a plan to pass down the _General > Transparent_ boolean to the React panels? It would be nice to be able to control the panel styles based on that value.

![image](https://user-images.githubusercontent.com/1216874/56978408-ad0b7400-6b77-11e9-95a4-f68fcf16bec8.png)

**Comment by torkelo** [comment]
Closing this, as most is completed.
