### ISSUE TITLE
Observability Roadmap

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#15999]
# 6.6 (previous)
- [x] Hover/tooltip for Graph #12000
- [x] Line wrap options #19355

# 6.7 (current)
- [x] Loki query faceting
- [ ] Rich history for Explore

# 7.0 (next)
- [ ] Trace viewer
- [ ] Prototype: Exemplars from Prometheus 
- [ ] Infinite scrolling (#19354 as first step)
- [ ] JSON formatting #18522
- [ ] Explore UI API for plugins

# Beyond
- [ ] Arches: contextual logs/metrics/traces in Grafana
- [ ] Prototype: Continuous profiling integration
- [ ] Prototype: Workbook/notebook/better-history UX
- [ ] Download log results as CSV #15887
- [ ] Multiple graphs per tab
- [ ] Tabbed view for each split section
- [ ] Log context label selection

**Comment by hugohaggmark** [comment]
Should this be included in 6.1 milestone?

**Comment by disfluxly** [comment]
@davkal  - Out of curiosity, is the "Trace Viewer" the internal diagnostics troubleshooting tool identified in https://grafana.com/docs/grafana/v6.5/installation/troubleshooting/#tracing , or is it the additional Explore functionality that we are all impatiently waiting for?

If not, is the latter on the Roadmap anywhere?

**Comment by J0nathan-S** [comment]
What about [#6557](https://github.com/grafana/grafana/issues/6557)? Would appreciate it very much

**Comment by andoks** [comment]
Trace 

> @davkal - Out of curiosity, is the "Trace Viewer" the internal diagnostics troubleshooting tool identified in https://grafana.com/docs/grafana/v6.5/installation/troubleshooting/#tracing , or is it the additional Explore functionality that we are all impatiently waiting for? laughing
> 
> If not, is the latter on the Roadmap anywhere?

I think it might be the latter, based on #23047. But I was unable to find a issue for it, and I'm not particularly familiar with the Grafana project 😅
