### ISSUE TITLE
Support list and revoke of user auth tokens in UI

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#16223]
#15836 implemented support for revoking user auth tokens thru the HTTP API. This is the second part of epic #15250

As a Grafana Admin there are functionality in the HTTP API for:
* Retrieving auth tokens for a user, see http://docs.grafana.org/http_api/admin/#auth-tokens-for-user
* Revoke auth token for user, see http://docs.grafana.org/http_api/admin/#revoke-auth-token-for-user
* Logout a user, see http://docs.grafana.org/http_api/admin/#logout-user

As a logged in user there are functionality in the HTTP API for:
* Retrieve auth tokens of the actual user, see http://docs.grafana.org/http_api/user/#auth-tokens-of-the-actual-user
* Revoke an auth token of the actual user, see http://docs.grafana.org/http_api/user/#revoke-an-auth-token-of-the-actual-user

### Tasks
- [x] UX mockups showing how a Grafana Admin can get a list of "recently used devices", "sessions" or whatever we decide to call it for a user.
- [x] UX mockups showing how Grafana Admin can revoke/delete a "recently used devices", "sessions" or whatever we decide to call it for a user plus logging a user out, i.e. revoking/deleting all "recently used devices", "sessions" for a user.
- [x] UX mockups showing how the currently logged in user a list of "recently used devices", "sessions" or whatever we decide to call it. Example from discourse and github can be found in epic #15250 
- [x] UX mockups showing how the currently logged in user can revoke/delete a "recently used devices", "sessions" or whatever we decide to call it.

**Comment by marefr** [comment]
This new functionality is suggested to be added to the server admin/edit user and user profile pages:

![image](https://user-images.githubusercontent.com/1668778/54993411-4a610e80-4ff4-11e9-9eb0-153785bb48d1.png)

![image](https://user-images.githubusercontent.com/1668778/54993424-4f25c280-4ff4-11e9-8bd7-6036635851af.png)

**Comment by Ijin08** [comment]
Mockups for profile page. One version with sessions section under the preferences tab and one with its own tab:
<img width="838" alt="Screenshot 2019-04-04 at 15 06 13" src="https://user-images.githubusercontent.com/23470681/55558062-8dee0380-56eb-11e9-89eb-fdda7ab3a6c6.png">
<img width="812" alt="Screenshot 2019-04-04 at 15 06 23" src="https://user-images.githubusercontent.com/23470681/55558082-95151180-56eb-11e9-9fd6-86f71d0b9cb6.png">

Mockup for admin users page:
<img width="772" alt="Screenshot 2019-04-04 at 15 07 00" src="https://user-images.githubusercontent.com/23470681/55558106-a2ca9700-56eb-11e9-8cb1-fc4dd71be7e5.png">

**Comment by torkelo** [comment]
@shavonn looks like you made a good start here. We can move forward with this change in angular and migrate it to a react component later.

**Comment by torkelo** [comment]
Can you open a PR?

**Comment by marefr** [comment]
Closed by #17434
