### ISSUE TITLE
Remove/deprecate PhantomJS

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#18083]
Tasks:
- [x] Grafana CLI: Allow installing custom binary plugins: https://github.com/grafana/grafana/pull/17551
- [ ] Packaging of image renderer plugin: https://github.com/grafana/grafana-image-renderer/pull/19
- [ ] Migration path for users upgrading when PhantomJS is removed? Deprecate first and give users time to switch to image renderer plugin and removing PhantomJS in the major/minor release after?
- [ ] Handle case when Grafana doesn't have any image renderer setup
- [ ] Switch docker base image to buster or alpine #18084
- [ ] Blog post
- [ ] Update documentation

**Comment by marefr** [comment]
Closing this in favor of #13802
