### ISSUE TITLE
Add security scan of our docker image to CI

### ISSUE THREAD

**Issue by xlson** [grafana/grafana#18603]
## Background
We have switched the docker image base a couple of times now, mostly to get rid of security vulnerabilities. With the new alpine image (#18468) finished it seems like a great time to set up automated scanning to make sure we stay on top of security issues.

## What needs to happen
Add security scanning of our docker images to CI, [Trivy](https://github.com/knqyf263/trivy) has been suggested as a good option.

## Tasks

- [ ] Run security scan in CI for the master branch (nightly)
- [ ] Run security scan in CI for the latest release branch (nightly)
- [ ] Run security scan in CI for PR:s builds (depends on how long it takes, might not be worth it)

**Comment by DanCech** [comment]
It's fairly easy to add, but does take a few minutes to run.  Here's an example config:
```
  scan_docker_image:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install trivy
          command: |
            apk --no-cache add curl git
            VERSION=$(curl --silent "https://api.github.com/repos/knqyf263/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
            wget https://github.com/knqyf263/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
            tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
            mv trivy /usr/local/bin
      - run:
          name: Scan Docker Image with trivy
          command: |
            trivy --exit-code 1 --quiet \
              --only-update alpine,nvd \
              grafana/grafana:"${CIRCLE_BRANCH}"
```

**Comment by knqyf263** [comment]
It takes a long time just for the first time. Using cache, the second time will be faster.
https://github.com/knqyf263/trivy#circleci

I would like to provide CircleCI Orbs for Trivy.

**Comment by DanCech** [comment]
@knqyf263 the problem with that approach is due to the way that trivy handles cache entries, once written it will never update them.  If you look at the output in https://circleci.com/gh/knqyf263/trivy-ci-test/25 you can see the following.

When loading the cache, it comes from the first build that stored it (in this case build 5):
```
Found a cache from build 5 at vulnerability-db
Size: 301 MB
Cached paths:
  * /root/.cache/trivy
```

When saving the cache it doesn't update it because it already exists:
```
Skipping cache generation, cache already exists for key: vulnerability-db
Found one created at 2019-05-07 13:28:16 +0000 UTC
```

I started with your example but removed the caching stuff because of that issue with how circleci caching works :(

If there is a file in the cache that we can use to determine the revision of the cache it may be possible to use that as a cache "version" by saving the cache at `vulnerability-db-{{ checksum "filename" }}`, then the next call to load `vulnerability-db` will actually load the newest cache key with the prefix `vulnerability-db` so it would get the updated version.  Of course, saving and loading the cache is also not free, so it may not actually save much time.

**Comment by markelog** [comment]
I think it would be cool to have the ability to run it locally as well, like we doing for the [shellcheck](https://github.com/grafana/grafana/blob/master/Makefile#L116). 

Since if CI would signal an error and let say you applied the fix, in order for you verify it you would have to either do the setup of `trivy` yourself on your machine or run the CI with your changes.

Which would be a cumbersome since trivy might fail the build at any point, for like docs changes

**Comment by marefr** [comment]
Can we setup this to only run once a day against master and/or latest release branch?

**Comment by DanCech** [comment]
https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow

**Comment by xlson** [comment]
@marefr That's probably a pretty good idea. Might be a lot better to run this nightly than for each commit. I'll add that to the issue.

**Comment by DanCech** [comment]
Experimenting with caching I came up with:
```
      - save_cache:
          key: vulnerability-db-{{ checksum "/root/.cache/trivy/db/trivy.db" }}
          paths:
            - /root/.cache/trivy
```
That seems to work, but takes about 2 minutes between restoring and saving the cache.  Overall I think it's an improvement over not using the cache, which seems to take 4 minutes to scan without the cache vs 15 seconds to update and scan.

**Comment by knqyf263** [comment]
@DanCech Oh, it's my fault... thank you.  As you mentioned, I would like to improve the time for restoring and saving the cache. 

One idea is to prepare an external server and send a request to the server. Then, you get the result of scanning. However, I think this ways is not good because CI pipelines depends on the external environment.

Anyone have any ideas? Although it's not a bad way to run Trivy nightly, I would like to know if there is any other better way.

**Comment by DanCech** [comment]
One option I've thought about is to build a docker image using docker-in-docker that contains trivy and the vulnerability database ready to go, published nightly or so.  Then in the ci pipeline it would just use that docker image to scan with `--skip-update`.  I haven't had time to experiment with that yet though.

**Comment by marefr** [comment]
#19195 fixed nightly scan of master image so closing this for now.

**Comment by knqyf263** [comment]
I know nightly scan fixes this problem. But the scan speed on the first run was dramatically improved (~ 10 seconds) with v0.2.0, so let me share it just in case.
https://github.com/aquasecurity/trivy/releases/tag/v0.2.0
