### ISSUE TITLE
Deprecate PhantomJS

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#18914]
Tasks:
- [x] Grafana CLI: Allow installing custom binary plugins: https://github.com/grafana/grafana/pull/17551
- [x] Switch docker base image to alpine #18084
- [x] Packaging of image renderer plugin: https://github.com/grafana/grafana-image-renderer/pull/19
- [x] Publishing of image renderer plugin: https://github.com/grafana/grafana-image-renderer/issues/8
- [x] Add deprecation warning in Grafana #18913 
- [x] Update documentation regarding image rendering and PhantomJS deprecated since Grafana v6.4 and alternatives to rendering using grafana image renderer

**Comment by marefr** [comment]
Blog post will happen later. Closing this since completed.
