### ISSUE TITLE
Platform 6.5 Roadmap 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#19427]
Project board: https://github.com/grafana/grafana/projects/14

Not in priority order. For recent work check old roadmap issue around frontend platform & dashboard: #15990 

## Dashboard
* [x] Support lazy like querying of template variables #19858 @hugohaggmark 
* [x] POC: Investigate the best way to communicate between Panels in a Dashboard #19432 @hugohaggmark 

## UI Components & Form Styles
* [x] Tooltip for @grafana/ui Graph component #20046  @dprokop 
* [x] **New** Button components (form styles) #17871 @peterholmberg 
* [x] Drawer component( to be used or upcoming panel inspect feature) #20078 @peterholmberg 

## React Migration  / Tech upgrades
* [x] Migrate DataSource HTTP Settings to React #19452 @peterholmberg @dprokop 
* [x]  A Metric Segment like component written in react to be used in query editors #19436
* [x] Modal in React #19369 @kaydelaney 
* [x] Server admin / settings no in React #19594 @kaydelaney 
* [x] Upgrade angularjs to 1.6.9  (security release) #19849 @peterholmberg 

## Quick and Small / Clean-ups / Small refactors 
* [x] Notice to browsers that are not fully supported (IE11, old firefox) #17453

---
## Deferred work
* **New** Input & Form components to support transition to new form style
* New singlestat panel in beta
* Meta analytics (frontend stat collection around queries, load times, refresh rates, errors)  
* Demo / Style guide page to test new form styles
* Template variable dropdowns (Dashboard submenu) 
* Experiments (R & D) with new graphing libraries and ways we can build a more generic & composable Chart component in @grafana/ui

**Comment by dprokop** [comment]
> Demo / Style guide page (in Grafana) to test them.

@torkelo maybe in storybook instead? Thats a good incentive to start deploying Storybook finally

**Comment by torkelo** [comment]
Think it's better to have it in Grafana so we can see real forms look like in context but not sure,
