### ISSUE TITLE
Backend plugins architecture and SDK

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#19667]
**Backend plugin architecture:**

**SDK:**
We want to make it easy for consumers/plugin developers to write a backend plugin, using Go as programming language to begin with, and an SDK should help with that. In addition, the SDK can abstract away things that a plugin developer shouldn't need to care about.

**Tasks:**
- [x] Bi-directional support for backend plugins https://github.com/grafana/grafana/issues/19667#issue-503428396
- [x] Support loading new version of backend plugin #19683
- [x] New HTTP endpoint for backend plugins #19669
- [x] Refactor start and manage of backend plugin processes #20053
- [x] Implement support for resources #21512 https://github.com/grafana/grafana-plugin-sdk-go/issues/34
- [x] Add logger abstraction https://github.com/grafana/grafana-plugin-sdk-go/issues/35
- [x] Pass user information #12043 https://github.com/grafana/grafana-plugin-sdk-go/pull/56
- [x] Streaming resource response #22569 https://github.com/grafana/grafana-plugin-sdk-go/pull/67
- [x] Add support for checking plugin config health #21519 https://github.com/grafana/grafana-plugin-sdk-go/issues/38
- [x] Protocol/protobuf naming https://github.com/grafana/grafana-plugin-sdk-go/issues/72
- [x] backend.proto JSON is incohesive https://github.com/grafana/grafana-plugin-sdk-go/issues/70
- [x] Don't merge plugin metrics with Grafana's metrics endpoint #22814
- [x] Mute logged warning about unknown service plugin.GRPCStdio #23461
- [ ] Refactor new datasource query endpoint #21510 https://github.com/grafana/grafana-plugin-sdk-go/issues/75

**Nice to have, but not required:**
- [x] Add support for receiving global configuration properties from Grafana #21515 
- [ ] Add support for validating plugin config #21516 https://github.com/grafana/grafana-plugin-sdk-go/issues/37
- [ ] Back-end plugins: Plugins failing to start should be unregistered #22603

Ref #6841

**Comment by bergquist** [comment]
:man_dancing:
