### ISSUE TITLE
New forms design

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#19855]
## Migrating forms to new design

Figma designs: https://www.figma.com/file/LTMA7BJeMLz7xv8E9TJq1J/Form-styles

### Scenario 1: implementing new design in currently available components, i.e. Input, Switch
Could possibly work, but will most probably break look and feel of some of the forms, i.e. Stackdriver's annotation query editor is a mixture of legacy HTML and grafana-ui form components. Also, i.e. switch relies on gf-form class name which will most probably have some consequences, as well as it has label coded into the component, which I think should be composed in the forms rather than implemented in the form element itself.

### Scenario 2: implement new class names with Emotion and next-gen form components
This has two advantages that makes me feel this is the correct way forward
1. Next-gen form elements would be implemented independently from current Input, Switch, etc components and exposed from grafana-ui via `Forms` namespace. 
```tsx
import { Forms } from '@grafana/ui';

// in render
return <Forms.Input {...} />
```

Later on, we could deprecate and remove current form elements from grafana-ui.

Each of these next-gen comonents would have their own css implemented using Emotion, that would be also available from Angular directives, see below.

2. New component's class names could be reused in angular templates. To achieve that we could export `getFormStyles` function from grafana-ui that would expose all of the new class names created when implementing new designs. The class names would be used to style primitives, meaning i.e. input, textarea, label, wrappers etc.

General draft of the returned class names:
```ts
const classNames = {
  form: string, // general form styles, i.e. spacing at the bottom
  fieldset: string, // spacing between fieldsets only
  legend: string, // caption for fieldset
  label: string, // form item's label
  descriptin: string, // form item's description/hint
  input: string,
  inputsGroup: string, // i.e. used for radio buttons, input with button suffix
  inputWithAffix: string, // wrapper for inputs with i.e. icons,
  ...
}

// Above object would be composed from component specific style factories:
const getFormStyles = () => ({
  ...getFormStyles(formProps?),
  ...getInputStyles(inputProps?),
})
```

And then the `getFormStyles` function could be attached to directive's scope and class names applied in the template:

```ts
// directive controller
...
import { Form } from '@grafana/ui';

$scope.getStyles = () => Form.getFormStyles(getCurrentTheme());
...
```

```html
<!-- Angular directive template -->
<input class="{{getFormStyles().input}}"/>
```
The drawback is that in angular plugins the plugin developer would have to know what's the underlying markup to apply the styles correctly. Maybe, to make migrations easier for angular plugins developers, we could also create directives for next-gen form elements so that they could be used without knowing the required markup:

i.e.
```html
<gui-input .../>
<gui-label .../>
<gui-legend .../>
```

But then Angular's bindig magic (`ng-model`) will not work and will have to be implemented in the controller as i.e. input's `onChange` handler. Hence, the directive approach is probably not the best one. 

I think exposing the new class names should be sufficient. It will require some effort from the external devs perspective to migrate to new markup, but we could communicate that until let's say 7.0 the legacy class names `gf-...`  will be available, so that they will have time to migrate to the new styles.

---
### TODO

The following tasks should be implemented as a separate PRs:

- [x] Introduce new colors to the GrafanaTheme (https://github.com/grafana/grafana/pull/19874)
  - [x] Add new primitives according to the design
  - [x] Add functional theme variables 
- [x] Introduce new spacing variables to GrafanaTheme that are form specific (https://github.com/grafana/grafana/pull/19875)
- [x] Align new Button styles with the design
  - [x] Implement Primary, Secondary and Destructive buttons (https://github.com/grafana/grafana/pull/19973)
  - [ ] Implement Buttons group component
- [x] Implement form's typographic elements (https://github.com/grafana/grafana/pull/19879)
  - [x] `Legend` - fieldset's header. Naming it `Legend` to aligned with HTML form element
  - [x] `Label`
  - [x] `Description`
  - [x] `ValidationMessage`
- [x] Implement `Forms.Input` UI component  (#20159) 
  - [x] Support input's prefix (i.e. Icon)
  - [x] Support input's suffix (i.e. Loading indicator)
  - [x] Support Input's groups, i.e. [Input][Button]
- [x] Implement `Forms.Textarea` UI component (#20307)
- [x] Implement `Forms.Select` UI component (#21092)
  - [x] Is there a way to reuse current `Select` component?
- [x] Implement `Forms.Radio` UI component
- [x] Implement `Forms.Checkbox` UI component (#20701)
- [x] Implement `Forms.Switch` UI component (#20470)
- [x] Implement `Form.Field` component (#20482)
  - [x] Accepts label, description and form input as props
  - [x] Accepts `horizontal: boolean` prop to display elements in a horizontal layout (i.e. Switch with label on the left)

**Comment by torkelo** [comment]
Think Scenario 2 definitely! and I really like your idea of making the emotion classes available in angular html templates. 

I think the markup should be pretty simple so should be ok, but for components we could as you suggest look at wrapping in angular directives to make the migration as easy and quick as possible.

**Comment by peterholmberg** [comment]
Can only agree that Scenario 2 is the way forward. Looking forward to isolated style with emotion. The idea with directives is brilliant, but I think we should add some sort of deprecation warning pretty early after we go live with the new Form styles.

**Comment by dprokop** [comment]
>  but I think we should add some sort of deprecation warning pretty early after we go live with the new Form styles

Yeah, problem is it's quite tricky as we can't hook into css class names usage:D Only thing we can do is to communicate to our community that we are deprecating the old class names and provide a migration guide to the new styles. For those using grafana-toolkit we could probably add a cunstom linter that shows a warning in the console if we detect usage of `gf-*` classnames

**Comment by hugohaggmark** [comment]
Awesome work, I agree with everyone here that Scenario 2 is the way forward and I like the Forms namespace idea.

**Comment by jschill** [comment]
Keep up the good work guys! 👏

**Comment by roidelapluie** [comment]
As we go to this point, I think setting up a custom logo ( or complete theme ) would be awesome.

**Comment by atymchuk** [comment]
@dprokop Hey, the link to Figma designs is broken. Curious to take a look at it.

**Comment by dprokop** [comment]
@atymchuk you should be able to see the Figma file now

**Comment by dprokop** [comment]
Closing as this can be considered done. We can improve the new forms going forward
