### ISSUE TITLE
Docs: Improve Installation documentation

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#19893]
The Installation section of the Grafana documentation has several potential areas of improvement.

- [ ] All sections need to be reviewed for grammar, formatting, and consistency.
- [ ] Add an Overview section to explain what the Installation topics cover, what they do not cover, and whether some methods are more recommended than others.
- [ ] Convert prose to numbered steps to make the information easier to understand.
- [ ] Reconcile content that is duplicated in Getting Started and the Grafana installation pages. Add links as appropriate.
- [ ] Clarify which instructions are for developer install and which are for regular install.
- [ ] Move information that is not related to installing Grafana into Getting Started. This might include Logging in for the First Time, Configuration, and Starting Grafana.
- [ ] Possibly merge the Installation and Getting Started sections.

Related issues: 
#17183
#16474
#19297 
#19298 

From Slack discussions:
speaking of installation guides, I have a suggestion, not sure if you have already plans for this, but; the different "options" should be more clearly visible, this is especially noticeable on the Installing using Docker ( https://grafana.com/docs/installation/docker/ ), on a quick look it's not clear which sections are "required", and which sections are mutually exclusive. I think this may even "scare" some new users as it looks like there are many steps to do to just get Grafana installed, when in reality there are just a few with the remaining being optional configuration and additional info.

For example, the `Grafana container with persistent storage (recommended)` and `Grafana container using bind mounts`, you have to read through both of them or at least be relatively experienced in working with Docker to realize you only need one of them.

Perhaps something like numbering the "required steps" with the mutually exclusive "options" with a letter (like 3a and 3b), or use more distinct subheadings. Perhaps something loosely like (from "Installing on Ubuntu / Debian"):
```
Install the package
    DEB Package
    APT Repository
Start the server
    via init.d service
    via systemd
```
and so on.

The ordering of some the sections seem to be a bit inconsistent. As I have been using Grafana for a long long time already, I'm blind to most of these, but I can still spot some obvious ones, such as the config related sections in the "Installing using Docker":
- The document starts with a minimal snippet for running the official container (really useful for experienced docker users)
- Next up is how to pass configuration to the container
- Then comes sections regarding running different versions or even building some
- Then there's again config related things ("Configuring AWS Credentials for CloudWatch Support")
- After that comes again sections regarding running the container (with different data persistence possibilities, as mentioned earlier)

I also think that some sections should be elsewhere, for example I think the "Migration from a previous version of the docker container to 5.1 or later" (and some sections below it) should probably be placed in the Docker section of "Installation -> Upgrading", rather than being under "Installation -> Installing using Docker" where it currently is. Especially since users looking to upgrade their Docker setups will more likely look into the Upgrading section only, and not check out the actual installation as they have Grafana installed already
