### ISSUE TITLE
Dashboard: Migrate Templating to React/Redux

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#19896]
# Migrating Template Variables to React/Redux - an Epic voyage
## Background
We (the Platform Squad) got some feedback this week that we've made big refactors and those are hard to understand and
reason about for contributors both internally and externally.

As a way to clarify what we're trying to accomplish by migrating Template Variables to React/Redux I'm gonna try to
document right here our decisions, plans and failures. This is the first time I've done this so be kind.

## The Mission
As most of you know we're trying to migrate our Angular code base to React. One large piece of complex code left is the
Template Variable system and components. We want to migrate the Template Variable system not just because we're migrating
but because we're thinking about introducing new features like `Application wide template variables`. We think features
like this could be more easily solved using React/Redux.

## The Challenge
We've a couple of challenges but the main challenge is that we have a mutable data structure today with Angular components
accessing and changing data more or less directly.

![image](https://user-images.githubusercontent.com/562238/68835337-16884580-06b8-11ea-87f1-1f0abd7a6c0a.png)

Our goal is to have an decoupled architecture where changes in UI results in actions being dispatched and changes an
immutable state.

![image](https://user-images.githubusercontent.com/562238/68835391-3b7cb880-06b8-11ea-870e-182ef529dc4e.png)

### First iteration
The first attempt to move closer to our goal failed miserably. I tried to split the core of the Templating system `VariableSrv`
to various Thunks. The thunks worked but the state was still shared between Redux and Angular which lead to the UI not
updating correctly.

### Second iteration
With the first failure in mind I've come up with a different approach in #20155. The purpose of #20155 is to move the
variable state into Redux using `getters` and `setters` in each `Variable` class changing as little as possible to
existing logic and core classes like `VariableSrv`. The thinking with this is to trick Angular to get/set state from/in
redux.

Unfortunately the Angular component that manages the CRUD of Variables `VariableEditorCtrl` uses a `"temporary"` variable
that is used when the user creates a new variable and when you change the type of variable. As I don't want to change the
existing solution to much I decided to create a `temporary` representation in each Variable class. My thinking is that
this added complexity will be removed when we migrate `VariableEditorCtrl` to React.

### e2e-tests
As this is such a complex part of Grafana we're going to cover this with e2e-tests before each moment so that we can be
sure that we're not introducing breaking changes.

### Hypothesis right now moving forward
- [x] Introduce better typings
- [ ] Cover template Variable CRUD with e2e-tests
- [x] Create a pattern to have Variables in Redux but at the same time continue with Angular Components (#20155)
- [x] Migrate VariableEditorCtrl to React
- [x] Cover Query template Variable usage with e2e-tests
- [x] Migrate ValueSelectDropdownCtrl component to React
- [ ] Cover AdHocFilter template Variable usage with e2e-tests
- [ ] Migrate AdHocFiltersCtrl to React
- [ ] Cover the rest of template variable usage with e2e-tests
- [ ] Migrate the rest of template variable components to React
- [ ] Migrate VariableSrv to Redux and Thunks, change TemplateSrv/Dashboard to use templating in Redux
