### ISSUE TITLE
E2E tests Roadmap

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#20583]
## Background
As our company grows our need for e2e tests have also grown. Today we're using a home grown solution built on top of Puppeteer for our e2e tests. We as a platform squad want to supply an easy away for internal and external contributors to add and run high quality e2e tests as part of their QA process and at the same time limit the amount of maintenance and documentation for our team. 
We've evaluated a couple of frameworks but now we've chosen Cypress for a POC.

## Mission
Our mission is to create a POC with Cypress and keeping our API on top of that to a minimal. After the POC we'll make the decision if we're continuing with Cypress or not and split out all e2e related code to it's own grafana package. Finally we'll document and provide guides for using e2e in Grafana.

- [x] POC of using Cypress as test runner for our E2E (#20753)
- [x] Create a separate, @grafana/e2e package that defines an API for E2E tests and common test scenarios(i.e. ensure login). (#20753)
- [x] Document the E2E API (#20962)
