### ISSUE TITLE
New Stat Panel Epic

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#20649]
Details some of the remaining work needed for the new singlestat (Stat panel) in order to bring it out of alpha state. 

# For beta (out of alpha) 

- [x] Rename panel to StatPanel
- [x] Have centered value text layout option (or auto behavior) (needs more detail) to make it look like the current singlestat panel. 
- [x] Improved font size handling based on all series, and measured width of the text (see BarGauge for reference) 
- [x] Parse value and separate unit from the number and lower font size of the unit
- [x] Some level of test coverage & refactoring
- [x] New panel icon (not the same as old singlestat)
- [x] Make sure field min / max is used
- [x] When min / max are empty they should be auto calculated based on data (data min / data max)
- [x] Fix light theme when color mode is set to value
- [ ] Add grid VizRepeater orientation that layout items in grid instead of flex colum & row
- [x] Improve "center" justify option.   

# Stretch goals & future features 
- [x] highlight last point if showing last (in calc)
- [ ] Introduce sub title field option (default to empty, but can be same expression as title for example ${__calc})
- [ ] Add trend part (up/down array & percentage)
- [ ] Add text to thresholds (needs UX design)
- [ ] Add icon to thresholds (needs UX design)

**Comment by roidelapluie** [comment]
Stat: Color is green when value is null

**What happened**:

I test the stat panel.

When the last metric is null, the background is green, even if threshold is set to blue.

![stat2](https://user-images.githubusercontent.com/291750/70534466-680edd80-1b5b-11ea-9858-8cc02682680b.png)


**What you expected to happen**:

Background is blue.

**How to reproduce it (as minimally and precisely as possible)**:

Set a query with last value null and threshold to green


**Environment**:
- Grafana version: Grafana v6.6.0-pre (0e4850f203)
- Data source type & version: stat 6.6.0-beta

**Comment by roidelapluie** [comment]
Custom threshold can not be imported from disk


**What happened**:

I try the stat panel, and when I write a threshold to a file on disk, with the following config:

```
{
  "datasource": "Prometheus",
  "gridPos": {
    "h": 6,
    "w": 12,
    "x": 12,
    "y": 0
  },
  "id": 2,
  "options": {
    "graphMode": "area",
    "colorMode": "background",
    "justifyMode": "auto",
    "fieldOptions": {
      "values": false,
      "calcs": [
        "last"
      ],
      "defaults": {
        "min": 0,
        "max": 100,
        "thresholds": [
          {
            "color": "dark-blue",
            "value": null
          }
        ],
        "mappings": [],
        "unit": "locale"
      },
      "override": {}
    },
    "orientation": "vertical"
  },
  "pluginVersion": "6.6.0-pre",
  "targets": [
    {
      "expr": "count(up{env=\"prod\"}) by(job)",
      "legendFormat": "{{status}}",
      "refId": "A"
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "",
  "type": "stat"
}
```


then

```
        "thresholds": [
          {
            "color": "dark-blue",
            "value": null
          }
```

is back to the default value in the dashboard (green+red)

**What you expected to happen**:

threshold is kept while re-imported



**Environment**:
- Grafana version: Grafana v6.6.0-pre (0e4850f203)
- Data source type & version: state 6.6.0-pre

**Comment by roidelapluie** [comment]
Dynamic height



**What would you like to be added**:

Related to #20649 

When min-max are autocomputed, I think it would be great to have an extra option:

- Align stats min/high

That way we can actually compare them by height.

Current output:
![stat](https://user-images.githubusercontent.com/291750/70532184-d309e580-1b56-11ea-9435-9b93bad1c2b9.png)

Expected output:

Prod is higher than the other ones

**Comment by torkelo** [comment]
Not sure what you mean dynamic height, align by height, they looks the same / aligned to me.

**Comment by roidelapluie** [comment]
I mean aligning the min and the max, sorry

**Comment by roidelapluie** [comment]
Dynamic height of the "graph line"
