### ISSUE TITLE
Declarative forms with json-schema

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#20657]
With new form components we want to introduce a simpler way of building forms in Grafana. There has already been some research work done around this topic in https://github.com/grafana/grafana/pull/16773. As an alternative and highly customisable solution fo building forms we want to experiment with https://react-jsonschema-form.readthedocs.io/en/latest/ . 

### TODO:

- [ ] How can we replace react-jsonchema-form built-in components with the [newly created Form components](https://github.com/grafana/grafana/issues/19855)? (https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/)
- [ ] Fluent API for defining form's schema so that we don't have to define complex json schemas for each form
- [ ] Where should the UI schema definition belong and what kind of components should it cover?
  - [ ] Experiment with Stats picker as a custom ui form widget built with 
  - [ ] Do wen need the schema to be extendable by plugin developers?
- [ ] Experiment with react-jsonschema-form usage in one of the configuration pages. Serves Admin's user edit(http://localhost:3000/admin/users/edit/1) or Organisation preferences(http://localhost:3000/org) are good candidates as they cover basic UI elements for forms (inputs, selects)

**Comment by ryantxu** [comment]
@dprokop -- is this issue still valid?  I think we have a pretty clear path forward with our bespoke options and editors :)

**Comment by dprokop** [comment]
Nope, closing
