### ISSUE TITLE
@grafana/* packages documentation

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#20656]
# This is an Epic issue for work around @grafana/* packages documentation

## Background:
We are currently working on making it easier to build plugins and extending Grafana with new amazing functionality by introducing the new @grafana/* packages. At the same time as we are releasing the first stable version of those packages we need to have some good documentation that describes the different parts of the packages and how to consume them.

The goal is to have a documentation up and running in the end of April 2020. Hopefully we have something to start iterating from earlier than that.

Currently we have found a really good solution for our design/component library that is in place for most of our newly created UI components. This is something that we will keep: [storybook.js](https://storybook.js.org/)

## What we want to achieve
We would like to have a documentation that makes it easy for developers to understand how to use the @grafana/* packages when developing plugins for Grafana. It should be publicly available as a web. _(Will update this part more when we/I have a better picture of what we are aiming for)._

## Challenges
Find a solution that..

* ...is easy to keep up to date.
* ...can be released along side the Grafana releases.
* ...works for both UI and pure typescript APIs.
* ...have support to mark parts of the APIs as deprecated, stable etc.

## Hypothesis
We are planning on doing the following setup:
* Use [TSDoc](https://github.com/microsoft/tsdoc) to document our code in the @grfana/* packages.
* Use [api-extractor](https://api-extractor.com/) to extract the API documentation meta data.
* Extend the [api-documenter](https://api-extractor.com/pages/setup/custom_docs/) to be able to output markdown in a [Hugo](https://gohugo.io/) friendly format so we can include it along side with our existing documentation.
* Storybook will be used for the UI Library (not sure how to host that one yet)

### TODO:
- [x] Set a plan/hypothesis on how to approach solve this.
- [x] Do a first extraction of all the packages and then do a demo.
- [x] Give some example on how we can use the TSDoc to our advantage.
- [x] Get a MVP version of the API-documenter in place.
- [x] ~~Write reference documentation used as example.~~
- [x] Setup so the generated documentation is integrated in our current build pipeline. 
- [x] Add step for running API documentation generation in release guide lines.

Design doc: https://docs.google.com/document/d/13mkx7p-0zXzSVGmHPIUpjbyJ6QoDq4hk5fRqn7QUkRM/edit#

**Comment by dehrax** [comment]
I've used Netlify for deploying smaller projects, and it is very hassle free. Literally just wite the build command in Netlify and you're good to go.

https://www.learnstorybook.com/intro-to-storybook/react/en/deploy/

**Comment by dprokop** [comment]
@mckn would be cool to do some quick POC with https://typedoc.org/ or https://api-extractor.com/ and see if we can get some quick wins there

**Comment by mckn** [comment]
> @mckn would be cool to do some quick POC with https://typedoc.org/ or https://api-extractor.com/ and see if we can get some quick wins there

Totally agree! But thinks it might be a parallell process as we check some examples on how other does it.

**Comment by mckn** [comment]
I am a big fan of the [react.js](https://reactjs.org/docs/react-api.html) documentation. It is easy to follow, have a good amount of text and some examples.

**Comment by mckn** [comment]
Adding tsdoc comments along side the code will be displayed in VSCode in the following way:

![vscode](https://i.imgur.com/PgWJX2k.png)
