### ISSUE TITLE
Table Panel Epic 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#20709]
- [x] Refactor current component to use the newer [react-window](https://github.com/bvaughn/react-window) 
- [x] Move current use of AutoSizer to https://npmjs.com/package/react-virtualized-auto-sizer 
- [x] Use tables component in the inspect drawer (https://github.com/grafana/grafana/issues/20710)
- [x] Refactor Explore so that it does not use TableModel but DataFrame instead. Then look at how we can remove the current table component there and use this new table component. 
- [x] Field hiding & ordering in panel settings #23135
  - [x] Use transformations API to apply field ordering/hiding 
  - [x] ~~What should be the model (maybe `Record<number>`) for storing order and where should it me stored (`PanelModel` property)~~
  - [x] ~~Ability of field reordering should be an opt-in feature (needs `PanelPlugin` API update to enable this)~~
  - [x] ~~Field reordering should be part of panel options sidebar~~
  - [x] UI for this should be a drag and drop list of all the fields for easy reorder
- [x] Support data links (only check first data link), and turn value into a link/anchor  https://github.com/grafana/grafana/pull/23590 @dprokop 
- [x] Support color value mode (we only have colored background now) #23427 
- [x] Add alignment option (left, center, right) #23389
- [x] Bump react-table version to the latest one #23247 
- [x] Horizontal scrolling
- [x] Resize columns https://github.com/grafana/grafana/pull/23365 (not working 100% on Windows) 
- [x] Store / remember table column sizes in options (field overrides)
- [x] Use field config title for panel column header

###Bugs: 
- [x] Cannot drag vertical scroll with the mouse because the overlay scrollbar is over the native scrollbar 

### Improvements vs Angular Table:
- [x] Prevent panel scroll when scrolling dashboard https://github.com/grafana/grafana/issues/21324

### Backlog
- Features overview/test dashboard https://github.com/grafana/grafana/issues/23904
- Persist sort order of columns
- Displaying sparkline in the table cell

Design doc: https://docs.google.com/document/d/1-Ys5XDGi6JkkxoqQJ604hHva3QT1f2PUQ-OZ3X1D2Qc/edit?usp=sharing
