### ISSUE TITLE
Inspect Drawer Epic

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#20710]
Consistent view for:
 * error details
 * response data (as table) -> download as CSV
 * request structure 
 * response metadata, and optionally allow DataSource to render it 
 * timing info (network, data processing & rendering) 
 * submit a ticket (with data) to grafana

Design doc: https://docs.google.com/document/d/1TF258ZOhaCv6pFfGueWvMT4d1wDvTS8My-SsUevdtyk/edit?usp=sharing]]

### TODO (this is work in progress)
- [x] Panel JSON tab
- [ ] ~~Display request-response and request separately (maybe as tabs? - needs UX work)~~
- [x] Display Response data as table
- [x] Stats display
  - [ ] Render times
  - [ ] Query times
  - [ ] Derive stats from the DataFrames
- [ ] UX Design update
- [ ] Transformations https://github.com/grafana/grafana/pull/23598 @peterholmberg  @torkelo 
  - [x] https://github.com/grafana/grafana/issues/21658
- [x] Meta data
- [x] Render Inspect in new Drawer component rather than  Modal
- [x] Display panel data's data frame as a Table
- [x] Migrate to react-virtualized-auto-sizer (https://github.com/grafana/grafana/issues/21409) #21511
- [x] Use auto sizer in inspecting drawer to size the table component #21511
- [x] Display query error in inspect drawer
- [x] Enable data download as CSV

**Comment by Dieterbe** [comment]
Not sure if this is the right place, but if a datasource (e.g. metrictank) returns a traceid in the response headers, it'd be nice if this traceid could be seen in the details of the panel, or even better, if it generates a link to jaeger to go straight to the trace corresponding to the panel in question.

**Comment by dprokop** [comment]
@torkelo added some actionable todos to this Epic. 

When it comes to timing info, you mean thinks like ie. time of query execution based on start/end timestamps in DataQueryRequest API? The data processing I assume creating dataframe, applying transformations etc. 

> response metadata, and optionally allow DataSource to render it

What do you mean by `allow DataSource render it`?

**Comment by dprokop** [comment]
Regarding Request/Response structure, I think we just need to show respective JSON parts form the XHR response, pretty much what we currently do with Query inspector. Or do you mean responses per targets?

**Comment by torkelo** [comment]
I mean the same as what we show in query inspector

**Comment by torkelo** [comment]
Basic (starting point) design idea for the inspect drawer 

![image](https://user-images.githubusercontent.com/10999/69969380-9d447b80-151c-11ea-86d4-779244d7aa8b.png)

**Comment by marefr** [comment]
Nice! Is the idea that you could see both the raw request/response and the data sent to panel (data frames) before being rendered? I would like to see that anyway. 

Possible to add back possible errors like in the old error modal, for example if some client error occur in "panel code"?

**Comment by torkelo** [comment]
@marefr yes, the idea is to be able to view raw data in tables, simple transforms (joins) and export to CSV (to replace the current export to CSV that table and graph panel implement and have that exist for all panels automatically). 

We can show js errors here as well possibly.
