### ISSUE TITLE
Platform Roadmap (6.6)

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#20740]
Project board: https://github.com/grafana/grafana/projects/14

Not in priority order. For recent work check old roadmap issues, #19427 and #15990

---

### Components & UI
- [x] Continue work with new form designs [Epic](https://github.com/grafana/grafana/issues/19855) 
- [x] POC of using react-json-schema as a solution for declarative forms [Epic](https://github.com/grafana/grafana/issues/20657)
- [x] New TimePicker UI (#17802)

### Visualisations
- [x] New single stat panel beta [Epic](https://github.com/grafana/grafana/issues/20649)
- [x] Custom units https://github.com/grafana/grafana/pull/20763´
- [x] ValueFormat structure that seperates unit prefix/suffix   https://github.com/grafana/grafana/pull/20763
- [x] Automatic font size alignment and max utilization 

### Migrations
- [x] Migrate Graphite and OpenTSDB configs to React [Epic](#19899)
  - [x] Graphite config editor
  - [x] OpenTSDB config editor

### [E2E tests](https://github.com/grafana/grafana/issues/20583)
- [x] POC of using Cypress as test runner for our E2E
- [x]  Create a separate, @grafana/e2e package that defines an API for E2E tests and common test scenarios(i.e. ensure login).
- [x] Document the E2E API

### New panel edit 
The work for new panel edit experience will be primarily focused around UX research and planing the architecture 
- [x] POC for UI and code architecture for new edit sidebar (https://github.com/grafana/grafana/pull/21097)

### Refactor 
- [ ] ~~Refactor GraphWithLegend component to follow architecture proposed with new Tooltip [issue todo]~~

### Packages
- [x] (ABANDONED) Organise packages exports into namespaces https://github.com/grafana/grafana/issues/20151
- [ ] ~~POC of using Storybook as documentation utilities and functions from @grafana/ui,runtime and data  [Epic[(https://github.com/grafana/grafana/issues/20656)~~

## Backend

Backlog board: https://github.com/grafana/grafana/projects/15
Project board: https://github.com/grafana/grafana/projects/23

---

### Backend Plugins (target Grafana v7.0)
- [ ] Backend plugins architecture and SDK #19667

## Deferred work
- Table Panel migration [Epic](https://github.com/grafana/grafana/issues/20709)
- Continue work on template variables migration to Redux [Epic](https://github.com/grafana/grafana/issues/19896)
- Replace AngularJS $http service with fetch https://github.com/grafana/grafana/issues/18049
- Panel inspect mode [Epic](https://github.com/grafana/grafana/issues/20710)
- Migrate some of the admin forms to the new design
