### ISSUE TITLE
Backend Plugins: Health checks and monitoring

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#20980]
When running Grafana and using backend plugins I need tools and diagnostics to be able to monitor and analyze the health of a certain backend plugin process.

Possible areas to consider:
- [ ] pprof profiling support
- [x] health check of plugin process
- [x] metrics #20984,  https://github.com/grafana/grafana-plugin-sdk-go/issues/28
- [ ] tracing

Ref #6841
