### ISSUE TITLE
Angular migration: pages & views

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#21484]
Mark | Description
-- | --
🏃 | work in progress

## Angular pages left to migrate to React

- [x] Dashboard import (http://localhost:3000/dashboard/import) #22338
- [x] Dashboards list (http://localhost:3000/dashboards) https://github.com/grafana/grafana/pull/23530 @Clarity-89 
- [x] New dashboard folder (http://localhost:3000/dashboards/folder/new) (https://github.com/grafana/grafana/issues/22687)
- [x] Dashboards folder (http://localhost:3000/dashboards/f/:uid/:slug) https://github.com/grafana/grafana/pull/23530 
- [x] Create organisation (http://localhost:3000/org/new)  #22542
- [x] Invite user (http://localhost:3000/org/users/invite)
- [x] Profile page (http://localhost:3000/profile) #24310
- [x] Select organisation (http://localhost:3000/profile/select-org) - Needs UX work I think #24739 @tskarhed 
- [x] ~Admin home~ (http://localhost:3000/admin) added redirect
- [x] Admin - users list (http://localhost:3000/admin/users)
- [x] Admin - Add new user (http://localhost:3000/admin/users/create) (#21506) 
- [x] Admin - User edit (http://localhost:3000/admin/users/edit/1) 
- [x] Admin - Organisations list (http://localhost:3000/admin/orgs) #23821
- [x] Admin - Organisation edit (http://localhost:3000/admin/orgs/edit/1)
- [x] User invite page (http://localhost:3000/invite/whatever)
- [x] Login - Signup (http://localhost:3000/signup) 
- [x] Reset password (http://localhost:3000/user/password/send-reset-email) #24344
- [x] Snapshots list (http://localhost:3000/dashboard/snapshots) #24266
- [ ] App page wrapper, `AppPageCtrl` (plugins/:pluginId/page/:slug)
- [x] Alerting - Notifications (http://localhost:3000/alerting/notifications)
- [x] Alerting - New channel (http://localhost:3000/alerting/notification/new) #25265
- [x] Alerting - Channel edit (http://localhost:3000/alerting/notification/1/edit)
- [x] 404 page (http://localhost:3000/doh)
- [x] Playlist edit #32218 (#25118)
- [x] Playlists

## Modals:

- [ ] Confirm modal (confirm_modal.html & utilSrv)
- [x] Share modal 
- [x] Dashboard save  https://github.com/grafana/grafana/pull/22395
- [x] Unsaved changes modal https://github.com/grafana/grafana/pull/23909 @dprokop 
## Dashboard components & views

- [x] Dashboard settings container & side menu 
  - [x] Dashboard settings (first view / menu item under dashboard settings view) #30914
  - [x] Template variables list #22434
  - [x] Template variable edit / settings #22434
  - [x] Annotation queries list #31950
  - [x] Annotation edit / settings #31950
  - [x] Dashboard history list #29970
  - [x] Dashboard history item & diff 🏃 @jackw
  - [x] Dashboard links editor  #31150
  - [x] JSON Model 
  - [x] Dashboard save button hidden when turning making dashboard editable (https://github.com/grafana/grafana/issues/29719) 
- [ ] Submenu container (container for variables, annotation toggles, dashboard links) #22434
  - [x] Variable select inputs #22434
  - [x] Annotation togggle #22434
  - [x] Dashboard links @peterholmberg 
    - [ ] Make sure menu positioning is correct (ref https://github.com/grafana/grafana/issues/22513)

## Components 
- [ ] Code editor
  This one is tricky. It uses Ace (https://ace.c9.io/) editor and is also used by 3rd party plugins which means, we cannot easily get rid of it. We need to make a decision if we want to migrate this to react and still use Ace, or maybe re-implement it with Slate. My suggestion is to experiment with Slate first to see what's the effort there to implement basic code editor.

# Services
* [ ] DashboardSrv
* [ ] DatasourceSrv 
* [ ] UtilSrv

**Comment by dprokop** [comment]
Some candidates to start with (as those could also introduce new form styles) are:
- [ ] Invite user (http://localhost:3000/org/users/invite)
- [ ] New dashboard folder (http://localhost:3000/dashboards/folder/new)
- [ ] Admin - Add new user (http://localhost:3000/admin/users/create)
- [ ] Reset password (http://localhost:3000/user/password/send-reset-email)
- [ ] Login - Signup (http://localhost:3000/signup)
- [ ] Alerting - New channel (http://localhost:3000/alerting/notification/new)

**Comment by stevenvachon** [comment]
Annotation editor might be an important one to focus on given that we're writing many plugins. Especially with https://github.com/grafana/integrations-team/issues/16

**Comment by torkelo** [comment]
@ryan just merged support for this https://github.com/grafana/grafana/pull/27375

**Comment by torkelo** [comment]
Remove this
coreModule.service("dashboardSrv", DashboardSrv) 

And add to this: 
AngularApp: 
coreModule.factory('timeSrv', () => getTimeSrv());
coreModule.factory('templateSrv', () => getTemplateSrv());

**Comment by tskarhed** [comment]
Closing since all pages and views are done. Directives and further conversion can be found #35326
