### ISSUE TITLE
Implement UnitPicker with Cascader

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#21610]
See previous #21379

**What would you like to be added**:
- UnitPicker should use the Cascader component

**Why is this needed**:
Because we are migrating to the new form styles, and the cascader provides a better alternative for selecting tree-structured data.

**TODO**
- [x] Implement create custom value in Cascader
- [x]  UnitPicker should have a feature toggle `newFormStyles` for using while migrating to new form styles. This should toggle between old and new designs.
- [x] Implement UnitPicker with Cascader
