### ISSUE TITLE
react-select issues

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#22019]
Just a list of issues realted to the react-select version bump

- [x] Can't do backspace on selected value #21872
- [x] Multivalue blurs on select https://github.com/grafana/grafana/issues/21983
- [x] Cascader unwanted blurring https://github.com/grafana/grafana/issues/21798
- [x] (Probably not related to the upgrade) Styling overlap 
https://github.com/grafana/grafana/issues/21504
- [x] Storybook page for Forms.Select is broken #22244
- [x] Scroll when changing selection with keyboard #21377

**Comment by tskarhed** [comment]
Blurring is probably related to document.activeElement, alternatively issue with menuListRef
https://github.com/torkelo/react-select/blob/79efe792c2edaf1b07e1bdeae0640f9829d4fc5e/src/Select.js#L1067

**Comment by tskarhed** [comment]
Closing this since we don't have any critical bugs with Select anymore.
