### ISSUE TITLE
Platform Roadmap (6.7+)

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#22062]
Project board: https://github.com/grafana/grafana/projects/14

Not in priority order. For recent work check see previous roadmap issue: #20740

Mark | Description
-- | --
🏃 | work in progress

---

### Components & UI
- [ ] Feature complete Inspect Drawer. 

Progress can be seen in the Epic issue (https://github.com/grafana/grafana/issues/20710)

### New Panel editor
Progress can be seen in the Epic issue (https://github.com/grafana/grafana/issues/21111)
Field config epic: https://github.com/grafana/grafana/issues/22269

### Migrations
- [x] Release backend_srv migration https://github.com/grafana/grafana/issues/18049
- [ ] Dashboard import migration (https://github.com/grafana/grafana/issues/21614)
- [x] Signup page (https://github.com/grafana/grafana/pull/21514)
- [x] User invite page https://github.com/grafana/grafana/pull/22263
- [x] QueryVariables migration to Redux(https://github.com/grafana/grafana/pull/22434)
- [x] Dashboard save modals (https://github.com/grafana/grafana/issues/22358)  

### Packages
- [x] Storybook deployed from master
- [ ] Migrate storybook to use babel instead of ts-loader
- [x] Build/release pipeline for packages documentation

### Tech debt
- [x] ts-loader to Babel migration
- [ ] Decrease strict null TS errors by 200-300

### Documentation
- [x] Stat, Gauge and BarGauge panel documentation

## Deferred work
- Feature complete Inspect Drawer. 
- Migrate storybook to use babel instead of ts-loader
