### ISSUE TITLE
FieldConfigs Epic (Override & editor components & infra)

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#22269]
Mark | Description
-- | --
🏃 | work in progress

### TODO (in priority order)
* [x] Move applyFieldOverride to PanelQueryRunner #22439 @dprokop 
* [x] Should we move fieldOptions to PanelModel (instead of nested under PanelModel.options). Maybe rename to fieldConfigs #22600  @dprokop
* [x] Add Value mapping editor to standard registry #22648  @dprokop 
* [x] Improve Value mappings editor UI to better fit the sidebar #22808 @dprokop 
* [x] Add RadioButtonGroup editor / field config type https://github.com/grafana/grafana/pull/23070 @dprokop 
* [x] Improve the API for creating custom options registries (Fluent interface) https://github.com/grafana/grafana/pull/23070 @dprokop 
* [x] A way for a panel plugin to specify they want field configs, specify which field settings care about / order.  https://github.com/grafana/grafana/pull/23214 @dprokop 
* [x] Deprecate setDefaults, ~setFieldConfigDefaults~ in favour of new fluent API for editors creation https://github.com/grafana/grafana/pull/23214 @dprokop
* [x] Enable opt in for field config (configure to pick up which config properties to be available) on `PanelPlugin` https://github.com/grafana/grafana/pull/23214 @dprokop 
* [x] Implement new design for field overrides [Figma] (https://www.figma.com/file/LJtrlpFTAZEDgnS8COtMSL/Panel-edit?node-id=151%3A109) https://github.com/grafana/grafana/pull/23630 @dprokop 
* [x]  **!!!!!!** Remove field config properties editors from panels editors (`LegacyValueMappingEditor`, `FieldPropertiesEditor`, `DataLinksEditor`, `ThresholdsEditor`) **!!!!!!** https://github.com/grafana/grafana/pull/23497 @dprokop 
* [x] Cleanup field override tests. We have field overrides tests in two locations (one next to the function file, and one in FieldConfigs component dir). https://github.com/grafana/grafana/pull/23307 @dprokop
* [x] The options type ApplyFieldOverrideOptions that get's passed to applyFieldOverrides contains two properties, standard, and custom.  Think a rename to `standardRegistry` and `customRegistry` would help as the code is hard to read with a property named custom living on field config being used in the same part of the code. https://github.com/grafana/grafana/pull/23307 @dprokop @torkelo 
  - [x] refactor setFieldConfigDefaults to use registry instead of defaults object https://github.com/grafana/grafana/pull/23376 @dprokop 
  - [x] get rid of setDefaults usages https://github.com/grafana/grafana/pull/23404 @dprokop 
- [x] Add support for nested config in field overrides  #23376 @dprokop 
* [x] ~~Namespace exports for FieldConfigs/* components~~ Those are not exposed now, only via the registry
* [x] Support dynamic field override expressions (it looks like this was removed)

### Bugs
- [x] StatPanel: Value mappings not working #22624 (fixed in https://github.com/grafana/grafana/pull/22648)
- [x] BarGauge throws loads of React warnings in the console #22760
- [x] Does not work for new fields generated by transform step (Try Reduce step for example). Understand why the fields do not show up in the matcher suggestions (Sepereate bug). But even when set manually is not applied. https://github.com/grafana/grafana/pull/23785  @dprokop 

### Questions
* [x] Should we move scoped vars from `FieldConfig` to `Field` ?
* [x] Clarify what the thinking is behind standardFieldConfigEditorRegistry, should plugins really be able to add to this and modify field options available to all panels? Do we have a use case for this?
* [x] What's our way for removing the old edit mode?
- No Value option is new, should we add this, how does it relate to the null value PR we never really completed: https://github.com/grafana/grafana/pull/18818 

### Backlog
- Implement component for field config variable suggestions #22359
- Update Grafana plugin tutorials with the new APIs for options/field config editor creation https://github.com/grafana/grafana/issues/23820

**Comment by dprokop** [comment]
> Clarify what the thinking is behind standardFieldConfigEditorRegistry, should plugins really be able to add to this and modify field options available to all panels? Do we have a use case for this?

@torkelo  I don't think they should be able to modify this registry, can't see use case for that. But we need to initialise the  registry somehow, that's why it's public now in grafana/data. I'm gonna change that and make sure the registry itself is not exposed from grafana/data, only the initialisation function

**Comment by dprokop** [comment]
> Support dynamic field override expressions (it looks like this was removed)

What do you mean by this?

**Comment by dprokop** [comment]
> Should we move fieldOptions to PanelModel (instead of nested under PanelModel.options). Maybe rename to fieldConfigs

Maybe, not 100% convinced to this. Currently `fieldOptions` defaults can be easily sneaked into the panel option defaults  by specifying `fieldOptions`. There's no type guarantee the `fieldOptions` will be added  thought. Maybe we should be more specific in PanelProps type definition, saying that options need to extend `PanelOptions`?

```
interface PanelOptions {
  fieldConfig?: FieldConfigSource;
}

export interface PanelProps<T extends PanelOptions = any> {
```

Think adding field config to the PanelModel directly will also make it harder for plugins to provide defaults. Currently we use `setDefaults` that easily handle that. With fieldConfig outside of `options` we need to adjust the API to allow field config defaults. 

Handling changes in PanelEditor will also require an additional method for the updates which will be pretty much the same as panel options change handler. 

None of above is critical, but I can't see a clear benefit in moving `fieldOptions` outside of PanelModel `options`. As suggested by Torkel  I think renaming `fieldOptions` to `fieldConfig` should be sufficient.

**Comment by torkelo** [comment]
or maybe do 
interface PanelOptions extends FieldConfigSource {
}

so that defaults and overrides are directly on options. 

Another unrelated idea. Wonder if a util factory functions for FieldPropertyEditorItems would be useful to minimize the boilerplate for defining new editor options:

![image](https://user-images.githubusercontent.com/10999/74915168-09b87380-53c4-11ea-8b44-3236dbe6416e.png)

That is a lot of lines and types to import for defining an option. think if we had a generic factory function most of those types could be derived or be set using defaults. 

example

```ts
const cellDisplayMode: newFieldPropertyEditorItem<SelectFieldConfigSettings<string>>() = {
    id: 'displayMode',
    name: 'Cell display mode',
    description: 'Color value, background, show as gauge, etc',

    settings: {
      options: [
        { value: 'auto', label: 'Auto' },
        { value: 'color-background', label: 'Color background' },
        { value: 'gradient-gauge', label: 'Gradient gauge' },
        { value: 'lcd-gauge', label: 'LCD gauge' },
      ],
    },
  };
```

Ie the editors could be automatically set by the factory function (or overwritten if set by caller). 

Another thing that I think we need to add to this FieldPropertyEditorItem is a function to hide/show setting based on what other options are already set. So we can have settings that are hidden if another option is not enabled / set to a specific value

**Comment by torkelo** [comment]
Added a question on the no value option: 

No Value option is new, should we add this, how does it relate to the null value PR we never really completed: https://github.com/grafana/grafana/pull/18818

**Comment by dprokop** [comment]
> Support dynamic field override expressions (it looks like this was removed)

@torkelo what do you mean by this?

**Comment by dprokop** [comment]
Closing,  created one followup for 7.0 https://github.com/grafana/grafana/issues/23820
