### ISSUE TITLE
Template Variables move to React/Redux Leftovers

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#22564]
**Issues to be fixed:**
- [x] Dashboard refresh does no longer work. The path there (in current variable system) -> refresh -> event timeRangeUpdated -> variableSrv updates any variables -> dashboard.templateVariablesUpdated -> dashboad.startRefresh() #22821
- [x] Single value variables should close and commit Picker when value is selected. #22823
- [x] Preserve order of variables when saving dashboard #22805
- [x] Infinite loop when using StackDriver #22917 (fixed by @daniellee)
- [x] Issue with ["value"] in current for single value variable #23208
- [x] Ad hoc filter not applied after page reload (from url) (#23106) (wrongly configured variable) 
- [x] Issue with updating query variable regex (template_srv - reading from getState). #23229

**Bare minimum**
- [x] Introduce data source variable type #22770
- [x] Introduce ad hoc variable type #22784
- [x] Introduce interval variable type #22797
- [x] Create proper dashboard migration step #23107 
- [ ] Remove feature toggle

**PR comments**
- [x] Remove uuid _Originally posted by @torkelo in (https://github.com/grafana/grafana/pull/22434_) #22858
- [x] Use registry instead of VariableAdapters. _Originally posted by @hugohaggmark in (https://github.com/grafana/grafana/pull/22434/review_comment/create_) #22866
- [x] Maybe this file could be split to variable_utils and types, as it's quite big? _Originally posted by @dprokop in (https://github.com/grafana/grafana/pull/22434_) #22884

**Misc**
- [ ] #20703
- [ ] New Form styles
- [ ] #22254
- [ ] documentation
- [ ] celebrate 🎉 

**When we have nothing else to do:**
- [ ] Create a tag component to handle the picker tags
- [ ] Change so the VariableTag and VariableOption uses text/value: string[] instead of string | string[]
- [x] Maybe move all the new React/Redux files to public/app/features/variables
- [ ] Have a look a see if we can make the adapter interface a bit simpler. Some of the functionality is shared between all variables.
- [ ] Move pickers folder into `public/app/features/variables/shared`. 
- [ ] Move editors folder into `public/app/features/variables/shared`. 
- [ ] Split OptionsPicker into one with multi support and one without.
