### ISSUE TITLE
Forms migration Epic

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#22862]
## General
- [x] Prepare a changelog notice about LegacyForm elements and their replacement counterparts from the new form styles.
- [x] Remove `Forms` namespace and put "legacy" form components (button, input, select etc) under `LegacyForms` namespace
- [ ] Handle gf-forms
  - Change the CSS?
  - Update examples in docs

- Create Angular Wrappers to use until Angular migration is done? Or just migrate  those views first
- Figure out how to handle email templates

## Forms/views that needs to be migrated
Some of these coincide with the Angular migrations #21484, take those first. https://github.com/grafana/grafana/issues/21484#issuecomment-574120475

- [x] Data Link/Panel Link modal https://github.com/grafana/grafana/pull/23778
- [x] http://localhost:3000/datasources (FilterInput and Button)
  - [x] Layout selector to radio button group
- [x] http://localhost:3000/org/teams #23810
- [x] http://localhost:3000/admin/orgs/edit/1
- [x] http://localhost:3000/alerting/list #23810
- [x] http://localhost:3000/admin/orgs (Buttons)
- [x] http://localhost:3000/alerting/notifications #22548
---
- [ ] http://localhost:3000/alerting/notification/new
- [ ] Buttons in dashboard header (Requires SplitButton and ButtonGroup #15434)
- [x] http://localhost:3000/profile
- [x] http://localhost:3000/profile/password
- [x] http://localhost:3000/profile/select-org #24739
- [x] http://localhost:3000/admin/users/edit/
- [x] http://localhost:3000/datasources/new
- [ ] http://localhost:3000/?editview=settings
- [ ] http://localhost:3000/?editview=annotations
- [ ] http://localhost:3000/?editview=templating
- [ ] http://localhost:3000/?editview=links
- [x] http://localhost:3000/org/users (FilterInput and Button)
- [x] http://localhost:3000/plugins
- [x] http://localhost:3000/org
- [ ] http://localhost:3000/org/apikeys
- [x] http://localhost:3000/dashboards
- [ ] http://localhost:3000/playlists/create *

- [x] Button in Create new panel (https://github.com/grafana/grafana/pull/23715)
- [x] Switch org modal (Buttons)
- [x] EmptyListCTA
- [ ] RowOptionsCtrl ![avatar](https://github.com/hugohaggmark.png?size=24)

## Components
__Legend__
   - __Replaces__: Old legend, rather use Field if it isn't a special case
   - [x] Namespace migration
__Label__
  - __Replaces__: Old FormLabel, rather use Field if it isn't a special case
   - [x] Namespace migration
__Button__
  - __Replaces__: Old Button component and the CSS class version
   - [x] Namespace migration
   - [x] Component completely replaced
   - [ ] CSS replacement

__Checkbox__
  - __Replaces__: Old checkbox
   - [x] Namespace migration
__Field__
  - __Replaces__: FormField, Legend and label, maybe?
   - [x] Namespace migration
__FieldValidationMessage (New)__

__Input__
  - __Replaces__: Input and places where `<input/>` occurs.
   - [x] Namespace migration
__RadioButtonGroup/RadioButton__
  - __Replaces__: Places where a dropdown or search has up to 4 items

__Select__
  - __Replaces__: Old Select component and possible some regular dropdowns
   - [x] Namespace migration
__Switch__
  - __Replaces__: Old Switch
   - [x] Namespace migration

__TextArea__
  - __Replaces__: Old TextArea
   - [x] Namespace migration

**Comment by dprokop** [comment]
@tskarhed awesome progress on this epic!

**Comment by tskarhed** [comment]
Thought I'd just mention the process of doing the namespace migration:
1. Move the legacy components export into the `LegacyForms` namespace
2. Fix all errors by doing something similar to this
```ts
import { LegacyForms } from '@grafana/ui'
const { Select, Input } = LegacyForms;
```
This makes it easy to migrate to the new form styles later.

3. Move new component from Forms namespace and export by itself
4. Fix all errors
5. Move legacy component into the folder `Forms/Legacy`. Make sure imports are updated
6. Move new component from `/Forms` to the components folder. Make sure imports are updated

**Comment by aocenas** [comment]
Noticed bunch of things on Loki config page not sure if they overlap with some that are already:

Button size does not match the field:
![Screenshot from 2020-04-06 12-32-17](https://user-images.githubusercontent.com/1014802/78554259-22ada480-780b-11ea-85c2-e04052ea3e7c.png)

Again button size
![Screenshot from 2020-04-06 12-32-22](https://user-images.githubusercontent.com/1014802/78554261-23ded180-780b-11ea-90c4-e59103f23a18.png)

Url which is slate custom editor height
![Screenshot from 2020-04-06 12-32-26](https://user-images.githubusercontent.com/1014802/78554263-24776800-780b-11ea-828e-ca72ffeb30d6.png)

**Comment by tskarhed** [comment]
Closing this in favor of clearer separate issues. The remaining form migration will be LegacyForms and Angular view/components. Removal of CSS will be way down the line.
