### ISSUE TITLE
Docs: build and start tracking progress of grafana/packages documentation

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#22957]
## Background
We are generating docs for packages based on code + code comments. The generated docs is currently stored in `docs/sources/packages_api` in the repository. The reason why we currently are doing that is because we hook into the existing build pipeline of the docs website. It is syncing everything below the `docs/sources` to the website repository. 

Until now we have only generated the docs manually but we would like to do this automatically and also start measuring code coverage of the packages docs.

## The way this would work is basically

> After having a sync with @aknuds1 we decided to aim for the following solution to get a solid pipeline to build, verify and generate the packages docs.

**On PR commits:**
We will run a job that builds, measure code coverage and check spelling of the code comments added in the PR. If any of those steps fails we will fail the build and prevent the PR from being merged to master. If the PR introduce new code without code comments we will also fail the build.

**On master commits:**
When starting the sync the `docs/source` to the website repository we should generate the packages docs and include it in the update being pushed to the website repository. This makes the need of keeping the generated *.md files within the grafana repository. 

## Todo
**Adding auto-generate on CI build:**
- [x] Add script for check code comments coverage threshold of the grafana packages (#24876)
- [x] Add Circle CI step for building, verify comments threshold and check spelling in the PR build pipeline. (#27930)
- [x] Extend the Github Action to generate the packages docs before pushing changes to website repository (verify that his is possible). (#27879)
- [x] Clean up the grafana repo by removing the auto-generated docs. (#27880)

**Adding docs:**
- [ ] Prioritised list of core types that are missing docs (@dprokop )
- [x] Add the metrics tracking & PR lint for packages documentation (#24876)
- [ ] Go through staging docs and identify internal types exposed form packages (mostly grafana-data)

**Known issues:**
- [ ] Have a look at the `export const value = { importedFunc, otherImportedFunc }` scenario. Compare [locationutil](https://staging.grafana.com/docs/grafana/latest/packages_api/data/locationutil/) with [urlUtil](https://staging.grafana.com/docs/grafana/latest/packages_api/data/urlutil/)
- [x] `{@links }` doesn't seem to be linked properly in website docs.
- [ ] `@deprecated` doesn't seem to be reflected in the generated docs

**Comment by aknuds1** [comment]
I think when it comes to the (Circle)CI step for building docs, we should implement it as a sub-command in [grafana/build-pipeline](https://github.com/grafana/build-pipeline).

Do you want to start prototyping this together @mckn? The tool is also independent of CI, so let's just try to implement the sub-command for local usage first.

**Comment by mckn** [comment]
> I think when it comes to the (Circle)CI step for building docs, we should implement it as a sub-command in [grafana/build-pipeline](https://github.com/grafana/build-pipeline).
> 
> Do you want to start prototyping this together @mckn? The tool is also independent of CI, so let's just try to implement the sub-command for local usage first.

this sounds awesome!

**Comment by aknuds1** [comment]
@mckn can you give me some simple specs for how the tool should build docs, so I have something to work off?

**Comment by mckn** [comment]
Yes, this is basically it:

https://github.com/grafana/grafana/blob/master/scripts/ci-reference-docs-build.sh

**Comment by aknuds1** [comment]
Thanks @mckn - I guess I can try and port the script.

**Comment by mckn** [comment]
So to prevent it from adding to the build time I would suggest to do it together with the `release-next-packages`. Because they are already building the packages.

**Comment by mckn** [comment]
I have a couple of small adjustments I need to do to the TimeZonePicker but after that I can join you.

**Comment by aknuds1** [comment]
Added an issue https://github.com/grafana/build-pipeline/issues/94 for it.

**Comment by mckn** [comment]
Closing this since we are building the docs in the CI and keeping track of the number of undocumented APIs.
