### ISSUE TITLE
Platform Roadmap (7.0)

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#23241]
Project board: https://github.com/grafana/grafana/projects/14

Mark | Description
-- | --
🏃 | work in progress

---

### Components & UI
- [x] Inspect Drawer (https://github.com/grafana/grafana/issues/20710)
- [x] Storybook available publicly (#22774)
- [x] Components documentation 
- [x] Look and feel update https://github.com/grafana/grafana/issues/23292
- [x] Rollup Indicators (https://github.com/grafana/grafana/issues/11700)

### New Table panel
- [x] [Table Panel Epic](https://github.com/grafana/grafana/issues/20709)

### New Panel editor
- [x] [New Panel Editor Epic](https://github.com/grafana/grafana/issues/21111)
- [x] [Field Config Epic](https://github.com/grafana/grafana/issues/22269)
- [x] [Transformations UI Epic](https://github.com/grafana/grafana/issues/23424)
  - [x] https://github.com/grafana/grafana/issues/23419

### Migrations
- [x] Dashboard import migration (https://github.com/grafana/grafana/issues/21614)
- [x] Migrate forms to use new form styles (https://github.com/grafana/grafana/issues/22862)
- [x] Enable new templating (https://github.com/grafana/grafana/issues/23219)

### Packages
- [x] Documentation for grafana-runtime #23456

### Backlog
- Document core types in grafana-data #22957

**Comment by andig** [comment]
Not sure this issue is an invite to participate, but I'm missing https://github.com/grafana/grafana/issues/1459 (localization of time format) to provide basic usability features for non-US users.

**Comment by javiermatos** [comment]
Could you please think about including a fix for #1664 (renaming data sources without breaking graphs) in this next release? The issue has been there for a really long time.
