### ISSUE TITLE
Grafana 7.0 Look & feel update

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#23292]
Design doc: https://docs.google.com/document/d/1V5hGOouT3YDQZ6hJX64LxSc5MxhdJR8lQ3QtPxXV0Ig/edit#

### TODO: 
- [x] Unicons implementation @ivanahuckova 
  - [x] Part 1: https://github.com/grafana/grafana/pull/23402
  - [x] Part 2: https://github.com/grafana/grafana/pull/23442
- [x] New form styles @tskarhed  https://github.com/grafana/grafana/issues/22862 
- [x] New getting started panel [Figma](https://www.figma.com/file/8F4IgMbc4EhHdDgCpmIgmt/Grafana-7.0-Onboarding-Getting-started-panel?node-id=275%3A0) @peterholmberg 
- [x] Login page update  @tskarhed @torkelo 
- [x] Theme colors update
- [x] Updated, unified card design @torkelo 

Backlog:
- Forgot password page: https://github.com/grafana/grafana/issues/24606
- Modals look & feel: https://github.com/grafana/grafana/issues/24607
