### ISSUE TITLE
Transformations tab epic

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#23424]
* [x] Transformations tab should be scrollable https://github.com/grafana/grafana/pull/23478 @dprokop
* [x] Align the transformation rows design with the query row design: https://github.com/grafana/grafana/issues/23419  https://github.com/grafana/grafana/pull/23478 @dprokop
- [x] Refactor transformations to use single registry https://github.com/grafana/grafana/issues/23424 @dprokop
* [x] Transformer for time series to aggregations #23611 
* [x] Time series labels to columns transformation (RA) @torkelo @hugohaggmark 
* [x] Update designs of transformations https://github.com/grafana/grafana/pull/23751 https://github.com/grafana/grafana/pull/23800 @dprokop
* [x] UI component for time series to columns (join by time) transformer

### Backlog
- Enable transformers reorder by drag and drop

**Comment by torkelo** [comment]
So we have a first iteration of series to columns 

But the naming of fields needs to be refined for time series as the field name is the same as the data frame name so you end up with data frames like this:
![Screenshot from 2020-04-16 10-35-52](https://user-images.githubusercontent.com/10999/79434090-2e992380-7fce-11ea-8857-7278b47c16f7.png)

So in cases like this where there is no duplicate field name between data frames it should just pick the field name. 

Also the question is what should this transformation be named?

Should we rename it from seriesToColumns to joinByField? 

![Screenshot from 2020-04-16 10-38-44](https://user-images.githubusercontent.com/10999/79434307-7b7cfa00-7fce-11ea-80b9-9febca126c7c.png)

In inspect I name it Join by time as it hard codes the join field name by Time name

**Comment by torkelo** [comment]
ping @ryantxu @hugo (see last comment)

**Comment by hugohaggmark** [comment]
> So we have a first iteration of series to columns
> 
> But the naming of fields needs to be refined for time series as the field name is the same as the data frame name so you end up with data frames like this:
> ![Screenshot from 2020-04-16 10-35-52](https://user-images.githubusercontent.com/10999/79434090-2e992380-7fce-11ea-8857-7278b47c16f7.png)
> 
> So in cases like this where there is no duplicate field name between data frames it should just pick the field name.
> 
> Also the question is what should this transformation be named?
> 
> Should we rename it from seriesToColumns to joinByField?
> 
> ![Screenshot from 2020-04-16 10-38-44](https://user-images.githubusercontent.com/10999/79434307-7b7cfa00-7fce-11ea-80b9-9febca126c7c.png)
> 
> In inspect I name it Join by time as it hard codes the join field name by Time name

If I understood your comment correctly this https://github.com/grafana/grafana/pull/23642 should fix it!

**Comment by dprokop** [comment]
> Should we rename it from seriesToColumns to joinByField?

@torkelo  I think we should call it joinByField, when I first came to Grafana, I had hard time understanding the seriesToColumns transformation until i realised it's actually a join. Also, for transformations I think we should use nouns rather that verbs to suggest the action being actually performed.

**Comment by torkelo** [comment]
yes, agree, think it should be named outerJoinByField
