### ISSUE TITLE
7.0 Polish & minor things

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#23551]
Mark | Description
-- | --
🏃 | work in progress

## 7.0beta cross-team testing issues
- [ ] Logo loading "sqashed"
![image](https://user-images.githubusercontent.com/1668778/81548074-fc84a280-937c-11ea-8e56-16a77143195a.png)
- [x] Configuration users page looks weird (too wide and not positioned in the center of the page) @tskarhed (#24533)
![image](https://user-images.githubusercontent.com/1668778/81555127-3d35e900-9388-11ea-9bbe-935a89e538b8.png)
- [x] TimeZones support: `Now delay now` doesn't seem to apply. Adding for example `1m` and going back to dashboard it doesn't apply. Going back to dashboard settings, the `Now delay now` field is empty again. @mckn 
  ![image](https://user-images.githubusercontent.com/1668778/81620286-d0ecd100-93eb-11ea-8e6c-f2cbb2dcff2c.png)
- [x] TimeZones support: Minor/feedback.Would be helpful/nice if timepicker tooltip showed the timezone selected and not the abbreviation since the abbreviation already is displayed in "timepicker selection" @mckn 
  ![image](https://user-images.githubusercontent.com/1668778/81620465-39d44900-93ec-11ea-979d-68a348ec7079.png)
- [x] TimeZones support: Minor/feedback. "timepicker selection" and tooltip maybe should show that local browser time is in use since all other timezones shows this? @mckn 
  ![image](https://user-images.githubusercontent.com/1668778/81620534-68eaba80-93ec-11ea-8ca3-082addf9ef7e.png)
- [ ] TimeZones support: Going to explore from a panel doesn't bring the time zone from dashboard (if new york timezone is saved on dashboard). I'm not sure this has worked before though.
- [x] Icons are but at the bottom (Safari 13.1 (15609.1.20.111.8) @ macOS 10.15.4 (19E287)) <img width="358" alt="03_PE_icons_1" src="https://user-images.githubusercontent.com/141744/81658800-65c9eb80-9439-11ea-95cc-5a96cde5e232.png"> the same for query editor <img width="437" alt="03_PE_icons_2" src="https://user-images.githubusercontent.com/141744/81658809-6793af00-9439-11ea-91d4-cb40e47cb546.png"> https://github.com/grafana/grafana/pull/24610#pullrequestreview-410732480
- [x] Select for panel edit sidebar is displayed by default instead fo tabs (all browsers @ macOS <img width="750" alt="PE_select" src="https://user-images.githubusercontent.com/141744/81658993-9578f380-9439-11ea-91f7-1bb2f1819061.png">
- [x] Transform tab: select options are cut (and layout breaks on Safari): 
<img width="1269" alt="Zrzut ekranu 2020-05-12 10 56 27" src="https://user-images.githubusercontent.com/141744/81664145-85fca900-943f-11ea-9672-91fe16765df4.png"> (Opera @ macOS)
<img width="1241" alt="Zrzut ekranu 2020-05-12 10 56 45" src="https://user-images.githubusercontent.com/141744/81664175-8bf28a00-943f-11ea-945d-213299bdbe38.png"> (Safari @ macOS)

## Known issues:
- [ ] Transform: Outer join issue with join on field that you cannot join on
- [ ] Transform: Rename Outer join to something more digestable (Join by field)
- [ ] Transform tab: Add field from calculation: Calculation fields. Make sure all definitions are in sentence case. 
![image](https://user-images.githubusercontent.com/52059945/81610265-17abde00-938e-11ea-8099-30d2edbb9e1d.png)
- [x] Transform tab: Add field from calculation. One or more items are cut off in the Calculation field. This is what it looks like when I scroll all the way up. 
![image](https://user-images.githubusercontent.com/52059945/81609287-7cfecf80-938c-11ea-87a6-2b575c12c1ac.png)
- [ ] Panel Edit: Graph visualization. In the Axes section, why is the Y-Axes section separated from the Left Y and Right Y section? It should be next to them, not on the other side of X-Axis.
- [x] Panel Edit: Graph visualization. Text should be "Stacking and null value". Also, need initial caps on all drop-down list options for consistency. https://github.com/grafana/grafana/pull/24371
![image](https://user-images.githubusercontent.com/52059945/81109671-4b3ec200-8ecf-11ea-81dc-584e9a609d82.png)
- [x] Panel Edit: Graph visualization. In the Panel tab, "Series overrides" is spelled wrong. Also, why are Thresholds in the Panel tab rather than in the Field tab? And why are Series overrides on the Panel tab rather than the Overrides tab? Very confusing, and it makes the Panel tab more cluttered than it needs to be. And isn't Time regions basically a field configuration or override?  https://github.com/grafana/grafana/pull/24371
![image](https://user-images.githubusercontent.com/52059945/81019899-83d19380-8e1c-11ea-9a02-ef1112e413db.png)
- [x] Panel Edit: Typo in the Bar gauge visualization display options.  https://github.com/grafana/grafana/pull/24371
![image](https://user-images.githubusercontent.com/52059945/81009437-7ced5580-8e09-11ea-861e-5a9f93e3b255.png)
- [x] Panel Edit: Typo and incorrect capitalization in Gauge visualization display options. https://github.com/grafana/grafana/pull/24371
![image](https://user-images.githubusercontent.com/52059945/81013130-837ecb80-8e0f-11ea-9695-cf1f3497c2f8.png)
- [x] Panel Edit: In the Table panel display section, the **Show header** option shows or hides column titles. We should rename this and rewrite the description text to clarify what it does. https://github.com/grafana/grafana/pull/24426
* [x] Make naming of the core panels consistent(use Sentence case) in the viz picker https://github.com/grafana/grafana/pull/24371
* [ ] Panel Edit: Hyphenate Y-axis and X-axis in the Panel Edit UI Panels tab.
* [ ] Panel Edit: Heatmap visualization: In Panel tab, move **Data format** above **Buckets**, because if you select **Time series buckets** as the Data format, then the Buckets section disappears. 
* [x] Panel Edit: The capitalization of the panel titles in the Visualisation section of the Panel tab is inconsistent. Could you please make them all sentence case? https://github.com/grafana/grafana/pull/24371
* [x] Panel Edit: Visualisation vs. Visualization. Currently using European spelling in the Panel tab, should we be using American spelling? https://github.com/grafana/grafana/pull/24558
* [ ] Panel Edit: Enforce initial capitalization of all options. Lots of initial lowercase in the Heatmap dropdown lists.
* [x] Panel inspect: "Stats" heading in the Stats tab is redundant. Please remove. https://github.com/grafana/grafana/pull/24371
* [x] Rename "Transformer" field label in panel inspect to "Transform data" https://github.com/grafana/grafana/pull/24371
* [x] Do not show deprecated panels in the viz picker https://github.com/grafana/grafana/pull/24371
* [ ] Update Graph Axes editor so imputs are full width of container (and not wider) https://github.com/grafana/grafana/issues/24091
- [ ] Review and update UI of Angular panel options
* [ ] Make our react buttons usable from angular so we can use the small sized buttons and align the design here:
  <img width="264" alt="Screen Shot 2020-04-27 at 20 03 26" src="https://user-images.githubusercontent.com/10999/80404994-48861080-88c2-11ea-8b63-e6fa51f2f9c3.png">
* [ ] Panel editor: For new panels have basic section default to open but for existing panels default to close
* [ ]  Autofocus the new threshold item after adding new threshold
* [x] Convert remaining stories to CSF (#22958) @tskarhed 
* [ ] Storybook: Make theme switcher work when viewing docs.

- [x] Add min height to the visualisation pane in the new panel editor
- [x] Template variables renders terribly wrong and do not wrap: https://github.com/grafana/grafana/pull/23862 @dprokop 
* [x] Add counter property to Query & Transform & Alert tab (1 if there is an alert). ~~And a counter to the Overrides tab~~ #23645 
* [x] Add Counter to collection property type (collapsible one) in the field overrides https://github.com/grafana/grafana/pull/23655 @dprokop 
* [x] In the Panel Editor side menu would be nice to persist in local storage what OptionGroup (collapse / expand) sections are expanded collapsed so switching tab or going back to dashboard will not loose the expand/collapse state. 
* [x] Add number to collapsed group section in panel editor sidebar (like Panel Links, Value mappings, Thresholds) So we can see that there are links,value mappings defined without expanding the section.  #23655 @dprokop 
* [x] Variables: Query Variable Editor and the query input text area looks really narrow (Fixed by https://github.com/grafana/grafana/pull/23614)
* [x] Panel edit panel links & data links use same component but in the UI (modal and items, and button) is is referred to as data links in both. Either change it to more neutral link, have prop so it can be different in the two use cases. https://github.com/grafana/grafana/pull/23778/files @tskarhed 
* [x] Data links/panel links modal: remove link remove button in the data links modal https://github.com/grafana/grafana/pull/23778 @tskarhed 
* [x] Update form in link edit modal to new form styles  https://github.com/grafana/grafana/pull/23778 @tskarhed 
* [x] Transformations - debug JSONFormatter is dark in Light Theme https://github.com/grafana/grafana/pull/23802 @dprokop 
* [x] Transformations debug - scroll is not working https://github.com/grafana/grafana/pull/23802 @dprokop 
* [x] Organise fields transformer persisted options are not reflected in the organise transformer editor https://github.com/grafana/grafana/pull/23812 @dprokop
* [x] Organise transformer UI - long field names are not wrapped, we need to either wrap or add ellipsis https://github.com/grafana/grafana/pull/23812 @dprokop
* [x] Table- header cell text overflows container - add ellipsis https://github.com/grafana/grafana/pull/23818 @dprokop
* [x] Display data link title as Tooltip in table cell (reported in #23617) https://github.com/grafana/grafana/pull/23818 @dprokop
* [x] Metrictank rollup indicator tweaks (reported in https://github.com/grafana/grafana/issues/23485) https://github.com/grafana/grafana/pull/23848 @torkelo

**Comment by aocenas** [comment]
Sometimes the table width is 50% even thought the width seems to be set correctly:
![Screenshot from 2020-05-13 13-10-42](https://user-images.githubusercontent.com/1014802/81805962-16102080-951c-11ea-84a7-7e247b766596.png)
![Screenshot from 2020-05-13 13-12-41](https://user-images.githubusercontent.com/1014802/81805970-18727a80-951c-11ea-8eae-53af33d556e2.png)
![Screenshot from 2020-05-13 13-16-52](https://user-images.githubusercontent.com/1014802/81805974-190b1100-951c-11ea-9ce1-9858cd2fdc59.png)

**Comment by aocenas** [comment]
If query does not return any data the table does not show anything. I would expect something like `No data` there instead:
![Screenshot from 2020-05-13 15-32-52](https://user-images.githubusercontent.com/1014802/81819210-4e6d2a00-952f-11ea-9700-012c04377449.png)

**Comment by torkelo** [comment]
Good feedback!

**Comment by sarlinska** [comment]
We need to add a handle for sidebar and visualisation – it's not at all obvious it can be dragged. Users already struggled with this during community call. We can use the one from the `Query History` drawer.
![image](https://user-images.githubusercontent.com/15225624/81830075-e8d36a80-953b-11ea-9e15-62148bb1e188.png)
![image](https://user-images.githubusercontent.com/15225624/81830098-f38dff80-953b-11ea-8669-63ebb5244a14.png)

**Comment by sarlinska** [comment]
The default size of the sidebar should always assure showing tabs. Dropdown is [very confusing for [users](https://grafana.slack.com/archives/CSKQV9Y5B/p1588609723003800) ) and should be used only as last resort. Dropdown + chevron for toggling sidebar visibility create a rather confusing combo, hence, we should avoid showing dropdown as much as possible.
<img width="1552" alt="sidebar-tabs" src="https://user-images.githubusercontent.com/15225624/81830590-8af35280-953c-11ea-9d15-3d9694094399.png">

**Comment by sarlinska** [comment]
When expanding and collapsing sections I should be able to see it's full/most of content, that means that the sidebar contet should be scrolled up when I expand a section. Right now I can expand section and if it's at the very bottom I cannot see it's content – it almost looks like nothing happened 👇 
![Kapture 2020-05-13 at 17 18 51](https://user-images.githubusercontent.com/15225624/81834262-01924f00-9541-11ea-93c5-5520e51538ee.gif)

**Comment by sarlinska** [comment]
It would be good to add `dashboard count` next to folders – right now collapsed folder (gdev dashboards) looks like an empty one 👇 
![image](https://user-images.githubusercontent.com/15225624/81834931-ef64e080-9541-11ea-872d-f3a83977a0d9.png)

**Comment by sarlinska** [comment]
This `Transformations info box` is massive – it should be possible to close it without clicking on transformation type. Especially that it keeps coming back if you delete all transformations.
![image](https://user-images.githubusercontent.com/15225624/81835459-934e8c00-9542-11ea-834d-a3111fde22f3.png)

**Comment by sarlinska** [comment]
@dprokop that is probably more than a minor issue 👇 This dropdown is actually dropup(?) + content is obscured. -- I am using Brave Version 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)

This is a 40 sec preview (the most extreme case is at the very end):

![Kapture 2020-05-13 at 17 55 20](https://user-images.githubusercontent.com/15225624/81836164-63ec4f00-9543-11ea-8f6d-c00f36096373.gif)

**Comment by dprokop** [comment]
> dprokop that is probably more than a minor issue 👇 This dropdown is actually dropup(?) + content is obscured. -- I am using Brave Version 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)

Fixed already on master

**Comment by torkelo** [comment]
> When expanding and collapsing sections I should be able to see it's full/most of content, that means that the sidebar contet should be scrolled up when I expand a section

This sounds very un-expected & disorienting to me

**Comment by dprokop** [comment]
> >When expanding and collapsing sections I should be able to see it's full/most of content, that means that the sidebar contet should be scrolled up when I expand a section

> This sounds very un-expected & disorienting to me


@sarlinska I agree with @torkelo about that. The UI will feel very jumpy when we introduce autoscroll to show the entire expanded section

**Comment by dprokop** [comment]
@sarlinska resolved/hidden some of your comments in favour of issues that I've created to followup on

**Comment by i5okie** [comment]
Also, Bar Gauge or Gauge for that matter does not show term labels.
![image](https://user-images.githubusercontent.com/2119240/82613267-bc41d300-9b79-11ea-8169-e9eb50bf45ee.png)
![image](https://user-images.githubusercontent.com/2119240/82613284-c5cb3b00-9b79-11ea-82e0-1981d5112889.png)

**Comment by niklasR** [comment]
Hey, not sure if this is captured, and not sure what it's called, but the panel menu dropdown doesn't work for me on v7.0.1 (Chrome 83 on Mac OS 10.15.4) - the keyboard shortcuts do work fine though.
![image](https://user-images.githubusercontent.com/724977/83663331-a0e6b700-a5c0-11ea-9b41-5831a9c0fbcc.png)

**Comment by torkelo** [comment]
Closing this as most of this is fixed
