### ISSUE TITLE
Implement E2E tests for Inspect Drawer

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#23686]
### TODO: 
- [x] Inspect Drawer should open when opened from the Panel Menu's Inspect button
  - [x] Correct tab should open when selected from Panel Menu's Inspect submenu
- [x] Inspect Drawer should open from New Panel Editor's Query Inspector button
  - [x] Query tab should be opened by default
- [x] Inspect Drawer's tab should change Inspector's content
- [x] Close button should close the Inspect Drawer
- [x] Expand button should make the Inspector full width

**Comment by marefr** [comment]
@dprokop Please label it

**Comment by dprokop** [comment]
@torkelo @hugohaggmark adde some basic e2e tests overview for Inspect Drawer

**Comment by hugohaggmark** [comment]
@dprokop perfect, will get on this when labels as columns is done.
