### ISSUE TITLE
Implement Dashboard E2E tests

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#23908]
WIP
This epic describes test cases for dashboards interaction:

### New dashboard (smoketest covers some of this)
- [ ] TODO

### Existing dashboard
- [ ] After dashboard was modified Unsaved Changes Modal should be shown
  - [ ] Should close on Cancel
  - [ ] Should dismiss changes on Dismiss and navigate to target url (i.e. when trigered by clicking on logo should go to home dashboard)
  - [ ] Should show Save Changes modal on Save. 
     - [ ] Should close on Cancel
     - [ ] Should navigate to target url (i.e. when trigered by clicking on logo should go to home dashboard) on Save

**Comment by natellium** [comment]
Will be tackled in https://github.com/grafana/grafana/issues/42374
