### ISSUE TITLE
DateTime: complete the timezone support with tests, documentation etc.

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#23917]
**What this PR does / why we need it**:
This it the second part of #23586 and split out in a separate PR to make sure we can get the other one merged as soon as possible.

**Todo:**
- [x] Documentation of this feature (#24080)
- [x] Add end-to-end tests (#24442)
- [ ] Look into adding useTimeZone + consumer component.
- [ ] Clean up the dateTime namespace in grafana-data
- [x] use on shared time zone picker for all the different scenarios.
