### ISSUE TITLE
Backend Plugins: Additional enhancements

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#23992]
Some leftovers from #19667 

- [ ] Refactor new datasource query endpoint #21510 https://github.com/grafana/grafana-plugin-sdk-go/issues/75
- [ ] Add support for validating plugin config #21516 https://github.com/grafana/grafana-plugin-sdk-go/issues/37
- [ ] Back-end plugins: Plugins failing to start should be unregistered #22603
