### ISSUE TITLE
CloudWatch Logs: List of issues and missing features

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#24333]
## Bugs:
- [ ] Log groups selector circle around the group list without updating the scroll position. (Issue: https://github.com/grafana/grafana/issues/24640)
- [ ] Query history: On reload empty metrics query is made (even in logs mode) creating empty Rich history item.
- [ ] table panel does not show long text (separate issue: https://github.com/grafana/grafana/issues/24304)

__done__ 7.0.1
- [x] When label is configured to show aggregate value id does not work (@kaydelaney PR: https://github.com/grafana/grafana/pull/24944)
- [x] Search does prefix search and does not do substring
search across all fields name (@kaydelaney PR: https://github.com/grafana/grafana/pull/24855)
- [x] Query history – display search query instead of
JSON (@kaydelaney PR: https://github.com/grafana/grafana/pull/24795)

__done__ 7.0
- [x] we still show fields that should be hidden `@log`, `@logStream` (@kaydelaney PR: https://github.com/grafana/grafana/pull/24580)
- [x] Template variables are not being interpolated (@kaydelaney Issue: https://github.com/grafana/grafana/issues/24603 PR: https://github.com/grafana/grafana/pull/24619) 
- [x] region selector does not seem to refresh the log groups (@aocenas PR: https://github.com/grafana/grafana/pull/24346)
- [x] regression breaking log groups request (PR: https://github.com/grafana/grafana/pull/24327)
- [x] when log stream selector is open it can be closed only by clicking into the selector again (seems to be fixed on master already)
- [ ] ~~autocomplete for fields does not match some fields like `kubernetes.container_name` (@aocenas)~~ Autocomplete seems to be working by prefix. More fuzzy matching would be nice but a separate feature request.
- [x] ~~it is possible to select sample query without log groups filled in~~ Going to improve the error message for unfilled log group (@aocenas PR: https://github.com/grafana/grafana/pull/24361)
- [x] autocomplete for fields does not do prefix matching if inside a function so in case of `count(@mess|)` it does not show any suggestions even though `@message` field exists (@aocenas PR: https://github.com/grafana/grafana/pull/24406)
- [x] suggestions does not work after comma with field prefix ie `fields @message, hos|`: (@aocenas PR: https://github.com/grafana/grafana/pull/24520)
- [x] ordering of columns in table is different from fields in query (@kaydelaney PR: https://github.com/grafana/grafana/pull/24447)
- [x] query reaching maximum number of attempts would seem to load indefinitely (@kaydelaney PR: https://github.com/grafana/grafana/pull/24447)
- [x] After changing log group new fields are not refreshed (@aocenas PR: https://github.com/grafana/grafana/pull/24529)
- [x] cheat sheet examples are mostly stats queries which work in metrics mode but we do not have a mechanism to support that right now (@kaydelaney 
 PR: https://github.com/grafana/grafana/pull/24398)
- [x] stats query which is grouped shows only one series instead of 1 series per group (@kaydelaney PR: https://github.com/grafana/grafana/pull/24396)
- [x] hint about stats query in logs mode does not always show (@kaydelaney part of PR: https://github.com/grafana/grafana/pull/24396)
- [x] autocomplete keeps suggesting field even after it is inserted. (@aocenas PR: https://github.com/grafana/grafana/pull/24581)
- [x] panic on error conversion when canceling query (PR: https://github.com/grafana/grafana/pull/24641)
- [x] Panic on query with multiple aggregations (@aocenas issue: #24639 PR: https://github.com/grafana/grafana/pull/24683)
- [x] Fix autocomplete after by keyword (@aocenas PR: https://github.com/grafana/grafana/pull/24644) 
- [x] Unify query mode selector look (@aocenas PR: https://github.com/grafana/grafana/pull/24648)
- [x] Panic when response contains sparse rows (@aocenas PR: https://github.com/grafana/grafana/pull/24702)
- [x] Can't access all the logGroups from the select (@kaydelaney Issue: https://github.com/grafana/grafana/issues/24554 PR: https://github.com/grafana/grafana/pull/24695)
- [x] Link to general kitchen sink issue from additional internal testing: https://github.com/grafana/grafana/issues/24504

## Missing features
- [x] Docs (draft PR: https://github.com/grafana/grafana/pull/23651)
- [x] data link from point in a graph similar to CloudWatch metrics (metrics code: https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/cloudwatch/datasource.ts#L402-L412) (@kaydelaney PR: https://github.com/grafana/grafana/pull/24334)
- [x] Additional sample queries (PR: https://github.com/grafana/grafana/pull/24288)

__Scheduled for 7.1__
- [ ] live tailing
- [ ] Inspect panel in Explore
- [ ] synchronized cursor between logs and graph (draft PR: https://github.com/grafana/grafana/pull/23721)

**Comment by mchene** [comment]
Here are some other issues I experienced on v7.1.0-pre (4cdd8bd933) using Chrome:
1. Dashboard Panel - Edit: Adding multiple stats aggregator returns error
a. Input: stats avg(container_memory_usage), percentile(container_memory_usage, 50) by bin(1h), kubernetes.container_name
b. Error message: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
2. Dashboard Edit Panel: Running too many queries with error seem to result in all queries failing (reproduced twice).  Result: required server restart.
3. Dashboard Panel – Edit: Autocomplete for multiple fields after “by” to specify criteria does not work
a. Input: stats avg(container_memory_usage), avg(kubernetes.container_name) by bin(1h)
b. Test Case: attempting to add another field after the bin does not provide available fields in query (e.g., add “,” after bin and attempt to add a field such as kubernetes.container_name).

**Comment by mchene** [comment]
New issues found on v7.1.0-pre (25e1238022) using Chrome:
1. Dashboard Panel – Chart Legend: Legend text should show value of stats aggregation
a. Description: Stats query generates aggregated value to visualize on a chart. The generate legend text should show the value for the time window specified rather than the stats operator expression.
b. Input: stats avg(container_memory_usage) by bin(1h), kubernetes.container_name | filter Type="Container"
c. Current result: apple-app avg(container_memory_usage)
d. Desired result: apple-app (50), where 50 is the aggregated measure for the time window specified

**Comment by Eraac** [comment]
Hi @aocenas, 

I just want to add actually we can't set a variable in the "region" field but we can in `Cloudwatch metrics`. As workaround we set the variable directly in the JSON model (and it's works) but that will be good if the input accept any variables

**Comment by aocenas** [comment]
@Eraac can you create a separate issue for it? This one is a bit stale, used during development and I am going to close this.
