### ISSUE TITLE
docs: missing links for the What's New for 7.0 article

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#24713]
In the what's new article, still waiting on the following documentation links:

- [x] Tracing docs, ref #24297
- [x] Panel Edit docs, ref #24711
- [x] Cloudwatch Logs docs, ref #23651
- [x] Time Zone docs ref #24080
- [ ] Metrictank rollup docs
- [ ] Updated Table panel docs (needs updated screenshot only)
- [x] Auto grid mode
- [ ] Sharing panel results (choosing --dashboard-- in the data source menu in the query editor)

**Comment by oddlittlebird** [comment]
@daniellee, has this been addressed?

**Comment by oddlittlebird** [comment]
@daniellee , still need an answer.
