### ISSUE TITLE
Platform Roadmap (7.1)

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#25349]
Project board: https://github.com/grafana/grafana/projects/14

Mark | Description
-- | --
🏃 | work in progress
---

### Components & UI
- [x] TimeZone: The ability to change timezone from time picker https://github.com/grafana/grafana/issues/24880 [PR](https://github.com/grafana/grafana/pull/24803) @mckn 
- [x] 🏃 Panel Inspect: improve the UI of table data options https://github.com/grafana/grafana/issues/25268
- [x] Refactor Panel Inspect https://github.com/grafana/grafana/pull/24480

### Table panel
- [x] Table: Add ad-hoc filters support to new table panel https://github.com/grafana/grafana/issues/25072 (PR #25467)
### Transformations
- [x] Timeseries to rows transformation https://github.com/grafana/grafana/issues/24945

### Tech debt / security 
- [x] Update jQuery to 3.5.1 https://github.com/grafana/grafana/issues/24225 (PR #24225)
- [x] Update Typescript to 3.9.3 [PR](https://github.com/grafana/grafana/pull/25154) https://github.com/grafana/grafana/issues/24656 @dprokop 

### Angular to React migrations
- [x] Migrate Text panel to React https://github.com/grafana/grafana/issues/25004 (PR #25504)
  - [x] Add `CodeEditor` component based on Monaco https://github.com/grafana/grafana/pull/25251 (PR #25618)
- [x] New Notifications Channel view https://github.com/grafana/grafana/pull/25265
- [x] Migrate Forgot password page to React and apply updated design https://github.com/grafana/grafana/pull/25366

## Postponed to 7.2
- Update look and feel of modals https://github.com/grafana/grafana/issues/24607
- Update Storybook to 6.0 https://github.com/grafana/grafana/issues/25312
- Prepare scope for 7.2 work on react-router migration [Draft PR](https://github.com/grafana/grafana/pull/22085)
- Automate docs generation during the release (@arve will work on this with the support from @grafana/grafana-frontend-platform )
- Start tracking docs coverage metrics https://github.com/grafana/grafana/pull/24876

**Comment by Bubbu17** [comment]
Hello guys, why will the following Features not be implemented in the 7.1 Rodmap of Grafana? #25081 and #25082

**Comment by dprokop** [comment]
@Bubbu17 we don't have plans for these two currently, but we will take those into consideration in future releases.
