### ISSUE TITLE
Storybook: Documenting @grafana/ui components

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#25513]
**What would you like to be added**:
Tons of documentation.

**Why is this needed**:
So people understand how to use @grafana/ui.

**How**
Please see [the guide](https://github.com/grafana/grafana/blob/master/contribute/style-guides/storybook.md#writing-mdx-documentation) on writing MDX docs.

## Undocumented stories/components

- [x] Alert
- [x] AlphaNotice
- [x] Badge
- [x] BarGauge
- [x] BigValue
- [x] Button
- [ ] ButtonCascader – details in [#27308](https://github.com/grafana/grafana/issues/27308)
- [x] Cascader
- [x] ClickOutsideWrapper
- [x] ClipboardButton https://github.com/grafana/grafana/pull/27451
- [x] Collapse - https://github.com/grafana/grafana/pull/27291
- [x] ColorPicker
- [x] ConfirmButton https://github.com/grafana/grafana/pull/27477
- [x] ConfirmModal
- [x] DataSourceSettings
- [x] Drawer #27267
- [x] FileUpload #27393
- [x] FormField https://github.com/grafana/grafana/issues/27596
- [x] FormLabel https://github.com/grafana/grafana/issues/27596
- [x] FormattedValueDisplay https://github.com/grafana/grafana/pull/27759
- [x] Forms
- [ ] Gauge
- [ ] Graph
- [ ] Icon – see details in [#27183](https://github.com/grafana/grafana/issues/27183)
- [x] IconButton
- [ ] InfoBox
- [ ] InfoTooltip
- [ ] Input
- [ ] JSONFormatter
- [x] Label [#27350](https://github.com/grafana/grafana/pull/27350)
- [ ] Layout
- [ ] Legend
- [ ] List
- [ ] LoadingPlaceholder
- [ ] Logs
- [ ] MatchersUI
- [ ] Modal
- [ ] Monaco
- [ ] OptionsUI
- [ ] Pagination
- [ ] PanelOptionsGrid
- [ ] PanelOptionsGroup
- [ ] PieChart
- [ ] Portal
- [ ] QueryField
- [ ] RefreshPicker
- [ ] SecretFormField
- [ ] Segment
- [ ] Select
- [ ] SetInterval
- [ ] SingleStatShared
- [x] Slider
- [ ] Spinner
- [ ] StatsPicker
- [ ] Switch
- [ ] TabbedContainer
- [ ] Table
- [ ] TableInputCSV
- [ ] Tabs
- [ ] Tags
- [ ] TagsInput [#27881](https://github.com/grafana/grafana/pull/27881)
- [x] TextArea
- [ ] ThemeColors – see details in [#27184](https://github.com/grafana/grafana/issues/27184)
- [ ] ThresholdsEditorNew
- [ ] TimePicker
- [ ] ToggleButtonGroup
- [ ] Tooltip
- [ ] Typeahead
- [ ] UnitPicker
- [ ] ValueMappingsEditor
- [ ] ValuePicker
- [ ] VizRepeater

## How (grep magic)
I checked all the component we have stories for by running
> `find -name "*.story.tsx" | grep -Po "(?<=components/).*(?=\.story\.tsx)" | grep -Po "(?<=/)[^/.]*$"
`

All the components with .mdx files (documentation):
>`find -name "*.mdx" -not -path "./node_modules/*"  | grep -Po "(?<=components/).*(?=\.mdx)" | grep -Po "(?<=/)[^/.]*$"
`

Writing these to text files then comparing with:

>` grep -Fxf mdx.txt stories.txt --invert-match`

Which gives us the list.

**Comment by rakhi2104** [comment]
I am interested.

**Comment by tskarhed** [comment]
@rakhi2104 Would you like to write some documentation or are you just eager to get it written? :smiley:

**Comment by rakhi2104** [comment]
I want to help write documentation.

**Comment by tskarhed** [comment]
@rakhi2104 Go ahead and pick a component, and I'll do what I can to help you. Just tell me if you need any help! :smiley:

**Comment by KarineValenca** [comment]
I want to help writing the documentation for the `Spinner` component.

**Comment by jessover9000** [comment]
@KarineValenca if you haven't started yet, please do! tell me if you need anything, will do what I can to help you :)

**Comment by KarineValenca** [comment]
@jessover9000 Actually, I already contribute with Spinner component https://github.com/grafana/grafana/pull/26754

I will pick another component to contribute in the next days, thank you for the support!

**Comment by jessover9000** [comment]
@KarineValenca That's awesome, I was on vacation so I probably just missed it. Thanks so much :)

**Comment by developer-sachidanand** [comment]
Add docs for VizRepeater

**Comment by khushijain21** [comment]
I see many components under "missing mdx" are already done and/or missing from [here](https://developers.grafana.com/ui/latest/index.html?path=/docs/forms-tags-taglist--list). 

There is docs missing for Legend, can I contribute?
