### ISSUE TITLE
Grafana v7.1 Release Plan

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#25697]
# Grafana v7.1
Release Coordinators: @aocenas  

### 1.1. Publish What's new in Grafana draft article
**When:** Wednesday 1st July 2020
**What:**

 - [x] Create Google doc and share with maintainers (Release coordinator)
 - [x] Write draft article (Maintainers)
 - [x] Open a PR (Release coordinator) in grafana repository
 - [x] Examine staging site
 - [ ] Publish to grafana.com

**Who:** Release coordinator and maintainers

### 1.2. Beta 1 Release
**Preconditions:**

- [ ] 1.1. Publish What's new in Grafana draft article

**When:** Wednesday 1st July 2020
**What:**

 - [x] Checkout new release branch, v7.1.x, from head of origin/master
 - [x] Update versions to the next version to be released
 - [x] Update package.json to contain the new “what's new” and “release note” links.
 - [ ] Commit everything and push release branch
 - [ ] Checkout master branch and branch of to a new branch
 - [ ] Update version in package.json to point to the next pre-release, i.e. v7.2.0-pre and commit
 - [ ] Open a PR
 - [ ] Checkout release branch, create and push beta release tag and wait for CircleCI release build to finish
 - [ ] Run automated verification tests
 - [x] Verify the front-end packages
 - [x] Update the changelog in master
 - [x] Create community site release note topic
 - [x] Create a new release on GitHub
 - [x] Create and upload Hosted Grafana images
 - [x] Update latest.json
 - [x] Close the milestone

**Who:** @aknuds1, @mckn 

## 2. Test and verification
Preconditions:

- [] 1.2. Beta 1 Release

**When:** Wednesday 1st July 2020 until July 14th
**What:** The test and verification is done on the release branch. More extensive plan for this will done separately.
**Who:** Primarily maintainers
**Who:** Release coordinator and maintainers

### 3.1 Publish What's new in Grafana final article

**Preconditions:**
 - [1] 1.2 Beta 1 released

**When:** Before stable release
**What:**

 - [ ] Create a new Google doc based on What's new in Grafana draft article published and share with maintainers (Release coordinator)
 - [ ] Write final article (Maintainers)
 - [ ] Open a PR
 - [ ] Publish to production (website repo)

**Who:** Release coordinator and maintainers

### 3.2 Create release blog post

**Preconditions:**
 - [ ] 3.1 Publish What's new in Grafana final article

**When:** Before stable release
**What:**

 - [ ] Use final what's new article as template and create new release blog post
 - [ ] Remember to change relative links from What's new article to absolute ones
 - [ ] Open a PR in website repo

**Who:** Release coordinator

## 4. Stable Release
**Preconditions:**

 - [ ] Beta released and no critical bugs left to fix for the stable release
 - [ ] 3. Docs and blog post

**When:** Tuesday 14th July 2020
**What:**

 - [ ] Cherry pick bug fixes into release branch (important for the stable release)
**Who:** TBD

**When:** Tuesday 14th July 2020
**What:**

 - [ ] Create and push stable release tag and do the actual release

**Who:** TBD

## 5. Publish Release blog post
**Preconditions:**

- [ ] 3.2 Create release blog post
- [ ] 4. Stable Release

**When:** Tuesday 14th July 2020
**What:**

 - [ ] Publish blog post

**Who:** Release coordinator

**Comment by mckn** [comment]
@aocenas this is great! Love it!

**Comment by torkelo** [comment]
Closing this :)
