### ISSUE TITLE
Alerting: Alert notifiers should store sensitive settings encrypted 

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#25967]
**What would you like to be added**:
Following #25113 which adds the basic support for storing sensitive settings encrypted we need to update all alert notifiers so that they support storing sensitive information encrypted.

Alert notifiers:
- [x] Slack (url and token) #25114
- [x] Webhook (password) #26164
- [x] Pagerduty (integration key) #26319
- [x] Alertmanager (Basic Auth Password) #26318
- [x] Opsgenie (API Key) #27074
- [x] Sensu (Password, possibly) #27131
- [x] Telegram (BOT API Token) #27122
- [x] LINE (token) #27157
- [x] Pushover (API Token, User key(s)?) #27159
- [x] Threema Gateway (API Secret) #27160

The following notifiers have not been converted to store sensitive settings encrypted because we don't believe they have any sensitive information and/or encrypting it would make it hard for administrators to understand what configuration is used for certain notifiers:
- [ ] VictorOps (Url?) 
- [ ] Google Hangouts Chat (Url)
- [ ] Microsoft Teams (URL)
- [ ] Discord (Webhook URL)
- [ ] DingDing (url)

**Comment by mtanda** [comment]
I start to work Alertmanager.

**Comment by marefr** [comment]
Fixed by #25114
Fixed by #26164
Fixed by #26319
Fixed by #26318
Fixed by  #27074
Fixed by #27131
Fixed by #27122
Fixed by #27157
Fixed by #27159
Fixed by #27160
