### ISSUE TITLE
Alerting: POC Add support for standalone alerts

### ISSUE THREAD

**Issue by papagian** [grafana/grafana#25976]
The goal for this POC of stand-alone alerts and figure out how much work it would be to deliver a stand-alone alerts feature. Stand-alone alerts will require a lot of frontend work so our goal here should be to build the backend foundation that they can later work on rapidly. 
Goals

- [X] **New feature toggle for enabling/disabling standalone alerts ([issue](https://github.com/grafana/grafana/pull/25984))**
 
All the POC work should be behind a feature toggle so users have to opt in to experience it. 

- [ ] **Build an API for CRUD operations of alert rules** ([Draft PR](https://github.com/grafana/grafana/pull/26659))

The goal for this API is to be able to create alert rules in the alert rules table that does not belong to a dashboard. It should also be possible to update and delete alert rules.

- [ ] **Basic page where we can show a stand-alone alert rule**.

We can ask people from the frontend squad to wire up some initial things. A basic form where we can change the values of the alert rules would be a great start. The goal is not to make it pretty, but usable. 

- [ ] **Identify and workaround all places where an alert rule is assumed to be connected with one dashboard.** ([Draft PR](https://github.com/grafana/grafana/pull/26671))

As alerts currently belong to dashboards we can assume that this is reflected in the code. 
During this POC we need to identify all areas where alert rules are expected to have one dashboard and refactor it to support 0 or more associated dashboards. 

Ex Alert notifications, Alert list page etc. 

- [ ] **Execute the test alert rule API endpoint from the basic edit page.**

In the new alert rules edit page we want to provide better tooling for iterating and improving alert rules. On this page, it should be possible to test alert rules similar to how they can be tested within the dashboard edit view.

**Comment by papagian** [comment]
Closing this since similar work for Alerting NG has got precedence over this.
