### ISSUE TITLE
Azure Analytics and Legend Name fixes for 7.1.x or 7.2

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#26533]
The Azure services in the Azure Monitor data source switched to data frames along with getting some features for extra dimensions.

Since the Azure Analytics services are using the new data frame model and some of the metadata features, some issues have been highlighted with regards to the legend name (e.g. display name for graphs) that behave as regressions for some users.

 - [x] The displayName Field configuration option's label expressions are not documented `__field.labels.X`. (Note: started a PR but simpler to do it together when these other issues are merged or decided). (User Issue: https://github.com/grafana/grafana/issues/26470 , WIP PR: https://github.com/grafana/grafana/pull/26489)
 - [x] `__field.labels` by it self is `[object Object]` (PR: https://github.com/grafana/grafana/pull/26531)
 - [x] No override for units makes it so users can not customize their units, and whatever they enter is overridden by the data (User Issue: https://github.com/grafana/grafana/issues/26497 , PR: https://github.com/grafana/grafana/pull/26529). 
 - [x] There is no way to access just the field name property, because `__field.name` is returning the name and labels. (PR: https://github.com/grafana/grafana/pull/26531)
 - [x] Overrides lack something to match multiple fields, so it makes the override vs Field Config settings confusing, and also makes tedious to set legend for something with multiple series/fields. Or worse, impossible if the data is more dynamic. So at least need an "all fields" option - or a regex like in the filter by name transform. (Feature Request Issue: https://github.com/grafana/grafana/issues/26831, user issue: https://github.com/grafana/grafana/issues/26828)

Finally, one other thing is the default display when there is only one unique name (in time series, often "metric") in data for multiple time series. In the case of Labels, if there is only one label, were do not display, k=v, but just v.  This keeps the legend items as short as possible. We may want to consider doing the same to the metric name (removing it from display) in the case where there is only one metric, there are labels, and multiple series. See https://github.com/grafana/grafana/issues/26470#issuecomment-661911578 for reference. (Done, one case use `${__field.labels.__values}`
