### ISSUE TITLE
Log frontend errors

### ISSUE THREAD

**Issue by domasx2** [grafana/grafana#27993]
**What would you like to be added**:
Opt-in, configurable way to capture frontend javascript errors and log them.

**Why is this needed**:
There's currently no visibility into errors occuring on frontend, so we rely on manual testing and user feedback to spot problems. It would be great to have frontend error logs as well for discoverability and debugging.

**Relevant links**

- [related post on grafana google group](https://groups.google.com/u/1/g/grafana-developers/c/SodA1v4I1BA)
- [public google doc summarizing the problem, proposed implementation and next actions](https://docs.google.com/document/d/14Bua0_zaJjVC6W_k1BplE2XceLoot5CofTjLOG9EHZ8/edit#)

**Todos**
- [x] base implementation: initialize Sentry on frontend and log it's events on backend
- [x] instrument `ErrorBoundary` in `@grafana/ui` to add component stack to error context, log this in backend
- [ ] configure inbound filters to ignore error spam from extensions, old browsers, etc. [see documentation](https://docs.sentry.io/clients/javascript/tips/)
- [x] add configurable rate limiting to backend API (what's a good way to do it?)
- [x] make sample rate configurable 
- [x] sourcemap support

**Questions / invstigations / ideas**
- [ ] investigate [Sentry breadcrumbs feature](https://docs.sentry.io/platforms/javascript/enriching-events/breadcrumbs/). Is it useful?
- [x] should we log user email / id?
   * Yes!
- [ ] what other metadata is useful and log-worthy for frotnend errors?
- [ ] expose some instrumenation for logging errors/messages via `@grafana/runtime`? Can it be Sentry-specific or should a layer of abstraction be added, to make ditching Sentry easier later?
- [x] what documentation is needed?
- [ ] it might be more robust to build separate entrypoint js file for setting up sentry and load it before loading the main js file, thereby having a better chance of logging working in case main file errors out. Not sure yet if worth the effort and overhead
- [x] whats best way to handle stacktraces with newlines, keeping go logger & loki in mind

**Comment by domasx2** [comment]
closing this, no plans to take it further for now
