### ISSUE TITLE
Icons: Improvements

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#28742]
### Improve documentation and usage of icons:

- [ ] https://github.com/grafana/grafana/issues/28744 Deprecation warning:
    - [ ] Add linter warning for new usage of font awesome classNames `fa-` 
    - [ ] By 7.4 introduce deprecation warning for font awesome (if possible, deprecate in 8.0)
- [ ] https://github.com/grafana/grafana/issues/28745 _(Ivana working on this)_ Another round of going through all the font awesome icons and removing them if possible
- [ ] https://github.com/grafana/grafana/issues/28746 Add color prop for updating color (so users can update it via css and also via color prop)
- [ ]  https://github.com/grafana/grafana/issues/28747 Monochrome icon
   - [ ] Update name to solid icons for more semantic name 
   - [ ] Switch monochrome icons that are implemented for solid icons
   - [ ] Improve typing - as we have only some solid icons (less than 15) - we should make sure that if users select the one, that don't exist in mono/solid form, they get warning
   - [ ] Display possible mono (solid) icons and explain which are available and what does it mean
- [ ] https://github.com/grafana/grafana/issues/28748 Improved Icon documentation (probably specifically documentation in storybook)
   - [ ] When to use which icon - add info regarding when do we usually use that icon 
   - [ ] Add information about Icon component being wrapper around unicons and any unicons icon can be added

**Comment by ivanahuckova** [comment]
I will close this epic/issues as icons changed a lot and if there will be a work done to improve experience with icons, that team will create epic/issues for it.
