### ISSUE TITLE
Explore: release trace to logs feature

### ISSUE THREAD

**Issue by zoltanbedi** [grafana/grafana#29509]
Trace to logs feature is already added and released in 7.3.0 but behind a feature flag. This issue is a meant to summarise the tasks that needs to be done to move it out from behind a feature flag to a stable feature.

## Tasks

- [ ] Remove feature flag
- [ ] Add possibility to configure
  - [ ] Select with a list of logs type data sources (we will only support Loki for the first time)
  - [ ] Tags to search for in the trace
- [ ] Add docs
