### ISSUE TITLE
Epic: MVP Library Panels

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#29610]
Epic issue for the Library/Shared/Reusable Panels feature. 

Please use avatar ![avatar](https://github.com/hugohaggmark.png?size=24) to indicate which task you're working on:

**Backend**
- [x] Featuretoggle (#29521)
- [ ] Database
  - [x] library_panel table (#29565)
  - [x] library_panel_dashboard table 
  - [ ] library_panel_tags table?
  - [x] Indexes
  - [ ] Commands 
  - [x] Queries 
  - [x] Tests 
- [ ] Api
  - [x] Create Panel (#29642)
  - [x] Update Panel (#29956)
  - [x] Delete Panel (#29741)
  - [x] Get all Panels (#29772) 
  - [x] Get Panel by ID (#29772)
  - [x] Link to Dashboard (#30212)
  - [x] Unlink from Dashboard (#30212)
  - [x] Better cleanup when deleting lib panels and loading dashboard with deleted lib panels (#30709)
  - [x] Add number of connected dashboards to lib panel meta (#30770)
  - [ ] Search
  - [x] Tests
- [ ] Unknown unknowns
  - [ ] Dashboard API changes?
  - [ ] Provisioning?
  - [ ] Tags?
  - [ ] Access / Rights?
  - [ ] Import Dashboard
  - [ ] Restore Dashboard version
 
**Frontend**
- [ ] Add Panel redesign (#30653) ![avatar](https://github.com/kaydelaney.png?size=24)
- [ ] Search (#30653) ![avatar](https://github.com/kaydelaney.png?size=24)
- [ ] Delete Library/Shared/Reusable Panel
- [ ] Save Panel as Library/Shared/Reusable Panel
- [ ] Edit Library/Shared/Reusable Panel
- [ ] Unknown unknowns
  - [ ] Templating?

Root issue #1803

**Comment by hugohaggmark** [comment]
@ivanahuckova sorry I forgot the labels

**Comment by ivanahuckova** [comment]
> @ivanahuckova sorry I forgot the labels

No worries at all 🙂
