### ISSUE TITLE
Grafana-ui: update stories to use controls

### ISSUE THREAD

**Issue by jackw** [grafana/grafana#30182]
**What would you like to be added**:
Now that grafana ui storybook is on v6 it'd be great if we migrate away from knobs to controls as detailed [here](https://github.com/grafana/grafana/blob/master/contribute/style-guides/storybook.md#controls).

**Why is this needed**:
Controls infers props through types and auto generates the form controls that knobs creates. This results in less code and so less maintenance. Below is a list of all remaining stories that make use of `addon-knobs`.

- [x] Alert/Alert.story.tsx #31145 
- [x] Badge/Badge.story.tsx https://github.com/grafana/grafana/pull/30180
- [x] BarGauge/BarGauge.story.tsx #31223
- [x] BigValue/BigValue.story.tsx #31240
- [x] Button/Button.story.tsx https://github.com/grafana/grafana/pull/29433
- [x] ButtonCascader/ButtonCascader.story.tsx #31288
- [x] CallToActionCard/CallToActionCard.story.internal.tsx #31393 
- [x] Card/Card.story.internal.tsx (This doesn't have any knobs)
- [x] Cascader/Cascader.story.tsx #31399
- [x] ClipboardButton/ClipboardButton.story.internal.tsx #31422
- [x] ColorPicker/ColorPicker.story.tsx #31429
- [x] ColorPicker/NamedColorsPalette.story.tsx #31443
- [x] ConfirmButton/ConfirmButton.story.tsx #31476
- [x] ConfirmModal/ConfirmModal.story.tsx #31781
- [x] Drawer/Drawer.story.tsx #31821
- [x]  Dropdown/ButtonSelect.story.internal.tsx 
- [x] FormField/FormField.story.internal.tsx #32018
- [x] Forms/FieldValidationMessage.story.tsx #32020
- [x] Forms/Form.story.tsx #32022
- [x] Forms/Legacy/Input/Input.story.internal.tsx #32059
- [x] Forms/Legacy/Select/Select.story.internal.tsx #32225
- [x] Forms/Legacy/Switch/Switch.story.internal.tsx #32249
- [x] Forms/Legend.story.tsx #32250
- [x] Forms/RadioButtonGroup/RadioButtonGroup.story.tsx #32251
- [x] Graph/Graph.story.tsx #32264
- [x] Graph/GraphLegend.story.tsx (not found in the codebase)
- [x] Graph/GraphWithLegend.story.tsx #32285
- [x] GraphNG/GraphNG.story.tsx #32294
- [x] InfoBox/InfoBox.story.tsx
- [x] Input/Input.story.tsx #32712
- [x] Layout/Layout.story.tsx #32761
- [x] List/List.story.internal.tsx #32832
- [x] Modal/Modal.story.tsx #32840
- [x] Pagination/Pagination.story.tsx #33045
- [x] PieChart/PieChart.story.tsx
- [x] SecretFormField/SecretFormField.story.internal.tsx #33920
- [x] Select/Select.story.tsx #33954
- [x] Slider/RangeSlider.story.tsx #33980
- [x] Slider/Slider.story.tsx #33983
- [x] Spinner/Spinner.story.tsx #33988
- [x] StatsPicker/StatsPicker.story.tsx #34008
- [x] Switch/Switch.story.tsx #34016
- [x] Table/Table.story.tsx #34193
- [x] TextArea/TextArea.story.tsx #34195
- [x] Tooltip/Tooltip.story.tsx #33130
- [x] ValuePicker/ValuePicker.story.tsx #33122
- [x] VizLayout/VizLayout.story.tsx #33043
- [x] VizLegend/VizLegend.story.tsx #32801

**Comment by hugohaggmark** [comment]
So I think we need to discuss if we should hide unnecessary controls before you move on @thisisobate. I reviewed from the top of the list and found a lot of unnecessary controls in a couple of them. You should look at the knobs in the story and only include controls that match the previous knobs.

![image](https://user-images.githubusercontent.com/562238/108954839-a663c000-766d-11eb-8a61-fe767173f303.png)
![image](https://user-images.githubusercontent.com/562238/108954744-90ee9600-766d-11eb-8756-fac74ae4fbb8.png)
![image](https://user-images.githubusercontent.com/562238/108955183-02c6df80-766e-11eb-8311-f42bb821f020.png)
![image](https://user-images.githubusercontent.com/562238/108955218-183c0980-766e-11eb-9c19-46c2a3fd9057.png)
![image](https://user-images.githubusercontent.com/562238/108955413-63eeb300-766e-11eb-81fb-ede371a54ffd.png)
![image](https://user-images.githubusercontent.com/562238/108955498-91d3f780-766e-11eb-8a2f-d86b8f9e9f8e.png)

**Comment by Clarity-89** [comment]
> So I think we need to discuss if we should hide unnecessary controls before you move on @thisisobate. I reviewed from the top of the list and found a lot of unnecessary controls in a couple of them. You should look at the knobs in the story and only include controls that match the previous knobs.

That's a good point. I tried removing controls with `{control: false}`, as mentioned [here](https://storybook.js.org/docs/react/essentials/controls#disable-controls-for-specific-properties), but they still show in the UI, not sue if it's a bug or I did smth wrong.

**Comment by hugohaggmark** [comment]
I think you can redefine `NOOP_CONTROL` to `export const NOOP_CONTROL = { table: { disable: true } };` and they are all gone.

**Comment by Clarity-89** [comment]
> I think you can redefine `NOOP_CONTROL` to `export const NOOP_CONTROL = { table: { disable: true } };` and they are all gone.

That also removes the props from the props table in the Docs tab, which is smth we want to avoid.

**Comment by hugohaggmark** [comment]
> > I think you can redefine `NOOP_CONTROL` to `export const NOOP_CONTROL = { table: { disable: true } };` and they are all gone.
> 
> That also removes the props from the props table in the Docs tab, which is smth we want to avoid.

Aha ok, I understand. Then we need to wait for Storybook 6.2 that promises more control over the controls :)
