### ISSUE TITLE
GraphNG (Act 2)

### ISSUE THREAD

**Issue by leeoniya** [grafana/grafana#30564]
This is a follow-up to https://github.com/grafana/grafana/issues/27848 (Act 1).

Now that we have most work items finished, let's migrate the few remaining and future (planned and possible) things to this issue. Most of the items here are specific to **Time series**, but I'm leaving the title as GraphNG for continuity. Feel free to change it.

Please help me migrate any remaining features to this issue and let's close the old one.

Cleanup:
- [ ] Renames https://github.com/grafana/grafana/issues/32846

Old features (parity):

- [x] [ms precision in tooltip when user zoomed in enough](https://github.com/grafana/grafana/issues/36017)
- [ ] Stacking an inverted series (* -1 transform?) - Issues: https://github.com/grafana/grafana/issues/30365
- [x] Closest no-null datapoint focus https://github.com/grafana/grafana/issues/31309, https://github.com/grafana/grafana/issues/34542
- [x] stacking (by value, by %)  https://github.com/grafana/grafana/pull/30749
- [x] histograms (move to its own panel)
- [x] thresholds (y)
- [ ] regions (x) https://github.com/grafana/grafana/issues/35486
    - [ ] Bug: #15010 #28017
- [x] annotations
- [x] shared crosshair https://github.com/grafana/grafana/pull/33433
- [ ] sorting legend items #30907
- [x] stat panels no longer use a shared min/max for all graphs, which de-stabilizes ranges across the group. we should look into adding softMin/softMax to Stat, which was designed to stabilize graphs without giving up autoranging (#32765)
- [x] Hiding series via field options: https://github.com/grafana/grafana/issues/33013

New features:

- [ ] focus series on legend hover (torkel request)
- [ ] series symbols - Issues: #28528, PR: #30192
- [ ] padding autosizing - Issues: #33092
- [ ] explicit padding control (for aligning multiple charts) - Issues: #4469
- [ ] grid show/hide (x, y) - Issues: #9305
- [ ] axis tick label rotation - Issues: #3591
- [ ] axis coloring (to visually match series to their y scale) - Issues: #29932
- [ ] bar width control, expose barMaxWidth (for timeseries pseudo-histograms) - Issues: #14130, #18220, Related PR: #30499, Demos: https://leeoniya.github.io/uPlot/demos/line-paths.html (see bottom 2 charts)
- [ ] x/y rectangular zoom, y-only zoom - Issues: #9457
- [x] scale-affixed-gradients as hz or vt stroke or fill colors - Issues: #437, Demos: https://github.com/leeoniya/uPlot/issues/416, https://leeoniya.github.io/uPlot/demos/gradient-fill.html
- [ ] Axes position independent from unit config (https://github.com/grafana/grafana/issues/31002)
- [ ] Viz alignment regardles y-axis being shown or not: https://github.com/grafana/grafana/issues/33014

Add'l cool stuff:
- [ ] axis titles (could help, now that there can be 30 y-axes :D)
- [ ] axis tick & grid density control (can get more visual scale resolution without forcing a zoom)
- [ ] y-shifted series - Demos: https://leeoniya.github.io/uPlot/demos/y-shifted-series.html
- [ ] custom fillTo level (not always 0) - Demos: https://github.com/leeoniya/uPlot/issues/292
- [ ] ordinal/even scale distribution (skip periods with no data) - Demos: https://leeoniya.github.io/uPlot/demos/candlestick-ohlc.html (skips showing weekends)
- [ ] interactive legend calcs: https://github.com/grafana/grafana/issues/31629

Bugs / Perf:

- [x] fix tooltip flickering/perf (https://github.com/grafana/grafana/pull/33609 was reverted in https://github.com/grafana/grafana/pull/33866)
- [x] GraphNG: Time series panel Tooltip is cut off at the top #31098
- [x] avoid x axis label collisions - Issues: #30906
- [x] superfluous getConfig() calls during init
- [x] Selecting (hiding) series via legend is not working if those series has a display name change via an override https://github.com/grafana/grafana/issues/31364
- [x] Tooltip shows wrong colors: https://github.com/grafana/grafana/issues/32087
- [x] Cannot read property 'stroke' of undefined https://github.com/grafana/grafana/issues/31203
- [x] GraphNG: Unit not displayed correctly on the Y-axis - Issues: #33895
TODO...

Feature requests / future
- color by value, color by value mappings: https://github.com/grafana/grafana/issues/35310

**Comment by dprokop** [comment]
thanks @leeoniya for moving the remaing issues!

**Comment by rovo89** [comment]
Regarding feature parity, there were some **series overrides** which helped to keep the graph simple on first sight, but have an easy way to dig deeper:

- Hidden series
- Hide in legend
- Hide in tooltip

**Hidden series** means that the series is available in the legend, but not selected by default. I use this to display only the two most common status types by default, but have the other status types available on "standby".

With **Hide in legend**, I added some series (calculated fields) which provide additional details only in the tooltip:
![image](https://user-images.githubusercontent.com/1573299/105815292-fb4ee080-5fb2-11eb-974a-a308d24f5159.png)

A **Style = Hidden** option would be helpful for the latter. I used *Lines = false* in the Graph panel and *Line width = 0* / *Fill opacity = 0* / *Show points = never* for Time series. This kind of works, but is less intuitive and still doesn't hide the points on hover.

**Comment by sakjur** [comment]
fwiw, #25580 suggests that having the "Add annotations" pop up on click doesn't make sense if annotations are disabled.

**Comment by hugohaggmark** [comment]
This might be a feature request to consider? #31853

**Comment by allomorphy** [comment]
> This is a follow-up to #27848 (Act 1).
> 
> Now that we have most work items finished, let's migrate the few remaining and future (planned and possible) things to this issue. Most of the items here are specific to **Time series**, but I'm leaving the title as GraphNG for continuity. Feel free to change it.

Hi @leeoniya 

Is there a place to track all these yummy features that you and the team are implementing?
Our special favourite right now is **annotations**
Thanks for the great work 🤗

**Comment by underdog** [comment]
inquiry: is there a timeline (public link/chart) for when beta3 will hit the release queue?
Thanks!!!!!
and not sure you hear it enough, or at all, but thanks for all the hard work being put into grafana!!!!!

**Comment by leeoniya** [comment]
> inquiry: is there a timeline (public link/chart) for when beta3 will hit the release queue?

beta3 should be out this week. though i expect this issue to remain open until at least 8.1.

> and not sure you hear it enough, or at all, but thanks for all the hard work being put into grafana!!!!!

thanks for using the betas, and keep the bug reports / feedback rolling in! the development pace is picking up rapidly and things often slip through our internal tests as we try to get all the shiny features and enhancements out asap :)

**Comment by leeoniya** [comment]
pushing this to future to keep it top of mind and as a general work list, but AFAIK none of these items are blockers for releases.

**Comment by pepjo** [comment]
I am trying the shared tooltip functionality that the release notes say is now available for the new time series plot. However, while the old graph sharing crosshair works, it does not seem to work for the new time series. I wonder if there is a different setting that needs to be enabled.

**Comment by pepjo** [comment]
It seems that the soft min and max values are not respected when all the values in the series are 0. In this case, I have a plot that rarely goes over 1 or under -1. Hence, I would like to set the soft min and max to those values to have a consistent sense of scale, but allowing bigger numbers to be shown if they appear.
![image](https://user-images.githubusercontent.com/1307305/121779025-91b22600-cb91-11eb-9643-bd7c5b112925.png)

The plot, however, shows the values from 100 to -100 even though the soft max and min are set to 1 and -1. 

When a value is different than 0, then the soft min and soft max are respected.

![image](https://user-images.githubusercontent.com/1307305/121779173-40eefd00-cb92-11eb-87e1-2ddbefd66f4d.png)

**Comment by leeoniya** [comment]
@pepjo thanks for the soft limits bug report, https://github.com/grafana/grafana/pull/35596 should fix it.

**Comment by pepjo** [comment]
Thanks for such a quick fix!

**Comment by dprokop** [comment]
This one has been with us for a long time and majority of the items here are already tracked as independent issues/discussions. Closing this epic.
