### ISSUE TITLE
BarChart: New Panel for v8

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#30741]
This is an epic issue to collect small issues & todos for this new panel

Infrastructure:
* [x] hoooooks simplifications, mause use a PureComponent so functions don't need explicit cache
* [x] legend reuse and simplification

Features:
* [ ] gdev test dashboard
* [x] Tooltip (https://github.com/grafana/grafana/pull/33938)
* [x] Close tooltip in edge cases (moving mouse out from viz on the outer bar, pressing e on keyboard to go to edit mode)
* [ ] BarChart component missing unit test(s)
* [x] Better value font sizing and spacing? (and font face + color) https://github.com/grafana/grafana/pull/34229
* [ ] Better 'Auto' behavior for show values -- should depend on size/density, show on hover
* [x] default to a 0 softMin baseline? non-zero based bars are very easy to misinterpret and result in universally terrible charts.
* [ ] stacked mode
* [x] Use PanelContext for hiding series (https://github.com/grafana/grafana/pull/33955)
* [x] Move BarChart viz to core (https://github.com/grafana/grafana/pull/33947)

Bugs
* [x] The current layout algorithm distributes bars left-to-right within each respective bar group. this results in a bit of weird behavior when there is only 1 field (series) and the bar width is < 100% of the group width -- it looks like the axis labels are off-center, since they're centered _per group_, and the bars are not centered in the group, but left-anchored. the workaround is pretty easy: set the bar width to 100% and use the group width to control the "bar width". we can work around this by swapping out what the panel controls map to when the field count is 1. 
![image](https://user-images.githubusercontent.com/43234/106295523-2d13b180-6216-11eb-95ba-fd3567374230.png)

* [x] An issue with negative values and showing the value is still not perfect 
![Screenshot from 2021-01-29 15-56-44](https://user-images.githubusercontent.com/10999/106290307-9ad9d080-624a-11eb-88fd-f5c9580e6b02.png)

Post v8
* [ ] Multiple axes and/or units? a bit unusual but really helps with information density: https://leeoniya.github.io/uPlot/demos/multi-bars.html. we'd render the units as part of the bar values displayed, too.
* [ ] data links https://github.com/grafana/grafana/issues/34608

**Comment by leeoniya** [comment]
i have a bunch to add here today, for consideration

**Comment by torkelo** [comment]
great, just add away. that is the purpose of this issue :)

**Comment by torkelo** [comment]
Added a bug as well with negative values intersecting the border line

**Comment by leeoniya** [comment]
yeah, there's plenty of tweaking left to do. the quadtree hit areas for the rectangles are slightly off as well.

**Comment by torkelo** [comment]
Found two issues,
1) seem to require two numeric fields, does not work with only one:

<img width="808" alt="Screen Shot 2021-03-04 at 19 53 40" src="https://user-images.githubusercontent.com/10999/110014772-77abb080-7d23-11eb-803e-d605b132dba3.png">

2) Does not handle the scenario where a data frame only contains a single row but many fields 

<img width="1078" alt="Screen Shot 2021-03-04 at 19 23 06" src="https://user-images.githubusercontent.com/10999/110014845-8db97100-7d23-11eb-995d-da16f6ae23cb.png">

The bar gauge panel does support this data format funnily (bar gauge above), and the opposite is true, the format bar chart support does not work with bar gauge 😢

**Comment by leeoniya** [comment]
#31703 fixes the first issue.

for the second, not sure it's a good idea to handle a transposed format. i guess we'd have to rely on special-case heuristics of the string-field's values? that being said, i _would_ like to see these panels get merged into one. not sure how realistic that is, though.

**Comment by dprokop** [comment]
Closing this in favor of followup issues created:
https://github.com/grafana/grafana/issues/36709
https://github.com/grafana/grafana/issues/36705
