### ISSUE TITLE
AzureMonitor: React Migration

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#30794]
This is an epic issue to collect and track the migration of the Azure Monitor datasource plugin to React, and improvements to the query editors, in a rough logical order

 - [x] Port Metrics to React
    - [x] Rewrite UI in React https://github.com/grafana/grafana/issues/31108 PR: https://github.com/grafana/grafana/pull/30783
    - [x] Error handling https://github.com/grafana/grafana/issues/31109
    - [x] Make "empty" query values actually nullable https://github.com/grafana/grafana/issues/31086
 - [x] Port Logs to React
 - [x] Loading indicators on dropdowns https://github.com/grafana/grafana/issues/31083
 - [x] Use Monaco for KQL editor PR https://github.com/grafana/grafana/pull/33528
 - [x] Deprecate Application Insights and Insights Analytics https://github.com/grafana/grafana/issues/30184
     - [x] Create read-only view for App Insights https://github.com/grafana/grafana/issues/32789
     - [x] Create read-only view for Insights Analytics https://github.com/grafana/grafana/issues/32790
 - [x] Basic UI-less Resource Picker for Logs https://github.com/grafana/grafana/issues/33700
 - [x] Resource Picker UI https://github.com/grafana/grafana/issues/33704
 - [x] Logs Resource-centric queries https://github.com/grafana/grafana/issues/33705
 - [x] Switch QueryEditor entry point to React (remove Angular) https://github.com/grafana/grafana/issues/33706
 - [x] Resource Picker for Metrics https://github.com/grafana/grafana/issues/44439
 - [ ] Use `VisualQueryBuilder` from ADX for Logs queries
     - [ ] Consider: performance of metadata queries 
     - [x] Bug: whole "where" line not removed https://github.com/grafana/azure-data-explorer-datasource/issues/121
 - [ ] Replace variable macros with query builder
 - [ ] Documentation

**Comment by andresmgot** [comment]
Azure Monitor plugin already uses React for all its components.
