### ISSUE TITLE
Chore: Get rid of global state in the backend

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#31033]
We have a goal to get rid of the global state in the backend in order to make the code mode stable, easily portable & testable to other environments. 

Todo
* [ ] Plugins package https://github.com/grafana/grafana/issues/29022
* [ ] Settings package https://github.com/grafana/grafana/issues/29021  
* [ ] TSDB registry (Create TsdbService that holds the registy)( 
* [ ] API handlers
* [ ] sqlstore handlers
* [ ] Global acccess of the bus 
* [ ] Alerting query eval (uses tsdb.HandleRequest) 
* [ ] Expression eval (uses tsdb.HandleRequest)
* [ ] Service registry (could be tricky)
