### ISSUE TITLE
Dashboard as code Grafana

### ISSUE THREAD

**Issue by ying-jeanne** [grafana/grafana#31038]
This is the dashboard as code EPIC:

We aim to find have a better solution for our customer to manage their dashboards from 2 different perspectives:
1. Easy or improve user experience to manage dashboard JSON via git 
2. Instead of store JSON, we have also Grafonnet to generate a dashboard programmatically, how to make provisioning modifiable in the future.

What is realistic for Q1:
- [ ] Spike of the EPIC, different solutions, benchmark, sizing, and roadmap for Q1 and Q2. 
https://github.com/grafana/grafana/issues/31047 sizing: 5

For solution 1
- [x]  we would decrease export dashboard size by removing the default values prototype: 
https://github.com/grafana/grafana/issues/13887 sizing 13
- [x] integrate the solution into Grafana code with frontend changes. 
https://github.com/grafana/grafana/issues/31044 sizing 8

- [ ] export JSON with reference than repeating several times the same object? 
https://github.com/grafana/grafana/issues/17887 sizing ?
 
- [ ] Integrate Github workflow (add a button to allow create a pull request from Grafana?)
- [ ] Integrate Github workflow inside Grafana (having pending, committed changes with approval mechanism?)

- [ ] Interface cleanup (adding schema version, panel type, remove Id from the interface, etc.)

Other ideas:
- [ ] provide a Grafonnet viewer? So we could see the dashboard changes before load.

**Comment by philomory** [comment]
Could we maybe also address #17887 at the same time? I feel like that would have as big an impact as #13887, or possibly even bigger.

**Comment by BertHartm** [comment]
@ying-jeanne can https://github.com/grafana/grafana/issues/17475 be considered as part of this as well? that's a rough one for editing dashboards if they aren't being saved to a database.

**Comment by RogersBryan** [comment]
It would be great if there was some sort of plugin to allow grabbing data from GitHub Actions/GitHub Workflows and providing Dashboard views for this. As many across the industry are switching to a DevOps model and adopting GitHub Actions for their CI/CD flows, there is no default "Dashboard" built in for visibility purposes. Having a plugin that provides these capabilities in Grafana would be highly valuable.

**Comment by ying-jeanne** [comment]
> It would be great if there was some sort of plugin to allow grabbing data from GitHub Actions/GitHub Workflows and providing Dashboard views for this. As many across the industry are switching to a DevOps model and adopting GitHub Actions for their CI/CD flows, there is no default "Dashboard" built in for visibility purposes. Having a plugin that provides these capabilities in Grafana would be highly valuable.

what do you mean by "grabbing data from Github actions/github workflows"? like how many workflows are triggered and whether it is successfully ran?

**Comment by ying-jeanne** [comment]
with the multistorage feature ongoing, this ticket is no longer needed.

**Comment by WillSewell** [comment]
@ying-jeanne could you link to more context on the "multistorage feature" please?

**Comment by Atrbear** [comment]
@ying-jeanne could you please link some infomation about "multistorage feature" please? Will storage include git reposity?
