### ISSUE TITLE
HTTP API improvements

### ISSUE THREAD

**Issue by ying-jeanne** [grafana/grafana#31096]
Today we don't have backend API documented yet. The objective of the EPIC is to create openAPI for existing services and define the workflow for future API changes. (code would update swagger? swagger would generate code? etc.)
 
- [ ] Study existing solutions to generate openAPI with the code. The result of the study would be faisable or not + Spike.   
       The spike: https://docs.google.com/document/d/1Le8w5X18ao5txChx_iBZR-85eukR6ILMv_pU7aYeAxY/edit   
       Issue: https://github.com/grafana/grafana/issues/31073
- [ ] Regarding the study implement API generation (whether manually or automatically)
- [ ] Define the new manual workflow for updating API.
- [ ] Identify the part of the workflow that we could automate and define what to be done further.

**Comment by aknuds1** [comment]
I think this overlaps with https://github.com/grafana/grafana/issues/31073.

**Comment by ying-jeanne** [comment]
> I think this overlaps with #31073.

I linked it as the user story of the EPIC for step 2 :)

**Comment by aknuds1** [comment]
Where's the link? Don't see it.

**Comment by ying-jeanne** [comment]
![image](https://user-images.githubusercontent.com/74549700/107520225-7b7b6580-6bb1-11eb-9f46-3ec4779b2626.png)

you can click on "Add issues to the Epic", it would link the tasks to the Epic.
