### ISSUE TITLE
PieChart: New core plugin / visualization

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#31116]
* [x] Basic display & options 
* [x] Legend below or to the right
* [x] Legend stats percent and or value, think there needs to be handled a bit differently than the legend stats in the graph as the panel already has reduced values so these are not exactly the same 
* [x] Change color from legend (saved as override) 
* [x] Data links support 
  * [x] Bug, data links do not work: https://github.com/grafana/grafana/issues/32637
* [x] Add migration for [PieChart](https://grafana.com/grafana/plugins/grafana-piechart-panel) -> PieChart NG
* [x] Add e2e test (#33737)
* [x] Hover over legend to highlight pie piece (needs a big change in legend component) (#32941)
* [x] Move DataFrame -> FieldDisplay values into PieChart componet so PieChart component takes in data: DataFrame[] prop  instead of fieldDisplayValues 
* [x] Unify Tooltip to look the way it looks in TimeSeries (preferably use the same components) #33032
* [ ] Legend & tooltip - unify panel options creation between timeseries & piechart ([addLegenOptions](https://github.com/grafana/grafana/blob/45eaf3cfdc733f294ec1f2dc954175eeda30ef0e/public/app/plugins/panel/timeseries/config.ts#L283), addTooltipOptions)
* [ ] Change the hover & highlight to one down the other slices (using opacity) (#33778)

|   |   |
|---|---|
| ![image](https://user-images.githubusercontent.com/2376619/111484122-be42d700-8735-11eb-9fce-0a0b9b1bb3cb.png)  |  ![image](https://user-images.githubusercontent.com/2376619/111484391-019d4580-8736-11eb-9d7e-8ddc5fefbf16.png) |

* [ ] Make it possible to toggle series on/off via legend (#33756) (see how it's done in time series panel: https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/timeseries/TimeSeriesPanel.tsx#L28)
* [x] Fix storybook (#33696)

For it to look good by default we need a new color palette! (using the named colors), planed for v8

**Comment by torkelo** [comment]
linked initial PR: https://github.com/grafana/grafana/pull/28020

**Comment by torkelo** [comment]
How to use VizLayout & Legend: 
https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/GraphNG/GraphNG.tsx#L320

**Comment by ralequi** [comment]
This plugin requiere the "other" option that the original piechart has.

**Example**: You have > 50 things to be shown on the piechart, but just a few (let's say 3 of them) have >90% of the cake. Resume the remaining 47 element into one piece called "others" (or a custom text) is necessary for great visualization.

Thanks for the new version. Looks good.
