### ISSUE TITLE
Epic: Panel Edit UX improvements

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#31279]
* [ ] Move visualization picker to the top
* [ ] Unify field default and panel option tabs into one
* [ ] Figure out new ux that does not require tabs and improve
* [ ] Allow panel plugins to control the order 
* [ ] Search across all options and overrides
* [ ] Link to visualization documentation

**Comment by torkelo** [comment]
closing in favor of https://github.com/grafana/grafana/issues/32244
