### ISSUE TITLE
Epic: enhancements in Grafana App API

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#31381]
This is an epic issue to keep track of findings that I believe we can improve in the App API when building App Plugins for Grafana.

**Areas of improvement:**

- [ ] Routing should be built in in the API so you don't have to implement your own routing.
- [ ] Page components being used in Grafana should be accessible from grafana/ui so it can be used instead of using the `onChangedNav` hack.
- [ ] The configuration page should probably have the `enabled/disabled` functionality built in since it feels like an standard setting used for all apps.

**Comment by mckn** [comment]
Super, I will add more things to this issue as I work my way through the app.

**Comment by besartberisha** [comment]
Thank you @mckn for opening this, this is really convenient.

Okay so lately there has been a request to add external links to the dropdown menu of the plugins, now based on what I could find is that the functionality is there, we can add external links to the menu but we need to enable that the external links to be open on a new tab, instead of on the same page.

![Screenshot 2021-02-19 at 16 39 59](https://user-images.githubusercontent.com/7255779/108686453-bc4e7500-74f5-11eb-9bea-54a9f675b49b.png)

Maybe we can also add an optional icon as well to distinguish external links from internal ones? 
cc: @richardqlam @oanamangiurea

**Comment by mckn** [comment]
> This is an epic issue to keep track of findings that I believe we can improve in the App API when building App Plugins for Grafana.
> 
> **Areas of improvement:**
> 
> * [ ]  [Page components being used in Grafana should be accessible from grafana/ui so it can be used instead of using the `onChangedNav` hack. #40057](https://github.com/grafana/grafana/issues/40057)
> * [ ]  The configuration page should probably have the `enabled/disabled` functionality built in since it feels like an standard setting used for all apps.

This is added as part of the plugins catalog.

> * [ ]  Routing should be built in in the API so you don't have to implement your own routing.

This is possible by using the react router.

> * [ ]  Add possibility to extend the dashboard panel menu with links into the app plugin.

Not yet possible. Opened a feature request for this: https://github.com/grafana/grafana/discussions/44004

> * [ ]  Add possibility to extend the plugin menu with external links ([Epic: enhancements in Grafana App API #31381 (comment)](https://github.com/grafana/grafana/issues/31381#issuecomment-783219163))
> * [ ]  Enable full width in app plugins template [requested by Cloud].
> * [ ]  Allow app plugins to have same menu UI as Grafana core.
