### ISSUE TITLE
Routing migration: Act 2

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#31873]
Folloup for https://github.com/grafana/grafana/issues/31548 & https://github.com/grafana/grafana/pull/31463

## TODOs
- [ ] Get rid of ngInject annotations
- [x] implement `RouteParamsProvider`
- [x] implement `RouteProvider`
- [ ] implement Angular $location compat API methods in the `LocationService` https://github.com/grafana/grafana/pull/31773
	- [x] `path`
	- [x] ~`hash`~
	- [x] `search`
	- [x] `url`
	- [x] make sure all of the above implementations are marked as deprecated and have deprecation warnings https://github.com/grafana/grafana/pull/31898
	- [ ] remove usages or injected $location provider  
- [x] POC API for AppPlugins
- [x] Migrate playlist routes
	- [x] Migrate playlist views to React (ref https://github.com/grafana/grafana/issues/21484)
- [x] Verify all routes migrated
- [x]  Route reload in dashboard page - think about "cleaner" way of handling forced reloads, ref #31683, alternative implemented in #31952
- [ ]  uploadDashboardDirective - refactor to React (used in cloud-monitoring ds)
- [x] Singlestat - remove the panel (using $location, i't to be depracated in v8)
- [x] HistoryListCtrl - to be removed in @jackw DashboardSettings migration work (using $location) https://github.com/grafana/grafana/pull/31997

Pages
- [x] Playlist list edit (needs angular to react migration) 

Bugs
- [x] Variable picker reverts to `All` when opening it (#31942)
![bug1](https://user-images.githubusercontent.com/562238/110928082-c27e8700-8326-11eb-8caa-8dd9d827e27a.gif)
- [x] Infinite reload after saving a dashboard ![avatar](https://github.com/dprokop.png?size=24) #31952
  ![bug2](https://user-images.githubusercontent.com/562238/110928651-6bc57d00-8327-11eb-8fe0-df9a62ba5f8c.gif)
- [x] I deleted a dashboard and confirm modal showed up, clicked Delete and got redirected to home dashboard, but modal didn't close https://github.com/grafana/grafana/pull/32033
- [x] time range zoom not working https://github.com/grafana/grafana/issues/32010
- [x] DataLinks: disabling "open in new tab" toggle causes URL to break
  - [x] Maybe related: DataLinks: DataLinks with absolute links are not working

https://user-images.githubusercontent.com/29557702/111775049-89a75a80-88b0-11eb-976c-19e358e09d18.mov

**Comment by dprokop** [comment]
@hugohaggmark ref second bug you reported:  We use history.state to force reload pages that are query parameter dependant. History state is persistent between reloads, and after saving the dashboard this state is set (forceRouteReload). We clean this state when route requiring force reload is updated. But if you refresh the page, componentDidUpdate will not fire, and the state will persist. I'll work on another solution for this. @torkelo your prophecy about this being problematic comes true :D

**Comment by oanamangiurea** [comment]
Other reported bug: RoutingNG: wrong datasource shown in explore coming from a panel  #32221

**Comment by dprokop** [comment]
> Other reported bug: RoutingNG: wrong datasource shown in explore coming from a panel 

Not related to RoutingNG
