### ISSUE TITLE
Epic: Panel Edit UX & ease of use enhancements 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#32244]
Todo
* [x] Move visualization picker to the top
* [x] Integrate visualization selection with library panel selection 
* [x] Unify the Panel options & Field options 
* [x] Add simple search for all options 
* [x] More advanced search for options that rank hits
* [x] Hide override options for panel without field override options 
* [x] Highlight matched word fragments 
* [x] Show which properties have overrides with a colored dot & tooltip
* [ ] Click on colored dot should add property name to search box 
* [ ] Search on property value 
* [ ] Collapse / expand query section 
* [ ] Support many Variables better via showing dropdowns in popover 

Ideas to test & explore (requires UX exploration) 
* [ ] Improve option categorization and naming 
* [ ] A way to collapse/expand all sections 
* [ ] How to show panel help & docs link
* [ ] Explore suggestions of real visualizations with current data 
* [ ] A way for sections to have descriptions 
* [ ] A way for sections to show help info (Like for Time series > Axis section to describe that axis unit and hard min/max is set in standard field options) 
* [ ] A way to configure the options pane
   * [ ] Show/hide section descriptions 
   * [ ] Show/hide field descriptions 

PRS
https://github.com/grafana/grafana/pull/32124

**Comment by jessover9000** [comment]
Ran the first usability test today and found a few issues that might be bugs (seemed like glitches to the user and I). The test was run with the time series panel. What we found:

### Visualization picker
- [ ] In the visualization list, the user had to click a visualization card twice in order to collapse the viz picker / on first click it didn't collapse
- [ ] In the visualization type cards, for long titles the signature label gets pushed out

### Radio groups
- [ ] When the user changed some radio group options, e.g. the gradient mode, the visualization changed but the highlight in the radio group stayed on the first option instead of switching to the second one

### Color schemes
- [ ] The user wanted to pick "single color" instead of a color scheme, and the graph changed to a single color but the dropdown/picker didn't change and still displayed the Color scheme selected. so the user wasn't able to adjust the color for the graph

### Recent tab
- [ ] The user changed some settings like line width, and they never showed up in the list of recent changes. So the user got confused about what the "Recent" list actually does or how it works. Bug or feature?
- [ ] When the user changed the line width, jumped to the recent tab and back to the "All" tab, the line width in the graph had changed but the input/slider for the setting had reset to the previously set value
