### ISSUE TITLE
Epic: V8 Theming updates

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#32784]
Theme updates required for 8.0

# Theme model work
* [x] Initial new theme model in place
* [x] Add transitions to theme
* [x] Add backward compatibility as much as possible 
* [x] Add tokens to support Alerts & Info boxes 
* [x] Add branding gradients 
* [x] Add typography to theme 

# Update to new theme model
* [x] Update button component to use new theme https://github.com/grafana/grafana/pull/32767
* [x] Migrate old card sass file to GlobalStyles #33183
* [x] Update inputs to use new theme 
* [x] Update Select to use new theme and new layer 
* [x] Update so all form components use v2 theme 
* [ ] Update SideMenu & Page components so they use the new theme (Page: #33413 & #33529)
* [x] Update code that uses "btn" classes to use new react Button components 

# Bugs
* [x] Link variant button cannot use standard filled disabled button style, bugged in TagsInput

# Component work
* [x] Update implementation of ShowConfirmModalEvent to use react modal (#33107)
* [x] Add ButtonStyle type & prop to buttons that is Contained (default) | Outline | Text   , map old ButtonVariant link to ButtonStyle text (#33384)
* [x] Add variant prop to IconButton so can have red & blue icon buttons (#33479)

# Update old component usage
* [x] We have some places that use the old btn btn--primary clases, we should update these to the grafana/ui use react components (#33226)
* [x] Get rid of all angular modals (#33476)

# Move styles to emotion 
* [x] Move body & html styles to emotion GlobalStyles
* [x] Move dashboard styles to emotion #32955
* [x] Move Panel styles to emotion #33115
* [x] Remove outline.js https://github.com/grafana/grafana/issues/32858

# Theming infra 
* [x] Update emotion to 11
* [x] Performance benchmarks to understand how to use it best

Focus state:
use https://github.com/WICG/focus-visible 
https://github.com/mui-org/material-ui/blob/next/packages/material-ui-utils/src/useIsFocusVisible.js

**Comment by hugohaggmark** [comment]
Will this issue be solved with the new theming? https://github.com/grafana/grafana/issues/32852

**Comment by thisisobate** [comment]
> Will this issue be solved with the new theming? #32852

Yeah...I think so.

**Comment by danmx** [comment]
Will this version include ability to define custom themes (https://github.com/grafana/grafana/issues/10495)?
