### ISSUE TITLE
Epic: bring new CUE-based config schema system to release-readiness

### ISSUE THREAD

**Issue by sdboyer** [grafana/grafana#33139]
#32527 introduces the skeleton of the "scuemata" system for schematizing Grafana objects (primarily dashboards and their constituent parts to start). There's lots of work left to do before the whole system is actually mature enough to power Grafana 8. This epic is intended to enumerate the remaining work.

[This doc](https://docs.google.com/document/d/1qp3flLb6q1dPqTmHQ6MV-o6lOmlctfMNpzTx2MdzucY) contains background on the architecture of the system. As indicated in the original PR, the goal of the system is to create patterns for defining canonical schemas for Grafana config objects, such that those schema can be consumed for a [variety of purposes](https://docs.google.com/document/d/1qp3flLb6q1dPqTmHQ6MV-o6lOmlctfMNpzTx2MdzucY/edit#heading=h.7mt72zf53p82) across the three target languages - TypeScript, Go, and CUE.

The outstanding TODOs are broken down into some categories.

**Automation**
We need commands to perform some tasks automatically. Some of these need to work for plugin authors, as well.
- [ ] Assemble files into cue/* dirs from packages/* dirs (+ do in CI). (Replace the hacky [cuegen.sh](https://github.com/grafana/grafana/blob/master/scripts/cuegen.sh))
- [ ] CLI command for running cuetsy generation of various plugins (+ do in CI)
- [ ] CLI command to perform CUE linting (+ do in CI)
- [ ] CLI command to validate basic scuemata family invariants (+ do in CI)
- [ ] System for snapshotting existing CUE files at release time for future CI checks to prevent unintentional breakages

**Docs**
We'd like to avoid much direct user-facing interaction with this system. A side effect of that would be that, at least for Grafana 8, this system ought not require a big user-facing section in our docs. But still, we need some things.
- [ ] Example `models.cue`/whatever files for plugin authors to follow
- [ ] Docs on [schema](https://github.com/grafana/grafana/tree/master/pkg/schema) and [load](https://github.com/grafana/grafana/tree/master/pkg/schema/load) packages need to be finalized
- [ ] Some example-laden docs explaining our reasoning behind when fields should be optional, and when they should have defaults

**Backend**
The backend is a, and initially the, key [consumer of the system's Go API](https://docs.google.com/document/d/1qp3flLb6q1dPqTmHQ6MV-o6lOmlctfMNpzTx2MdzucY/edit#heading=h.nnhp8p2zisny).
- [ ] REST endpoint for retrieving JSON Schema representing panels and dashboards, generated from CUE
- [ ] REST endpoint for trimming defaults from an object
- [ ] `InstanceDashboardFamily()` to accompany [Base and Dist](https://docs.google.com/document/d/1qp3flLb6q1dPqTmHQ6MV-o6lOmlctfMNpzTx2MdzucY/edit#heading=h.2252p3xs7l7c) loader implementations (requires registry, plugin dir, etc.)
- [ ] Selectively wrap CUE errors with better explanations on paths that are particularly common for people to hit

**Frontend**
The [frontend](https://docs.google.com/document/d/1qp3flLb6q1dPqTmHQ6MV-o6lOmlctfMNpzTx2MdzucY/edit#heading=h.a9edw79l0qn0) will be insulated from details of families and lineages, dealing only with the most recent version of schemas.
- [ ] Use JSON Schema in panel JSON view
- [ ] Add button to remove defaults in JSON view

**CUE**
- [ ] Create [scuemata family definition](https://docs.google.com/document/d/1qp3flLb6q1dPqTmHQ6MV-o6lOmlctfMNpzTx2MdzucY/edit#heading=h.ujeqgyxihmn2)(s?) for datasource plugins, like [`#PanelFamily`](https://github.com/grafana/grafana/blob/0a3e7dea6234eb6045d1fa0d28c054dedbf6e750/cue/scuemata/panel-plugin.cue)
  - [ ] Create family defs for all datasource plugins using the above
- [ ] Create family defs for all panel plugins
- [ ] Create schema for all [core components](https://docs.google.com/document/d/1qp3flLb6q1dPqTmHQ6MV-o6lOmlctfMNpzTx2MdzucY/edit#heading=h.g9yvg0l8093k); also, finalize how these work (file & package names, etc.)
- [ ] Finalize the actual dashboard schema so we can, y'know, use it

**Scuemata system**
- [ ] Make the [Resource type](https://github.com/grafana/grafana/blob/0a3e7dea6234eb6045d1fa0d28c054dedbf6e750/pkg/schema/schema.go#L269-L272) into something actually useful- [ ] Generalize [compositional scuemata](https://docs.google.com/document/d/1qp3flLb6q1dPqTmHQ6MV-o6lOmlctfMNpzTx2MdzucY/edit#heading=h.vcg9e8vrkgbx); convert dashboard scuemata to the generic system
- [ ] General approach to [composing scuemata version metadata](https://docs.google.com/document/d/1qp3flLb6q1dPqTmHQ6MV-o6lOmlctfMNpzTx2MdzucY/edit#heading=h.kltz6aredkdy) into schema
- [ ] Implement [`ApplyDefaults()`](https://github.com/grafana/grafana/blob/0a3e7dea6234eb6045d1fa0d28c054dedbf6e750/pkg/schema/schema.go#L29) (can it be a func instead of a method? 🙏)
- [ ] Implement [`TrimDefaults()`](https://github.com/grafana/grafana/blob/0a3e7dea6234eb6045d1fa0d28c054dedbf6e750/pkg/schema/schema.go#L34) (can it be a func instead of a method? 🙏)
- [ ] Fix up `Migrate()` implementations

**Verification**
- [ ] Testing harness + cases for migrations
- [ ] Testing harness + cases for panel plugins
- [ ] Testing harness + cases for datasource plugins

**Comment by justinTM** [comment]
@sdboyer hi Sam does this mean CUE is not being worked on by Grafana?

**Comment by sdboyer** [comment]
@justinTM oh sorry, no! we definitely are, heavily. See the [area/scuemata](https://github.com/grafana/grafana/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fscuemata) label, and [this discussion](https://github.com/grafana/grafana/discussions/39593) is a quick sketch of what we're planning on.

We've been doing our work sorta stealthily to this point, but in 8.3 we plan to put a clearer public face on it.

**Comment by justinTM** [comment]
@sdboyer beautiful. appreciate your candid details in all your replies!

i just took a step back from two months of trying to templating dashboards-as-code for my employer and i think i will freeze development on that nasty Terraform JSON templating thing and instead keep a close eye on CUE and changes to grafonnet.

thanks again

**Comment by sdboyer** [comment]
I'm quite hopeful you'll be pleased with what we've come up with 🙂
