### ISSUE TITLE
Epic: Unified alerting

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#33198]
This is an epic issue to track work that needs to be done in the new unified alerting functionality. Try to group the tasks to make it easier to find what you are looking for. This epic is mainly used to track the frontend work.

**Questions**:
- [x] What kind of time ranges should you be able to select in the TimeRangePicker when adding queries? Disable the possibility to select absolute time ranges? (yes)
- [x] When creating a system rule we currently only have a single `expression: string` field. How should we handle that in combination with the QueryEditor. (only the metric + text field for query)

**QueryEditor**:
- [x] Add query editor when creating threshold alert (https://github.com/grafana/grafana/pull/33123).
- [x] Make sure that we map the `RelativeTimeRange` to quick ranges in the TimeRangePicker list when possible.
- [x] Move the `AlertingQueryRows` and `AlertingQueryEditor` to the `unified alerting` folder structure.
- [x] Rename the `GrafanaQuery` and `GrafanaQueryModel` in alerting to something similar to the other `DataQuery` types that exists in Grafana. (#34714)
- [x] Make it possible to execute queries from "create alert" page.
- [x] I've noticed on master when creating an alert, when I change the datasource, the datasourceUid is not updated, just the name.
- [ ] If we can't find the selected datasource display an error to the user. (AlertingQueryRow.tsx:62)
- [ ] Implement take until in the AlertingQueryRunner so we don't rely on the backend srv implementation that is deprecated.
- [ ] Write react-testing library tests for the AlertingQueryEditor.
- [x] Change so we change the size of the visualization depending on size of the query result.
- [x] Use AutoSizer to handle screen resizing

**Relative Time Range:**
- [x] Add different form error message depending on the validation error. (#34730)
- [x] Change default time range to now-1h

**Alert list view**:
- [x] Proper error handling when things goes bananas.

**Visualization**
- [x] Removed fixed height. Table "needs" a fixed height so that's why it's hard coded. Could make it dynamic depending on number of values or something.
- [x] Investigate why the graph line does not cover the entire width of the graph on longer time ranges.
- [x] Rearrange some of the markup so that drag n drop snapshot is the query row + vis. Also so that collapsing a row hides editor + viz. (#34658)

**General**:
- [x] Clean up the alerting folder structure and remove unused code.
    - [x] actions from ng alerting
- [ ] ~~Make alerting type a radio button group instead of dropdown~~
- [x] ~~Refactor alert rule page to use redux instead of react-hook-form~~

**Expressions**
- [ ] Fix issue with classic conditions value input. Throws error when removing value to write a new one. 
     `react-dom.development.js:67 Warning: Received NaN for the `value` attribute. If this is expected, cast the value to a string.`

**Style tweaks**:
- [x] Add some `padding-right` to the AlertingQueryEditor

**Comment by mckn** [comment]
Closing this one since we have fixed all of the important things and will setup individual issues for future work.
