### ISSUE TITLE
Update grafana-ui components so they use new theme

### ISSUE THREAD

**Issue by thisisobate** [grafana/grafana#33264]
**Why is this needed**:
Since our goal is to improve the look and feel of Grafana, we want to update the UI components to use the new theme model. Below is a list of all components that make use of the old theme model.

Relates to #32784

- [x] Alert/Alert.tsx 
- [x] AlphaNotice/AlphaNotice.tsx 
- [ ] Badge/Badge.tsx 
- [ ] BarChart/BarChart.tsx #33266
- [x] Button/Button.tsx
- [x] Button/ButtonGroup.tsx #33302
- [x] Button/ToolBarButtonRow.tsx #33305
- [x] ButtonCascader/ButtonCascader.tsx #33306
- [ ] CallToActionCard/CallToActionCard.tsx #33309
- [x] Card/Card.tsx
- [ ] Collapse/Collapse.tsx #33326
- [x] Collapse/CollapsableSection.tsx #33378
- [ ] ColorPicker/ColorPicker.tsx
- [ ] ColorPicker/ColorInput.tsx #33387
- [ ] ColorPicker/SpectrumPalette.tsx #33385
- [ ] ColorPicker/NamedColorsPalette.tsx 
- [ ] ConfirmButton/ConfirmButton.tsx
- [x] ConfirmModal/ConfirmModal.tsx
- [x] CustomScrollbar/CustomScrollbar.tsx
- [x]  DataLinks/DataLinkInput.tsx
- [ ] DataLinks/DataLinksInlineEditor/DataLinksInlineEditor.tsx #33391
- [x] DataLinks/DataLinksInlineEditor/DataLinksListItem.tsx #33392
- [x] DataLinks/DataLinksEditor.tsx #33389
- [ ] DataLinks/DataLinkSuggestionsInput.tsx  #33390
- [ ] Drawer/Drawer.tsx 
- [ ]  Dropdown/ButtonSelect.tsx 
- [ ] FormField/FormField.tsx 
- [ ] Forms/FieldValidationMessage.tsx 
- [ ] Forms/Form.tsx 
- [ ] Forms/Legacy/Input/Input.tsx 
- [ ] Forms/Legacy/Select/Select.tsx
- [ ] Forms/Legacy/Switch/Switch.tsx
- [ ] Forms/Legend.tsx
- [ ] Forms/RadioButtonGroup/RadioButtonGroup.tsx
- [ ] Graph/Graph.tsx
- [ ] Graph/GraphWithLegend.tsx
- [ ] GraphNG/GraphNG.tsx
- [ ] InfoBox/InfoBox.tsx
- [ ] Input/Input.tsx
- [ ] Layout/Layout.tsx
- [ ] List/List.tsx
- [ ] Modal/Modal.tsx
- [ ] Monaco/CodeEditor.tsx
- [ ] Pagination/Pagination.tsx
- [ ] PieChart/PieChart.tsx
- [ ] SecretFormField/SecretFormField.tsx
- [ ] Select/Select.tsx
- [ ] Slider/RangeSlider.tsx
- [ ] Slider/Slider.tsx
- [ ] Spinner/Spinner.tsx
- [ ] StatsPicker/StatsPicker.tsx
- [ ] Switch/Switch.tsx
- [ ] Table/Table.tsx
- [ ] TextArea/TextArea.tsx
- [ ] Tooltip/Tooltip.tsx
- [ ] ValuePicker/ValuePicker.tsx
- [ ] VizLayout/VizLayout.tsx
- [ ] VizLegend/VizLegend.tsx
