### ISSUE TITLE
Library Panels: UX improvements

### ISSUE THREAD

**Issue by jessover9000** [grafana/grafana#33363]
Hey team! Reviewed the status quo of the feature. Some nitpicks (not sure whether just issues with my Grafana or yet to be fixed):

- [X] The terminology is a bit messy, some places say library panel, some places global panel. The user research resulted in "Shared panels" so we should remember to check all the views for the right wording 🤓 Could also change "Add current panel to library" button to "Share current panel to library". ![avatar](https://github.com/kaydelaney.png?size=24) (#33540)
- [ ] For me once a panel is added to the library, the panel edit still looks almost identical. The save button text changing is the only feedback I get as a user that I'm not editing a regular panel. In the original design there was supposed to be the reusable panel icon depicted in the top left with the panel name, and also the description "Shared panel" under the title. I recommend that we add that in there
- [ ] The "Global panel information" somehow feels out of place within the options dropdown, since those are not options but just information. Could we just show that info either above the dropdowns in the panel settings, or maybe even as part of the subtitle on the left? See a mockup here:
![image](https://user-images.githubusercontent.com/53754871/115887507-49f50500-a452-11eb-811b-e065f5422e77.png)

- [ ] Since the shared panels are now part of the visualization picker, I think if you search for something while the picker is expanded search results should include both visualizations and global panels (in the panel settings the search also spans all tabs).
- [ ] The visualization picker tooltip should say "Click to change visualization or replace with a shared panel" ![avatar](https://github.com/kaydelaney.png?size=24)
- [ ] The search box placeholder text should say "Search for visualizations or shared panels" ![avatar](https://github.com/kaydelaney.png?size=24)
- [x] The Shared panels / Global panels tab should get an info icon with a tooltip that explains more about what those panels are and links to the docs ![avatar](https://github.com/kaydelaney.png?size=24) (#33428)
- [x] The modal for "Change to library panel", I think we should write "Replace with library panel" because that explains more clearly what happens there. ![avatar](https://github.com/kaydelaney.png?size=24) (#33424) 

**Managing the panel library**
- [x] Could we just add a sort dropdown and a filter dropdown under the search box similarly to the manage dashboards view? (#33425)
![image](https://user-images.githubusercontent.com/53754871/115887682-76108600-a452-11eb-87fb-838dea1853e9.png)
We might not need the folder vs list view for now, and no blue buttons in the top either, so just those dropdowns left and right. The filter dropdown could be "Filter by visualization type" instead of by tag. That would keep the views sort of consistent for now until we have redesigned the top navigation and adapted the filtering to maybe include tags and other advanced features
- [x] If we introduce a filter there, maybe in the panel edit panel library tab such a filter could also be useful? (#33425)
- [x] Should panel description be shown in the global panels list? I'm thinking it could be useful to understand better what each panel is about (#33452)

_Originally posted by @jessover9000 in https://github.com/grafana/grafana/issues/31305#issuecomment-825709145_

**Comment by kaydelaney** [comment]
Some thoughts:

> For me once a panel is added to the library, the panel edit still looks almost identical. The save button text changing is the only feedback I get as a user that I'm not editing a regular panel. In the original design there was supposed to be the reusable panel icon depicted in the top left with the panel name, and also the description "Shared panel" under the title. I recommend that we add that in there

For me it looks like this:
![image](https://user-images.githubusercontent.com/45561153/116247378-b299f580-a762-11eb-91de-5fe123d13d5d.png)

>Since the shared panels are now part of the visualization picker, I think if you search for something while the picker is expanded search results should include both visualizations and global panels (in the panel settings the search also spans all tabs).

Not 100% sure what "while the picker is expanded" means? Since currently the visualizations and global panels are categorized with tabs, I worry it might be a bit confusing to receive the results for one tab while the other tab is selected. Or maybe the global panels / visualizations tab selector could disappear when showing search results?
(This is what it looks like for me, currently, just in case you're seeing something different)
![image](https://user-images.githubusercontent.com/45561153/116248416-c4c86380-a763-11eb-957f-45d89ff99cb3.png)

**Comment by hugohaggmark** [comment]
Closing this for v8.
