### ISSUE TITLE
LibraryPanels: Final touches

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#33530]
- [x] Naming
   - [x] Library panel in general  ![avatar](https://github.com/kaydelaney.png?size=24) (#33540)
   - [x] Use create library panel instead of add to library panel  ![avatar](https://github.com/kaydelaney.png?size=24)  (#33540)
- [x] Folder
   - [x] Add separate view under folder that lists the panels for that folder (#33560)
   - [x] Add folder filter to manage library panel page (#33560)
   - [x] Add folder name on the libaray panel card description, make that clickable somehow (#33697)
- [x] Per page should be more than 40 on the manage library panel page (#33560)
