### ISSUE TITLE
Epic: Theme updates

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#33564]
Long term goals for the themes project. This is not needed for 8.0

# Theme model work
* [ ] Complete breakpoints media queries (missing 2 I think) 

# Update to new theme model
* [ ] Update old sass theme variables to use new theme variables
* [ ] Legacy select 
* [ ] Update jaeger-ui components so they use the v2 theme
* [ ] Update PanelEdit to use new theme model
* [ ] Update Dashboard components and views to use new theme
* [ ] Update Explore to use new theme
* [ ] Update Alerting views to use new theme
* [ ] Update Config views to use new theme
* [ ] Update Enterprise code to use new theme 

# Bugs

# Component work
* [x] Side menu hover menu needs to use new components with emotion styles (using old sass styles right now) https://github.com/grafana/grafana/pull/38995
* [ ] Make Menu component support nested fly out submenu so we can use it for PanelMenu 
* [ ] Update panel menu design https://github.com/grafana/grafana/issues/33256
* [ ] Create a Typography component , similar to what exists in material-ui 

# Update external plugins to use a new theme
* [ ] Enterprise plugins 
* [ ] Easy start 

# Move styles to emotion 
* [ ] Element styles (base elements)  to emotion GlobalStyles

# Theming infra 
* [ ] Update useStyles to support memoize of custom props 

Focus state:
use https://github.com/WICG/focus-visible 
https://github.com/mui-org/material-ui/blob/next/packages/material-ui-utils/src/useIsFocusVisible.js

**Comment by JoaoSilvaGrafana** [comment]
@natellium Given how old this is and we have the design system project now, should we close it? Do we even know if some of these have been completely in the mean time by other issues?

**Comment by ashharrison90** [comment]
@JoaoSilvaGrafana i was going to suggest the same thing. this feels very outdated, e.g. all the tasks to update to v2 theme i think were completed by @kaydelaney here: https://github.com/grafana/grafana/pulls?q=is%3Apr+author%3Akaydelaney+theme+v2+is%3Aclosed+

**Comment by JoaoSilvaGrafana** [comment]
I'm gonna close it then, someone can reopen it if they feel like it!
