### ISSUE TITLE
Managed Identities for Azure Monitor datasource

### ISSUE THREAD

**Issue by kostrse** [grafana/grafana#33721]
Roadmap of work involved for support of managed identities for Azure Monitor datasource.

### Plugin proxy and authentication provider

Changes which need to be made into PluginProxy and server config:

- [x] Split implementations of token providers (#32820)
- [x] Authentication type configuration in plugin routes (#33669, #33674)
- [x] Add Azure settings in Grafana server config (#33728)
- [x] Pass flag from server to plugin frontend whether the Managed Identity enabled for Grafana server or not (#33728)
- [x] Azure token provider with support for Managed Identities (#33807)

### Azure Monitor datasource plugin

Changes which need to be made into Azure Monitor plugin to support Managed Identities:

- [x] Introduce AzureCredentials, reusable AzureCredentialsForm and refactor configuration UI (#33620)
- [x] AzureMonitor: cloud and route resolution on backend (#34342)
- [x] Add Managed Identity switch into configuration UI (#34170)
- [ ] Cleanup list of routes and add missing clouds

### Known bugs

- [x] Plugins: Fix Azure token provider cache panic and auth param nil value (#34252)
- [x] Azure China log analytics error (#31662)

**Comment by sunker** [comment]
@kostrse just reviewed https://github.com/grafana/grafana/pull/33674, but that was before I read through this issue. 

This all sounds great, but one thing that concerns me is that the plugin proxy in core grafana is not available for external plugins. I want to make sure that all the work that you put into adding support for Managed Identity auth is not something that will only be available for Azure Monitor (since it's a core plugin), but also for [Azure Data Explorer](https://github.com/grafana/azure-data-explorer-datasource/) and other Microsoft datasource backend plugins that might come in the future.

There's a similar need for AWS plugins. Auth is the same for all of them, so all the code to handle that is put in a common [golang package](https://github.com/grafana/grafana-aws-sdk/tree/main/pkg/awsds). We could create a new repo, grafana-microsoft-sdk-go, that would house shared code for microsoft related things. 

AWS auth is somewhat different though. It does not use an http client, but the golang sdk. The shared microsoft sdk should be able to expose an applyRoute function similar to the one in core grafana. Let's discuss this further in tomorrow's meeting. 

Question: Will the auth to a certain datasource in Azure Managed Grafana be restricted on a user level? I.e, does the Azure OAuth user only steer access to AMG, or also to specific datasources?

**Comment by kostrse** [comment]
Thanks @sunker for feedback!
Yes, my intention is to have support for managed identities eventually in all Azure datasources, not only in Azure Monitor.

Thank you for pointing out that plugin proxy is accessible only for core plugins, it's something I overlooked. I was under false impression that it used by all plugins, including external.

I would be happy to discuss what are my options to make the authentication logic reusable,

With regards to the shared library. Let's maybe call it **azure**, not **microsoft**, because for now it's going to be very Azure specific (clouds, Azure models etc.).

I also going to have some shared code on frontend side, reusable component for Azure credentials, some Azure models, API wrappers. Maybe it makes sense to have shared frontend library as well.

Could you please also look at this PR and share your thoughts:
#33728 AzureMonitor: Azure settings in Grafana server config
