### ISSUE TITLE
Azure: Harmonize Azure datasource auth

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#33809]
**What would you like to be added?**:

I would like authentication to have the same features and it to be handled in the same code for all Azure datasource plugins.

**Why?**

Work for adding support for a new Azure auth type, Managed Identity, has already been [started](https://github.com/grafana/grafana/issues/33721). At the moment there's no way of writing the code for this in one single place and make it available to all Azure plugins. 

There's plans to build more datasource plugins for Azure services in the near future. If authentication, which should be identical or at least very similar for all Azure services, is handled in a shared isolated module that is tested, it will speed up development for future Azure plugins.    

**How does it work today?**:

At the moment we have two Azure datasource plugins. Azure Monitor which is a core plugin and Azure Data Explorer (ADX) which is an external datasource plugin with a backend. 

For both plugins there's two types of requests to Azure API:s that needs to be authenticated. 
1. The main query function that is triggered on dashboard/explore refresh
	**Azure Monitor**
	Before the request is passed to the Azure API, [ApplyRoute](https://github.com/grafana/grafana/blob/main/pkg/api/pluginproxy/ds_auth_provider.go#L16) is called on core Grafana's pluginproxy. This will read token auth params that are specified for the [current route](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/grafana-azure-monitor-datasource/plugin.json#L31-L209), and issue a request to the Azure token api to retrieve a token. The token is then cached in the pluginproxy and will be reused in all requests to Azure for a certain time. 
	
	The Azure Monitor datasource is converted to use dataframes, but it's still using the old tsdb endpoint. 
	**ADX**
	The plugin proxy in core Grafana is not available to external plugins, so ADX has its [own way of retrieving tokens](https://github.com/grafana/azure-data-explorer-datasource/blob/master/pkg/azuredx/azuredx.go#L143-L168) for QueryData requests. A new HttpClient is created for each request to QueryData. Token retrieving is done upon creation of the HttpClient and are therefore not cached. 
	
2. Frontend queries that are used to populate the Query Editor with meta data. 
	**Azure Monitor**
	Uses the reverse proxy in core Grafana, so therefore following the same auth procedure as Azure Monitor DataQuery requests.
	**ADX**
	Uses the reverse proxy in core Grafana, so therefore using a different auth procedure than ADX QueryData requests.

**Problem with current solution**

As of today, it's painful to add new features/make changes to Azure plugin authentication since it has to be done in two places (and even more places if we add more plugins). This would obviously not be a problem if only the pluginproxy became available to external plugins, but I don't think that's the right path forward. Azure plugins should handle this on its own.     

**Suggested solution**

Azure plugin auth should not be handled in the pluginproxy (or independently), but in a separate, reusable go package. The package should provide tokens to the client. It should also contain logic for token caching, national clouds handling etc. 

All Azure plugins and both types of requests (frontend meta data queries and dashboard/explore queries) should use the same HttpClient. The HttpClient should only be recreated when the datasource settings change. The HttpClient should use the token provided from the shared package.  

In order to get there, some refactoring needs to be done. Separate issues will be created for each task

**Azure Monitor**
- [x] Needs to be refactored to use the latest plugin-sdk api:s instead of the old tsdb api. https://github.com/grafana/grafana/issues/34510
- [x] Remove possibility of having different credentials for Logs and Metrics
  - [x] Show a warning if a panel is using the wrong credentials #35858
- [x] Instead of using the pluginproxy to retrieve bearer tokens for the main query function, use auth middleware and token provider package https://github.com/grafana/grafana/issues/35027
- [x] It should implement a CallResourceHandler. Instead of using the pluginproxy in core Grafana for frontend requests, it should be using the CallResourceHandler api in its own backend to retrieve meta data. 

**ADX** 
- [x] Needs to be refactored so that the HttpClient is not reacreated for each requests.  https://github.com/grafana/azure-data-explorer-datasource/issues/229
- [x] Instead of using the pluginproxy in core Grafana for frontend requests, it should be using the CallResourceHandler api in its own backend to retrieve meta data. https://github.com/grafana/azure-data-explorer-datasource/issues/232

**Common Azure task**
- [ ] Create new repo for shared go packages such as the token provider
- [ ] Create new repo for shared frontend code such as the ConfigEditor which should be basically the same for all Azure datasource plugins. 

I'm not entirely sure if aforementioned refactorings can be done today or if we're waiting for features to be added in the plugin-sdk. WDYT @marefr @wbrowne @ryantxu? 

More info will come...

**Comment by iwysiu** [comment]
@sunker Is there something specific that we're waiting for for this?

**Comment by kostrse** [comment]
Hi @iwysiu, could you give details what is your area of concern, I may help?

**Comment by sunker** [comment]
One thing that's left is to move the token provider package from the azure monitor directory in core grafana into the [grafana-azure-sdk-go](https://github.com/grafana/grafana-azure-sdk-go). Once that is done, we can start consuming it in the Azure Monitor data source and in the ADX data source. We might have to do some tweaking in ADX to get it to work. 

Can we start this work now @kostrse or are you actively working on contributions to the token provider package? If so, we can wait.

**Comment by kostrse** [comment]
@sunker lets discuss this

**Comment by sunker** [comment]
> @sunker lets discuss this

Sorry for late response - yes let's discuss! I'll reach out on teams so that we can find a time that works for both of us.

**Comment by kostrse** [comment]
Remaining work to move the Azure implementation to a shared library ([grafana/grafana-azure-sdk-go](https://github.com/grafana/grafana-azure-sdk-go)):

- [ ]  #46002
- [ ] Move interface `azcredentials/AzureCredentials` to [grafana/grafana-plugin-sdk-go](https://github.com/grafana/grafana-plugin-sdk-go/) and introduce strongly-typed configuration struct in `sdkhttpclient.Options`.
- [ ] Update Azure implementation to strongly-typed contracts from [grafana/grafana-plugin-sdk-go](https://github.com/grafana/grafana-plugin-sdk-go/)
- [ ] Copy Azure implementation to [grafana/grafana-azure-sdk-go](https://github.com/grafana/grafana-azure-sdk-go)
- [ ] Switch Grafana to [grafana/grafana-azure-sdk-go](https://github.com/grafana/grafana-azure-sdk-go)

@sunker, @marefr

**Comment by marefr** [comment]
@kostrse sounds good to me. Personally I had started with "Move interface `azcredentials/AzureCredentials` to [grafana/grafana-plugin-sdk-go](https://github.com/grafana/grafana-plugin-sdk-go/) and introduce strongly-typed configuration struct in `sdkhttpclient.Options`" since it will require changes to Grafana and probably similar changes as already suggested with https://github.com/grafana/grafana/pull/46002.

**Comment by kostrse** [comment]
(1) and (2) can be done in parallel, since my PR (1) doesn't change any of the azcredentials interfaces,  just changes they way how datasources use it.  (1) and (2) can be merged in any order.

**Comment by marefr** [comment]
Great. I've added some comment on 1) and 2).

**Comment by kostrse** [comment]
Updated the above list of remaining tasks
https://github.com/grafana/grafana/issues/33809#issuecomment-1055173828

**Comment by aangelisc** [comment]
@kostrse this epic is pretty much complete since ADX has almost been completely migrated to [the SDK](https://github.com/grafana/grafana-azure-sdk-go) right?

**Comment by kostrse** [comment]
> @kostrse this epic is pretty much complete since ADX has almost been completely migrated to [the SDK](https://github.com/grafana/grafana-azure-sdk-go) right?

I created an epic to track progress on migration of frontend code to `grafana-azure-sdk-react`:
* https://github.com/grafana/grafana-azure-sdk-react/issues/1

This issue can be closed already.
