### ISSUE TITLE
Plugins: Add Marketplace to Grafana for installing / uninstalling without restart

### ISSUE THREAD

**Issue by jackw** [grafana/grafana#33930]
- [x] Add Marketplace app plugin to Grafana codebase #33869
- [x] Wire up Marketplace app plugin to Grafana backend endpoints #33869
- [x] Introduce visual feedback whilst navigating / waiting on async requests #33869
- [x] Plugin details cannot load a plugin without a browser refresh #33869
- [x] Fix bug with Dashboard Search erroring when opening whilst browsing Marketplace app #33579
- [x] View plugin tab is incomplete / broken #34274
- [x] ~Disabled but pinned marketplace creates menu item with broken links~ Config is now handed by backend
- [x] Replace remaining usage of `stylesFactory` in component with `useStyles2` #34274
- [x] Filter out renderers from listings due to complexity supporting installing #34274
- [ ] After plugin install refresh the page so users have access to newly installed plugins in the browser
- [ ] Expose app `<Page />` component from grafana-ui and remove marketplace Page component
- [ ] VersionsList `fromNow` dates are translated based on browser locale
- [x] Images fail to load from readme with CSP active #34265 
- [x] Auto enable the plugin catalog based on the `config.ini` flag
