### ISSUE TITLE
Prometheus: Metric browser improvements

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#33976]
**What would you like to be added**:

List of items to follow-up on after #33847 

Tasks (search for `TODO #33976` in the code to find relevant parts)

- [x] create a common Label component
- [ ] remove code duplication from PrometheusMetricsBrowser
- [ ] make fetching labels and values parallel
- [ ] introduce a common interface to replace `LokiLanguageProvider | PromQlLanguageProvider`
- [ ] add support for Histogram group

Tasks moved from #33847:

- [x] add HELP and TYPE
- [ ] make metrics collapsible
- [ ] add histograms helper (search {le=~".+"} first?)
- [ ] add recording rules helper (or filter)
- [ ] investigate the new Labels APIs that recently started taking a selector (to replace the use of the Series API)

Some other ideas:

- [ ] add fuzzy search (in a way that would work for Loki and Prometheus at the same time)
- [ ] updated labels when time picker changes

**Why is this needed**:  Mainly to clean up technical debt and implemented two minor missing features.

**Comment by gtk-grafana** [comment]
After chatting with Gabor, we might want to reevaluate the priority of these issues, this ticket was created before the query builder was released, so some of these might not be as relevant as they were.

`introduce a common interface to replace LokiLanguageProvider | PromQlLanguageProvider`
We also discussed the common interface for LokiLanguageProvider | PromQlLanguageProvider, and came to the conclusion that we can keep separate interfaces for LokiLanguageProvider and PromQlLanguageProvider.

`add support for Histogram group`
Not entirely sure what the issue is here, but I can check to see if we can build grouped histograms via the metrics browser like we can via the raw query or query_builder.

**Comment by ifrost** [comment]
> add support for Histogram group
> Not entirely sure what the issue is here, but I can check to see if we can build grouped histograms via the metrics browser > like we can via the raw query or query_builder.

When the metrics browser was added (1 year ago) it changed the behavior for users as before it'd had metrics grouped by type (see comment here https://github.com/grafana/grafana/pull/33847#issuecomment-838431637). It's been a year and I don't think anyone asked about it so I think we don't need to add it anymore.

**Comment by itsmylife** [comment]
Thanks for the input @ifrost 

Here is the summary of the conversation I had with @ifrost
- Those are the tasks mainly for housekeeping and code quality.
- There are some suggestions that might be useful for the users.
- One year ago changing/refactoring things was easy but now the person who will take care of this should build a context and understand what was duplicated. So that will affect the effort. We cannot directly say its effort just by looking at the definition. 
- Reached out to Jay for his input to determine the priority of this.

**Comment by llamafilm** [comment]
Showing the HELP text in the description field would be very helpful for me, especially for SNMP metrics whose purpose is not obvious from the name. Is that tracked somewhere else or is this still the right issue?

**Comment by itsmylife** [comment]
This issue is a bit obsolete after we made a series of changes in metrics browser and how we fetch the data. I'm closing this issue. We will work on potential future improvements in other tasks/issues.
