### ISSUE TITLE
Timeline: Epic for panel features for v8 / v8.1 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#34080]
* [x] Zoom https://github.com/grafana/grafana/pull/34079 
* [x] Dynamic Contrast text https://github.com/grafana/grafana/pull/34072 
* [x] Move from alpha to beta
* [x] Text alignment option https://github.com/grafana/grafana/pull/34087
* [x] Fill opacity option 
* [x] Line width option  
* [ ] Gap option to have small gaps between boxes (can we use this instead of column width for peroid changes as well?) 
* [x] Hide text values when there is no space for them 
* [x] Legend 
* [x] Tooltip :run: https://github.com/grafana/grafana/pull/35005 

Bugs
* [x] The left y axis ticks get cut of 
![Screenshot from 2021-05-14 12-47-00](https://user-images.githubusercontent.com/10999/118260442-9c09d300-b4b2-11eb-97bb-b5b32f19223c.png)

* [x] Don't try to render exact sampling times on x axis when there's series mis-alignment; fall back to regular tick gen. (see below)
![image](https://user-images.githubusercontent.com/43234/118175339-9ac6a080-b3f5-11eb-862f-1946df6bd9c1.png)

**Comment by leeoniya** [comment]
i took a stab at the axis ticks/alignment issue.

the problem is that it's actually rather difficult to determine if things are truly aligned. in the example above, it's not enough to check all the first boxes. B and C are actually aligned (having compatible multiples), but actually testing this numerically runs you into float precision math issues, making a simple/cheap assessment impossible even for those.

if you have any ideas about how to test for alignment, let me know.
