### ISSUE TITLE
Epic: Frontend dependency audit tasks

### ISSUE THREAD

**Issue by kaydelaney** [grafana/grafana#34129]
Recently myself and @jackw spent some time auditing our frontend dependencies and wrote down some steps that could be taken to improve our bundle sizes.
This epic will be used to keep track of any tasks being done in service of that.

### Tasks

- [x] Move `@types`, `why-did-you-render`, `emotion-eslint`, `copy-webpack-plugin`, and `nodemon` to devDependencies. (handled in #34124)
- [x] Remove `md5` and use `uuid` instead. (#34192)
- [x] Move `immutable`, `is-hotkey` and `react-inlinesvg` dependencies to `grafana-ui` (#34290)

### Open questions

- [ ] One of our dependencies used for logging, "Sentry", seems quite large (400kb) for a logger. Is it necessary, or can we replace it with a smaller dependency, or even roll our own solution?
- [ ] `baron` is used by the `grafana-panel` directive. Is there a way we can remove it and use `react-scrollbar` instead?
- [ ] Can `moment` be replaced with something more lightweight, like `date-fns` or `luxon`?
- [ ] Is `tinycolor2` still needed, or can it be replaced with a smaller dependency, or even just have its functionality done with css?
- [x] Is `fast-text-encoding` used anywhere? Is it needed?
  - don't think so, have removed in https://github.com/grafana/grafana/pull/42085
- [ ] Is `dangerously-set-html` needed? Can we just use react's built-in functionality?
- [ ] Is `debounce-promise` needed? Can we use `rxjs` or `lodash` debouncing?
- [ ] Is `file-saver` necessary? Can we just use native browser APIs?
- [ ] Is `pluralize` necessary?
- [ ] What is depending on `prop-types`? Is it needed?
  - ironically `dangerously-set-html-content` has it as a peerDep. so it can maybe be removed depending on whether we decide we still need `dangerously-set-html-content`.
- [ ] Can we use `react-split-pane` instead of `re-resizable`?
- [ ] Can `react-loadable` be replace with React's built-in lazy-loading? (react.lazy)
- [ ] `rst2html`: Do we still need to use the fork?
