### ISSUE TITLE
Prepare v8 test plan

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#34181]
- [x] Panel edit update (@dprokop )
- [x] New visualizations
  - [x] Pie chart (@oscarkilhed )
  - [x] TimeSeries (@dprokop)
  - [x] BarChart (@dprokop)
  - [x] State timeline (@torkelo @leeoniya )
  - [x] Status grid (@leeoniya )
  - [x] Histogram (@leeoniya )
- [x] Library panels (@hugohaggmark)
- [x] Marketplace app (@jackw)
