### ISSUE TITLE
Azure Monitor configuration improvements

### ISSUE THREAD

**Issue by kostrse** [grafana/grafana#34622]
Improvements to configuration experience in the Azure Monitor datasource:

#### v8.0
- [x] Reset default subscription when credentials change PR #34707
- [x] Remove/disable the App Insights configuration #33709, PR #34725
- [x] Remove "same as" credentials switch for newly created datasources #34621, PR #34758
- [x] Improve validation of datasources in config editor #34431, PR #34787
- [x] Default subscription should not be required #34618, PR #34787
- [x] Logs Analytics tab uses credentials of Metrics to get list of subscriptions #33765
- [x] Remove default workspace from configuration editor #34619

#### v8.1
- [x] Show error message in config editor if cannot fetch list of subscriptions #34426
- [x] Configuration editor should be disabled for read-only datasources #34616

**Comment by BWalti** [comment]
I'm not sure if this is the right place, but if not I'd gladly create an issue or whatever.

In our environment we have multiple Azure Application Insights instances (one for each "environment" like testing and production) and I created a dashboard where we can switch the environment by changing "one drop down" (from testing -> production) - this is basically switching the data source from Azure Monitor (Testing) to Azure Monitor (Production) with different credentials assigned.

Furthermore we are using variable queries to fetch all the other things like subscription, resource groups etc in the "structurally" identical environments (e.g. there is always a resource group with some postfix == 01)

Now all queries and panels were using these variables - but since v8.0 I can't figure out how to create such a variable for the "application insights" resource which would be needed in the new "Logs" Query.

Checking the dashboards JSON it seems, that the `resource` attribute requires the "fully qualified" URI like
`/subscriptions/{subscription-guid}/resourceGroups/{resourcegroup-name}/providers/microsoft.insights/components/{insights-name}`

Where as my "Application Insights" variable with the following query only contains the name:
`ResourceNames($FirstResourceGroup, microsoft.insights/components)`

And when I'm using that variable I get "no data".

@kostrse, is there a way to create a variable for the application insights resource itself so that it can be used in a Query using "Logs" service?
