### ISSUE TITLE
State Timeline: Streaming Performance

### ISSUE THREAD

**Issue by leeoniya** [grafana/grafana#34947]
below is an unflattering profile of the State timeline panel at 20Hz:

![image](https://user-images.githubusercontent.com/43234/120052397-c8613b80-bfea-11eb-832a-65bf54980676.png)

many functions run _per datapoint_ and need fixing or bypasses:

- [x] `tinycolor(color).setAlpha(opacityPercent).toString()` is really slow since it does new object construction, parsing, then maybe colorspace conversions, then converting back to string. there is a much faster way to do this if we already get an rgb hex string and only need to add alpha. (#34948)
  https://github.com/grafana/grafana/blob/dfc466052d9c6fafbebaaf6691bab0caa1287e17/public/app/plugins/panel/state-timeline/timeline.ts#L516-L519
- [x] `quadtree.ts` is a spatial index that's re-built for each frame for all rects to support hover interaction by mouse, we can skip this for fast streams, densely-packed data, or do it lazily only on mouse hover. (#34949)
- [x] as part of streaming, we may need to cache the output of `field.display()` and circPush() it in a similar fashion as we do with the actual data append. running this function on every datapoint on every frame is way too expensive even if it's possible to optimize some subset of what it does. (#35072)
- [ ] the `mergeValues()` function does not work when the colors are derived from thresholds, since consecutive values can have same color but different raw values. we need to run the thresholds/mappings first so we can reduce the number of discrete states and allow mergeValues() to reduce the number of rects we end up rendering, can easily be 10-100x reduction in draw costs and quadtree costs. (#35073)
- [ ] `valueFormat.ts` is the `toFixed()` function, which does a lot of number -> string conversion, parsing and re-assembling. surely we can fall back to native `Number.toFixed()` in common cases. (#34951)

**Comment by leeoniya** [comment]
what's already done is a major improvement, pushing remaining work to 8.1

**Comment by grafanabot** [comment]
This issue was removed from the 9.0.0 milestone because 9.0.0 is currently being released.
