### ISSUE TITLE
Angular migration: Services and cleanup

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#35326]
Leftovers from #21484

## Delete and move directives
- [x] Remove json_editor_ctrl.ts
- [x] Move directives to app/angular
- [x] Remove unused directives (be careful as these might be used by Angular plugins)

## Remove ngInject from services

```js
Remove this
coreModule.service("dashboardSrv", DashboardSrv)

And add to this:
AngularApp:
coreModule.factory('timeSrv', () => getTimeSrv());
coreModule.factory('templateSrv', () => getTemplateSrv());
```
- [x] DashboardSrv - https://github.com/grafana/grafana/pull/36810
- [x] NavModelSrv - https://github.com/grafana/grafana/pull/36810
- [x] DynamicDirectiveSrv
  - i think the whole point of this is to render an angular directive, in which case i don't think we can remove the `ngInject` here as it will definitely need the `$compile` service. //ash
  - as for removing it altogether, currently it's used by `panel-editor-tab`, which is used by `AngularPanelOptions`, which can be used by `OptionsPaneOptions` if there's an angular controller, which i think is going to be blocked by plugins that are still angular based... //ash
- [x] uiSegmentSrv
  - not sure how we can replace `$sce` //ash
- [ ] util_srv - https://github.com/grafana/grafana/pull/36842
  - as dominik mentioned [here](https://github.com/grafana/grafana/pull/36842#pullrequestreview-708353543), this is blocked by the fact that plugins could still be using `hideModal`/`showModal`, so we can't remove those methods without properly announcing that they'll be gone //ash
- [x] LinkSrv - https://github.com/grafana/grafana/pull/36849
- [ ] DatasourceSrv
  - not sure how to replace `$injector` //ash

## Convert controllers
- [ ] GrafanaCtrl
- [x] PanelLinkEditor - think this has been converted - removing old angular code done as part of https://github.com/grafana/grafana/pull/36838 // ash

**Comment by tskarhed** [comment]
This and the angular stuff in the same directory is probably unused and can be removed
https://github.com/grafana/grafana/blob/main/public/app/features/panel/panellinks/module.html

**Comment by ashharrison90** [comment]
have done some more low hanging fruit - i think the rest needs some _thought_ 🤔

**Comment by hugohaggmark** [comment]
@torkelo do you know if there's anything left on this issue? Thank you 🙏

**Comment by torkelo** [comment]
yes, we can close this
