### ISSUE TITLE
Detect breaking changes in the plugins API prior to release of Grafana

### ISSUE THREAD

**Issue by wbrowne** [grafana/grafana#35656]
## Main goal of this epic
We need to know that we are not breaking (plugins can be used / interacted with by customers) the most important plugins that our customers use while shipping a new version of Grafana. 

### Nice to have
- We would like to improve the experience of maintaining a plugin as a plugin developer. 
- We would like to have a clear strategy on how to communicate breaking changes when they cannot be avoided.
- Developers who modify plugin code need to be able to know that they are introducing breaking changes

### Description
Goal of this POC is to test if we gain the desired outcome as quickly as possible. That's why it will be `local` first and see how much use cases we would cover with it without having to deal with added complexity of a CI pipeline.

The overall idea is to create a private repository where we can host the source of external Grafana plugins. This repository can be used to update, build and verify (in a later stage) that plugins won't be broken with Grafana version updates.

### Tasks:
- [ ] https://github.com/grafana/grafana/issues/42180
- [ ] https://github.com/grafana/grafana/issues/42188
- [ ] https://github.com/grafana/grafana/issues/42190
- [ ] https://github.com/grafana/grafana/issues/42192
- [ ] https://github.com/grafana/grafana/issues/42193

### Related:
https://github.com/grafana/grafana/discussions/40586 (Proposal 5)
https://github.com/grafana/grafana/discussions/40586#discussioncomment-1499975

### Description
The goal of this POC is to create a set of examples on how to implement the "most" popular features of plugins. Together with each example we should create a test suite that can be used to verify that the example is working when doing changes in the Grafana repository. When this POC is done we should have examples, tests and a way of running them against a given commit of the Grafana repository.

Benefits of this approach:

- We can use these examples to showcase/documentation of how to extend Grafana.
- We can run the tests of these examples on a regular basis to verify that none of the APIs are broken between major versions.

To scope this POC we should only create a couple of examples to cover the most basic functionality of Grafana.

### Tasks
- [x] https://github.com/grafana/grafana/issues/42208
- [x] https://github.com/grafana/grafana-plugin-examples/issues/14
- [x] https://github.com/grafana/grafana-plugin-examples/issues/12
- [x] https://github.com/grafana/grafana-plugin-examples/issues/11
- [x] https://github.com/grafana/grafana-plugin-examples/issues/9

### Description
The goal of this POC is to create a tool that can compare two versions of the `@grafana/packages` and notify the PR author about potential breaking changes. Hopefully this will raise awareness about what changes to the `@grafana/packages` might affect the plugins in a negative way.

If we do a breaking change it should be done as an active decision and not as a side effect. 

After building this tool we realized that we can use the same tool to scan plugins published to grafana.com to gather information about what parts of the `@grafana/packages` that are being used.

### Tasks
- [x] #41757
- [x] https://github.com/grafana/levitate-grafana-ci/issues/2
- [x] https://github.com/grafana/levitate-grafana-ci/issues/3
- [ ] https://github.com/grafana/community-pipeline/issues/33
- [x] https://github.com/grafana/grafana/issues/52633
- [x] https://github.com/grafana/levitate-grafana-ci/issues/19

Related:
#24923
https://github.com/grafana/grafana/discussions/40586

**Comment by tolzhabayev** [comment]
We will revive this or create a new one once we pick up more work in this area again.
