### ISSUE TITLE
Custom Kiosk Mode

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#36202]
This PR will add a custom kiosk mode. TBD

**TODO**

- [x] Buttons related to permissions shouldn't be part of the custom settings.![avatar](https://github.com/thisisobate.png?size=24)
- [x] Compare the current kiosk mode(s) on [grafana play](https://play.grafana.org/) with this branch and make sure the different configurations correlate with how it works on play.*
- [x] Change so we only apply the configuration when you press the kiosk mode button in the dashboard navigation. It should toggle the configuration when pressing it multiple times.**
- [ ] Figure out how we should save the custom configuration values and what profile the user have selected.
- [x] Fix flaky gorilla TimePicker toggle
- [x] Add toggles for the things that is missing and can't be toggled via the config yet. ![avatar](https://github.com/thisisobate.png?size=24)
- [ ] Animate the top navigation menu when you move the mouse.
- [ ] Add toggles for template variable dropdowns
- [x] For Standar and TV hide the checkboxes and show only a description.

**Suggested implementation: add a `enabled: bool;` property to the `GorillaContextType` (should be false by default) and toggle that property when pressing the kiosk mode button in the dashboard navigation. Also add a check if the configuration is enabled or not in the `useGorillaConfiguration` hook. If it is enabled return the configuration. If it isn't return undefined.

Related issues:
#7450
#25894
#26105

**Comment by baur** [comment]
Please, also add block ESC button in embedded kiosk mode, for clients no needs for that

**Comment by Ijin08** [comment]
[Link](https://www.figma.com/file/55URnY7wFtn49zPf9NH0nO/Kiosk-mode?node-id=17%3A193) to Figma

**Comment by mckn** [comment]
> Please, also add block ESC button in embedded kiosk mode, for clients no needs for that

Do you have any suggestions on how to exit the kiosk mode?

**Comment by baur** [comment]
> > Please, also add block ESC button in embedded kiosk mode, for clients no needs for that
> 
> Do you have any suggestions on how to exit the kiosk mode?

Block only on embedded mode, there is no need when dashboard embedded for another system (site)

**Comment by mckn** [comment]
> > > Please, also add block ESC button in embedded kiosk mode, for clients no needs for that
> > 
> > 
> > Do you have any suggestions on how to exit the kiosk mode?
> 
> @mckn, Block only on embedded mode, there is no need when dashboard embedded for another system (site)
> 
> #13706

Would it be okay to disable all the keyboard shortcuts? Or do you need to have those available?

**Comment by baur** [comment]
@mckn 

> > > > Please, also add block ESC button in embedded kiosk mode, for clients no needs for that
> > > 
> > > 
> > > Do you have any suggestions on how to exit the kiosk mode?
> > 
> > 
> > @mckn, Block only on embedded mode, there is no need when dashboard embedded for another system (site)
> > #13706
> 
> Would it be okay to disable all the keyboard shortcuts? Or do you need to have those available?

In our case: No control, No navigation, only view mode. Maybe optional,  by param (?nocontrol=true)? Because I'm not sure that required by all customers ...

**Comment by baur** [comment]
any news? for us this is most wanted feature ...

**Comment by hugohaggmark** [comment]
Someone might pick this up during upcoming hack day or feel free to continue the work in #36201.
