### ISSUE TITLE
Plugins: improve the plugins management in Grafana

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#36229]
We are planning on moving the plugins catalog into Grafana core as a replacement on the current plugin management tab (configuration/plugin). The first benefit of this is to give the user the possibility to install/uninstall plugins on the fly without restarting Grafana. Something that the plugins catalog enables today.

- [x] Move the plugins catalog into Grafana as is ([#36026](https://github.com/grafana/grafana/pull/36026))
- [x] Make the navigation to be consistent with the Grafana configuration page. ([#36026](https://github.com/grafana/grafana/pull/36026))
- [x] Add support for listing/browsing enterprise plugins. ([#36599](https://github.com/grafana/grafana/pull/36599))
- [x] Add support for installing enterprise plugins (if you have a valid license). ([#36653](https://github.com/grafana/grafana/pull/36653))
- [x] Change so when searching we do that auto-magically when you have not typed a letter for 500ms instead of pressing enter. ([#36643](https://github.com/grafana/grafana/pull/36643))
- [x] Should not display uninstall button for core plugins (look at elasticsearch). ([#36671](https://github.com/grafana/grafana/pull/36671))
- [x] Should not display embedded plugins in installed plugins list ([#36675](https://github.com/grafana/grafana/pull/36675))
- [x] Prevent search field from forcing the filter to "all" on load. Caused by a bug in `useDebounce`.
- [x] Refactor local and remote plugins into one structure (CatalogPlugin) to reduce logic in UI components ([#36859](https://github.com/grafana/grafana/pull/36859))
- [x] If an app plugin is installed it should display the plugin navigation tabs for configuration and plugin signature information etc.  ([#36678](https://github.com/grafana/grafana/issues/36678)) ([#37063](https://github.com/grafana/grafana/pull/37063))
- [x] Add a back button to the plugins list to be able to navigate back when viewing a plugin. ([#37095](https://github.com/grafana/grafana/pull/37095))
- [x]  Update the look and feel of the browse page to match the latest figma design. ([#37350](https://github.com/grafana/grafana/pull/37350))
- [x] Fix catalog permissions for org and server admins. ([#37504](https://github.com/grafana/grafana/pull/37504))
- [x] Display a (you need to upgrade) if you try to install an enterprise plugin.
- [ ] ~Add support for finding the compatible plugin version with the current running version of Grafana.~
- [ ] ~Add support for installing plugins via the UI for Grafana HA setups.~

**Comment by wbrowne** [comment]
All done!

**Comment by mckn** [comment]
Wow, great work @wbrowne @jackw <3
