### ISSUE TITLE
Alerting: Rendering of labels, values and annotations

### ISSUE THREAD

**Issue by gotjosh** [grafana/grafana#36401]
[Prometheus supports a plethora of variables/functions](https://prometheus.io/docs/prometheus/latest/configuration/template_reference/) that can be used within Annotations and Labels of the alerting rules. Furthermore, [another set of these variables](https://prometheus.io/docs/alerting/latest/notifications/) are available in the Alertmanager that can be used as part of the notification templates.

To ensure Grafana alerting users can have a similar experience and craft descriptive annotations and labels as part of their alerting rules we need to make sure we provide these. The Prometheus **ones Grafana does not support** (but the Alertmanager ones we do already).

You can take a peek at the [implementation on the Prometheus side for these functions here](https://github.com/prometheus/prometheus/blob/7c125aa5fb22c07a15831e0f79cafc58c2ebae0b/template/template.go#L121) and a good understanding on these get [rendered on the Prometheus side is here](https://github.com/prometheus/prometheus/blob/main/rules/alerting.go#L318-L384).

There's one more thing to consider here, the current Alertmanager notification templates don't support $value at the moment - maybe we shouldn't either and keep the use of $values (or N $values in the Grafana case) something we only support for in annotations and labels. 

### To-do
- [x] Implement the 15 existing prom functions
- [x] Make the table tests for them
- [ ] Intregration tests? (? as currently not sure)
- [x] Update Grafana documentation for the new funcs

**Comment by gotjosh** [comment]
Silly me, it looks like we've implemented the labels expansion but _only_ that as part of https://github.com/grafana/grafana/pull/35159/files

Everything else is valid. Makes me wonder, is there a reason why we decided to implement this in the cache rather than in the scheduler @codesome?

**Comment by codesome** [comment]
> is there a reason why we decided to implement this in the cache rather than in the scheduler

The merging of alert rule labels with the result was happening in the cache, and that felt like the natural place to expand since the expansion should happen just before attaching alert rule labels with the result. However, we should be able to take out the entire label merging part out of the cache and into the scheduler.
