### ISSUE TITLE
Graphite: Migrate QueryEditor to React

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#36481]
This is a recap of the plan for Graphite QueryEditor migration. The idea is to migrate in following steps (numbers matching design doc steps):

- [x] 1: Migrate QueryCtrl to flux: #36484
- [x] 2: Migrate low-hanging directives to Graphite specific React components:
  - [x]  #36797
    - [x] bugfix: #37202
  - [x] #37070
- [x] 3: #37309
- [x] 4 & 5: #37590
- [x] 6: #37919
- [ ] ~~7: Clean up~~ (may happen post 8.2)

More details in [design doc](https://docs.google.com/document/d/1cdC-py1ClQy1mitZAawwmKI5zfjbCPjspTvFS-4slN4/). Manual testing scenarios: [here](https://gist.github.com/ifrost/e8faa2976caf610e9e03ec815ce83d82).
