### ISSUE TITLE
Accessibility checks -  Add Pa11y CI in main pipeline to collect a11y issues  

### ISSUE THREAD

**Issue by thisisobate** [grafana/grafana#36555]
In order to improve accessibility in Grafana, there is a need to continuously check how accessible our UI layout is. This would help us track how close we are to being WCAG compliant. Outlined below are some of the approaches we hope to take in order to achieve our goal.

**Todos**:

- [x] Research on how we can add pa11y CI to our yarn task
- [x] Experiment with different approaches to see which one works best.
- [x] Fetch a11y metrics and populate on a dashboard CI stats

**Pages to test**: PR #36841

- [x] Dashboard landing page 
- [x] DashboardSettings Page
- [x] Search Page
- [x] Bar Gauge Panel Edit Page 
- TimeSeries Panel Edit page - not going to implement this on this iteration 
- [x] Explore page
- [x] Manage Dashboards page
- [x] Alerting list page
- [x] Configurations pages (data sources, users, plugins, preferences)
