### ISSUE TITLE
Geomap panel alpha release

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#36585]
This issue details work required to get a new geomap panel ready for production.  We have explored using [leaflet](https://github.com/grafana/grafana/pull/35915) and [openlayers](https://github.com/grafana/grafana/pull/36188) as the foundation, and openlayers (6+) seems to be a more robust and stable ecosystem.  Both are great for simple things, but the more advanced features are better supported in openlayers.

Currently there are many plugins that support maps.  This plugin changes the model so we can implement and configure *layers* rather than the entire map panel.  This could potentially be its own plugin type -- but for simplicity, we will implement all layer plugins within grafana core (for now)

See:
https://grafana.com/grafana/plugins/grafana-worldmap-panel/
https://grafana.com/grafana/plugins/pr0ps-trackmap-panel/
https://github.com/panodata/grafana-map-panel
https://grafana.com/grafana/plugins/gowee-traceroutemap-panel/
https://grafana.com/grafana/plugins/citilogics-geoloop-panel/
https://grafana.com/grafana/plugins/woutervh-mapbox-panel/

### Initial alpha panel
In https://github.com/grafana/grafana/pull/36188, we introduce a basic structure to have a "basemap" and "layers" appear on a map.  This PR handles the foundation, without yet implementing many details.  

### Worldmap parity
- [x] circles overlay: #36680 
- [x] heatmap overlay: https://github.com/grafana/grafana/pull/36769
- [x] Support mapping string values to a location in json config
- [ ] Labels

### For 8.1
- [x] Name/icon?  "map" panel is too general... is "geomap" reasonable?
- [x] Configurable dimensions https://github.com/grafana/grafana/pull/36825
- [x] https://github.com/grafana/grafana/pull/36894
- [x] Remove or hide not yet ready layers (iconAtLastPoint / geojson)
- [x] Server settings for base layer -- and disable options
- [x] #36889
- [ ] ensure worldmap panel migrations work well
- [x] documentation!

### Maybe 8.1
- [x] Select marker shape https://github.com/grafana/grafana/issues/36724
- [x] Support marker popup / tooltips
- [x] https://github.com/grafana/grafana/pull/36893

### For 8.3
- [x] support multiple layers
- [x] #41436
- [x] #41498
- [x] #41504
- [x] #41511
- [x] #41506
- [x] #41508
- [x] Update / Create Devenv test dashboard (Nikki + Nathan) 
   - Panel Geomap (existing devenv test dashboard), potentially just update the existing dev env test panel
- [x] Geomap: Lookup option for location causing runtime error (crash)
   - Potentially addressed by [this PR](https://github.com/grafana/grafana/pull/41170/files#diff-f714484565ee71a8cf2fbf71a03d3080b1360e010093084631ced947d3d7fcbf)
- [x] #42393

Nice to haves:
- [x] #41223
- [x] #41222

### Soon
- [ ] [Geojson layer] Ability for user to upload custom geojson files
- [ ] Define spatial types in dataframes and support them further up the stack
- [ ] #41221
- [ ] #41224
- [ ] Going into panel fullscreen "View" mode does not work properly, the geomap view does not change size 
- [ ] Host a better default basemap (currently using cartodb)
- [ ] timeseries slider, for [tracks](https://grafana.com/grafana/plugins/pr0ps-trackmap-panel/) and [fill](https://grafana.com/grafana/plugins/citilogics-geoloop-panel/) 
- [ ] Improve react legend system
- [ ] Make all options use sentence case (They use title case now)
- [ ] #40496  
- [x] #42095

**Comment by wz2b** [comment]
I opened separate tickets for this (sorry) because I didn't realize there was a catch-all.  I have two feature requests:

Pertaining to the marker layer:

* The ability to set a marker's size and/or color based on a query result column
* Clickable markers that either
  * Go to some URL provided by the query, or
  * Set some dashboard variable that can be a cue for other panels on the dashboard to show data related to whatever you clicked

**Comment by wz2b** [comment]
Custom shapes would be really nice to have.  Currently the shape is drawn as a canvas.  It could be an SVG instead in which case the user could provide an SVG path.  Even as a canvas, the user could provide a closed path.  Then perhaps somehow you could use value ranges to have a different shape for a "good" location marker vs a "not so good" location - imagine that you want the marker shape to be either a happy face or a smiley face depending on the results of that query row.

**Comment by wz2b** [comment]
It seems like the shape in the LEGEND should match the shape you have selected
![image](https://user-images.githubusercontent.com/1521209/128931697-6fb70ece-a2be-485e-ba73-acd933da90c6.png)

**Comment by wz2b** [comment]
I think this is another feature request, but maybe it's a bug.  When you have value mappings, the mapped text for that range or value works fine but the marker color you select for that value or range doesn't seem to work.  The Thresholds section always wins.  Also if I only have one threshold I get an error:

![image](https://user-images.githubusercontent.com/1521209/128933894-6c993f51-e2b5-467c-8052-5cd58b287b49.png)

**Comment by laurielounge** [comment]
Feature request - modify the tooltip that pops up on mouseover to allow just showing certain fields. For example, I don't want the lat/long when I mouseover, just the City and the metric

**Comment by wz2b** [comment]
> Feature request - modify the tooltip that pops up on mouseover to allow just showing certain fields.

I tested adding an extra field with an Influx data source, just as a test, to see what it did.  It worked.  I just added the city to the query:

```
  |> map(fn: (r) => ({ r with 
      city: "Rochester, NY"
  }))
```

so I think what Laurie is asking for could be resolved with the ability to just hide things from the tooltip - lat, lng, time, depending on what the user wanted.  One way to do this could be to add a "tooltip filter" option.  Another way might be some kind of template - maybe you could even stick a little picture/icon in the tooltip.  It may not be worth the effort to take it that far, but being able to filter lat/long/time out of the tooltip sounds like a good idea to me, if it's not too difficult.

**Comment by wetterfrosch** [comment]
Hi there! I appreciate the new geomap panel very much. I humbly like to add a feature-request for this plugin here of which I am dreaming for some time:

* user-defined character(s) as a custom shape (like @wz2b suggested)
* using the result-value of a query as the custom shape, including the possibility to of values or value-ranges to a shape.

Or described the other way around: drawing result-values directly in the map.

Why? Just think about characters like 🌤 for defining the state of the weather. I would be very beautiful if one could generate such simple weather-map within a map-panel. Within this scope the next idea would be to draw a map with the wind-directions using arrows like ↑. But I assume this feature would be nice for IT-applications, too -- one would be capable of encoding an explicit state of a machine instead of a quantifier.

**Comment by cosmos1978** [comment]
> I think this is another feature request, but maybe it's a bug. When you have value mappings, the mapped text for that range or value works fine but the marker color you select for that value or range doesn't seem to work. The Thresholds section always wins. Also if I only have one threshold I get an error:
> 
> ![image](https://user-images.githubusercontent.com/1521209/128933894-6c993f51-e2b5-467c-8052-5cd58b287b49.png)

I m facing the same problem seems the chosen color does not work it is always overruled by the threshold value

**Comment by erlfos** [comment]
Hi
The Geomap panel looks good, but it lacks one thing the Worldmap panel has and that is the option to center the map on the last geohash, only static coordinates are available in the Geomap "Initial View" option list. With the "Last GeoHash" option in the Worldmap panel I can change a variable and the map center moves to the new location. It is very useful.
![image](https://user-images.githubusercontent.com/45815831/133594275-2e6d7bc2-5c94-4d72-a5f2-a42bc345eba8.png)

**Comment by EthanMelamed** [comment]
1) Legend Text Override:
Legend text should be overridden by display name overrides
![image](https://user-images.githubusercontent.com/15130833/134428233-a73a926e-28b6-4b79-9e53-43043d1e2299.png)

2) Marker Colour with Multiple Fields
Not sure if this is a bug, but here's the behaviour:
Given a query that returns 2 different fields A & B where B has a higher max value than A
And the Marker Colour is set to A
And the colour scheme is set to Blue-Yellow-Red
Then the legend shows the highest value of A at the top end of the range with a bright red colour
BUT the markers with that value are not bright red
![image](https://user-images.githubusercontent.com/15130833/134430428-81ed2df9-7c29-4644-bccb-6925034b27ac.png)

The workaround I've found for the above is to add an override to set the maxValue of A

**Comment by alexkappa** [comment]
Hi, I'm not sure if this is a bug or if it's my mistake, but I'm having trouble using **Coords** from a Prometheus query. The latitude and longitude drop downs do not list my corresponding labels. 

**Geohash** works as expected. I suspect it might have something to do with the expectation of lat/long to be a number?

<img width="792" alt="Screen Shot 2021-09-27 at 17 58 42" src="https://user-images.githubusercontent.com/1204095/134943732-79e1c384-a539-4336-a577-4d29eb201455.png">

This is the output of the Prometheus query in case it helps. Note: `hash` is a geohash, `id` is an [H3 index](https://h3geo.org/).

```
{hash="9erjw356p6hj", id="874985b99ffffff", instance="metrics:2112", latitude="19.253895", longitude="-102.376812"} | 10.996715006810351
{hash="9eweeb8gd4fk", id="8749aa39dffffff", instance="metrics:2112", latitude="20.306097", longitude="-103.193461"} | 11.477445717490586
{hash="9ewkvk20sn06", id="8749ab5a6ffffff", instance="metrics:2112", latitude="20.545925", longitude="-103.480052"} | 6.650108164409902
{hash="9ewkvy158u23", id="8749ab5b5ffffff", instance="metrics:2112", latitude="20.556044", longitude="-103.456846"} | 19.589776460219532
```

Thank you!

**Comment by yosiasz** [comment]
Feature request - ability to show a value on the 🔵 of the map without having to hover on each. Amazing product and thank you!

**Comment by pmorange** [comment]
Hi,

Using Loki as a source and Geomap as a visualization type, I can't make it work.
It works with WorldMap but in geomap the lookup field seems to have a problem :

My logs are seen like that :
![image](https://user-images.githubusercontent.com/8950440/140047012-3a008375-aed3-4557-9ef4-1bdf30fca4fe.png)

Using this query I can make a WorldMap tile display the geolocation of IPs :
![image](https://user-images.githubusercontent.com/8950440/140047155-0e6783bf-0dc6-4361-9335-d2b7b2f7ec96.png)

But with a Geomap nothing gets displayed and I can't select a lookup field (either no field is proposed or a jiberish is displayed in the drop-down menu) :
![image](https://user-images.githubusercontent.com/8950440/140047356-9b07e0ee-985c-40bd-8303-22088d5cf664.png)

Any help would be appreciated as geomap looks nicer than worldmap.
Thanks

**Comment by billabongrob** [comment]
Would it be possible to draw lines on the map panel, under the assumption that we drop lat/long into our prometheus labels?  Our use case is measuring throughput/latency/etc... between datacenters on a map.

**Comment by pmorange** [comment]
> Would it be possible to draw lines on the map panel, under the assumption that we drop lat/long into our prometheus labels? Our use case is measuring throughput/latency/etc... between datacenters on a map.

Hi,
It seems what you are looking for could be the "Traceroute Map Panel", available in the plugins section of Grafana.
I have not used it but it seems to correspond to your description.
Regards.

**Comment by billabongrob** [comment]
> > Would it be possible to draw lines on the map panel, under the assumption that we drop lat/long into our prometheus labels? Our use case is measuring throughput/latency/etc... between datacenters on a map.
> 
> Hi, It seems what you are looking for could be the "Traceroute Map Panel", available in the plugins section of Grafana. I have not used it but it seems to correspond to your description. Regards.

Traceroute map panel is pretty cool; however, not exactly what we're looking for.  In software defined networks, hops aren't incredibly relevant or useful in troubleshooting.  Also in private networks, we're forced to define our own IP lat/long.   With the help of blackbox icmp and some standard deviation work, we're able to identify things that are slower than usual, so now we're adding source (lat|long) and destination (lat|long) and we'd like to draw a simple line between the source/destination.  I may revisit the traceroute panel, but in an ideal world, we should be able to draw lines I would think.  :)

**Comment by Oliv4945** [comment]
Hi,

> > I think this is another feature request, but maybe it's a bug. When you have value mappings, the mapped text for that range or value works fine but the marker color you select for that value or range doesn't seem to work. 
>
> I m facing the same problem seems the chosen color does not work it is always overruled by the threshold value

I have the same issue.

Also, if  I get the data from two InfluxDB queries, only one can only be displayed at a time


@nmarrs @nikki-kiga: should I open separate issues?

**Comment by alexanderzobnin** [comment]
Is there any plans to visualize routes? For example, Strava returns your exercise route in a polyline format, so I can convert it to the array of geo poins and then put it on the map. But does not look 100% precise, sice points are not connected:

![Screenshot from 2021-12-23 14-08-37](https://user-images.githubusercontent.com/4932851/147238255-240bbdaa-f7b5-48ea-b7f7-c001bf59a6af.png)

Would be nice to have it like a path:

![Screenshot from 2021-12-23 15-08-46](https://user-images.githubusercontent.com/4932851/147238444-0e8f9a32-5dac-49c1-bc08-bd91d58c8923.png)

**Comment by leeoniya** [comment]
strava also supports gpx export, which openlayers (geomap's lib) has support for: https://openlayers.org/en/latest/examples/gpx.html

**Comment by alexanderzobnin** [comment]
@leeoniya yes, but it's not necessary in the plugin, sice I can get geo points in polyline format.

**Comment by atifali** [comment]
lets track this here: https://github.com/grafana/grafana/issues/44240
closing this one now
