### ISSUE TITLE
Accessibility Phase 1

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#36602]
This Epic gathers the areas we want to focus on during the first phase of the accessibility work. This is meant to focus on the Grafana consumer who wants to view dashboard, panels and alerts.

- Dashboards #35613
- Panels
- Alerts

Here are some misc. issues that don't fit into a specific feature:

## Docs
- [ ] Accessibility statement #34771
- [ ] Add an accessibility section in pull request guidelines. #36454

## CI
- [ ] Integrate accessibility checks in the CI ![avatar](https://github.com/thisisobate.png?size=24) #36555 
- [ ] Investigate ways to improve e2e performance
