### ISSUE TITLE
Refactor: Propagate context.Context "everywhere"

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#36734]
Epic tracking the ongoing refactoring of using `context.Context` "everywhere", see [ongoing refactoring](https://github.com/grafana/grafana/blob/main/pkg/README.md#use-contextcontext-everywhere) for details. 

By "everywhere" we're not referring to everywhere as in every single utility method etc. The goal is to be able to propagate `context.Context` between all the different layers in the backend, for example all the way from the API layer down to the database layer.

**Approach:**
A few examples of already merged pull requests refactoring smaller parts of dispatching messages via the bus and propagating the `context.Context`. This shows a sane approach for gradually refactor towards propagating `context.Context` "everywhere" by keeping changes somewhat small and concise which makes it easy to review and should get things merged quickly. This approach should hopefully decrease the change of creating a lot of conflicts for work in progress branches/features.
- https://github.com/grafana/grafana/pull/34955
- https://github.com/grafana/grafana/pull/35963
- https://github.com/grafana/grafana/pull/36735

In some cases introducing context for something could cause a ripple in large parts of the code base. To limit the amount of changes you can temporarily pass `context.TODO()` to denote that work is needed to propagate the context properly.

**Refactoring plan:**
1. Start with propagating `context.Context` when interacting with the bus since it's currently central in the backend and used a lot. We want to move away from using the bus, but that's a lot of work so starting with enforcing propagation of `context.Context` here should bring us closer our end goal short term. In summary, move everything to use `bus.DispatchCtx` and `bus.AddHandlerCtx` and remove support for `bus.Dispatch` and `bus.AddHandler`.
2. Continuing with the bus, move everything to use `bus.PublishCtx` and `bus.AddAddEventListenerCtx` (new functions/methods that requires use of `context.Context` and then remove support for `bus.Publish` and `bus.AddEventListener`.
3. Continue with [services](https://github.com/grafana/grafana/blob/main/contribute/architecture/backend/services.md#methods), making sure that every service method takes `context.Context` as the first argument and propagates it to the other layers it interacts with.
4. Hopefully there shouldn't be a lot work left at this place, but we probably need to verify somehow if there's code we've forgot to refactor to use and propagate `context.Context` properly.

**Tooling:**
Initially there was some discussions whether we could programmatically refactor all the code interacting with the bus to enforce usage and propagation of `context.Context`. The conclusion was that it's tricky because the bus are using reflection and it's hard to know where to take the `context.Context` from, hence why a gradual migration was decided. 

Is there perhaps any tools out there that could help us to understand how far we've come towards our goal, e.g. what functions/methods does not take `context.Context` as it's first argument. 

**Related issues:**
- #22123
- #29489
- #31071
- #41482

What is left to do - files where AddHandler needs to be replaced with AddHandlerCtx:
In package pkg/services/sqlstore:
- [x] temp_user.go @idafurjes https://github.com/grafana/grafana/pull/41284
- [x] playlist.go @idafurjes https://github.com/grafana/grafana/pull/41337
- [x] dashboard_version.go @idafurjes https://github.com/grafana/grafana/pull/41672
- [x] apikey.go @idafurjes https://github.com/grafana/grafana/pull/41698
- [x] alert_notification.go @ying-jeanne https://github.com/grafana/grafana/pull/41307

In other packages:
- [x] pkg/services/notifications/notifications.go https://github.com/grafana/grafana/pull/42578
- [x] pkg/services/login/loginservice.go
- [x] pkg/services/login/authinfo/service.go https://github.com/grafana/grafana/pull/42096
- [x] pkg/services/datasources/service.go https://github.com/grafana/grafana/pull/42294
- [x] pkg/services/alerting/service.go https://github.com/grafana/grafana/pull/41307
- [x] pkg/bus/bus.go 

Cleanup tasks:
- [x] Remove rest of the DispatchCtx https://github.com/grafana/grafana/pull/42603
- [x] Remove AddHandlerCtx from tests https://github.com/grafana/grafana/pull/42585
- [x] Replace AddEventListener with AddEventListenerCtx https://github.com/grafana/grafana/pull/42284 
- [x] Remove context.TODO() https://github.com/grafana/grafana/pull/42555 https://github.com/grafana/grafana/pull/43409
- [x] Rename AddEventListenerCtx, PublishCtx, AddHandlerCtx, DispatchCtx back to AddEventListener, Publish, AddHandler, Dispatch https://github.com/grafana/grafana/pull/43557 https://github.com/grafana/grafana/pull/43563 https://github.com/grafana/grafana/pull/43566

**Comment by marefr** [comment]
With #36733 merged it means that Grafana will output 2 different warning log messages in case the bus are used incorrectly and [development app mode](https://grafana.com/docs/grafana/latest/administration/configuration/#app_mode) is enabled:
- `WARN[07-14|00:23:06] DispatchCtx called with message handler registered using AddHandler and should be changed to use AddHandlerCtx logger=bus msgName=<message name>`
- `WARN[07-14|00:24:02] Dispatch called with message handler registered using AddHandlerCtx and should be changed to use DispatchCtx logger=bus msgName=<message name>`

If you see any of above warning messages those are good subjects to fix/resolve.

**Comment by idafurjes** [comment]
Finished

**Comment by hairyhenderson** [comment]
FYI my PR https://github.com/grafana/grafana/pull/80481 adds context propagation in a place where it was missing (sending notifications via SMTP)
