### ISSUE TITLE
Support Mute Timings within Unified Alerting

### ISSUE THREAD

**Issue by gotjosh** [grafana/grafana#37752]
Support for recurring silencing is a hot topic for alerting within Grafana per https://github.com/grafana/grafana/issues/36637 and the most voted feature under the alerting label per https://github.com/grafana/grafana/issues/6592.

The Alertmanager upstream has recently implemented a feature that supports this https://github.com/prometheus/alertmanager/pull/2393 which means we can easily implement it within Grafana too.

A high-level list of steps to take are:

- [x] #40291
- [x] #41285
- [x] Support CRUD of `<mute_time_intervals>` through the API - [doc link](https://prometheus.io/docs/alerting/latest/configuration/#mute_time_interval)
- [x] Support attaching `<mute_time_intervals>` to a particular route. [doc link](https://prometheus.io/docs/alerting/latest/configuration/#route)
- [x] Pass the `<mute_time_intervals>` configuration to the Alertmanager.
- [x] Update the documentation
- [x] Close the two issues mentioned above.

**Comment by armandgrillet** [comment]
I've talked with the UX team about this, the plan is to start working on the UX the second week of September and then have the front-end and back-end work starting. This means missing the 8.2 release and being done around the end of September.

**Comment by armandgrillet** [comment]
Removed @kylebrandt from the assignees as he is moving back to the Grafana team but this will need backend work.

**Comment by armandgrillet** [comment]
@nathanrodman Have you talked to Jessica about this? AFAIK we need her opinion before moving forward with front-end/UX work.

**Comment by nathanrodman** [comment]
@armandgrillet I've been meeting with Jess on this and we have some initial UX designs that we're working through
