### ISSUE TITLE
Prometheus migration to backend data source

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#37784]
Checklist:
- [x] Correct interval calculation on backend https://github.com/grafana/grafana/pull/39036
  - [ ] Figure out logging of `maxDataPoints == 0` https://github.com/grafana/grafana/pull/39036#discussion_r705323107
- [x] Correct global variables interpolation on backend https://github.com/grafana/grafana/pull/39051
- [x] Time series queries in Explore https://github.com/grafana/grafana/pull/39133
  - [x] Clarify that step is actually min step in Explore and update units #41209
  - [ ] Figure out if we could/should use Warnings https://github.com/grafana/grafana/pull/39133#discussion_r709937279
- [x] Instant queries in Explore https://github.com/grafana/grafana/pull/39351
- [x] Both queries in Explore https://github.com/grafana/grafana/pull/39462
  - [ ] Check why are we not doing day light saving aligning https://github.com/grafana/grafana/pull/39462#discussion_r716636481
- [x] Exemplar queries in Explore https://github.com/grafana/grafana/pull/39531
- [x] Time series queries in Dashboard https://github.com/grafana/grafana/pull/40333
  - [x] Fix error message propagation https://github.com/grafana/grafana/pull/40674
  - [ ] Create PrefferedVizType enum https://github.com/grafana/grafana/pull/40333#discussion_r728740854
- [x] Instant queries in Dashboard https://github.com/grafana/grafana/pull/40333
- [x] Exemplar queries in Dashboard https://github.com/grafana/grafana/pull/40333
- [x] Annotation queries in Dashboard #41059
- [x] Refactor for scalability with other query types https://github.com/grafana/grafana/pull/40921
- [x] Health check query https://github.com/grafana/grafana/pull/42189
- [ ] Queries getting templating variables in Dashboard
- [ ] Load rules
- [ ] Get metadata
- [ ] Label values
- [ ] Metric names
- [ ] Label keys
- [ ] Series labels

List of all Prometheus query types and where are they used: 

| Type          | Functions                                        | Request         | Endpoint                      |
|---------------|--------------------------------------------------|-----------------|-------------------------------|
| ~Range~   | ~performTimeSeriesQuery, annotationQuery~                           | ~_request~        | ~/api/v1/query_range~           |
| ~Instant~       | ~performInstantQuery~                              |~ _request ~       | ~/api/v1/query~                 |
| ~Exemplars~     | ~getExemplars~                                     | ~_request ~       | ~/api/v1/query_exemplars~       |
| Load rules    | loadRules                                        | metadataRequest | /api/v1/rules                 |
| Get metadata  | start                                            | metadataRequest | /api/v1/metadata              |
| Label values  | fetchLabelValues, getTagValues, labelValuesQuery | metadataRequest | /api/v1/label/`${key}`/values   |
| Metric names  | metricNameQuery                                  | metadataRequest | /api/v1/label/`__name__`/values |
| Label keys    | fetchLabels, getTagKeys, labelNamesQuery         | metadataRequest | /api/v1/labels                |
| Series labels | fetchSeriesLabels, labelValuesQuery              | metadataRequest | /api/v1/series                |

**Comment by kostrse** [comment]
@ivanahuckova @MasslessParticle @marefr are you planning to migrate **templating queries** from `ds_proxy` to Prometheus backend `prometheus/promclient` in near future?

I maintain Azure authentication in Prometheus datasource.

Since templating queries which still go through the plugin proxy, the same datasource authentication logic has to be maintained to both places: in `promclient` and in `services/datasources/service.go` to have all Prometheus scenarios work.

**Comment by ivanahuckova** [comment]
+cc @grafana/observability-metrics is moving of prometheus templating queries planned for Q1?

**Comment by marefr** [comment]
@kostrse if everything needed goes through this https://github.com/grafana/grafana/blob/main/pkg/infra/httpclient/httpclientprovider/azure_middleware.go should support both ds proxy and prom client. That's why it's important to add azure related authentication fields to the https://github.com/grafana/grafana-plugin-sdk-go.

**Comment by kostrse** [comment]
Currently there are three ways to enable Azure authentication for plugin developer:

1. Via **plugin.json** routes (handled [here](https://github.com/grafana/grafana/blob/b07345e57e52ad6d7ae8240a49a38d9a76517850/pkg/api/pluginproxy/ds_auth_provider.go#L102) in `pkg/api/pluginproxy/ds_auth_provider.go`). Requires the plugin developer to configure a route with Azure authentication enabled. Currently not used by any publicly available datasources but potentially can be still useful for frontend-only plugins.
   
2. Programmatically, by configuring `httpclient.Provider` and `httpclient.Options` in plugin's backend code. Used by Azure Monitor ([here](https://github.com/grafana/grafana/blob/b07345e57e52ad6d7ae8240a49a38d9a76517850/pkg/tsdb/azuremonitor/httpclient.go#L44)), Azure Data Explorer ([here](https://github.com/grafana/azure-data-explorer-datasource/blob/95f4824d9f6b787bdf1bd76643ce536c82edfc4d/pkg/azuredx/datasource.go#L46)) and Prometheus ([here](https://github.com/grafana/grafana/blob/b07345e57e52ad6d7ae8240a49a38d9a76517850/pkg/tsdb/prometheus/promclient/provider.go#L56)). Requires the plugin developer to implement code that configures the `httpclient.Options`.

3. Via **JsonData** (handled [here](https://github.com/grafana/grafana/blob/b07345e57e52ad6d7ae8240a49a38d9a76517850/pkg/services/datasources/service.go#L281) in `pkg/services/datasources/service.go`). Used by Prometheus templating queries. It allows any user with write access to datasources to enable Azure authentication on any datasource and send access token to any endpoint, even if datasource doesn't explicitly provide configuration UI for it (user can update JsonData directly via REST API).

Currently the (3) isn't big concern because it requires feature flag `httpclientprovider_azure_auth` to be enabled. But I was thinking to remove this capability (by deleting [this block of code](https://github.com/grafana/grafana/blob/b07345e57e52ad6d7ae8240a49a38d9a76517850/pkg/services/datasources/service.go#L280-L290) in `pkg/services/datasources/service.go`) simply because no datasource is going to use it in the foreseeable future and it's just unnecessary exposure that could be attack surface potentially.

The only thing that requires (3) are **Prometheus templating queries** which still follow that code path.

@marefr What do you think about this?

**Comment by marefr** [comment]
> The only thing that requires (3) are **Prometheus templating queries** which still follow that code path.

@kostrse yes, so if you remove this now Prometheus templating queries will not work until the task _Templating queries in Dashboard_ have been fixed. I'm not sure these changes makes sense now? Was this the cleanup PR referred to with "I will send one more cleanup PR before adding strongly-typed configuration to grafana-plugin-sdk-go" in https://github.com/grafana/grafana/pull/44407#issuecomment-1026581073?

**Comment by kostrse** [comment]
>  I'm not sure these changes makes sense now?

@marefr It's not urgent right now. I just thinking to remove Azure auth from JsonData sooner or later (3), so I'm curious if there're any plans to close on the templating queries, as it affects how do I plan my further Azure auth work.

I can continue to maintain support for Azure auth in JsonData as long as it required for templating queries.

**Comment by taleena** [comment]
New issue from this epic added to represent a dependency: https://github.com/grafana/grafana/issues/48790
This epic likely needs to be cleaned and closed.

**Comment by ivanahuckova** [comment]
I am closing this issue as it is old and it seems not to be used anymore. IF anyone uses this, feel free to reopen it.
