### ISSUE TITLE
Epic: Navigation improvements (WIP)

### ISSUE THREAD

**Issue by lukasztyrala** [grafana/grafana#37961]
# Background

Grafana is expanding as a product. More applications, plugins, data sources, features, workflows are added and made possible within the Grafana interface. The integration and interoperability of open-source and commercial offerings (Enterprise, Cloud) move forward. Grafana is becoming an operating system for observability (and beyond). All that makes navigating Grafana more challenging, and we need to prepare the product's structure and information architecture for the future.

## Epic use cases

As people we need navigation that fits our mental model, so do not have to learn the implementation model to understand how to locate and use Grafana's apps and features.

As a user, I need an intuitive way to move around Grafana, so I do not have to rely on muscle memory and learn untypical paths to find features I am looking for.

As a user, I want more flexibility in managing my interface, so I can access my apps and features faster and spend less time clicking around.

As a user, I want to navigate Grafana no matter the screen size, so I can choose where and how I interact with Grafana.

As an administrator I want Grafana users to be able to find dashboards, features, and apps they need faster, so I do not need to support them in exploring the product.

As an administrator I want Grafana to better support Stacks/Organisations/Instances setup, so I can navigate faster.

As an administrator, I need a better structure of admin and configuration apps, so I can spend less time finding information, making changes, troubleshooting problems, and managing my instances/stacks, organizations, teams, users, and resources.

As a plugins developer, I need more guidance and features to make my apps and plugins easy to discover and navigate for end users.

As a Grafana developer, I need a standardized way to implement new features, plugins, and apps, so that the user experience is consistent and the development process is faster and more reliable.

As a designer, I need good information architecture as a foundation for features and interaction that I design so that people can navigate Grafana easily.

As a Cloud/Enterprise/OSS division, we need navigation that fits our specific context, so that users can navigate Grafana easily and make full use of the product's features.

# Core navigation stories/issues
Prioritised issues we're currently working on or planning to do so. 

## Navbar (OS-level navigation)

- [ ] Accessibility improvements
	- [x]  [Keyboard navigation](https://github.com/grafana/grafana/issues/38454) 
- [x] Highlight current navbar page (@VesnaDean) https://github.com/grafana/grafana/issues/39021
- [x] Refactor Navbar https://github.com/grafana/grafana/issues/38507
- [x] Restructure Navbar into sections: home, core apps, installed apps, config (+ profile and help) https://github.com/grafana/grafana/pull/41045
- [x] Rename Sidemenu -> Navbar https://github.com/grafana/grafana/issues/39478
- [ ] Customize navbar
     - [x] #43822
     - [ ] Implement ability to find and organize navbar items with UX designs #46354
- [ ] Expand profile logo to flyout with user profile actions
- [ ] Placeholder to revise megamenu based on user testing feedback

## Folders management (@amy-super)

- [ ] [In-situ folder management](https://docs.google.com/document/d/1RKGvbx6Hwh1CZHQvuo22ad2U4vwcmxOTTPK646_UBM8/edit#). Move folder management features from tabs template to folder list view. Figma file [here](https://www.figma.com/file/esk6QuF0SSt8jY2UsggXJp/?node-id=842%3A8085). 
     - [ ] #43918
     - [ ] #43919
     - [ ] #43920
     - [ ] #43923
     - [ ] #43927
     - [ ] #43928
     - [ ] #43929
     - [ ] #43930
     - [ ] #43931
     - [ ] #43932
     - [ ] #43933

# To be explored
Not prioritised collection of ideas that we might consider in the future. Everything here requires technical, design, and product exploration.

## Navbar (OS-level navigation)

- Home logo as an expandable section
- Better Org/Stack switcher in the Navbar
- User/Org/Stack app section personalisation
- Move home link from Dashboards and add title/hover state for logo
- All apps / Plugin marketplace expanded view for home navbar element

## App/plugin/ds (app level navigation)

- App 1st level navigation + app title redesign and PoC
	- The name of an app as a homepage for the app?
- Config apps vs Canvas apps?
- Common/Important Actions button section in the 1st level of navigation
- Introduce 2nd level navigation for apps
- Breadcrumbs
	- Design breadcrumbs component
	- Folders and Dashboards(!) as an organisation structures not apps/building blocks

## Object level (user-created entities level navigation)

- Object title and back to list button
- Object (entity) level navigation design
- Object-level navigation and breadcrumbs – how they work together?
- Migrate from Full-screen pages → Templates

## Mobile/narrow viewports navigation

- Home and core apps bottom navbar on mobile + expanded menu for installed apps
- Application navigation + expanded app navigation

## Homepage

- Change nesting of the homepage – home dashboard as a homepage for Dashboard app + a dedicated homepage template with no Home Dashboard?
- PoC for creating a dedicated template for the homepage that can include both (Home) dashboard section (managed and configurable by admins/editors) and other components (fixed and predetermined by home template)
- Dedicated templates per division (OSS as a default, Enterprise, Cloud)

## Satellite projects stories/issues

To improve information architecture and navigability some features need to be fixed or restructured to allow new navigation to work.

### Dashboard app improvements

- #39169
	- Change home dashboard title (icon + name) to improve the clarity of information architecture
	- Rename Dashboard app home tab from Manage to Browse
	- Remove Home dashboard link from Dashboard icon in the navbar (flyout menu on hover)
	- Remove Add icon from the navbar

### Components standardization

- Standardise objects list's search, filter, sort, actions bar
- Interrupted and auxiliary workflows – modals/drawers

### Server admin and Configuration redesign

- Merge Configuration and Server admin apps into a single configuration app
- Redesign information architecture for server admin and org configuration pages, considering moving away from organizations, introduction of fine-grained access control and need to expose server admin sections to Grafana Cloud product
	- Clean up User/Team management
	- Redesign stats page
	- Bring config.ini into Grafana configuration

### Other…

- Whitelabeling options with new navigation
- App / Plugin / App plugin / Data source / Data source plugin – naming conventions and clean-up
- Nested folders (https://raintank-corp.slack.com/archives/C036J5B39/p1628619652089200) feature
