### ISSUE TITLE
Roadmap: Observability Squad

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#38004]
# 8.2 Roadmap

### New features
- [ ] https://github.com/grafana/grafana/issues/19348
- [ ] Shared cursor between graph and logs panel
- [ ] Make <kbd>Shift</kbd>+<kbd>Enter</kbd> a global keyboard shortcut
- [ ] Query History: Team History
- [ ] Graph styles mode:
  - [ ] https://github.com/grafana/grafana/issues/17439

### Tech / Refactors
- [ ] Accessibility improvements
- [ ] Integrate trace view more with Grafana and grafana/ui

### Backend migrations
 - [ ] https://github.com/grafana/grafana/issues/37784

### Tech / Refactors
- [ ] Migrate Prometheus query editor to Monaco
- [ ] Migrate Graphite query editor to React

### New features
- [ ] Service map for Tempo/Prometheus
- [x] Tempo search
- [ ] https://github.com/grafana/grafana/issues/19949 (full range histogram for Loki)
- [ ] Add search highlight for other logging datasources

# Post 8.2
- https://github.com/grafana/grafana/issues/12757
- Logs to trace for X-Ray Data Source
- Allow creating new dashboard from explore or save it to panels library
- Allow plugins to add or configure visualisations in Explore
- Mixed datasources in Explore
