### ISSUE TITLE
Accessibility checks: Phase 2 - Adding Pa11y CI PR stage

### ISSUE THREAD

**Issue by thisisobate** [grafana/grafana#38063]
In phase 1 of the [accessibility checks project](https://github.com/grafana/grafana/issues/36555), we implemented a solution that allows us to collect a11y metrics on main branch and populate to a dashboard.

As for phase 2, we want to add a11y checks in the PR pipeline to prevent regression.

**Todos**
- [ ] Set thresholds for accessibility errors
- [ ] Log new a11y errors introduced by a PR
- [ ] Introduce new HTML reporter to visualize what are the current a11y issues, something like this https://gitlab-ci-utils.gitlab.io/pa11y-ci-reporter-html/
