### ISSUE TITLE
Checklist: migrate datasources backend code to use DataQuery.Interval

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#38899]
with https://github.com/grafana/grafana/pull/38434 merged, now the `DataQuery.Interval` value has a good value that a datasource can use, both in alerting (new and old) and in dashboard and explore-mode queries.
there is no need to manually call `interval.GetIntervalFrom`, `interval.Calculate`, `tsdb.GetIntervalFrom` or `tsdb.Calculate` to calculate it.

here is a list of datasources that call the above-mentioned functions and could be simplified:
- [ ] sql_engine
- [x] elasticsearch
- [x] prometheus (this one is complicated, the interval-handling in prometheus is complex because of the min_step + safe_step + interval_factor things, so it cannot just use `DataQuery.Interval`... so i say let's consider prometheus done)
- [x] loki
- [ ] azuremonitor (only uses interval.getIntervalFrom so it might not apply here)
- [ ] cloudmonitoring (only uses interval.calculate, so it might not apply here)

note: it is possible that the given data-source has something special and it is not possible to use the generic code, and that is ok. but we should check each datasource if we can simplify their code.
