### ISSUE TITLE
Tempo: Search UI Improvements

### ISSUE THREAD

**Issue by connorlindsey** [grafana/grafana#39241]
# Background
Tempo Search is currently behind a feature toggle. Below are the improvements we're making to the UI before release.

# Improvements
- [x] Run query with Ctrl+Enter in all text fields - #39247
- [x] Better handling of async fetching of autocomplete values - #39371
- [x] Add to query history - #39250
- [x] Add beta tag  - #39489
- [x] Add ability to opt-out of search - #39489
- [x] Info message if search is not enabled in the backend - #39489
- [x] Hide Loki search if not configured (separate config from trace to logs config) - #39534
- [x] Ctrl+Enter on dropdowns - #39534
- [x] Set default limit - #39534
- [x] Input validation - #39534
