### ISSUE TITLE
Microsoft Fastpass Tasks

### ISSUE THREAD

**Issue by kaydelaney** [grafana/grafana#39429]
Checklists for keeping track of pages whose fastpass issues we've fixed.
(Put your avatar next to issues you'd like to take on)

### Admin  (![avatar](https://github.com/kaydelaney.png?size=24))
- [ ] /admin/orgs
- [ ] /admin/orgs/edit/{id}
- [ ] /admin/upgrading

### Datasources
- [ ] /datasources
- [ ] /datasources/edit (gdev-cloudwatch)

### Teams
- [ ] /org/teams (empty)
- [ ] /org/teams/new
- [ ] /org/teams/edit/{id} (Add team member)
- [ ] /org/teams/edit/{id}
- [ ] /org/teams/edit/{id}/settings

### Org Misc.
- [ ] /org
- [ ] /org/apikeys (empty)
- [ ] /org/users

### Alerting
- [ ] /alerting
- [ ] /alerting/list
- [ ] /alerting/groups
- [ ] /alerting/silence/new
- [ ] /alerting/notifications
- [ ] /alerting/notifications/templates/new
- [ ] alerting/notifications/receivers/new
- [ ] alerting/routes (edit)

### Misc
- [ ] /explore (with gdev-testdata)
- [ ] /profile
- [ ] /plugins

### Dashboard Management
- [ ] /dashboards
- [ ] /dashboards/folder/new
- [ ] /dashboard/import
- [ ] Dashboard search
- [ ] /playlists
- [ ] /playlists/new
- [ ] /library-panels

### Dashboards
- [ ] Share modal
- [ ] Add panel
- [ ] Edit panel (gdev-testdata/timeseries)

#### Dashboard Settings
- [ ] General
- [ ] Annotations
- [ ] Annotations edit
- [ ] Variables
- [ ] Variables new
- [ ] Dashboard links
- [ ] Versions
- [ ] Permissions
- [ ] Json model
