### ISSUE TITLE
Loki: Full range logs volume improvements 

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#39856]
Follow up on #39327.

Questions/tasks:
- [ ] How to handle instant queries? 
  - ~Hide logs volume?~
  - ~Show a warning message the graph may not make sense?~
  - Force logs volume query to always be a range query
- [ ] Should panel size be fixed if volume is not loaded/while loading? ([reference](https://github.com/grafana/grafana/pull/39327#discussion_r719139631))
- [ ] Cache results to keep logs volume when more logs are loaded ([reference](https://github.com/grafana/grafana/pull/39327#discussion_r719141905))
- [ ] Performance:
  - Remove auto-loading?
  - Separate time timeout for logs volume and a warning message telling that time range should be narrowed down or query made more specific
  - Load histogram only up to restricted time range
- [ ] https://github.com/grafana/grafana/issues/39915 
- UI:
  - [ ] Histogram takes too much vertical space?
  - [ ] No need to take so much space with a single button? 
  - [ ] Show all stacked values in the tooltip?
- UX:
  - [ ] Could we show partial histogram first with an option to load full-range?

**Comment by slim-bean** [comment]
A couple thoughts/things I've noticed:

I was originally hoping the implementation would keep the current behavior of showing the generated histogram from the log results with an option to then load the entire time range through a button.

I still think the partial range histogram would be useful.

My other feedback is related to this but not specific to just this, there is a lot of vertical space used by "non-log" results.

This is made much more noticeable when the histogram doesn't load:

![image](https://user-images.githubusercontent.com/10332331/136038335-577c1509-c205-402a-9df9-c335c598da87.png)

However even when the histogram loads, there is still a huge amount of vertical space consumed by buttons, padding, other white space etc.

![image](https://user-images.githubusercontent.com/10332331/136038491-a55c5327-0624-4708-868c-ef76a041190f.png)

This gets much worse if you try to add multiple queries:

![image](https://user-images.githubusercontent.com/10332331/136038601-bef15e6f-b5b8-4a13-945b-a48964c2a697.png)

And to make things even more frustrating at times, when you have a refresh set on the query, it auto scrolls to the top on every reload making it nearly impossible to just see the log content auto refreshing in a small window.

The whitespace and usability is really probably a separate issue it just becomes way more obvious when the histogram isn't present.

So really I was just hoping to see the current generated histogram with an option to load the full histogram.
