### ISSUE TITLE
Tempo: Service Graph Improvements

### ISSUE THREAD

**Issue by connorlindsey** [grafana/grafana#39879]
## Background
The Service Graph feature is currently behind a feature toggle. Below are the improvements we're making to the UI before relase.

## Improvements

**Comment by joe-elliott** [comment]
- [ ] Automatically clear results when swapping tabs. When I do a service graph query and then swap to "TraceID" the service graph is still visible. 
  ![image](https://user-images.githubusercontent.com/2272392/137316919-b8c00dca-a393-46a8-8a2f-1a060d881477.png)
- [ ] Service graph is only showing two nodes (cortex-gateway and gme-distributor) when `tempo_service_graph...` metrics show far more pairs.

**Comment by mapno** [comment]
- [ ] Rename metric's namespace from `tempo` to `traces` ([context](https://github.com/grafana/agent/pull/988#discussion_r728944825))

**Comment by mapno** [comment]
> I am not sure this makes sense. Technically and practically your are not switching tabs but just changing query type and you still have to run the query. Like if you go to traceId query type, to change the contents of the explore we would (as the code is currently structured) run the query, but because there is no TraceId it would just return 404. When going to ServiceGraph, there is no filtering but if we add some it would be a bit clearer that this is just different query. And in general I think it makes sense to show the old query results until user runs a new query. Maybe it could be argued that the tabs input element for the Query type isn't super intuitive here.

I agree with the sentiment that I would expect data to automatically load when selecting service graphs. Specially now since there isn't any filtering to do. Maybe when it's possible to filter it may be more intuitive, since it'll be similar to how other data sources work.

> Would it make sense to have a prometheus query field here? Just allowing to select labels?

My idea was implementing something similar searching for logs with LogQL, when you initially filter by tags. Those tags then can be appended to the prometheus query.

I.e. filtering by `{cluster="my-cluster"}` is translated to `sum(rate(traces_service_graphs_request_total{cluster="my-cluster"}[5m])) by (service,client)`.

I'm not familiar enough with prometheus+grafana, but maybe it could be possible to fetch the available labels as you can with prometheus metrics.

**Comment by mapno** [comment]
Trying to recap a bit the different ideas/improvements we still have in this issue:

- [ ] Slideout panel with additional data
- [ ] Filtering pulls all available tags, instead those of the service graphs metrics `traces_service_graphs...`. We should see `client`, `server` and only a few other more tags.
- [ ] Outline of nodes sometimes appears displaced (this is in Chrome `v95.0.4638.69`, macOS Monterrey)
![image](https://user-images.githubusercontent.com/39532714/142409230-b79793e6-45d6-48de-87c9-849fd09e3520.png)
- [ ] Node distribution sometimes is not optimal, and edges will cross each other when it's not necessary. 
![image](https://user-images.githubusercontent.com/39532714/142409985-4e111380-5bbc-4336-92db-5e47aa21cbe0.png)
- [ ] When linking nodes/edges to source data, it'd be great if the query is filtering based on what's selected.
- [ ] (Idea) Move data from nodes to edges.
- [ ] Stretch: Compare two different time ranges
- [ ] (Optional) Make possible to drag nodes around
- [ ] (*) Initiate a service graph query on switch the tab. Currently, after swapping to the tab, you have to manually hit the blue "Run query" button.
- [ ] (*) Automatically clear results when swapping tabs. When I do a service graph query and then swap to "TraceID" the service graph is still visible

(*): There's been different discussions about these topics, pointing out it's working as expected and in line with other implementations. Listing them here anyway.

**Comment by connorlindsey** [comment]
Closing. Will track future changes in separate issues
