### ISSUE TITLE
Integration tests: Remove `go build tags` from integration tests

### ISSUE THREAD

**Issue by dsotirakis** [grafana/grafana#40473]
**What happened**:

Currently, we use `go build tags` ([link](https://pkg.go.dev/go/build#hdr-Build_Constraints)) to declare integration tests go files. This is not the best option, since tags signatures may change as we move to newer Golang versions.

**What you expected to happen**:

We shouldn't depend on `go build tags`. A good pattern that can be used is setting environmental variables on CI (or locally) and then checking inside the actual integration tests to see if the variable is set. More info/ideas [here](https://peter.bourgon.org/blog/2021/04/02/dont-use-build-tags-for-integration-tests.html)

To do:

OSS
- [x] Rename OSS integration tests to follow new naming convention #49438
- [x] Run OSS integration tests without grabpl #49448
- [x] Prevent OSS test-backend from running integration tests #50359 

Enterprise
[Chore: Remove go build tags from enterprise integration tests #3443](https://github.com/grafana/grafana-enterprise/pull/3443)
- [x] Rename enterprise integration tests to follow new naming convention
- [x] Run enterprise integration tests without grabpl

**Comment by marefr** [comment]
Related https://github.com/grafana/grafana/issues/39197
