### ISSUE TITLE
Microsoft Fastpass Tasks

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#40505]
### Alerting
- [ ] ~~/alerting~~
- [x] /alerting/list #40816
- [x] /alerting/groups #40943
- [x] /alerting/silence/new
- [x] /alerting/notifications
- [x] /alerting/notifications/templates/new
- [x] alerting/notifications/receivers/new
- [x] alerting/routes (edit)

**Comment by kaydelaney** [comment]
Several of these issues have been fixed by #41154 I think

**Comment by peterholmberg** [comment]
All done 🥳
