### ISSUE TITLE
PluginsCatalog: clean up the legacy plugin management code and add possibility to enable/disable plugin installation.

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#40503]
**Description:**
Remove the legacy plugin management code in favor of the new plugins catalog. We should probably also change/add a configuration value to enable/disable the plugin installation functionality in the plugin catalog.

**Todo:**
- [x] Clean up routing to use a single entry-point under `public/app/features/plugins/admin` (https://github.com/grafana/grafana/pull/41686)
- [x] Remove old plugin management components (https://github.com/grafana/grafana/pull/41686)
- [x] Remove old plugin state-handling code (https://github.com/grafana/grafana/pull/41739)
- [x] Make it possible to enable/disable install controls in the plugins catalog. (https://github.com/grafana/grafana/pull/41749)
- [ ] ~Get rid of nav-trickery in the backend (@jackw for more information).~ Talked to @jackw about this and we agreed that would take this to a separate task.
