### ISSUE TITLE
Epic: Icon Panel - basic icon panel support (beta release)

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#40722]
This is an epic issue to track changes need to make the icon panel usable for 8.3

NOTE: Icon panel is being removed v10.1
- [x] #68861

TODO:
- [x] Force icon to 100% width and height
- [x] Add 'icon' to value mapping editor
  - [x] #43939
  - [x] #44236
  - [x] #44298
  - [x] #44341
  - [x] #40723
  - [x] #44016
- [x] Address bugs / glitches
  - [x] #46595
- [ ] Improve out-of-the-box options
     * backgrounds: https://github.com/grafana/grafana/tree/main/public/img/bg
     * geomap icons: https://github.com/grafana/grafana/tree/main/public/img/icons/marker
     * iot icons: https://github.com/grafana/grafana/tree/main/public/img/icons/iot
- [ ] Explore uploading option

**Comment by grafanabot** [comment]
This issue was removed from the 8.5.0 milestone because 8.5.0 is currently being released.

**Comment by nmarrs** [comment]
The decision was made to remove icon panel from Grafana core starting in v10.1. We recommend using [the canvas panel](https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/canvas/) instead for this functionality

**Comment by nmarrs** [comment]
Closing out this epic as we removed the icon panel from Grafana core
