### ISSUE TITLE
Visualizations: Suggestions & Previews Epic 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#40804]
* [x] Real visualization previews that work at small scale. This works by first rendering them at large scale and then scaling it down #40527 
* [x] VisualizationSuggestionsBuilder abstraction that caches some data attributes so they can be shared
* [x] VisualizationSuggestionsAppender makes typing easier for each suggestion supplier 
* [x] Preview gets tweaked options to improve preview (increased line width, limit on values in panels that use VizRepeater etc).  
* [x] New updated action that can apply plugin change & options & fieldConfig in one action. 
* [x] Some basic inspection of data that adapts settings and what visualizations to show, these can only get refined over time. This feature will never be done.  
* [x] Presented in ux feedback session 
* [ ] Add ranking to each suggestion so that they are presented in order of how well they fit the data. 
* [x] Make search work
* [ ] Add keyboard navigation 
* [ ] Fix AutoSizer issue, wish the splitter could send the width so we do not have to use AutoSizer, it cases scrolling flickers. I can get split pane to send width but no while you drag
* [ ] Support suggestions that show icon instead of real panel (useful for news, dashboard list, alert list & others) 
* [ ] Show suggestions inside panel when panel cannot render current data (new component) 
* [ ] Show option suggestions somewhere inside pane (different form of suggestion) 
* [x] Bar chart suggestions 
* [x] Time series suggestions
* [x] Pie chart suggestions
* [x] Bar gauge
* [x] Gauge
* [x] Stat 50%
* [x] Timeline
* [ ] XY chart 
* [ ] Status grid
* [ ] Logs panel
* [ ] Histogram
* [ ] News panel
* [x] Unit tests
* [x] e2e test

Issues / problems
* [ ] Should we overwrite all current panel options, field config & overrides? What options to do we have here. 
* [ ] Optional title for cards (50%, not enabled yet), some panels could need a title somtimes
