### ISSUE TITLE
Geomap multiple layers and additional layer capabilities

### ISSUE THREAD

**Issue by nikki-kiga** [grafana/grafana#41219]
Enable multiple layers and add additional functionality to markers, GeoJSON, and text layers.

- [x] Add style options based on GeoJSON feature properties 
- [x] Support multiple layers
- [x] Add custom icon functionality through resource picker on markers layer
- [x] Add text layer
- [x] Use GeoJSON for gazetteer instance
- [x] Initial field lookup transformation
- [ ] #41224

Bugs:

Nice to haves:
- [ ] #41221
- [ ] #41222
- [ ] #41223

**Comment by nmarrs** [comment]
Moved to https://github.com/grafana/grafana/issues/36585
