### ISSUE TITLE
Translate navigation proof-of-concept

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#41610]
Epic to track progress on developing a proof of concept for internationalising Grafana using Lingui, starting with the navigation.

 - [ ] Move babel config out of Webpack so it can be used standalone
 - [ ] Add Lingui core framework (babel changes, `<I18nProvider />` app wrapper)
 - [ ] Interim manual `lingui extract` / `lingui compile` workflow
 - [ ] Figure out how to translate menu items which [come from the backend...](https://github.com/grafana/grafana/blob/main/pkg/api/index.go#L141) 😬
 - [ ] Mark up desktop menu with `<Trans />` for translating
 - [ ] Mark up mobile megamenu with `<Trans />` for translating
 - [ ] Translate extracted messages
 - [ ] Add user preference for switching locale

**Comment by osg-grafana** [comment]
cc @osg-grafana
