### ISSUE TITLE
POC 2: Plugin examples with integration tests (locally first, CI later)

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#41756]
### Description
The goal of this POC is to create a set of examples on how to implement the "most" popular features of plugins. Together with each example we should create a test suite that can be used to verify that the example is working when doing changes in the Grafana repository. When this POC is done we should have examples, tests and a way of running them against a given commit of the Grafana repository.

Benefits of this approach:

- We can use these examples to showcase/documentation of how to extend Grafana.
- We can run the tests of these examples on a regular basis to verify that none of the APIs are broken between major versions.

To scope this POC we should only create a couple of examples to cover the most basic functionality of Grafana.

### Tasks
- [x] https://github.com/grafana/grafana/issues/42208
- [ ] https://github.com/grafana/grafana-plugin-examples/issues/14
- [ ] https://github.com/grafana/grafana-plugin-examples/issues/12
- [ ] https://github.com/grafana/grafana-plugin-examples/issues/11
- [ ] https://github.com/grafana/grafana-plugin-examples/issues/9

**Comment by mckn** [comment]
Closing in favor of epic https://github.com/grafana/grafana/issues/35656
