### ISSUE TITLE
Refactor: Migrate to Opentelemetry

### ISSUE THREAD

**Issue by idafurjes** [grafana/grafana#41968]
We want to migrate to Opentelemetry. Not to break the backward compatibility we want to leave the Jeager Opentracing solution and add a possibility to configure Opentelemetry (with Jaeger) instead of Opentracing.

Steps to migrate to Opentelemetry
- [x]  Add configuration for Opentelemetry and add an Tracer interface https://github.com/grafana/grafana/pull/41963
- [x]  Use the Tracer interface instead of opentracing trough codebase https://github.com/grafana/grafana/pull/42674
- [x]  Remove global variable GlobalTracer
