### ISSUE TITLE
Plugins: Setup repository that includes popular plugins

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#42180]
### Description
Create a github repository that includes the following plugins as git sub modules (if we don't have any other suggestions). We start with the most "popular" plugins available to start verifying the most used plugins but also to challenge this approach. This repository needs to be private to be able to include enterprise plugins.

The "internal" plugins have been excluded from the lists since they will not be able to build outside of the Grafana repository. Data source plugins have been selected based on number of queries in HG. Panel and App plugins have been selected based on download count from `grafana.com`. 

Data source plugins:
- https://github.com/grafana/servicenow-datasource
- https://github.com/alexanderzobnin/grafana-zabbix
- https://github.com/grafana/appdynamics-grafana-datasource
- https://github.com/grafana/newrelic-datasource

Panel plugins (skipping clock panel to get a better sample):
- https://github.com/grafana/piechart-panel
- https://github.com/grafana/worldmap-panel
- https://github.com/NatelEnergy/grafana-discrete-panel
- https://github.com/Vonage/Grafana_Status_panel

App plugins:
- https://github.com/TencentCloud/tencentcloud-monitor-grafana-app
- https://github.com/alexanderzobnin/grafana-zabbix
- https://github.com/grafana/synthetic-monitoring-app
- https://github.com/RedisGrafana/grafana-redis-app

### Tasks
- [ ] Repository is created
- [ ] Submodules are added
- [ ] Script to update all submodules is available

### Note
This is a subtask of the https://github.com/grafana/grafana/issues/41755 issue.
