### ISSUE TITLE
Plugins: Script to be able to build app plugins with latest version of Grafana (POC1)

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#42192]
### Description
Setup a script that can be used to update and build app plugins with the latest version of Grafana. This script should update both the frontend and the backend package.

Should we update to latest version of the `@grafana/packages` or should we update to latest compatible according to what is specified in the `plugin.json`?

Should we update the backend package as well?

### Tasks
- [ ] Script can build app plugins
- [ ] Script can update app plugin with latest version of `@grafana/packages`
- [ ] Script can update app plugin with latest version of grafana backend sdk.

### Note
This is a subtask of the https://github.com/grafana/grafana/issues/41755 issue.
