### ISSUE TITLE
Plugins: Script to be able to build datasource plugins with latest version of Grafana (POC1)

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#42190]
### Description
Setup a script that can be used to update and build datasource plugins with the latest version of Grafana. This script should update both the frontend and the backend package.

Should we update to latest version of the `@grafana/packages` or should we update to latest compatible according to what is specified in the `plugin.json`?

Should we update the backend package as well?

### Tasks
- [ ] Script can build datasource plugins
- [ ] Script can update datasource plugin with latest version of `@grafana/packages`
- [ ] Script can update datasource plugin with latest version of grafana backend sdk.

### Note
This is a subtask of the https://github.com/grafana/grafana/issues/41755 issue.
