### ISSUE TITLE
Plugins: Audit popular plugins and setup repository for examples (POC2)

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#42208]
### Description
Do an audit of the plugins specified below and track what features of the plugin SDKs are being used. Create a new Github repository that will be the host for the plugin examples and their integration tests. Within this repository create separate issues with a description for each of the examples that we should implement.

Data source plugins:
- [x] https://github.com/grafana/servicenow-datasource
- [x] https://github.com/alexanderzobnin/grafana-zabbix
- [x] https://github.com/grafana/appdynamics-grafana-datasource
- [x] https://github.com/grafana/newrelic-datasource

Panel plugins (skipping clock panel to get a better sample):
- [x] ~~https://github.com/grafana/piechart-panel~~
- [x] https://github.com/grafana/worldmap-panel
- [x] https://github.com/NatelEnergy/grafana-discrete-panel
- [x] https://github.com/Vonage/Grafana_Status_panel

App plugins:
- [x] https://github.com/TencentCloud/tencentcloud-monitor-grafana-app
- [x] https://github.com/alexanderzobnin/grafana-zabbix
- [x] https://github.com/grafana/synthetic-monitoring-app
- [x] https://github.com/RedisGrafana/grafana-redis-app

### Tasks
- [x] Plugins have been audited
- [x] Repository is created (https://github.com/grafana/plugins-examples)
- [x] Issues for what examples to implement is created

### Note
This is a subtask of the https://github.com/grafana/grafana/issues/41756 issue.

**Comment by mckn** [comment]
### tencentcloud-monitor-grafana-app

- How to create a query editor
- How to query support data in a query editor
- How to create a datasource configuration editor
- How to implement a data source (with backend)
- How to include dashboard json

**Comment by mckn** [comment]
### alexanderzobnin-zabbix-app

- How to create a query editor
- How to query support data in a query editor
- How to create a datasource configuration editor
- How to implement a data source (with backend)
- How to include dashboard json
- How to work with "nested" plugins
- How to get current time range
- How to support template variables
- How to support annotations
- How to migrate datasource json data between plugin versions
- How to store credentials

**Comment by mckn** [comment]
### grafana-synthetic-monitoring-app

- How to setup different pages with routing in an App
- How to configure an App plugin with/without tabs.
- How to navigate with `getLocationSrv`.
- How to work with "nested" plugins

**Comment by mckn** [comment]
### grafana-redis-app

- How to work with "nested" plugins
- How to setup provisioning of datasources and apps
- How to configure an app plugin
- How to create a panel plugin with custom configuration
- How to use the form components.
- How to create/convert your data into a data frame (so it can be used in visualizations).
- How to get current time range
- How to include dashboard json
- How to configure an App plugin with/without tabs.

**Comment by mckn** [comment]
### worldmap-panel

- How to publish app events to display generic error messages.
- How to support light/dark theme (automatically done if the plugin uses grafana theme).
- How to query support data in a panel.

**Comment by mckn** [comment]
### grafana-discrete-panel

- How to publish custom app events.
- How to support multiple major versions of Grafana.
- How to format values (to prevent implementing custom formatting).
- How to support annotations in panel.
- How to use tooltip in panels.
- How to update the time range from a panel.

**Comment by mckn** [comment]
### grafana-discrete-panel

- How to migrate plugin configuration between versions.
- How to use time series panel.
- How to format display values.

**Comment by mckn** [comment]
### newrelic-datasource

- How to add annotations query editor.
- How to add config query editor.
- How to add variable query editor.
- How to add a query editor.
- How to implement a data source.
- How to include dashboards.
- How to migrate configuration data and queries.

**Comment by mckn** [comment]
### appdynamics-grafana-datasource

- How to add config query editor.
- How to add a query editor.
- How to implement a data source.
- How to support template variables.
- How to query support data.
- How to include dashboards.

**Comment by mckn** [comment]
### servicenow-datasource

- How to add config query editor.
- How to add a query editor.
- How to add template query editor.
- How to implement a data source.
- How to migrate configuration data and queries.
- How to include dashboards.
- How to use form components.

**Comment by mckn** [comment]
Closing in favor of sub issues to #41756
