### ISSUE TITLE
Epic: Next gen redux state

### ISSUE THREAD

**Issue by kaydelaney** [grafana/grafana#42283]
The purpose of this epic is to track our progress with migrating dashboard state to redux, starting with a number of experiments listed below.

### Experiments

- [ ] #42292
- [x] #42293
- [x] #44262 ![avatar](https://github.com/hugohaggmark.png?size=24)
- [ ] Design a pattern for updating a dashboard setting/attribute
- [ ] Cache dashboard state
