### ISSUE TITLE
Explore button leads to "Unexpected error" for  plugins that are using GrafanaTheme and Grafana 8.2+

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#42361]
**Why?**
Following up on this escalation https://github.com/grafana/support-escalations/issues/1421, we have to check if there are more plugins that are potentially affected by this bug and need to be updated.

**Goal**
- Find out what was causing the issue
- Find out which plugins might be affected by this
- Figure out how to info plugin developers if there are breaking changes in `8.2+`

**How to reproduce?**
- Go [here](https://g82-beta.grafana.net/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22AWS%20IoT%20Sitewise%22,%7B%22timeOrdering%22:%22ASCENDING%22,%22refId%22:%22A%22,%22maxPageAggregations%22:1,%22queryType%22:%22PropertyValueHistory%22,%22assetId%22:%226edf67ad-e647-45bd-b609-4974a86729ce%22,%22propertyId%22:%223016a465-b862-47bc-8e24-0cc7b619347e%22%7D%5D) and click on "Explore" at the top right

**What fixes the issue?**
Updating dependencies and switching to using `GrafanaTheme2`
Example PR: https://github.com/grafana/iot-sitewise-datasource/pull/109/files

**Affected versions**
- Upgrading from `8.1.5` to `8.2.3`

**Might be relevant for**
- Detecting breaking changes theme (https://github.com/grafana/grafana/issues/35656)

**Tasks**
- [ ] Identify plugins that are using any of the [mixins](https://github.com/grafana/grafana/blob/52316606276d4322358eec0d761e0dfe411b04a0/packages/grafana-ui/src/themes/mixins.ts) from `@grafana/ui`
- [ ] Make sure that none of those plugins depend on Grafana `>=8.2.0` in case they still didn't update their code
- [ ] Update the [migration guide](https://github.com/grafana/grafana/blob/d98cb8274c93c1ae135f31eeab26f17948edb66c/docs/sources/developers/plugins/migration-guide.md) with notes on how to update the usage of any [mixins](https://github.com/grafana/grafana/blob/52316606276d4322358eec0d761e0dfe411b04a0/packages/grafana-ui/src/themes/mixins.ts) when upgrading from Grafana `<= 8.1.x` to `>= 8.2.0`

**Comment by marefr** [comment]
Potential `grafanaTheme` usage in the grafana org: https://github.com/search?l=TSX&q=org%3Agrafana+grafanaTheme&type=Code

**Comment by mckn** [comment]
Things we should do regarding this:

- Highlight this, within the company to raise awareness, as an example on a breaking change for plugins.
- Update the plugins migration guide so other plugin developers are aware that this is a breaking change.
- Create an example on how they should have made this change but still keep backward compatibility.
- Update the `grafanaDependency` of plugins that are using the `styleMixins.listItem` so you will not be able to install plugins that isn't compatible.

**Comment by leventebalogh** [comment]
After some thinking I am deciding to move this issue back to the `Planned` column for now.

The main reason is that most of the actions that we could take would require us to get more data on how other plugins are depending on our packages and what they actually use from them. We are currently focusing on getting this information together, and then we will get back to this.

Updated the list of tasks with some links, so it is easier to pick it up when we get back to it.

**Comment by tolzhabayev** [comment]
@leventebalogh can we use the data collected now to find out which plugins are affected?
