### ISSUE TITLE
Improve our e2e test suite

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#42374]
We've had a few bugs recently that have highlighted some gaps in our testing. We can do better! 🔧 

- [ ] Define a list of core user flows we need to test
- [ ] Create new tests based on above list (expand this step!)
- [ ] Replace any hardcoded `wait`s with better logic (see https://docs.cypress.io/guides/references/best-practices#Unnecessary-Waiting)
- [x] Investigate any optimisations (e.g. api login: https://github.com/grafana/grafana/issues/40451)
- [x] (maybe) Investigate outputting failed cypress run videos to ephemeral external storage? (https://github.com/grafana/build-pipeline/issues/274)

### Existing dashboard
- [ ] After dashboard was modified Unsaved Changes Modal should be shown
  - [ ] Should close on Cancel
  - [ ] Should dismiss changes on Dismiss and navigate to target url (i.e. when trigered by clicking on logo should go to home dashboard)
  - [ ] Should show Save Changes modal on Save. 
     - [ ] Should close on Cancel
     - [ ] Should navigate to target url (i.e. when trigered by clicking on logo should go to home dashboard) on Save

**Comment by hugohaggmark** [comment]
> We've had a few bugs recently that have highlighted some gaps in our testing. We can do better! 🔧
> 
> * [ ]  Define a list of core user flows we need to test

I totally agree!

> * [ ]  Create new tests based on above list (expand this step!)

I totally agree
> * [ ]  Replace any hardcoded `wait`s with better logic (see https://docs.cypress.io/guides/references/best-practices#Unnecessary-Waiting)

I agree but with previous versions of Cypress their recommended way of aliased paths haven't always worked so that explains a lot of the hardcoded waits.
> * [ ]  Investigate any optimisations (e.g. api login: [e2e tests: use faster login-step #40451](https://github.com/grafana/grafana/issues/40451))

This would be great, but we should make sure we keep one "real login" test so we know that works. Another thing would be to experiment with keeping the browser running and not closing it between tests. This will also increase performance a lot but it will also increase the complexity of our e2e framework too.
> * [ ]  (maybe) Investigate outputting failed cypress run videos to ephemeral external storage?
There is an ongoing issue here that hasn't received any attention: https://github.com/grafana/build-pipeline/issues/274
