### ISSUE TITLE
Improve frontend codebase health

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#42385]
Over the life of Grafana the frontend codebase has accumulated various tech debt and smells that lead to bugs and generally make it harder than it needs to be to develop Grafana with confidence. This is an epic to track the various efforts we have to improve the overall quality of the frontend code.

Tasks includes:

 - [x] Investigate/implement betterer prevent additional smells from being added while we fix existing ones
    - [x] Requires fix for https://github.com/phenomnomnominal/betterer/issues/902
    - [x] https://github.com/grafana/grafana/pull/45055
 - [x] #44430
 - [x] #51194
 - [x] https://github.com/grafana/grafana/pull/50591 to prevent errors being caught unsafely.
 - [x] https://github.com/grafana/grafana/issues/42359 to make it easier to find genuine errors
