### ISSUE TITLE
Data Migration of apikeys to serviceaccounts

### ISSUE THREAD

**Issue by eleijonmarck** [grafana/grafana#43023]
why and what:
As an admin I'd like a button to enable the service-accounts feature toggle, so that I can manually choose to try out the new feature and migrate my API keys, and I can do that on Cloud or onprem. 

This will actually change the UI in the organization admin panel from API keys to Service Accounts.

MVP

- [ ] revert back from service account to api key ( via api and cli )
- [ ] investigate if we should support converting multiple
- [ ] deprecation message once feature toggle is enabled
- [ ] capture failed migration and "revert" / make everything in a transaction
- [ ] discussion: ability to go back to apikeys from upgrade if possible. (this is feedback from the alerting team)
- [ ] success screen when successful migration has been done

---

# Data migration

Currently in discussion for how we should proceed with the data migration from apikeys to service accounts

**Comment by eleijonmarck** [comment]
we are not doing a migration of the service accounts
