### ISSUE TITLE
InfluxDB migration to backend data source

### ISSUE THREAD

**Issue by joey-grafana** [grafana/grafana#43076]
Checklist:
- [x] Run query in Explore https://github.com/grafana/grafana/pull/43352
- [x] Field keys, Measurements, Retention policies, Tag keys, Tag values https://github.com/grafana/grafana/pull/44546
- [x] New variable types https://github.com/grafana/grafana/pull/44789
- [x] Variables https://github.com/grafana/grafana/pull/45512
- [x] Annotations https://github.com/grafana/grafana/pull/45635
- [x] Run query in dashboard https://github.com/grafana/grafana/pull/45636
- [x] Run query in edit mode https://github.com/grafana/grafana/pull/45636
- [x] Influx dashboards https://github.com/grafana/grafana/pull/45636
- [x] TestDataSource https://github.com/grafana/grafana/pull/45636

**Comment by gtk-grafana** [comment]
Closing as this looks completed.

**Comment by kylebrandt** [comment]
@gtk-grafana (@itsmylife)

So this isn't complete. There are two different things:
 - Deprecating Browser Access Mode for Server Access Mode (https://github.com/grafana/grafana/pull/53529)
 - Migrating Datasources to the backend

Migrating datasource to the backend makes it so the backend is what takes a query model, and turns into an API request, and in the dataquery case turns the response for the into dataframes. This makes things consistent with alerting and FE queries instead of doing it twice - enables server side query caching etc.

So currently the backend migration (what this issue is about) is under the feature flag `influxdbBackendMigration` so it has not been shipped. It is also perhaps not complete as far as what needs to be done under the feature flag -- not sure.

**Comment by itsmylife** [comment]
I am closing this issue since it is completed. This was `phase 1` of the migration. Phase 2 is here https://github.com/grafana/grafana/issues/60321
