### ISSUE TITLE
Extend configurability of OpenTelemetry

### ISSUE THREAD

**Issue by idafurjes** [grafana/grafana#43947]
After OpenTelemetry was added as a configurable option for tracing we can extend the features and add configuration for them

- [ ] Add remote sampling
- [ ] Add rate limiting sampling 
- [ ] Add tempo as an alternative to jaeger

**Comment by hairyhenderson** [comment]
Hey @idafurjes 👋 - we need remote sampling for grafana/hosted-grafana#2712 so I'm going to issue a PR to support that.
