### ISSUE TITLE
CW Logs Handover

### ISSUE THREAD

**Issue by iwysiu** [grafana/grafana#44072]
As part of the handover of this plugin, we should:

- [x] Remove the unused "live" code from [live.go](https://github.com/grafana/grafana/blob/main/pkg/tsdb/cloudwatch/live.go) https://github.com/grafana/grafana/issues/44071
- [x] Rework the query timeout to be one timeout instead of a separate start and polling timeout https://github.com/grafana/grafana/issues/44074
- [x] Use the new query header for logs https://github.com/grafana/grafana/issues/43290
- [x] Assorted small refactors https://github.com/grafana/grafana/issues/44073
