### ISSUE TITLE
Remove bus

### ISSUE THREAD

**Issue by zserge** [grafana/grafana#44130]
Replace any usages of the bus package in Grafana backend  with dependency injection and direct mehtod calls. This should increase the type safety of the backend and enable further refactoring.

bus.Dispatch can be found in the following packages, each to be handled individually:

- [x]    1 middleware
- [x]    1 plugins/manager
- [x]    1 plugins/plugincontext @yangkb09 
- [x]    1 services/alerting/conditions
- [x]    1 services/provisioning/utils @zserge https://github.com/grafana/grafana/pull/44989
- [x]    1 services/searchusers
- [x]    2 cmd/grafana-cli/commands @yangkb09 https://github.com/grafana/grafana/pull/45177
- [x]    2 components/dashdiffs @ying-jeanne https://github.com/grafana/grafana/pull/45175
- [x]    2 services/live/features
- [x]    2 services/login/authinfoservice @zserge https://github.com/grafana/grafana/pull/45787
- [x]    2 services/ngalert/notifier
- [x]    2 services/notifications
- [x]    2 services/oauthtoken
- [x]    2 services/provisioning/dashboards @zserge https://github.com/grafana/grafana/pull/44989
- [x]    2 services/search @ying-jeanne 
- [x]    2 services/sqlstore @idafurjes https://github.com/grafana/grafana/pull/45199
- [x]    2 services/thumbs https://github.com/grafana/grafana/pull/45210 also https://github.com/grafana/grafana/pull/46772
- [x]    3 services/contexthandler/authproxy @zserge https://github.com/grafana/grafana/pull/45425 
- [x]    3 services/guardian @ying-jeanne https://github.com/grafana/grafana/pull/45215 also @zserge https://github.com/grafana/grafana/pull/46711
- [x]    3 services/provisioning/plugins @zserge https://github.com/grafana/grafana/pull/44989
- [x]    3 services/quota @idafurjes https://github.com/grafana/grafana/pull/45143
- [x]    4 services/cleanup @zserge https://github.com/grafana/grafana/pull/45401
- [x]    4 services/provisioning/datasources @zserge https://github.com/grafana/grafana/pull/44989
- [x]    5 services/dashboards @ying-jeanne https://github.com/grafana/grafana/pull/45395
- [x]    5 services/plugindashboards @yangkb09 https://github.com/grafana/grafana/pull/45630
- [x]    6 login @zserge
- [x]    7 infra/usagestats/service @idafurjes https://github.com/grafana/grafana/pull/45275
- [x]    7 services/provisioning/notifiers @zserge https://github.com/grafana/grafana/pull/44989
- [x]    8 services/contexthandler @zserge https://github.com/grafana/grafana/pull/45425 
- [x]    9 services/login/loginservice @ying-jeanne https://github.com/grafana/grafana/pull/44907
- [x]   13 services/alerting @zserge https://github.com/grafana/grafana/pull/44496
- [x]   19 services/ngalert @zserge https://github.com/grafana/grafana/pull/44465
- [x]   20 services/alerting/notifiers @zserge https://github.com/grafana/grafana/pull/44496
- [x]   147 api (see detailed list of files below)

List of files containing bus.Dispatch inside the pkg/api:

- [x] api/admin.go @yangkb09 https://github.com/grafana/grafana/pull/44920
- [x] api/admin_users.go @yangkb09 https://github.com/grafana/grafana/pull/44869
- [x] api/alerting.go @zserge https://github.com/grafana/grafana/pull/44894
- [x] api/apikey.go @ying-jeanne https://github.com/grafana/grafana/pull/44955
- [x] api/dashboard.go @idafurjes https://github.com/grafana/grafana/pull/44923
- [x] api/dashboard_snapshot.go @ying-jeanne https://github.com/grafana/grafana/pull/44956
- [x] api/datasources.go @idafurjes https://github.com/grafana/grafana/pull/44987
- [x] api/frontendsettings.go @yangkb09 https://github.com/grafana/grafana/pull/44921
- [x] api/health.go @zserge https://github.com/grafana/grafana/pull/44897
- [x] api/index.go @yangkb09 https://github.com/grafana/grafana/pull/44851
- [x] api/ldap_debug.go @ying-jeanne https://github.com/grafana/grafana/pull/45014 
- [x] api/login.go @ying-jeanne https://github.com/grafana/grafana/pull/44995
- [x] api/login_oauth.go @ying-jeanne https://github.com/grafana/grafana/pull/44907
- [x] api/org_invite.go https://github.com/grafana/grafana/pull/44530
- [x] api/password.go @yangkb09 https://github.com/grafana/grafana/pull/44482
- [x] api/playlist.go https://github.com/grafana/grafana/pull/44485
- [x] api/playlist_play.go https://github.com/grafana/grafana/pull/44485
- [x] api/pluginproxy/pluginproxy.go @zserge https://github.com/grafana/grafana/pull/44899
- [x] api/plugins.go @idafurjes https://github.com/grafana/grafana/pull/44762
- [x] api/preferences.go @idafurjes https://github.com/grafana/grafana/pull/44762
- [x] api/quota.go @idafurjes https://github.com/grafana/grafana/pull/44762
- [x] api/search.go @ying-jeanne https://github.com/grafana/grafana/pull/44825
- [x] api/signup.go https://github.com/grafana/grafana/pull/44485
- [x] api/stars.go https://github.com/grafana/grafana/pull/44218
- [x] api/team.go https://github.com/grafana/grafana/pull/44218
- [x] api/user.go https://github.com/grafana/grafana/pull/44468
- [x] api/user_token.go @idafurjes https://github.com/grafana/grafana/pull/44762

Finally:

- [x] Create bus interface for events
- [x] Remove bus.Dispatch and related tests
- [x] Remove AddHandler calls
- [x] Decide if SQLStoreMock should use testify/mock or remain hand-written
- [x] Revisit usage of store method calls in the pkg/api (perhaps a service method was meant to be used instead?)

**Comment by sdboyer** [comment]
> Create bus interface for events

What's involved here?

**Comment by zserge** [comment]
Well, bus is used as two parts - an implicit method invoker (i.e. 1-1 calls from the caller to the callee) and as an implicit event bus (pub/sub). The latter is still used in a few parts of Grafana and I would rather hide the in-proc implementation behind an interface to make further changes in this area easier to refactor (if we ever end up with a proper message bus).

**Comment by sdboyer** [comment]
Perhaps it's the wording that's confusing me - it says "create bus interface for events," but it seems to me that if you remove `bus.Dispatch` and `bus.AddHandler`, then what's left really just is the pub/sub broker, plus the two other methods?

Or perhaps that's what you mean - you really just want the two pub/sub methods. So, adding a new interface would mean we'd end up with:

```go
type Bus interface {
	Publish(ctx context.Context, msg Msg) error
	InTransaction(ctx context.Context, fn func(ctx context.Context) error) error
	AddEventListener(handler HandlerFunc)
	SetTransactionManager(tm TransactionManager)
}

type EventBus interface {
	Publish(ctx context.Context, msg Msg) error
	AddEventListener(handler HandlerFunc)
}
```

If that's what you mean, all 👍 from me.

As to the pure event side - looking at the [currently defined set of events](https://github.com/grafana/grafana/blob/main/pkg/events/events.go), it appears that all of our current message flavors are intrinsically covered by the kinds of events that any bog-standard k8s apiserver would issue watch notifications for: state changes in persisted objects.

If that's true, i think that we can a) treat the event bus as deprecated and ask people not to introduce new usages of it, and b) expect that it be subsumed by standard manager/controller event notifications, once the requisite dependencies are met.

Another possible path is that we treat the event bus as another case to be satisfied by a [general HA communication strategy](https://docs.google.com/document/d/1hrZHxaIuKocMtsQM_HdbLxao1pBgCka-hYvzGJf1F7A/edit#). I'd like to avoid introducing more requirements there, if possible - and it should be possible, as long as it's a requirement that subscribers are idempotent. Not sure that that holds today, or that it's an enforceable requirement even if it happens to.

**Comment by vincejv** [comment]
Hi @zserge, armhf build is not running, have suspicion something to do with this PR https://github.com/grafana/grafana/pull/44496 

logs and details in this issue: https://github.com/grafana/grafana/issues/48130
