### ISSUE TITLE
Do an initial run with Levitate for all plugins published to grafana-com

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#44158]
This issue is done when we have successfully imported all Levitate output for plugins published in grafana.com. The output should be store in the BigQuery dataset that already is setup.

This is useful for us to understand what parts of the `@grafana/packages` are being used by external plugins. 

## Tasks

- [ ] Add support for Levitate to handle nested plugins.
- [ ] Remove the dataset already imported to BigQuery.
- [ ] Run the import against all (latest versions of) plugins in grafana-com (can be done locally).
