### ISSUE TITLE
Geomap Panel Improvements/Features

### ISSUE THREAD

**Issue by atifali** [grafana/grafana#44240]
Pulling this out from the original alpha release epic for the new Geomap panel: https://github.com/grafana/grafana/issues/36585

The following improvements and features are outstanding from the original proposal and some are new requested/desirable features for a growing list of use-cases:

Bugs:
- [x] #43937
- [x] #44688
- [x] #44740
- [x] Map controls don't respond in the edit mode unlike the toggle options in the data layers settings
- [x] Going into panel fullscreen "View" mode does not work properly, the geomap view does not change size 
- [x] #47398

New Features:
- [x] #44020
- [ ] Define spatial types in dataframes and support them further up the stack
- [ ] [Geojson layer] Ability for user to upload custom geojson files
- [x] #47399
- [x] #40496

Nice to haves:  
- [ ] timeseries slider, for [tracks](https://grafana.com/grafana/plugins/pr0ps-trackmap-panel/) and [fill](https://grafana.com/grafana/plugins/citilogics-geoloop-panel/) 
- [ ] Add option for a single point time-series geolocation data marker based on a linked time-series panel
- [x] #43554
- [x] Improve react legend system which is currently non-existent
- [x] Thresholds do not play nicely with the color styles for marker layer
- [ ] Host a better default basemap (currently using cartodb)
- [ ] Toggle option for showing a specific value from the result on the spatial markers rather then on hover

Clean up / refactors:
- [ ] #54302
- [x] #54315
- [ ] #53329
- [ ] #53273
- [x] #54325

**Comment by yoyo421** [comment]
support for wkt from fields will be really useful (points / linestring / polygon)

**Comment by wetterfrosch** [comment]
Coloring of GeoJSON-elements based on data-series' values would be great!

Although I love the heat-map function, too, this would definitely enable a better view on values valid for areas/ploygons.

Great work led to this nice geomap-panel and will lead to many sleepless nights! ... Oh, for @heidimhurst probably too :)

**Comment by tillsteinbach** [comment]
Quick question: The dynamic zoom to fit the data is implemented already in 5.0.0, right? In general this works great for me, but the fit is not updated when the data is changing. It only fits once when the panel is loaded. Is that something for a feature request or a bug report?

**Comment by ziggi** [comment]
It would be nice to be able to change the projection. For example, I need a 2D projection for a simple game map, but I can't use the Geomap Panel.

**Comment by genofire** [comment]
@yoyo421 oh yes, wish i could label prometheus metrics with a line (instatt of a marker for the destionation)

**Comment by andness** [comment]
I'm testing the Geomap in the current main branch and I'm very happy to see the support for multiple layers using separate queries. But I miss the ability to toggle on and off the layers by clicking in the legend (same way as you can toggle on and off series in graphs). Is that perhaps what is covered by the _"Improve react legend system which is currently non-existent"_? 

We're use and love Grafana (a lot!), so I think we would be willing to invest some time into improving this.

**Comment by alexl04** [comment]
> "timeseries slider, for tracks" would be amazing to have since the old trackmap plugin is not working anymore.

I fully agree! I [read here](https://github.com/grafana/grafana/pull/43554) that there have been written solutions but I can't figure out if they will be included in GeoMap someday or not.

Having Tracks/Routes on a GeoMap based on Lat/Lon data from a time-series query is more than welcome in our dashboards where we show the latest received position of our vessels together with Offshore Windfarm objects (Turbines, Substations, Cable Routes, Scour Protections you name it) on top of OpenStreetMaps.

Data Layers with custom objects and formatting options like the direction, color etc of a marker make it possible to monitor our fleet in real-time (like Marine-Traffic) already but we miss the option of showing the history of positions in a track/route. Switching to Marine-Traffic for only that is not what we like either because we of course also dashboard lots of sensor data from equipment onboard our vessels next to the latest position etc in GeoMap. Really awesome and truly useful in the Offshore market, thanks Grafana.

![image](https://user-images.githubusercontent.com/56631466/191226816-349af9a6-9ee2-4354-89b3-819de7041dcd.png)

**Comment by alex-tate** [comment]
The timeslider functionality was addressed in #51495 but is seemingly undocumented and hasn't resulted in a tick in the tasklist at the top of this issue. I've tried it now using a Postgres data source (same as @alexl04, I'm working with vessel tracks) and while it works to a degree, it is very slow to update the position when moving along the timeseries panel.

**Comment by MatinF** [comment]
Would be great to have this functionality added to Grafana Cloud

**Comment by alex-tate** [comment]
I take back my comment about the timeslider being slow. After exiting my testing dashboard and then coming back to it, things worked smoothly in a very similar way to the TrackMap plugin. There are a few minor oddities but I'll test further to check that they aren't caused by my underlying data before reporting.

**Comment by alexl04** [comment]
> I take back my comment about the timeslider being slow. After exiting my testing dashboard and then coming back to it, things worked smoothly in a very similar way to the TrackMap plugin. There are a few minor oddities but I'll test further to check that they aren't caused by my underlying data before reporting.

Tested the Route (Alpha) functionality in Geomap (included in Grafana 9.1.6) in combination with time-series data stored in PostgreSQL 13 (just index on timestamp and mmsi for speed) and can report that the shared crosshair function works perfectly smooth. Just make sure that you turn on "shared crosshair" in the dashboard settings and format your query in the GeoMap panel as "time-series". Your time-series data should be ordered ASC as well. Else it won't work.

For other noobs like me, Alpha features from core panels like GeoMap will become visible in Grafana if you set those to True in your custom.ini file (or the general if you don't have a custom.ini) with all your settings. It is also possible to create your dashboard in a grafana environment where you have set it to True and then copy it to another environment where its not set to true. Routes will pop up. Just sharing.

![image](https://user-images.githubusercontent.com/56631466/192975588-9e979b44-ecd9-4333-b11d-e48c9248dd7f.png)

**However, there are some bugs to report as well:**

- Selecting the Route (alpha) as data layers does not always work and it seems not possible to include multiple data layers with the same Data Type. In this case Routes. After selecting Layer Type Routes it switches back to Markers. I work with the Chrome Browser.
- Data Layer does not show in Legend

**I also have some feature requests although I'm not sure if this is the right place to report those, nevertheless, these will be helpful:**

1. For Routes, custom icons (including its rotation) and colors based on some data field would be useful. Just like with Markers. With AIS data from vessels, we could then visualize its historical course over ground, speed, and position with just visuals! awesome.
2. For Map View > View > Fit data layers. This is very useful but it would be even better if the end-user can select which data layer. For example with help of the Legend. Turn on, zoom in on that data.

Cheers to you all

**Comment by drew08t** [comment]
We created a [new epic to track Geomap improvements](https://github.com/grafana/grafana/issues/58543) going forward.
