### ISSUE TITLE
Epic: Prometheus & Loki Visual Query builders

### ISSUE THREAD

**Issue by meanmina** [grafana/grafana#44253]
‼️ Outstanding issues moved to https://docs.google.com/spreadsheets/d/1XPznl5zSR8VaJkf20doRGUM15MK57wauN10j71yxKxQ/edit#gid=0

## Shared 
* [ ] Support for disable operation action & state
* [ ] Drag and drop is not working when you have many operations and they wrap  This is not an easy fix, no drag and drop lib I have found supports this for elements of dynamic width. 
* [ ] Run query should only run a single query. This needs interface changes to QueryEditorProps and some substantial changes to query execution in Grafana
* [ ] If a query editor could specify the query to run we could have an action on each operation that said "Run query up this operation". So you can run part of a query or inner expression. This is very common in loki queries where you want to only run the inner logs query to see what it returns, and then from that modify or then run the outer query (that has range functions etc). 
* [ ] Improved query pattern UX so that query patterns can have a description. 
* [ ] For binary operations run partial queries to figure out labels/joins options
* [ ] Better errors using parser
* [x] Support for dynamic width inputs (inputs that expand or decrease width based on value, as user types). @ivanahuckova https://github.com/grafana/grafana/pull/45601
* [x] Support for template variables in label filters @ivanahuckova 
* [x] Show doc for metrics (aka metrics HELP) @aocenas https://github.com/grafana/grafana/pull/46406

## Prometheus 
* [x] Visual editor implementation https://github.com/grafana/grafana/issues/47316
* [x] Refine operation explain docs (trigonometric functions and new prometheus functions added (PR https://github.com/grafana/grafana/pull/45745)
* [x] Query builder documentation 
* [x] For explore it should remember preferred editor
* [ ] e2e test 

## Loki 
* [x] Line filters
   * [x] Dynamic width input that expand or conctract based on current value (would save some horizontal space)
* [x] Label filter expressions 
* [x] Json 
* [x] Plain aggregations 
* [x] Support for aggregations with by label
* [x] Support for aggregations without label 
* [x] Unwrap
* [x] Line format expression operation
* [x] Label format expression operation 
* [x] Range operations 
  * [x] Rate
  * [x] Count over time
  * [x] Sum over time 
  * [x] Bytes rate
  * [x] Bytes over time
  * [x] Absent over time
* [x] Support for legend formats. We should explore how we might not need this or have it automatic with opt-in
* [x] Support for step (and maybe resolution??). We should try to explore not needing this.
* [x] Support for binary operations on nested query 
* [x] Make it clear/mandatory to have at least 1 stream selector
* [x] Query builder documentation https://github.com/grafana/grafana/pull/48523

**For the non-MVP issues below, I have created separate issues (so they are removed from this epic):**
* [ ] ~Some basic hints~  #48533
  * [ ] ~Detect logfmt or json formats~ #48533
* [ ] ~e2e test~ #48531 
* [ ] ~Implement ip_label_filter in visual query editor~ #48532 
* [ ] ~For explore it should remember preferred editor~ #48534 
* [ ] ~Unwrap with property suggestions based on results~ https://github.com/grafana/grafana/issues/48535
* [ ] ~Unwrap with conversion operator (e.g. duration)~ https://github.com/grafana/grafana/issues/48535
* [ ] ~JSON format options~ #48532

**Comment by hugohaggmark** [comment]
@meanmina  this is a friendly reminder to add appropiate labels to make the issue triage smoother for people on issue triage. Thank you.
