### ISSUE TITLE
Plugins: Refactoring tasks

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#44260]
- [x] https://github.com/grafana/grafana/issues/44257
- [x] https://github.com/grafana/grafana/pull/44583
- [x] https://github.com/grafana/grafana-plugin-sdk-go/pull/463
- [x] https://github.com/grafana/grafana/issues/44553
- [x] https://github.com/grafana/grafana/issues/44655

**Comment by tolzhabayev** [comment]
@marefr all the subtasks seem done?

**Comment by marefr** [comment]
There's still potential things left I think, but closing it for now.
