### ISSUE TITLE
Query history migration: Shared history

### ISSUE THREAD

**Issue by meanmina** [grafana/grafana#44327]
Migration to BE
Design doc: https://docs.google.com/document/d/1BdVtoXCxhH0Q6C-O_Z7jKi-u1m5pDoS9_HQKhYu_hEE

Long story short:
* When query history panel is opened all local storage items are migrated to backend storage (local storage is not cleared)
* Behavior remains unchanged:
  * query is added after running it in Explore
  * queries can be starred, commented, deleted
  * queries can be run directly from the  query history panel
  * queries can be filtered by date, datas ource, and text
* Retention period is fixed at 14 weeks
* Settings: only home tab can be modified

Backend:
- [x] Add to query history #44479
- [x] Delete from query history https://github.com/grafana/grafana/pull/44653
- [x] Update comment https://github.com/grafana/grafana/pull/44981
- [x] Star query https://github.com/grafana/grafana/pull/45077
- [x] Remove star https://github.com/grafana/grafana/pull/45077
- [x] Search with pagination https://github.com/grafana/grafana/pull/45932
- [x] Search in comments https://github.com/grafana/grafana/pull/46761
- [x] Decide on retention (7d/14d) 14d
- [x] Query history user's preferences https://github.com/grafana/grafana/pull/47506
  - [x] Add a test for https://github.com/grafana/grafana/pull/47506 
- [x] Add migration endpoint for queries in local storage https://github.com/grafana/grafana/pull/47551
- [x] Pass config enabled/disabled query history to frontend https://github.com/grafana/grafana/pull/48204
- [x] Add from and to filtering + fix data source filtering https://github.com/grafana/grafana/pull/48212
- [x] Create cleanup with 14d retention https://github.com/grafana/grafana/pull/48303
- [] ~Add swagger definitions~ https://github.com/grafana/grafana/issues/50305
- [ ] ~Test and improve indices.~ [Use COUNT to get total number of queries] (https://github.com/grafana/grafana/pull/49217#discussion_r878769826) https://github.com/grafana/grafana/issues/50306
- [x] Change config to true

Frontend:

The current implementation is heavily coupled with local storage. We need to extract persistence logic to a separate layer that can be easily switched with a feature flag (between local storage and remote storage). The persistence layer and all actions should take into account that persistence may be asynchronous. 

- [x] #44969
- [x] #44967 (**)
- [x] #45179
- [x] #44991
- [x] #44988
- [x] #48409
- [x] #47252
- [x] #48407
- [x] #48406
- [x] #45379
- [x] #48408
- [x] #48411
- [x] #49089
- [x] #49559
- [x] #45180
- [x] #49090
- [x] #49668

(*) Remote storage will not return all items so filtering and searching has be changed. Current implementation filters items in UI assuming all items are returned. This logic has to be moved to persistence layer.

(**) Current model is based on data source name. Remote storage will use data source uid. This should be changed so view models always use data source uid
