### ISSUE TITLE
AzureMonitor: Resource Picker for Metrics

### ISSUE THREAD

**Issue by vickyyyyyyy** [grafana/grafana#44439]
Improvements to the Resource Picker that we should do before adding it to Metrics
- [x] https://github.com/grafana/grafana/issues/46057
- [x] https://github.com/grafana/grafana/issues/46062
- [x] nice to have: https://github.com/grafana/grafana/issues/46063

Adding the picker to Metrics
- [x] https://github.com/grafana/grafana/issues/46059
- [x] https://github.com/grafana/grafana/issues/46058
- [x] https://github.com/grafana/grafana/issues/46060
- [x] https://github.com/grafana/grafana/issues/46061
- [x] https://github.com/grafana/grafana/issues/46065
- [x] #47784
- [ ] remove feature flag and release

Design Doc: https://docs.google.com/document/d/1TsMoi0L6daKn26bKXSL6x1HnuxnFXOeh1tbrMTv8Ve0/edit# (private to grafana folks for now)

**Comment by vickyyyyyyy** [comment]
Partial work has been done in this draft PR: https://github.com/grafana/grafana/pull/40887

**Comment by sarahzinger** [comment]
I changed the description to be more relevant, but here is the old description just in case: 

### Discussed in https://github.com/grafana/grafana/discussions/43289

<div type='discussions-op-text'>

<sup>Originally posted by **joshhunt** May  4, 2021</sup>
 - Add the Resource Picker to Metrics
 - Migrate existing subscription / resource group / namespace / resource name fields to new resourceUri field</div>
