### ISSUE TITLE
Dashboard previews - MVP

### ISSUE THREAD

**Issue by ArturWierzbicki** [grafana/grafana#44449]
https://docs.google.com/document/d/1qLUVFJaYShFfgiI_AsamQX-unOBOz0Mqq4ylgxwzjBo/edit#

- [x] support full-page screenshots and thumbnail mode in node-renderer
   - PR https://github.com/grafana/grafana-image-renderer/pull/312
- [x] improve performance of the crawler process 
   - PR node https://github.com/grafana/grafana-image-renderer/pull/314
   - PR grafana https://github.com/grafana/grafana/pull/44098
   - PR docs https://github.com/grafana/grafana/pull/45490
- [x] implement SQL based queue for the crawler 
   - PR https://github.com/grafana/grafana/pull/44083
- [x] run crawler as a background service https://github.com/grafana/grafana/blob/main/pkg/server/backgroundsvcs/background_services.go
   - PR https://github.com/grafana/grafana/pull/44891 
- [x] support checking version of image-renderer
   - PR rendering service https://github.com/grafana/grafana/pull/44470
   - PR rendering service v2 https://github.com/grafana/grafana/pull/45505
   - PR https://github.com/grafana/grafana/pull/44601
   - UX figma link:
- [x] prevent crawler from running when image-renderer is outdated
   - PR https://github.com/grafana/grafana/pull/45623  
- [x] hide the existing admin UI &  fix authorization for admin API calls
   - PR https://github.com/grafana/grafana/pull/45493
- [x] track feature usage via reporting interactions with `show previews` toggle
   - PR https://github.com/grafana/grafana/pull/44589 
   - PR#2 https://github.com/grafana/grafana/pull/44739
 - [x] test dashboards previews on dev HG
    - [x] IR version update  https://github.com/grafana/deployment_tools/pull/26138
 - [x] roll out dashboard previews on `ops.grafana.net` (staging)
    - [x] IR version update https://github.com/grafana/deployment_tools/pull/26413 
- [x] Track OSS adoption https://github.com/grafana/grafana/issues/47127   
- [x] Add documentation

After beta release: 
- [x] Resolve Enterprise FGAC permission issue https://github.com/grafana/grafana/issues/46968
- [ ] Resolve datasource permission issue https://github.com/grafana/grafana/issues/47448
- [ ] Refactors
   - [ ] generify grafana boot data https://github.com/grafana/grafana/pull/44601#discussion_r808277000
   - [x] externalize configuration https://github.com/grafana/grafana/pull/45628
 - [ ] resolve styling UX feedback
 - [ ] roll out IR `3.4.1` to prod HG clusters
 

@radiorental @ryantxu

**Comment by ArturWierzbicki** [comment]
mvp going out in 9.0, closing in favor of https://github.com/grafana/grafana/issues/50748
