### ISSUE TITLE
Chore: Clean up logs and warnings from Observability Experience unit tests

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#45028]
The following tests are outputting errant logs and warnings to the console during unit tests. Some of these are pointing out genuine errors and things that should be looked at, while others might be a bit more benign but should be cleaned up to make testing more pleasant.

In the future we may consider making console logs to be a failure condition in tests, so it would be good to sort these out sooner 😇

 - [ ] 3 logs from `public/app/core/utils/explore.test.ts`
 - [ ] 1 log  from `public/app/features/explore/Explore.test.tsx`
 - [ ] 1 log  from `public/app/features/explore/ExploreQueryInspector.test.tsx`
 - [ ] 2 logs from `public/app/features/explore/TraceView/TraceView.test.tsx` (When this is fixed revert jest.mock('@jaegertracing/jaeger-ui-components' in InspectDataTab.test.tsx and DashboardPage.test.tsx)
 - [ ] 1 log  from `public/app/features/explore/TraceView/useDetailState.test.ts` (When this is fixed revert jest.mock('@jaegertracing/jaeger-ui-components' in InspectDataTab.test.tsx and DashboardPage.test.tsx)
 - [ ] 1 log  from `public/app/features/explore/TraceView/useSearch.test.ts` (When this is fixed revert jest.mock('@jaegertracing/jaeger-ui-components' in InspectDataTab.test.tsx and DashboardPage.test.tsx)
 - [ ] 1 log  from `public/app/features/explore/Wrapper.test.tsx`

See [this comment](https://github.com/grafana/grafana/issues/42359#issuecomment-1032179575) for common warnings and how to fix them.

If you have any questions be sure to reach out to the User Essentials team ✌🏻 

Part of https://github.com/grafana/grafana/issues/42359

**Comment by gelicia** [comment]
@joshhunt I checked this out and only see warnings from `public/app/core/utils/explore.test.ts` - is there a verbose mode or some other way of running tests where you'd get logs on the other ones?
