### ISSUE TITLE
Chore: Clean up logs and warnings from Alerting unit tests

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#45023]
The following tests are outputting errant logs and warnings to the console during unit tests. Some of these are pointing out genuine errors and things that should be looked at, while others might be a bit more benign but should be cleaned up to make testing more pleasant.

In the future we may consider making console logs to be a failure condition in tests, so it would be good to sort these out sooner 😇

 - [x] 4 logs from `public/app/features/alerting/unified/PanelAlertTabContent.test.tsx`
 - [x] 1 log  from `public/app/features/alerting/unified/RedirectToRuleViewer.test.tsx`
 - [x] 2 logs from `public/app/features/alerting/unified/RuleViewer.test.tsx`

See [this comment](https://github.com/grafana/grafana/issues/42359#issuecomment-1032179575) for common warnings and how to fix them.

If you have any questions be sure to reach out to the User Essentials team ✌🏻 

Part of https://github.com/grafana/grafana/issues/42359

**Comment by nathanrodman** [comment]
One of the console logs I'm seeing is due to Angular somehow being loaded twice and I'm not sure how to resolve it

```
    console.log
      WARNING: Tried to load AngularJS more than once.

      at .yarn/cache/angular-npm-1.8.2-307000482b-35ea81a23b.zip/node_modules/angular/angular.js:36440:13
```
