### ISSUE TITLE
Chore: Clean up logs and warnings from User Essentials unit tests

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#45031]
The following tests are outputting errant logs and warnings to the console during unit tests. Some of these are pointing out genuine errors and things that should be looked at, while others might be a bit more benign but should be cleaned up to make testing more pleasant.

In the future we may consider making console logs to be a failure condition in tests, so it would be good to sort these out sooner 😇

 - [x] 1 log  from `packages/grafana-data/src/dataframe/FieldCache.test.ts` #45141
 - [x] 1 log  from `packages/grafana-ui/src/components/Cascader/Cascader.test.tsx` #45142
 - [x] 6 logs from `packages/grafana-ui/src/components/ErrorBoundary/ErrorBoundary.test.tsx` #45138
 - [x] 1 log  from `packages/grafana-ui/src/components/Logs/LogDetails.test.tsx`#45193
 - ~~[ ] #45194~~ removed so we can close this issue
 - [x] 2 logs from `public/app/angular/AngularLocationWrapper.test.ts` #45319
 - [x] 1 log  from `public/app/angular/services/annotations_srv.test.ts` #45135
 - [x] 5 logs from `public/app/core/components/NavBar/NavBarItem.test.tsx` #45139
 - [x] 1 log  from `public/app/core/logs_model.test.ts`
 - [x] 3 logs from `public/app/core/services/echo/backends/sentry/transports/CustomEndpointTransport.test.ts` #45311
 - [x] 1 log  from `public/app/core/utils/fetch.test.ts`#45134
 - [x] 1 log  from `public/app/core/utils/kbn.test.ts` #45313
 - [x] 1 log  from `public/app/features/dashboard/components/DashboardSettings/GeneralSettings.test.tsx`
 - [x] 3 logs from `public/app/features/dashboard/containers/DashboardPage.test.tsx` #https://github.com/grafana/grafana/pull/45373
 - [x] 1 log  from `public/app/features/inspector/InspectDataTab.test.tsx` #https://github.com/grafana/grafana/pull/45374
 - [x] 1 log  from `public/app/features/profile/UserProfileEditPage.test.tsx`
 - [x] 2 logs from `public/app/features/query/state/runRequest.test.ts` #https://github.com/grafana/grafana/pull/45375
 - [x] 1 log  from `public/app/features/variables/query/actions.test.ts`

See [this comment](https://github.com/grafana/grafana/issues/42359#issuecomment-1032179575) for common warnings and how to fix them.

If you have any questions be sure to reach out to the User Essentials team ✌🏻 

Part of https://github.com/grafana/grafana/issues/42359
