### ISSUE TITLE
Epic: New and improved heatmap panel

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#45495]
This issue will track major features required to release the new heatmap panel.  The initial working version is added in https://github.com/grafana/grafana/pull/44080

### Parity with current heatmap

- [x] Show gradient in legend
- [x] Show gradient in panel options editor
- [x] Support zooming
- [x] Shared tooltip
  https://github.com/grafana/grafana/pull/50271
- [x] Color palette clamping to specific min/max count range & filtering of values outside specified range
  https://github.com/grafana/grafana/pull/50204
- [x] Support log buckets
  https://github.com/grafana/grafana/pull/49969
- [ ] Tooltip cleanup
  - [ ] Fix tooltip bug at top of y range showing wrapped-around (lowest) bucket bound
  - [ ] Fix histogram tooltip rects overlapping
- [x] When Y axis is not ordinal (calculate) we need to support min/max range from config
- [ ] Audit migrations from current heatmap implementation

### Bugs
- [x] Legend indicator on hover is misplaced on initial render (maybe only in `Calculate: No` mode)
  ![image](https://user-images.githubusercontent.com/43234/172017417-c40fcff5-254e-4dcf-8c01-e73b104c6174.png)

### Fundamentals

- [ ] Devenv test dashboard
- [ ] e2e test for devenv dashboard
- [ ] Unit tests for appropritate parts 

### Previous issues resolved by new panel

- [x] https://github.com/grafana/grafana/issues/40919 (must verify)
- [x] https://github.com/grafana/grafana/issues/9584 
- [x] https://github.com/grafana/grafana/issues/10993
- [x] https://github.com/grafana/grafana/issues/19393
- [x] https://github.com/grafana/grafana/issues/24365
- [x] https://github.com/grafana/grafana/issues/20914

### New features

- [ ] Auto-expand time range to fit cells at edges
- [x] https://github.com/grafana/grafana/issues/32917
- [x] https://github.com/grafana/grafana/issues/13895
- [x] https://github.com/grafana/grafana/issues/71159
- [ ] Render counts as text inside tiles?

Once we are confident the new heatmap has parity with the old (flot based) one, we will automatically swap it in

### Related, but not required for the panel

- [ ] Document the `heatmap-rows` DataFrame type
- [ ] Document the `heatmap-cells` DataFrame type

**Comment by torkelo** [comment]
Missing a devenv dashboard :)

**Comment by torkelo** [comment]
Time axis seems to use `am` and `pm` formatting, so not the same time formatting as time series panel

**Comment by grafanabot** [comment]
This issue was removed from the 8.5.0 milestone because 8.5.0 is currently being released.

**Comment by grafanabot** [comment]
This issue was removed from the 9.0.0-beta2 milestone because 9.0.0-beta2 is currently being released.

**Comment by grafanabot** [comment]
This issue was removed from the 9.1.0 milestone because 9.1.0 is currently being released.

**Comment by reyjrar** [comment]
Data links are presented on Heatmaps as an option, but there's no way I can see to interact with them. They do not appear when I click on a cell.. I only see the cell details.

Would be cool if the data links worked and if the ad-hoc query filter buttons also showed up.

**Comment by stephan-hof** [comment]
> Data links are presented on Heatmaps as an option, but there's no way I can see to interact with them. They do not appear when I click on a cell.. I only see the cell details.

Having the exact same problem. Also tried it out on play.grafana.org.
On the right hand side `Data Links` are configured, but clicking on cell of the Heatmap does not show them.
![no_data_links_for_heatmap](https://user-images.githubusercontent.com/620934/203778071-ea0ac4ad-6710-4db8-be09-cedfaca49a97.jpg)

**Comment by ndevenish** [comment]
Is this likely to be re-added to any milestone? It'd be nice to have a heatmap where data links were possible.

**Comment by juandetoro** [comment]
It'd be nice to have a heatmap where data links were possible…
