### ISSUE TITLE
Search v2

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#45498]
Backend:
- [x] reuse `[]dashMeta` for multiple requests.  Currently we parse all dashboards on each query :grimacing: 
   - https://github.com/grafana/grafana/pull/47709
- [x] support `starred` dashboards (?)
- [ ] JOIN usage analytics when enterprise
- [ ] Move the [AuthService stub](https://github.com/grafana/grafana/blob/main/pkg/services/searchV2/auth.go#L15) into a service supported by the auth squad :)
- [x] Include URL in dashboard result

Frontend search page:
- [x] https://github.com/grafana/grafana/pull/45487
- [x] #46750
- [x] #47073
- [x] Match current layout
- [x] Add a score to each result (and then sort)
- [x] https://github.com/grafana/grafana/issues/47068
- [x] #47218
- [ ] #47415

Frontend general support:
- [ ] Support linking to dashboard panels by URL (ie add panelId as url parameter then scrollTo)  See [netdata example](https://london3.my-netdata.io/#menu_web_log_nginx_submenu_urls;after=0;before=0;theme=slate;utc=America/Los_Angeles)

**Comment by ryantxu** [comment]
new tasks tracked elsewhere...
