### ISSUE TITLE
EPIC: E2E: Improve the support for writing tests for plugins

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#45594]
**What happened**:
During the work of writing e2e tests for some of our examples (https://github.com/grafana/grafana-plugin-examples) we discovered that there are a lot of things that can be improved when offering better support to plugin developers.

The key things that I think needs to be improved:

- There are no up to date documentation of the conventions and ideas of how to use the e2e framework. Maybe better to remove our wrapper and instead just offer small utility  functions to get help generating proper selectors for the different parts of Grafana. In that case we can point developers to the Cypress documentation instead of providing our own.

-  We should probably provide the most common flows to let the plugin developer focus on only writing tests for the parts of the UI that they have developed.

- Within each context (query editor, configuration editor etc.), it would be nice to be able to run cypress command in that context only. This will make it easier to write stable and reliable tests.

**What to do**:

- [ ] Show case how we can setup plugins to run e2e tests without using grafana-toolkit and the e2e package.
- [ ] Introduce a grafana/cypress package that contains utility functions to write e2e tests in plugins.
- [ ] Make sure that we can pass test-id to the panel edit options UI.
- [ ] Make sure that is is possible to pass test-id to the most used components in grafana/ui.
- [ ] Use the "new" pattern for our tests in our plugin examples.
- [ ] Write documentation about how to write e2e tests for plugins.

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/76753
- [ ] https://github.com/grafana/grafana/issues/76754
- [ ] https://github.com/grafana/grafana/issues/76755
```

**Comment by mckn** [comment]
<img width="1050" alt="Skärmavbild 2022-02-25 kl  14 48 07" src="https://user-images.githubusercontent.com/172951/155726137-92332593-7f1e-43f6-8789-2fb7b251abf0.png">
<img width="1030" alt="Skärmavbild 2022-02-25 kl  14 47 57" src="https://user-images.githubusercontent.com/172951/155726142-12d60f27-ae2f-4a30-89a7-6f69d73d2bdb.png">
<img width="1041" alt="Skärmavbild 2022-02-25 kl  14 47 48" src="https://user-images.githubusercontent.com/172951/155726143-e29c36aa-192c-470d-ab7f-24a8bb701242.png">

**Comment by mckn** [comment]
> Idea:
> 
> We are using test ids while testing React Components with Jest and @testing-library/react Currently we have our own implementation of jest selectors helper which works in the same way as @grafana/e2e-selectors works and to be consistent between e2e and unit tests. Example of usage:
> 
> ```
> import { screen } from '@testing-library/react'
> 
> const TestIds = {
>   panel: {
>     container: 'data-testid panel',
>     button: (name: string) => 'panel button ${name}',
>   }
> }
> 
> const getPanelSelectors = getJestSelectors(TestIds.panel);
> 
> test('Panel', () => {
>   const selectors = getPanelSelectors(screen)
> 
>   selectors.container() // screen.getByTestId
>   selectors.container(true) // screen.queryByTestId
>   selectors.button(false, 'submit') // screen.getByLabelText
>   selectors.button(true, 'submit') // screen.queryByLabelText
> })
> ```
> 
> It will be useful to have another package for jest selectors which will help keeping React components are consistent between units and e2e tests.

This is great feedback! Thanks 🙏🏻

**Comment by mckn** [comment]
I did play around a bit with creating a stand alone `@grafana/cypress` package that provided a number of support functions to make it easier for plugin developers to write E2E tests. This is my findings and some ideas that I think is worth continue to evaluate as we move this support forward.

**Some assumptions that I have made:**

- Plugin developers don't want to write tests that cover core Grafana behaviour they only want to write test for the behaviour their plugin adds to Grafana.
- Plugin developers want to write one test suite that should be able to test their plugin, reliably, across multiple versions of Grafana.
- Plugin developers would like to manage their cypress setup as they feel fit their needs the best.

**Scenarios we need to provide to the developers:**

- Navigate to a query editor for a specified query.
- Navigate to a panel on a dashboard.
- Navigate to and edit, via the panel editor, a panel on a dashboard.
- Navigate to a config editor of a data source.
- Navigate to a variable editor of a data source.
- Navigate to a config editor of an app.
- Trigger an UI extension in the panel menu.
- Trigger an UI extension in explore.

> I have probably missed a scenario here but there should not be super many.

Each scenario needs to be able to run as a signed in/out user. The developer needs to be able to provide stable test ids, aria labels or labels/roles to UI components used in the query editor, panel, config editor etc. added by the plugin.

**For me the following setup makes sense:**

The plugin developer creates a number of provisioning files that creates the test context which bootstrap Grafana and the plugin so it is ready to be verified with E2E tests. He/she adds a dependency on a npm package with support files provided by Grafana. The developer wires those support files to the local cypress setup according to this [guide](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Support-file).

The plugin developer uses custom commands to navigate to where the plugin extends Grafana e.g. to a query editor of a specified query (if the plugin is a data source).

The plugin developer uses selectors specified, in the query editor, by the plugin developer to interact with the different parts of the query editor. It can use regular cypress selectors to interact and verify their plugin.

```js
# example of how it could look
describe('query editor', () => {
  beforeEach(() => {
    cy.grafana({ 
      url, 
      credentials: { user: 'admin', password: 'admin' } 
    }).getQueryEditor({ query: 'A' }).as('queryEditor');
  });

  it('should have an input with value time', () => {
    cy.get('@queryEditor').get('input[value=time]').scrollIntoView().should('be.visible');
  })

  it('should have an input with value temperature', () => {
    cy.get('@queryEditor').get('input[value=temperature]').scrollIntoView().should('be.visible');
  })
})
```
**The npm package that provides flows/support to navigate to the different contexts specified above should do the following:**

- Should detect what version of Grafana we are currently running tests against and internally use the proper selectors to navigate to the specified context. It should have builtin support for multiple versions of Grafana so the plugin developers never need to change version of the support package to run tests agains an older version of Grafana. Plugin developers should only need to update the support package when they want to support never versions o Grafana.
- Should not have any dependency on the grafana packages. It should be as stand alone as possible to make it easy for plugin developers to use what ever version of cypress they seem fit their needs the best.
- Should probably add one root command (grafana) which would provide sub-commands to trigger flows/scenarios that we support.
- Should follow Cypress conventions for specifying configurations, hosts etc.

**Comment by tolzhabayev** [comment]
Thanks for the summary 👍 

> The developer wires those support files to the local cypress setup
Do you mean something like this?

`cypress.json`:

```
"supportFile":"node_modules/@grafana/cypress-plugin-support-files/support.ts"
```

> Should detect what version of Grafana we are currently running tests against and internally use the proper selectors to navigate to the specified context. It should have builtin support for multiple versions of Grafana so the plugin developers never need to change version of the support package to run tests agains an older version of Grafana. Plugin developers should only need to update the support package when they want to support never versions o Grafana.

How could this look like? Without the details but high level?

> The npm package that provides flows/support to navigate to the different contexts
The package versioned by grafana versions? by cypress versions?

Do you know if `custom commands` that provide the flows via `supportFile` are stable between cypress version changes?

**Comment by mckn** [comment]
> Thanks for the summary 👍
> 
> > The developer wires those support files to the local cypress setup
> 
> Do you mean something like this?
> 
> `cypress.json`:
> 
> ```
> "supportFile":"node_modules/@grafana/cypress-plugin-support-files/support.ts"
> ```

Not really, or I guess you could do it like that. It is up to the plugin developer to decide how to set it up but the cypress convention is to create an `e2e.ts` file in the support folder and then import the libraries that you would like to use.

https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/fundamentals__add-custom-command-ts/cypress/support/e2e.ts




> > Should detect what version of Grafana we are currently running tests against and internally use the proper selectors to navigate to the specified context. It should have builtin support for multiple versions of Grafana so the plugin developers never need to change version of the support package to run tests agains an older version of Grafana. Plugin developers should only need to update the support package when they want to support never versions o Grafana.
> 
> How could this look like? Without the details but high level?

So when I did it in the POC I collect it from grafana boot data. Then I had some logice that could create selectors on the fly depending on that version. I later stored those selectors in an alias so it is easy to reuse in the support library.

Lets say that we have a internal selector structure that looks something like this:

```ts
type Selectors = {
    panelByTitle(title: string) => Chainable<Element>
    queryEditor(refId: string) => Chainable<Element>
    ...
}
```

That is what our exposed flows are depending on to collect the different elements on the page. So in my example above we have `getQueryEditor(opts: Options) => select.queryEditor(opts.refId)` which will return the element to the plugin developer so it can be used in the tests.

In Grafana 10.1.0 the markup for the panel edit is changed so we need to use a different selector to fetch the query editor compared to how it worked in Grafana 10.0.0.

Internally in the library we would then have a versioned structure for each selector. I'm not sure how we should structure this files/folders etc to make it easy to scale but the idea would be as follows:

const queryEditor = {
   "10.0.0": (refId: string) => Chainable<Element>,
   "10.1.0": (refId: string) => Chainable<Element>,
};

const panelByTitle = {
   "10.0.0": (title: string) => Chainable<Element>
}

So if we are running the library in Grafana 10.1.0 the logic which creates the selector structure would select the latest available selector that has a version less than or equal to the version of Grafana that we are currently running.

So the selectors object that we will use in our public APIs would use the `10.1.0` from the `queryEditor` selector and the `10.0.0` from the `panelByTitle` since that didn't change in version `10.1.0` of Grafana. 

The plugin developer would never see this but he/she would only work with the public API that is `getQueryEditor`. I hope I managed to explain this in a way that makes sense.

> 
> > The npm package that provides flows/support to navigate to the different contexts
> 
> The package versioned by grafana versions? by cypress versions?

This package would have its own versioning. Probably following cypress major versioning if needed.

> 
> Do you know if `custom commands` that provide the flows via `supportFile` are stable between cypress version changes (e.g. can same `custom commands` usually be used for `Cypress 7` and `Cypress 12`?)

If that is the case we would need to pick "major" versions of cypress to support and release different major versions of our support package to "follow" that version.

**Comment by sunker** [comment]
Closing this epic in favour of https://github.com/grafana/grafana/issues/77484
