### ISSUE TITLE
Navigation: Ability to find and organize nav items 

### ISSUE THREAD

**Issue by axelavargas** [grafana/grafana#46354]
Old Approach: [Ability to pin/unpin items in the navbar (show/hide, declutter the navbar) ](https://github.com/grafana/grafana/issues/43822)

### Approach Changed(Behind feature toggle):

Instead of offering the ability to `pin/unpin`  items in the navbar, we are moving towards

- In the mega menu we will be adding a new section of `Saved Items`
- When implementing the mega menu with collapsible sections
	- Each section item will NOT contain icons
	- On hovering each item it will be possible to `save/bookmark` the item into the saved items
	- When clicking any saved item the active state should belong to the parent section of the item, not to the saved items 
	- An item that is `saved` can also be `unsaved` from the `saved Items` section and the parent section of the item.
- We will be keeping the current navbar with all the items but adding a scroll mechanism when items overflow
- Initially reordering is not going to be possible inside the the `saved Items`
- A persisted state is desirable when collapsing or uncollapsing sections in the mega menu
- The old prototype of the navbar should remove the visual sections(logo, core, plugins, etc), but should keep the + button changes

##### Update existing structure
- [x] Clean up the old prototype of the navbar to remove the visual sections (keep the change and remove the + button, remove the home button, the logo is the new home) https://github.com/grafana/grafana/pull/46693
- [x] Update [Navigation: Store pinned status in a db #44376](https://github.com/grafana/grafana/issues/44376) to support new approach (saved items section)
- [x] Navigation item titles can break into multiple lines
- [x] #46872
- [x] #47113
- [x] #46726 @JoaoSilvaGrafana @axelavargas 
- [x] #47965

#### Add new functionality
- [x] Add persisted state to megamenu sections (open/closed)
- [x] #47072
- [x] ~#48749~
- [x] #49219 
- [x] #44976

#### Keep current functionality intact
- [x] On mobile devices, keep the 'megamenu' behind a hamburger icon: similar to current behavior
- [x] ~Whitelabeling: 1) Grafana logo can be replaced by the customer’s logo. 2) There might be an additional logo, in case of AWS-based deployments.~ confirmed this is still working - ash
- [x] Pro features highlighting - https://github.com/grafana/grafana/pull/49892

#### Feature toggles
- [x] #47884

#### Questions?

_Originally posted by @axelavargas in https://github.com/grafana/grafana/issues/43822#issuecomment-1062183871_

**Comment by amy-super** [comment]
@axelavargas this all looks great to me! Really happy to see the Rudderstack addition :)
