### ISSUE TITLE
Prometheus: Implement visual query builder

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#47316]
## Prometheus 
* [x] Metric select (can start with metric or labels)
* [x] Label filters (can start with metric or labels)
* [x] Plain aggregations 
* [x] Aggregations by label
* [x] Support aggregations without label. Think we can support it by having "Max without", "Sum without" operations. 
* [x] Parser that can take a text expression and transform it into the visual model [@aocenas][#44824]
* [x] Support for legend format option.
* [x] Histogram quantile function
* [x] Label_replace function
* [x] Add missing functions @srclosson 
* [x] Hint system, for example, hint to add function rate. @ivanahuckova
* [x] Support for step and maybe resolution. We should try to explore íf we can somehow skip / automatically handle these. 
* [x] Show resolution option, only if set to something other than 1/1 (or deprecate it fully) @torkelo 
* [x] Metric search with highlights and multi-word search (so searching `template failures` would match a metric name `prometheus_template_text_expansion_failures_total`. This is not something the text editor suggestions can do but with the select dropdown we have for metrics now we could implement a custom search that would check matches for both words (separated by white space). @ivanahuckova 
* [x] For explore it should remember preferred editor
