### ISSUE TITLE
EPIC: Swagger go/api-client generation

### ISSUE THREAD

**Issue by ying-jeanne** [grafana/grafana#47827]
**All steps we need to finish for the generated OpenAPI client for Go in [grafana-openapi-client-go](https://github.com/grafana/grafana-openapi-client-go).**

## Summary

Go-swagger can generate clients in different languages from the OpenAPI specification that will be synched with the grafana API. In addition to this, we can trigger the generation of the client whenever a Grafana release is tagged and in that way having an updated client version for each supported grafana version.

### Problem Statement

Grafana maintains a [Go API client](https://github.com/grafana/grafana-api-golang-client) (which is used by other [tools](https://github.com/grafana/terraform-provider-grafana) for interacting with grafana instances). However, this is a library on top of the client that re-introduces [models](https://github.com/grafana/grafana-api-golang-client/blob/e5fb6a3c3e108194be38766f878111eccc22a2b5/api_key.go#L11) sent or retrieved from the client (other than the ones defined in grafana codebase). The client and the models are usually out of sync of the API given that manual effort is required for addressing any API change.

### Impact

- Save internal developer time by removing the need to manually write code to implement the new feature in the client each time there is a new feature.
- Maintain feature parity with the Grafana backend, ensure that all features that are offered in Grafana are also offered by the client
- Minimise security vulnerabilities, missing features, tech debt, code smells, etc.

### Key Deliverables/Acceptance Criteria

- As a Grafana developer, I want to trigger the client generation so I can see new features that were added to the backend in the client without having to write code to add those features.

### Rough Scope

Q3 2023

### How are we measuring success?

- Provide support for nested folders around GA in the Terraform Provider through the OAPI client.
- Provide E2E support for the `Folder` backend service in the TF Provider through the Client as well as at least 2 other backend services by the end of the quarter.
- Empower other teams to 1) generate clients for Grafana backend services and 2) replace the client for those services in the Terraform Provider.

### Milestone 1: Bootstrap OpenAPI Go Client [6 weeks]
- [x] #71995
- [x] https://github.com/grafana/grafana-openapi-client-go/pull/6
- [x] https://github.com/grafana/grafana-openapi-client-go/pull/8
- [x] [Generate client for all APIs]( https://github.com/grafana/grafana-openapi-client-go/pull/13)
- [x] #72001
- [x] #72003
- [x] https://github.com/grafana/terraform-provider-grafana/issues/935
- [ ] #73264
- [ ] #73263
- [ ] #71996 

### Milestone 2: OpenAPI Automation [4 weeks]

CI automation around the OpenAPI specification & client can be done in parallel with the work to bootstrap the client.

- [x] #73267
- [x] #75090
- [x] #73266
- [ ] https://github.com/grafana/grafana-openapi-client-go/issues/9
- [ ] #73265

### Milestone 3: Next Steps

Blocked by the two sections above.

- [x] #73262
- [x] https://github.com/grafana/grafana/issues/65869

### Past Improvements
- [x] Improve the make command to take Grafana version as input in order to generate the go-client corresponding the Grafana swagger version, maybe to improve in the future. we need to note from which version we support.
- [x] Make optional field work in the go-client generation
- [x] Make the generated swagger JSON key ordered so we can have a consistent output every time. https://github.com/grafana/grafana/pull/50576
- [x] ~Make the array works in the go-client generation @ying-jeanne~ Resolved by using go-swagger client generator tool
- [x] Move generated go-client outside of grafana
- [x] Spin up a grafana docker image during unittest of go client

**Comment by safaci2000** [comment]
Hi, I'm really interested in this ticket.  Are there any tasks that I may help with?  Basically looking for a more official golang-api SDK/client to utilize.

**Comment by danielthedm** [comment]
Decision: Need to figure out if this should go in it's own branch or in a separate repo

**Comment by safaci2000** [comment]
I've been using a [fork](https://github.com/esnet/grafana-swagger-api-golang) of this branch for my own use case.   It's almost an exact copy I just updated the version it's built against.  I will say that there a few endpoints that need some polish.  

ie. Swagger definition doesn't match the response returned.  If you need a beta tester let me know.  I'd love to see this become a bit more official.

**Comment by nikimanoledaki** [comment]
@safaci2000 we just merged the PR to generate all services in the OAPI spec using swagger! https://github.com/grafana/grafana-openapi-client-go/tree/main/client 🎉
