### ISSUE TITLE
Create a new alert state history API

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#48359]
# Why an Alert State History API

Grafana users should be able to see the history of an alert rule. When was the rule alerting? How many alert instances where alerting or pending, and what were they? What were the values in queries and expressions that controlled the behavior of the rule?

After implementing this API, the alerting frontend can display this history information in dashboard panels and the alerting UI itself.

[Grafana Internal Design Document](https://docs.google.com/document/d/15KMBhUFPDkzWWpjZSXw1L3zsuEVg2xzZJEuuNiEfFn8/edit#)

## On Deck
- [x] #52496 
- [x] #52499 
- [x] https://github.com/grafana/grafana/issues/60930
- [x] #52501
- [x] Communicate with external loki instances: https://github.com/grafana/grafana/pull/61114
- [x] Authenticate with external loki instances: https://github.com/grafana/grafana/pull/61696
- [x] Explore loki client configuration
- [x] Format state history entries as log lines and push them to Loki (https://github.com/grafana/grafana/pull/61724)
- [x] Design a Loki-friendly representation of `state.Values` https://github.com/grafana/grafana/pull/62643
- [x] https://github.com/grafana/grafana/issues/58351 (https://github.com/grafana/grafana/pull/61646)
- [x] Add endpoint for querying alert state history https://github.com/grafana/grafana/pull/61992
  - [x] Support querying by label (https://github.com/grafana/grafana/pull/62831)
  - [x] Support querying by time range (https://github.com/grafana/grafana/pull/61992)
  - [x] Support querying by rule UID (https://github.com/grafana/grafana/pull/61992)
- [x] Define a dataframe-based format for state history data (what is the schema inside the dataframe?) (https://github.com/grafana/grafana/pull/61992)
- [x] https://github.com/grafana/grafana/issues/59445
- [x] https://github.com/grafana/grafana/issues/64942

## Exploration
- [ ] Allow remote loki backend to be pointed to a datasource configuration (optional, may not be needed)
- [x] #52498 
- [x] #52502 
- [x] #52497 

## To be expanded upon
- [ ] https://github.com/grafana/grafana/issues/52788

### Related Issues:
These illustrate problems we want to solve with a state history API:
*  #45900 
* #45300 
* https://github.com/grafana/alerting-squad/issues/340
* https://github.com/grafana/grafana/issues/49779

The state history and preview APIs should adopt the same structure to make UI development straightforward for these related types of data.
* #51319

**Comment by bygui86** [comment]
hi guys
thanks for this issue, it's really really important for us.
what's the status?
is this related to the button `Show state history` in a detailed view of an alert? (that button shows nothing)
do you have an idea of when this will be released?
thanks :)

**Comment by go4real** [comment]
Hello Grafana colleagues,
Our company desperately needs this feature!!
Please release this with Grafana Cloud.
Thanks ahead~

**Comment by fornellas** [comment]
Prometheus provides the `ALERTS` time series. I'd consider having this data available as a similar prometheus time series, as 1. it is familiar to many people, 2. people can use promql to do any calculations / dashboards they want on top.

**Comment by armandgrillet** [comment]
@bygui86 We would like to have this ready for release by the end of January 2023.

**Comment by bygui86** [comment]
@armandgrillet thanks for the info!
is this related to the button `Show state history` in a detailed view of an alert? (that button shows nothing)
do you have an idea of when this will be released?

**Comment by armandgrillet** [comment]
This issue is about a new API which the Grafana frontend will be able to consume, we do not have worked on the use by frontend yet but `(that button shows nothing)` looks like a bug which we will be able to fix once the new API is available. I cannot see a related issue in this repository about that problem, can you create one so that we can keep track of the issue you're mentioning?

**Comment by bygui86** [comment]
@armandgrillet  I was able to understand the button `Show state history` not showing anything. It was due to upgrade and migration from alerts created with the old alerting system to new unified one.
Removing every dashboard and panel reference fixed that.

**Comment by arash-bizcover** [comment]
@armandgrillet do we have any **API** endpoint to show the **current**  state/status of an alert_rule at all?
