### ISSUE TITLE
Service Graph improvements

### ISSUE THREAD

**Issue by connorlindsey** [grafana/grafana#48351]
Below is an ordered list of improvements we will work on in Q2. If you'd like to see something added or prioritized, let us know. Items will be tracked as separate issues when we start working on them, and we will link those here.

- [x] Download and upload service graphs https://github.com/grafana/grafana/pull/50260
- [x] Make visualization take whole height of screen in Explore https://github.com/grafana/grafana/pull/50518
- [x]  Add link to Tempo search with service selected https://github.com/grafana/grafana/pull/49776
- [x]  Add menu item to filter by that service https://github.com/grafana/grafana/pull/49776
- [x]  Review linked queries https://github.com/grafana/grafana/pull/50897
- [x]  Review stats shown on nodes and edges https://github.com/grafana/grafana/pull/50897
- [x] Update hover styles to better emphasize hovered connections https://github.com/grafana/grafana/pull/51925
- [ ] Clarify client/server relationship.
    - Show inbound and outbound requests?
- [ ]  Investigate layout algorithm
    - Scenario to consider: https://github.com/grafana/grafana/issues/49988
    - Prevent edges overlapping
    - Prevent edges from going through nodes which aren't connected
- [ ]  Improve framing on initial render (position of graph on initial render)
- [ ]  Filter filter values to only those from the service graph metrics
- [ ]  Negative numbers appearing in ops (negative latency on num of requests on an edge - could put some safeguards when we calculate the metrics). Didn't see this in a while. Bug a couple of weeks ago where arc values didn't add up to 100% when data coming from backend.
- [x] Add context menu to edges https://github.com/grafana/grafana/pull/52396
- [ ] Add filters from service graph to linked queries

Potential improvements
- [ ] Add ability to drag nodes
- [ ] Handle producer, consumer, and database nodes
- [ ] Show changes over time
- [ ]  Compare two time ranges

**Comment by joe-elliott** [comment]
Awesome, list. Thanks @connorlindsey. One that I'd like to add is color coding client/server connections red that are showing an elevated error rate. Currently we only color code the node.

**Comment by rlex** [comment]
https://github.com/grafana/grafana/discussions/52183 would like to add my feature request

**Comment by joey-grafana** [comment]
Closing this epic as it was only intended for to track items for Q3. The remaining items have been added to the backlog.
