### ISSUE TITLE
Epic: Search and browse dashboards

### ISSUE THREAD

**Issue by zsofiakomaromigrafana** [grafana/grafana#48688]
We are updating the search (`&search=open`) and browse dashboards (`/dashboards`) pages to support the following:
- New search API and displaying additional data in the results table (e.g. data source) and searching dashboards by panel title
- Folder nesting

1. New results table (rest of the UI unchanged)
- [ ] Create components for search results table
- [ ] Use new search results table and new API on `/dashboards`
- [ ] Use new search results table and new API on `&search=open`

2. Nested folders

3. Additional UI updates (outside the search results table)
