### ISSUE TITLE
Chore(Epic): Migrate from DashboardID to DashboardUID in Frontend

### ISSUE THREAD

**Issue by axelavargas** [grafana/grafana#48850]
**What happened**:

To support nested folders in our new Search Engine we need to stop relying on internal `IDs` for Dashboards and folders.

Because of this, our backend team is migrating the API endpoints to use `DashboardUID` instead of `DashboardID`  ([Backend Issue](https://github.com/grafana/grafana/issues/48331)). For Grafana v9.0 these changes are still backward compatible, but we need to do the migration in the frontend.

Frontend Places that need migration:

- [x] #51870 @ivanortegaalba 
- [x] #51976 @ivanortegaalba 
- [x] #52065  @lpskdl 
- [x] #52459 @lpskdl 
- [x] #52586 @ivanortegaalba 
- [x] #52863 @lpskdl 
- [x] Remove `id` from `DashboardSearchHit`, `DashboardSection` & `DashboardSectionItem` to avoid using IDs as the result of a search
- [x] Remove `id` from DashboardDataDTO to avoid usage of `id` when managing the dashboard data model
- [x] #54243
- [x] #54235
- [x] #54270
- [x] https://github.com/grafana/grafana/pull/54296
- [x] Stop using DashboardPicker by ID as part of https://github.com/grafana/grafana/pull/54125
- [x] #58564
- [x] #57874

### Blocker for #58564
- [x] #58568
- [x] #58569

### After migration is complete

- [ ] Test navigation still works with some of these app plugins that have integrated dashboards 
	- [ ] [grafana.com/grafana/plugins/?type=app](https://grafana.com/grafana/plugins/?type=app): redis, zabbix and tencent should be enough. (Plugins Platform squad is happy to support with testing)
- [x] #53193

**Comment by joshhunt** [comment]
Remaining places DashboardPicker is used for dashboard ID:
 - Enterprise reporting https://github.com/grafana/grafana-enterprise/blob/main/src/public/reports/ReportForm/SelectDashboard.tsx#L246
