### ISSUE TITLE
Internationalisation: Productionalise

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#49280]
What's required for an initial "public" release of internationalisation:

 - [ ] Add + save user preference for locale
 - [ ] Load messages for user's selected locale
 - [ ] Connect codebase to Crowdin to sync translation files
 - [ ] Connect Crowdin to translation partner to translate messages
