### ISSUE TITLE
Time series panel: Graph panel features parity and improvements epic

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#49670]
Ref https://github.com/grafana/grafana/issues/49031

This issue summarizes features that were available in **old Graph panel** and are missing in the **Time series panel**. It should bring more clarity on when and if we as Grafana are going to implement those for the new panel.

**Missing features:**
- [ ] Time regions support https://github.com/grafana/grafana/issues/35486
- [ ] Null represented as 0 https://github.com/grafana/grafana/discussions/43093
- [ ] Possibility to toggle legend visibility from panel menu https://github.com/grafana/grafana/issues/49005
- [ ] Log scale different bases support (currently Time series panel supports log2 and log10 only)
- [ ] https://github.com/grafana/grafana/pull/49126

**Features that need improvements:**
- [ ] https://github.com/grafana/grafana/discussions/38299
- [ ] Legend & tooltip sorting/filtering:
  - [ ] https://github.com/grafana/grafana/discussions/41104
  - [ ] https://github.com/grafana/grafana/discussions/38861
  - [ ] https://github.com/grafana/grafana/discussions/38305
- [ ] Y-axis 
  - [ ] Improve auto-decimals, to prevent looking like they repeat when exceeding 3 decimals. somewhat intertwined with https://github.com/grafana/grafana/issues/35838
  - [ ] Improve y-axis auto-scaling to select top and bottom ticks better so they're always at the graph edges. https://github.com/grafana/grafana/issues/39359 
- [ ] https://github.com/grafana/grafana/issues/46290
- [ ] https://github.com/grafana/grafana/issues/46273
- [ ] https://github.com/grafana/grafana/issues/47064
- [ ] https://github.com/grafana/grafana/issues/46271
- [x] https://github.com/grafana/grafana/discussions/38305

**Comment by samjewell** [comment]
Hi team
I think there's an additional item for the Missing Features list:

The old Graph panel allowed for the result of an instant query to be transformed with the series-override `Transform: constant`
![image](https://user-images.githubusercontent.com/2903904/175263292-ca2bc935-7062-42d9-b490-a20771e65566.png)


A place where we still use this is on the Billing/Usage dashboard, for the blue dashed line:
![image](https://user-images.githubusercontent.com/2903904/175262844-ceabeb67-0fde-40c2-80b6-4d83f4df4a4c.png)


When I migrate this panel to the new TimeSeries panel type I can see that the configuration for that series (the override with the transform) has been migrated, but it doesn't render correctly (actually the blue line doesn't render at all):
![image](https://user-images.githubusercontent.com/2903904/175263667-6e83ea1f-3e49-4bee-b2ee-bdcb2bbf1253.png)

This is blocking us from upgrading to the Time-series panel right now.

**Comment by leeoniya** [comment]
better rendering parity for constantY: https://github.com/grafana/grafana/pull/51401

**Comment by codeincarnate** [comment]
One thing coming up for Time Series is ordering of rendering in chart vs legend/tooltip. Issue for that is at #36882

**Comment by Jafner** [comment]
People following this issue on the forums: [Y-axis zero align](https://community.grafana.com/t/v8-and-y-axis-zero-align/49152) are being pointed here, but I don't see an issue in this epic for aligning the zeroes on Time Series panels with two or more Y-axes.  

In my use case here: 
![image](https://user-images.githubusercontent.com/40403594/179803077-cab16d02-346a-4bdc-b46d-1881135a3337.png)
The bits per second and packets per second axes are slightly misaligned.

**Comment by leeoniya** [comment]
i'm struggling to reproduce this function in the old panel to see how it worked before, but i think the easiest way to get align-0 working is to introduce an option for forcing axes/scales to be symmetric (there have been requests for this feature as well [1]), effectively making 0 always centered vertically on any axis where it is enabled.

for example if raw data range is this:

fieldA min/max (left y axis): 3,9
fieldB min/max (right y axis): -17,113

setting both fields to have symmetric y axes (vertically-centered 0) would result in ranges of e.g.:

left axis: -10,10
right axis: -115,115

so in this case you would lose some visual resolution in the negative part of fieldB, with 85% of the displayed negative range being empty space, but this will have to be the trade-off.

[1] https://community.grafana.com/t/symmetrical-y-axis/10562

**Comment by samjewell** [comment]
Hey team
Just spotted another feature gap between the old Graph panel and the new Time Series panel.

The old Graph panel has a "Right Y" axis configurable. See screenshot:

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/2903904/212130088-74e9e74c-dd62-4176-a846-006870452195.png">

We use this in the Billing/Usage dashboard on Grafana cloud, and while it is missing we can't do a straightforward migration to the new TimeSeries panel. We'd have to redesign the dashboard to move all these "Right Y" queries out from this panel to a new panel, which itself would make the data harder to read in some cases. The Right Y is useful as it allows users to see how costs correlate with usage.

And we'd love to migrate to the new panel, partly because [this issue](https://github.com/grafana/grafana/issues/59698) is stopping users from being able to use the following workflow:
- Create a library panel from a panel on the Billing/Usage dashboard
- Add that library panel to a new dashboard of their own construction, where they do their own custom costs/usage analysis and alerting etc.

Can you let me know if you think this feature gap is likely to be closed, or is considered out-of-scope for the new TimeSeries panel? Thanks!

**Comment by CoreMoni** [comment]
Hello,
I'd like to mention another missing feature: The sort order of stacked lines does not reflect the sort order of the legend.

![image](https://user-images.githubusercontent.com/111497946/215071426-9b197893-1b95-4a2a-8adc-81d7566d0734.png)

See also: https://community.grafana.com/t/sorting-of-stacked-series-in-time-series-panel/69577
Apparently it was working in 8.3.0, but not in 8.5.9, and now, in 9.3.6, it's still not working.

**Comment by leeoniya** [comment]
> The old Graph panel has a "Right Y" axis configurable. See screenshot:

@samjewell the TimeSeries panel supports unlimited y axes. you just have to use a field override to set `Axis placement` where needed.

> The sort order of stacked lines does not reflect the sort order of the legend.

this was removed deliberately because it had many problems. see https://github.com/grafana/grafana/discussions/54142.

**Comment by samjewell** [comment]
> @samjewell the TimeSeries panel supports unlimited y axes. you just have to use a field override to set Axis placement where needed.

Ah nice, thanks @leeoniya, that's great to know. I think the automatic migration tool just discards the second Y-Axis when it migrates. Could it be extended to preserve this maybe, do you think?

**Comment by CoreMoni** [comment]
> this was removed deliberately because it had many problems. see #54142.

Darn... I have several panels showing usage/utilization data, and the stacks should be sorted from biggest consumer to smallest instead of alphabetically. We achieved this via sorting by avg in the legend. Is there any way to influence the stacking order in the Time series panel at all?

**Comment by leeoniya** [comment]
> Could it be extended to preserve this maybe, do you think?

if i recall correctly, we already automatically create additional right Y axes for fields that have a different unit (try it out with a fresh panel and two different-unit fields), so i'm not sure there is anything that needs to be migrated. maybe open a new issue with more specific details about the types of old configs that arent working as you expect?

**Comment by leeoniya** [comment]
> Is there any way to influence the stacking order in the Time series panel at all?

not dynamically based on the data. you can use an Organize fields transform to put them into a predefined order, or modify your sql select query to do the same.

**Comment by CoreMoni** [comment]
> or modify your sql select query to do the same

My datasource is prometheus, and PromQL has SORT() and SORT_DESC(), but neither function seems to have any effect on the stacking order

**Comment by leeoniya** [comment]
hmm, it looks like you're right, i think those functions only work for instant queries and and not range queries. https://stackoverflow.com/questions/64395442/how-can-i-sort-the-legend-by-series-name-in-prometheus-grafana/65353296

https://github.com/grafana/grafana/blob/6c990b461e4650effbfddb1fc9264bb6ad4d726a/packages/grafana-ui/src/components/uPlot/PlotLegend.tsx#L60-L116

if we were to bring back reordering fields by "legend" calculations in the viz, we would need to pull these calcs above the vis+legend components, so that the viz can be reconfigured from them; you can't wag a dog by its tail, so they say.

**Comment by dprokop** [comment]
> if we were to bring back reordering fields by "legend" calculations in the viz, we would need to pull these calcs above the vis+legend components, so that the viz can be reconfigured from them; you can't wag a dog by its tail, so they say.

@leeoniya you are right about this. In some circumstances (when no min/max std options are provided) the calcs will be present in the field's state prior visualization - because auto min/max triggers stats calculation:

https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/field/fieldOverrides.ts#L173-L175

But we cannot assume calcs are there when the stacking is processed, hence we would have to calculate those when the panel is prepared (maybe in `prepareGraphableFields`, or maybe better internally to uPlot wrapper- `prepState` in GraphNG.tsx that creates the aligned frame?). Then the calcs will be in place for stacking to use it and sort the groups correctly I think.

**Comment by samjewell** [comment]
> > Could it be extended to preserve this maybe, do you think?
> 
> if i recall correctly, we already automatically create additional right Y axes for fields that have a different unit (try it out with a fresh panel and two different-unit fields), so i'm not sure there is anything that needs to be migrated. maybe open a new issue with more specific details about the types of old configs that arent working as you expect?

Thanks for this @leeoniya - I've opened this issue: https://github.com/grafana/grafana/issues/66704
