### ISSUE TITLE
Standardize message body and title templating in receivers

### ISSUE THREAD

**Issue by JacobsonMT** [grafana/grafana#49716]
Some receivers allow templating on the title/subject and message body field and some use the hard-coded default (`{{ template "default.title/message" . }}`). 

I think it would be good to add a UI configuration to all receivers that are missing templating on these fields.

These receivers use a hard-coded default message field:

- [x] kafka, on "details" https://github.com/grafana/grafana/pull/57361
- [x] line, "description" on message https://github.com/grafana/grafana/pull/57388
- [x] opsgenie, on "description" https://github.com/grafana/grafana/pull/50131
- [x] threema, on "text" https://github.com/grafana/grafana/pull/57429
- [x] victorops, on "state_message" https://github.com/grafana/grafana/pull/57458
- [ ] webhook, on "Message" https://github.com/grafana/grafana/pull/58058 https://github.com/grafana/grafana/discussions/44334

For titles, the only receiver (supporting titles) that currently allows a custom title is slack. Which leaves the following to be updated:

- [x] dingding, on "title" https://github.com/grafana/grafana/pull/57498
- [x] discord, on "title" https://github.com/grafana/grafana/pull/57506
- [x] email, on "title/subject" https://github.com/grafana/grafana/pull/49742
- [x] googlechat, on "title" https://github.com/grafana/grafana/pull/57517
- [x] kafka, on "description" https://github.com/grafana/grafana/pull/57361
- [x] opsgenie, on "message" https://github.com/grafana/grafana/pull/50131
- [x] pushover, on "title" https://github.com/grafana/grafana/pull/57530
- [x] victorops, on "entity_display_name" https://github.com/grafana/grafana/pull/57458
- [ ] webhook, on "title" https://github.com/grafana/grafana/pull/58058

Other receivers don't have a dedicated title but still embed the default title in their message. These can also benefit from making this title customizable:

- [x] line https://github.com/grafana/grafana/pull/57388
- [x] threema https://github.com/grafana/grafana/pull/57429
- [x] wecom https://github.com/grafana/grafana/pull/51529

The next contact points are already customizable but have new settings handling:

- [x] pagerduty https://github.com/grafana/grafana/pull/57524

**Comment by grafanabot** [comment]
This issue was removed from the 9.2.0 milestone because 9.2.0 is currently being released.
