### ISSUE TITLE
User friendly alert definitions for provisioning

### ISSUE THREAD

**Issue by santihernandezc** [grafana/grafana#50012]
Our JSON representation of an alert rule contains a `data` field which is huge and intricate. If you want to provision an alert rule, you have to follow this current format.

We could come up with a simpler format for provisioning alert ruler in our main data sources in a more succinct way. We would need a translation layer to go from this new format to a format that Grafana understands and can use internally.

Steps:
- [ ] Figure out a set of common data sources.
- [ ] Have a simple alert rule definition for each of these.
- [ ] Figure out where to perform the format translation.
- [ ] Implement the translation layer.

**Comment by azelezni** [comment]
We came across this same issue when starting to use Grafana Alerts with file provisiong, I ended up making a tool [grafana-simple-fp](https://github.com/azelezni/grafana-simple-fp) to make it simpler to define alerts, it's still very limited (only supports prometheus, and minimal elasticsearch support) however the yaml structure is much simpler.
