### ISSUE TITLE
Alerting: Remove the concept of `object_matchers` in favour of using upstream's `matchers`

### ISSUE THREAD

**Issue by gotjosh** [grafana/grafana#50040]
As it stands, `object_matchers` is kind has kind of a convoluted implementation that started in https://github.com/grafana/grafana/pull/38629.

It probably was the best decision at that point to move forward, but we've reached a point where its implementation is doing more harm that good - I think it's time we kick off the conversation around separating the validation logic from the parsing logic in the upstream `ParseMatchers` and `ParseMatcher` function so that can re-use them downstream in Grafana.

Concretely I'd like to see:

- [ ] Test & validate how would `ParseMatchers` and `ParseMatch` can separate validation from parsing.
- [ ] File a proposal upstream (Alertmanager) to split them
- [ ] Remove the concept of `object_matchers` on both the backend and front-end
- [ ] Test the marshalling and unmarshalling all the way from the migration to the API

**Comment by alexweav** [comment]
This can be considered part of alertmanager unification.

**Comment by grobinson-grafana** [comment]
Closing as duplicate of https://github.com/grafana/alerting-squad/issues/729.
