### ISSUE TITLE
Loki query builders epic

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#50235]
- [x] https://github.com/grafana/grafana/issues/48530
- [x] https://github.com/grafana/grafana/issues/48531
- [x] https://github.com/grafana/grafana/issues/48532
- [x] https://github.com/grafana/grafana/issues/48534
- [x] https://github.com/grafana/grafana/issues/48535
