### ISSUE TITLE
Logs: UX improvements

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#50234]
The UX/PM team ran a series of interviews with self-serve customers who self identified as 'beginners' and new to LogQL. We also interviewed a few internal users. 

The following is a list of Github issues that we created coming out of that research.

- [x] https://github.com/grafana/grafana/issues/50268
- [x] https://github.com/grafana/grafana/issues/50861
- [x] https://github.com/grafana/grafana/issues/50904
- [x] https://github.com/grafana/grafana/issues/50188
- [x] https://github.com/grafana/grafana/issues/50265
- [x] https://github.com/grafana/grafana/issues/50871
- [x] https://github.com/grafana/grafana/issues/50270
- [x] https://github.com/grafana/grafana/issues/51150

**Comment by 09jvilla** [comment]
I'm removing `Remove highlight for filtered word (maybe intern issue)` from the list until we have a github issue and an actual design for this. Right now I'm calling this out of scope for the original work.

**Comment by gabor** [comment]
NOTE: i'm removing https://github.com/grafana/grafana/issues/48988 from the list, that issue's current direction is to be solved by the loki squad.

**Comment by 09jvilla** [comment]
Sounds good to me @gabor .

**Comment by svennergr** [comment]
https://github.com/grafana/grafana/issues/56038 in https://github.com/grafana/grafana/issues/50270 is not trivial with the way the context is currently designed and implemented. I'll close this issue and cover https://github.com/grafana/grafana/issues/56038 in https://github.com/grafana/grafana/issues/58032.
