### ISSUE TITLE
Tracing improvements

### ISSUE THREAD

**Issue by joey-grafana** [grafana/grafana#50254]
List of upcoming tracing improvements - please let us know if you'd like anything added to this list.

- [x] Horizontal scrolling https://github.com/grafana/grafana/pull/50278
- [x] OTEL terminology and tracing conventions (span.kind, status, etc.) https://github.com/grafana/grafana/pull/51379
- [x] Customize span tag (HTTP GET) in trace UI: [https://github.com/grafana/grafana/discussions/43707](https://github.com/grafana/grafana/discussions/43707) https://github.com/grafana/grafana/pull/50931
- [x] Show absolute time https://github.com/grafana/grafana/pull/50685
- [x] Don't show red in span colors https://github.com/grafana/grafana/pull/50074
- [x] Show consistent span colors https://github.com/grafana/grafana/pull/50782
- [x] Jaeger add support for variables and interpolate in explore https://github.com/grafana/grafana/pull/50500
- [x] Add more template variables in Tempo and interpolate in explore https://github.com/grafana/grafana/pull/52306
- [x] Add template variables in Zipkin and interpolate in explore https://github.com/grafana/grafana/pull/52306
- [x] Tempo/Prometheus select ds in new tab (cmd + click) https://github.com/grafana/grafana/pull/52319
- [ ] Close details when span (or outer spans) are collapsed
- [x] Refactor go trace parsing to use json-field (see https://github.com/grafana/grafana/pull/48486)
- [x] Sort attributes alphabetically https://github.com/grafana/grafana/issues/45793

Potential improvements
- [ ] Mini-map feature
- [ ] Make 'header' sticky (to discuss)

**Comment by nicolastakashi** [comment]
Hey @joey-grafana 
I don't know if it's already available.
Would be nice if Grafana has a panel for Service Dependency Graph from Jaeger as well as we have for Loki.
Jaeger uses a spark job to build the Service Graph and would be awesome have this available on Grafana.

**Comment by nicolastakashi** [comment]
Hey @connorlindsey thanks 😄 
I've opened the feature request, and I'm available to support this implementation if you allow me.
Probably I just need some guidance but I would love to support it.
