### ISSUE TITLE
Make config for notification channels consistent across all AMs

### ISSUE THREAD

**Issue by santihernandezc** [grafana/grafana#50462]
When setting up a new contact point, the level of configuration we give users is not the same if they're using the internal AM vs. the Cloud AM.

This comes from https://github.com/grafana/grafana/issues/47813, where several users were trying to customize the title and message for OpsGenie alerts without success. This option is currently only available for Cloud Alertmanager users (screenshots below).

<details>

![Screen Shot 2022-06-08 at 17 29 47](https://user-images.githubusercontent.com/41638679/172711208-e5067a3c-dc26-4308-9090-c61efd8c3585.png)
<summary>
Config for OpsGenie using Grafana AM
</summary>
</details>

<details>

![image](https://user-images.githubusercontent.com/41638679/172711451-7f5836fb-490f-44d4-8788-0725dd249c6d.png)
<summary>
Config for OpsGenie using the Cloud AM
</summary>
</details>

This configuration fields come from different sources. For Grafana AM we pull those fields from the [back end](https://github.com/grafana/grafana/blob/c59938b23580e238d27b17213860afe38606fc4f/pkg/services/ngalert/notifier/available_channels.go#L844-L897), where we have all contact point definitions in a single file. For the Cloud AM the config is in the [front end](https://github.com/grafana/grafana/blob/c59938b23580e238d27b17213860afe38606fc4f/public/app/features/alerting/unified/utils/cloud-alertmanager-notifier-types.ts#L255-L292).

**Action Items:**
- [ ] Identify which contact points have differences between AMs.
- [ ] For each one, figure out which differences can be fixed (there may be some differences due to the nature of each AM).
- [ ] Figure out a way of getting the config fields from the same field regardless of the AM (optional).
- [ ] Fix differences.

**Comment by DWebb0** [comment]
I'm registering my interest here, this is blocking a few Customers progressing with their adoption of Alerting.

**Comment by aifraenkel** [comment]
Closing given there was no activity for a few years and it wasn't prioritized since then.
