### ISSUE TITLE
Grafana Ops workflow audit

### ISSUE THREAD

**Issue by jessover9000** [grafana/grafana#50657]
**Background / Why we're doing this**

Grafana is expanding its offering for Alerting and DevOps. Independently built-and-released features still need to provide a seamless user experience. This collection of tasks strives to blend the workflows and experience together.

**Deliverables**

- [x] Product DNA doc [#50136](https://github.com/grafana/grafana/issues/50136) – [GoogleDoc](https://docs.google.com/document/d/1Sd0tGyNDTU8FMpo7TT9R485qrvQUocG3rLTDtGr89wc/edit#)
- [x] Competitive research for Alerting (results weaved into [Workflow board](https://miro.com/app/board/uXjVOVhp4Uw=/))
- [x] [Competitive research for OnCall and Scheduling](https://miro.com/app/board/uXjVO9owL-g=/), done by Raphael Batyrbaev
- [ ] Unified Alerting workflows [#48438](https://github.com/grafana/grafana/issues/48438)
- [x] Interview plan for GrafanaOps stakeholder interviews [#50137](https://github.com/grafana/grafana/issues/50137)

**UX goals**

Make Grafana the place for your DevOps workflow that makes being on-call not suck – both as a main event and as a supporting artist.

1. Incremental improvements: Adoption

- [ ] Enable users to get OnCall or Incident up and running within 10 minutes
- [ ] Data model for product overlaps: Do we want to unify properties and settings for overlapping areas so handover between products is easier? 

2. Incremental improvements: Compartmentalize

- [ ] Shorten workflows and/or split them up into smaller chunks
- [ ] Identify steps per sitting and areas with highest number of steps
- [ ] Identify optional parts of workflows that can be repackaged as “Advanced” steps

3. Incremental improvements: Wasted opportunities

- [ ] Identify connections between features that should be there but are not
- [ ] How might we connect Alert state history to OnCall / Incident?
- [ ] Escalate Incidents directly from OnCall and pull data from one product to the other
- [ ] Example: If an alert pops up in OnCall and an escalation chain runs, and then it’s declared as an incident, all the information from OnCall should get transitioned to an Incident event timeline

4. Radical improvements: Recommended DevOps path

- [ ] What should the experience be like if a fresh user installs Grafana Alerting + OnCall + Incident all at once? How might we make users feel like they are using just one product that is GrafanaOps?
- [ ] Information architecture of overall GrafanaOps
- [ ] Where do we want settings to be managed? Users have to learn which parts of the UI enable them to do what
