### ISSUE TITLE
Dashboard previews - GA

### ISSUE THREAD

**Issue by ArturWierzbicki** [grafana/grafana#50748]
follow up after https://github.com/grafana/grafana/issues/44449

- [ ] resolve styling UX feedback 
   - [ ] https://raintank-corp.slack.com/archives/C01PWGFJKQ9/p1648129314206259
   - [ ] https://raintank-corp.slack.com/archives/C030BN49G2U/p1655830816055019?thread_ts=1653904176.460669&cid=C030BN49G2U
- [x] roll out IR `3.4.1` to prod HG clusters
   - [x] canary https://github.com/grafana/deployment_tools/pull/33855 https://github.com/grafana/deployment_tools/pull/33936
   - [x] prod https://github.com/grafana/deployment_tools/pull/33982
- [x] Leverage HTTP caching - use ETag header https://github.com/grafana/grafana/pull/51008
- [x] Resolve datasource permission issue https://github.com/grafana/grafana/issues/47448
- [ ] update docs: remove mentions of "beta" and update permissions section
- [ ] PLACEHOLDER - incorporate MVP feedback

**Comment by ArturWierzbicki** [comment]
closing in favor of https://github.com/grafana/grafana/issues/65693
