### ISSUE TITLE
Navigation: Phase 2 🚀 

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#50791]
designs here: https://www.figma.com/file/jylhhvPsRKdGR5xlmIqXem/Start-here---Navigation?node-id=99%3A621

# Some prep

- [x] #50858
- [x] https://github.com/grafana/grafana/pull/51115

# TODO

- [x] Create new **basic** top navigation component
    - [x] Grafana logo (to go home)
    - [x] Hamburger menu opens the existing mega menu (https://github.com/grafana/grafana/pull/51616) 
- [x] Add new top navbar and remove existing Navbar (behind new feature toggle) #51301
- [x] #53947 
- [x] #53948 
- [x] Create standalone `Breadcrumb` UI component
  - [x] partly done by https://github.com/grafana/grafana/pull/51301
  - [x] https://github.com/grafana/grafana/pull/53383
  - [x] https://github.com/grafana/grafana/pull/53471
  - [x] #53761
- [x] Integrate `Breadcrumb` component in top navigation component 
  - [x] partly done by https://github.com/grafana/grafana/pull/51301
- [x] Integrate actions (e.g. dashboard actions + kiosk toggle) into top navbar
- [x] #53592
- [x] Implement new Page layout (#51510)
  - [x] Add Vertical tabs (Section nav)
  - [x] Item page with item level horizontal tabs
  - [x] Page title component that updates document title like old Page component does 
  - [x] #53141
  - [x] #55724
  - [x] #55725
- [x] #55616
- [x] Explore ways we can add links to page description (to docs for example)  (https://github.com/grafana/grafana/pull/52425) 
- [x] #54837
- [x] #54838
- [x] #55017
- [x] #55100
- [x] #55747
- [x] #56359
- [x] #56536
- [x] #56780
- [x] Further IA changes:
  - [x] #58211
  - [x] #58212
  - [x] #58213
  - [x] #58214
  - [x] #58215
  - [x] #59292
- [x] Plugin page customisation
  - [x] #58210
  - [x] #58322
- [x] #58629
- [x] #61213
- [x] #61147
- [x] #57989 
- [x] #57990 
- [x] #55755 

## Command palette
To be developed behind a separate feature toggle.
- [x] #61091
- [x] #61092
- [x] #61095
- [x] #61093
- [x] #62287

## Tracking
- [x] #59647
- [x] Create a Grafana dashboard with the number of instances with the `topnav` feature toggle on, and their number of active users (or if not available, then total users).
  - https://ops.grafana-ops.net/d/QkrxA1p4k/user-essentials-new-navigation-metrics?orgId=1

## Blocking Bugs
- [x] ~Hamburger does not close the mega menu due to ClickOutsideWrapper closing the mega menu before the click on the hamburger click handler is called, which then toggles it back.~ https://github.com/grafana/grafana/pull/52770 
- [x] ~Show user icon when not signed in~ (done by https://github.com/grafana/grafana/issues/53947)
- [x] #55723
- [x] #55553
- [x] #55555
- [x] #60962
- [x] ~Navigation: routes that don't render a `<Page>` don't show topnav~ not sure when it got fixed, but this is now fixed
- [x] #57276
- [x] #58236
- [x] #58228
- [x] #58230
- [x] https://github.com/grafana/grafana/issues/58700
- [x] ~Navigation: Plugin page alignment issues (e.g. k8s monitoring)~ fixed by https://github.com/grafana/grafana-k8s-plugin/pull/292

## Non-blocking bugs
- [ ] https://github.com/grafana/grafana/issues/58999
- [ ] https://github.com/grafana/grafana/issues/59056
- [ ] Navigation: Section nav is temporarily lost while plugin page loads
  - not sure how we could fix this... because the plugin is responsible for rendering the `<PluginPage>` (and therefore 'SectionNav') 🤔 
 
## Future-looking / UX-y things
- [x] #52267
- [x] #52268
- [x] #52270
- [x] #52276
- [x] #52281
- [x] #52284
- [x] #52285

## Pages
- [x] Dashboard
  - [x] Dasbboard toolbar actions (https://github.com/grafana/grafana/pull/51950)
  - [x] Dashbord settings (https://github.com/grafana/grafana/pull/52682)
  - [x] Dasbboard panel edit (https://github.com/grafana/grafana/pull/54746)
  - [x] Dashboard view panel
  - [x] #55116
  - [x] Rethink kiosk mode 
- [x] Dashboard section pages (Browse, Import, New folder, Folder pages, Library panels) https://github.com/grafana/grafana/pull/51666
- [x] #53970 
- [x] Teams (done by https://github.com/grafana/grafana/pull/51510)
- [x] #53575
- [x] #53576
- [x] #53578
- [x] #53579
- [x] Explore
  - [x] https://github.com/grafana/grafana/issues/54271
  - [x] #56269
- [x] Service accounts list page (https://github.com/grafana/grafana/pull/52425)
- [x] #53967 
- [x] #53968
- [x] Alerting 
  - [x] https://github.com/grafana/grafana/issues/54278
  - [x] #55109
  - [x] #55110
  - [x] #55111
  - [x] #55112
  - [x] #55113
- [x] User profile https://github.com/grafana/grafana/pull/51664
- [x] Reports list page
- [x] https://github.com/grafana/grafana/issues/54272
- [x] https://github.com/grafana/grafana/issues/54279
- [x] https://github.com/grafana/grafana/pull/55094
- [x] https://github.com/grafana/grafana/pull/55104
- [x] #55106
- [x] #55107
- [x] #55108
- [x] https://github.com/grafana/grafana/pull/55571

## Enterprise
- [x] https://github.com/grafana/grafana/issues/60052
  - Enterprise and OSS uses the addIndexDataHook to modify the nav tree, this is no longer working when topnav and new IA is used (as it is looking for child nodes that it cannot find).
https://github.com/grafana/grafana/blob/23956557d8c6a119b7de5be5c42024e29634d002/pkg/services/licensing/oss.go#L56

## Plugins
- [x] Synthetic monitoring
- [x] k8s monitoring
- [x] Connections (old Quick start) 
- [x] On Call
- [x] Incidents 
- [x] Mimir Enterprise 
- [x] Loki Enterprise 
- [x] Tempo Enterprise
- [x] k6
- [x] https://github.com/grafana/machine-learning/issues/2057
- [x] Others 

# Pages that could need design tweaks 
Maybe they lack a cancel button or have double titles 
* [x] #60959
* [x] New playlist
* [x] #60960
* [x] Change password 

# Update E2E tests 
* [x] #60901
  - When the feature toggle is to be enabled by default we will need to update a large number of e2e tests. If there is nothing ^ else to do we can start with this early and just not merge PR as this task could take a a while. 

# Pre-launch readiness checks
- [x] Fill out cloud readiness doc
  - https://docs.google.com/document/d/16uXLpN6ACi-x2SlzNGjNyPeD9iVEpgN9cVhmlBv_y5I/edit?usp=sharing

# Post-launch tasks
- [x] Navigation: Review feature rollout dashboard
  - https://ops.grafana-ops.net/d/5mFErDb7z/grafana-features-rollout-statuses?orgId=1

**Comment by torkelo** [comment]
Missing new page layout with new SectionNav component 
 
There are things here that are a bit related that we need to figure out.
* NavModel / NavModelItem , what should drive breadcrumbs, section nav & item navigation.
