### ISSUE TITLE
GLDS-Figma Clean-up — Epic

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#51049]
Figma Clean up Phases

Things to include:

- [x] File Structure — component per page
- [x] Component Naming — mirror Storybook
- [x] Remove side conversations and comments — mark as resolved
- [x] Component Status Indicator
- [x] Component Index
- [x] Introduction & Overview Page
- [x] Contribution Guidelines & Form
