### ISSUE TITLE
Saga DS - Metrics [epic]

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#51279]
In connection with the Platform UX efforts on the UE Team, we need to identify and plan for how we will be measuring design system performance and ROI for Grafana.

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/69135
- [ ] https://github.com/grafana/grafana/issues/84519
- [ ] https://github.com/grafana/grafana/issues/84518
- [ ] Use UXLite survey for designers/devs
- [ ] Add a button to saga so users can rate it (per page or for whole site)
- [ ] https://github.com/grafana/grafana/issues/84520
```

Possibilities to track:
- [ ] Imports of emotion (usage of CSS should decrease)
- [ ] Number of css properties used in emotion functions
- [ ] Usage of className in props
- [ ] Token usage vs not being used (i.e. places that use a custom borderRadius and not a token)

Planning File: [Measuring Design Systems at Grafana Labs](https://docs.google.com/document/d/1TvSpW6HqpLVHnCPFKXaWzrcsbiV35bRdaMYEdolU_ZM/edit?usp=sharing)

**Comment by joshhunt** [comment]
- Scan grafana codebase and grafana plugins from the registry (like levitate dashboard does)
 - Record:
   - Repo/project
   - File name
   - # of css properties used in emotion functions
     - need to catch both css objects and css tagged templates being used
   - time of scan

Being able to identify historical trends is important

**Comment by JoaoSilvaGrafana** [comment]
For inspiration, radius tracker project ran their component tracker against grafana and its plugins: https://observablehq.com/@smoogly/design-system-metrics
