### ISSUE TITLE
Alerting: Improve alert generator - receiver workflow

### ISSUE THREAD

**Issue by konrad147** [grafana/grafana#51425]
We would like to improve the connection between alert generators and alert receivers to enhance the alert rule creation and boost users' confidence that alerts work as expected

The list of tasks is not complete. These are the first steps in this journey
- [x] https://github.com/grafana/grafana/issues/51321
- [x] https://github.com/grafana/grafana/issues/49212
- [x] https://github.com/grafana/grafana/issues/51417
- [x] https://github.com/grafana/grafana/issues/51424
- [x] https://github.com/grafana/grafana/issues/45455
