### ISSUE TITLE
Command Palette Follow Up

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#51448]
Epic for keeping track of bugs/features/etc related to the command palette post release in Grafana 9

- [x] ~Add folder searching~ https://github.com/grafana/grafana/pull/62663
- [x] ~Automatically build navigation list ([src](https://raintank-corp.slack.com/archives/CPXKS6FB5/p1655804167175019))~ https://github.com/grafana/grafana/pull/58138
- [ ] Add most commonly used actions ([src](https://raintank-corp.slack.com/archives/C02TXB92G6T/p1655843124089549))
  - partially done by https://github.com/grafana/grafana/pull/58138 (added `New dashboard`/`New alert rule`)
- [ ] Add duplicate datasource like what was implemented for the hackathon ([src](https://raintank-corp.slack.com/archives/CPXKS6FB5/p1656433840815759))
- [x] #60032
- [x] #56840
- [x] #56885
- [x] Add documentation about what features are available ([src](https://raintank-corp.slack.com/archives/C02TXB92G6T/p1657189281200249)) https://github.com/grafana/grafana/issues/61095
- [x] ~Remove feature toggle~ https://github.com/grafana/grafana/pull/62698

**Comment by deathchurch** [comment]
For me the Command Palette doesn't work, on Windows 10 pressing Ctrl+K in Edge (103.0.1264.37), whilst on Grafana homepage, or any page does nothing. Running Grafana 9.0.1 on Windows Server, do you have to enable it in settings somewhere?

**Comment by gelicia** [comment]
@deathchurch nope - it should be enabled by default. One thing is it relies off some assumptions on what your path is, do you have `serve_from_sub_path` set to something (we know about this one), or any other configuration changes that alter the path (we tested in a variety of configurations but might have missed something)?

**Comment by deathchurch** [comment]
I do have Grafana running behind an IIS proxy, but the `serve_from_sub_path` is commented out.

**Comment by deathchurch** [comment]
@gelicia I have worked out what the issue was, my defaults.ini was not up to date, once I copied over the defaults.ini from the zip the Command Palette does now work. When I upgrade Grafana I copy everything from the zip apart from Conf and Data directories, this seems to be the issue, thanks for looking at your end.

**Comment by gelicia** [comment]
@deathchurch not a problem - thanks for investigating!
