### ISSUE TITLE
Migrate SQL datasources to react

### ISSUE THREAD

**Issue by oscarkilhed** [grafana/grafana#51476]
Our core SQL datasource plugins are still using angular, preventing the final removal of angular as a dependency.

Our intention is to use the SQL query builder built for google big query plugin to reduce the number of query builder implementations.

- [ ] Generalize the query builder in grafana experimental

We're also touching up the configuration pages in order to make them a bit more consistent.

- [x]  MySQL 
  - [x] Migrate raw query builder
  - [x] Migrate visual query builder
  - [x] https://github.com/grafana/grafana/issues/20504
  - [x] #54079

- [x] Postgres
  - [x] Migrate raw query builder
  - [x] Migrate visual query builder
  - [x] Migrate configuration page
  - [x] Update documentation https://github.com/grafana/grafana/pull/56011
    - [x] Aurora RDS [connection shows successful when connection attempt fails](https://github.com/grafana/support-escalations/issues/2944)
  
Related issues:  
- [ ] https://github.com/grafana/grafana/issues/50360

- [x] MSSQL
  - [x] Migrate raw query builder
  - [x] Migrate visual query builder
  - [x] https://github.com/grafana/grafana/issues/20505
  - [ ] Update documentation https://github.com/grafana/website/pull/10149

Other issues:
- [ ] https://github.com/grafana/grafana/issues/51283
- [ ] https://github.com/grafana/grafana/issues/43579
- [ ] #53053

**Comment by codeincarnate** [comment]
Going to close this one out now the Postgres has been merged and we can track elsewhere 🥳
