### ISSUE TITLE
Loki: Improved query patterns

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#52090]
Design: https://www.figma.com/file/YeTF07V4TUNydMJMD1DYBd/Query-builder-improvements?node-id=2441%3A19243

Tasks for Loki:
- [x] Rename `Label` to `Label filter` https://github.com/grafana/grafana/pull/53446
- [x] Rename `Query pattern` to `Kick start your query`
- [x] A warning modal appears if the user tries to select a pattern while having a working query
- [x] Add modal with sections called Logs and Metrics that expand to shows the query pattern card
- [ ] Red border over the Label and value sections to guide the user. https://github.com/grafana/grafana/pull/55751
- [x] Wording in the "FieldValidation" component changed to: Select a least label and value (stream selector) https://github.com/grafana/grafana/pull/53449
