### ISSUE TITLE
Explore: Convert SASS styling .elapsed-time, .logs-rows, .logs-meta-item__labels, .text-link, .label-slider, .slider, .muted, .space-between

### ISSUE THREAD

**Issue by L-M-K-B** [grafana/grafana#52155]
- [x] **elapsed-time** (public/sass/pages/_explore.scss L41, public/app/features/explore/Time.tsx L12) => styling n/a; has been removed
- [x] **logs-rows** (public/app/features/explore/LiveLogs.tsx L122, packages/grafana-ui/src/components/Logs/getLogRowStyles.ts L43-48) => styling n/a; has been removed
- [x] **logs-meta-item__labels** (public/app/features/explore/LogsMetaRow.tsx L110, Where is it defined?) => styling n/a; has been removed
- [x] **text-link** (public/app/features/explore/NoDataSourceCallToAction.tsx L25 + many others, defined in packages/grafana-ui/src/themes/GlobalStyles/elements.ts L143-145) => already converted to emotion
- [x] **label-slider** (public/app/features/explore/RichHistory/RichHistoryQueriesTab.tsx L41, 174, 175, 190) => transfer to own element
- [x] **slider** (public/app/features/explore/RichHistory/RichHistoryQueriesTab.tsx L58+L60+L178, RangeSlider.tsx L33, packages/grafana-ui/src/components/Slider/Slider.tsx L85, styles.ts L23-62 (?), public/app/core/components/OptionsUI/slider.tsx L96+L98) => transfer to own element
- [x] **muted** (packages/grafana-ui/src/themes/GlobalStyles/elements.ts L88-95)  => styling n/a; has been removed
- [x] **space-between** (public/app/features/explore/RichHistory/RichHistorySettingsTab.tsx L29-31, L81, L93, L104) => transfer to own element
