### ISSUE TITLE
Feature Tracking

### ISSUE THREAD

**Issue by L-M-K-B** [grafana/grafana#52231]
We want to track more UI interactions in Explore. 

## Preparation
- [x] #52232
- [x] List for Tracking Items (see annexe 2 in design doc)
## Implementation
- [x] Create a sheets file for documentation purposes (see [file](https://docs.google.com/spreadsheets/d/19zp0RFj-GCy_ZFhyURJoutgwN6NjI9eUs-7F8PHflrc/edit?usp=sharing))
- [x] Add items from annexe 2 to documentation
- [x] #54082
- [x] #54083
- [x] #54323
- [x] #56809

**Comment by grafanabot** [comment]
This issue was removed from the 9.1.0 milestone because 9.1.0 is currently being released.
