### ISSUE TITLE
Scenes: A new framework and runtime for dashboards (Epic)

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#52484]
The current DashboardModel, PanelModel, DashboardGrid, redux variable system, and TimeSrv have a very old legacy. They have many structural and architectural issues that make dynamic features, nesting, and extensibility very hard to implement. This is why we are persuing a new architecture built from the ground up to be able to support

* Deep nesting and easy composition
* Different layout systems including a new flex layout.
* Support time ranges, variables, and query runners on different levels of the scene object graph.
* Easy extensibility so that new element types can be added to a dashboard without changing the runtime.
* A runtime state (that includes query results) that can be serialized and cached in the frontend and shared in support tickets. This also makes it possible to move between dashboards without having to re-query everything.
* Efficient state updates and React re-rendering. State updates should only trigger render updates to relevant parts of the Scene
* Easy to test state model and state model + react with minimal setup 
* Support for cross-cutting concerns like Url sync and Undo/Redo
* Conditional display of panels/parts of the scene 
* Repeat panel or rows (nested scene) by series 
* More efficient and simpler way to repeat panels & rows by variable 
* A basis for programmatic dashboards (dashboards defined through code and that runs as the dashboard is shown) 
* Extensible dashboard framework and runtime that can be embedded and used from plugins 

### Initial starting point
* Initial POC PR: https://github.com/grafana/grafana/pull/50980 
* Improve typing: https://github.com/grafana/grafana/pull/52422
* Nested scene (to handle things like rows) https://github.com/grafana/grafana/pull/52367

### Model fundamentals  
* [ ] Support for serializing scene and deserializing 
* [ ] Support for a persisted state (that is can be different from the complete serialized state)
* [ ] Support for SceneObject default state (needs something like defaultProps that react class components have, but tricky from a Typescript perspective) 

## Systems

* [ ] URL State: Flesh out the URL sync system (just a starting point right now). The tricky bit of how to identify scene objects when needed. Say when you have two time ranges, multiples rows with collapse/open state that all need to be encoded in URL.
* [ ] Variables: Continue work on variable system 
* [ ] Conditions: A way to conditionally show a subtree. Based on conditions like time range, data state, and variable state. This could then be used for drilldowns, and other dynamic behaviors. 
* [ ] Query Runners
  * [ ] Support transformations
  * [ ] Support standalone transformations (a scene data node without queries but only transformations)
  * [ ] Support annotation queries  
* [ ] Editor 
  * [ ] Declarative options 
  * [ ] Queries??? 
  * [ ] UX?? 

### Components

* [ ] Make TimeRangePicker more complete (handle auto-refresh for example)  
* [ ] Add GridLayout to support the current dashboard layout system
* [ ] FlexLayout how to add lazy rendering of elemens outside viewport 
* [ ] Tabbed layout 

### Support old dashboard model 

* [ ] Initial test of loading dashboard json -> building a scene from it. What is missing? (A LOT)

### Existing Issues to keep in mind in the new model

- [ Panel automatically changing position](https://github.com/grafana/support-escalations/issues/3777)

**Comment by natellium** [comment]
We should keep this in mind within the scope of this epic https://github.com/grafana/grafana/issues/717
