### ISSUE TITLE
Epic: Storage - git the things

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#52916]
### Dashboards from storage
- [x] https://github.com/grafana/grafana/pull/51949
- [ ] Create a content root folder that should only contain dashboards https://github.com/grafana/grafana/issues/54866
- [ ] Include dashboards from content folder in search index.  Only at startup for now.
- [ ] Consider index per storage root (SQL is one of them)
- [ ] Render folder listing page with same components as search

### Store API:
- [x] Support git backend https://github.com/grafana/grafana/pull/52192
- [x] Implement PR and Push workflows for git backend
- [ ] Expose methods to list history depending on store backend

### Entity API
- [ ] https://github.com/grafana/grafana/pull/47849
- [ ] Define entity API protobuf definitions https://github.com/grafana/grafana-plugin-sdk-go/pull/527
- [ ] Implement the EntityAPI as a grafana service.  WIP: https://github.com/grafana/grafana/tree/entity-api
- [ ] Implement entity history with the git history APIs
- [ ] Expose the EntityAPI as a gRPC service.  Depends on https://github.com/grafana/grafana/pull/47849

### Git tools expertise
- [ ] Checkout a specific version of a file (in a multi-threaded environment)
- [ ] git history from a file
- [ ] list changes not it your local checkout

### Security + permissions
- [ ] Simple OSS prefix security: https://github.com/grafana/grafana/compare/path-authz
- [ ] Enterprise will extend this with custom rules, roles and permissions

### Exporter
- [ ] Update exporter to write to entity API rather than git commits directly

![image](https://user-images.githubusercontent.com/705951/181421832-5350adb9-24c1-4cd9-98fc-206f85c54205.png)

**Comment by torkelo** [comment]
> Render folder listing page with same components as search

What does this mean? 

Should that not be the other way around, support folder + card view in search?

**Comment by ryantxu** [comment]
Current path: https://github.com/grafana/grafana/pull/96329
