### ISSUE TITLE
Bring Prom streaming parser to parity and make default

### ISSUE THREAD

**Issue by evandandrea** [grafana/grafana#52926]
## Definition
We recently introduced a [new client](https://github.com/grafana/grafana/pull/48477) to the Prometheus plugin to simplify response processing and improve performance and memory consumption. After starting to use the new client, we are expecting performance improvements and less memory consumption. Before making a new client as default, we have to ensure it returns the same exact data as the old client. Below there are steps we should follow.

## A/C
- New client returns the same exact data as the buffered client (the old client) returns

## Fixes
Fixes https://github.com/grafana/grafana/issues/43369

## Steps
- [x] Fix the legend difference between buffered response and streaming response https://github.com/grafana/grafana/pull/55941
- [x] Add exemplar sampling to the new client https://github.com/grafana/grafana/pull/56049
- [x] Fix Exemplar sampling difference between old and new client https://github.com/grafana/grafana/pull/56049
- [x] Make streaming client (querydata) as default client https://github.com/grafana/grafana/pull/58365
- [ ] Prometheus: Remove old client (`buffered`) https://github.com/grafana/grafana/pull/59898

## Roadmap
v9.2: New client flag is there, should be feature complete, we encourage people to use it
v9.3: New client is default, flag to use old. Old client deprecated, no changes
v9.4: Delete old client (Feb)
https://raintank-corp.slack.com/archives/C03FZ9T50R1/p1665073148493249

We are moving this out of Q3 and potentially Q1 of 2023

**Comment by evandandrea** [comment]
- Dedicating some, not complete capacity to this.
- In information gathering phase. Found an unfinished task related to this (#52738). Digging to see if there's anything more related to this.
- This and 52738 may actually be better combined into an epic. Let's do that. Ismail will migrate these into an epic.

**Comment by itsmylife** [comment]
Fix the legend in stream parser client: https://github.com/grafana/grafana/pull/55941

**Comment by gtk-grafana** [comment]
@itsmylife can we update the description for this to make it more specific to the q4 requirements?
