### ISSUE TITLE
Time picker should warn for values in the future

### ISSUE THREAD

**Issue by AndiDog** [grafana/grafana#53719]
**Why is this component needed**:

When people enter From/To from an incident timeline or customer e-mails and chats, they often fail because their timezone settings do not match, customer/colleague did not provide the correct timezone, etc. To avoid very basic mistakes, Grafana should hint if a value is in the future, since metrics and other displayable data is typically from the past.

**Where is/could it be used?**:

I developed a draft for use in the main time picker of Grafana (dashboards/explore). See this screenshot and the PR which I will attach to this issue.

<img width="664" alt="Warning-styled alert showing that time value is in future" src="https://user-images.githubusercontent.com/1376043/184556900-ac1ba636-a846-4a51-a292-047d8fce32af.png">

**Implementation** (Checklist meant for the person implementing the component)

- [?] Component has a story in Storybook.
- [?] Props and naming follows [our style guide](https://github.com/grafana/grafana/blob/main/contribute/style-guides/frontend.md).
- [?] It is extendable (rest props are spread, styles with className work, and so on).
- [x] Uses [theme for spacing, colors, and so on](https://github.com/grafana/grafana/blob/main/contribute/style-guides/themes.md).
- [x] Works with both light and dark theme.

**Documentation**

- [ ] Properties are documented.
- [ ] Use cases are described.
- [ ] Code examples for the different use cases.
- [ ] Dos and don'ts.
- [ ] Styling guidelines, specific color usage (if applicable).

**Comment by JoaoSilvaGrafana** [comment]
Hey @AndiDog unfortunately we won't have time to prioritise this issue anytime soon. We think there should be a more subtle option for information boxes for cases like this. We will keep this in mind when we do work on input components with designers again, but for the moment we will have to close this issue.
