### ISSUE TITLE
GLDS- Layout Component Documentation — Epic

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#53977]
Identify the page layouts used across Grafana to begin the work to unify pages against layout templates

**Resources**
- [Figma File](https://www.figma.com/file/zuUV7VU8wqhXEK1S3GXbTQ/Layout-Component?node-id=1%3A32)
- [Documentation](https://docs.google.com/document/d/1T2oJBCRoYdd1EMOSq0lw1mDM_FcedqFiYRdP8lW9sIM/edit?usp=sharing)

**Next Steps**

- [ ] [Documentation on button position by layout type](https://github.com/grafana/grafana/issues/53977#issue-1344806401)
- [ ] Call out key differences by layout types
- [ ] Use cases with Grafana examples
- [ ] [stretch] Flexibilities — what can we do with each type?

**Comment by staton-hyse11** [comment]
I don't think this work is something we still want to do. I'll close this issue and if the topic comes up in the future we will create new.
