### ISSUE TITLE
Update XY Chart to bring status from Alpha to Beta 

### ISSUE THREAD

**Issue by codeincarnate** [grafana/grafana#54192]
We're prepping to get the XY Chart (scatter plot) ready for a beta release. Tracking tasks here and will expand as further work is done.

- [x] Fix prepScatter issue on no data
- [x] Set default mode
- [x] Update mode names
- [x] Toggling between XY/Explicit adds redundant form elements
- [ ] Switch to mode 2 rendering in uPlot to allow for unordered data
- [x] Determine what should be done on zoom
- [x] https://github.com/grafana/grafana/issues/44712
- [ ] Update status from Alpha to Beta

**Comment by mdvictor** [comment]
Additionally, I would say tooltip and legend options being functional, alongside custom options that currently don't work (e.g: point size)

**Comment by mdvictor** [comment]
Determining what should be done on zoom will be discussed further but is not a priority for the beta release.

**Comment by codeincarnate** [comment]
There is an open question of what we should do regarding annotations. We may want to want for a later beta to do it though. I think there may be code written to support annotations for the barchart that could make it work but I'm not 100% sure.

**Comment by mdvictor** [comment]
From what I've seen the annotations work on timeseries because this is what the API when saving/retrieving them from storage. I might be wrong but I did not find any non-timeseries panel that works with annotations.

Another argument as to leave this for later is that there are other panels that do not have annotations functionality (e.g: heatmap, status history, bar chart)

Imo this is not a priority for the beta.

**Comment by codeincarnate** [comment]
I've given some more thought to annotations and completely agree. I think they're important but a big and key change there is that it would be moving from 1D (linear) annotations to 2D (area) annotations. I'm sure the behavior will have to be different (i.e. how do we treat intersected annotations) so something to keep on the radar.

**Comment by codeincarnate** [comment]
Another thing I'm not sure about, I think "Centered Zero" here doesn't make sense necessarily (unless we're trying to center in both x and y perhaps). I suppose it's a bit of a philosophical question but probably worth discussing how it would work. This would presumably effect any higher dimensions visualizations as well.

**Comment by mdvictor** [comment]
PR has been merged. We should be all good to bump this up to a beta!

**Comment by leeoniya** [comment]
a few observations...

should Mode option be renamed to something like Field mapping or Dimension mapping or Mapping mode or Series defs? the current naming provides no useful information with all terms being kind of generic (Mode: Auto / Manual), like...auto/manual _what_?

should we rename the `point` option to something better, like `showPoints` like in TimeSeries?

also not sure about whether `line` can be anything other than Linear. _maybe_ it can be smooth though that seems odd, and how would you draw a stepped line between points in e.g. a smiley face? i'm tempted to ditch the "interpolation" aspect and just leave it as a `showLines: true`, and we can add line interpolation as another option in the future if needed, same as we have in TimeSeries?

![image](https://user-images.githubusercontent.com/43234/189274332-2bdc5202-b704-458f-8168-215ab75582b3.png)

setting points to "Never" auto-enables the line, which is maybe okay, but the line option doesnt reflect that it's now enabled. not sure if we should just remove the magic for now and make users enable the line explicitly? we can also have a mode that controls both points and line visibility via `Show: points / line / points-line`, that way users dont have to screw around with various Never combos and we dont need any magic auto-enabling.

![image](https://user-images.githubusercontent.com/43234/189274193-416714fc-6068-4f56-bfb7-4a227f7e3c20.png)

the tooltip is a bit strange. it would probably be less confusing if we ditched the custom item with the color line and just rendered a label in front of each facet like:

```
Lat: 36.7
Price: 250
...+ other facets in Manual mode (point size field, point color field)
```

![image](https://user-images.githubusercontent.com/43234/189276812-0d9c3627-0063-4c31-bac4-a334d6669098.png)

**Comment by mdvictor** [comment]
Hey @leeoniya . This is great feedback. I agree with the modifications, work is still in progress with them due to the new Grafana version releases. What I don't fully understand is what you mean by the last point regarding the legend. Can you please explain that part?

**Comment by mdvictor** [comment]
Writing this down for posterity: Another improvement is to add line style per series (in manual mode at least) so that a user can select each series what line style he desires

**Comment by mdvictor** [comment]
Latest updates have been merged. Are we ready to bump this to a new beta version?

**Comment by leeoniya** [comment]
let's do it :+1:

**Comment by imReker** [comment]
@mdvictor 
Series mapping can't recognize string column(if data is in table format), any chance to support?
![image](https://user-images.githubusercontent.com/4949937/196436735-65e40d62-5c35-4ea8-97c8-b97a0c7f0bd1.png)
![image](https://user-images.githubusercontent.com/4949937/196437872-b9891bb1-432a-414e-bad0-10b3c23dd08f.png)

**Comment by leeoniya** [comment]
@imReker are you asking to show the `name` column in the tooltip, or something else?

**Comment by leeoniya** [comment]
> Yes, that's what I want. Show all string fields in the tooltip so I can identify them

will track in https://github.com/grafana/grafana/issues/57221

> (maybe show name above the chart points is better).

this is more involved: https://github.com/grafana/grafana/issues/57222

**Comment by yulipumal** [comment]
@codeincarnate, please consider for Beta also this tooltip issue https://github.com/grafana/grafana/issues/65042 (duplicate: https://github.com/grafana/grafana/issues/57221)
