### ISSUE TITLE
Explore: Mixed Datasource followup

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#54533]
This ticket addresses things brought up in the [PR](https://github.com/grafana/grafana/pull/53429) or elsewhere that we need to address in order to make mixed datasource in explore generally available.

[Definition of Done review](https://docs.google.com/document/d/1QRXdgI6spLHiskbQGNWr1wEhIROk2MwNcAsXC5ZaWm4/)

```[tasklist]
- [x] #61089
- [ ] #61546
- [ ] #65360
- [x] Complete [DoD](https://docs.google.com/document/d/1QRXdgI6spLHiskbQGNWr1wEhIROk2MwNcAsXC5ZaWm4/)
- [x] change feature toggle to beta
- [ ] https://github.com/grafana/deployment_tools/pull/67790
- [x] Complete "what's New" for 10.0
- [x] make stable & enable feature flag by default
- [ ] #52417
- [x] Discuss how log volume should be aggregated in the future (https://github.com/grafana/grafana/pull/63036#pullrequestreview-1328087859) (fixed by https://github.com/grafana/grafana/pull/65392)
```

In the future we may consider adding more tracking to this feature, e.g. how log volume is being displayed (more details in https://github.com/grafana/grafana/pull/63036#issuecomment-1455388321)

**Comment by gelicia** [comment]
Design doc : https://docs.google.com/document/d/157JpbakX2W0dE7pyKJleFhpkUKCUTntg1dyezU_3jS0/edit#

**Comment by meanmina** [comment]
Does https://github.com/grafana/grafana/issues/57359 block us from removing the feature flag? If yes, we should include this in the epic task list above.
