### ISSUE TITLE
Help: Add help wizard to panel menu

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#55005]
In 9.2, we will release a new feature that lets people easily create a message they should include in support requests, or paste into github issues.  This system creates a dashboard we can load to help diagnose and reproduce visualization issues.

![2022-09-09_13-45-02 (1)](https://user-images.githubusercontent.com/705951/189445231-deb6b6f2-3207-49cc-a240-659bf8941271.gif)

Docs TODO:
- [x] #55170 Add information in documentation
- [ ] Update github issue templates to point to the docs above
- [x] Release blogpost?

Tech TODO:
- [x] https://github.com/grafana/grafana/pull/55059
- [x] https://github.com/grafana/grafana/pull/53998 will support showing data before and after transformation.  It will also let us show annotation data without duplicating it explicitly
- [ ] UX for the randomize buttons
- [x] Show field type icons in table view

https://github.com/grafana/grafana/issues/55005#tasklist-block-c7e5bb20-9f39-4ae0-bbf4-9c0b4da5da6e

**Comment by grafanabot** [comment]
This issue was removed from the 9.2.0 milestone because 9.2.0 is currently being released.
