### ISSUE TITLE
Glue: Generic Data Links (GA)

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#55236]
Feature toggle:

```
[feature_toggles]
correlations = true
```

[Design doc](https://docs.google.com/document/d/1f4vVhocXiZ-34yW18gnoyR40NgA2b0Zw4SmSv5MvEnY/edit)
[Project roadmap](https://github.com/orgs/grafana/projects/111/views/33)
[Delivery Plan](https://docs.google.com/document/d/13deKHd9CoN6ZzHEzVzjfhfyj615HgSDAo4DVHM4yqVI)

Replaces: #29417

**Every task implies adding docs/related material when appropriate**

<details><summary>(✅ Done) Stage 1: Add static links to query results (9.4)</summary>

### Stage 1
```[tasklist]
- [x] #55368
- [x] #56682
- [x] #55369
- [x] #55370
- [x] #55625
```
</details>

<details><summary>(✅ Done) Stage 2: (2022 Q4) Add dynamic links to query results |(9.5)</summary>

### Stage 2: (🚧 2022 Q4) Add dynamic links to query results |(9.5)

```[tasklist]
- [x] #58235
- [x] #58574
- [x] #60023
- [x] #61029
- [x] #61030
- [x] #61033
- [x] #59583
- [x] #61782
```
</details>

<details><summary>(✅ Done) Stage 3:  (2023 Q1) Correlations Editor and UX improvements (10.0)</summary>

```[tasklist]
- [x] Create an FRR: https://docs.google.com/document/d/1-OTyd8KizDDxM9pR-cna1LB7fEcvu7XgXoP181GJIsQ
- [ ] #55371
- [ ] #62100
- [ ] #63559
- [ ] #64144
- [x] #63955
- [ ] #64157
- [ ] #65536 
```
</details>

<details><summary>(✅ Done) Stage 4:  )2023 Q2 & Q3) Post *Preview* improvements</summary>

```[tasklist]
- [ ] #62462
- [ ] #60692
- [ ] #58441
- [ ] #65773
- [ ] https://github.com/grafana/grafana/issues/71110
- [ ] https://github.com/grafana/grafana/issues/71511
- [ ] https://github.com/grafana/grafana/issues/70684
- [ ] https://github.com/grafana/grafana/issues/71535
- [ ] https://github.com/grafana/grafana/issues/71536
- [ ] https://github.com/grafana/grafana/issues/64144
- [ ] https://github.com/grafana/grafana/issues/68254
- [ ] https://github.com/grafana/grafana/issues/75832
- [ ] https://github.com/grafana/grafana/issues/76260
```
</details>
