### ISSUE TITLE
Glue: UX for Correlation Editor

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#55371]
Requirements:

Correlations editor should be implemented as step-by-step wizards with following steps on separate pages:
Step 1: Define **label** and **description** for the correlations
Step 2: Define **target data source** and **target query**
Step 3: Define **source data source**, **select a sample**, **select target field**, and **map variables** + **validate the query**

All elements are read-only if the opened correlation is provisioned.

```[tasklist]
### Tasks
- [x] Discuss proposals 1 & 2 and pick one for clickable mock-up
- [x] Create a clickable mock-up
- [x] Test selected proposal
- [x] Create list of pain points and improve the proposal
- [x] Define tasks to create the query editor
- [x] https://github.com/grafana/grafana/issues/60957
- [x] https://github.com/grafana/grafana/issues/60958
- [ ] https://github.com/grafana/grafana/issues/62095
- [x] https://github.com/grafana/grafana/issues/60967
- [x] https://github.com/grafana/grafana/issues/60966
```

Notes: table with the results preview may require showing multiple tables. For example "exemplars" query will return 2 data frames with different structures, example: https://gist.github.com/ifrost/dba22e95374843f9f4bc7faba8f975d0

<details><summary>Proposal 1 (rejected)</summary>

A rough idea on how UI could look like:
![image](https://user-images.githubusercontent.com/1170767/191000575-01320167-8962-48db-ac6e-680b4ed70a76.png)

Given how we are breaking down implementation, we could split the UX work in the following steps:

### 1. Add static links to query results
Correlations need to specify on which field from the original result they need to be attached and which query to run. (see https://github.com/grafana/grafana/issues/55369)

### 2. variables preview
users may choose to run an example query against the source datasource to help with configuring the correlation, they may want to select a single result from the result set, and we may want to help them understanding which variables are available in their query
![image](https://user-images.githubusercontent.com/1170767/191002105-162e2dce-1ad7-4a10-9652-8fc46e02c3d2.png)

### 3. Transformation editor
TBD

</details>

<details><summary>Proposal 2 (approved)</summary>

Guided step-by-step wizard

![image](https://user-images.githubusercontent.com/745532/204555226-d6cd10cd-f6a8-4c44-80f5-38a23a361034.png)

https://user-images.githubusercontent.com/745532/210546961-a04ee759-5cfd-4985-987c-a30b3c27fe16.mov

Updated version:

https://user-images.githubusercontent.com/745532/210558105-69e91841-d048-4594-9ea7-b7e68139d289.mov

</details>

Correlations Editor mock-up: https://github.com/grafana/grafana/tree/ifrost/correlations-editor-mock-up
