### ISSUE TITLE
GLDS- Create a new Figma Library for Icons — EPIC

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#55411]
--Research--
- [x] Interviews for users to take their insights and experience using icons from our GLDS
- Amy
- Vesna
- Niat
- Pauric
- Nadine
- Lukasz
- Joao
- Ivanna
- [x] Analysis from Users Interviews
[Research Link](https://miro.com/app/board/uXjVPOIIGm4=/?share_link_id=295672985016)

--Tasks--
  

- [x] Create [EPIC issue ](https://github.com/grafana/grafana/issues/56941)in Github to align Storybook and Figma
   There are current efforts to refactor how icons are used across the product and we’ll actively work to keep Figma, Storybook and Product in sync through out this work 

- [x] Draft guidelines on how to submit new icons, where to look
   Concise guidelines on where new icons can be sourced and how to get them added in Figma/Storybook 

- [x] What size to use when
   Documenting proper times to use which size 

- [x] Workshop for organising icons 
   Card sorting

**Comment by natydej** [comment]
[https://docs.google.com/document/d/1Qwj58MLhgoIuFZw17vbOa0zmWRnWkxxBVS3gTpHyeFU/edit#](url)
