### ISSUE TITLE
Plugins: Breaking changes in Grafana v10

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#55605]
This issue should be used to keep track of API changes we want to introduce in Grafana 10. It can be things that is deprecated and should be removed or API changes that we shouldn't do in minor versions. It's both about keeping track of what breaking changes we did, so we can add migration docs for them, and also keeping track of what we would like to still do in this upcoming major version.

[See full list of breaking changes (merged PRs) for Grafana v10 →](https://github.com/grafana/grafana/pulls?q=is%3Apr+is%3Aclosed+milestone%3A10.0.0+label%3A%22breaking+change%22)

### Migration docs for breaking changes in v10
These are the list of breaking changes we think we should add migration docs for. Please feel free to extend the list.

```[tasklist]
### Tasks
- [x] Add migration docs for https://github.com/grafana/grafana/pull/64786
- [x] Add migration docs for https://github.com/grafana/grafana/issues/66480
```

### Planned breaking API changes before v10
These are the things that we are planning to do, feel free to pick them up or to extend the list.

```[tasklist]
### Tasks
- [ ] Introduce a different FieldConfigSettings for the options UI that handles multiple stings so we can e.g. pass testId for each instance. (https://github.com/grafana/grafana/blob/main/public/app/core/components/OptionsUI/strings.tsx)
```
