### ISSUE TITLE
Improve Explore state management

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#55812]
Explore state management has currently some issues that are both slowing us down and being the source of a few bugs.

In https://docs.google.com/document/d/15OR65nvWtbeCFOe3shS0cOWbux1BFXxx00TdVbXobbA/edit# we are exploring possible solutions to make make URL and state management a more robust and introduce strong URL schema versioning and migrations. 

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/pull/66117
- [ ] https://github.com/grafana/grafana/pull/66286
- [ ] Explore URL migrations (based on https://docs.google.com/document/d/17yLg7Mok3OWfozCgOegxbjSFBdlIIQbywb75mxcsrVw/edit#heading=h.5sybau7waq2q)
```
