### ISSUE TITLE
[Meta] Toolkit: Deprecate and remove plugin-building and creation-related commands

### ISSUE THREAD

**Issue by academo** [grafana/grafana#55997]
```[tasklist]
### For Grafana 9.x:
- [x] https://github.com/grafana/grafana/issues/55996
- [x] https://github.com/grafana/grafana/issues/56001
- [x] https://github.com/grafana/grafana/issues/56028
- [x] https://github.com/grafana/grafana/issues/56112
- [x] https://github.com/grafana/grafana/issues/57061
- [x] https://github.com/grafana/grafana/issues/56005
- [x] Toolkit: Deprecate `plugin:create` command in favor of `@grafana/create-plugin`
- [x] https://github.com/grafana/grafana/issues/57244
- [x] https://github.com/grafana/grafana/issues/60287
- [x] https://github.com/grafana/grafana/issues/60288
- [x] https://github.com/grafana/grafana/issues/60289
- [x] Toolkit: Deprecate `plugin:ci-build` command
- [x] Toolkit: Deprecate `plugin:ci-package` command
- [x] Toolkit: Deprecate `plugin:ci-report` command
- [x] https://github.com/grafana/grafana/issues/57721
- [x] https://github.com/grafana/grafana/issues/56008
- [x] https://github.com/grafana/grafana/issues/56015
- [x] https://github.com/grafana/grafana/issues/56027
- [x] https://github.com/grafana/grafana/issues/57677
- [x] https://github.com/grafana/grafana/issues/57727
- [x] Update readme of toolkit to say that it is now deprecated (https://www.npmjs.com/package/@grafana/toolkit
- [x] See where we use it in our pipeline and update it - grabpl?
- [ ] https://github.com/grafana/grafana/issues/67214
```

```[tasklist]
### For Grafana 10
- [x] https://github.com/grafana/grafana/issues/55998
- [ ] https://github.com/grafana/grafana/issues/57752
- [x] https://github.com/grafana/grafana/issues/56018
- [ ] https://github.com/grafana/grafana/issues/67121
- [ ] https://github.com/grafana/grafana/issues/67122
- [ ] https://github.com/grafana/grafana/issues/67127
- [ ] https://github.com/grafana/grafana/issues/67181
- [ ] https://github.com/grafana/grafana/issues/67182
- [ ] https://github.com/grafana/grafana/issues/67183
- [ ] https://github.com/grafana/grafana/issues/67132
- [x] Toolkit: Remove `plugin:bundle-managed` command
- [ ] https://github.com/grafana/grafana/issues/57660
- [ ] https://github.com/grafana/grafana/issues/57750
- [ ] https://github.com/grafana/grafana/issues/67472
```

**Comment by grafanabot** [comment]
This issue was removed from the 9.3.0-beta1 milestone because 9.3.0-beta1 is currently being released.

**Comment by useEffects** [comment]
This is just bad, for our enterprise apps we are still using version grafana 8.x, migration is just not possible for us

**Comment by academo** [comment]
> This is just bad, for our enterprise apps we are still using version grafana 8.x, migration is just not possible for us

@useEffects You can keep using the already published working versions of toolkit v9.x.x which are available via NPM. those versions will continue working. This deprecation and now removal simply means we won't be publishing any more updates or support to `@grafana/toolkit` and all new plugins should use create-plugin.

I should mention you can definitely build plugins for Grafana 8 (we have tested it) using our new [tooling](https://github.com/grafana/plugin-tools/tree/main/packages/create-plugin) as long as they are not angular plugins. You can see our guide here on how to migrate your plugin https://grafana.com/developers/plugin-tools/migration-guides/migrate-from-toolkit
