### ISSUE TITLE
[Epic - Panels]: Implement new Panel Chrome (Header and Menu)

### ISSUE THREAD

**Issue by axelavargas** [grafana/grafana#56163]
With the design explorations done in this [issue](https://github.com/grafana/grafana/issues/31080), we can begin the implementation of the new panel header; initially, everything goes behind a feature flag due to complicated parts that need more iterations.

The design here: [panel header latest decisions](https://www.figma.com/file/jdTCXlq75p55itRRSaerFx/Panel-header-and-menu?node-id=2672%3A235&t=ZN8EBdyt0FTXhSFA-0)

---
##### (Use `PanelChrome` in `PanelStateWrapper` behind feature flag `newPanelChromeUI`)
- [x] #59083 [_Done_](https://github.com/grafana/grafana/pull/60147)
- [x] #59080 [_Done_](https://github.com/grafana/grafana/pull/60514)
- [x] #59085 [_Done_](https://github.com/grafana/grafana/pull/60537)
- [x] https://github.com/grafana/grafana/pull/61399
- [x] #61554 [_Done_](https://github.com/grafana/grafana/pull/61595)
- [x] #61552 _Done_
- [x] #61660 [_Done_](https://github.com/grafana/grafana/pull/61695)
- [x] #61661 _In Progress_
- [x] [PanelChrome: Allow panel to be dragged if set as draggable from the outside](https://github.com/grafana/grafana/pull/61698) --- Done
----- Aiming for this but it will depend on the complexity of the headerless panel
- [x] #59078 @kaydelaney [_Done_](https://github.com/grafana/grafana/pull/61774)

### TODO for 9.4.0  (Before release -- focus should be on bug fixing)
- [x] #61550 [_Done_](https://github.com/grafana/grafana/pull/61757)
- [x] https://github.com/grafana/grafana/pull/62466

### TODO after the 9.4 release 
- [ ] #59082
- [ ] #61553 --- In progress https://github.com/grafana/grafana/pull/63040
- [ ] #61569
- [x] #61548
- [x] #61547
- [ ] #61597
- [ ] Prevent menu opening from embedded panels
- [ ] #59079 

### TODO future: Require input from UX 
- [x] #60672 ---- Rethinking loading states?

### TODO for 10.0.0
- [ ] #59398

<details>
<summary>Done:</summary>

- [x] #56396 ![image](https://user-images.githubusercontent.com/13227501/194278794-a5adff12-aec9-4ef1-adc2-c60f6244713b.png) #56450 
- [x] Implement  component POC .
	- [x] Create the new layout based on the design when panels have a title (title to the left, menu shown on hover/focus, etc..)
		- [x] #56644 -- @axelavargas 
		- [x] #56451 --- @polibb https://github.com/grafana/grafana/pull/57203
</details>

---
#### Existing issues

- [ ] https://github.com/grafana/grafana/issues/25930
- [ ] https://github.com/grafana/grafana/issues/56526

---
<details> 
<summary> Discussed Topics History </summary> 
Future-looking / UX-y things

- [x] Streaming interactions and status loading: With the current design we have a problem with table panels viz with the streaming interactions and status loading interactions (see screenshot), we are exploring a better way to handle this scenarios.
![image](https://user-images.githubusercontent.com/239999/193791473-16704824-a5c8-4f29-bdb6-749959f180a5.png)

- [x] DragNDrop Zone: should we _always_ leave some empty space for it between the icons and the states in the header, or rely on the title not being actionable and using it for DnD as well?
![image](https://user-images.githubusercontent.com/13227501/202519354-54a52492-f93a-49ee-8749-5f775007bcf1.png)
Discussed by @dprokop in PR #57203 :

> When it comes to the ability of dragging a panel, I don't think the PanelChrome should have knowledge about the `dragClass` - as the dragging mechanism can change in the future and not rely on the class name, and the property would not be needed anymore.
> 
> I think we have two options here:
> 1. Give full control of the drag handle to the consumer of PanelChrome - let him/her provide the drag handle via `titleItems` array - looking at the design that's exactly what the drag handle is.
> 2. Instead of `dragClass` have a property `dragHandle: ReactNode` that explicitly requires a react element to be passed by the consumer.
> 
> IMO the second option is the most optimal and makes the PanelChrome possible to use with any kind of dnd mechanism.

- [x] How will the DragNDrop happen when no header is set at all? For example,
![image](https://user-images.githubusercontent.com/13227501/202519471-f85e7e1d-f64f-4ddb-b032-71e899adaaeb.png)
- [x] If it happens that too many icons are passed from the outside taking up the whole space in the header: should we allow for inner scrolling of the set of items placed together? Here a `title` is passed together with [`titleItems[]`](https://github.com/grafana/grafana/pull/57203), but because the `titleItems` are too many they cover the whole space:
![image](https://user-images.githubusercontent.com/13227501/202519872-75a9aa72-9bbe-4ce1-8610-c5b841d201a8.png)

#### To Discuss, some form is already implemented:

- [x] Which items always cause a header to exist? (Regardless of whether it is a fixed header or a header that shows on hover). For now the following always create a header for the `PanelChrome`: 
  - [x] Only a `title`.
![image](https://user-images.githubusercontent.com/13227501/203070257-cf4a922e-cd1f-4c6f-88fc-3babf9efb606.png)
  - [x] Only `titleItems`.
![image](https://user-images.githubusercontent.com/13227501/203070301-cefeb3da-ba93-4ee0-b02c-435549884f11.png)
  - [x] Only a `menu`.
![image](https://user-images.githubusercontent.com/13227501/203070359-12bb8952-f80e-47d4-87d2-31a8054e7d72.png)
  - [x] Any combination of the above.
  - [x] Do we allow hoverable header to be without a `title` or `titleItems` (icons)? It could have only a `menu` with `hoverHeader = true`, then it would be hoverable header with a drag-n-drop icon and a menu icon next to it.
- [x] show-on-hover icons (`menu`) should move the rest of the layout to show up or should their space be reserved? Right now the space is reserved, the icon is only `visibility: hidden`. 
![image](https://user-images.githubusercontent.com/13227501/202520009-dcabe5f9-f814-4ee9-b3da-78d6ccc8d211.png)
![image](https://user-images.githubusercontent.com/13227501/202520032-4618978d-5013-4eaf-a798-afe93d42d370.png)
</details>

---
###  Before GA

- [ ] Write documentation

**Comment by torkelo** [comment]
@axelavargas important that this is done as a continuation on the component grafana/ui component PanelChrome (and work needed to so that this component is used by the core PanelChrome component)

https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/PanelChrome/PanelChrome.tsx  

There is also this issue: 
https://github.com/grafana/grafana/issues/31080  (maybe can be deleted and replaced by this issue)

**Comment by torkelo** [comment]
Part of this work could also be renaming the current PanelChrome component we are using in core to something like "PanelStateWrapper" or something, so as to not confuse it with the PanelChrome (in grafana/ui)

**Comment by axelavargas** [comment]
🤔 @torkelo to verify that I got it right:

- we will implement the new layout in the `PanelChrome` in the grafana UI
- Rename PanelChrome from core grafana to something sensible (i.e PanelStateWrapper or similar)
- Use the feature flag to use the newer PanelChrome

Is this correct?

**Comment by torkelo** [comment]
@axelavargas yepp!

**Comment by axelavargas** [comment]
The first iteration is completed ✔️ 🥳 . Closing this epic in favor of https://github.com/grafana/grafana/issues/63093
