### ISSUE TITLE
Epic: Table Panel Enhancements

### ISSUE THREAD

**Issue by codeincarnate** [grafana/grafana#56220]
There are a number of ongoing efforts to make improvements to the table panel. This issue is going t be used to track those.

### Tasks
- [ ] https://github.com/grafana/grafana/issues/56884
- [x] https://github.com/grafana/athena-datasource/issues/167
- [x] https://github.com/grafana/grafana/pull/53768
- [x] https://github.com/grafana/grafana/issues/31315
- [x] https://github.com/grafana/grafana/issues/40925
- [x] https://github.com/grafana/grafana/issues/45442
- [x] https://github.com/grafana/grafana/issues/11418
- [x] https://github.com/grafana/grafana/pull/59363
- [x] https://github.com/grafana/grafana/pull/63182
- [ ] https://github.com/grafana/grafana/issues/59474
- [ ] https://github.com/grafana/grafana/issues/61259
- [x] https://github.com/grafana/grafana/issues/25623
- [ ] https://github.com/grafana/grafana/issues/24482
- [x] https://github.com/grafana/grafana/issues/8017
- [x] https://github.com/grafana/grafana/issues/64308
- [ ] https://github.com/grafana/grafana/issues/64913
- [x] https://github.com/grafana/grafana/issues/71863
- [x] https://github.com/grafana/grafana/issues/71902
- [x] https://github.com/grafana/grafana/issues/7310
- [ ] https://github.com/grafana/grafana/issues/24901
- [ ] https://github.com/grafana/grafana/issues/65312
- [x] https://github.com/grafana/grafana/issues/80235

**Comment by codeincarnate** [comment]
Checking off annotations support as this was added directly to the dashboard data source in #53998. That being said that change isn't documented to my knowledge plus looks like it could use a little cleanup.

**Comment by baldm0mma** [comment]
@joshhunt also has a possible enhancement mentioned [here](https://raintank-corp.slack.com/archives/C023A30M3S7/p1685462867301379) that could possibly fit into this epic. @codeincarnate thoughts?

**Comment by yulipumal** [comment]
Any news on the cell style to show sanitized HTML? #2448

**Comment by codeincarnate** [comment]
We're currently considering approaches on a sanitized HTML cell. The crux of things at the moment is that security requirements have generally gotten more stringent and safely sanitizing HTML input can be a huge task. So we're currently trying to figure out a way to hopefully meet that bar.

We're happy for any feedback here to better understand use cases! We're hoping to avoid general HTML content as it's not great in terms of security (or usability for many folks). Our ability to add cell types is also much more flexible, so we could also potentially provide cell types to meet more pressing needs that don't need general HTML entry.

**Comment by yulipumal** [comment]
Thanks @codeincarnate, that are good news!

My most urgent application would be to display an image of any size. This would mean that an image with fixed width and height would have to adjust the table row height. Currently, the possibility to show images via cell type "Image" with three adjustable row heights (sm, md, lg) is too rigid. With the previous table panel, it was possible 
This does not necessarily require html in general, as you said a specific cell type would be fine.

**Comment by NielKemp** [comment]
I Don't know if the is the right place to add this, but I'm currently at my wits end with trying to use the table viz type in Grafana, an HTML sanitization would've been a great fix. 

All I want to do is be able to change the font size of the content of my table Vizualization, as well as the column headers. I'm on V9.5 and there is no obvious way to do this besides HTML.

**Comment by baldm0mma** [comment]
Hey @NielKemp , I'm sorry about your frustration, I know exactly how you feel. We are planning to invest some significant effort into the Table component this quarter, and will be working diligently to communicate those upgrades. We'll keep you updated when we know more.

**Comment by yulipumal** [comment]
Thank you very much for your work on this table panel issue @codeincarnate @baldm0mma. 

Is there any update on the cell style to show sanitized HTML? #24482 And what is our opinion on PR #68326

**Comment by natellium** [comment]
👋 We're continuing to work on the table panel but won't be using this issue for tracking. If you wanna follow the progress, please review the individual issues :)
