### ISSUE TITLE
I18n: Migrate to I18next

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#56303]
The outcome from the work done on https://github.com/grafana/grafana/pull/55300 was that we want to switch to a translation library that has less dependencies on our build tooling.

 - [x] Setup i18next in Grafana + switch phrases to react-i18next components https://github.com/grafana/grafana/pull/55845
 - [x] Update Crowdin integration to use the new JSON message catalogues
    - en messages.json must include phrases for Crowdin to ingest, but for english phrases we will use the default message in the source
 - [x] Update dev tooling (`i18n:extract` and `i18n:compile`) if needed
 - [x] Update contributing docs
