### ISSUE TITLE
Epic: GRPC Server - Auth

### ISSUE THREAD

**Issue by toddtreece** [grafana/grafana#56422]
## User initiated requests

* [ ] Generate scoped JWT based on intersection of SignedInUser scopes and the scopes needed by plugin
* [ ] Attach JWT to outgoing gRPC request metadata from Grafana
* [ ] Provide access to `Identity` in plugin based on information in JWT
* [ ] Provide SDK util or middleware to optionally attach JWT to outgoing gRPC requests from plugin to Grafana

## Plugin background tasks
SDK:
* [ ] Expose new service for receiving service account tokens from Grafana
* [ ] Provide method to attach token to outgoing gRPC request
* [ ] Expose new background task service?

Grafana:
* [ ] Figure out when this should happen, and how to configure it (answer can not be for all plugins all the time!)
* [ ] Figure out how to create service account without an org role (or an empty org role) for each plugin
* [ ] Create a service account token on plugin startup and send it to the plugin after the initial handshake
* [ ] Delete service account if plugin is removed from Grafana

**Comment by ryantxu** [comment]
plans have changed
