### ISSUE TITLE
GLDS-Figma Loose Ends — EPIC

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#56470]
[Figma Link](https://www.figma.com/file/htVIFrTq8e7sx8Olo7L6kZ/branch/Adz5S6sx3LTcfkrlYcGp3y/Grafana-design-system---Dark-theme?node-id=3015%3A0)

**Needs to investigate:**
- [ ] Feedback Patterns
- [ ] Cards
- [ ] Dashboards Visualizations

**Needs to be updated:**
- [x] #56490
- [x] #56491
- [ ] Inline Form Styles
- [x] Templates of Pages

**Needs to follow up:**
- [ ] Explore Items
- [x] Data Table
- [x] Table Explorations
- [x] FooterMenu
- [x] Table

**Needs to be replaced:**
- [x] SideBarNavigation

**Needs to maintain:**
- [x] PageMenu
- [x] Curser
- [x] ComponentChecklist

**Needs to be deprecated:**
- [x] Button-Toolbar-Split

**Comment by natydej** [comment]
A [branch](https://www.figma.com/file/HvJ0cBKqIt1Q509dZGlExE/Need-to-be-deprecated?node-id=8444-13521) already created in Figma, ready to merge/publish for these components to be deprecated:

- InfoBox (The component is no longer approved for us and devs/designers should use an alert component)
- ClickOutsideWrapper (Needs removed as a component)
- DataSourceHttpSettings (Needs removed as a component)

**Comment by staton-hyse11** [comment]
This work has been completed
