### ISSUE TITLE
Epic: Canvas - Beta feedback

### ISSUE THREAD

**Issue by adela-almasan** [grafana/grafana#56512]
```[tasklist]
### Bugs 🐞
- [ ] https://github.com/grafana/grafana/issues/67941
- [x] https://github.com/grafana/grafana/issues/56513
- [x] https://github.com/grafana/grafana/issues/56757
- [x] https://github.com/grafana/grafana/issues/56758
- [x] https://github.com/grafana/grafana/issues/58081
- [x] https://github.com/grafana/grafana/issues/58492
- [x] https://github.com/grafana/grafana/issues/60804
- [x] https://github.com/grafana/grafana/issues/61438
- [x] https://github.com/grafana/grafana/issues/61441
- [x] https://github.com/grafana/grafana/issues/61640
- [x] https://github.com/grafana/grafana/issues/61831
- [x] https://github.com/grafana/grafana/issues/61930
- [x] https://github.com/grafana/grafana/issues/62047
- [x] https://github.com/grafana/grafana/issues/62126
- [x] https://github.com/grafana/grafana/issues/62519
- [x] https://github.com/grafana/grafana/issues/62527
- [ ] https://github.com/grafana/grafana/issues/63760
- [ ] https://github.com/grafana/grafana/issues/63869
- [ ] https://github.com/grafana/grafana/issues/67940
- [ ] https://github.com/grafana/grafana/issues/65298
- [ ] https://github.com/grafana/grafana/issues/61190
- [ ] https://github.com/grafana/grafana/issues/69350
- [ ] https://github.com/grafana/grafana/issues/73445
```

```[tasklist]
### Feedback 💡
- [ ] https://github.com/grafana/grafana/issues/58384
- [ ] https://github.com/grafana/grafana/issues/61440
- [x] https://github.com/grafana/grafana/issues/57219
- [x] https://github.com/grafana/grafana/issues/57216
- [x] https://github.com/grafana/grafana/issues/57218
- [x] https://github.com/grafana/grafana/issues/57311
- [x] https://github.com/grafana/grafana/issues/61110
- [x] https://github.com/grafana/grafana/issues/61100
- [x] https://github.com/grafana/grafana/issues/60190
- [x] https://github.com/grafana/grafana/issues/57310
- [x] https://github.com/grafana/grafana/issues/60493
- [x] https://github.com/grafana/grafana/issues/61429
- [x] https://github.com/grafana/grafana/issues/61423
- [x] https://github.com/grafana/grafana/issues/61439
- [ ] https://github.com/grafana/grafana/issues/67611
- [ ] https://github.com/grafana/grafana/issues/66711
- [ ] https://github.com/grafana/grafana/issues/48225
- [ ] https://github.com/grafana/grafana/issues/48229
- [ ] https://github.com/grafana/grafana/issues/73656
```

### [Community Feedback](https://github.com/grafana/grafana/discussions/56835) ❤️

```[tasklist]
### Community feedback
- [ ] https://github.com/grafana/grafana/issues/63902
- [ ] https://github.com/grafana/grafana/issues/60751
- [ ] https://github.com/grafana/grafana/issues/57308
- [ ] https://github.com/grafana/grafana/issues/63761
- [ ] https://github.com/grafana/grafana/issues/63876
- [ ] https://github.com/grafana/grafana/issues/63880
- [ ] https://github.com/grafana/grafana/issues/63881
- [x] https://github.com/grafana/grafana/issues/57376
- [x] https://github.com/grafana/grafana/issues/58542
- [x] https://github.com/grafana/grafana/issues/60778
- [x] https://github.com/grafana/grafana/issues/59011
- [x] https://github.com/grafana/grafana/issues/61415
```

**Comment by drew08t** [comment]
Feature requests (in no particular order, plus I know some of these are already on the radar):

- [ ] Arrow controls
- [ ] Duplicate multiple things
- [ ] Place selected element options above layer options
- [ ] Auto-align elements
- [ ] Position based on data
- [ ] When resizing really small elements, move control hands outside
- [ ] When moving elements, focus layout option menu (to see numbers change)
- [ ] Font options (more than just size)
- [ ] Selecting under transparent elements
- [ ] Preview in element list (like text content for example)

Bugs:

- [ ] When dragging elements to re-arrange them, screen goes black and can't save or proceed.
- [ ] Can't save after moving multi-selected elements.

**Comment by nmarrs** [comment]
>  Can't save after moving multi-selected elements.
I am not able to reproduce this issue, do we have a repro case for this? @drew08t

> When dragging elements to re-arrange them, screen goes black and can't save or proceed.
I am also having a hard time reproducing this bug, do we have a solid repro case for this as well?

**Comment by grafanabot** [comment]
This issue was removed from the 9.3.0-beta1 milestone because 9.3.0-beta1 is currently being released.

**Comment by edalevol** [comment]
Hey, I only get a subset of icons to choose from when selecting element -> svg-icon and the path img/icons/unicons. 
The selection of icons is sorted and i can only chose from the 98 first icons, the last icon i can chose is "assistive-listening-systems". Trying to search-/ilter for other icons doesn´t work. 

Is this limited by intention? a bug? a bug on my end only?

The dir /usr/share/grafana/img/icons/unicons contains alot more icons than the ones i can choose from.

self hosted on ubuntu 22.04
grafana version 9.3.2

**Comment by nmarrs** [comment]
Hi @edalevol, the current list of icons is limited at this time so this is not a bug on your end 👍
