### ISSUE TITLE
EPIC: NestedFolders

### ISSUE THREAD

**Issue by mildwonkey** [grafana/grafana#56880]
This Epic is to track the Nested folders implementation 

### Outstanding tasks for GA:
```[tasklist]
### GA
- [ ] https://github.com/grafana/identity-access-team/issues/523
- [ ] #79401
- [ ] #78752
- [ ] #74600
- [ ] https://github.com/grafana/grafana/issues/72090 required due to duplicate folder names
- [ ] https://github.com/grafana/grafana/issues/80324
```

```[tasklist]
### After GA (move to a separate EPIC?)
- [ ] #79332
- [ ] #78546
- [ ] #78599
- [ ] https://github.com/grafana/grafana/issues/80131
```

### List of previous tasks:

```[tasklist]
### Main tasks
- [x] Move the migration into the store package & put behind feature flag #58590
- [x] NestedFolder store implementation & tests - @papagian & @idafurjes #57700 #57662
- [x] NestedFolders feature flag  - @mildwonkey
- [ ] Add to Dashboard & Alert services: `GetCountInFolder()` - @mildwonkey
- [x] add migration in services to migrate folders from dashboard table to folder table @ying-jeanne
- [x] Refactor service to separate legacy and nested folder methods
- [x] check for loops in Create @ying-jeanne
- [x] check max depth in Create https://github.com/grafana/grafana/pull/59213
- [x] sync function from dashboard -> new folder table (so users can turn the feature on and off)
- [x] https://github.com/grafana/grafana/pull/63275
- [ ] Update command (svc): only title and description https://github.com/grafana/grafana/pull/60323
- [ ] Move command/DTO (svc): only parent UID in DTO JSON body (POST /api/v1/folders/:uid/move) @ying-jeanne
- [x] #63080
- [ ] #63082
- [ ] Remove feature toggle once GA
- [ ] #63108
- [ ] Browse view: use searchV1 even if panelTitleSearch is enabled
- [x] Empty `url` property for parent folders in API responses https://github.com/grafana/grafana/pull/68082
- [ ] Search v1 for specific folders (using `folderIds` query parameter) should return results in inherited folders too https://github.com/grafana/grafana/pull/68066
- [x] Search v1 support for fetching top levels: included in https://github.com/grafana/grafana/pull/65040#issuecomment-1521600086
- [x] Allow renaming a folder several times https://github.com/grafana/grafana/pull/68379
- [ ] #71425
- [x] Empty folderID and folderUID from search response for folders
- [ ] https://github.com/grafana/grafana/issues/74433
- [ ] https://github.com/grafana/grafana/issues/73271
- [ ] https://github.com/grafana/grafana/issues/74671
```

```[tasklist]
### Registry
- [ ] https://github.com/grafana/grafana/issues/63872 
```

```[tasklist]
### Coordination with other teams
- [ ] https://github.com/grafana/grafana-authnz-team/issues/172
- [x] #58762
```

**Comment by tolzhabayev** [comment]
Nested Folders are GA in Grafana 11 https://grafana.com/docs/grafana/next/whatsnew/whats-new-in-v11-0/#subfolders
