### ISSUE TITLE
GLDS- Align Storybook and Figma Icons — EPIC

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#56941]
Currently our Storybook has much more icons than our Figma File DS. They are more than 30 icons from the Storybook that need to be added on Figma to be aligned.

Icons:
- [x] https://github.com/grafana/grafana/issues/56942
- [x] https://github.com/grafana/grafana/issues/56944
- [x] https://github.com/grafana/grafana/issues/56946
- [x] https://github.com/grafana/grafana/issues/56948
- [x] https://github.com/grafana/grafana/issues/56949
- [x] https://github.com/grafana/grafana/issues/56950
- [x] https://github.com/grafana/grafana/issues/56951
- [x] https://github.com/grafana/grafana/issues/56952
- [x] https://github.com/grafana/grafana/issues/56953
- [x] https://github.com/grafana/grafana/issues/56954
- [x] https://github.com/grafana/grafana/issues/56955
- [x] https://github.com/grafana/grafana/issues/56956
- [x] https://github.com/grafana/grafana/issues/56957
- [x] https://github.com/grafana/grafana/issues/56958
- [x] https://github.com/grafana/grafana/issues/56961
- [x] https://github.com/grafana/grafana/issues/56962
- [x] https://github.com/grafana/grafana/issues/56963
- [x] https://github.com/grafana/grafana/issues/56964
- [x] https://github.com/grafana/grafana/issues/56965
- [x] https://github.com/grafana/grafana/issues/56979
- [x] https://github.com/grafana/grafana/issues/56966
- [x] https://github.com/grafana/grafana/issues/56967
- [x] https://github.com/grafana/grafana/issues/56968
- [x] https://github.com/grafana/grafana/issues/56980
- [x] https://github.com/grafana/grafana/issues/56969
- [x] https://github.com/grafana/grafana/issues/56970
- [x] https://github.com/grafana/grafana/issues/56981
- [x] https://github.com/grafana/grafana/issues/56982
- [x] https://github.com/grafana/grafana/issues/56971
- [x] https://github.com/grafana/grafana/issues/56983
- [x] https://github.com/grafana/grafana/issues/56973
- [x] https://github.com/grafana/grafana/issues/56974
- [x] https://github.com/grafana/grafana/issues/56976
- [x] https://github.com/grafana/grafana/issues/56977
- [x] https://github.com/grafana/grafana/issues/56978
- [x] https://github.com/grafana/grafana/issues/56960
- [x] https://github.com/grafana/grafana/issues/58653
- [x] https://github.com/grafana/grafana/issues/58663
- [x] https://github.com/grafana/grafana/issues/58664
- [x] https://github.com/grafana/grafana/issues/58665
- [x] https://github.com/grafana/grafana/issues/58666
- [x] https://github.com/grafana/grafana/issues/58668
- [x] https://github.com/grafana/grafana/issues/58676
- [x] https://github.com/grafana/grafana/issues/58680
- [x] https://github.com/grafana/grafana/issues/58681
- [x] https://github.com/grafana/grafana/issues/56972

**Next Steps:**

- [x] Merge the branch of adding all new icons to the main file
- [x] Publish all changes of new icons
- [ ] Create a new file for the icons new home
- [ ] Move icons to the new file
- [ ] Publish new library
- [ ] Update main component library

**Comment by staton-hyse11** [comment]
Tracking standalone icon library work in ticket https://github.com/grafana/grafana/issues/59675
