### ISSUE TITLE
G10 Get Started: Loki (Part 1)

### ISSUE THREAD

**Issue by evandandrea** [grafana/grafana#57731]
A key goal of Grafana 10 is to improve the getting started experience in Grafana, where that journey is defined as going from an empty instance to monitoring something. This is valuable because:

> An improved onboarding experience for new-to-Grafana users will help people achieve their desired outcomes (creating dashboards, keeping their systems healthy) faster, and help them build confidence as continuing users. Users who successfully set up their first data source and query it are far more likely to return to, share, and eventually pay for Grafana and Grafana Cloud.

Additional context:

- [Framing](https://docs.google.com/document/d/1j8ew0mNL3jQUa4KmdHmZzzPxpJl_1HunczaJuvMA7bU/edit#bookmark=id.7abyf01er8bt)
- [Presentation](https://docs.google.com/presentation/d/1mzZYfKVbo9ju8X0EqpSiN_z1Q865clVXbAUjiaS3eaQ/edit#slide=id.g1596ba710f4_0_114)
- [FAQ](https://docs.google.com/document/d/1Ts2TK_uHd4ffc-UxEcT1kyXd8ceouepJ_wkRLo4nByg/edit#)

This epic represents investment of roughly one month of an engineer's time in improving the Getting Started experience around Loki. We should balance this time between: clearing technical blockers (i.e. BE migration, research, and initial execution on research. Further cycles of these can be captured in subsequent epics.

## Get started path for Loki:

We formulated following path, that if the user completes, we can consider that `getting started with Loki` was successfull: 

![Image](https://user-images.githubusercontent.com/30407135/198342064-b543a4b4-849f-4436-be32-cc3b11a34d5e.png)

The key objective we're pursuing with the changes listed below is `to minimize and address ambiguity and address to the user with a clearer language`.

With that in mind, we identified the following improvement categories and tasks:

### 1. Setting up Loki data source first time
 
- When user is setting up Loki for the first time, **make it less overwhelming** by showing only fields that need to be set up (url + auth) and toggle-off advanced settings (derived fields/alerting). These can be always toggled off, or toggled-on when user returns back to data source to edit it second time.
- URL field's placeholder should have text that makes it clear that field is not filled up (e.g. `Example: https://localhost:3100`)
- Help users set up data sources by providing links/resources to Loki auth documentation (if there is some)
- https://github.com/grafana/grafana/issues/54228

### 2. Guide users to Explore
- When user sets up data source, it is not clear what should they do next. We have Explore button in the page but it is basically invisible. We should make "next step - going to Explore" more obvious by having "Explore your data now" with a link to Explore in data source validation message. 

![Image](https://user-images.githubusercontent.com/30407135/198340103-6ba5ced9-06c0-4f16-9e62-5961b84ee1aa.png)

### 3. In Explore get to the first results as soon as possible 
- Make it easier to get to some/any results by helping users create meaningful queries. We can reuse already existing components - `Kick start your query` and add section with `New to Loki, start here!`. This should include complete queries with incrementally growing complexity. 
- Make it more clear what some query editor features do, for example we should rename `Explain` to `Explain query` 
- Remove clutter (redundant buttons/toggles) to make buttons/hints that are on screen/appear more me attractive:
  - Remove Raw query toggle and always show raw query https://github.com/grafana/grafana/issues/58511
  - Remove cheatsheet as users don't click on it + it is boring and we can make `kick start your queries  > new to Loki, start here` section more interesting using already existing feature

### 4. Use filters to get to specific results (error logs, warning logs) 
- Leverage `hints` as a tool to help writing queries. Right now we suggest parsers. E.g. suggest line filters. 
![Image](https://user-images.githubusercontent.com/1069378/199745685-ac63ae2f-4112-41dd-9159-4891728c5776.png)
  - Use a clearer description for hints: Rename `logfmt_parser()` to `logfmt parser` and `json_parser` to `json parser` https://github.com/grafana/grafana/issues/59188
  - Add more hints: https://github.com/grafana/grafana/issues/59191
    - hint: add text filter
    - hint: add label filter
- Make it easier to write first queries by adding more hints and change them to be more goal oriented instated of "what operation will be added" oriented (this is in comparison to current use `logfmt` use `json_parser` which are not understandable to the new users):
  - `search logs that contain text` (will add line contains)
  - `search logs with key-value pair` (will add parser and label filter)

- `Line filter` operation in Operations should be the first one (not the last one). If possible opened Line filter options (Line contains/line contains not) should be displayed right away.
- Make it clear that at least 1 label filter is necessary by removing closing button (x button) if there is only 1 filter. 
- For easier interaction with label filtering, Label filter expression should suggest labels https://github.com/grafana/grafana/issues/59216
- Line contains regex should explain what regex it expects (https://yourbasic.org/golang/regexp-cheat-sheet/) 
- https://github.com/grafana/grafana/issues/57051

### 5. Create a dashboard from this query

We didn't find anything to improve. 

### 6. Log panel

Once the query is formed and executed, we move to the list of logs. On top of the list, we find some toggles, and depending on the results you get, some of them don't have an effect in the output which we found very confusing, specially for beginners.

- `Prettify JSON` is present, even when there's no JSON in the logs. Toggling it on and off has no effect.  https://github.com/grafana/grafana/issues/62872
  ![imagen](https://user-images.githubusercontent.com/1069378/205034050-e0c137c4-5848-495c-a72a-655b9fe6e846.png)
- `Dedup` is a technical concept and doesn't clearly communicate its meaning.   https://github.com/grafana/grafana/issues/62873
  ![imagen](https://user-images.githubusercontent.com/1069378/205035070-ca595e05-e758-4c83-979d-56fb85ccbddf.png)
  There is also no reference of how "Exact", "Numbers", and "Signature" repeated lines.
- `Unique labels` also fails to clearly communicate its purpose, forcing the user to toggle it on and off in an attempt to guess its meaning.
 ![imagen](https://user-images.githubusercontent.com/1069378/205035647-25e80326-f6d4-42a3-83b4-0ba037bf6c69.png)
 When turned on, a "(no unique labels)" string appears on every line.
 ![imagen](https://user-images.githubusercontent.com/1069378/205035743-473b17d8-ac0e-4754-9c2a-f44311ca8369.png)

### Non-get started issues:
 
_Non-starting tasks where we discovered UX issues: alerting has no description or link documentation, maxLines have no title)_ 

## Tasks: (to be created)

```[tasklist]
### Tasks
- [x] https://github.com/grafana/grafana/issues/59222
- [x] https://github.com/grafana/grafana/issues/58511
- [x] 
- [x] 
- [x] https://github.com/grafana/grafana/issues/59188
- [ ] Loki: Hide "prettify json" option when there is no JSON in display
- [ ] Loki: "Dedup" concept has unclear meaning
- [ ] Loki: Hide "prettify json" option when there is no JSON in display
- [ ] https://github.com/grafana/grafana/issues/59188
- [ ] https://github.com/grafana/grafana/issues/59222
- [ ] https://github.com/grafana/grafana/issues/59188
- [ ] https://github.com/grafana/grafana/issues/57746
- [ ] https://github.com/grafana/grafana/issues/59191
- [ ] https://github.com/grafana/grafana/issues/59216
- [ ] https://github.com/grafana/grafana/issues/57051
- [ ] https://github.com/grafana/grafana/issues/59222
- [ ] https://github.com/grafana/grafana/issues/59188
- [ ] Loki: Find a better way to communicate the purpose of "Dedup"
- [ ] https://github.com/grafana/grafana/issues/59188
- [ ] https://github.com/grafana/grafana/issues/62873
- [ ] https://github.com/grafana/grafana/issues/62872
- [ ] https://github.com/grafana/grafana/issues/59188
```

**Comment by mckn** [comment]
@evandandrea can you please add labels to the issues you create so they don't end up in the issue triage workflow? Thanks 🙏🏻

**Comment by mary-sitzenstatter** [comment]
I think there is an assumption here - that users will Explore their data after they have configured the data. I think this is something we should ""explore"" :) a bit

**Comment by matyax** [comment]
@mary-sitzenstatter that's a great point. I'll check if we have data on that, probably not.

**Comment by matyax** [comment]
Update here: we finished all the initial tasks derived from this excercise that we could do without UX approval. Now we're waiting to sync with UX for further changes.

**Comment by matyax** [comment]
We've done all the tasks that we could do after this excersise.  This will now continue in https://github.com/grafana/grafana/issues/61769
