### ISSUE TITLE
Navigation IA: Move `Cloud link` into the `Admin` section

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#58213]
# prereqs
- [x] ~https://github.com/grafana/grafana/issues/58211~ no longer a prereq

# TODO
- [x] `Cloud link` appears in the `Admin` section (no order mentioned so i would guess last, maybe confirm with someone)
- [x] `Cloud link` does not appear under `Apps`

potentially useful information: there's an existing function [here](https://github.com/grafana/grafana/blob/main/pkg/services/navtree/models.go#L101) where we _might_ want to do this
