### ISSUE TITLE
EPIC: Plugins: Add support for loading plugins with Webpack

### ISSUE THREAD

**Issue by jackw** [grafana/grafana#58249]
This is a follow up to #39961 breaking down how to  deliver the ability to load plugins in the frontend using Webpack and the [module federation](https://webpack.js.org/concepts/module-federation/) plugin.

```[tasklist]
### Tasks
- [ ] Update Grafana core to bootstrap the app and configure the Webpack federated modules plugin to [expose plugin dependencies](https://github.com/grafana/grafana/blob/main/public/app/features/plugins/plugin_loader.ts)
- [ ] Update Grafana core plugin loading to load plugins that use the federated module plugin
- [ ] Implement error handling and caching stategies
- [ ] Create a Webpack "plugin" for `create-plugin` that updates the config to include the federated module plugin
- [ ] Make sure plugins continue to load via CDN. `publicPath: 'auto'` should assist here.
- [ ] Deprecate SystemJS in `@grafana/runtime`
- [ ] Write / update documentation related to plugin loading where necessary
```

**Comment by trevorSwainSKAO** [comment]
During this update, are you also adding in the code into WebPack 5 so that Grafana can be embedded into an application ?    I would be really useful as it would also allow for error handling should it be unavailable, and, if possible, the passing in of login credentials.   Many thanks.

**Comment by jackw** [comment]
Closing this as we have decided module federation will not be an appropriate technology due to the plugins CDN project and sandboxing project.

**Comment by jackw** [comment]
Reopening so we don't lose this thread.
