### ISSUE TITLE
Remove flakiness from build E2Es

### ISSUE THREAD

**Issue by ivanortegaalba** [grafana/grafana#58396]
### General
- [x] Share the action plan with Release Engineering team to get approval
- [x] #58877
- [x] Create a reporter for Jest
- [x] Reorg the tests to create a Drone job for each product area (won't do)
- [x] Create a readme about how to add a new E2E test suite to Drone (won't do)
- [x] Implement tracking to gather E2E errors together with recordings
- [x] Create a dashboard with the data with a drilldown easy to go (delegated to Rel eng)
- [x] Create an issue for each of the flaky tests encountered

### Current frontend tests issues:
- [x] #58747 (skipped)
- [x] #59315

### References
* [Design doc: Improve E2Es reliability](https://docs.google.com/document/d/1DwgDO2Dk7BeQQTSAwZfGHOoi_62jG21J9gIyZLd7T00/edit#heading=h.5sybau7waq2q)

**Comment by grafanabot** [comment]
This issue was removed from the 9.2.6 milestone because 9.2.6 is currently being released.
