### ISSUE TITLE
Tech: Assess design's technical feasibility

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#58571]
### TODO

- [ ] Create issue for implementation of first iteration
- [ ] Breakdown into possible tasks
- [ ] Refine with the team: review breakdown, assess dependencies, risks, etc.
