### ISSUE TITLE
Epic: Dashboard - Drag and Drop

### ISSUE THREAD

**Issue by codeincarnate** [grafana/grafana#58918]
The idea is that you can drag and drop a file(csv) to the dashboard and visualise it in the most easiest way.

In the first iteration we want to add this feature to the edit panel.  It will add a new query to the query row with the Grafana datasource and persist the parsed csv in a snapshot.

```[tasklist]
### Tasks
- [x] Add dropzone to the edit panel
- [x] Parse csv to dataframe
- [x] Persist dataframe in Grafana datasource
- [x] Try to parse time when there are no headers
- [x] Try to parse excel document
- [x] Constrain the file size in 200kb
- [x] Put it behind feature flag
- [x] Phase 2: Usability of the same Drag & Drop data in multiple dashboards
- [x] Test different date formats
- [x] Try adding multiple files into 1 panel
- [x] Test different time formats
- [x] Increment file size
```

```[tasklist]
### Enhancements
- [ ] https://github.com/grafana/grafana/issues/62355
- [ ] Increment max file size
