### ISSUE TITLE
A11y: Fix elements not handling keyboard interactions

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#58924]
# How to make progress on this issue

- ✅ create a new subtask by clicking the `Convert to issue` button next to the corresponding task below, assign yourself + add the `type/accessibility` label
- ⏱️ temporarily enable the eslint rules `jsx-a11y/click-events-have-key-events` and `jsx-a11y/no-static-element-interactions`
  - this can be done by changing them from `"off"` to `"error"` in your `.eslintrc`
- 🔍 open the file to see where the error is (or run `yarn lint` if your editor isn't set up to show eslint errors)
- 🔧 fix the error
  - this will be heavily dependant on context
    - should you be able to interact with this element via the keyboard or is there another element that already handles the same behaviour via the keyboard?
  - in some cases, the best fix is to **use the correct semantic element** for the job. if something behaves like a button but we want it to look different, we can still use the `<button type="button">` element and style it appropriately. this will handle all our keyboard accessibility needs for us. there's even a handy [`clearButtonStyles`](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Button/Button.tsx#L306) util to undo the basic button styling.
  - if using a `<button>` or other similar interactive element is not appropriate, refer to the documentation [here](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/click-events-have-key-events.md) and [here](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-static-element-interactions.md). this will likely involve setting a `role` and implementing a custom `onKeyPress`
- 🧪 test it! can you interact with this element using the keyboard now?
- 🥳 turn the rules back off and deliver a PR with the fix! 

# TODO

## @grafana/alerting-squad 
- [x] #59266
- [x] #59267
- [x] #59268
- [x] #59269
- [x] #59270
- [x] #59271

## @grafana/grafana-authnz-team 
- [ ] #70971
- [ ] #70969

## @grafana/aws-plugins
- [x] #58931

## @grafana/bi-squad
- [x] #59043
- [x] #59042
- [x] #59041
- [x] #59038
- [ ] #59037

## @grafana/dashboards-squad 
- [x] #63365
- [x] #62855
- [ ] #70975
- [ ] #70976
- [ ] A11y: Fix keyboard accessibility in `public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderNotice.tsx`
- [x] A11y: Fix keyboard accessibility in `public/app/features/scenes/components/layout/SceneGridLayout.tsx`
- [x] A11y: Fix keyboard accessibility in `public/app/features/scenes/editor/SceneComponentEditWrapper.tsx`
- [x] A11y: Fix keyboard accessibility in `public/app/features/scenes/editor/SceneObjectTree.tsx`
- [ ] #70982
- [x] #60556

## @grafana/grafana-edge-squad 
- [ ] #70965
- [ ] #70973
- [ ] #70984
- [x] #70373
- [x] A11y: Fix keyboard accessibility in `public/app/features/search/components/SearchCheckbox.tsx`
- [ ] #62859
- [ ] #70983
- [x] A11y: Fix keyboard accessibility in `public/app/features/live/dashboard/DashboardChangedModal.tsx`
- [ ] #70978
- [ ] #70979

## @grafana/observability-experience-squad 
- [x] #58928
- [x] #58929
- [x] #58930

## @grafana/observability-logs
- [x] #59046
- [x] #59047
- [x] #59048

looks like these might be deprecated and getting removed?:
- [x] A11y: Fix keyboard accessibility in `packages/grafana-ui/src/components/Logs/LogRowContext.tsx`
- [x] A11y: Fix keyboard accessibility in `packages/grafana-ui/src/components/Logs/LogRowMessage.tsx`

## @grafana/observability-metrics 
- [x] A11y: Fix keyboard accessibility in `public/app/plugins/datasource/prometheus/components/PromCheatSheet.tsx`
- [x] #70444

## @grafana/observability-traces-and-profiling 
- [ ] #61531
- [x] #59410
- [x] #61532
- [x] #68514

## @grafana/user-essentials 
- [x] #59284
- [x] #59383
- [x] #59403
- [x] #59021
- [x] #59579
- [x] #60922
- [x] #70501
- [x] #59566
- [x] #60400
- [x] #60401
- [x] #60402
- [x] #59379
- [x] #58975
- [x] #59860
- [x] #59570
- [x] #60554
- [ ] #70963
- [ ] #70964
- [x] #59380
- [x] #60843
- [x] #59695
- [x] #58969
- [x] #62494
- [x] #59668
- [x] #58965

**Comment by taleena** [comment]
@ashharrison90 should we move all the incomplete ones to a new epic if they still need to be done?

**Comment by ashharrison90** [comment]
do we get any value from that? the main value from this epic was to help enable the eslint rule. now that's done, the individual issues are all on squads boards and I think leaving squads to fix their own problems is fine tbh.
