### ISSUE TITLE
Navigation: papercuts

### ISSUE THREAD

**Issue by zsofiakm** [grafana/grafana#59056]
List of papercut issues for Grafana's new navigation.

- [x] ~When navigating to the Grafana Cloud home app, we momentarily display a side nav with the whole nav tree, before showing a loading indicator. The layout with the side nav should not be displayed.~ fixed by https://github.com/grafana/grafana/pull/66799
- [x] #66314
- [x] https://github.com/grafana/grafana/issues/65394
- [x] ~Megamenu does not remember previously expanded sections~ https://github.com/grafana/grafana/pull/59661
- [x] ~Inconsistent `Starred` behavior: In the hamburger menu, when `Starred` is clicked, the menu closes and the user isn't redirected to a specific page. A possible solution is to open `/dashboards?starred`~ https://github.com/grafana/grafana/pull/62685
- [x] ~`Apps` needs a different icon in the hamburger menu, as it uses the same icon as `Dashboards`.~ https://github.com/grafana/grafana/pull/59476

Improvements:

- [x] #65523
- [x] #66758

**Comment by ashharrison90** [comment]
@zsofiakm are you able to attach a video/screenshot of the first one? i can't reproduce on any environment, just wanna make sure i haven't misunderstood 😅

**Comment by zsofiakm** [comment]
@ashharrison90 Sure, [here it is](https://user-images.githubusercontent.com/97596715/205641073-e1772ad2-ac0c-4d09-a0e3-5dd38171c36c.mov). I'm using Chrome on a mac.

**Comment by ashharrison90** [comment]
@zsofiakm hmmmmmm not sure what's going on, still can't repro 🤔 


https://user-images.githubusercontent.com/20999846/205660327-37bef40f-45ce-432b-8881-556b19331517.mp4
