### ISSUE TITLE
Epic: Barchart Enhancements

### ISSUE THREAD

**Issue by codeincarnate** [grafana/grafana#59458]
An epic for tracking ongoing enhancements to the Barchart

### Community discussions / requests
- [x] https://github.com/grafana/grafana/discussions/38193
- [ ] https://github.com/grafana/grafana/discussions/40532
- [ ] https://github.com/grafana/grafana/discussions/38500

### Enhancements

- [ ] #57956
- [ ] #57971
- [x] #57963
- [x] #57966
- [x] #3591
- [x] #36712
- [ ] https://github.com/grafana/grafana/issues/35940

### Bugs

- [x] #55932
- [x] #59304 
- [ ] #59273 
- [x] #61454
- [ ] https://github.com/grafana/grafana/issues/62260

**Comment by mdvictor** [comment]
Added https://github.com/grafana/grafana/issues/61454 to the list

**Comment by GrzegorzLyp** [comment]
Please add this. Screenshot from play.grafana.org. Same issue on 9.4.0pre. When You select not first element in legend then tooltips are not showing. When nothing is selected or first is selected tooltips are showing.

![image](https://user-images.githubusercontent.com/29247982/215598620-28acb4a0-e7ef-4061-a700-43649c1d3029.png)
