### ISSUE TITLE
Align Entity API with Kind system

### ISSUE THREAD

**Issue by sdboyer** [grafana/grafana#59684]
Currently, there is code related to the Entity API that is handwritten which, now that the kind framework exists, needs to be derived or generated from kind declarations. Most important and obvious is any (non-test) case in which there exists a list of kinds that is not derived from the canonical kind declarations.

The kind system and jennies are now in a position where we should be able to support all such cases - and if we can't, then we'll (of course) figure out how we need to refactor. But the longer this gap remains open, the greater the risk becomes.

Each of the following needs to be refactored to either be or depend on code generated from canonical kind declarations: 

- [ ] [This list](https://github.com/grafana/grafana/blob/5736b46962b4d4eb01a17d498c845955c965a8a2/pkg/services/store/kind/registry.go#L32-L63) that populates the `pkg/services/store/kind.KindRegistry`. #59899 
- [ ] More generally, the above `KindRegistry` needs to be refactored to be generated, and i'm guessing it'll require some elbow grease to make that fit well. #59899 
- [ ] In particular, being able to support a Go implementation of `GetEntitySummaryBuilder`, such as appear in `pkg/services/store/kind/*`, will require likely require generating an implementation (perhaps `BackendKind`? `InternalKind`?) that wraps the `Kind` structs generated under `pkg/kinds/*`. (Or maybe we just do it with some thinner funcs, not a whole type...:shrug: #59899 
- [ ] Testing for [this explicit list](https://github.com/grafana/grafana/blob/5736b46962b4d4eb01a17d498c845955c965a8a2/pkg/services/store/kind/registry_test.go#L21-L31) should be unnecessary - though we may need a mechanism for a dummy/helper
- [ ] [This whole list](https://github.com/grafana/grafana/blob/fb98a97efad6b816238e53af2baebdda7e9464aa/pkg/models/entity.go#L9-L40) needs to be generated

(this list may not be complete)

**Comment by sdboyer** [comment]
cc @ryantxu

**Comment by sdboyer** [comment]
With the shift back to k8s, this is no longer a goal.
