### ISSUE TITLE
Explore: Create starred/recently viewed list that includes Explore Items

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#60267]
Hackathon branch: https://github.com/grafana/grafana/compare/main...kristina/recent-viewed-explore

Currently, there is a panel called "Dashboard List" that shows on the homepage of new installs of Grafana by default. Explore's query history saves every query ran, and also has a feature where you can star and unstar queries you'd like to keep saved. We would like to have query history content show, when relevant, to this dashboard list panel. Our end goal is to provide more routes to explore, and enhance the experience for users that use Explore more than dashboards.

While the Dashboard list is an existing panel, we would rather copy this panel and and enhance that copy. This is due to the default, widespread adoption of the existing panel, and the fact that the panel, even down to the component name, only refers to dashboards. Extensive changes will be required to have even the internals refer to explore items as well. This does mean redundant code in the codebase, but we would hope that with enough iteration time, we could replace the dashboard list with this copy, and eventually deprecate the dashboard list.

- [x] #60268
- [ ] Add time data to dashboard impressions (optional based on design)
- [ ] Enhance query-history endpoint to have more optional parameters
- [ ] Enhance query-history endpoint to have distinct parameter, for so repeated queries are only displayed once[^1]
- [ ] Enhance query-history endpoint to optionally allow duplicate calls
- [ ] Enhance SearchCard and SearchCardExpanded to handle additional information
- [ ] Create new panel, based on DashList panel, for displaying both dashboard and explore items
- [ ] Enable star toggle on distinct explore query

[^1]: When this parameter is enabled, we should look into how this can work with query history as well, perhaps as something toggleable. This will help with #51328 , specifically the parts about duplicate, subsequent query runs being saved. Even if we do not save duplicate, subsequent query runs, the distinct parameter will still be relevant as this list will only want to display distinct queries.

**Comment by Elfo404** [comment]
We are not planning to work on this issue in the foreseeable future. Please upvote or comment if you would like it to be prioritized.
