### ISSUE TITLE
Improve Grafana Alerting notification templates

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#60387]
```[tasklist]
### Make it easier to write templates
- [ ] https://github.com/grafana/grafana/issues/61764
- [ ] https://github.com/grafana/grafana/issues/63470
- [ ] https://github.com/grafana/grafana/issues/65106
- [x] https://github.com/grafana/grafana/issues/61763
- [ ] https://github.com/grafana/grafana/issues/63503
- [ ] https://github.com/grafana/grafana/issues/65109
```

```[tasklist]
### Make it easier to use templates
- [ ] https://github.com/grafana/grafana/issues/63468
- [ ] https://github.com/grafana/grafana/issues/61762
```

**Comment by grafanabot** [comment]
This issue was removed from the 9.5.0 milestone because 9.5.0 is currently being released.
