### ISSUE TITLE
A11y Lab at GKO

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#60634]
The idea is to set up a few laptops that would have some settings/ conditions that'd replicate different types of disabilities - e.g try to use grafana with a color blind filter, with just one hand, etc. The main goal would be to create awareness while being respectful.

#### Tasks

- [x] Organise logistics with event team @natellium 
- [x] Prepare swag (idea to do pins with "keep a11y in mind!") @natellium & @amy-super & @natydej 
- [x] Put together a list of volunteers to be help with the lab & schedule
- [x] Prepare lab exercises
- [x] Install [Colorblindly](https://chrome.google.com/webstore/detail/colorblindly/floniaahmccleoclneebhhmnjgdfijgg?hl=en) Chrome extension on computers to be used for the colorblind exercise
- [x] Get comfortable using VoiceOver if we want to do a screen reader exercise
- [x] Create a Google Form for people to sign up to be part of the working group when they stop by at the lab [Form Link](https://docs.google.com/forms/d/e/1FAIpQLSe3st-3gbiSjWKCQ_XpguTBfEV7YLl3dCTunyJ_NazGJ4noXA/viewform)

**Links & Docs**

- [Sign up sheet/roster](https://docs.google.com/spreadsheets/d/1Lvl_NShWZlmU33J2RvS7t_zrycYdzba5gnbtEBURLug/edit?usp=sharing)
- [Google form](https://docs.google.com/forms/d/1LWs-7Us2H72Q5o2zhuAomIsoKt46iF8n535dWoRGO5A/edit)

**Comment by natydej** [comment]
Some pins ideas for the swag! I've attached some mockups, and the [figma link](https://www.figma.com/file/igXH0LcTupqaqXhnnGhQ9V/A11Y-Swag?node-id=0%3A1&t=d7eG8QHW6PsPaxnU-0) for more ideas if we have that budget.
![pin-V2](https://user-images.githubusercontent.com/51436795/210263671-3bd417cf-d14c-4462-a397-5a822e269d72.png)
![pin-V1](https://user-images.githubusercontent.com/51436795/210263673-0f989936-0cc5-4f5b-9c7a-4dc698acc190.png)

**Comment by amy-super** [comment]
**Current logistics**

- When: During the Grand Prix learning sessions in the mornings (9-10 AM on Tues, Weds, Thurs)
- Where: At the registration or catering area
- How: 5 laptops (so ~5 volunteers)

**Comment by amy-super** [comment]
Proposed tasks: 

- Keyboard-only navigation through a complex dashboard (Grafana play home is a really good example)
- Viewing a heatmap panel with the Colorblindly extension ([this dashboard on play would work](https://play.grafana.org/d/heatmap-calculate-log/heatmap-calculate-log?orgId=1)) 
- Listen to the video(s) with screen readers

**Comment by amy-super** [comment]
**Keyboard-only navigation**
Starting at play.grafana.net, can you tell me what the highest CPU percentage is over the last 3 hours using only your keyboard? 

**Heatmap**
Find the "Heatmap calculate (log)" dashboard on play.grafana.net. Now that you're here, I'll show you how to view it with an extension that mimics different types of color blindness. What do you think about what you're seeing? 

**Screen reader**
Open the Docebo link here: https://grafanalabs.docebosaas.com/learn/course/3353/play/9742/screenreader-demo-showing-dashboard
View these videos: 
- Alternate screenreader demo showing homepage
- Screenreader demo showing dashboard

**Comment by staton-hyse11** [comment]
[Facilitator Guide](https://docs.google.com/document/d/1vrDMp2a1iGR5V-qY2vyM_1XpjBsRD14JfLNws9O6Ebg/edit?usp=sharing)
