### ISSUE TITLE
Pass list of Azure clouds to frontend via frontendsetitngs

### ISSUE THREAD

**Issue by kostrse** [grafana/grafana#61127]
Depends on:
- https://github.com/grafana/grafana-azure-sdk-go/issues/24

Design discussion:
- #61016

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana-azure-sdk-go/pull/104
- [ ] https://github.com/grafana/grafana/pull/84039
- [ ] https://github.com/grafana/grafana/pull/83460
- [ ] https://github.com/grafana/grafana-azure-sdk-react/pull/128
```

**Comment by aangelisc** [comment]
Are we still planning on implementing custom clouds?
