### ISSUE TITLE
Custom Azure clouds in Azure datasources

### ISSUE THREAD

**Issue by kostrse** [grafana/grafana#61124]
Roadmap of work involved for support of custom Azure clouds in Azure datasources.

Design discussion:
- #61016

The work assumes three stages:
- Introduce the new Clouds API and move Azure datasources from hardcoded configuration to the new API.
- Allow customization of clouds for Azure datasources implemented in Grafana core.
- Allow customization of clouds for Azure datasources implemented externally.

### Prereq: migrate Azure Monitor to common format
- [x] https://github.com/grafana/grafana/issues/75123

```[tasklist]
## Clouds API for Azure datasources
- [ ] https://github.com/grafana/grafana-azure-sdk-go/issues/24
- [ ] https://github.com/grafana/grafana-azure-sdk-go/issues/27
- [ ] https://github.com/grafana/grafana/pull/82023
- [ ] https://github.com/grafana/grafana/pull/82043
- [ ] Azure Data Explorer: Azure routes from Grafana Azure SDK
- [ ] #61127
- [ ] #85415
- [ ] Use clouds from API in Azure Monitor configuration UI
- [ ] https://github.com/grafana/azure-data-explorer-datasource/pull/800
```

```[tasklist]
### Custom clouds configuration for built-in Azure datasources
- [ ] https://github.com/grafana/grafana-azure-sdk-go/issues/25
- [ ] #61126
```

```[tasklist]
### Custom clouds configuration for external Azure datasources
- [ ] Pass Azure cloud config via environment variables to external datasources
- [ ] https://github.com/grafana/grafana-azure-sdk-go/issues/26

```

**Comment by aangelisc** [comment]
Closing as custom clouds support was added in #87667
