### ISSUE TITLE
Epic: [GA] Navigation, old nav clean up

### ISSUE THREAD

**Issue by zsofiakm** [grafana/grafana#61214]
After the phased rollout on Grafana Cloud, improve the navigation based on user feedback. With the GA in OSS, remove the old navigation.

# TODO
- [x] https://github.com/grafana/grafana/pull/66548
- [x] https://github.com/grafana/grafana/pull/66287
- [ ] https://github.com/grafana/grafana/pull/66878

**Comment by grafanabot** [comment]
This issue was removed from the 9.5.0 milestone because 9.5.0 is currently being released.
