### ISSUE TITLE
Explore: Support log volume histogram for mixed data sources

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#61546]
Full-range log volume logic relies on a log volume data provider that is not available in the mixed data source.

It means that when a mixed data source is used Explore assumes there's no provider available and falls back to the loaded-logs histogram:

![Image](https://user-images.githubusercontent.com/745532/212680660-c65e07c2-6946-422d-bd63-85acf127153e.png)

The histogram should show aggregated log volume for all logs.

Needs checking: ensure bucketing is consistent when multiple data sources are used.

```[tasklist]
### Tasks
- [x] https://github.com/grafana/grafana/issues/61994
- [x] Show logs volume histogram per query
- [ ] https://github.com/grafana/grafana/pull/65392
```

Future improvements (required to use mixed data sources only [#63023](https://github.com/grafana/grafana/issues/63023)):

* Show single legend to allow filtering by type

**Comment by gelicia** [comment]
Relates to #63036
