### ISSUE TITLE
EPIC: Plugins: extending the Grafana UI

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#61658]
**Description**:
This is an epic to keep track of the overall progress of giving the possibility to extend the Grafana UI by plugins. ~~For more details please read the [design doc](https://docs.google.com/document/d/1-g6-4RJx3LzsldvdwUZb_wHXAS5Z7_kt6Ql9zAoLj8I).~~

_Edit:_

During the work with this functionality we realized that declaring the extensions in both `module.ts` and `plugin.json` made the solution way to complex for almost no benefit at all. The main reason why we wanted to have it in `plugin.json` was so we could detect and present what kind of extensions a plugin will add to Grafana prior to installing it.

This is still a good goal that we might want to reach but we will try to resolve it when we have rolled out the plugin extensions. The solution might still be to add something in plugin.json but we will exclude that for now.

This makes the design doc a bit outdated and we have decided to put our efforts in building the feature instead of keeping the design doc up to date. For more details and examples on how this work please visit this https://github.com/grafana/grafana/pull/63089.

```[tasklist]
### Todo
- [x] https://github.com/grafana/grafana/pull/61663
- [ ] https://github.com/grafana/grafana/pull/63089
- [ ] https://github.com/grafana/grafana/pull/63802
- [ ] https://github.com/grafana/grafana/pull/64504
- [ ] https://github.com/grafana/grafana/pull/64029
- [x] ~~Should we provide some kind of API safely register extensions without making the app explode in older versions without plugin extension support?~~ **Decision: no**
- [ ] #64599
- [ ] #64946
- [ ] https://github.com/grafana/grafana-plugin-examples/pull/135
- [ ] https://github.com/grafana/grafana-plugin-examples/pull/137
- [ ] https://github.com/grafana/grafana/pull/64855
- [ ] https://github.com/grafana/grafana/issues/64947
- [ ] https://github.com/grafana/grafana/issues/64959
- [ ] https://github.com/grafana/grafana/pull/65327
- [ ] https://github.com/grafana/grafana/pull/65524
- [ ] https://github.com/grafana/grafana/issues/65774
- [ ] https://github.com/grafana/grafana/issues/65775
- [ ] https://github.com/grafana/grafana/issues/65776
```

```[tasklist]
### Documentation
- [ ] #64747
```

**Comment by grafanabot** [comment]
This issue was removed from the 9.4.0 milestone because 9.4.0 is currently being released.

**Comment by grafanabot** [comment]
This issue was removed from the 9.5.0 milestone because 9.5.0 is currently being released.

**Comment by mckn** [comment]
I think we can close this since we are done with everything except the Explore toolbar which soon is done.
