### ISSUE TITLE
Saga DS- Select Component [epic]

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#61679]
The current `Select` component has performance issues and does not meet the needs of Grafana. We need to better understand how this is being used to make improvements to the current component or replace with a higher performing component.

```[tasklist]
### Component Tasks
- [ ] Select component [explore]
- [ ] Select component [design]
- [ ] Select component [build]
- [ ] Select component [document]
- [ ] Select component [publish]
```

```[tasklist]
### Other
- [ ] https://github.com/grafana/grafana/issues/57675
```

[Explanation of phases and definitions of done](https://docs.google.com/document/d/1hcwu4YtAlq4jcqQVckdXB_PK2FZ6Kn2s3ri7-PCwaa4/edit?usp=sharing)

**Comment by joshhunt** [comment]
We have a seperate epic now that we're doing New Select Component
