### ISSUE TITLE
Saga DS - Content migration [epic]

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#61688]
There is a lot of existing content floating around that would be helpful to have in Saga. We want to find and migrate that content to Saga to provide an easy place of reference for anyone working with Grafana's UI

```[tasklist]
### Tasks
- [ ] #62039
- [ ] Content migration [design]
- [ ] Content migration [build]
- [ ] Content migration [document]
- [ ] Content migration [publish]
```

[Explanation of phases and definitions of done](https://docs.google.com/document/d/1hcwu4YtAlq4jcqQVckdXB_PK2FZ6Kn2s3ri7-PCwaa4/edit?usp=sharing)
