### ISSUE TITLE
Saga DS - IconButton [epic]

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#61683]
Improve consistency of `IconButton`

```[tasklist]
### Tasks
- [x] https://github.com/grafana/grafana/issues/62010
- [ ] https://github.com/grafana/grafana/issues/66515
- [ ] https://github.com/grafana/grafana/issues/64166
- [ ] https://github.com/grafana/grafana/issues/64164
- [ ] IconButton [publish]
```

[Explanation of phases and definitions of done](https://docs.google.com/document/d/1hcwu4YtAlq4jcqQVckdXB_PK2FZ6Kn2s3ri7-PCwaa4/edit?usp=sharing)

**Comment by natydej** [comment]
Actionable items for the next steps:

- [ ]  Clean up the styles
- [ ]  Alignment for size options
- [ ]  Documenting how we can/can't use the component
- [ ]  Create a ticket for each phase [design, build and document]

**Comment by staton-hyse11** [comment]
(This is a test)
### Findings

1. Thing
2. Thing
3. Thing

### Agreed Scope

1. Thing
2. Thing
3. Thing

### Next Steps

1. Thing
2. Thing
3. Thing

**Comment by staton-hyse11** [comment]
### Findings

1. Thing
2. Thing
3. Thing

### Agreed Scope

1. Thing
2. Thing
3. Thiing

### Next Steps

1. Thing
2. Thing
3. Thing

**Comment by staton-hyse11** [comment]
Closing this as it's done.
