### ISSUE TITLE
Saga DS - Card Component [epic]

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#61687]
There are many different versions of our card component throughout Grafana. Some cards are overwritten while others are custom one-offs. There is a need to provide a flexible and exhaustive solution for various use cases.

```[tasklist]
### Tasks
- [ ] #62040
- [ ] https://github.com/grafana/grafana/issues/75546
- [ ] https://github.com/grafana/grafana/issues/75548
- [ ] https://github.com/grafana/grafana/issues/75547
- [ ] Card component [publish]
```

[Explanation of phases and definitions of done](https://docs.google.com/document/d/1hcwu4YtAlq4jcqQVckdXB_PK2FZ6Kn2s3ri7-PCwaa4/edit?usp=sharing)

**Comment by Aires-Grafana** [comment]
**Q:** Why are you addressing the card component?

**A:** Our card components have been very inconsistent within the product and through a design debt effort this quarter, we are now measuring them. The card redesign will allow us to have a flexible component that can be implemented in various use cases to decrease the number of components we support (6 have been identified in the getting started flow!)
