### ISSUE TITLE
Saga DS - Package versioning [epic]

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#61689]
Decide on how we would like to version grafana/ui package, possibly independently from Grafana. Should take into consideration how plugins interact with this and how the Saga website would be versioned.

```[tasklist]
### Tasks
- [ ] #62027
- [ ] https://github.com/grafana/grafana/issues/69888
- [ ] Package versioning [document]
- [ ] Package versioning [publish]
```

[Explanation of phases and definitions of done](https://docs.google.com/document/d/1hcwu4YtAlq4jcqQVckdXB_PK2FZ6Kn2s3ri7-PCwaa4/edit?usp=sharing)

**Comment by staton-hyse11** [comment]
Phases for work
- [ ] Discovery
- [ ] Document
- [ ] Build
- [ ] Publish

**Comment by JoaoSilvaGrafana** [comment]
(keeping the original description here)

Decide:
- version UI package independently from Grafana
- Plugin packaging for UI package
- New/different NPM package for Saga

Do we want to track per/page versioning within Saga?

**Comment by staton-hyse11** [comment]
This was completed
