### ISSUE TITLE
Saga DS - Text Component [epic]

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#61686]
Create a new `Text` component in grafana/ui that developers can use directly instead of having to manipulate css properties like `font-size`, etc.

```[tasklist]
### Tasks
- [ ] #62092
- [ ] #66135
- [ ] https://github.com/grafana/grafana/issues/71415
- [ ] https://github.com/grafana/grafana/issues/66140
- [ ] https://github.com/grafana/grafana/issues/72659
- [x] Text component [publish]
```

```[tasklist]
### Others
- [ ] https://github.com/grafana/grafana/issues/68246
- [ ] https://github.com/grafana/grafana/issues/68389
```

### From experimental to proper component:
- Do not be within the _unstable_ package for more than two minor versions: `Text component` should be under **@grafana/ui** in **10.2.x**
- Get feedback from different devs and agree on | discuss what is needed to turn the _unstable_ component to a proper component.

[Explanation of phases and definitions of done](https://docs.google.com/document/d/1hcwu4YtAlq4jcqQVckdXB_PK2FZ6Kn2s3ri7-PCwaa4/edit?usp=sharing)
