### ISSUE TITLE
Epic: Scatter Plots the path to 1.0

### ISSUE THREAD

**Issue by codeincarnate** [grafana/grafana#61734]
Ongoing changes to bring the XY Chart out of beta, and bring XYZ to alpha, beta, and beyond.

### XY Chart

- [ ] https://github.com/grafana/grafana/issues/49763
- [x] https://github.com/grafana/grafana/issues/58798
- [ ] https://github.com/grafana/grafana/issues/57222
- [ ] https://github.com/grafana/grafana/issues/59037
- [x] https://github.com/grafana/grafana/issues/53582
- [ ] https://github.com/grafana/grafana/discussions/38193 (done for Timeseries, but probably not XY Chart)
- [x] https://github.com/grafana/grafana/issues/57221

### XYZ Chart

- [ ] https://github.com/grafana/grafana/pull/61445

**Comment by selvavm** [comment]
Hi,

I am not sure if this is the right place to ask this question but I will try. 

In my usecase, I will have 10 mins or 20 mins data based on the filter (dashboard variable). When I use timeseries panel, I see that either there is empty region or clipping as it does not reset the x-axis limits. So, a user has to manually zoom or drag which is not effective. 

I could see XY chart does it well and also double clicking on the plot resets the x-axis limits. 

However, XY chart does not support shared tooltip or shared zooming. Is there plans to support it?
