### ISSUE TITLE
IconButton [explore]

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#62010]
**Goal**
Understand how and where we are using the `IconButton` through a UI audit

**Tasks**
- [x] Investigate how `IconButton` is used throughout Grafana
- [x] Document findings from discovery
- [x] Review findings with Saga team
- [x] Create tasks for the following phases and assign

**Comment by staton-hyse11** [comment]
The below are items presented as "possible work" from the recent UX All-Hands meeting.

- [ ] Identify where it’s used
> - Grafana
> - Plugins
> - Look for [Button]
> - Look for [IconButton]
> - Custom components?

- [ ] Document use case
> - States
> - Styling
> - Accessibility

- [ ] Document behaviors
> - Does it use Tooltips
> - Limitations
> - Use cases

- [ ] Report out findings

- [ ] Team review process

**Comment by natydej** [comment]
Actionable items for the next steps:

- [ ] Clean up the styles
- [ ] Alignment for size options
- [ ] Documenting how we can/can't to use the component

**Comment by natydej** [comment]
Tasks are defined in each phase ticket.
