### ISSUE TITLE
Package versioning [explore]

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#62027]
**Goal**
Understand what are our options for the versioning of `grafana/ui` and of the Saga documentation.

```[tasklist]
### Tasks
- [x] Create a DesignDoc with the proposed options
- [x] Share broadly to gather feedback
- [x] Review findings with Saga team
- [x] Create tasks for the following phases and assign
```
