### ISSUE TITLE
Epic: [GA] Improved dashboard browse view

### ISSUE THREAD

**Issue by zsofiakm** [grafana/grafana#62024]
**Folder hierarchy display:** To provide a clear overview of the organization of resources within Grafana, we will be implementing the display of the folder hierarchy in the Browse view. This will allow users to easily see the structure and location of different dashboards and alerts within the system.

**Improved loading time:** As the number of folders and dashboards within Grafana increases, it is important to ensure that the system remains performant. To optimize loading times, querying has to become more performant.

```[tasklist]
- [ ] Decouple UI from BE changes, gating our code behind NestedFolder OR newBrowseUI (see [draft PR](https://github.com/grafana/grafana/pull/72162/files#diff-e30e0ab2225aa18f0d41c48fd3f2772308ea09ab149195eb3be8657b17c725e8R5) )
- [ ] Write rollout plan (see [Nested Folder Rollout](https://docs.google.com/spreadsheets/d/1mdU5GqAlN1269oSZIczcBodtXh_QIwrDtCxP7y6rNYc/edit#gid=987994848) )
- [ ] Copy [this Dashboard](https://ops.grafana-ops.net/d/ff12963b-e917-4e81-b737-db12b0aba450/fe-platform-subfolders?orgId=1) to monitor new feature toggle
- [ ] Create enablement video
- [ ] Rollout

```

### bugs
- [ ] https://github.com/grafana/grafana/issues/64210
