### ISSUE TITLE
Content migration [explore]

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#62039]
**Goal**
Migrate existing components and documention to Saga

```[tasklist]
### Tasks
- [x] checkbox
- [x] radio
- [ ] toggle/switch
- [x] input
- [x] Textarea
- [x] Slide
- [x] Autosave
```

**Comment by staton-hyse11** [comment]
We could do interviews with various teams or build a poll/form to send out asking for submissions.

**Comment by natydej** [comment]
In order to update this content, the following steps must be taken:

- [ ] Checkbox
- [ ] - [ ] Design Visual Assets 
- [ ]     - [ ] (do-don’ts)
- [ ]     - [ ] Anatomy
- [ ]     - [ ] Alignment
- [ ]     - [ ] Placement
- [ ] - [ ] Finalise the documentation for the “Usage”
- [ ] 
- [ ] RadioButtonList
- [ ] - [ ] Design Visual Assets
- [ ]     - [ ] (do-don’ts)
- [ ]     - [ ] Anatomy
- [ ]     - [ ] Alignment
- [ ]     - [ ] Placement
- [ ] - [ ] Finalise the documentation for the “Usage”
- [ ] 
- [ ] 
- [ ] Switch
- [ ] - [ ] Create the page in Saga
- [ ] - [ ] Design Visual Assets
- [ ]     - [ ] (do-don’ts)
- [ ]     - [ ] Anatomy
- [ ]     - [ ] Alignment
- [ ]     - [ ] Placement
- [ ] - [ ] Write all the documentation
- [ ] 
- [ ] 
- [ ] Input
- [ ] 	Create a page in Saga
- [ ] 	Documentation [done](https://docs.google.com/document/d/1TGqqz29ZCNfsEEAEqzWTY4j7ZyzQP4GpM4x-dnxbwWQ/edit)
- [ ] - [ ] Design Visual Assets
- [ ]     - [ ] (do-don’ts)
- [ ]     - [ ] Anatomy
- [ ]     - [ ] Alignment
- [ ]     - [ ] Placement
- [ ] 
- [ ] TextArea
- [ ] 
- [ ] - [ ] Create a page in Saga
- [ ] - [ ] Write all the documentation
- [ ] - [ ] Design Visual Assets
- [ ]     - [ ] (do-don’ts)
- [ ]     - [ ] Anatomy
- [ ]     - [ ] Alignment
- [ ]     - [ ] Placement
- [ ] 
- [ ] Slider
- [ ] - [ ] Need to investigate if need to add the variant of “With marks” in Figma to match Storybook
- [ ] - [ ] Design Visual assets
- [ ]     - [ ] Behaviors - states

**Comment by natydej** [comment]
[Documentation](https://docs.google.com/document/d/1PHoXFOnhMaswPUC2JyjBCz6idPIivSFZ7Wl0rGpE-pU/edit#) for checkbox ready to review, also the [visual assets](https://www.figma.com/file/Ft7z7ysVzVhtCf7SFlvzyN/Saga-Visual-Assets?type=design&node-id=402-1533) for Saga

**Stakeholders:**
@staton-hyse11 @JoaoSilvaGrafana

**Comment by natydej** [comment]
[Documentation](https://docs.google.com/document/d/1BlFTFTwBagerfFxrTPx9diiSDmkkj_Y_GzKhkbTHZgQ/edit#) for Switch need to be paused until we have the last design of the forms using this component.

**Comment by staton-hyse11** [comment]
This work is complete
