### ISSUE TITLE
Card component [explore]

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#62040]
**Goal**
Identify the various current card component solutions and understand the needs for them

**Tasks**
- [x] Audit the UI to identify as many types of cards components we have
- [x] Review audit findings with the Saga Team
- [x] Agree on how to unify the current offerings and what new options are needed
- [x] Scope out the next phases of work

**Comment by staton-hyse11** [comment]
This would be a good candidate to have the designers provide their designed solutions for the focus areas in a Figma file

**Comment by Aires-Grafana** [comment]
The explore work was done with the UI Audit, and it was presented and reviewed with Saga team.
It was defined on what we need to do next to make the component flexible and aligned for the majority of use cases.
Agreed that a possible slot component with swap instance prop availability would be a great fit for edge cases combined with a well stablished guidelines and documentation on how to create content for the card component.

[Audit work](https://www.figma.com/file/4cqbHRRcRm59FOIdbtPotP/Saga---Card-Component?type=design&node-id=1-9175&mode=design) in Figma.
[Exploratory work ](https://www.figma.com/file/4cqbHRRcRm59FOIdbtPotP/Saga---Card-Component?type=design&node-id=1-15060&mode=design)in Figma.
