### ISSUE TITLE
Data source selector

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#62083]
**Goal**
As a user of a newly created panel, I want to easily select the data source I want to query. 

**Requirements & Caveats**

- Support for the drag&drop functionality created by @grafana/grafana-bi-squad 
- Should align with explore

**Task list (optional)**
```[tasklist]
- [x] https://github.com/grafana/grafana/issues/63649
- [x] https://github.com/grafana/grafana/issues/65050
- [x] https://github.com/grafana/grafana/issues/66407
- [x] https://github.com/grafana/grafana/issues/66915
- [x] https://github.com/grafana/grafana/issues/66875
- [ ] https://github.com/grafana/grafana/issues/66922
- [ ] https://github.com/grafana/grafana/issues/66944
- [x] Display a 🔍 icon when the dropdown is open and the user can search instead of the anchor
- [ ] https://github.com/grafana/grafana/issues/67897
```

**Resources**

- [Figma file](https://www.figma.com/file/QGmQM1TS5ufz3u6w0H8Z2H/Panel-edit?node-id=0%3A1&t=PLQ1GRuFFuVh0uif-0)
- [Design doc](https://docs.google.com/document/d/1ey_YbvTXsMjdroN3ltiGtQ8KG2K_2VDfKcjMcc-oiyE/edit#heading=h.5sybau7waq2q)
- [Product DNA](https://docs.google.com/document/d/1GMCK7ayKdht4p-SaMPr1ohAQFWfEkPgYopEjvi0zr8k/edit?usp=sharing)
