### ISSUE TITLE
Text component [explore]

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#62092]
**Goal**
Understand what are the requirements for a `Text` component

**Tasks**
- [x] Investigate how typography is used throughout Grafana
- [x] Research other design systems to gather how other `Type`/`Text` components are built and what properties they have
- [x] Document findings from discovery
- [x] Review findings with Saga team and agree on what structure the component will have
- [x] Create tasks for the following phases and assign

**Comment by staton-hyse11** [comment]
Recent discussion is this will be expanded to exploring creating a type-system that scales and refactoring our typography scale as a whole.

**Comment by JoaoSilvaGrafana** [comment]
Exploration for the component: https://docs.google.com/spreadsheets/d/1yq4K-JjS-8eAM6XhxHiCHwKj2S9WOA4A2WTEhxHVxnc/edit#gid=793665239

Sheet explanation:
- Proposed props: Finalized list of the props to include in the component (question regarding if we should allow overriding the `weight` prop)
- Other DS exploration: How other design systems define their text components and with which props
- Used styles: Grouped list of props used in Grafana to override regular styles from headers (researched in the next tabs)
- h1 - h6: List of usages of these elements and what style was being set on them

**Comment by torkelo** [comment]
@JoaoSilvaGrafana @staton-hyse11 if color is only the colors.text (primary, secondary, disabled, link) it won't be able to create text with colors error, warning or success. I think those colors are needed as well. So might need to add a new TextColor type that is a union of the keys of colors.text and primary.text | error.text | warning.text etc 

Or we add error, warning, success to the colors.text object (and make them the same as colors.primary.text) but it becomes tricky with colors.text.primary (dark/light) and colors.primary.text (blue)

**Comment by JoaoSilvaGrafana** [comment]
Ah good catch @torkelo ! In my explorations I missed that there are a couple of components that use that. I think it is good enough to just do a type union, instead of adding more things to the `colors.text` object 👍
