### ISSUE TITLE
Task: Change pubdash footer and add title logo

### ISSUE THREAD

**Issue by juanicabanas** [grafana/grafana#62370]
Now we will always have the pubdash title after a conversation with Torkel. So, does it make sense to put the Grafana footer **powered by Grafana** next to the title? It was a Torkel's suggestion and would be good to have a discussion with the UX team and see if it makes sense and it's prettier

![Screenshot 2023-03-14 at 14 38 23](https://user-images.githubusercontent.com/20256983/225091366-3120ff89-222d-4334-bf49-a7f55b0f6731.png)

### Solution
The designs are below:

**Desktop:**
<img width="1440" alt="PubdashLogo-Desktop" src="https://github.com/grafana/grafana/assets/51436795/bf0886bb-60c6-4dc2-adb2-ae4aabb34678">

**Tablet:**
<img width="820" alt="PubdashLogo-Tablet" src="https://github.com/grafana/grafana/assets/51436795/92d667e4-6134-4ef5-8208-09a536954182">

**Mobile:**
<img width="360" alt="PubdashLogo-Mobile" src="https://github.com/grafana/grafana/assets/51436795/6372ec59-2a4a-4fa7-9b20-103b14680ad9">

[Figma Link](https://www.figma.com/file/sPfx0P9xsSRVwCEBskyb1O/Public-Dashboards---Email?type=design&node-id=0-1&mode=design)
```[tasklist]
### Tasks
- [x] Add new config key to hide the Grafana logo when enterprise
- [x] Add new config key to public dashboard documentation: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/configure-custom-branding/
- [x] Add title logo
- [x] Modify footer
- [x] Add referrer to grafana.com
- [ ] Add enterprise doucumentation: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/enterprise-configuration/
```

**Comment by juanicabanas** [comment]
what about mobile view?

**Comment by juanicabanas** [comment]
@Ijin08 can you help us in this decision for G10?

This is the desktop POC 

![Image](https://user-images.githubusercontent.com/11707172/232868572-0ab1627f-e2aa-4c42-959e-21f4668bc66c.png)


And in mobile, we would leave it as it is



![Image](https://user-images.githubusercontent.com/11707172/232868675-30682101-02a2-4792-b02d-7b234b3f0512.png)

**Comment by juanicabanas** [comment]
Suggested designs to define with @natydej 
https://www.figma.com/file/sPfx0P9xsSRVwCEBskyb1O/Public-Dashboards---Email?node-id=0%3A1&mode=dev

**Comment by torkelo** [comment]
looks good

**Comment by natydej** [comment]
Proposal attached:

<img width="1440" alt="PubdashLogo" src="https://github.com/grafana/grafana/assets/51436795/0c1bded7-90dc-4c71-83c4-0fa5408fa2a7">
[Figma Link](https://www.figma.com/file/sPfx0P9xsSRVwCEBskyb1O/Public-Dashboards---Email?type=design&node-id=0-1&mode=design)

The idea is to have only the icon of the Grafana logo next to the title, considering users who are familiar with Grafana, also, have the "Powered by Grafana" link on the footer for those who are not familiar with the company yet. The main goal is to have visibility for adoption.

**Comment by juanicabanas** [comment]
Something to take into account is that the footer can be customized thanks to the while label enterprise feature.

- I noticed the font size has changed. Should we also change the font size for the white label footer?
- If we want to change the footer from "<text> <G logo>" to be: "<text> <G logo> <text>" like Powered by <G> Grafana, we would need to make an extra change. However, we could take the whole "<G> Grafana" as a logo and just a little change would be necessary. I couldn't find in the repo the  "<G> Grafana" logo, but I did find another that is "<G> Grafana Labs"

![Image](https://github.com/grafana/grafana/assets/11707172/57ccc5ba-2a30-4596-baed-6c93b0853551)

**Comment by juanicabanas** [comment]
Waiting for confirmation if we should add a new setting to customize the logo next to the title.

**Comment by juanicabanas** [comment]
If new settings will be added, it's necessary to also modify [this documentation](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/configure-custom-branding/)

**Comment by juanicabanas** [comment]
After a talk with @thanos-karachalios, 2 new white label config keys will be added in order to: 

- Hide the title logo
- Customize the title logo

**Comment by evictorero** [comment]
We want to increase MAUs. We should evaluate after this task adding a CTA to [grafana.com](https://grafana.com/) (maybe with a referer) and tracking this click as well.
