### ISSUE TITLE
Milestone: Public Dashboards v4🤑

### ISSUE THREAD

**Issue by jalevin** [grafana/grafana#62372]
Theme: Launch beta, make some 💵, listen to our customers!

Public dashboards has been out in the wild for us to [gather feedback ](https://github.com/grafana/grafana/discussions/49253)and we have a [monetization strategy](https://docs.google.com/document/d/1iBb6rw9270_y2PKR2BOQvSFDFQYnhiXBMYYBoypZCOE/edit#heading=h.8dt6c26884i). There's an agreement in place with Pismo for additional usage on passphrase protected public dashboards and we know that the next major feature to complete will be template variables. What we don't know is WHEN it will be possible to complete as there are a lot of moving pieces. So in the meantime, let's make it official and launch beta while we get started!

[Project folder](https://drive.google.com/drive/folders/1mLQjXeJAMrWG5PexKoF41r53Q4XSIU7y)

### Epic: Design Variables Support - grafana/grafana-partnerships-team#388 
- [x] grafana/grafana-partnerships-team#459
- [x] grafana/grafana-partnerships-team#527
- [ ] Design Doc - https://docs.google.com/document/d/1k0_1AetcuUsJxIWZz5sDMHPd2vpndXh4tnxak42768E/edit#heading=h.5sybau7waq2q
- [ ] grafana/grafana#62395 
- [x] grafana/grafana-partnerships-team#172 
- [ ] grafana/grafana-partnerships-team#161 
- [ ] Product DNA
- [ ] POC
- [ ] Design document (decision)
- [ ] Delivery Plan (probably only support core datasource plugins)
- [ ] Implementation document (technical)
- [ ] 1 pager (consensus)
- [ ] Spike: Is variable support worth our time

### Research
- [x] https://github.com/grafana/grafana/issues/62392
- [ ] https://github.com/grafana/grafana/issues/62389
- [x] https://github.com/grafana/grafana/issues/62393
- [ ] https://github.com/grafana/grafana/issues/62383

### Enhancements

- [ ] grafana/grafana-partnerships-team#427 
- [ ] grafana/grafana-partnerships-team#426
- [x] grafana/grafana-partnerships-team#464 
- [ ] grafana/grafana#62380 
- [ ] grafana/grafana#62382

### Tech Debt
- [ ] grafana/grafana#62377 
- [x] grafana/grafana-partnerships-team#469
