### ISSUE TITLE
Story: Make public dashboards audit table more responsive and improve design

### ISSUE THREAD

**Issue by owensmallwood** [grafana/grafana#62376]
See [thread](https://raintank-corp.slack.com/archives/C03DA734R3N/p1668589483027469)

TLDR: Row buttons dont match other tables. Table doesn't look great on smaller/mobile views. Torkel suggested using cards instead of a table for the smaller views. 
![Screenshot 2023-03-14 at 14 43 49](https://user-images.githubusercontent.com/20256983/225092529-e40a380e-c4a5-4f8c-841e-97015660ed25.png)

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/68136
- [ ] https://github.com/grafana/grafana/issues/68141
- [ ] https://github.com/grafana/grafana/issues/78313
```

**Comment by juanicabanas** [comment]
@Ijin08 can you help us on this? We want to add pagination and a search bar like this design. 

![Image](https://user-images.githubusercontent.com/11707172/236934339-d7ed00c1-8a31-4f30-87f3-8a426a1b96e0.png)

 Is it correct?
And we would need to modify at least the blue color on the icons. Which would be a good solution?

Thanks

**Comment by juanicabanas** [comment]
- [ ] Change design and use Card component
- [ ] Add pagination
- [ ] Add search input

**Comment by natydej** [comment]
This issue will be addressed when we update this design for the public dashboard page -[ issue related ](https://github.com/grafana/grafana/issues/82303)

Design:
<img width="1440" alt="PublicDashboardPage" src="https://github.com/grafana/grafana/assets/51436795/b11f2a75-8920-44ef-8fc3-d196379f8fd3">
