### ISSUE TITLE
Add user tracking to new nav elements

### ISSUE THREAD

**Issue by yaelleC** [grafana/grafana#62474]
When going live with Navigation GA, we want to get numbers of interactions with our new megamenu:

- [x] Add a `grafana_breadcrumb_clicked` event to BreadcrumbItem onClick
- [x] Add `grafana_toggle_menu_clicked` event with `collapsed` prop (to identify whether megamenu is opened or closed)
- [x] Add the same `grafana_navigation_item_clicked` event for secondary nav. With a new `secondaryNav = true` prop (to distinguish e.g. between a click on `onCall` from the megamenu sub title and one on `onCall` from the secondary nav header)

**Comment by yaelleC** [comment]
Adding here for visibility:

* for `grafana_breadcrumb_clicked`, we could add the url from the breadcrumb as a prop on the event
* for `grafana_toggle_menu_clicked`, we could have a better name for the prop so as to avoid confusion around the timing for collapsed (is it the state before toggle or after). e.g. we could have `action` with `open `and `close` values?
