### ISSUE TITLE
Add panel selecting a DS as onboarding experience

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#62493]
### Scope
Continuation of https://github.com/grafana/grafana/issues/58218. Defines what's needed for the Datasource connection feature to go GA.

### Requirements & Caveats

```[tasklist]
### For G10 Under FF: First stable version to gather feedback and data
- [ ] https://github.com/grafana/grafana/issues/65049
- [ ] https://github.com/grafana/grafana/issues/62343
- [ ] https://github.com/grafana/grafana/issues/65585
- [ ] https://github.com/grafana/grafana/issues/65588
- [ ] https://github.com/grafana/grafana/issues/65833
- [ ] https://github.com/grafana/grafana/issues/66659
- [ ] https://github.com/grafana/grafana/issues/67239
- [x] Direct "New Datasource" button to connections page if toggle is enabled
- [ ] Enable FF in Canary
```

```[tasklist]
### Feedback G10-preview: Bugs or improvements
- [ ] https://github.com/grafana/grafana/issues/67700
- [ ] https://github.com/grafana/grafana/issues/67894
- [ ] https://github.com/grafana/grafana/issues/67709
- [ ] https://github.com/grafana/grafana/issues/67805
- [ ] https://github.com/grafana/grafana/issues/66917
- [ ] https://github.com/grafana/grafana/issues/66946
- [ ] Update the E2E plugin repository supporting the new flow
- [ ] Create new E2Es to make sure the new onboarding works
- [ ] https://github.com/grafana/grafana/issues/68316
```

### Docs

- [Product DNA](https://docs.google.com/document/d/1MOIQGDO0sOqk1A4ggJ91VidXoYLk2dcGP-e4y2d2Y7A/edit?usp=sharing)
- [Figma](https://www.figma.com/file/QGmQM1TS5ufz3u6w0H8Z2H/Panel-edit?node-id=367-16845&t=HT6ANivik7hX8B40-0)
- [FigJam Critical User Journey](https://www.figma.com/file/CAjSIYwYh9VTGCdoRdEUbK/CUJ%3A-Datasource-connection-with-Dashboards?node-id=0%3A1&t=LjwQgToS3pPkLZd9-1)
- [Delivery plan](https://docs.google.com/document/d/10OS_1tGApW1pHEyaKRskHzUwwzml7xlIPO48csqNzuk/edit#)

**Comment by thanos-karachalios** [comment]
After discussion with @ivanortegaalba and @Ijin08 

- Not replicate OSS solution flow[depending POC outcome]
- Follow flow through standard screens: "Empty State Dashboard" #60108 , "DS selection modal" #62083 and "Collections Page"
- Current issue with the suggested solution, is user flow breaks with the initial dashboard creation flow. @ivanortegaalba to check feasibility of user journey continuation through Connections page flow (Check [FigJam Option 1 Flow](https://www.figma.com/file/Kvamy9CjSbN9tsCBaSmO91/Cloud-onboarding-flow-diagrams?node-id=0%3A1&t=7mR5YeZv9HB3LghJ-0))
- If the above is not feasible through the POC, we are not effectively solving the onboarding of new users. In such case @Ijin08 creates a screen similar to OSS solution

**Comment by thanos-karachalios** [comment]
After discussion with @ivanortegaalba and @Ijin08 and based on the outcomes of POC:

- @Ijin08 creates a screen similar to OSS solution. This is applicable only on first time dashboard author as described in Product DNA doc. Some preliminary designs exist when initially scoping the feature between @thanos-karachalios and @ivanortegaalba for Patrick to start with. Thinking of time to G10 we can exclude suggested dashboards out of scope for now.

- Review the appropriate wording or text in the CTA of modal in creating new viz in existing dashboards.

- @Ijin08 to create flows for first time authors and behaviour of modal in existing dashboards

Inline/in-context DS config would provide a new perspective scoping the solution and is best to think about it overall holistically post G10
