### ISSUE TITLE
EPIC: Deliver Remote Panel Plugins via CDN for Hosted Grafana

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#62607]
**Why?**
Tracking Epic for our work on enabling loading panel plugins via CDN on Hosted Grafana

```[tasklist]
### Tasks
- [x] https://github.com/grafana/deployment_tools/pull/55924
- [x] https://github.com/grafana/grafana/pull/59096
- [x] https://github.com/grafana/deployment_tools/pull/56446
- [ ] https://github.com/grafana/grafana/issues/71635
```

☝️ `tasklist` is a broken feature so creating simplified list below:

- [x] Phase 1: Backfill plugin CDN
- [x] Phase 1: https://github.com/grafana/grafana/pull/63202
- [x] Phase 1: Verify panel plugins are functional
- [x] Phase 1: https://github.com/grafana/plugins-cdn-tools/issues/5
- [x] Phase 1: Configure multiple panels in Ops
- [x] Phase 2: Fetch plugin.json remotely https://github.com/grafana/grafana-enterprise/pull/4797
- [x] ~Phase 2: Fetch MANIFEST.txt remotely~ (only signed plugins are permitted on the CDN)
- [x] Phase 2: Ensure no loading from disk
- [x] Phase 2: Build dashboard to track CDN impact in HG
- [x] Phase 2: Fix faro collection in HG to keep track of frontend errors https://github.com/grafana/hosted-grafana/issues/4385
- [x] Phase 2: Rollout to instances https://github.com/grafana/hosted-grafana/issues/3669
- [x] Phase 2: Validate goal reached with HG https://github.com/grafana/hosted-grafana/issues/3716
- [x] Phase 2 (if necessary): load plugin.json and module.js concurrently (https://github.com/grafana/grafana-enterprise/pull/4845)

(if goal reached with HG):
- [ ] Phase 3: Figure out how to handle signature verification for CDN plugins
- [x] Phase 3: Upload new plugins to CDN as soon as they are published

**Comment by tolzhabayev** [comment]
fyi @wbrowne @xnyo please use this issue to track ongoing work

**Comment by tolzhabayev** [comment]
@xnyo closing this epic, we can continue single bigger improvements via new epics.
