### ISSUE TITLE
NestedFolders: Basic Alpha

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#62848]
First stage for supporting nested folders in the Grafana frontend will be the bare minimum changes to create, view, update, and delete folders in the existing folder view UI to test out the backend and discover any other shortcomings. The interface may not be ideal, but it also should not be buggy or have feature/buttons/etc that simply don't do anything.

```[tasklist]
### Basic nested folders CRUD
- [x] Create folders inside other folders https://github.com/grafana/grafana/pull/59126
- [x] Refactor frontend Browse/Search types https://github.com/grafana/grafana/pull/63162
- [x] Show nested folders https://github.com/grafana/grafana/pull/63746
- [ ] https://github.com/grafana/grafana/issues/65265
- [ ] https://github.com/grafana/grafana/issues/65288
- [x] Breadcrumbs for nested folders should reflect it's hierarchy
- [x] Fix folder's parent showing as "General"
```

```[tasklist]
### Testing checklist
- [x] Rename nested folders (confirm no regressions)
 - [ ] Library panels work with nested folders
 - [ ] Alerts work with nested folders
- [ ] https://github.com/grafana/grafana/issues/65272
```

```[tasklist]
### Nice to haves (for 9.5)
- [ ] Show folder's parent folder in FolderPicker
- [x] Improve styling of folders vs dashboard in Folder view, to help differentiate them
- [ ] https://github.com/grafana/grafana/issues/65514
- [ ] https://github.com/grafana/grafana/pull/65661
```

```[tasklist]
### Post-alpha (new epic)
- [ ] https://github.com/grafana/grafana/issues/65289
```

**Comment by kdrapel** [comment]
A very much needed feature for very very long time, people already mentioned this back in 2018...

**Comment by grafanabot** [comment]
This issue was removed from the 9.5.0 milestone because 9.5.0 is currently being released.
