### ISSUE TITLE
Nested Folders: Strict constrain on nested folder titles

### ISSUE THREAD

**Issue by papagian** [grafana/grafana#63082]
**What happened**:

Previously there was no a dedicated table for folders: they were stored in the `dashboard` table (with a `is_folder` flag set).
As part of the work in the nested folders: we introduced a table dedicated for folders (`folder`).
The `folder` table requires [folder titles to be unique under a folder](https://github.com/grafana/grafana/blob/f46f8bdd3acef271b77af9a98ceb2edf3bba3c9a/pkg/services/sqlstore/migrations/folder_mig.go#L25-L28).  The `dashboard` table also requires [the folder titles to be unique under a folder](https://github.com/grafana/grafana/blob/33277fccde146e49e2eb4f3f8afdf8c091ff7076/pkg/services/sqlstore/migrations/dashboard_mig.go#L176).
When creating a nested folder, for keeping [backward compatibility](https://docs.google.com/document/d/1trRt3KDJxBXa8khgmQgZB0n7KtVXE1UGX4v11FDBUv8/edit#heading=h.qdidspdfg89) we create an entry both in the `dashboard` table and in the new `folder` table.
However,  during folder creation when we insert the entry in the `dashboard` store we don't set the `folder_id` for folders. In fact, there is a check that prevents us:
https://github.com/grafana/grafana/blob/5f5f51b3bfba1d3b6f04847f15f81d6b78b97ce4/pkg/services/folder/folderimpl/folder.go#L605-L607

Hence, it's impossible to have the following folder structure:
- parent folder
	- subfolder
		- subfolder
		
Besides a frontend check prevents also this:
<img width="1240" alt="Screenshot 2023-02-08 at 12 52 26 PM" src="https://user-images.githubusercontent.com/1632407/217510919-30f194a7-d936-4cc9-b9eb-ddf8cc7b3aa5.png">

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/pull/72602
- [ ] https://github.com/grafana/grafana/issues/58184
- [ ] https://github.com/grafana/grafana/pull/74725
- [ ] https://github.com/grafana/grafana/pull/75817
- [ ] https://github.com/grafana/grafana/issues/74671
- [x] add schema migration for dashboard table to add `folder_uid` column
- [x] add data migration at the dashboard service startup to populater the `folder_uid` column
- [x] update dashboard service to store `folder_uid`
- [x] drop unique index on dashboard table using `folder_id`
- [x] introduce unique index on dashboard table using `folder_uid`
```

**Comment by grafanabot** [comment]
This issue was removed from the 9.5.0 milestone because 9.5.0 is currently being released.

**Comment by yuri-tceretian** [comment]
Issue https://github.com/grafana/grafana/issues/58184 may be a blocker for removing this constraint because Alerting API refers to a folder by it's name.
