### ISSUE TITLE
Panel header GA

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#63093]
### Scope
Continuation of #56163  Defines what's needed for the new panel header to go GA.

### Resources
* [Product DNA](https://docs.google.com/document/d/1zvK4slC8A7BlzkWL7EMhGXKOF6M3qAXr6H3P_TURlNE/edit)
* [Figma design](https://www.figma.com/file/jdTCXlq75p55itRRSaerFx/Panel-header-and-menu?node-id=2672%3A235&t=ZN8EBdyt0FTXhSFA-0)
* [Dovetail feedback from the first iteration](https://grafana.dovetailapp.com/projects/6QS5OMSb3xUOxC4ngrkFuZ/readme)
* [Data Insights and Analysis](https://docs.google.com/document/d/1dmA9IdbTnhfp90KzeH4FUHV17VUt9994J0FiofWsrQk/edit#heading=h.hkzoain5mb26)
* [Rollout plan](https://docs.google.com/spreadsheets/d/1OuKqq1RQnhD7R3rnE45eBVdHQDQvf_tL-ybmnokXpvg/edit#gid=406187327)

#### Existing issues ([Dashboard](https://ops.grafana-ops.net/goto/_gnNm3bVR?orgId=1) to test this issues with new panel header)

- [x] https://github.com/grafana/grafana/issues/25930 --- tested: solved by new panel header
- [x] https://github.com/grafana/grafana/issues/56526 --- tested: solved by new panel header
- [x] https://github.com/grafana/grafana/issues/49070 --- tested: solved by new panel header
- [x] https://github.com/grafana/grafana/issues/63372 --- tested: solved by new panel header
- [x] https://github.com/grafana/grafana/issues/52010 --- tested: solved by new panel header
- [x] https://github.com/grafana/grafana/issues/51813

### Tasks
- [x] Improve menu discoverability on desktop and mobile: Add more contrast to the menu --- https://github.com/grafana/grafana/pull/64492
- [x] #64512
- [x] Add Cancel Query Option https://github.com/grafana/grafana/pull/64796
- [x] Improve status alert: Change the position to be on the left next to the title and not in the middle ---> https://github.com/grafana/grafana/pull/63776
- [x] #64542
- [x] #59079 
- [x] #64600
- [x] #63501 -- @ivanortegaalba 
- [x] #64701
- [x] Write documentation ([Draft PR](https://github.com/grafana/grafana/pull/65073))
- [x] Plan rollout
- [x] #61553 --- Done https://github.com/grafana/grafana/pull/63040
- [x] Dashboards: Enable feature flag newPanelChromeUI by default #65593

Require input from UX 
- [x] #60672 ---- Rethinking loading states?
- [x]  https://github.com/grafana/grafana/pull/63776

### Post GA 9.5 
- [ ] #61569
- [ ] #61597
- [ ] #59082
- [ ] #66282

#### For 10.0.0
- [ ] #59398

**Comment by grafanabot** [comment]
This issue was removed from the 9.5.0 milestone because 9.5.0 is currently being released.

**Comment by natellium** [comment]
@axelavargas closing this as an epic. We can tackle the remaining through the individual issues.
