### ISSUE TITLE
Unify onboarding experience across on-prem and Cloud

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#63175]
### Goal
The current onboarding experience of creating your first dashboard and setting up a datasource is different on Cloud and on-prem. We're aiming to unify this while making it easier for the users to set up their first dashboard with data.

### Requirements & Caveats
- Currently, for the onboarding wizard, there is a custom-defined experience to get the users started with creating a dashboard
- With the efforts recently made to add a landing page for an empty dashboard and create a panel, the wizard is kind of embedded into he experience
- There is a part missing, the pre-built dashboards. Which are present in the wizard but not in the core product. Having that piece covered, we can direct users to the dashboard without any custom wizard.

### Tasks
- [x] Ideate possible solutions
- [x] Write Product DNA
- [x] Sync with @aligerrard about how to apply the learnings from the wizard to use them in the core product
- [ ] Do a PoC to test a new flow to include everything the wizard has into the core experience
    - [ ] Add the pre-built dashboards into the creation flow. Probably in the empty state
    - [ ] (Verify this hypothesis and collect use cases) Enable "create a panel into dashboard" by URL. Nowadays the panel can only be added clicking from the empty page once the dashboard is created. But you cannot access to add the first panel into a dashboard by URL. This is useful to point links into the dashboard edition.
- [x] https://github.com/grafana/grafana/issues/71362 

### Resources

1. [Figma](https://www.figma.com/file/RqCjSrm8uj0Xa003mfAfel/Dashboards-G10?node-id=1253-4870&t=IvjV1umlonCDWnpy-0)
2. [Product DNA](https://docs.google.com/document/d/1DUQfitoYFyOF3xEYCxNlyrZuDR62lohxXo26Pgac8wM/edit#heading=h.lo4c6e71q7vo)
3. [Analytics](https://docs.google.com/document/d/1CkV87S6n9oLVr8cG-Aapc6pVQxQtotfxWOBsZ05-vJY/edit#)

**Comment by natellium** [comment]
@ivanortegaalba do we want to keep this open?

**Comment by ivanortegaalba** [comment]
> @ivanortegaalba do we want to keep this open?

I'd say no. We already had some unification work:
* Optimized empty state
* Improved import to access community templates
* Connect "Build a dashboard" from datasources views
* New DS picker

So I'd consider this as "Won't do"
