### ISSUE TITLE
Keep improving ease of use of Grafana Alerting

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#63177]
```[tasklist]
### Simpler alert rule creation process
- [x] https://github.com/grafana/grafana/issues/61832
- [x] https://github.com/grafana/grafana/issues/36336
- [ ] https://github.com/grafana/grafana/issues/60576
- [ ] https://github.com/grafana/alerting-squad/issues/404
- [ ] https://github.com/grafana/grafana/issues/35699
- [ ] https://github.com/grafana/grafana/issues/62649
- [ ] https://github.com/grafana/grafana/issues/49009
```

```[tasklist]
### Improve notification and alert management 
- [ ] https://github.com/grafana/grafana/issues/62650
- [ ] https://github.com/grafana/grafana/issues/60578
- [ ] https://github.com/grafana/grafana/issues/60580
- [ ] https://github.com/grafana/grafana/issues/62652
```

```[tasklist]
### Templating / notifications improvements (see epic issue)
- [ ] https://github.com/grafana/grafana/issues/60387
- [ ] https://github.com/grafana/grafana/issues/63258
- [ ] https://github.com/grafana/grafana/issues/63349
- [ ] Add reference template
```

```[tasklist]
### Miscellaneous
- [] https://github.com/grafana/grafana/issues/62870
- [ ] https://github.com/grafana/grafana/issues/48353
- [ ] https://github.com/grafana/grafana/issues/53151
- [ ] grafana#57846
- [ ] https://github.com/grafana/grafana/issues/55320
- [ ] https://github.com/grafana/alerting-squad/issues/331
- [ ] https://github.com/grafana/grafana/issues/56009
- [ ] https://github.com/grafana/alerting-squad/issues/351
- [ ] https://github.com/grafana/grafana/issues/62969
- [ ] https://github.com/grafana/grafana/issues/59721
- [ ] https://github.com/grafana/grafana/issues/60713
- [ ] https://github.com/grafana/grafana/issues/62969
- [ ] https://github.com/grafana/alerting-squad/issues/345
- [ ] https://github.com/grafana/grafana/issues/62587
- [ ] https://github.com/grafana/grafana/issues/43855
- [ ] https://github.com/grafana/grafana/issues/63988
```

**Comment by grafanabot** [comment]
This issue was removed from the 9.5.0 milestone because 9.5.0 is currently being released.
