### ISSUE TITLE
Scenes: Milestone 2

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#63433]
**Goal**
After a successful PoC (see https://github.com/grafana/grafana/issues/58889), our next objective will be to continue establishing the framework internally by:
* Continue evolving the Scenes framework with a focus on app plugins, have one internal plugin running Scenes in prod by G10
* Facilitate resources for the adoption of the framework
* Support more core functionality

**Requirements & Caveats**
* Our efforts should be align with the As Code initiative. As discussed, to ensure this we won't make any changes to the existing dashboard JSON.

**Tasks**

- [x] Decide which plugin we will focus on for G10.
- [ ] Typed visualizations: Make core viz types available from grafana/schema so that these can be used in grafana/scenes. 🏃 @dprokop 
- [x] Setup documentation page for scenes (see [docs scope](https://docs.google.com/document/d/1ul5iE6Q-CFhjbu9SOe-6LbsC71hobiSnYkHvdrXq014/edit#heading=h.ywfg0vfzh7sy)).
- [ ] Solve fundamental UX problems with Scenes as apps (ref [Scenes apps UX challanges](https://docs.google.com/document/d/13CafKOo4y3icTmocU4H2-72Kl7ACm-pLeNtNjQ5l5hY/edit?usp=sharing))
- [x] Implement a reference Scene App plugin example.
- [x] #64317
- [x] Templating: [Block query execution for queries that use variables until variables have finished updating.](https://github.com/grafana/scenes/pull/21) ([ref](https://github.com/grafana/grafana/issues/58289))
- [x] #63867
- [x] #65832
- [ ] Templating: Handling Error / Loading state of a template variable to reflect it in the selector. ([ref](https://github.com/grafana/grafana/issues/58289))
- [x] #64047
- [x] #63868
- [x] #64208 
- [ ] Add support for annotation queries.

**Design**
Figma file
