### ISSUE TITLE
Improve o11y for Grafana dashboard

### ISSUE THREAD

**Issue by ivanortegaalba** [grafana/grafana#63467]
**Goal**
As a Grafana engineer, I can see in a single dashboard the current health status of the codebase in the different engineering areas: performance, reliability, maintainability, and security.

**Docs**
* [Design doc](https://docs.google.com/document/d/1W3g3F8lC_vRPMZnUlaA6aaUaO-qfCKGeQOD2JvTI-og/edit#)

**Requirements & Caveats**
* The team can access a dashboard with the metrics reflecting Grafana dashboard status
* The dashboard shows the performance of the Grafana Dashboard views
* The dashboard shows the errors, bugs, and incidents caused by Grafana Dashboard
* The dashboard shows the number of security issues related to the Grafana Dashboard
* The dashboard shows different maintainability scores for the Grafana Dashboard codebase

```[tasklist]
### Tasks
- [x] Investigate how Faro works and what metrics we have available
- [x] https://github.com/grafana/grafana/issues/65784
- [x] Write a design doc for an MVP of what we want to monitor in the Grafana frontend
- [ ] https://github.com/grafana/grafana/issues/70327
- [x] Track for a month the different incidents, and how they reflect in Faro
```
