### ISSUE TITLE
Datasource picker: MVP for an updated datasource picker.

### ISSUE THREAD

**Issue by oscarkilhed** [grafana/grafana#63649]
Part of: #62083

```[tasklist]
### Tasks
- [ ] Opens in a drawer.
- [ ] Behind feature flag.
- [ ] Has a control similar to the current control.
- [ ] Has a filtering function.
- [ ] Sets focus to the filtering input box.
- [ ] A section of recently used datasources.
- [ ] File upload section.
```
