### ISSUE TITLE
Remove SASS styles

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#64129]
## Why?
SASS styles need to be removed in favor of Emotion. Removing the actual scss files may be done in the next step.

## How?
List components that use string-based class names, and make sure they are replaced with either Emoition or a component that provides the same styles.

Angular components do not need to be modified. These will be deprecated on their own timeline.

A search in the repo for classNames that are pure strings gives the following:
```
grep "className=\"" ./public/app -lR
```

### Components
- [ ]./public/app/AppWrapper.tsx
- [ ] ./public/app/AppWrapper.tsx
- [ ] ./public/app/plugins/datasource/jaeger/components/ConfigEditor.tsx
- [ ] ./public/app/plugins/datasource/loki/components/LokiCheatSheet.tsx
- [ ] ./public/app/plugins/datasource/loki/components/AnnotationsQueryEditor.tsx
- [ ] ./public/app/plugins/datasource/loki/components/LokiOptionFields.tsx
- [ ] ./public/app/plugins/datasource/loki/components/LokiQueryField.tsx
- [ ] ./public/app/plugins/datasource/loki/configuration/DerivedFields.tsx
- [ ] ./public/app/plugins/datasource/loki/configuration/MaxLinesField.tsx
- [ ] ./public/app/plugins/datasource/loki/configuration/ConfigEditor.tsx
- [ ] ./public/app/plugins/datasource/loki/configuration/DerivedField.tsx
- [ ] ./public/app/plugins/datasource/loki/querybuilder/components/LokiQueryBuilderOptions.tsx
- [ ] ./public/app/plugins/datasource/alertmanager/ConfigEditor.tsx
- [ ] ./public/app/plugins/datasource/zipkin/ConfigEditor.tsx
- [ ] ./public/app/plugins/datasource/zipkin/QueryField.tsx
- [ ] ./public/app/plugins/datasource/cloudwatch/components/MetaInspector.tsx
- [ ] ./public/app/plugins/datasource/cloudwatch/components/Forms.tsx
- [ ] ./public/app/plugins/datasource/cloudwatch/components/LogsCheatSheet.tsx
- [ ] ./public/app/plugins/datasource/cloudwatch/components/ConfigEditor.tsx
- [ ] ./public/app/plugins/datasource/cloudwatch/components/XrayLinkConfig.tsx
- [ ] ./public/app/plugins/datasource/cloudwatch/components/ThrottlingErrorMessage.tsx
- [ ] ./public/app/plugins/datasource/cloudwatch/components/LogsQueryField.tsx
- [ ] ./public/app/plugins/datasource/graphite/components/FunctionEditor.tsx
- [ ] ./public/app/plugins/datasource/graphite/components/FunctionEditorControls.tsx
- [ ] ./public/app/plugins/datasource/graphite/components/MetricTankMetaInspector.tsx
- [ ] ./public/app/plugins/datasource/graphite/components/AnnotationsEditor.tsx
- [ ] ./public/app/plugins/datasource/graphite/configuration/ConfigEditor.tsx
- [ ] ./public/app/plugins/datasource/graphite/configuration/MappingsConfiguration.tsx
- [ ] ./public/app/plugins/datasource/influxdb/components/VisualInfluxQLEditor/TagsSection.tsx
- [ ] ./public/app/plugins/datasource/influxdb/components/ConfigEditor.tsx
- [ ] ./public/app/plugins/datasource/influxdb/components/VariableQueryEditor.tsx
- [ ] ./public/app/plugins/datasource/influxdb/components/InfluxCheatSheet.tsx
- [ ] ./public/app/plugins/datasource/influxdb/components/QueryEditor.tsx
- [ ] ./public/app/plugins/datasource/influxdb/components/FluxQueryEditor.tsx
- [ ] ./public/app/plugins/datasource/influxdb/components/AnnotationEditor.tsx
- [ ] ./public/app/plugins/datasource/opentsdb/components/RateSection.tsx
- [ ] ./public/app/plugins/datasource/opentsdb/components/FilterSection.tsx
- [ ] ./public/app/plugins/datasource/opentsdb/components/OpenTsdbDetails.tsx
- [ ] ./public/app/plugins/datasource/opentsdb/components/TagSection.tsx
- [ ] ./public/app/plugins/datasource/opentsdb/components/MetricSection.tsx
- [ ] ./public/app/plugins/datasource/opentsdb/components/DownSample.tsx
- [ ] ./public/app/plugins/datasource/opentsdb/components/AnnotationEditor.tsx
- [ ] ./public/app/plugins/datasource/cloud-monitoring/components/VariableQueryEditor.tsx
- [ ] ./public/app/plugins/datasource/cloud-monitoring/components/MQLQueryEditor.tsx
- [ ] ./public/app/plugins/datasource/cloud-monitoring/components/__snapshots__/VariableQueryEditor.test.tsx.snap
- [ ] ./public/app/plugins/datasource/cloud-monitoring/components/AnnotationsHelp.tsx
- [ ] ./public/app/plugins/datasource/tempo/QueryEditor/ServiceGraphSection.tsx
- [ ] ./public/app/plugins/datasource/tempo/QueryEditor/QueryField.tsx
- [ ] ./public/app/plugins/datasource/tempo/traceql/TempoQueryBuilderOptions.tsx
- [ ] ./public/app/plugins/datasource/tempo/configuration/SearchSettings.tsx
- [ ] ./public/app/plugins/datasource/tempo/configuration/ConfigEditor.tsx
- [ ] ./public/app/plugins/datasource/tempo/configuration/QuerySettings.tsx
- [ ] ./public/app/plugins/datasource/tempo/configuration/ServiceGraphSettings.tsx
- [ ] ./public/app/plugins/datasource/tempo/configuration/LokiSearchSettings.tsx
- [ ] ./public/app/plugins/datasource/elasticsearch/components/QueryEditor/AnnotationQueryEditor.tsx
- [ ] ./public/app/plugins/datasource/elasticsearch/configuration/DataLink.tsx
- [ ] ./public/app/plugins/datasource/elasticsearch/configuration/DataLinks.tsx
- [ ] ./public/app/plugins/datasource/prometheus/components/PromCheatSheet.tsx
- [ ] ./public/app/plugins/datasource/prometheus/components/PromExploreExtraField.tsx
- [ ] ./public/app/plugins/datasource/prometheus/components/PromQueryField.tsx
- [ ] ./public/app/plugins/datasource/prometheus/configuration/AzureCredentialsForm.tsx
- [ ] ./public/app/plugins/datasource/prometheus/configuration/PromSettings.tsx
- [ ] ./public/app/plugins/datasource/prometheus/configuration/AzureAuthSettings.tsx
- [ ] ./public/app/plugins/datasource/prometheus/configuration/ExemplarsSettings.tsx
- [ ] ./public/app/plugins/datasource/prometheus/configuration/ExemplarSetting.tsx
- [ ] ./public/app/plugins/datasource/prometheus/querybuilder/components/LabelFilterItem.tsx
- [ ] ./public/app/plugins/datasource/azuremonitor/components/MonitorConfig.tsx
- [ ] ./public/app/plugins/datasource/azuremonitor/components/AzureCredentialsForm.tsx
- [ ] ./public/app/plugins/datasource/azuremonitor/components/DefaultSubscription.tsx
- [ ] ./public/app/plugins/datasource/phlare/ConfigEditor.tsx
- [ ] ./public/app/plugins/datasource/grafana/components/QueryEditor.tsx
- [ ] ./public/app/plugins/panel/status-history/StatusHistoryPanel.tsx
- [ ] ./public/app/plugins/panel/xychart/XYChartPanel.old
- [ ] ./public/app/plugins/panel/xychart/XYChartPanel2.tsx
- [ ] ./public/app/plugins/panel/traces/TracesPanel.tsx
- [ ] ./public/app/plugins/panel/nodeGraph/NodeGraphPanel.tsx
- [ ] ./public/app/plugins/panel/debug/RenderInfoViewer.tsx
- [ ] ./public/app/plugins/panel/annolist/AnnoListPanel.tsx
- [ ] ./public/app/plugins/panel/histogram/HistogramPanel.tsx
- [ ] ./public/app/plugins/panel/state-timeline/StateTimelinePanel.tsx
- [ ] ./public/app/plugins/panel/graph/Legend/LegendSeriesItem.tsx
- [ ] ./public/app/plugins/panel/graph/Legend/Legend.tsx
- [ ] ./public/app/features/dashboard/components/DashboardRow/DashboardRow.tsx
- [ ] ./public/app/features/dashboard/components/SubMenu/DashboardLinks.tsx
- [ ] ./public/app/features/dashboard/components/SubMenu/SubMenuItems.tsx
- [ ] ./public/app/features/dashboard/components/SubMenu/SubMenu.tsx
- [ ] ./public/app/features/dashboard/components/SubMenu/DashboardLinksDashboard.tsx
- [ ] ./public/app/features/dashboard/components/HelpWizard/HelpWizard.tsx
- [ ] ./public/app/features/dashboard/components/VersionHistory/VersionHistoryHeader.tsx
- [ ] ./public/app/features/dashboard/components/VersionHistory/VersionHistoryTable.tsx
- [ ] ./public/app/features/dashboard/components/TransformationsEditor/TransformationsEditor.tsx
- [ ] ./public/app/features/dashboard/components/SaveDashboard/forms/SaveProvisionedDashboardForm.tsx
- [ ] ./public/app/features/dashboard/components/DeleteDashboard/DeleteDashboardModal.tsx
- [ ] ./public/app/features/dashboard/components/AddPanelWidget/AddPanelWidget.tsx
- [ ] ./public/app/features/dashboard/components/AnnotationSettings/AnnotationSettingsEdit.tsx
- [ ] ./public/app/features/dashboard/components/AnnotationSettings/AnnotationSettingsList.tsx
- [ ] ./public/app/features/dashboard/components/DashboardSettings/DashboardSettings.tsx
- [ ] ./public/app/features/dashboard/components/DashboardSettings/GeneralSettings.tsx
- [ ] ./public/app/features/dashboard/components/RowOptions/RowOptionsButton.tsx
- [ ] ./public/app/features/dashboard/components/DashboardPermissions/DashboardPermissions.tsx
- [ ] ./public/app/features/dashboard/components/LinksSettings/LinkSettingsList.tsx
- [ ] ./public/app/features/dashboard/components/ShareModal/ShareEmbed.tsx
- [ ] ./public/app/features/dashboard/components/ShareModal/ShareLibraryPanel.tsx
- [ ] ./public/app/features/dashboard/components/ShareModal/ShareSnapshot.tsx
- [ ] ./public/app/features/dashboard/components/ShareModal/ShareExport.tsx
- [ ] ./public/app/features/dashboard/components/ShareModal/ShareLink.tsx
- [ ] ./public/app/features/dashboard/containers/SoloPanelPage.tsx
- [ ] ./public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderMenuItem.tsx
- [ ] ./public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderMenuTrigger.tsx
- [ ] ./public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderCorner.tsx
- [ ] ./public/app/features/dashboard/dashgrid/PanelHeader/PanelHeader.tsx
- [ ] ./public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderTitleItems.tsx
- [ ] ./public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderLoadingIndicator.tsx
- [ ] ./public/app/features/dashboard/dashgrid/PanelChromeAngular.tsx
- [ ] ./public/app/features/storage/RootView.tsx
- [ ] ./public/app/features/logs/components/LogDetailsRow.tsx
- [ ] ./public/app/features/query/components/QueryGroupOptions.tsx
- [ ] ./public/app/features/query/components/SavedQueryPicker.tsx
- [ ] ./public/app/features/profile/UserOrganizations.tsx
- [ ] ./public/app/features/profile/UserTeams.tsx
- [ ] ./public/app/features/profile/UserProfileEditForm.tsx
- [ ] ./public/app/features/profile/ChangePasswordPage.tsx
- [ ] ./public/app/features/profile/UserSessions.tsx
- [ ] ./public/app/features/support-bundles/SupportBundlesCreate.tsx
- [ ] ./public/app/features/support-bundles/SupportBundles.tsx
- [ ] ./public/app/features/live/pages/PipelineTable.tsx
- [ ] ./public/app/features/live/pages/PipelineAdminPage.tsx
- [ ] ./public/app/features/manage-dashboards/components/ImportDashboardOverview.tsx
- [ ] ./public/app/features/manage-dashboards/components/SnapshotListTable.tsx
- [ ] ./public/app/features/manage-dashboards/components/PublicDashboardListTable/PublicDashboardListTable.tsx
- [ ] ./public/app/features/annotations/components/AnnotationResultMapper.tsx
- [ ] ./public/app/features/query-library/components/QueryEditorDrawerHeader.tsx
- [ ] ./public/app/features/query-library/components/DatasourceTypePicker.tsx
- [ ] ./public/app/features/explore/NoDataSourceCallToAction.tsx
- [ ] ./public/app/features/explore/TraceView/components/utils/DraggableManager/demo/RegionDemo.tsx
- [ ] ./public/app/features/explore/TraceView/components/utils/DraggableManager/demo/DraggableManagerDemo.tsx
- [ ] ./public/app/features/explore/TraceView/components/utils/DraggableManager/demo/DividerDemo.tsx
- [ ] ./public/app/features/explore/TraceView/components/utils/DraggableManager/README.md
- [ ] ./public/app/features/explore/TraceView/components/settings/SpanBarSettings.tsx
- [ ] ./public/app/features/explore/TraceView/components/TraceTimelineViewer/SpanDetail/AccordianLogs.tsx
- [ ] ./public/app/features/explore/TraceView/components/TraceTimelineViewer/SpanDetail/AccordianReferences.tsx
- [ ] ./public/app/features/explore/LogsMetaRow.tsx
- [ ] ./public/app/features/api-keys/ApiKeysTable.tsx
- [ ] ./public/app/features/api-keys/ApiKeysAddedModal.tsx
- [ ] ./public/app/features/api-keys/MigrateToServiceAccountsCard.tsx
- [ ] ./public/app/features/api-keys/ApiKeysForm.tsx
- [ ] ./public/app/features/api-keys/ApiKeysActionBar.tsx
- [ ] ./public/app/features/teams/TeamGroupSync.tsx
- [ ] ./public/app/features/teams/TeamListRow.tsx
- [ ] ./public/app/features/teams/CreateTeam.tsx
- [ ] ./public/app/features/teams/TeamList.tsx
- [ ] ./public/app/features/teams/TeamMembers.tsx
- [ ] ./public/app/features/teams/TeamMemberRow.tsx
- [ ] ./public/app/features/playlist/PlaylistForm.tsx
- [ ] ./public/app/features/playlist/PlaylistTable.tsx
- [ ] ./public/app/features/users/UsersActionBar.tsx
- [ ] ./public/app/features/users/UsersListPage.tsx
- [ ] ./public/app/features/users/UsersTable.tsx
- [ ] ./public/app/features/serviceaccounts/ServiceAccountsListPage.tsx
- [ ] ./public/app/features/serviceaccounts/components/ServiceAccountProfileRow.tsx
- [ ] ./public/app/features/serviceaccounts/components/ServiceAccountTokensTable.tsx
- [ ] ./public/app/features/serviceaccounts/components/ServiceAccountProfile.tsx
- [ ] ./public/app/features/serviceaccounts/components/ServiceAccountsListItem.tsx
- [ ] ./public/app/features/serviceaccounts/ServiceAccountCreatePage.tsx
- [ ] ./public/app/features/alerting/AlertRuleList.tsx
- [ ] ./public/app/features/alerting/TestRuleResult.tsx
- [ ] ./public/app/features/alerting/unified/components/AlertManagerPicker.tsx
- [ ] ./public/app/features/alerting/unified/components/rule-editor/QueryWrapper.tsx
- [ ] ./public/app/features/alerting/unified/components/AlertLabelDropdown.tsx
- [ ] ./public/app/features/alerting/StateHistory.tsx
- [ ] ./public/app/features/alerting/NewNotificationChannelPage.tsx
- [ ] ./public/app/features/alerting/EditNotificationChannelPage.tsx
- [ ] ./public/app/features/alerting/NotificationsListPage.tsx
- [ ] ./public/app/features/admin/UserProfile.tsx
- [ ] ./public/app/features/admin/ldap/LdapUserTeams.tsx
- [ ] ./public/app/features/admin/ldap/LdapUserPermissions.tsx
- [ ] ./public/app/features/admin/ldap/LdapSyncInfo.tsx
- [ ] ./public/app/features/admin/ldap/LdapUserGroups.tsx
- [ ] ./public/app/features/admin/ldap/LdapConnectionStatus.tsx
- [ ] ./public/app/features/admin/ldap/LdapUserMappingInfo.tsx
- [ ] ./public/app/features/admin/ldap/LdapUserInfo.tsx
- [ ] ./public/app/features/admin/ldap/LdapPage.tsx
- [ ] ./public/app/features/admin/AdminOrgsTable.tsx
- [ ] ./public/app/features/admin/AdminSettings.tsx
- [ ] ./public/app/features/admin/UserPermissions.tsx
- [ ] ./public/app/features/admin/UserOrgs.tsx
- [ ] ./public/app/features/admin/UserSessions.tsx
- [ ] ./public/app/features/admin/UserListAdminPage.tsx
- [ ] ./public/app/features/admin/AdminListOrgsPage.tsx
- [ ] ./public/app/features/admin/UserLdapSyncInfo.tsx
- [ ] ./public/app/features/invites/InviteeRow.tsx
- [ ] ./public/app/features/invites/SignupInvited.tsx
- [ ] ./public/app/features/invites/InviteesTable.tsx
- [ ] ./public/app/features/variables/editor/VariableEditorEditor.tsx
- [ ] ./public/app/features/variables/editor/VariableEditorList.tsx
- [ ] ./public/app/features/variables/inspect/VariablesUnknownTable.tsx
- [ ] ./public/app/features/variables/query/QueryVariableEditor.tsx
- [ ] ./public/app/features/variables/adhoc/picker/AdHocFilterKey.tsx
- [ ] ./public/app/features/variables/adhoc/picker/AdHocFilterValue.tsx
- [ ] ./public/app/features/variables/adhoc/picker/AdHocFilter.tsx
- [ ] ./public/app/features/variables/adhoc/picker/AdHocFilterRenderer.tsx
- [ ] ./public/app/features/variables/adhoc/picker/OperatorSegment.tsx
- [ ] ./public/app/features/variables/adhoc/picker/ConditionSegment.tsx
- [ ] ./public/app/features/variables/pickers/PickerRenderer.tsx
- [ ] ./public/app/features/variables/pickers/shared/VariableOptions.tsx
- [ ] ./public/app/features/variables/pickers/shared/VariableLink.tsx
- [ ] ./public/app/features/variables/pickers/shared/VariableInput.tsx
- [ ] ./public/app/features/variables/pickers/OptionsPicker/OptionsPicker.tsx
- [ ] ./public/app/features/plugins/sql/components/ConfirmModal.tsx
- [ ] ./public/app/features/plugins/admin/components/Loader.tsx
- [ ] ./public/app/features/plugins/admin/components/PluginDetailsDisabledError.tsx
- [ ] ./public/app/features/plugins/admin/components/PluginSubtitle.tsx
- [ ] ./public/app/features/plugins/admin/components/PluginDetailsSignature.tsx
- [ ] ./public/app/features/plugins/admin/components/AppConfigWrapper.tsx
- [ ] ./public/app/features/plugins/admin/components/PluginDashboards.tsx
- [ ] ./public/app/features/org/NewOrgPage.tsx
- [ ] ./public/app/features/org/UserInvitePage.tsx
- [ ] ./public/app/features/inspector/QueryInspector.tsx
- [ ] ./public/app/features/inspector/InspectStatsTable.tsx
- [ ] ./public/app/features/inspector/InspectJSONTab.tsx
- [ ] ./public/app/features/search/components/PreviewsSystemRequirements.tsx
- [ ] ./public/app/features/transformers/FilterByValueTransformer/ValueMatchers/BasicMatcherEditor.tsx
- [ ] ./public/app/features/transformers/FilterByValueTransformer/ValueMatchers/RangeMatcherEditor.tsx
- [ ] ./public/app/features/transformers/FilterByValueTransformer/FilterByValueFilterEditor.tsx
- [ ] ./public/app/features/transformers/FilterByValueTransformer/FilterByValueTransformerEditor.tsx
- [ ] ./public/app/features/transformers/editors/OrganizeFieldsTransformerEditor.tsx
- [ ] ./public/app/features/transformers/editors/ReduceTransformerEditor.tsx
- [ ] ./public/app/features/transformers/editors/RenameByRegexTransformer.tsx
- [ ] ./public/app/features/transformers/editors/GroupByTransformerEditor.tsx
- [ ] ./public/app/features/transformers/editors/FilterByRefIdTransformerEditor.tsx
- [ ] ./public/app/features/transformers/editors/CalculateFieldTransformerEditor.tsx
- [ ] ./public/app/features/transformers/editors/LabelsToFieldsTransformerEditor.tsx
- [ ] ./public/app/features/transformers/editors/FilterByNameTransformerEditor.tsx
- [ ] ./public/app/features/transformers/editors/ConcatenateTransformerEditor.tsx
- [ ] ./public/app/features/transformers/prepareTimeSeries/PrepareTimeSeriesEditor.tsx
- [ ] ./public/app/features/canvas/elements/droneTop.tsx
- [ ] ./public/app/features/canvas/elements/droneFront.tsx
- [ ] ./public/app/features/canvas/elements/droneSide.tsx
- [ ] ./public/app/features/datasources/components/DataSourceLoadError.tsx
- [ ] ./public/app/features/datasources/components/DashboardsTable.tsx
- [ ] ./public/app/features/datasources/components/ButtonRow.tsx
- [ ] ./public/app/features/datasources/components/DataSourceTestingStatus.tsx
- [ ] ./public/app/features/datasources/components/NewDataSource.tsx
- [ ] ./public/app/features/datasources/components/DataSourcePluginState.tsx
- [ ] ./public/app/features/datasources/components/BasicSettings.tsx
- [ ] ./public/app/features/datasources/components/DataSourceCategories.tsx
- [ ] ./public/app/features/datasources/components/CloudInfoBox.tsx
- [ ] ./public/app/features/folders/FolderPermissions.tsx
- [ ] ./public/app/features/folders/FolderSettingsPage.tsx
- [ ] ./public/app/core/navigation/GrafanaRouteError.tsx
- [ ] ./public/app/core/components/OrgSwitcher.tsx
- [ ] ./public/app/core/components/PermissionList/DisabledPermissionListItem.tsx
- [ ] ./public/app/core/components/PermissionList/AddPermission.tsx
- [ ] ./public/app/core/components/PermissionList/PermissionListItem.tsx
- [ ] ./public/app/core/components/PermissionList/PermissionList.tsx
- [ ] ./public/app/core/components/QueryOperationRow/OperationRowHelp.tsx
- [ ] ./public/app/core/components/TraceToLogs/TraceToLogsSettings.tsx
- [ ] ./public/app/core/components/TraceToLogs/TagMappingInput.tsx
- [ ] ./public/app/core/components/Footer/Footer.tsx
- [ ] ./public/app/core/components/AccessControl/Permissions.tsx
- [ ] ./public/app/core/components/AccessControl/AddPermission.tsx
- [ ] ./public/app/core/components/AccessControl/PermissionListItem.tsx
- [ ] ./public/app/core/components/AccessControl/PermissionList.tsx
- [ ] ./public/app/core/components/TagFilter/TagBadge.tsx
- [ ] ./public/app/core/components/SharedPreferences/SharedPreferences.tsx
- [ ] ./public/app/core/components/PageLoader/PageLoader.tsx
- [ ] ./public/app/core/components/TraceToMetrics/TraceToMetricsSettings.tsx
- [ ] ./public/app/core/components/NodeGraphSettings.tsx
- [ ] ./public/app/core/components/Select/TeamPicker.tsx
- [ ] ./public/app/core/components/Select/UserPicker.tsx
- [ ] ./public/app/core/components/PageActionBar/PageActionBar.tsx
- [ ] ./public/app/core/components/PluginHelp/PluginHelp.tsx
- [ ] ./public/app/core/components/AppNotifications/AppNotificationList.tsx
- [ ] ./public/app/core/components/Login/LoginServiceButtons.tsx
- [ ] ./public/app/core/components/EmptyListCTA/EmptyListCTA.tsx
- [ ] ./public/app/core/components/ErrorPage/ErrorPage.tsx
- [ ] ./public/app/core/components/PageHeader/PageHeader.tsx
- [ ] ./public/app/core/components/AppChrome/AppChrome.tsx
- [ ] ./public/app/core/components/AppChrome/Organization/OrganizationSelect.tsx

### Documentation
- [ ] ./docs/sources/tutorials/build-a-data-source-plugin/index.md
- [ ] ./docs/sources/developers/plugins/add-support-for-variables.md
- [ ] ./docs/sources/developers/plugins/add-query-editor-help.md

**Comment by tskarhed** [comment]
We should probably do a subset of these, as a lot of them have global helper classes that are already in Emotion.

**Comment by torkelo** [comment]
@tskarhed been waiting for someone to review the state of sass / emotion and pick this up. 

I did a theme hackathon in december and in that hackathon I moved a lot of scss to global emotion styles:
https://github.com/grafana/grafana/compare/torkelo-hackathon#diff-177e16893989cfa2e84ba586985fbd37db68702a9ea1a45ee53469910db45f38 

But never found time to extracted those bits into a PR

**Comment by tskarhed** [comment]
@torkelo Oh, cool! Is it basically support for custom themes?

From what I have seen from the GlobalStyles, it would be a first step to migrate from SASS, and actually be able to remove the SASS-files and still have backwards compatibility.

However, the issue still remain when using string className that it is not easy to find out where the styles actually come from. My suggestion would be doing something like this:
```jsx
<p className="muted">...</p>
```
Would become
```jsx
const styles = useStyles2(getElementStyles);
return <p className={styles.muted}>...</p>
```

**Comment by tskarhed** [comment]
Okay, so the plan is to have the `Typography` component cover the helper class use cases? At the moment it doesn't implement any functionality except for displaying an h1.

**Comment by torkelo** [comment]
@tskarhed yea, that component is not yet implemented (only a placeholder). Thinking is to make it  something like material UI has. 

Maybe not cover all helper classes, but some

**Comment by tskarhed** [comment]
@torkelo Okay. We had a discussion in user essentials, and it seems like the priority is getting rid of the SASS files, which means that we'll mostly just move everything to GlobalStyles in Emotion as a first step. I'll restructuere this issue a bit.

**Comment by tskarhed** [comment]
I updated the issue with the other approach.

**Comment by khushijain21** [comment]
The link you've added under "considerations" is broken, can you redirect to the correct URL?

**Comment by tskarhed** [comment]
@khushijain21 It is in a private repository, so no can do

**Comment by ashharrison90** [comment]
thought i'd give an update on this:
- this is basically done 🥳 
- there is an `_angular` file containing SCSS that is needed for angular components
  - this can't be removed until angular is removed in Grafana 12
- there is a `font_awesome` file containing the font awesome SCSS
  - although this is deprecated, there are lots of plugins using these font awesome icons
  - we **should not** migrate these to emotion globals. the large amount of dom nodes it inserts causes performance issues
  - until we figure out a proper migration/deprecation plan, these will have to stay
- there are 2 classes in the `_grafana.scss` file that are needed for the preloader
  - these can't be moved to emotion since these are needed before emotion even loads
  - probably should be moved to just a plain css file somewhere (TODO)
