### ISSUE TITLE
EPIC: Angular deprecation

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#64143]
# Goal: This EPIC is used to track angular deprecation work 

```[tasklist]
### Announcements
- [ ] https://github.com/grafana/grafana/pull/63928
- [x] Announce the deprecationg in various community channels (@sympatheticmoose)
- [x] Talk to CX / train them on how to activate the option if necessary (@sympatheticmoose)
- [x] Announce to commercial plugin partners (@ljsmith93)
- [ ] Provide CX with self-service instructions on how to contact their customer regarding remaining Angular plugin installations (@sympatheticmoose)
```

```[tasklist]
### Missing functionality
- [ ] https://github.com/grafana/grafana/pull/64137
- [ ] https://github.com/grafana/grafana/issues/64400
- [ ] https://github.com/grafana/grafana/issues/64484
- [ ] https://github.com/grafana/grafana/issues/64737
```

```[tasklist]
### Core migration
- [ ] https://github.com/grafana/grafana/pull/63915
- [ ] Plan how to deal with legacy alerting UI (@armandgrillet)
- [ ] Graph old panel -> Timeseries auto migration or plan how to deal with them (@jensallen)
- [ ] Table old panel auto migration or plan how to deal with them (@jennyfanna)
- [ ] https://github.com/grafana/grafana/issues/65246
- [ ] pre-supplied Dashboards (e.g. the Grafana Cloud Billing/Usage one) (ask Seamus Toth)
- [ ] common Mixins (ask Seamus Toth)
```

```[tasklist]
### Docs
- [ ] https://github.com/grafana/grafana/issues/45930
```

```[tasklist]
### Plugin Reviews / Catalog
- [ ] https://github.com/grafana/grafana/pull/64006
- [ ] https://github.com/grafana/plugin-validator/pull/82
- [x] Prepare standard notes we can send out to plugin authors during plugin reviews (@tolzhabayev)
```

For plugin migrations, please consider that even if the latest version of the plugin your responsible for might be already migrated, chances are high that some of the **older** versions of your plugin are still running on Grafana cloud instances. You have to consider this fact when making decisions.

```[tasklist]
### Plugin Migrations
- [ ] grafana-worldmap-panel - decide what to do with it (@jennyfana)
- [ ] https://github.com/grafana/plugin-validator/pull/82
- [x] Prepare standard notes we can send out to plugin authors during plugin reviews (@tolzhabayev)
- [ ] grafana-es-open-distro-datasource - decide what to do with it (@evandandrea)
- [ ] grafana-simple-json-datasource - deprecated, decide what to do with it (@evandandrea)
- [x] grafana-singlestat-panel - deprecated (@tolzhabayev)
```

```[tasklist]
### Cloud Integrations
- [ ] (If required) Ensure documentation is updated for Cloud Integration dashboards which may display a warning banner resulting from the use of an Angular plugin (@edwin-onattu)
- [x] Update guide for CX to cover cloud integration dashboard warnings (@sympatheticmoose)
- [ ] Migrate to React panels in top 10 integrations (@Dasomeone)
- [ ] Migrate to React panels in all currently maintained integrations (@Dasomeone)
```

**Comment by mjseaman** [comment]
Hi, some suggestions for managing communication and helping customers migrate. Adding these for discussion, and then inclusion of whichever items make sense in the to-do list above.

**I know Angular deprecation is happening: ~90% of customers, ~50% of community, and ~80% of Angular plugin code owners have seen a notice that we are deprecating Angular.**

- [ ] Inclusion in What’s New and upgrade guide 
- [ ] Tool for CX to identify customers with Angular plugins
- [ ] Email template for CX to send to customers announcing deprecation

**I know how I’m affected: There’s a way to identify which of my plugins are affected,  there are tools and clear instructions for how to stop using Angular (e.g. plugin alternatives)**

- ~Angular off by default in Grafana 10.0~
- [ ] Docs page lists the [known Angular plugins](https://docs.google.com/spreadsheets/d/1zq4DJCIHRaNNinM5onizGBDHDLZE98LFLNqkfYnC1K0/edit#gid=655734561), and alternatives where they exist
- [ ] Banner, panel highlight, and/or warning messages on pages that run Angular in Grafana, with a link to learn more
- [ ] Detection tool in grafana-cli to run against my instance and get a list of affected plugins

**I’ve done what I need to do: Less than X% (10%?) of Grafana instances still have Angular plugins by the day we fully remove Angular**

- [ ] Usage stats for the number of angular plugins installed (and instances used?)
- [ ] A panel migration tool, to automatically migrate all panels at once where possible (e.g. from Worldmap to Geomap)
