### ISSUE TITLE
Border Radius: Check and fix deviations from standard

### ISSUE THREAD

**Issue by L-M-K-B** [grafana/grafana#64385]
We introduced a standard for the Grafana wide use of border radii and agreed to use 2px unless it's required differently for styling purposes (e.g. to create a certain shape).

[Here](https://internal-ops-us-east-0.grafana.net/design-system/Styling/border-radius/) you can find the documentation in Saga.
[Here](https://docs.google.com/spreadsheets/d/1gFij3aFnyMMVnNESiQbLk33e7dgAnSpMuU4WGXaKjoU/edit#gid=0) you can find the whole list of deviations.

```[tasklist]
- [ ] https://github.com/grafana/grafana/issues/64414
- [ ] https://github.com/grafana/grafana/issues/64408
- [ ] https://github.com/grafana/grafana/issues/64290
- [ ] https://github.com/grafana/grafana/issues/64421
- [ ] https://github.com/grafana/grafana/issues/64423
- [ ] https://github.com/grafana/grafana/issues/64419
- [ ] https://github.com/grafana/grafana/issues/64488
- [ ] https://github.com/grafana/grafana/issues/64490
- [ ] https://github.com/grafana/grafana/issues/65089
- [ ] https://github.com/grafana/grafana/issues/70502
```

**Comment by grafanabot** [comment]
@L-M-K-B please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:
