### ISSUE TITLE
Feature parity - `getLegacyAngularInjector().get('dashboardSrv')`

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#64484]
### Goal
Check if we need to expose any parts of the `dashboardSrv` service for angular plugins to be able to upgrade to use React.

### Why?
The `dashboardSrv` ([implementation](https://github.com/grafana/grafana/blob/58f3f00bd548db39f1dc9b8c874dad2480e03298/public/app/features/dashboard/services/DashboardSrv.ts#L41)) is one of the core Grafana services, and however it was available using the legacy angular injector, is not exposed anymore for the React components. Part of this task is to investigate what plugins are using from this service and if they would need any work from the Grafana core side to be able to migrate.

### Action plan
- Research what functionality needs to be exposed and how, we do not want to "just filter out dashboardSrv" but rather find a proper way to expose what is needed by plugin authors.
- Use `@grafana/runtime` to expose the new functions and methods.
- Work with the team that owns Twinmaker App and Dashboards squad to get their feedback on the functionality exposed. 
- Once exposed ping the team to migrate to using it in Twinmaker App

```[tasklist]
### Tasks
- [ ] Define a set of guidelines of how we want to expose new plugins APIs
- [ ] https://github.com/grafana/grafana/issues/73562
- [ ] https://github.com/grafana/grafana/issues/73753
```

**Comment by leventebalogh** [comment]
### Affected plugins
This list is not complete, we were using Github's code search ([cs.github.com](https://cs.github.com/)) to find affected plugins. We are mostly focusing on actively developed plugins / projects here (had contributions in the last 1 year), as they are most likely to be affected by any changes we do to this part of the codebase. 

**Actively developed**
- [grafana-iot-twinmaker-app](https://github.dev/grafana/grafana-iot-twinmaker-app) (app)
    - Usage:
        - Uses `dashboardSrv.dashboard` to get the currently active dashboard [here](https://github.com/grafana/grafana-iot-twinmaker-app/blob/main/src/common/dashboard.ts#L30). To me it looks like knowing the current dashboard is quite important for the functionality of the plugin, and I am not sure that we any replacement for it at the moment. @ryantxu what do you think?
       


**Not actively developed**
The following projects seem to depend on the `timeSrv` but are not actively developed (no contributions in the last 1 year): 
- [grafana/grafana-roci-app](https://github.com/grafana/grafana-roci-app)
- [image-viewer-panel](https://github.com/ryantxu/image-viewer-panel)

**Comment by leventebalogh** [comment]
Pinging @grafana/dashboards-squad for visibility, and to ask your opinion on if there would any preferred way to provide the current dashboard (currently used by the [iot-twinmaker-app](https://github.com/grafana/grafana-iot-twinmaker-app/blob/main/src/common/dashboard.ts#L30)), or if it is something that we don't want to do in the future.

**Comment by iwysiu** [comment]
Hi! Yes we need it, its being used in twinmaker for plugin panels that we would still like to work.

**Comment by tolzhabayev** [comment]
> Hi! Yes we need it, its being used in twinmaker for plugin panels.

can you elaborate a bit more on the use case for plugin panels? Maybe there are other ways to achieve the same outcome.

**Comment by ryantxu** [comment]
We could do something like this:  https://github.com/grafana/grafana/compare/angular-injector-hack#diff-3da8a637055b104e560cd7ca042f9c967745a6fe84a05ed78b56b5271bd320d1R25

or we need to figure out how to officially expose the `dashboardSrv` -- scenes will eventually offer some way to interact with a dashboard, but that is a long way off.  (that behavior is exactly what twinmaker is doing)

**Comment by idastambuk** [comment]
Hi @mckn, I'm currently investigating if we can support the functionality in Twinmaker with Scenes, but from @ryantxu's last comment it looks like it won't be possible for a while. Can you confirm that we will be going with the 'expose dashboardSrv' route before we remove the workaround from https://github.com/grafana/grafana/pull/67439? Thanks!

**Comment by mckn** [comment]
> Hi @mckn, I'm currently investigating if we can support the functionality in Twinmaker with Scenes, but from @ryantxu's last comment it looks like it won't be possible for a while. Can you confirm that we will be going with the 'expose dashboardSrv' route before we remove the workaround from #67439? Thanks!

Yeah, we will expose an alternative to the DashboardSrv prior to removing the workaround in #67439. We have tracked this in an issue and will work on it next couple of weeks.

**Comment by tolzhabayev** [comment]
Added "Action plan" to the issue description.

FYI @idastambuk, @academo, @jackw, @mckn 

For any vetos ping: @ryantxu @torkelo

**Comment by tolzhabayev** [comment]
Closing in favour of https://github.com/grafana/grafana/issues/73874

> Some backward compatibility for plugins (and internal code) that access dashboardSrv.getCurrent and dashboardSrv.updatePanels. Something like https://github.com/grafana/grafana/pull/73755 but not a wrapper around old dashboardSrv but around the current dashboard scene.

@idastambuk for now you will have to keep using the `getLegacyAngularInjector` and then switch to the new solution that will be provided as part of the DashboardScene EPIC linked above.
