### ISSUE TITLE
Saga DS - Toggletip [epic]

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#64559]
Create a new component to solve needs that currently result in misusing our tooltip component

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/64558
- [x] https://github.com/grafana/grafana/pull/64459
- [x] https://github.com/grafana/grafana/issues/56032
```

**Comment by staton-hyse11** [comment]
This ticket has been retro-actively made to track all of the progress made on the new toggletip component
