### ISSUE TITLE
Saga DS - Typography alignment [epic]

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#64561]
Currently, the typography used in product is different than the styles created in Figma — we want to align them as much as possible.

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/64449
- [ ] https://github.com/grafana/grafana/issues/63280
- [ ] Typography alignment [publish]
```

[Explanation of phases and definitions of done](https://docs.google.com/document/d/1hcwu4YtAlq4jcqQVckdXB_PK2FZ6Kn2s3ri7-PCwaa4/edit?usp=sharing)
