### ISSUE TITLE
Epic: Metric Encyclopedia Part II More Feedback

### ISSUE THREAD

**Issue by bohandley** [grafana/grafana#64577]
Feedback from @galen, @leeoniya  and UX team to be implemented in M.E. Part II

- [x] #64621
- [x] #64581
  - [x] #64582
- [x] #64583
  - add bitly link to be able to turn off or see if there is Grafana config option to turn off links like this
- [ ] #64704
- [x] #64710
  - select button in row
- [x] #64705
- [x] #64711
- [x] #64706
- [x] ~~[pagination component](https://developers.grafana.com/ui/latest/index.html?path=/story/buttons-pagination--with-pages) that is in Storybook.~~ arguing to keep the select as there can be hundreds of pages and the pagination component is hard to navigate.
- [x] #64713
- [x] #64712
- [x] #64857

Stretch goals
- [x] Fix for small screens @gtk-grafana 
- [x] Fix loading state @gtk-grafana 
- [ ] Rows without descriptions @gtk-grafana 
- [x] Rename to Metric Browser.
- [ ] Differentiate backend search and allow it to stay once user has selected it.
- [x] Too many `useState` refactor with [this](https://stackoverflow.com/questions/62681581/using-too-many-usestate-hooks-in-react-how-do-i-refactor-this/65990137#65990137).
- [ ] Research: What are the general search and filter patterns within Grafana?  
- [ ] How do new users go about exploring?
- [ ] Does the user have an idea or not of what to search? 
- [ ] Recommendations or clues of searching and filtering in grafana.
- [ ] backend filter by type.
- [x] optimize displayMetrics() (filtering/pagination) to use useCallback or useMemo.
- [x] Ask Leon about further optimizations.
- [x] [add config switch sort differently, "alphabetically" and "sort results by relevance"](https://github.com/grafana/grafana/pull/64576#issuecomment-1466573826)
- [x] group the fuzzy-search and the filteredResults into a single setState/useReducer call, that way everything is cached. Thanks @leeoniya!

**Comment by bohandley** [comment]
Updated as of March 13, 2023 based on the following:

[Discussions with Leon](https://github.com/grafana/grafana/pull/64576#issuecomment-1466573826)
[Metric Encyclopedia hackathon epic](https://github.com/grafana/grafana/issues/64703)

**Comment by bohandley** [comment]
This PR will tick a lot of these boxes :) https://github.com/grafana/grafana/pull/67084

**Comment by bohandley** [comment]
Getting review for the above changes requested. Next steps are UI improvements in Q2
