### ISSUE TITLE
Metric Encyclopedia Hackathon Epic

### ISSUE THREAD

**Issue by bohandley** [grafana/grafana#64703]
This is to document the work done on the Metric Encyclopedia for the March 2023 Hackathon.

This work includes UI mockups and style quick wins.

Mockups: 
- [ ] Prometheus Query Builder: Order the 3 main components top to bottom. 1) M.E., 2) labels, 3)operations, give numbers like the Metrics Browser for Code.
- [ ] Metric Encyclopedia Modal: Show results in table, no more expanding. Select button on right inline row.
- [ ] Information architecture, move switches in Browse text and filter inputs to the Results section.

Style Quick Wins
- [ ] Prometheus Query Builder: Add X to explicitly show removing the selected metric.
  - Badge with X, check out the tag component with x-out
- [ ] Metric Encyclopedia Modal: Wider modal, more real estate.
- [ ] Metric Encyclopedia Modal: Implement upper limit on results per page, 1000
- [ ] Metric Encyclopedia Modal: Label the switches. Move inline switches in text browser to below the test browser input.
