### ISSUE TITLE
Prometheus: Incremental querying

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/grafana#65355]
**What is this**:
Prometheus Incremental querying epic

**Why?**:
Dashboards running auto-refresh request the same data over and over again.

**How?**:
Save query results locally in users browser, only query for durations that haven't already been cached.

```[tasklist]
- [x] Research POC and discuss with squad
- [ ] Get approval on design doc
- [x] Add what's new blurb
- [x] Merge MVP: https://github.com/grafana/grafana/pull/62932
- [ ] https://github.com/grafana/grafana/pull/65742
- [x] Merge Tracking PR: https://github.com/grafana/grafana/pull/65244
- [x] Enable in ops-cortex
- [x] https://github.com/grafana/grafana/issues/72411
- [ ] https://github.com/grafana/grafana/issues/69807
- [ ] e2e tests
- [ ] Blog article
- [ ] Prometheus: Incremental querying - delete cache ident on UI actions
- [ ] General release: on by default
- [ ] Research incremental querying with annotations
```

**Comment by gtk-grafana** [comment]
Related: Incremental querying PoC with influx: https://github.com/grafana/grafana/pull/66893
