### ISSUE TITLE
Prometheus: Browser Cache Epic

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/grafana#65397]
```[tasklist]
### Tasks
- [x] [Design Document](https://docs.google.com/document/d/19RnKIDbR-WZ_0AUvT4txrcAFg-OORujGr8g6q6L5-V4/edit#) approval
- [x] https://github.com/grafana/grafana/issues/60420
- [x] Deploy to dev/staging
- [x] Deploy to 50% of hosted prod
- [x] Deploy to 100% of hosted prod
- [x] Update documentation and remove feature flag
- [ ] Remove old code in 10.2 or later
```

**Comment by itsmylife** [comment]
@gtk-grafana Is this done? If not, could you please point what needs to be done?
