### ISSUE TITLE
Correlations Launch content

### ISSUE THREAD

**Issue by meanmina** [grafana/grafana#65536]
```[tasklist]
### Tasks
- [x] GrafanaCon "What's New" contribution @jay
- [x] Launch blog post @gelicia
- [ ] Webinar - a couple months after launch or at GA
```

**Comment by gelicia** [comment]
We are going to be substantially changing the UI for the editor and don't want to do a webinar that will be outdated by the next release, so we will hold off on a webinar for now unless we get a push for it.
