### ISSUE TITLE
NestedFolders: New Browse Dashboards

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#65604]
See designs https://www.figma.com/file/wgZ2KOiIcrKjCCnuBjgpik/Nested-folders?node-id=470-7558&t=AJ411TdvwkJd013J-4

Building a new browse dashboards for nested folders with the following high-level objectives:

  - A larger distinction between Browse and Search views. No a weird toggle that can sometimes be used to move between views - when you search, you're in a flat list search results view. when you're not searching, you see the tree view
  - Browsing folders and dashboards in a tree view where the entire hierarchy can be expanded and browsed.
  - There is no more General folder. Dashboards and Folders without a parent are shown as siblings at the root level
  - All data and views must be fully paginated and lazily/virtually rendered so all items can be shown in a performant way
  - [Actions (such as move) must be aware of the hierarchy of selected items](https://github.com/grafana/grafana/issues/65289). e.g:
    - if a folder and all of it's children are selected and moved, then only the parent folder will have it's parent UID changed
    - if a folder is collapsed, selected, then later expanded, then all the children should already be 

![Start](https://user-images.githubusercontent.com/46142/228819959-0422e745-04de-4c4d-bb6a-3c5361f2a070.png)

```[tasklist]
### Browse Dashboards
- [x] Scaffold out new Browse Dashboards view https://github.com/grafana/grafana/pull/66003
- [x] https://github.com/grafana/grafana/issues/65683
- [x] Basic item selection https://github.com/grafana/grafana/pull/66843
- [ ] https://github.com/grafana/grafana/issues/66933
- [ ] https://github.com/grafana/grafana/issues/65679
- [ ] https://github.com/grafana/grafana/issues/65681
- [ ] https://github.com/grafana/grafana/issues/66935
- [ ] https://github.com/grafana/grafana/issues/67392
- [ ] https://github.com/grafana/grafana/issues/67741
- [ ] https://github.com/grafana/grafana/pull/67113
- [ ] https://github.com/grafana/grafana/pull/67749
- [ ] https://github.com/grafana/grafana/issues/68450
- [ ] https://github.com/grafana/grafana/issues/67740
- [x] Vertically align folder expand/collapse Align arrows
- [x] Change “Empty folder” message to secondary text color, keep the italics, change text to “No items”
- [ ] https://github.com/grafana/grafana/issues/68884
- [ ] https://github.com/grafana/grafana/issues/69693
- [ ] https://github.com/grafana/grafana/issues/68330
- [ ] https://github.com/grafana/grafana/issues/68329
- [ ] https://github.com/grafana/grafana/issues/65217
- [ ] https://github.com/grafana/grafana/issues/69548
- [x] `fetchNextChildrenPage called with a parentUID of 'general' instead of undefined` after deleting item
- [ ] https://github.com/grafana/grafana/issues/69842
```

```[tasklist]
### Browse Folder view
- [ ] https://github.com/grafana/grafana/issues/68070
- [ ] https://github.com/grafana/grafana/issues/68452
- [x] Restore Library Panels/Alerts tabs to Folder view
- [ ] https://github.com/grafana/grafana/issues/68285
- [ ] https://github.com/grafana/grafana/issues/68332
- [ ] https://github.com/grafana/grafana/issues/69136
- [ ] https://github.com/grafana/grafana/issues/70574
```

```[tasklist]
### Miscellaneous
- [ ] https://github.com/grafana/grafana/issues/65745
- [ ] https://github.com/grafana/grafana/issues/74314
- [ ] https://github.com/grafana/grafana/issues/69611
- [ ] Research if we can populate notification history from something other than toasts
- [ ] Determine when to show toasts - on successes? Errors? And what should they say?
- [ ] Take another look at modals once nested folder picker is in - is the text too small? Hard to read?
- [ ] https://github.com/grafana/grafana/issues/68707
- [ ] https://github.com/grafana/grafana/issues/72089
- [ ] https://github.com/grafana/grafana/issues/70085
- [ ] https://github.com/grafana/grafana/issues/71417
- [ ] https://github.com/grafana/grafana/issues/65419
```

```[tasklist]
### Backend dependencies
- [ ] https://github.com/grafana/grafana/issues/66038
- [ ] https://github.com/grafana/grafana/issues/66033
- [ ] https://github.com/grafana/grafana/issues/66034
- [ ] https://github.com/grafana/grafana/issues/71425
```

```[tasklist]
### Bugs
- [ ] https://github.com/grafana/grafana/issues/73465
- [ ] https://github.com/grafana/grafana/issues/71174
- [ ] https://github.com/grafana/grafana/issues/71274
- [ ] https://github.com/grafana/grafana/issues/72354
- [ ] https://github.com/grafana/grafana/issues/74590
- [ ] https://github.com/grafana/grafana/issues/74666
```

```[tasklist]
### Issues to verify (expected to be fixed by new browse view)
- [ ] https://github.com/grafana/grafana/issues/59351
- [ ] https://github.com/grafana/grafana/issues/59543
- [ ] https://github.com/grafana/grafana/issues/51825
- [ ] https://github.com/grafana/grafana/issues/64210
- [ ] https://github.com/grafana/grafana/issues/64756
- [ ] https://github.com/grafana/grafana/issues/10339
- [ ] https://github.com/grafana/grafana/issues/62859
- [ ] https://github.com/grafana/grafana/issues/70983
```

```[tasklist]
### Post-GA tidyup
- [ ] Refactor SearchView to use DashboardsTree
```
```[tasklist]
### Rollout
- [ ] https://github.com/grafana/grafana/issues/74334
- [ ] https://github.com/grafana/grafana/issues/74314
- [x] Create separate Rollout dashboard (https://ops.grafana-ops.net/goto/KLoXtGiSg?orgId=1)
```

**Comment by AndreKR** [comment]
These are all for the "Dashboards" page, correct? Or do they apply to the "Dashboard list" visualization/panel as well?
