### ISSUE TITLE
Enable Faro in ops.grafana.com to use Faro as the main tool to observe grafana

### ISSUE THREAD

**Issue by ivanortegaalba** [grafana/grafana#65784]
**Goal**
Be able to use [Faro app in Ops](https://ops.grafana-ops.net/a/grafana-kowalski-app/apps/4/overview) to get reported Faro data

```[tasklist]
### Tasks
- [x] Report to the Faro team the DS selector is not working, and all the queries are canceled in the Faro app
- [x] Ask if Grafana has configured Faro SDK properly to report to Ops. There is [a Dashboard with data already](https://ops.grafana-ops.net/d/7uZYxAWVz/grafana-frontend-kowalski?orgId=1&var-cluster=All&var-slug=All)
- [x] Run session in monthly meeting
- [x] Run breakout session in offsite
- [x] Write documentation as style-guide to explain the current setup for Faro
- [x] Gather feedback
```

**Comment by grafanabot** [comment]
@ivanortegaalba please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:

**Comment by ivanortegaalba** [comment]
After the 2 sessions with the teams, we concluded that:

**Current problems**
1. Engineers want to monitor their Frontend, but they don't know how
2. Engineers don't know we have Faro already monitoring Grafana
3. Some plugins used Faro but they stopped maintaining them
4. They don't have any SLO to meet or incidents where the monitoring would help

**Action points**

- [ ] Document the current setup of Faro and push it to the style guidelines
    - [ ] How to use the Faro app to query your app data
    - [ ] How to configure your plugin with to send data to Faro scoped to your plugin
    - [ ] How to use Faro SDK to report: measurements, errors, or logs 
    - [ ] Best practices and how to not use Faro
- [ ] Move Faro to ops.grafana.com

**Future steps**
- [ ] Propose a way to monitor Plugins out of the box

**Expected outcome**
* Teams have a to-go place where they can see their metrics. No matter

**References**
- Frontend weekly [meeting notes](https://docs.google.com/document/d/1LmS2esCEGI1eacQMgg-0ZyRjg84kRFw6Z1XIqkCeOIc/edit#heading=h.blk1nku2n7y5) 
- Breakout sessions outcome ([Room 1](https://miro.com/app/board/uXjVM8u1QrE=/)) or ([Room 2](https://miro.com/app/board/uXjVM8tFZMM=/))
- [Design doc ](https://docs.google.com/document/d/1W3g3F8lC_vRPMZnUlaA6aaUaO-qfCKGeQOD2JvTI-og/edit#heading=h.5sybau7waq2q)
