### ISSUE TITLE
Prom Config Overhaul Epic

### ISSUE THREAD

**Issue by bohandley** [grafana/grafana#65877]
This issue is to organize the efforts around the Prometheus Configuration Page Overhaul.

[The work and meeting notes are here](https://docs.google.com/document/d/1Pw0l30ijhBAnXqm5IFPU8jPEtiL5ZtW29OQhE-dU5l8/edit#heading=h.3cdq44kqtkii)

The list of work includes Stages 1 & 2
[The discussion of this breakdown is here](https://docs.google.com/document/d/1WqEbJvInT_94xA4M-pATMYypnjGIs3dbwNbEvsqGuF8/edit#heading=h.rldiir2jr775), April 14, 2023

Stage 1 https://github.com/grafana/grafana/pull/66198

- [x] Implement health check, improve error handling for the test connection function
- [x] Organize additional settings
  - [x] Meet with Galen and Ismail
  - [x] Consider refactoring complex components 
- [x] Improve tooltips for each element and add links to docs
- [x] Add custom labels for the connection URL 

Stage 2
- [x] build behind feature flag to test Azure and SigV4 auth
- [x] [Description component](https://docs.google.com/document/d/11XMaYHSMSra8AoN2-yVW-5QPbjEXgkAFbTIF6N84cGE/edit#heading=h.o1zp7h8irwci)
- [x] Connection URL
- [x] Auth 
- [x] Use new auth component 
- [x] Improve error handling
  - [x] Return more verbose errors
  - [ ] Return success with Prom type. The prom type image used to be shown in the save and test modal message
- [ ] Use Editable header component
- [x] Toggle open/close/hide settings that are not the bare minimum

**Comment by bohandley** [comment]
Added more clear info on description https://docs.google.com/document/d/11XMaYHSMSra8AoN2-yVW-5QPbjEXgkAFbTIF6N84cGE/edit#heading=h.o1zp7h8irwci

**Comment by bohandley** [comment]
Look at removing azure feature toggle prometheusAzureOverrideAudience https://github.com/grafana/grafana/issues/65808

**Comment by bohandley** [comment]
Stage II is merged! Looking forward to the bug bash to make sure eveything is working.

Still to implement:
- [ ] SigV4 style updates in aws repository (in progress)
- [ ] Return success with Prom type. The prom type image used to be shown in the save and test modal message (in progress via alert WIP)
- [ ] Use Editable header component (in progress dependent on enterprise squad)

**Comment by bohandley** [comment]
After SigV4 PR is closed, I will be closing this and adding three more issues.

- [ ] make the config overhaul GA
- [ ] Return success with Prom type. The prom type image used to be shown in the save and test modal message (in progress via alert WIP)
- [ ] Use Editable header component (in progress dependent on enterprise squad)
