### ISSUE TITLE
Loki: Improve query caching

### ISSUE THREAD

**Issue by svennergr** [grafana/grafana#65994]
### Summary

Loki queries are cached based on the exact query expression. This PR lists some opportunities to improve caching.

### Solution

```[tasklist]
### Tasks
- [ ] trim query expressions before queries are executed
- [x] investigate if it would be worth sorting labels before queries are executed
- [x] investigate other opportunities to improve caching (e.g. sort parameters for `json` parser)
```

### Measurement

We already have metrics for cache hits and misses.

**Comment by gtk-grafana** [comment]
Pitching something we did for Prometheus:
Caching resource calls via setting the [`X-Grafana-Cache`](https://github.com/grafana/grafana/blob/1bf94058dbcbef0017f83a8fcad78355afcd9492/pkg/tsdb/prometheus/resource/resource.go#L49) could help us decrease the number of API calls that hit the backend/db (from query writing UI), if you snap the time ranges.

With Prometheus, we heard from users that the labels over time for production instances were relatively stable, so snapping the duration of resource queries to the closest minute(s)/hour didn't negatively impact the query writing UX: by potentially returning label/values that don't entirely match the duration of the current query.

If this assumption holds true for Loki as well I would suggest this as an easy way to speed up the query writing UX, and reduce number of API calls made.

**Comment by gtk-grafana** [comment]
Also snapping the request from/to to the nth closest minute would probably help hit the cache more then the other proposed solutions? (but for the actual query, instead of the metadata/resource calls proposed in my previous comment), but this might also not be appropriate for all use cases
