### ISSUE TITLE
Epic: DataViz Documentation

### ISSUE THREAD

**Issue by jennyfana** [grafana/grafana#66008]
An Epic to record all the activities to do with Documentation and DataViz.  We need to do a review of all the documentation for all the panels in the DataViz domain and then apply any fixes required.

```[tasklist]
### Review
- [ ] https://github.com/grafana/grafana/issues/66010
```

```[tasklist]
### Fixes
- [ ] https://github.com/grafana/grafana/issues/66011
- [ ] https://github.com/grafana/grafana/pull/62113
- [ ] https://github.com/grafana/grafana/issues/66195
- [ ] https://github.com/grafana/grafana/issues/67157
```

**Comment by jennyfana** [comment]
The context of this Epic was to collect all the work relating to docs work for specific panel work.  We will use the type/docs label to monitor any documentation work that needs to progress.
