### ISSUE TITLE
Text component [build]

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#66135]
**Goal**
Create a `Text` component that can be used to apply typography styles in a simple way, without the need of extra css.

**Tasks**
- [ ] Make use of the [component skeleton](https://github.com/grafana/grafana/tree/main/packages/grafana-ui/src/components/Typography) previously created by Torkel
- [ ] Should have following props: as, variant, weight, color, truncate, textAlignment, margin, className, children
- [ ] Prop `variant` should be calculated by default depending on what `as` we define, i.e. if `as='h1'` then the variant should be `theme.typography.h1`
- [ ] Create storybook story with controls

Use the [exploration sheet](https://docs.google.com/spreadsheets/d/1yq4K-JjS-8eAM6XhxHiCHwKj2S9WOA4A2WTEhxHVxnc/edit#gid=793665239) for more information on each prop.
