### ISSUE TITLE
Epic: Timeseries

### ISSUE THREAD

**Issue by adela-almasan** [grafana/grafana#66196]
```[tasklist]
### Release v10.0 
- [ ] https://github.com/grafana/grafana/issues/35486
- [ ] https://github.com/grafana/grafana/issues/64642
```

```[tasklist]
### Graph parity 
- [ ] https://github.com/grafana/grafana/issues/49670
```

```[tasklist]
### Features 

```

```[tasklist]
### Bugs 🐞
- [ ] https://github.com/grafana/grafana/issues/66625
- [ ] https://github.com/grafana/grafana/issues/66626
- [ ] https://github.com/grafana/grafana/issues/64088
- [ ] https://github.com/grafana/grafana/issues/56085
- [ ] https://github.com/grafana/grafana/issues/36882
- [ ] https://github.com/grafana/grafana/issues/46581
- [ ] https://github.com/grafana/grafana/issues/62447
- [ ] https://github.com/grafana/grafana/issues/63840
- [ ] https://github.com/grafana/grafana/issues/43909
- [ ] https://github.com/grafana/grafana/issues/52538
- [ ] https://github.com/grafana/grafana/issues/46273
- [ ] https://github.com/grafana/grafana/issues/65581
- [ ] ---------- Investigate further ----------
- [ ] https://github.com/grafana/grafana/issues/34912
- [ ] https://github.com/grafana/grafana/issues/42994
- [ ] https://github.com/grafana/grafana/issues/39740
- [ ] https://github.com/grafana/grafana/issues/46440
- [ ] https://github.com/grafana/grafana/issues/57565
- [ ] https://github.com/grafana/grafana/issues/63413
- [ ] https://github.com/grafana/grafana/issues/44417
- [ ] https://github.com/grafana/grafana/issues/47991
- [ ] https://github.com/grafana/grafana/issues/49515
- [ ] https://github.com/grafana/grafana/issues/61010
```

```[tasklist]
### Clean code 🧼
- [ ] https://github.com/grafana/grafana/issues/66886
```

**Comment by grafanabot** [comment]
@adela-almasan please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:

**Comment by nmarrs** [comment]
This epic looks... epic! Great job on creating this @adela-almasan 😄
