### ISSUE TITLE
Epic: Improve backend plugins documentation

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#66401]
The documentation for [backend plugins](https://grafana.com/docs/grafana/latest/developers/plugins/backend/)  is quite sparse. It does however give good high level information, but doesn't answer how it works on a more technical level. Would be nice with some additional technical details, like architectural figures and so on. 

In addition, there are some backend plugin documentation mixed in with the [Add authentication for data source plugins](https://grafana.com/docs/grafana/latest/developers/plugins/add-authentication-for-data-source-plugins/#authenticate-using-a-backend-plugin). Might be an opportunity to divide the [Build a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/) to make it more clear what's related to plugins without a backend and the other way around.

```[tasklist]
### Tasks
- [x] https://github.com/grafana/grafana/issues/75706 https://github.com/grafana/plugin-tools/pull/448
- [ ] https://github.com/grafana/grafana/issues/79862
- [ ] https://github.com/grafana/plugin-tools/issues/480
- [ ] New page: Instance management
- [ ] New page: Error handling (related https://github.com/grafana/grafana/issues/75761)
- [ ] New page: Add a resource handler (https://community.grafana.com/t/how-to-add-a-resource-handler-for-your-data-source/58924)
- [ ] New page: Add a query multiplexer/router (https://community.grafana.com/t/how-to-add-a-query-multiplexer-router-for-your-datasource/59406)
- [ ] New page: HTTP client
```

**Comment by sympatheticmoose** [comment]
cc @josmperez

**Comment by josmperez** [comment]
Let's make this structural change in Q4, shouldn't take long.

**Comment by marefr** [comment]
@josmperez sounds good :+1: 

> Are there existing architectural diagrams we could refer to?

I think what we did in Q3 is enough so we can skip this

**Comment by marefr** [comment]
Probably not in Q4. But hopefully Q1. 

The "New page: Add a resource handler" and "New page: Add a query multiplexer/router" I think is something you could draft if you're up for it. My idea was probably just to copy the content from the community site.

**Comment by josmperez** [comment]
@marefr - The two subtasks based on community forum posts are now drafted, submitted for review. Please take a look.
