### ISSUE TITLE
Data sources - migrate to new form styling

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#66479]
Migrate the following data sources to new form styling that can be found [here](https://developers.grafana.com/ui/latest/index.html?path=/story/forms-form--basic)

**Metrics**
- [ ] Prometheus
- [ ] InfluxDB
- [ ] Graphite
- [ ] OpenTDSB

**Logs**
- [ ] Loki
- [ ] Opensearch
- [ ] Elasticsearch

**Traces**
- [ ] Tempo
- [ ] Jaeger
- [ ] Zipkin
- [ ] Flare
- [ ] Parca

**AWS**
- [x] Cloudwatch
- [x] Athena
- [x] Redshift
- [ ] Timestream
- [x] Xray
- [ ] OpenSearch
- [x] Sitewise
- [x] Twinmaker

**Partner Plugins** 
I believe these are under their own repo (or at least some)
- [x] Azure Monitor
- [x] Azure Data Explorer
- [x] Cloud Monitoring
- [x] Sentry
- [x] Clickhouse
- [x] Humio
- [ ] Datastax
- [x] MSSQL

**OSS Big Tent**
- [ ] MySQL
- [ ] PostgresSQL
- [ ] Github
- [ ] Google Sheets
- [ ] CSV
- [ ] JSON API
- [ ] Zabbix

**BI**
- [ ] Google BigQuery
- [ ] DataViz
- [ ] Simple JSON

**Enterprise data sources**
All of these are under their own repo
- [ ] AppDynamics plugin
- [ ] DataDog plugin
- [ ] Dynatrace plugin
- [ ] Honeycomb plugin
- [ ] NewRelic plugin (New Relic)
- [ ] SignalFx plugin
- [ ] WaveFront plugin
- [ ] Azure Devops plugin
- [ ] GitLab data source
- [ ] Jira data source
- [ ] MongoDB data source
- [ ] Oracle data source
- [ ] Salesforce datasource
- [ ] SAP Hana
- [ ] ServiceNow data source
- [ ] Snowflake data source
- [ ] SQLyze data source
- [ ] Databricks data source
- [ ] Splunk plugin

**Comment by grafanabot** [comment]
@staton-hyse11 please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:
