### ISSUE TITLE
Saga: Contribution process

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#66518]
We need to better understand the contribution process and how well it is servicing the needs of our designers and developers
```[tasklist]
### Tasks
- [x] Create initial contribution process workflow
- [x] Gather feedback from past contributors
- [x] Adjust workflow to match experiences
```
