### ISSUE TITLE
Public dashboards GA

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#66586]
**Features**
- [ ] #74347
- [ ] https://github.com/grafana/grafana/issues/74346
- [x] https://github.com/grafana/grafana/issues/74350
- [x] https://github.com/grafana/grafana/issues/62903
- [x] https://github.com/grafana/grafana/issues/65957
- [x] https://github.com/grafana/grafana-enterprise/issues/5186
- [x] https://github.com/grafana/grafana/issues/72107
- [x] https://github.com/grafana/grafana/issues/73790

**UX**
- [x] https://github.com/grafana/grafana/issues/64319

**Tech Debt**
- [x] https://github.com/grafana/grafana/issues/69024

**Docs** 
- [x] #74693
- [x] https://github.com/grafana/grafana/issues/62394

**Bugs**
- [x] https://github.com/grafana/grafana/issues/67556
- [x] https://github.com/grafana/grafana/issues/62479
- [x] https://github.com/grafana/grafana/issues/61896
- [x] https://github.com/grafana/grafana/issues/69022
- [x] https://github.com/grafana/grafana-enterprise/issues/5279
- [x] https://github.com/grafana/grafana-enterprise/issues/5327
- [x] https://github.com/grafana/grafana/issues/72260

**Spikes**
- [x] https://github.com/grafana/grafana/issues/62369
- [x] https://github.com/grafana/grafana/issues/71057
