### ISSUE TITLE
UI Extensions: Introduce configuration options

### ISSUE THREAD

**Issue by leventebalogh** [grafana/grafana#66716]
### What is the new use-case?

We have recieved a request (from the [Private Datasources Plugin](https://github.com/grafana/grafana-pdc-app)) to make it possible to extend the Datasources configuration form with a custom section. As the logic of handling the existing secure networks already lives in the plugin itself (grafana-pdc-app), this could help them a lot with keeping all the relevant logic in a single place and to keep it decoupled from core.

![Screenshot 2023-04-18 at 8 13 07](https://user-images.githubusercontent.com/9974811/232687451-9ada92ee-0499-4630-b5c7-143a1274da50.png)

### Possible issues
Introducing an extension point to the Datasources configuration form also comes with the risk of any plugins being able to register their own sections, which can "pollute" the form in a way that it's overly complex, hard to oversee, etc. There is also a chance for a plugin "listening into" other changes inside the form using the react-hook-form context. 

**A possible solution** 
We could introduce a Grafana configuration for UI extensions, where the admins could white-list which plugins are allowed to extend a certain extension point.

---

```[tasklist]
### Tasks
- [x] Create a PoC for registering UI elements as extensions, and introducing an extension point in the datasources-configuration which handles them
- [x] Create a PoC for adding a Grafana configuration option for UI extensions. (Also figure out a way to restrict - possibly by  whitelisting - which plugins are allowed to extend a certain extension point.)
- [ ] Create public extension point for configuration
- [ ] Update documentation for new extension point
- [ ] Create documentation for managing extension points
```

**Comment by tolzhabayev** [comment]
@leventebalogh I have detached the "As admin I want to control ext. points" so we can keep it as a backlog issue. And closing this one until we have more clear common use cases, PDC is good for now.
