### ISSUE TITLE
Use the new alert state history API

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#66949]
Following https://github.com/grafana/grafana/issues/48359, we can use the new alert state history API in the Grafana Alerting frontend: 

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/63654
- [ ] https://github.com/grafana/grafana/issues/63655
- [ ] https://github.com/grafana/grafana/issues/64535
- [ ] https://github.com/grafana/grafana/issues/63656
- [ ] https://github.com/grafana/grafana/issues/63658
- [ ] https://github.com/grafana/grafana/issues/63659
- [ ] https://github.com/grafana/grafana/issues/63660
- [ ] Update dashboards to query the state history endpoint over the annotations endpoint (pending, needs expansion)
```

**Comment by dudufan** [comment]
I cannot find the feature that query alert history via http API, does grafana not support?
