### ISSUE TITLE
Simpler alert rule creation process

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#66983]
Following the UX work done in https://github.com/grafana/grafana/issues/60576, we want to provide a new way of creating alert rules with multiple steps and a wizard instead of a long form.

For the community, here is a preview regarding how the first step could look like:
<img width="1149" alt="SS 2023-04-20 at 17 21 59" src="https://user-images.githubusercontent.com/2117580/233412656-25b6b88f-33aa-4967-a20b-72d04fc07645.png">

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/68093
- [ ] https://github.com/grafana/grafana/issues/68094
- [ ] https://github.com/grafana/grafana/issues/68098
- [ ] https://github.com/grafana/grafana/issues/68099
- [ ] https://github.com/grafana/grafana/issues/68100
- [ ] https://github.com/grafana/grafana/issues/68121
- [ ] https://github.com/grafana/grafana/issues/68185
- [ ] https://github.com/grafana/grafana/issues/68200
- [ ] https://github.com/grafana/grafana/issues/68615
- [ ] https://github.com/grafana/grafana/issues/70317
```

**Comment by VermaPriyanka** [comment]
Can you share a preview of the Mimir/Loki rule as well?

**Comment by VermaPriyanka** [comment]
What would the form look like for a Mimir/Loki data source, for data source managed alert rules?

**Comment by alexweav** [comment]
Related OSS issue that might be covered: https://github.com/grafana/grafana/issues/49009
