### ISSUE TITLE
A11y: [Modal] Improve a11y

### ISSUE THREAD

**Issue by L-M-K-B** [grafana/grafana#67302]
There are several issues with Modal and components using Modal.

### Tasks
- [x] #67297
- [x] #45509
- [x] A11y: [Modal] Make content scrollable to improve a11y (buttons can be hidden when the content is too long)
  - remove style overrides on `ValueMappingsEditorModal` (`tableWrap`)
- [x] A11y: [Modal] Add role="dialog" to the actual modal part of the component
- [x] A11y: [Modal] Improve visuals on smaller screen widths
- [ ] https://github.com/grafana/grafana/issues/94966
- [ ] Add modal width variants? (narrow/default/wide)

**Comment by taleena** [comment]
These are all easy to test together, keeping it as one issue.
