### ISSUE TITLE
Saga: Toggletip — padding is too large

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#67390]
The current `ToggleTip` padding is exceptionally large compared to other, similar popover-type components. 

```[tasklist]
### Tasks
- [x] Adjust padding to 16px [code]  (Remove title top padding and footer bottom padding and just have a container padding of 16px)
- [x] Adjust padding to 16px [design]
- [ ] Document spacing decisions for future reference [document]
```

**Comment by staton-hyse11** [comment]
Spacing information:

- large Cards use 16px
- Panels 8px
- Page container on large screens 24px
- Page container on small screens 16px

**Comment by Aires-Grafana** [comment]
@staton-hyse11 Toggletip component updated in Figma with 16px padding set in autolayout.

**Comment by JoaoSilvaGrafana** [comment]
This is done on the code on [this PR](https://github.com/grafana/grafana/pull/75007/files)

**Comment by staton-hyse11** [comment]
I don't think we need to formally capture the sizing changes. This ticket is complete.
