### ISSUE TITLE
FlameGraph: Add features from pyroscope/flamegraph

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#67729]
We want to align the flamegraph visualizations to be eventually able to use single library.

Features missing from the flamegraph currently:

```[tasklist]
### Tasks
- [x] sandwich view - selecting a node, shows all parents and all children https://github.com/grafana/grafana/pull/69723
- [x] text align buttons - for long node labels sometimes it make sense to show end of the text rather than start https://github.com/grafana/grafana/pull/68893
- [x] different color coding based on node type https://github.com/grafana/grafana/pull/70770
- [x] diff view - isn't used in Grafana yet but will be needed if we want to switch with pyroscope/flamegraph
- [ ] graph view - TBD not clear how much this is valuable for the flamegraph
- [ ] highlight similar nodes based on selected node
- [ ] color coding table based on the same schema as the graph
```

**Comment by tomershafir** [comment]
Hi, I would suggest to pull compare view as well.

Also, can you maybe share an ETA?

**Comment by tomershafir** [comment]
As part of the differential graph feature, I would suggest addressing elided functions issue, like [Brendan Greg suggests](https://www.brendangregg.com/blog/2014-11-09/differential-flame-graphs.html)

**Comment by aocenas** [comment]
@tomershafir tag explorer and compare view probably won't be part of profile view in Explore. There is a separate app plugin for pyroscope available on Grafana Cloud. We may work on something but because of the generic way Explore works it is not straight forward to port those views there.

> As part of the differential graph feature, I would suggest addressing elided functions issue, like [Brendan Greg suggests](https://www.brendangregg.com/blog/2014-11-09/differential-flame-graphs.html)

Will have to check but I don't think we will have that problem because pyroscope returns profile diffs as merged(profile1, profile2) and then color code based on the difference so we show all the code paths from both. @petethepig am I right with this?

**Comment by tomershafir** [comment]
@aocenas hey, what about the diff view? its really useful to observe changes

**Comment by aocenas** [comment]
@tomershafir At this moment diff view exists inside a Pyroscope App plugin which is available in Grafana Cloud. Adding a sensible diff capability inside Explore is a bigger task we may work in the future but isn't priority right now.
