### ISSUE TITLE
New data source picker GA

### ISSUE THREAD

**Issue by ivanortegaalba** [grafana/grafana#67908]
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/68630
- [ ] https://github.com/grafana/grafana/issues/67948
- [ ] https://github.com/grafana/grafana/issues/68631
- [ ] https://github.com/grafana/grafana/issues/68825
- [ ] https://github.com/grafana/grafana/issues/68826
- [ ] https://github.com/grafana/grafana/issues/68316
- [ ] https://github.com/grafana/grafana/issues/69435
- [ ] https://github.com/grafana/grafana/issues/66914
- [ ] https://github.com/grafana/grafana/issues/66916
- [ ] https://github.com/grafana/grafana/issues/69109
- [ ] https://github.com/grafana/grafana/issues/69209
- [ ] https://github.com/grafana/grafana/issues/69691
```
