### ISSUE TITLE
Create panel: Split between visualization and widget

### ISSUE THREAD

**Issue by ivanortegaalba** [grafana/grafana#67910]
### Scope
In order to simplify panel creation, we'd like to split the types of panels by whether they need data or not. 

### Requirements & Caveats
* Panels that require a datasource being set up will be called "visualisations". E.g: timeseries, table, stats, etc. 
* Panels that don't work with a data source will be called "widgets". E.g dashboard list, news, annotations, etc.
* Deliver a PoC to test if users understand the differences between widgets and visualization. This will be under FF to deploy it to a small number of users and gather metrics.
* FullStory session recording will provide us a thorough understanding of our changes and feature usage.

```[tasklist]
### Tasks
- [x] Create designs
- [ ] https://github.com/grafana/grafana/issues/69539
- [ ] https://github.com/grafana/grafana/issues/70911
```

#### Things we did not tackle during POC that are relevant for the code to be GA
- [ ] 	`PanelTypeCard` need some refactoring to fix a11y issues and comply with design styles
- [ ]  e2e are missing and we could benefit from more unit test
- [ ]  We are filtering library panels between widgets and viz in the frontend , we should analyze if we can do this in the backend

##### Suggestions from the POC PR 
- [Extract getPluginMetaData outside
](https://github.com/grafana/grafana/pull/70850#discussion_r1251830330)
-  [Refactor isWidget logic](https://github.com/grafana/grafana/pull/70850#discussion_r1251868970)
- [Componentize DashboardEmpty page](https://github.com/grafana/grafana/pull/70850#discussion_r1251889246)

### Resources
- [Product DNA](https://docs.google.com/document/d/1w538TNK1NXKs4vlrUPcRWG97dTZk4kUBe7B7NxmaGh4/edit?usp=sharing)
- [Figma](https://www.figma.com/file/RqCjSrm8uj0Xa003mfAfel/Dashboards-G10?type=design&node-id=1606-6115&t=ayUZ4c3FFgi4VtfJ-0)

**Comment by imatwawana** [comment]
Not sure but under the things that need to be considered for GA, should we add docs updates? There would be some restructuring of the documentation since widgets woudln't be grouped under Visualizations anymore and we'd probably need to make some changes in other docs to change naming conventions.
