### ISSUE TITLE
Remove legacy access control

### ISSUE THREAD

**Issue by IevaVasiljeva** [grafana/grafana#68076]
**What**

Starting from Grafana 10, RBAC is enabled by default. We should remove legacy access control code, as it is not used anymore.

**Why**

The main goals are:
* make access control code simpler and easier to read and reason about;
* make the code more maintainable (less code ~> less work when making changes)
* catch any RBAC bugs that might have made it through

**Tasks**

Feel free to add/remove items from here, this is a quick list of tasks that were on top of my mind

- [ ] Remove access control conditionals that check if RBAC is enabled or not
- [ ] Remove the `IsDisabled` method
- [ ] Remove the legacy AC filter for dashboard and folder search
- [ ] Remove legacy AC guardians for dashboards and folders
- [ ] Remove legacy AC guardians for data sources
- [ ] Remove the legacy AC fallback from AC middleware
- [ ] Remove the legacy AC fallback from the frontend route registration
- [ ] Remove legacy AC tests (most of them have postfix `_LegacyAccessControl`)
- [ ] Remove legacy AC DB entries (ie, ACL tables) - note that we shouldn't do this for a while, as it'll make downgrade to a version running on the legacy AC impossible

**Comment by IevaVasiljeva** [comment]
Some other related PRs:
* cleaning up dash and folder access check logic: https://github.com/grafana/grafana/pull/68968
* legacy test removal and updating tests that are still relevant:
   * https://github.com/grafana/grafana/pull/68895
   * https://github.com/grafana/grafana-enterprise/pull/5184
* removing legacy AC for teams (a multi-part series):
   * https://github.com/grafana/grafana/pull/68841
   * https://github.com/grafana/grafana/pull/68840
   * https://github.com/grafana/grafana-enterprise/pull/5176
   * https://github.com/grafana/grafana/pull/68820
   * https://github.com/grafana/grafana/pull/68715
