### ISSUE TITLE
Prioritization List of Components [epic]

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#68071]
**Goal:**
Create a list of the **high-complexity** components to be done, based on this [inventory](https://docs.google.com/spreadsheets/d/1n_9PWs0DCMwKX1KGJcOBG72UvGHJBqTaByfMJZitSmY/edit#gid=0)

```[tasklist]
### Tasks
- [ ] Investigate what other primitives should be prioritized
- [ ] Identifying the most important components to pick up
- [ ] Categorize components for people to contribute vs saga core team to be responsible
```
