### ISSUE TITLE
Auth: Use PKCE by default (If OAuth provider supports PKCE)

### ISSUE THREAD

**Issue by arukiidou** [grafana/grafana#68073]
**What is the chore?**:

Change default to true for providers that support PKCE.
v10.0 coming up, I think now is the time.

- follow-up
  - #22122
    - #39948

**Is there anything else we need to know?**:

- Ensure that it can be overridden by env as an escape hatch
  - `GF_AUTH_AZUREAD_USE_PKCE`
  - `GF_AUTH_GITLAB_USE_PKCE`
  - `GF_AUTH_GOOGLE_USE_PKCE`
  - `GF_AUTH_OKTA_USE_PKCE`

Github and Generic should not be changed yet.

| Provider | Supports PKCE | Reference | 
| -------- | ------------- | ------ | 
| Azure AD | Yes           |       https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow | 
| Github   | No            |  https://github.com/orgs/community/discussions/40077     | 
| GitLab   | Yes           |      https://docs.gitlab.com/ee/api/oauth2.html#supported-oauth-20-flows  | 
| Google   | Yes           |     https://developers.google.com/identity/protocols/oauth2/native-app?hl=en   | 
| Okta     | Yes           |      https://developer.okta.com/docs/guides/implement-grant-type/authcodepkce/main/  | 
| Generic  | Unknown       | -      | 

- suggest labels
  - https://github.com/grafana/grafana/labels/area%2Fauth%2Foauth
  - https://github.com/grafana/grafana/labels/breaking%20change
  - https://github.com/grafana/grafana/labels/add%20to%20changelog
  - https://github.com/grafana/grafana/labels/no-backport

- relates #64746

```[tasklist]
### Tasks
- [x] Add use_pkce to defaults.ini #68095
- [x] Add use_pkce to sample.ini #68095
- [x] Ensure that it can be overridden by env #68095
- [ ] Update document
```

**Comment by eleijonmarck** [comment]
@arukiidou thank you for the contribution. this is something we would definitely want to have and it does make sense.
We are having discussions about bundling this together with other potential OAuth breaking changes not part of v10

We are looking at the changes currently and evaluating if this should be part of v10 or part of OAuth breaking changes
