### ISSUE TITLE
Saga - Update visual assets for new alerts

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#68103]
Update Saga content with the new design of Alerts, first step is to design the assets [here](https://www.figma.com/file/Ft7z7ysVzVhtCf7SFlvzyN/Site-Assets?type=design&node-id=115-3068&t=8x6SalAIV7jTjx1V-0), then update Saga portal.

```[tasklist]
### Tasks
- [ ] Banner ([Figma Link](https://www.figma.com/file/htVIFrTq8e7sx8Olo7L6kZ/Saga-Components--Dark-theme?type=design&node-id=12611-15120))
- [ ] Inline Banner ([Figma Link](https://www.figma.com/file/htVIFrTq8e7sx8Olo7L6kZ/Saga-Components--Dark-theme?type=design&node-id=12611-15121))
- [ ] Toast ([Figma Link](https://www.figma.com/file/htVIFrTq8e7sx8Olo7L6kZ/Saga-Components--Dark-theme?type=design&node-id=12611-15122))
```

**Comment by staton-hyse11** [comment]
This is no longer needed.
