### ISSUE TITLE
Epic: Legends - Outdated

### ISSUE THREAD

**Issue by adela-almasan** [grafana/grafana#68135]
```[tasklist]
### Existing issues
- [ ] https://github.com/grafana/grafana/issues/75879
- [ ] https://github.com/grafana/grafana/issues/66704
- [ ] https://github.com/grafana/grafana/issues/64084
- [ ] https://github.com/grafana/grafana/issues/65299
- [ ] https://github.com/grafana/grafana/issues/46273
- [ ] https://github.com/grafana/grafana/issues/18186
- [ ] https://github.com/grafana/grafana/issues/60746
- [ ] https://github.com/grafana/grafana/issues/65275
- [ ] https://github.com/grafana/grafana/issues/73442
- [ ] https://github.com/grafana/grafana/issues/21962
- [ ] https://github.com/grafana/grafana/issues/73575
- [ ] https://github.com/grafana/grafana/issues/73211
- [ ] https://github.com/grafana/grafana/issues/83785
- [ ] https://github.com/grafana/grafana/issues/84328
- [ ] https://github.com/grafana/grafana/issues/85183
```

**Comment by baldm0mma** [comment]
Closing in favor the new [Legend Epic](https://github.com/grafana/grafana/issues/86938).
