### ISSUE TITLE
Epic: BI App

### ISSUE THREAD

**Issue by supilee** [grafana/grafana#68165]
```[tasklist]
### Deliverables
- [ ] https://github.com/grafana/grafana/issues/70428
- [ ] https://github.com/grafana/grafana/issues/70441
- [ ] https://github.com/grafana/grafana/issues/70443
- [ ] https://github.com/grafana/grafana/issues/70440
- [x] https://github.com/grafana/grafana/issues/69027 --> Q2
- [ ] https://github.com/grafana/grafana/issues/70093 --> Q3
```
