### ISSUE TITLE
Expression card improvements

### ISSUE THREAD

**Issue by soniaAguilarPeiron** [grafana/grafana#68194]
https://www.figma.com/proto/AYMboJsnYgSAAdYM9hoMLn/Alerting?page-id=0%3A1&type=design&node-id=1323-29936&viewport=897%2C-2807%2C0.3&scaling=min-zoom&starting-point-node-id=1322%3A29730

```[tasklist]
### Tasks
- [x] Remove the expression type selector from the header of an expression and only have the type as read-only. The expression type should not be editable - i.e. if I've added for example a Math expression, it cannot be changed to a different kind of expression, it can only be removed.
- [x] Reduce, Threshold, Math and Resample should use half of the screen width. Classic condition should use the full screen width
- [x] Add the expression description to the expression body
- [x] Make order of fields consistent for all the expression types
- [x] Remove alert condition footer and move it to the header
- [ ] https://github.com/grafana/grafana/issues/68195
```
