### ISSUE TITLE
Saga DS - Link component [epic]

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#68222]
Create a `Link component` to be used within Grafana
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/68481
- [ ] https://github.com/grafana/grafana/issues/69303
- [ ] https://github.com/grafana/grafana/issues/70573
- [x] Link component [publish]
```
