### ISSUE TITLE
Saga DS - Color Tokens [epic]

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#68220]
Establish clear definitions of how color is used throughout the product and provide a systemic approach.
At the end we should have a POC of how color tokens would be used across Grafana.

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/69274
- [ ] Color Tokens [design]
- [ ] Color Tokens [build]
- [ ] [Color Tokens [document]](https://github.com/grafana/grafana/issues/51766)
- [ ] Color Tokens [publish]
```

**Comment by staton-hyse11** [comment]
Closing this to track all token work under #80673
