### ISSUE TITLE
Epic: Tooltips

### ISSUE THREAD

**Issue by adela-almasan** [grafana/grafana#68238]
```[tasklist]
### Heatmap tooltip prerequisites
- [ ] https://github.com/grafana/grafana/issues/13895
- [ ] https://github.com/grafana/grafana/issues/71159
- [ ] https://github.com/grafana/grafana/pull/71238
- [ ] https://github.com/grafana/grafana/issues/72405
```

```[tasklist]
### Issues/Blockers
- [ ] https://github.com/grafana/grafana/pull/79531
- [ ] https://github.com/grafana/grafana/pull/76379
- [ ] https://github.com/grafana/grafana/pull/75328
- [ ] https://github.com/grafana/grafana/pull/75597
- [ ] https://github.com/grafana/grafana/pull/75382
- [ ] https://github.com/grafana/grafana/pull/75499
- [ ] https://github.com/grafana/grafana/pull/75329
- [ ] https://github.com/grafana/grafana/pull/76675
```

```[tasklist]
### Phase 1
- [ ] https://github.com/grafana/grafana/issues/69348
- [ ] https://github.com/grafana/grafana/pull/70872
- [ ] https://github.com/grafana/grafana/pull/71603
- [ ] https://github.com/grafana/grafana/issues/71156
- [ ] https://github.com/grafana/grafana/issues/71157
- [ ] https://github.com/grafana/grafana/issues/71158
- [ ] https://github.com/grafana/grafana/issues/71895
- [ ] https://github.com/grafana/grafana/issues/71790
- [ ] https://github.com/grafana/grafana/issues/75843
```

```[tasklist]
### Phase 2
- [ ] https://github.com/grafana/grafana/issues/75688
- [ ] https://github.com/grafana/grafana/issues/75656
- [ ] https://github.com/grafana/grafana/issues/77247
- [ ] https://github.com/grafana/grafana/issues/77250
- [ ] https://github.com/grafana/grafana/issues/77633
- [ ] https://github.com/grafana/grafana/issues/71900
- [ ] https://github.com/grafana/grafana/pull/78703
- [ ] https://github.com/grafana/grafana/pull/78353
```

```[tasklist]
### Phase 3
- [ ] https://github.com/grafana/grafana/issues/75689
- [ ] https://github.com/grafana/grafana/issues/77658
- [ ] https://github.com/grafana/grafana/issues/75655
- [ ] https://github.com/grafana/grafana/issues/78771
- [ ] https://github.com/grafana/grafana/issues/78772
- [ ] https://github.com/grafana/grafana/issues/78773
- [ ] https://github.com/grafana/grafana/issues/78835
- [ ] https://github.com/grafana/grafana/issues/79717
- [ ] https://github.com/grafana/grafana/issues/78923
- [ ] https://github.com/grafana/grafana/issues/78753
- [x] Tooltips: What's new
- [ ] https://github.com/grafana/grafana/pull/79531
- [ ] https://github.com/grafana/grafana/issues/75783
```

```[tasklist]
### Phase 4
- [ ] https://github.com/grafana/grafana/issues/80246
- [ ] https://github.com/grafana/grafana/issues/80243
- [ ] https://github.com/grafana/grafana/issues/80250
- [ ] https://github.com/grafana/grafana/issues/78775
- [ ] https://github.com/grafana/grafana/issues/80767
- [ ] https://github.com/grafana/grafana/issues/79605
- [ ] https://github.com/grafana/grafana/pull/81031
- [ ] https://github.com/grafana/grafana/issues/81202
- [ ] https://github.com/grafana/grafana/pull/81017
```

```[tasklist]
### Feedback/Bugs
- [ ] https://github.com/grafana/grafana/issues/80768
- [ ] https://github.com/grafana/grafana/issues/79485
- [ ] https://github.com/grafana/grafana/issues/79604
- [ ] https://github.com/grafana/grafana/issues/57956
- [ ] https://github.com/grafana/grafana/issues/82210
- [ ] https://github.com/grafana/grafana/issues/85446
```

```[tasklist]
### Later
- [ ] Geomap
- [ ] https://github.com/grafana/grafana/issues/79375
- [ ] https://github.com/grafana/grafana/issues/71605
- [ ] https://github.com/grafana/grafana/issues/71602
- [ ] Figure out https://github.com/grafana/grafana/issues/78444
- [ ] https://github.com/grafana/grafana/issues/73989
```

**Comment by lukasztyrala** [comment]
@adela-almasan + @Develer + @leeoniya + @drew08t 

Here is an attempt to simplify decisions around tooltips, as sometimes it seems we are moving in circles (which is not that bad considering this is an ongoing exploration and iteration, but we also need to keep delivery in mind):
1. Let's focus on delivering consistent architecture across all tooltips for the initial implementation.
2. This means ignoring specific use cases – we will return to them in the future on a per-panel basis.
3. We consider what we have today, not what will come.

With the above in mind, here is the suggestion for tooltip architecture and content across visualizations (-geomap, see below):

![Univers-Tooltip-Architecture](https://github.com/grafana/grafana/assets/141744/35c80c9f-b7dc-4e0c-a5bd-0c8d596440d1)

Next steps:
1. Transfer this thinking into Figma.
2. Add designs for `Add annotation` button to the tooltips.
5. Tackle Geomap tooltip (requires tabs or similar solution due to many layers)
