### ISSUE TITLE
Saga DS - Secondary button styling adjustment

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#68255]
@torkelo's recent design changes to the secondary button styling need to be captured for the Figma components.

PR for reference https://github.com/grafana/grafana/pull/68250

```[tasklist]
### Tasks
- [ ] Update dark theme secondary button styles
- [ ] Update light theme secondary button styles
- [ ] Update Saga site assets
```
