### ISSUE TITLE
Use Monaco Query Editor for Cloudwatch logs

### ISSUE THREAD

**Issue by katebrenner** [grafana/grafana#68448]
This will improve auto-complete, provide easier guidance and help for commands, etc.
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/68449
- [ ] https://github.com/grafana/grafana/issues/69341
- [ ] https://github.com/grafana/grafana/issues/69342
- [ ] https://github.com/grafana/grafana/issues/69344
- [ ] https://github.com/grafana/grafana/issues/69345
- [ ] https://github.com/grafana/grafana/issues/69346
- [x] Update What's New
- [ ] https://github.com/grafana/grafana/issues/69347
- [ ] https://github.com/grafana/grafana/issues/72311
- [ ] https://github.com/grafana/grafana/issues/75395
```
