### ISSUE TITLE
Link component [explore]

### ISSUE THREAD

**Issue by eledobleefe** [grafana/grafana#68481]
## **Goal**
Understand how and where we are using `links` through a UI audit

```[tasklist]
## Tasks
- [x] Explore the use of links through all Grafana and document it
- [x] Explore the use of links in other DS and document it
- [x] Sum up the info gathered and establish how the component should be
- [x] Review the findings and show the proposal to the Saga team
- [x] Create tasks for the following phases and go forward
```

**Comment by eledobleefe** [comment]
Closing this issue as completed. We go forward to the next step: [Link component [build]](https://github.com/grafana/grafana/issues/69303)
