### ISSUE TITLE
Instrumentation: Add label to HTTP request metrics/logs that defines the source of the error

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#68480]
### Problem
There is no easy way to differentiate between failures in Grafana or the downstream datasource. Grafana instruments the requests using the status returned from the datasource. Currently we work around this by [excluding those paths from SLOs and alerts since query correctness or datasource functionality are out of our control. Considering how important datasource requests are, the blind spot is very large.

The following is based on the consensus around proposal 2 in [design doc](https://docs.google.com/document/d/1_8KSW3O6R-0hzcVq9VPj9iLoB064NEdJDIEe0uh58Zo/edit#heading=h.qxgswnj04le).

### Proposal

For the `http_request_duration_seconds` metric add a new label, suggested to be named `errorSource`, that defines the source of the error. The allowed values of this label are:
- `grafana`: denoting an error/HTTP status happened within Grafana.
- `downstream` : denoting an error/HTTP status originating from a downstream server/backend plugin. 

Setting the `errorSource` label make most sense when HTTP status >= 4xx. Suggested to set it to `grafana` per default and when HTTP status < 4xx, but open for discussion. 

#### API Endpoints
Given `/api/datasources/proxy/uid/:uid/*`,  `/api/datasources/proxy/:id/*` and `/api/plugin-proxy/:pluginId/*`, which behaves like HTTP proxies. If the requests are sent downstream the `errorSource` should be considered `downstream`, otherwise `grafana`. Would Grafana fail to process the downstream response and write it out to the HTTP response the `errorSource` should be considered `grafana`.

Given `/datasources/:id/resources/* `,  `/api/datasources/uid/:uid/resources/*` and `/api/plugins/:pluginId/resources/*`, which normally mimics HTTP proxy over gRPC. If the requests are sent downstream the `errorSource` should be considered `downstream`, otherwise `grafana`. Would Grafana fail to process the downstream response and write it out to the HTTP response the `errorSource` should be considered `grafana`.

Given `/datasources/:id/health`,  `/api/datasources/uid/:uid/health` and `/api/plugins/:pluginId/health`. If the requests are sent downstream the `errorSource` should be considered `downstream`, otherwise `grafana`. Would Grafana fail to process the downstream response and write it out to the HTTP response the `errorSource` should be considered `grafana`.

#### POC
#65916 - this approach should work, but need to be able to signal/propagate an error is `downstream` within plugin management where the `contextmodel.ReqContext` is not available. I guess we already do that for `QueryData` ([code](https://github.com/grafana/grafana/blob/ab5a3820d5fff4f0f042024b0aee0632e6a4ca08/pkg/plugins/manager/client/client.go#L73)), but need to do that for `CallResource` and `CheckHealth` as well.

A related idea is to incorporate `errorSource` into https://github.com/grafana/grafana/tree/main/pkg/util/errutil to ease signal/propagate this information when there are no HTTP request/context available.

#### Questions
- Is there any use case to track `errorSource` when HTTP status < 4xx, i.e. downstream HTTP response of 200 being proxied through Grafana?
- What if errors happening within core plugins, e.g. Prometheus, would that be considered `downstream` or `Grafana`?

```[tasklist]
### Tasks
- [x] https://github.com/grafana/grafana/pull/74114
- [x] Remove the `datasourceQueryMultiStatus` feature toggle and related code using it, basically reverting #48550 https://github.com/grafana/grafana/pull/90191
- [ ] [Nice to have] Adding the team metadata - similar to https://github.com/grafana/grafana/pull/71010
- [x] Figure out if any other requests/routes need this, e.g. live? Shouldn't be any
- [ ] https://github.com/grafana/grafana/pull/75462
- [x] Remove requestInstrumentationStatusSource feature toggle
```

**Additional notes**
- Involve @bergquist into the PR reviews to keep him informed
```[tasklist]
### Rollout
- [ ] https://github.com/grafana/deployment_tools/pull/89884
- [ ] https://github.com/grafana/deployment_tools/pull/89982
- [ ] https://github.com/grafana/deployment_tools/pull/90206
- [ ] https://github.com/grafana/deployment_tools/pull/91666
```

**Comment by bergquist** [comment]
> Is there any use case to track errorSource when HTTP status < 4xx, i.e. downstream HTTP response of 200 being proxied through Grafana?

I can't think of any reason. 

> What if errors happening within core plugins, e.g. Prometheus, would that be considered downstream or Grafana?

That should be considered a grafana error. I don't think we can get this 100% correct but in general that is what we should aim for.

**Comment by marefr** [comment]
@bergquist thanks :pray: 

> That should be considered a grafana error. I don't think we can get this 100% correct but in general that is what we should aim for.

Think @wbrowne had an idea we could possibly use the "target" support to figure this out

**Comment by marefr** [comment]
From @bergquist: Would be nice to use this to hold the error source value https://github.com/grafana/grafana/blob/main/pkg/middleware/requestmeta/request_metadata.go#L18 as we're planning to add more things to this later.

**Comment by marefr** [comment]
@xnyo did have a look at streaming and live, but since they're websocket doesn't seem to apply here and/or it's a bit hard to digest.

**Comment by bergquist** [comment]
We should add some documentation about this in https://github.com/grafana/grafana/blob/main/contribute/backend/instrumentation.md#L1 before we consider it complete. Once we have that we can send it to other teams who might need to identify some of their requests as downstream errors.

**Comment by marefr** [comment]
@bergquist I realize now that we have this documented here https://github.com/grafana/grafana/blob/main/contribute/backend/errors.md#error-source so going to close this. Let us know if you don't agree
