### ISSUE TITLE
Layout component(s) [explore]

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#68528]
## **Goal**
Understand what are the requirements for Layout components in Grafana

```[tasklist]
## Tasks
- [x] Investigate what type of Layout components already exist in Grafana (inside and outside grafana/ui)
- [x] Research other design systems to gather how other Layout components are built and what properties they have
- [x] Document findings from discovery
- [x] Review the findings and show the proposal to the Saga team
- [x] Create tasks for the following phases and go forward
```

**Comment by JoaoSilvaGrafana** [comment]
Based on this [investigation](https://docs.google.com/spreadsheets/d/1rZVJrs9x7WIyd3RSrK-Z6i_knXweeYuzZx3DDueKpHA/edit#gid=0) of other design systems we are going to create "unstable" components for the following components:
- Stack (copied over from experimental)
- Flex
- Box
- Grid

And then figure out with the broader frontend team what is the best combination to use them.

**Comment by yaelleC** [comment]
@JoaoSilvaGrafana moving to done does not automatically close the issue. I'm closing it now, feel free to reopen if needed ;)
