### ISSUE TITLE
Gather snapshots analytics

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#68607]
### Goal
Understand how snapshots are being used so we can decide the next steps for this feature

```[tasklist]
### Tasks
- [x] Create a dashboard for all Sharing analytics
- [x] Gather usage metrics for the diff sharing features. To consider: Link, Snapshots, Export, PDF, Report, Public dashboards
- [ ] Measure: how many snapshots are being created in comparison to the amount of dashboards and org has?
- [ ] Qualitative research: understand what users use snapshots for. Either through an in-app or external survey.
- [ ] https://github.com/grafana/grafana/issues/70147
```

**Comment by grafanabot** [comment]
@natellium please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:
