### ISSUE TITLE
Spacing Tokens [explore]

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#68660]
```[tasklist]
### Tasks
- [x] Understand how spacing is being used today throughout the product
- [x] Create trial tokens to see how they impact product
- [x] Establish tokens within Token Studio
```

**Comment by staton-hyse11** [comment]
After exploring several different approaches to spacing, a path forward has been choosen.

Structure:
space.#
# = a multiplication of a root, which is 8px.

The scale is as such (1 = 8px):

- 0
- .25
- .5
- 1
- 1.5
- 2
- 2.5
- 3
- 4
- 5
- 6
- 8
- 10

The number is being represented as whole numbers (.25 = 25, 1 = 100, 5 = 500, 10 = 1000). This scale allows developers to easily understand the multiplication table at use and does not limit us to t-shirt sizes. T-shirt size, while are rather simple, are limiting in number and provide no indication of actual size.
