### ISSUE TITLE
EPIC: Frontend plugins sandboxing

### ISSUE THREAD

**Issue by academo** [grafana/grafana#68883]
Based on the discoveries here https://github.com/grafana/grafana/pull/66092

We want to implement [sandboxing](https://en.wikipedia.org/wiki/Sandbox_(computer_security)) of frontend plugins in grafana to enhance security.

### Tasks milestone 1
- [x] https://github.com/grafana/grafana/issues/68886
- [x] https://github.com/grafana/grafana/issues/69602
- [ ] Improve error messages from inside the sandbox.
- [x] Test the sandbox against the most popular plugins
- [x] https://github.com/grafana/grafana/issues/69846
- [x] #70898
- [x] #70602
- [x] #70360
- [x] #70843
- [x] #71713
- [x] #72269
- [x] #72270
- [x] #72329
- [x] #72669
- [x] #73392
- [x] #74439
- [x] #74552
- [x] #74587
- [x] #75290
- [x] #76225
- [x] #76356
- [x] #75514
- [x] https://github.com/grafana/plugins-private/issues/40
- [x] #89340

### Future tasks
- [ ] Investigate if we need to limit/scope local- and session storage access.
- [ ] Investigate if we need to limit access to cookies.

**Comment by KristianGrafana** [comment]
I installed the "Dynamic Text" plugin, as described [here](https://github.com/grafana/grafana/pull/68889) - and in that description on how to test, you mention that output in the console should be prefixed with `[plugin]` to ensure that arbitrary JavaScript is sandboxed. 

Based on small testing, I found a way to output data to the console without the mentioned prefix, furthermore, it seems like `alert(1)` will get outputted to the console as `[plugin] 1`, but I managed to actually do an alert. Please see the screenshot with a potential bypass and then just `alert(1)`

![image](https://github.com/grafana/grafana/assets/114284895/aa347d6f-e736-4a5b-a161-74dce9a71684)

Since this is a security feature, would you mind creating a forum for discussions around potential bypasses? Currently, it's unclear what you consider as a sandbox escape in the context of Grafana and its plugins.

**Comment by tolzhabayev** [comment]
**Project Update**

**Highlight**
We have decided to go make the sandbox not on by default but configurable by admins for specific plugins. We are currently trying to figure out settings storage for the sandbox and are a blocked by unified storage.

**Trending**


🟡 at risk


**Next**

We are trying to figure out the storage solution for sandbox settings.

**Comment by tolzhabayev** [comment]
**Project Update**

**Highlight**
Frontend Plugin Sandbox is in private preview in Grafana 11.5 and is rolled out to 100% of cloud customers already. 
We can resolve this EPIC and create single issues based on customer feedback.

**Trending**


🟢 on track


**Next**
