### ISSUE TITLE
EPIC: expose angular dependency

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/grafana#68974]
As a Grafana user, I can easily discover legacy angular components to begin migrations, so that I can upgrade my Grafana instances with confidence, and benefit from a more secure and reliable product experience.

Tasks:

- [x] As a user, I can see a dismissible warning that a dashboard I am viewing is using a legacy Angular component. 
  - [x] Sketch prototypes for how this could be presented in the UI and present for feedback from UX (Banner / Border / Tooltip / Other)
- [x] As a administrator, when browsing the plugin catalog or plugin details pages (admin > plugins, admin > plugins > plugin, connections > plugin, grafana.com/plugins), I can detect which are based on Angular through a new shield icon or persistent warning notification.
- [x] As an editor, when browsing the available datasources (connections > datasources, admin > datasources) I can detect which are based on Angular through a new shield icon or similar.
- [x] As an administrator, if I disable angular support, I am no longer able to install plugins which are based on Angular (similar experience to if the grafana version is incompatible). The install button should be disabled in order to prevent issues in Grafana Cloud.
- [x] As an administrator or Grafana support engineer, I can generate a list of all dashboards with angular panels and/or datasources.
- [x] As an administrator, I can disable Angular deprecation UI features for a specific plugin via the config ini
- [ ] Add telemetry to report number of detected Angular plugins installed
- [x] Add telemetry to detect that a(n anonymous) user has dismissed a warning and/or followed links to read the deprecation notice
- [ ] ~Spike: explore dummy react plugin to replaced angular plugins when support is disabled to still allow dashboards to load and present value information to the user.~
