### ISSUE TITLE
EPIC: Extract one core plugin out of the core

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#68973]
**Why?**
- Customers/users need to upgrade Grafana to get core plugin updates. Especially troublesome in Grafana Cloud if there’s a serious bug in a core plugin since the only way today is to downgrade the Grafana instance. The other way around, a bug in Grafana might stop customers from getting the new functionality/bug fixes of a core plugin they’ve been longing for and have to wait for a new Grafana version to be released.
- New versions of Grafana need to be released more often due to bugs and security issues in core plugins. 
- Grafana core plugin developers might take shortcuts and use Grafana core APIs and functionality rather than extending the official plugin SDKs. This limits certain plugins to only work when part of Grafana and makes it hard to package as an external plugin. Further, the larger plugin ecosystem cannot use any Grafana code that’s not exposed through the official SDK’s. As a result, Grafana core plugin developers do not dogfood the plugin platform enough and are not exposed to problems like maintaining compatibility with multiple Grafana versions. 
- We only support certain versions of services our datasources connect to in a specific Grafana version.
- [Internal doc with more why](https://docs.google.com/document/d/1bZIzJphoslR2qLIQIyZ7pYrL0WzpPXmuhvG5-Ejx_ZM/edit#)

**Design Doc**

https://docs.google.com/document/d/1K5xSlyABcv-ZAFlRR3RNBva8JQy5QYMUuvXFFcQw_qo

**Goals**
- Be able to update plugins separately
- Treat core plugins as normal plugins when it comes to usage of packages and APIs that we are offering

```[tasklist]
### Tasks
- [x] Discover what is necessary to be able to make core plugins - normal plugins (design doc and PoC branch done)
- [x] Figure out which plugin to extract as the first showcase (testdata data source)
- [ ] https://github.com/grafana/grafana/issues/71329
- [x] Conditionally skip loading test data source as a core plugin
- [x] Move test data source code to a new directory
- [ ] https://github.com/grafana/grafana/issues/74004
- [ ] https://github.com/grafana/grafana/pull/75388
- [ ] https://github.com/grafana/grafana/pull/75479
- [ ] https://github.com/grafana/grafana/pull/75528
```

**Comment by bhks** [comment]
Would Grafana alerting also needs to be refactored to use API path vs inbuilt service/interface dependency ? OR it would be just fine since the interface is separated from the client created InMemory for each plugins ?

**Comment by andresmgot** [comment]
At the moment, alerting is not a core plugin so it won't be affected by this task.
