### ISSUE TITLE
docs: add guidance on React Router 6 upgrade

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/grafana#69059]
At minimum a new section under here https://grafana.com/docs/grafana/next/developers/plugins/migration-guide/v9.x-v10.x/ would be good to help plugin developers understand their options and how this support has been enabled.

Could also consider it's own section i.e. `/migration-guide/react-router-5-6/` and linking from the former.
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/plugin-tools/pull/746
- [ ] https://github.com/grafana/plugin-tools/pull/707
- [ ] https://github.com/grafana/plugin-tools/pull/710
- [ ] https://github.com/grafana/scenes/pull/570
- [ ] https://github.com/grafana/grafana-plugins-platform-team/issues/81
- [ ] https://github.com/grafana/plugin-tools/pull/718
- [ ] https://github.com/grafana/grafana-plugin-examples/pull/245
- [ ] https://github.com/grafana/plugin-tools/pull/756
- [ ] https://github.com/grafana/grafana/issues/81988
- [x] Create an issue in `grafana/scenes` to update to react-router v6: https://github.com/grafana/scenes/issues/608
- [x] Add a post about the migration to the community forum (https://community.grafana.com/t/migrating-app-plugins-to-use-react-router-v6/115410)
- [x] Create a grouping issue for what needs to be done in core Grafana to migrate it to react-router v6 (https://github.com/grafana/grafana/issues/83666)
- [x] Create a grouping issue for tracking how internal app plugins update to react-router v6: https://github.com/grafana/grafana-plugins-platform-team/issues/85
```

**Comment by GrafanaWriter** [comment]
@josmperez - FYI

**Comment by leventebalogh** [comment]
I think the goal of this issue has been reached (what's left is mostly tracking how internal app plugins migrate and to help with the migration of Grafana core if necessary). I am closing this issue, please reopen if you disagree.
