### ISSUE TITLE
DashboardLoader: Features parity for Scenes

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#69072]
This epic collects high-level areas to be addressed in order to run the current dashboard model as a scene.

We have started some work around running dashboards using Scenes. The support is provided via https://github.com/grafana/grafana/blob/main/public/app/features/scenes/dashboard/DashboardsLoader.ts class.

```[tasklist]
### Tasks
- [ ] Add migration for Dashboard time options
- [ ] Add migration for Dashboard links
- [ ] Add support for inspecting a panel
- [ ] Add support for Annotation queries
- [ ] Enable panel menu rendering on scene panels
```
