### ISSUE TITLE
Epic: Add Azure Authentication to MSSQL Datasource

### ISSUE THREAD

**Issue by baldm0mma** [grafana/grafana#69087]
### Discussed in https://github.com/grafana/grafana/discussions/69085

<div type='discussions-op-text'>

<sup>Originally posted by **baldm0mma** May 25, 2023</sup>
In late April 2023, the Azure SCOM MI team approached us to see if we could build out some enhancements to our MSSQL plugin. Currently, the plugin works well with Azure SQL Database, and any on-prem SQL services they have, but cannot connect with Azure SQL MIs. Essentially our team would need to build the Azure Authentication piece that will allow Azure SQL MI users to connect safely to their data.

Currently, the offering the Azure SCOM MI team is rolling out is not supported by our MSSQL plugin, and therefore users cannot access any of their MSSQL data; there is an Azure Authentication piece missing.</div>

### Connected issues
#29089

## Tasks
```[tasklist]
### Planning and contracting
- [x] Get solid [documentation](https://docs.google.com/document/d/1ST9Fzl033cKCnPg3NTv7JWTCW8kx82TtNW2xbs7eEOM/edit) on technical expectations
- [x] Build reference and design [documentation](https://docs.google.com/document/d/1stn7rqY6_OJy0lIA4kOnQY2CFAGbpTh1iTo4uHu6EYE/edit#heading=h.5sybau7waq2q)
- [x] Estimate development time/cost
- [x] Connect with Business and Program staff to coordinate estimates and draw up contracts
```
```[tasklist]
### Development
- [x] https://github.com/grafana/grafana/issues/70200
- [x] https://github.com/grafana/grafana/issues/70199
- [x] https://github.com/grafana/grafana/pull/69208
- [x] Create applicable unit/functional/integration tests
- [ ] https://github.com/grafana/grafana/pull/73597
```
```[tasklist]
### Testing - Code
- [x] Run applicable unit/functional/integration tests through Drone
```
```[tasklist]
### Testing - Squad Dogfooding in Azure Environments
- [ ] https://github.com/grafana/grafana/issues/71306
- [x] Azure SQL Server - Managed Identity auth
- [x] Azure SQL Server - App registration auth
- [x] Azure SQL Managed Instance - Managed Identity auth
- [x] Azure SQL Managed Instance - App registration auth
- [x] Any existing auth situations - including SOCKS proxy support from previous driver
- [x] Private endpoint scenarios
- [x] VPN/Firewall scenarios
```
```[tasklist]
### Bug fixes and correspondence with Azure team
- [ ] Assure Azure team is satisfied with product
```

**Comment by zoltanbedi** [comment]
Duplicate of #29089

**Comment by baldm0mma** [comment]
Final [draft](https://github.com/grafana/grafana/pull/73597) of PR

**Comment by baldm0mma** [comment]
I believe we have delivered as promised. The Azure SCOM team has everything they need, and any more work will probably fall to the oss-datasources squad with our assistance if needed.
