### ISSUE TITLE
Saga DS - Spacing Tokens [build]

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#69134]
**Goal**

Implement the spacing tokens defined in https://github.com/grafana/grafana/issues/68660 into the Theme object

**Tasks**

- [ ] Add the spacing tokens to the theme
- [ ] Create a way to be able to get a numeric version of the tokens and a string version that appends `px` to it
- [ ] Test these tokens in an existing component
