### ISSUE TITLE
Link component [build]

### ISSUE THREAD

**Issue by eledobleefe** [grafana/grafana#69303]
**Goal**

Create a `TextLink` component that can be used to create text links in a simple way, without the need of extra CSS or code.

**Tasks**
- [x] Use the existing [Link component](https://github.com/grafana/grafana/blob/f610e37aec9a5cb5275fd17ccfffd4a36f63f700/packages/grafana-ui/src/components/Link/Link.tsx#L4) as a basis
- [x] Should have the following props:
       · _href_: mandatory
       · _color_: optional but will be `theme.colors.text.link` by default as this is broadly used
       · _external_: optional but set to `false` as default
       · _icon_: optional. Mostly used with external links
       · _inline_: optional and default `true`. Indicates whether it is wrapped up by more text or is like a block.
       · _variant_: optional. If the users need to apply it a specific appearance will do it by setting the variant styles.
       · _weight_: optional. It will be the users the option to change the font weight.
- [x] Should turn the link underlined when on hover, as it is the common behaviour broadly found.
- [x] Create storybook story with controls.

**Comment by grafanabot** [comment]
@eledobleefe please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:
