### ISSUE TITLE
Draft: Dashboards - POC split between visualization and widget delivery plan

### ISSUE THREAD

**Issue by ivanortegaalba** [grafana/grafana#69539]
Part of: #67910 

**What do we want to prove?**
* How confusing is for the user to create the concept "Widget" in the process of creating a dashboard
  * What is the metric that will consider the experiment successful
    * The usage of adding panel with widget types doesn't drop: 
      * Add instrumentation to the current picker to know how frequent widgets are selected
* How technically hard is it to split these two journeys when creating a panel

**Questions**
* Can we split the list of panels in widgets and vizs? Do we have any reliable way of doing it nowadays?
* Can we use the current visualization picker for the PoC? Do you know if we need to do the new viz picker first?
* Do we affect the plugin catalog by separating widgets and viz?
* Are the extension points dependent on DS? Are they affected by this change?
* Do we plan to differentiate the panel when it contains a widget or viz?
* For plugin authors: Does this differentiation affects their creation experience?

**Stakeholders**
* Plugin platform: They review the community plugins. Do they know about plugin panels that have a mix between being a widget and a visualization at the same time (based on some sort of configuration)?

**Analitycs to add** (check with @thanos-karachalios)
* Add widget event 
  * Adoption
  * Session recording based on this event

**Scope**
**Widget Flow**
1. Enable "Add Widget" in the empty dashboard state
2.  When the user clicks on "Add Widget" a modal will show with the list of available widgets
3.  When the user selects a widget and enters "Edit Mode", it will see the current UI, but with the list filtered by widgets (`skipQuery=== true`)
4. The name of the tab should be changed to "Widgets"
5.  The suggestions tab will be removed from this flow, library panels are kept, but we need to check if it is possible to show only "widget" library panels
**Widget Flow Screenshots**

|Add Widget Option|Modal Widget List|Edit Widget List|
|-|-|-|
![image](https://github.com/grafana/grafana/assets/239999/67eb4f98-a5e0-4469-8629-d6d72d3be338)|![image](https://github.com/grafana/grafana/assets/239999/5dd31d10-ed33-41bf-8c9e-b7e810bfda11)|![image](https://github.com/grafana/grafana/assets/239999/98fbad29-a351-4565-bbfb-cfc645b73c7c)|

**Viz Flow**
* We keep the existing behavior: The modal with the list of datasources will be shown only when creating the first visualization
* After the first viz is created, subsequent viz should select by default the previous datasource (DS) used for that dashboard
* The tab "Visualization" should be filtering out the widgets (`skipQuery ===false`)
* Once filtered, try to not touch the default state, it is ok to select a viz type by default for now

**Notes**
* We want to reuse the existing code for this POC

**Viz Flow Screenshots**

|Add Viz First Panel|Add Viz - More than one panel - last DS used| Viz list filtered|
|-|-|-|
![image](https://github.com/grafana/grafana/assets/239999/d9b58e9b-fdeb-4de4-a8ea-f0ab83211d1e))|![image](https://github.com/grafana/grafana/assets/239999/40b1e87a-b10c-4a0a-9366-5cf519fe9771)|![image](https://github.com/grafana/grafana/assets/239999/24b82f32-46eb-4d3f-9a53-5e0a70bee561)|

```[tasklist]
### Tasks
- [x] Create feature flag
- [x] Create Widget Option on EmptyDashboard and Widget modal
- [x] Modify PanelEditor visualizations list to split between widgets and visualizations
```

**Comment by juanicabanas** [comment]
- It's possible to get the widgets list in the DashboardEmpty component, since it's in the config global object, thanks to `getAllPanelPluginMeta` method
- It's possible not to create a default panel to show the widget list. We can show a modal and once the user choose a widget, create the specific panel and enter in edit mode
