### ISSUE TITLE
Improve Alerting - OnCall Integration

### ISSUE THREAD

**Issue by konrad147** [grafana/grafana#69571]
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/67096
- [ ] https://github.com/grafana/grafana/issues/69597
- [ ] https://github.com/grafana/grafana/issues/69598
- [ ] https://github.com/grafana/grafana/issues/69599
- [ ] https://github.com/grafana/grafana/issues/69600
- [ ] https://github.com/grafana/grafana/issues/69601
- [ ] https://github.com/grafana/grafana/issues/71403
- [ ] https://github.com/grafana/grafana/issues/72811
```

**Comment by armandgrillet** [comment]
We're done with this epic despite some issues still being open.
