### ISSUE TITLE
Epic: Bundle grafana/ui in plugins

### ISSUE THREAD

**Issue by jackw** [grafana/grafana#69888]
Based on the consensus reached in the [versioning grafana ui design doc](https://docs.google.com/document/d/1j1DESyp7Mm8tpqdIRtzFrXt-gI04Iz_tY4xl6rrTvb4/edit#heading=h.ve4du26wqsib) this issue is a placeholder for researching what is necessary to bundle grafana/ui in plugins.

```[tasklist]
### Tasks
- [ ] How to solve the theme context? Should it live in grafana/data or core? (https://github.com/grafana/grafana/pull/75108)
- [ ] How to solve icon bundling? Can we move the cache to core? (https://github.com/grafana/grafana/pull/74922)
- [ ] How will Monaco Editor behave when bundling grafana/ui?
- [ ] Can we move moment/time-zone out of grafana/ui?
- [ ] How do we update create-plugin webpack config?
- [ ] What does the roll out plan look like?
```

**Comment by grafanabot** [comment]
@jackw please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:
