### ISSUE TITLE
Grafana Toolkit: Deprecate package on NPM registry and remove

### ISSUE THREAD

**Issue by jackw** [grafana/grafana#70042]
With Grafana 10 released we should now be able to go ahead and deprecate it on the NPM registry and remove the package from the Grafana codebase.

Things to watch out for:
- Release process 

```[tasklist]
### ToDos
- [ ] https://github.com/grafana/grafana/issues/73105
- [x] Delete the package from the grafana/grafana repo
- [x] Deprecate it on NPM https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions
- [x] Remove from Licensing https://github.com/grafana/grafana/blob/5d8e6aa162d83614055f46bebd4fdbe9f0260bce/LICENSING.md?plain=1#L16
- [x] Remove from codeowners https://github.com/grafana/grafana/blob/5d8e6aa162d83614055f46bebd4fdbe9f0260bce/.github/CODEOWNERS#L308
- [ ] https://github.com/grafana/grafana/issues/73681
- [x] Make sure we don't mention toolkit in the current latest documentation
```
