### ISSUE TITLE
BI App: Alpha Version availability

### ISSUE THREAD

**Issue by supilee** [grafana/grafana#70093]
```[tasklist]
### Tasks
- [ ] Roadmap planning and breakdown
- [ ] Development
- [ ] Bug Bash and Dogfooding
- [ ] Go/No-Go decision and documented
```
