### ISSUE TITLE
BI App: Refactoring and future-proofing codebase

### ISSUE THREAD

**Issue by mdvictor** [grafana/grafana#70428]
The BI App is in a Hackathon state and could use some polishing. We need to:

- [ ] [Go through the codebase and clean up unused/redundant components + refactor the main app page](https://github.com/grafana/grafana/issues/70429)
- [ ] [Refactor transformations to be used in a more general way](https://github.com/grafana/grafana/issues/70430)
- [ ] [Refactor drag and drop components](https://github.com/grafana/grafana/issues/70431)
