### ISSUE TITLE
SQL data sources: Add analytics

### ISSUE THREAD

**Issue by zoltanbedi** [grafana/grafana#70422]
```[tasklist]
### Tasks
- [ ] Add UI tracking for MSSQL
- [ ] Add query execution metrics for MSSQL
- [ ] Create a dashboard for MSSQL tracking
- [ ] Add UI tracking for MySQL
- [ ] Add query execution metrics for MySQL
- [ ] Create a dashboard for MySQL tracking
- [ ] Add UI tracking for Postgres
- [ ] Add query execution metrics for Postgres
- [ ] Create a dashboard for Postgres tracking
```

**Comment by zoltanbedi** [comment]
Closing in favor of #72895 #72896
