### ISSUE TITLE
Quality: Create test scenario list for existing BI use cases

### ISSUE THREAD

**Issue by supilee** [grafana/grafana#70727]
Combine BI test scenarios/use cases/issues from Bug Bash 10.0 together as specification for upcoming Bug Bashes
```[tasklist]
### Tasks
- [x] Collect 9.5 test scenarios
- [x] Collect 10.0 test scenarios
- [ ] Create BI test spec template
```

**Comment by supilee** [comment]
Completed - see [#70767](Bug Bash BI Test Spec Template #70767)
