### ISSUE TITLE
Bug Bash Test Spec Template (BI example)

### ISSUE THREAD

**Issue by supilee** [grafana/grafana#70767]
This is a collection of bug bash test scenarios. It contains scenarios that can be picked for any bug bash round. 
For every bash, the squad has to pick items that should be verified in the corresponding round.
NOTE: this list is a living doc since scenarios will be added when applicable.

**How to use**
1.  create an epic with the labels: type/epic , bug-bash
2. copt the  CONTENT section below to the new epic
3. change the **title** to: Bug Bash _VERSION_ BI
4. in the newly created epic, remove the test scenarios that are **NOT** being tested in the bug bash round
5. check off the items that have been tested and add the result after the item. When a test fails, add a link to the GH issue.  If no issues exists yet, please create one first.

**Passed/Fail Example:**
- [ ] [Datagrid: Select all and delete rows does not delete all at once #66225](https://github.com/grafana/grafana/issues/66225) - PASSED
- [ ] [Datagrid: Column width changes when drag and dropping the column #66229](https://github.com/grafana/grafana/issues/66229) - FAILED

----------- CONTENT------------
**Test Environment Information**
Release:
Test Environment:
Browser and browser version:

**Mandatory for NEW features or enhancements**
- [ ] Develop new technical documentation (resource: Grafana [Writers' Toolkit](https://grafana.com/docs/writers-toolkit/))
- [ ] Review existing technical documentation for feature enhancement
- [ ] Audit existing technical documentation for technical accuracy

**Test scenarios:**
- [ ] [Datagrid: Select all and delete rows does not delete all at once #66225](https://github.com/grafana/grafana/issues/66225)
- [ ] [Datagrid: Bar chart is not immediately updating when entering a numerical value in grid #66226](https://github.com/grafana/grafana/issues/66226)
- [ ] [Datagrid: Column width changes when drag and dropping the column #66229](https://github.com/grafana/grafana/issues/66229)
- [ ] [Datagrid Feature Request: Add the option to rename the column header #66227](https://github.com/grafana/grafana/issues/66227)
- [ ] [Datagrid: Deleted column reappears after leaving editing mode #66232](https://github.com/grafana/grafana/issues/66232)
- [ ] [Datagrid: Add column btn on hover styling issue #67365](https://github.com/grafana/grafana/issues/67365)

**Issues found:**

**Go/No-Go (if applicable):**

**Comment by grafanabot** [comment]
@supilee please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:

**Comment by supilee** [comment]
Empty template can be found [here](https://github.com/orgs/grafana/projects/448/views/1?pane=issue&itemId=33032773).
Example can be found [here](https://github.com/orgs/grafana/projects/448/views/1?pane=issue&itemId=32804916)
