### ISSUE TITLE
Epic: XY Chart GA

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#70780]
Previous epic: https://github.com/grafana/grafana/issues/61734

### Tasks
- [x] https://github.com/grafana/grafana/issues/80653
- [x] https://github.com/grafana/grafana/issues/80652
- [x] https://github.com/grafana/grafana/discussions/70224
- [x] https://github.com/grafana/grafana/issues/78497
- [x] #70915
- [x] https://github.com/grafana/grafana/issues/64463
- [x] https://github.com/grafana/grafana/issues/80651
- [x] https://github.com/grafana/grafana/issues/80648
- [x] https://github.com/grafana/grafana/issues/70325
- [x] https://github.com/grafana/grafana/issues/70920
- [x] https://github.com/grafana/grafana/issues/70560
- [x] https://github.com/grafana/grafana/pull/67878
- [x] https://github.com/grafana/grafana/issues/70223 + https://github.com/grafana/grafana/pull/70225
- [x] https://github.com/grafana/grafana/pull/71168
- [x] https://github.com/grafana/grafana/issues/71317

### Later
- [ ] https://github.com/grafana/grafana/issues/82209
- [x] https://github.com/grafana/grafana/issues/49763
- [ ] https://github.com/grafana/grafana/issues/57222
- [x] https://github.com/grafana/grafana/pull/70407
- [ ] https://github.com/grafana/grafana/issues/81608
- [x] https://github.com/grafana/grafana/issues/59037
- [x] https://github.com/grafana/grafana/issues/45810
