### ISSUE TITLE
Dashboard: Remove `newPanelChromeUI` feature flag

### ISSUE THREAD

**Issue by axelavargas** [grafana/grafana#70790]
In Grafana, we've rolled out a new panel header for our panels. Initially, these changes were behind the `newPanelChromeUI` feature flag. However, following substantial discussion and positive feedback, we've decided it's time to remove the feature flag and make this new panel header available to all Grafana users.

```[tasklist]
### Tasks
- [x] Remove old code that the old panel header was using
- [x] Update e2e and unit tests as needed
- [x] Ensure this change is introduced in a major or minor version
```

```[tasklist]
### Leftover tasks
- [ ] Remove not used anymore `ErrorIndicator` from grafana/ui
- [ ] Remove `loadingBar()` e2e-selector if not used
- [ ] Refactor the `PanelEditorTableView` component to utilize the new properties of `PanelChrome`
```

```[tasklist]
### Testing tasks
- [ ] Add e2e test: interacting with panel menu
- [ ] Add e2e test: interacting with panel header links, description, time range
- [ ] Add e2e test: interacting with panel error
- [ ] Add e2e test: interacting with panel drag-n-drop with and without header
- [ ] Add e2e test: interacting with panel notices (graphite DS)
- [ ] Add e2e test: interacting with panel streaming data
- [ ] Add e2e test: interacting with panel hovering header
```
