### ISSUE TITLE
Epic: Data Export

### ISSUE THREAD

**Issue by supilee** [grafana/grafana#70868]
**Why do we need this** 
As of now, exporting data is hidden behind a menu structure that is not easily to find for users. 
The Data Export functionality shall bring a more straightforward and easy to find method of exporting which would be focused on panels and not on dashboards. 

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/71313
- [ ] Support for all panel types
- [x] Support for all basic image types (PNG, JPEG, BMP)
- [x] CSV, XLS, and Numbers files
- [x] JSON files (Panel JSON, Panel Data, DataFrame JSON)
- [ ] https://github.com/grafana/grafana/issues/25138
```

**Comment by mdvictor** [comment]
Update on progress regarding this:

- Removed `Multiple panel exports` for now.
- The UI will be moved into the `Share Panel` section.
- Need to look into geomap support, although image support might not be possible.
- Custom format is still WIP

**Comment by codeincarnate** [comment]
Closing this as it's more or less completed
