### ISSUE TITLE
Docs: Template Variables guide and advanced examples for plugins

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#70943]
**Why?**

We need better documentation on how to use template variables in plugins as this is an area where we get a lot of questions and very few expertise in our squad.

**How?**
We already have initial docs [here](https://grafana.com/docs/grafana/latest/developers/plugins/add-support-for-variables/) 
and we have our community post with more advanced use cases [here](https://community.grafana.com/t/how-to-use-template-variables-in-your-data-source/63250)

```[tasklist]
### Tasks
- [x] Start by merging the content of what we have in our forum  into the docs
- [ ] Add "How to interpolate variable named X into a query value named Y (with different name)"
- [ ] Add "How to inject the variable label in query editor input fields"
- [ ] Add more as you see fit / check out other requests we got over time
```

**Comment by josmperez** [comment]
Need developer review of new/revised content for task 1, above.

Need a response to https://community.grafana.com/t/using-the-value-of-a-variable-in-the-name-of-another-variable/15236 to add to this topic (to complete task 2, above)

Need "how to inject the variable label in query editor input fields" to complete task 3, above.

**Comment by josmperez** [comment]
hi, I'm still looking for a developer to review this PR and draft some text in response to tasks 2 and 3 above. Do either or both of you have time to write something up?

**Comment by josmperez** [comment]
Now in "Ideation" in Plugins Platform, moving to "Needs research" in Docs.
