### ISSUE TITLE
[Epic] Internationalization (i18n) - strings to mark up

### ISSUE THREAD

**Issue by zsofiakm** [grafana/grafana#70957]
As part of our ongoing efforts to improve the internationalization (i18n) of Grafana, we are inviting all community members to contribute to marking up hard-coded strings in Grafana OSS. The Grafana team will be taking these strings and get them translated to our supported languages (Spanish, French, German, Simplified Chinese).

We have a guide on how to mark up strings for internationalization. You can find it here: [Internationalization Guide](https://github.com/grafana/grafana/blob/813ebf988d354bf23e981e00c9c8458995774c21/contribute/internationalization.md)

Please remember to follow the guide closely when marking up strings. This will ensure consistency across the codebase and make the translation process smoother.

Thank you for your help in improving Grafana.

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/73614
- [ ] https://github.com/grafana/grafana/issues/73619
- [ ] https://github.com/grafana/grafana/issues/73979
- [ ] https://github.com/grafana/grafana/issues/74365
- [ ] https://github.com/grafana/grafana/issues/74366
- [ ] https://github.com/grafana/grafana/issues/75533
- [ ] https://github.com/grafana/grafana/issues/75532
- [ ] https://github.com/grafana/grafana/issues/75531
- [ ] https://github.com/grafana/grafana/issues/75530
- [ ] https://github.com/grafana/grafana/issues/75529
- [ ] https://github.com/grafana/grafana/issues/75534
- [ ] https://github.com/grafana/grafana/issues/75536
- [ ] https://github.com/grafana/grafana/issues/77686
```

**Comment by ashharrison90** [comment]
we've been tackling this as part of https://github.com/grafana/grafana/issues/98962, closing so we don't have duplicate epics to track
