### ISSUE TITLE
Explore: Content Outline

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#71088]
Needs proper grooming

Implement what described in https://github.com/grafana/grafana/issues/65594
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/73691
- [ ] https://github.com/grafana/grafana/issues/73826
- [x] Determine Icon for Flame Graph
- [x] Determine Icon for Custom Panel
- [ ] https://github.com/grafana/grafana/issues/74363
- [ ] https://github.com/grafana/grafana/issues/76462
```

**Comment by harisrozajac** [comment]
### Scrolling to the panel - how to set up references

1.  My current solution is to add scrollRef prop to PanelChrome because all panels except Flame Graph panel are wrapped in PanelChrome. 

2. Another option would be add scrollRef prop to each panel container. 

- [ ] Determine what should scrollRef id format look like
It should probably use the pane id + the name of the panel.

**Comment by ifrost** [comment]
> Scrolling to the panel - how to set up references

Just an idea, but I was wondering if the API could work like this. Let's say I have components:

```js
<Content>
  <Container>
    <VisualizationFoo/>
    <VisualizationBar/>
  </Container>
  <Container>
    <VisualizationXyzzy/>
  </Container>
</Content>
```

And to build the outline I can use `<ContentOutline/>` component for the main outline toolbar and just wrap any component with `<ContentOutlineItem/>` HOC to register it inside the outline. As the outline and components might be in different parts of the tree everything could be wrapped inside `<ContentOutlineContext/>`, e.g:

```js
<Content>
  <Container>
    <ContentOutlineContextProvider>

      <ContentOutline/>

      <ContentOutlineItem title="foo" icon="foo">
        <VisualizationFoo/>
      </ContentOutlineItem>

      <ContentOutlineItem title="bar" icon="bar">
        <VisualizationBar/>
      </ContentOutlineItem>

    </ContentOutlineContextProvider>
  </Container>
  <Container>
    <ContentOutlineContextProvider>

      <ContentOutline/>

      <ContentOutlineItem title="xyzzy" icon="xyzzy">
        <VisualizationXyzzy/>
      </ContentOutlineItem>

    </ContentOutlineContextProvider>
  </Container>
</Content>
```

`ContentOutlineContext` could provide API to register/unregister an item in the outline:

pseudo-code:

```jsx
function ContentOutlineItem(children) {
  const { register, unregister } = useContentOutlineContext();
  const ref = useRef(null);
  useEffect(() => {
    const id = register(...);
    return () => unregister(id);
  }, [ref]);

  return <div ref={ref}>{children}</div>
}
```

**Comment by harisrozajac** [comment]
@ifrost I like this approach! It's a cleaner and more maintainable way to solve the problem of setting up references.
