### ISSUE TITLE
BI Bug Bash Scenario Collection

### ISSUE THREAD

**Issue by supilee** [grafana/grafana#71401]
Please add links to issues with fixes that should be verifies here. Those will then be test scenarios that can be picked for coming bug bashes. 

**Test scenarios:**
- [ ] [Datagrid: Select all and delete rows does not delete all at once #66225](https://github.com/grafana/grafana/issues/66225)
- [ ] [Datagrid: Bar chart is not immediately updating when entering a numerical value in grid #66226](https://github.com/grafana/grafana/issues/66226)
- [ ] [Datagrid: Column width changes when drag and dropping the column #66229](https://github.com/grafana/grafana/issues/66229)
- [ ] [Datagrid Feature Request: Add the option to rename the column header #66227](https://github.com/grafana/grafana/issues/66227)
- [ ] [Datagrid: Deleted column reappears after leaving editing mode #66232](https://github.com/grafana/grafana/issues/66232)
- [ ] [Datagrid: Add column btn on hover styling issue #67365](https://github.com/grafana/grafana/issues/67365)
