### ISSUE TITLE
feat: warn users when a plugin is deprecated

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/grafana#71528]
Plugins may be deprecated for a number of reasons:
- no longer maintained
- no longer valid (i.e. backing service is EOL)
- commercial agreements expire
- plugin is superseded by a replacement

Deprecated plugins no longer appear in the catalog for new users to install them, however there are no changes for existing installations. This prevents dashboards suddenly breaking for users and is a non-disruptive approach we have no intention of changing. 

However, given deprecated plugins cannot be updated to new versions, they are effectively stale and may include security vulnerabilities or stop working with newer versions of the services they interact with (including Grafana).

Within the Grafana UI, we want to provide a warning to users to help them understand when they are using a deprecated plugin.

```[tasklist]
### MVP
- [x] When a user navigates to the plugin catalog and views installed plugins, a deprecated plugin should have a warning icon (yellow triangle, exclamation mark) with the title "Deprecated" and the tooltip text "This plugin is deprecated and no longer receives updates." (https://github.com/grafana/grafana/pull/74598)
- [ ] https://github.com/grafana/grafana/issues/74515
- [x] Review the impact of a plugin which has Angular warnings and is deprecated. If necessary, the deprecated warning icons/messages should replace Angular warnings.
- [ ] https://github.com/grafana/grafana-com/issues/7631
```

```[tasklist]
### Next
- [ ] https://github.com/grafana/grafana/issues/74723
- [ ] When a user navigates to a dashboard which is using a deprecated plugin, display a warning icon in the appropriate panel.
- [ ] Provide the ability to determine which dashboards are reliant on a given plugin - possibly reusing parts of the approach in https://github.com/grafana/detect-angular-dashboards
- [ ] Create documentation on the detection of dashboards which are reliant on a given plugin.
- [ ] Provide link to detecting dashboard documentation within deprecation warning messages
- [ ] When a user navigates to a dashboard which is using a deprecated plugin and edits the panel, display a warning message similar to angular, with the title "Deprecated plugin" and body "This plugin is deprecated. More information: {deprecation_context}".
- [ ] https://github.com/grafana/website/issues/16979
```

**Examples of Angular Warnings for inspiration**
Plugin catalog:
<img width="792" alt="Screenshot 2023-08-23 at 16 54 45" src="https://github.com/grafana/grafana/assets/19860021/98c9432b-86ea-4c93-8dcb-f862092377ed">

Plugin detail page:
<img width="1218" alt="Screenshot 2023-08-23 at 16 54 15" src="https://github.com/grafana/grafana/assets/19860021/109685c1-1da9-4b62-a116-62d0a5b1b83b">

Panel edit page:
<img width="398" alt="Screenshot 2023-08-23 at 16 56 47" src="https://github.com/grafana/grafana/assets/19860021/5af614c5-1bab-4bcb-b997-66c3a3192fd4">

Dashboard alerts - see https://github.com/grafana/grafana/pull/70951 for examples

**Follow up**
This solution would not solve for the following scenario:
- PluginX has v1 which contains a critical vulnerability which is patched in v2, and the user has v1 installed currently.

In this scenario we may remove v1 from the catalog, which from a user perspective likely has the same impact as deprecation. Deprecation on a version basis _could_ be an option here but would then require further conditional logic to still enable updates.

**Things to consider**
- When adding new fields / changing anything around gcom api - we have to make sure we are not stepping on the toes of this project https://github.com/grafana/grafana-plugins-platform-team/issues/19

**Comment by tolzhabayev** [comment]
Closing as most of the work and the rest will be moved to https://github.com/grafana/grafana-community-team/issues/236
