### ISSUE TITLE
Logs: Infinite scroll in the logs visualization

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#71728]
Infinite scrolling has been implemented Logs Context in https://github.com/grafana/grafana/pull/69459. Now we should look into the possibility of implementing it in the logs panel itself.

In order to do that, we need to address some challenges and limitations, such as:

## Explore

- Logs datasources often have a "max lines" setting which should be respected, and sometimes has a hard limit (e.g. 5000 lines for Loki).
- Time range selection:
  - Can it be ignored? Should it be updated?
  - If it needs to be updated, how do we prevent Explore's default behavior of re-running the request?
- Explore support to append new "pages" of logs to the current result.

## Dashboards and app plugins

Both dashboards and app plugins make use of the Logs panel, so we need to evaluate if we want to support the feature there, and how would it integrate with each context where it's used.

---

This is the continuation https://github.com/grafana/grafana/issues/67625)

```[tasklist]
### Tasks
- [x] Propose and discuss POC
- [x] Add feature flag
- [x] Implement in Explore
- [x] Implement in Dashboards
- [x] Add coverage to the new `runLoadMoreQueries` action
- [ ] https://github.com/grafana/grafana/issues/92881
- [x] Scrolling with "oldest first"
- [x] Check nano second precision
- [x] Consider lowering the default line limit (from 1000 to maybe 500)
- [x] Check top scroll
- [x] Duplicated results for newer logs
- [x] Check permalinking
- [x] Grab loader from Logs Context
- [x] Add X-Query-Tag header
- [x] Logs volume after scrolling
```

Relevant comments for context:

https://github.com/grafana/grafana/pull/76348#pullrequestreview-1809519708

https://github.com/grafana/grafana/pull/76348#pullrequestreview-1812788073

**Comment by Pexers** [comment]
+1 👍 
Excited to have infinite log scrolling within panels!

**Comment by Daniel-Ebert** [comment]
Hi, thank you all for you great work on the implementation :) Can I already enable this in my self-hosted-instance with Grafana v11 ?

**Comment by matyax** [comment]
@Daniel-Ebert Absoltely! To use it, you need to enable a feature flag called logsInfiniteScrolling.

Docs for feature toggles: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/feature-toggles/

**Comment by matyax** [comment]
@Daniel-Ebert Absolutely! But only for Explore for now. To use it, you need to enable a feature flag called logsInfiniteScrolling.

Docs for feature toggles: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/feature-toggles/

**Comment by Daniel-Ebert** [comment]
Ah great, thank you for your quick answer :) Just tested it and works fine for me! Any estimation already when this will be able in the log panels ? :)

**Comment by matyax** [comment]
Hi @girishr-github . It's not likely to be implemented in the short term, but we have it in our radar.

**Comment by matyax** [comment]
@girishr-github  and others, if all goes well, https://github.com/grafana/grafana/pull/97095 should enable infinite scrolling in dashboards, when the option inside the panel is enabled. Please keep in mind that this is an experimental feature there, and it will not be compatible with transformations.

**Comment by matyax** [comment]
This can be closed, as infinite scrolling is available in Explore, Explore Logs, and Dashboards. For dashboard users, remember it's an opt-in feature in the panel options:

![Image](https://github.com/user-attachments/assets/c1fdb3ff-23c8-42ed-9703-5f57b3ed063a)
