### ISSUE TITLE
Dashboard: Create POC for creating a panel progressively

### ISSUE THREAD

**Issue by axelavargas** [grafana/grafana#71768]
Part of #67902

### Requirements & Caveats
The goal is to prove how hard it is to stop showing a default widget with everything setup. Instead, we will deliver the panel UI in steps so the users can learn how to do it.

- When creating a panel, there is no default panel created, instead, we have everything blank, but with the DS open by default with the default DS selected.
- When selecting the DS or closing the modal, we have the Query editor rendered, for the selected DS. But there is not visualization set just an empty space waiting for the first query to be triggered
- When triggering the first query, the "raw table" visualization appears, with the queried data. But also the widget selector opens with the suggestions selected (Verify with @Ijin08)
- When the user selects a visualization type, we consider the panel completed and display all the viz options to be edited.
```[tasklist]
### Tasks
- [ ] Assess the complexity of removing the default state of a panel and panel edit view when creating and leaving everything blank
- [ ] How hard is it to not allow the user to save the panel if it is incomplete (viz + DS selected)
- [ ] Put everything under a FF and enable it for X% of users to get metrics (Rudderstack + FullStory)
```
