### ISSUE TITLE
Tooltip: Refinements p2

### ISSUE THREAD

**Issue by adela-almasan** [grafana/grafana#71900]
```[tasklist]
### TODO
- [x] Trend: Fix Single mode issue
- [x] Heatmap: Bring back Legend functionality https://github.com/grafana/grafana/pull/75712/commits/d16641086c368a115604aa172b1f83cad8e75842
- [x] Heatmap: Add feature flag to new options
- [x] XY Chart: Remove `All` from Tooltip Mode
- [x] Status history: FIx Mode
- [x] Status history: Remove `overflow: hidden`
- [x] UX discussion: XY & Status history color in header
- [x] Status History: Add `newVizTooltips` feature flag
- [x] Status History: Rearrange display data (time in header, the rest on second row)
- [ ] https://github.com/grafana/grafana/pull/77831
```

```[tasklist]
### For later
- [ ] State timeline: Add `All` mode
- [ ] XY Chart: Investigate color (header/value)
- [ ] Investigate: Better mark for the anchoring point
- [ ] Add padding between crosshair and tooltip
```
