### ISSUE TITLE
Q3 🪵 goals

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#72002]
### What was done

- [x] `feature` Add support to know which query produced which log line to enable new capabilities such as effectively show the active state of filters in the query through the magnifying glass icons in log details._
- [x] `app plugins` #75866
- [x] Create an inventory of internally made app plugins, check which use our components (logs panel) or data sources (Loki and Elasticsearch) @ivanahuckova https://docs.google.com/document/d/1sRqwU4hpGs3rcbTV4_tEk0vjRvCU0vCZuBRKtrSEQis/edit#heading=h.1w757wdidxxv
- [x]  `devops` Loki: Create SLOs, dashboards and alerts #71454 @svennergr 
- [x] `devops` Loki: Further instrument owned code with metrics and logs https://github.com/grafana/grafana/issues/71454 @svennergr 
- [x] `devops` Elasticsearch: Create SLOs, dashboards and alerts https://github.com/grafana/grafana/issues/72630  @ivanahuckova 
- [x] `devops` Elasticsearch: Further instrument owned code with metrics and logs  https://github.com/grafana/grafana/issues/72630  @ivanahuckova 
- [x] `feature` Table formatted logs https://github.com/grafana/grafana/issues/71461 @gtk-grafana 
_Users have been asking for this for a long time. We have an initial version behind feature flag, needs more polish. May be more important now with OpenTelemetry generating lots of labels. Work on showing/hiding columns. Needs infinite scroll if pagination is removed._

### Not done, bringing/considering in Q4

- [ ]  `feature` [Easier search and filter: support to match log lines with queries](https://github.com/grafana/grafana/issues/76129). @matyax  
_By having support for matching log lines with queries, we can fully support the extended behavior of the 🔍  filters in Log Details, to add and remove filter from the appropriate queries_.
- [ ]  `feature` Infinite scroll for logs https://github.com/grafana/grafana/issues/71728 @matyax  
_Pagination in logs currently is inadequate, other tools support infinite-scroll, which is easier to use, more intuitive. Make sure app-plugins can use this too. We have this running in logs-context already._
- [ ] `app plugins` Loki: Improve the API of the data source plugin https://github.com/grafana/grafana/issues/77356
- [ ] `devops` Loki: Convert to external plugins https://github.com/grafana/grafana/issues/72631 @gtk-grafana point of contact to see when we can pick this up 
  - [ ] Check if the app-plugin that use loki datasource use-case can still work with loki as external-datasource
- [ ] `devops` Elasticsearch: Convert to external plugin as test-run to identify problems https://github.com/grafana/grafana/issues/72632 @gtk-grafana point of contact to see when we can pick this up 
- [ ] `ux` Logs: "Feedback/why are you using logs explore" button in Explore
- [ ] `ux` Logs: New logs explore concept https://github.com/grafana/grafana/issues/70002
- [ ] `ux` Loki: Move the "show logs"  button in Log browser https://github.com/grafana/grafana/issues/71747
- [ ] `ux` Loki: Create and test new UI concept for Log browser https://github.com/grafana/grafana/issues/72635

### Not considered for Q4 anymore
- [ ] `devops` Loki: Audit for sources of cascading failure to instead fail fast/predictably 
_for example, if the received loki-data is too large, it may be OK for the loki plugin to just return an error saying “data was too large”_
- [ ] `devops` Elasticsearch: Audit for sources of cascading failure to instead fail fast/predictably 
_for example, if the received es-data is too large, it may be OK for the loki plugin to just return an error saying “data was too large”_
- [ ] `tech` Loki: Dataplane migration https://github.com/grafana/grafana/issues/72320
- [ ] `devops` Logs panel: Create SLOs, dashboards, alerts and further instrument owned code with metrics and logs
- [ ] `devops` Logs panel: Convert to external plugin as test-run to identify problems
- [ ] `devops` Logs panel: Audit for sources of cascading failure to instead fail fast/predictably
- [ ]  `ai` Copilot for Loki queries (ML/AI)
- [ ] `ux` Logs: Easier search and filter
- [ ] `ux` UX: Fullstory evaluation
- [ ] `ux` Loki: Predefined operations review feature toggle with customers and gather feedback] 
- [ ] `ux` Loki: How UX can help us mitigate bumpy experience with Logs volume https://github.com/grafana/grafana/issues/68956 

## References

- [Brainstorming doc](https://docs.google.com/document/d/1q2kHxZx5iTPbNBywwpnAnsjgYoWnXjPFfrSPtiP8d0o/edit)
- [Instrumentation best practices](https://github.com/grafana/grafana/blob/main/contribute/backend/instrumentation.md)
