### ISSUE TITLE
Layout component(s) [build]

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#72088]
**Goal**
Create several layout components that can be used across Grafana.

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/73469
- [ ] https://github.com/grafana/grafana/pull/73226
- [ ] https://github.com/grafana/grafana/issues/73468
- [ ] https://github.com/grafana/grafana/issues/73467
- [ ] Gather feedback from broader Frontend team about which ones are valuable
- [ ] Move the valuable ones from `unstable` into core grafana/ui and delete the rest
```

This is the [exploration](https://docs.google.com/spreadsheets/d/1rZVJrs9x7WIyd3RSrK-Z6i_knXweeYuzZx3DDueKpHA/edit#gid=0) for these components with several examples of how other design systems do it.

**Comment by staton-hyse11** [comment]
I have created a folder on Saga to house the documentation for these primitive components and have linked the PR to this issue 👍
