### ISSUE TITLE
Alerting provisioning improvements

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#72135]
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/62904
- [ ] https://github.com/grafana/grafana/issues/72810
- [ ] https://github.com/grafana/terraform-provider-grafana/pull/1060
- [ ] https://github.com/grafana/terraform-provider-grafana/pull/1083
```

Related issues:
- https://github.com/grafana/support-escalations/issues/6062
```[tasklist]
### UI Tasks
- [x] Add export to JSON
- [ ] https://github.com/grafana/grafana/issues/74656
- [ ] https://github.com/grafana/grafana/issues/74521
- [ ] https://github.com/grafana/grafana/pull/75114
- [ ] https://github.com/grafana/grafana/issues/76014
- [ ] Export button foMute Timings
- [ ] https://github.com/grafana/grafana/pull/76954
```

```[tasklist]
### Backend tasks
- [ ] https://github.com/grafana/grafana/pull/73166
- [ ] https://github.com/grafana/grafana/pull/74423
- [ ] https://github.com/grafana/grafana/pull/74625
- [ ] https://github.com/grafana/grafana/pull/75322
- [ ] https://github.com/grafana/grafana/pull/75849
- [ ] https://github.com/grafana/grafana/pull/76082
- [ ] Export of mute timings
```

```[tasklist]
### Lowest priority
```
