### ISSUE TITLE
InfluxDB: SQL Support

### ISSUE THREAD

**Issue by itsmylife** [grafana/grafana#72169]
We have an initial implementation of [SQL support for InfluxDB](https://www.influxdata.com/blog/introducing-influxdb-3-0/):
- https://github.com/grafana/grafana/pull/72167
- https://github.com/grafana/grafana/pull/72168

We will track the rest of the progress with this Epic

Improvements in SQL Support

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/77758
- [x] InfluxDB SQL: Add annotation editor
- [ ] InfluxDB SQL: Development environment with `make devenv sources=influxdbsql`
- [ ] https://github.com/grafana/grafana/issues/79590
- [x] InfluxDB SQL Bug: Fix code/builder toggle position on sql editor
- [ ] https://github.com/grafana/grafana/issues/75754
- [x] InfluxDB SQL: Backend should accept $__timeRange, $__column, … audit all backend variable interpolations
- [ ] https://github.com/grafana/grafana/issues/74987
- [x] InfluxDB SQL: Group by queries need a double check
- [x] InfluxDB SQL: Ad-hoc filters
- [ ] https://github.com/grafana/grafana/issues/75442
- [x] InfluxDB SQL: Updating the query doesn't reflect in URL
- [ ] https://github.com/grafana/grafana/issues/75951
- [ ] https://github.com/grafana/grafana/issues/78552
```

**Comment by itsmylife** [comment]
With this last piece (https://github.com/grafana/grafana/pull/79474) merged I am marking this epic as done. The rest of the tasks and issues will be tracked separately.
