### ISSUE TITLE
Bug bash 10.1 - Dashboards

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#72349]
**Test Environment Information**
Release: 10.1
Test Environment: https://testymctestface.grafana-dev.net
Browser and browser version: 114.0.5735.198 (Official Build) (arm64)

**Mandatory for NEW features or enhancements**
- [ ] Develop new technical documentation (resource: Grafana [Writers' Toolkit](https://grafana.com/docs/writers-toolkit/))
- [ ] Review existing technical documentation for feature enhancement
- [ ] Audit existing technical documentation for technical accuracy

**Test scenarios:**
- [ ] https://github.com/grafana/grafana/pull/70850 -- @axelavargas 
- [x] https://github.com/grafana/grafana/issues/69109
- [ ] #70609 
- [ ] https://github.com/grafana/grafana/issues/64319

**Issues found:**
- no issues found

**Go/No-Go (if applicable):**
