### ISSUE TITLE
Epic: [Navigation] Megamenu with open/closed states

### ISSUE THREAD

**Issue by zsofiakm** [grafana/grafana#72446]
As we continue to improve Grafana's usability, we've received feedback indicating that navigation between certain features has become more difficult due to the introduction of the hamburger menu and the section navigation. There is also an increased effort required to access certain features that are now placed lower in the hierarchy. To address this, we propose refining the navigation system to enhance user experience and make features easier to access.

### User Stories

1. **Persistent Navigation:** I want to have the navigation visible as I move between pages, for tasks like gathering incident data, setting up Grafana for the first time, or exploring Grafana as a new user in an existing organization. 
2. **Collapsible Navigation:** I want to be able to collapse the navigation when I'm focused on a single task, like editing a dashboard.

### Acceptance Criteria
**Functional:**

1. Open/Closed State: The navigation sidebar can be collapsed.
2. 3 Levels: Top, second and third level navigation items are accessible from the megamenu.

**Responsiveness:**

1. Viewport Adaptability: Navigation is collapsed by default on viewports narrower than 1440px (or smaller?).
2. Mobile Devices: On mobile devices (viewports narrower than 768px), when opened, navigation is full screen.

**Accessibility:**

1. Touch/Click Targets: Touch/click targets meet WCAG AA requirements ([minimum 24x24 px](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html)).
2. State Feedback: Navigation items come with hover and active states.

### UI Implications

1. Megamenu Sizing: As the megamenu will have more content than before, it needs to be compact. Current width is 350px, and proof-of-concepts suggest reducing this to 250px.
2. WCAG Compliance: Smaller nav item height while remaining WCAG AA compliant, with a minimum height of 24px.
3. Icon Selection: For desktop, select an appropriate icon for collapsing the navigation, as the current hamburger icon doesn't fit. Possible alternatives include a collapse icon or sidebar icon.

### Designs
[Figma artboards](https://www.figma.com/file/FStledDq3ytXssh4PykKf5/Combined-megamenu?type=design&node-id=648-15218&mode=design&t=o2VbXdFceTbxkrhU-0)
[Figma prototype](https://www.figma.com/proto/FStledDq3ytXssh4PykKf5/Combined-megamenu?page-id=648%3A15218&type=design&node-id=648-15642&t=o2VbXdFceTbxkrhU-0&scaling=min-zoom&starting-point-node-id=648%3A15601)

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/74916
- [ ] https://github.com/grafana/grafana/issues/74917
- [ ] https://github.com/grafana/grafana/issues/75273
- [ ] https://github.com/grafana/grafana/issues/75446
- [ ] https://github.com/grafana/grafana/issues/75725
- [ ] https://github.com/grafana/grafana/issues/75726
- [ ] https://github.com/grafana/grafana/issues/75727
- [ ] https://github.com/grafana/grafana/issues/76518
- [ ] https://github.com/grafana/grafana/issues/76519
- [ ] https://github.com/grafana/grafana/issues/77379
- [ ] https://github.com/grafana/grafana/issues/77263
- [ ] https://github.com/grafana/grafana/issues/77262
- [ ] https://github.com/grafana/grafana/issues/76520
- [ ] https://github.com/grafana/grafana/issues/81775
```

**Comment by amy-super** [comment]
Design work to be captured here: #72141

**Comment by ashharrison90** [comment]
@yaelleC i would prefer to keep it open if that's ok, then when we raise the PR to clean up the toggle we can mark it as fixing this issue. once that PR is merged this will close along with it.
