### ISSUE TITLE
Bug Bash 10.1 - Logs Squad

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#72499]
**Test Environment Information**
Release: 10.1
Test Environment: https://testymctestface.grafana-dev.net
Browser and browser version: Firefox, Chrome, Safari, latest stable version.

**Mandatory for NEW features or enhancements**
- [ ] Elastic: [Log samples](https://github.com/grafana/grafana/issues/62212) [PR from Gareth](https://github.com/grafana/grafana/pull/70258)
- [ ] Logs: [Permalink PR from Sven](https://github.com/grafana/grafana/issues/67379)
- [x] Loki: [Step option](https://github.com/grafana/grafana/issues/58337) PRs from Ivana 
- [ ] Logs: [Context infinite scrolling](https://github.com/grafana/grafana/issues/67625) [PR from Gabor](https://github.com/grafana/grafana/pull/69459) 
- [x] Loki: [Query splitting sub-request progress](https://github.com/grafana/grafana/issues/65104) [PR from Matias](https://github.com/grafana/grafana/pull/69574) 
- [x] Loki: [Query splitting on by default](https://github.com/grafana/grafana/issues/67547) [PR from Matias](https://github.com/grafana/grafana/pull/72094) 
- [ ] Logs: [Handle dataplane compliant Logs frames](https://github.com/grafana/grafana/issues/67657) [PR from Gabor](https://github.com/grafana/grafana/pull/70318) 

**Hidden befind feature toggle that defaults to false**
- [ ] Loki: [Prettify LogQL queries](https://github.com/grafana/grafana/issues/61041) [PR from Gareth](https://github.com/grafana/grafana/pull/64337)
- [ ] Logs: [Toggle behaviour for filter in/out label](https://github.com/grafana/grafana/issues/61765) [PR from Matias](https://github.com/grafana/grafana/pull/70091)

**Test scenarios:**

Doc: https://docs.google.com/document/d/1Enn7s_czE1x4cTD9odNQ1VmYZwaF8GRlS1MpD-sep3s/edit#heading=h.8snul68fykf

#### What to check

**Issues found:**
[Logs: Clicking hide this field after filtering freezes the app](https://github.com/grafana/grafana/issues/72504) - newly introduced issue
[Logs volume: Computed logs volume with multiple queries shows "Data outside time range"](https://github.com/grafana/grafana/issues/72507) - this issue is present in previous versions as well
[Logs: Filter for/out interactions are showed even if data source does not support it](https://github.com/grafana/grafana/issues/72505) - this issue is present in previous versions as well

**Go/No-Go (if applicable):** link to Go/No-Go doc

**Comment by grafanabot** [comment]
@matyax please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:
