### ISSUE TITLE
Elasticsearch: Convert to external plugin

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#72632]
The next step for the lifecycle of core plugins is externalization. For that, we need to assess the current state, dependencies, and limitations, to get an approximate estimation of the effort required and eventually address them.

```[tasklist]
### Tasks
- [ ] Identify and replace backend dependencies that cannot be kept as an external DS 
- [ ] Identify and replace frontend dependencies that cannot be kept as an external DS 
- [ ] Assess impact on app/plugin developers
- [ ] https://github.com/grafana/grafana/pull/76894
```

**Comment by aflinchb** [comment]
@matyax @ivanahuckova - Is there a plan to focus on this work? My team is currently working on an effort where we are exploring making some changes to the Elasticsearch datasource to support nested queries, but would prefer to do so in a custom plugin (vs. changes to the entire Grafana codebase).  Is my understanding correct that converting to an external plugin would allow for that capability?

**Comment by ivanahuckova** [comment]
@aflinchb we plan to focus on this in the next months, but the plan is to keep Elasticsearch in the grafana/grafana repo, but it will have its own folder.

**Comment by aangelisc** [comment]
Closing this and once we've figured out what we're doing with core data sources new issues and tasks will be created.
