### ISSUE TITLE
Loki: Convert to external plugin

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#72631]
The next step for the lifecycle of core plugins is externalization. For that, we need to assess the current state, dependencies, and limitations, to get an approximate estimation of the effort required and eventually address them.

```[tasklist]
### Tasks
- [x] Identify and replace frontend dependencies that cannot be kept as an external DS
- [ ] Identify and replace backend dependencies that cannot be kept as an external DS
- [ ] Assess impact on app/plugin developers
```

**Comment by gtk-grafana** [comment]
The metrics squad is currently undergoing this task with the Prometheus data source, and have identified a bunch of code available in core frontend that is not available to third party plugins, and they are also currently in progress creating a design doc to discuss how to allow external projects to use backend/go code. I will continue to monitor their progress and share any relevant documentation here.

**Comment by svennergr** [comment]
I don't think this is a goal anymore. Even though being core, plugins can run as separate binaries.
