### ISSUE TITLE
Epic: Change style of sharing button to make it more obvious

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#72741]
### Goal
Improve the “Share” button style to increase the adoption

### Requirements & Caveats
What are the requirements? Are there any known limitations?

```[tasklist]
### Tasks list
- [x] UX Research
- [x] Design mockups
- [ ] https://github.com/grafana/grafana/issues/77298
- [x] Feedback from the team
- [x] Testing
- [ ] https://github.com/grafana/grafana/issues/77431
```

**Comment by natydej** [comment]
In order to continue with the designs proposal, I need some metrics from the toolbar actions, issue related [here](https://github.com/grafana/grafana/issues/73610)

**Comment by natydej** [comment]
Metrics for Dashboard sharing:
https://ops.grafana-ops.net/d/e6ec0bf0-c369-414a-b99e-619c6d0efa70/dashboards-sharing?orgId=1

After sharing designs with the Squad, we decided to test this design below:
<img width="1444" alt="share-button" src="https://github.com/grafana/grafana/assets/51436795/be9d4bc5-276a-40f4-ba72-d20d80bfd583">

[Figma link](https://www.figma.com/file/rPzflElZXoRp3PAtDiYicZ/Share-dashboard?type=design&node-id=1026-3414&mode=design)

**Outcome:**

- To improve the adoption of the sharing button, we need to make this CTA primary, hence we had to change the "add button" to be secondary - in order to be consistent with our DS guidelines [here](https://internal-ops-us-east-0.grafana.net/design-system/Components/Buttons/Button)
- We decided to keep the icon as it is now, to avoid confusion with this new UI style and placement for this button.
- The placement on the top-right where other users' actions are, so it can be more visible.

**Next steps:**
Measure the visibility of this button with these changes, to compare it with what we had before and see how much we increase the adoption there.

**Comment by evictorero** [comment]
> In order to continue with the designs proposal, I need some metrics from the toolbar actions, issue related [here](https://github.com/grafana/grafana/issues/73610)

@natydej this is still valid? This Story is blocked and needs support from Eng? If that is the case we should prioritize the needed task.

**Comment by natydej** [comment]
Hey @evictorero, we can move forward on this, since I aligned with @Ijin08 toolbar's work and decided to add the "share" button on the latest design you see [here](https://www.figma.com/file/rPzflElZXoRp3PAtDiYicZ/Share-dashboard?type=design&node-id=1026-3414&mode=design) - Those metrics are important but for the toolbar buttons placement.
