### ISSUE TITLE
Add feature tracking for data sources

### ISSUE THREAD

**Issue by vickyyyyyyy** [grafana/grafana#72760]
We need to determine what features we want to track for our data sources.

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/72895
- [ ] https://github.com/grafana/grafana/issues/72896
- [ ] https://github.com/grafana/grafana/issues/72897
- [ ] https://github.com/grafana/grafana/issues/72898
- [ ] https://github.com/grafana/grafana/issues/72899
- [ ] https://github.com/grafana/grafana/issues/72900
- [ ] https://github.com/grafana/grafana/issues/72901
```
