### ISSUE TITLE
Migrate to new styling in data sources

### ISSUE THREAD

**Issue by vickyyyyyyy** [grafana/grafana#72761]
This epic consists of a few things that can be done at the same time:

- updating the configuration pages to match the [guidelines](https://docs.google.com/document/d/11XMaYHSMSra8AoN2-yVW-5QPbjEXgkAFbTIF6N84cGE/edit#heading=h.qud4at7uoleb).
- use [auth component](https://github.com/grafana/grafana-experimental/tree/main/src/ConfigEditor/Auth) in the datasource configuration pages.
- migrate legacy forms to the [new form styling](https://github.com/grafana/grafana/issues/66479).

---
**Configuration Pages:**
- [x] BigQuery - https://github.com/grafana/google-bigquery-datasource/pull/214
- [x] Postgres - https://github.com/grafana/grafana/pull/75525
- [x] MySQL - https://github.com/grafana/grafana/pull/74902
- [x] GitHub - https://github.com/grafana/github-datasource/pull/255
- [x] Google Sheets - https://github.com/grafana/google-sheets-datasource/pull/211
- [x] Zabbix - https://github.com/grafana/grafana-zabbix/pull/1725
- [x] JSON - https://github.com/grafana/grafana-json-datasource/pull/391
- [x] CSV - https://github.com/grafana/grafana-csv-datasource/pull/280

**Legacy Forms:**
- [x] BigQuery - no legacy components found
- [x] Postgres - no legacy components found
- [x] MySQL - no legacy components found
- [x] GitHub - https://github.com/grafana/github-datasource/pull/272
- [x] Google Sheets - https://github.com/grafana/google-sheets-datasource/pull/220
- [x] Zabbix - https://github.com/grafana/grafana-zabbix/pull/1743
- [x] JSON - https://github.com/grafana/grafana-json-datasource/pull/395
- [x] CSV - https://github.com/grafana/grafana-csv-datasource/pull/285
