### ISSUE TITLE
GrafanaUI: Move MatchersUI out

### ISSUE THREAD

**Issue by L-M-K-B** [grafana/grafana#72877]
MatchersUI (packages/grafana-ui/src/components/MatchersUI) is currently part of grafana-ui. The components in the folder are not exported by default so using them directly from the npm package requires the whole path and a lot of intention. That may reduce the number use cases in plugins outside of the grafana repo.
In order to find out where components from MatchersUI are used in open Github repos: https://github.com/search?q=%40grafana%2Fui%2Fsrc%2Fcomponents%2FMatchersUI&type=code

**TODO:**
- [ ] check current use cases in grafana repo
- [ ] consult with plugin platforms team about deprecation
- [ ] move MatchersUI folder out of grafana-ui (to core?) and leave a deprecation note

**Comment by L-M-K-B** [comment]
It's not exposed in the npm package. We need to find a better place for this and talk to some teams.
