### ISSUE TITLE
MySQL: Add feature tracking to datasource

### ISSUE THREAD

**Issue by gwdawson** [grafana/grafana#72896]
We need to determine what features we want to track for our data sources.

- [ ] decide what features we want to track
- [ ] implement feature tracking
- [ ] create a dashboard to view the usage
