### ISSUE TITLE
Postgres: Add feature tracking to datasource

### ISSUE THREAD

**Issue by gwdawson** [grafana/grafana#72895]
We need to determine what features we want to track for our data sources.

- [ ] decide what features we want to track
- [ ] implement feature tracking
- [ ] create a dashboard to view the usage
