### ISSUE TITLE
JSON: Add feature tracking to datasource

### ISSUE THREAD

**Issue by gwdawson** [grafana/grafana#72900]
We need to determine what features we want to track for our data sources.

- [ ] decide what features we want to track
- [ ] implement feature tracking
- [ ] create a dashboard to view the usage

**Comment by gwdawson** [comment]
completed in this pr https://github.com/grafana/grafana-json-datasource/pull/366
