### ISSUE TITLE
Epic: CanCAD

### ISSUE THREAD

**Issue by drew08t** [grafana/grafana#72959]
```[tasklist]
### Canvas
- [ ] https://github.com/grafana/grafana/issues/72936
- [ ] https://github.com/grafana/grafana/issues/72940
- [ ] https://github.com/grafana/grafana/issues/72937
- [ ] https://github.com/grafana/grafana/issues/72939
- [ ] https://github.com/grafana/grafana/issues/72941
- [ ] https://github.com/grafana/grafana/issues/72942
- [ ] https://github.com/grafana/grafana/issues/73069
```

```[tasklist]
### File Import
- [ ] https://github.com/grafana/grafana/issues/72943
- [ ] https://github.com/grafana/grafana/issues/72945
- [ ] https://github.com/grafana/grafana/issues/72948
- [ ] https://github.com/grafana/grafana/issues/72949
- [ ] https://github.com/grafana/grafana/issues/72955
- [ ] https://github.com/grafana/grafana/issues/72947
```

```[tasklist]
### Conversion
- [ ] https://github.com/grafana/grafana/issues/72957
- [ ] https://github.com/grafana/grafana/issues/72954
- [ ] https://github.com/grafana/grafana/issues/72952
- [ ] https://github.com/grafana/grafana/issues/72956
- [ ] https://github.com/grafana/grafana/issues/72958
- [ ] https://github.com/grafana/grafana/issues/73182
```

```[tasklist]
### AutoCAD
- [ ] https://github.com/grafana/grafana/issues/72950
- [ ] https://github.com/grafana/grafana/issues/72951
```

```[tasklist]
### Bugs / Clean-up / Enhancements / Dreams
- [ ] https://github.com/grafana/grafana/issues/73021
- [ ] https://github.com/grafana/grafana/issues/73066
- [ ] https://github.com/grafana/grafana/issues/73177
```
