### ISSUE TITLE
Complete implementation of the Update Feature Toggles endpoint

### ISSUE THREAD

**Issue by mmandrus** [grafana/grafana#73059]
after the phase 2 design is done, implement it in the existing endpoint
```[tasklist]
### Tasks
- [x] Create new auth scope for feature-toggles
- [x] Update GCom create method to setup the instance AP + token
- [x] Update HGAPI to propagate the token to Grafana
- [x] Create the authenticated /feature-toggles endpoint in HGAPI
- [x] Configure Grafana to use the webhook authentication
- [x] Update GCom reconcile script to generate tokens for existing stacks
- [x] Update GCom with proxy to hgapi /feature-toggles
```
