### ISSUE TITLE
EPIC: Help extracting further core plugins out of the core

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#73115]
Following up on the first part: https://github.com/grafana/grafana/issues/68973

**Why?**
Continue on our journey to extract further plugins out of the core we want to start working with further core datasources.

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana-plugin-sdk-go/issues/755
- [ ] https://github.com/grafana/grafana-plugin-sdk-go/pull/775
- [ ] https://github.com/grafana/grafana-plugin-sdk-go/pull/769
- [ ] https://github.com/grafana/grafana/pull/76816
- [ ] https://github.com/grafana/plugin-tools/issues/480
- [ ] https://github.com/grafana/grafana-plugin-examples/issues/209
- [x] Feature toggles for core plugins
- [ ] https://github.com/grafana/grafana/issues/78267
- [ ] https://github.com/grafana/grafana/issues/78268
- [x] HTTP client (provider): Provide a better out of the box experience for external plugins in regards to HTTP client middlewares
- [ ] https://github.com/grafana/grafana/issues/81452
```

**Comment by gabor** [comment]
i'm looking into interval-related complications, created two issues that describe the problems i've found: 
- https://github.com/grafana/grafana/issues/78267
- https://github.com/grafana/grafana/issues/78268
