### ISSUE TITLE
Epic: Transformation Feature Requests H2FY24

### ISSUE THREAD

**Issue by baldm0mma** [grafana/grafana#73237]
```[tasklist]
### \[Priority: high] Support for dashboard variables
- [x] [Product board](https://grafana.productboard.com/feature-board/2966034-gtm-feature-requests/features/16818823/detail)
- [x] [Zendesk Ticket 1](https://grafana.zendesk.com/agent/tickets/70828)
- [x] [Zendesk Ticket 2](https://grafana.zendesk.com/agent/tickets/84785)
- [x] [Zendesk Ticket 3](https://grafana.zendesk.com/agent/tickets/91575)
- [ ] https://github.com/grafana/grafana/issues/74478
```

```[tasklist]
### \[Priority: medium] Capitalization
- [x] [Product Board](https://grafana.productboard.com/feature-board/2966034-gtm-feature-requests/features/21030778/detail)
- [ ] https://github.com/grafana/grafana/issues/74479
```

```[tasklist]
### \[Priority: high] Cumulative total
- [x] [Product Board](https://grafana.productboard.com/feature-board/2966034-gtm-feature-requests/features/15950756/detail)
- [x] [Zendesk Ticket](https://grafana.zendesk.com/agent/tickets/96665)
- [x] [Related closed issue](https://github.com/grafana/support-escalations/issues/7139)
- [ ] https://github.com/grafana/grafana/issues/74480
```

```[tasklist]
### \[Priority: medium] Passing on calculations from transformation to transformation
- [x] [Product Board](https://grafana.productboard.com/feature-board/2966034-gtm-feature-requests/features/20274422/detail)
- [ ] https://github.com/grafana/grafana/issues/74486
```

```[tasklist]
### Sums n value of table with n-1 value of same table - DEPRIORITIZED; WORKAROUNDS EXIST
- [x] [Product Board](https://grafana.productboard.com/feature-board/2966034-gtm-feature-requests/features/21375442/detail)
- [x] [Zendesk Ticket](https://grafana.zendesk.com/agent/tickets/95938)
- [ ] https://github.com/grafana/support-escalations/issues/7139
```
```[tasklist]
### Add row index as percent to "Add field from calculation"
- [ ] https://github.com/grafana/grafana/issues/73216
```

```[tasklist]
### Build table with rows/columns based on labels - CLOSED DUE TO AGE OF TICKET AND ALREADY POSSIBLY SOLVED
- [x] [Product Board](https://grafana.productboard.com/feature-board/2966034-gtm-feature-requests/features/8636286/detail)
- [x] [Zendesk Ticket](https://grafana.zendesk.com/agent/tickets/23822)
- [ ] https://github.com/grafana/support-escalations/issues/7193
```

```[tasklist]
### Pick which field is the value, and which is the label - DEPRIORITIZED
- [x] [Product Board](https://grafana.productboard.com/feature-board/2966034-gtm-feature-requests/features/10952992/detail)
- [x] [Zendesk Ticket](https://grafana.zendesk.com/agent/tickets/36649)
- [ ] https://github.com/grafana/support-escalations/issues/7140
```

```[tasklist]
### Allow value mappings to happen before a transformation - CLOSED FOR FURTHER DISCUSSION
- [x] [Product Board](https://grafana.productboard.com/feature-board/2966034-gtm-feature-requests/features/11192524/detail)
- [x] [Zendesk Ticket](https://grafana.zendesk.com/agent/tickets/38940)
- [ ] https://github.com/grafana/support-escalations/issues/7141
```

```[tasklist]
### Support value mappings on dynamic values of other cells - DEPRIORITIZED
- [x] [Product Board](https://grafana.productboard.com/feature-board/2966034-gtm-feature-requests/features/11338833/detail)
- [ ] https://github.com/grafana/support-escalations/issues/7142
```

```[tasklist]
### Add an "All unique values" calculation in the "Group by" transformation
- [x] [Product Board](https://grafana.productboard.com/feature-board/2966034-gtm-feature-requests/features/11543755/detail)
- [x] @zsofiakm is following up with the customer.
- [ ] https://github.com/grafana/grafana/issues/74487
```

```[tasklist]
### Support for additional math operations other than binary operations - DEPRIORITIZED; WORKAROUNDS/EXPRESSIONS EXIST
- [x] [Product Board](https://grafana.productboard.com/feature-board/2966034-gtm-feature-requests/features/14338050/detail)
- [x] [Zendesk Ticket](https://grafana.zendesk.com/agent/tickets/55453)
- [ ] https://github.com/grafana/support-escalations/issues/7144
```

```[tasklist]
### Support rename by regex followed by "group by" and merge the resulting output - DEPRIORITIZED
- [x] [Product Board](https://grafana.productboard.com/feature-board/2966034-gtm-feature-requests/features/14481662/detail)
- [x] [Related Escalation](https://github.com/grafana/support-escalations/issues/3254)
- [ ] https://github.com/grafana/support-escalations/issues/7146
```

```[tasklist]
### Convert datetime into a day to group by day - COMPLETED
- [x] [Product Board](https://grafana.productboard.com/feature-board/2966034-gtm-feature-requests/features/15108631/detail)
- [ ] https://github.com/grafana/support-escalations/issues/7145
```

```[tasklist]
### Configure multiple thresholds from the "Config from Query result" transformation and config the colors for those thresholds - DEPRIORITIZED
- [x] [Product Board](https://grafana.productboard.com/feature-board/2966034-gtm-feature-requests/features/15294162/detail)
- [x] [Zendesk Ticket](https://grafana.zendesk.com/agent/tickets/60943)
- [x] [Relevant Issue 1](https://github.com/grafana/grafana/issues/45803)
- [x] [Relevant Issue 2](https://github.com/grafana/grafana/issues/37948)
- [ ] https://github.com/grafana/support-escalations/issues/7147
```

```[tasklist]
### Feed data into the "Organize Fields" transform from a dashboard variable
- [x] [Product Board](https://grafana.productboard.com/feature-board/2966034-gtm-feature-requests/features/15819890/detail)
- [x] [Possible related issue]()
- [ ] https://github.com/grafana/grafana/issues/74488
```

```[tasklist]
### Add "absolute" as a Binary transform math operator
- [x] [Product Board](https://grafana.productboard.com/feature-board/2966034-gtm-feature-requests/features/16053064/detail)
- [x] [GitHub Discussion](https://github.com/grafana/grafana/discussions/38134)
- [x] [Zendesk Ticket](https://grafana.zendesk.com/agent/tickets/65855)
- [x] [Dashboard](https://teckresources.grafana.net/d/ZuHOa74Vz/hvc-data-reporting?orgId=1&from=1666103778744&to=1666276578744)
- [ ] https://github.com/grafana/grafana/issues/74489
```

```[tasklist]
### Combine the results of two queries to build a new time series
- [ ] [Product Board](https://grafana.productboard.com/feature-board/2966034-gtm-feature-requests/features/17371837/detail)
- [ ] [Zendesk Ticket](https://grafana.zendesk.com/agent/tickets/75414)
- [ ] https://github.com/grafana/grafana/issues/74490
```

```[tasklist]
### Filter/limit Transformations automatically via series/data frame data
- [ ] https://github.com/grafana/grafana/issues/74063
```

```[tasklist]
### Add configuration error - DEPRIORITIZED DUE TO SIMILAR TO WORK BEING DONE
- [ ] #76966
```

**Comment by samjewell** [comment]
I'd like to see:
- The words "pivot table" included in the "Grouping to matrix" transform title or subtitle, so I can search "pivot table" and find it
- The word "transpose" in the "Rows to fields" transform, so I can search that term.

**Comment by samjewell** [comment]
I'd like to be able to search for the config options **within** a transform, and have that transform show up in the search results. For example, search "Binary operation" and have "Add field from calculation" show up in the results list.

**Comment by samjewell** [comment]
I'd like the "Table view" toggle to live with (ie. next-to or within, visually) the "Transforms" tab:

![image](https://github.com/grafana/grafana/assets/2903904/be638c0c-c56b-423d-a066-4f7b3990cb48)

![image](https://github.com/grafana/grafana/assets/2903904/de7f61cc-0d17-4659-8609-34e546e8e83c)

I never discovered or found out what this toggle was for until a colleague showed me. I ALWAYS use it now when writing transformations. I always use those two pieces of functionality together, and I never use either one independently.

**Comment by jennyfana** [comment]
As we have not received feedback about the possibility of using Series to Row for Transforming Time Series (Combine Results of Two Series) this Epic will be closed.  If the specific request for this Transformation reemerges we shall reconsider.

**Comment by runiq** [comment]
@natellium Could you explain a bit why you decided to close this? I was under the impression that this issue was the place to watch for variables in thresholds (IIRC, it's been a while).
