### ISSUE TITLE
Epic: Docker PR builds for external data sources

### ISSUE THREAD

**Issue by adamyeats** [grafana/grafana#73287]
```[tasklist]
### Tasks
- [x] Implement Docker PR builds in `clickhouse-datasource`
- [x] Implement Docker PR builds in `azure-data-explorer-datasource`
- [x] Implement Docker PR builds in `falconlogscale-datasource`
- [x] Implement Docker PR builds in `astradb-datasource`
- [x] Implement Docker PR builds in `sentry-datasource`
```

**Comment by adamyeats** [comment]
On hold for a couple of week while we test on `clickhouse-datasource`

**Comment by adamyeats** [comment]
Resolved.
