### ISSUE TITLE
GrafanaUI: Create `Box` component in `unstable` folder

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#73467]
Add a `Box` component to grafana/ui in the `unstable` folder so it can be used locally to gather feedback on our layout components.

For inspiration on what properties are needed here, [this spreadsheet](https://docs.google.com/spreadsheets/d/1rZVJrs9x7WIyd3RSrK-Z6i_knXweeYuzZx3DDueKpHA/edit#gid=0) has examples of how other design systems implement this.

```[tasklist]
### Tasks
- [ ] Create `Box` component
- [ ] Create story in storybook
- [ ] Write mdx docs for storybook
```
