### ISSUE TITLE
GrafanaUI: Move `Stack` component from grafana/experimental to `unstable` folder in grafana/ui

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#73469]
There is a stack component in grafana/experimental ([here](https://github.com/grafana/grafana-experimental/blob/main/src/QueryEditor/Stack.tsx)). We should move that into `grafana/ui` into the `unstable` folder so we can start using it locally and to help us get feedback on which layout components we should have.

On the migration we should make sure to use our spacing tokens for the `gap` property instead of a generic `number`.
```[tasklist]
### Tasks
- [ ] Create a story in Storybook
- [ ] Write mdx docs in Storybook
- [ ] Mark as deprecated in grafana/experimental
```

**Comment by grafanabot** [comment]
@JoaoSilvaGrafana please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:
