### ISSUE TITLE
Saga - Website Improvements

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#73499]
Website improvements to be made before Go Live:

```[tasklist]
### Tasks
- [ ] Code snippet examples
- [ ] https://github.com/grafana/grafana/issues/75435
- [ ] https://github.com/grafana/grafana/issues/75633
- [ ] https://github.com/grafana/grafana/issues/76694
- [ ] https://github.com/grafana/grafana/issues/76810
- [ ] Move Storybook to bottom of the page
- [x] Code preview "copy to clipboard" bug
- [ ] Interactive Table page rename to InteractiveTable
```

```[tasklist]
### Live Code Previews
- [ ] Add previews for Button
- [ ] Add previews for IconButton
- [x] Add previews for Alert
- [ ] Add previews for Field
- [ ] Add more previews for Input (examples on how to show invalid state with Field)
- [ ] Add previews for InteractiveTable (? if it looks good?)
- [ ] Add previews for Switch
- [ ] Add previews for TextLink
- [ ] Add previews to Text
- [ ] Add previews for TextArea
- [ ] Add previews for Toggletip
- [ ] Add previews for Tooltip
```

We should aim for comprehensive previews for each prop so users can see in-situ examples of what they look like and how to use them. Different options for the same prop, for conceptually similar props can be previewed in the same live code example. For example, the following is recommended:

```tsx
<Stack>
  <Button variant="info" />
  <Button variant="success" />
  <Button variant="error" />
</Stack>
```

or

```tsx
<Stack>
  <Input prefix={<Icon name="search" />} />
  <Input suffix={<Icon name="search" />} />
</Stack>
```

**Comment by JoaoSilvaGrafana** [comment]
See this slack [thread](https://raintank-corp.slack.com/archives/C025WTVRBSN/p1696417481982229) for some suggestions on changes including:
- Sync the styles with those of the [developer portal](https://grafana.com/developers/plugin-tools)
- Typography alignment

**Comment by Clarity-89** [comment]
> We should aim for comprehensive previews for each prop so users can see in-situ examples of what they look like and how to use them. 

I'm not sure about this, it seems like duplication of the stuff we already have in storybook and the examples for more complex components, like tables, would require a lot of code setup.
