### ISSUE TITLE
Saga - Expand A11y representation

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#73519]
For Go Live we should build out our a11y section of the site to be more representative of the work that is being done on the product and the commitment to improving it iteratively.

```[tasklist]
### Tasks
- [x] create new folder for all accessibility content
- [x] add Accessibility Statement
- [ ] add VPAT
- [x] Move style guide to it's own area and rename
```
