### ISSUE TITLE
Improve DS Metrics

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#73521]
We need to improve and simply the metrics for the design system so stakeholders can clearly see impact and progress.

**Comment by yaelleC** [comment]
Should we be writing a Design Doc on the success on the Design System? Align everybody on expectations and agree on metrics ? 
Kind of the next level from your Product DNA?

**Comment by staton-hyse11** [comment]
```[Key Results]
### Tasks
- [ ] Rollout new Figma structure plan for improved Figma component usage
- [ ] Implement CSAT on Saga V1
- [ ] Identify ways to track what FE teams are using design system components vs not 
- [ ] Track the number of contributions (eng/desg)
```
