### ISSUE TITLE
Story: Shared query & repeats: Improve docs and UI

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#73548]
Refs: 
https://github.com/grafana/grafana/issues/52930
https://github.com/grafana/grafana/issues/46361
https://github.com/grafana/grafana/discussions/38182

Repeating a row with a panel that is using a shared query is currently not supported. We need to:
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/73968
- [x] https://github.com/grafana/grafana/issues/73929
- [ ] https://github.com/grafana/grafana/issues/73930
```

**Comment by juanicabanas** [comment]
@imatwawana I just updated this to be a story with multiple issues so we can manage them.

**Comment by juanicabanas** [comment]
https://github.com/grafana/grafana/issues/73930 has to be merged once the documentation is updated

**Comment by imatwawana** [comment]
I removed https://grafana.com/docs/grafana/latest/datasources/#special-data-sources documentation from the list of docs to be updated, as it doesn't make sense to introduce the idea of repeating rows in documentation that is itself an introduction to data sources
