### ISSUE TITLE
On-call rotation in Grafana frontend

### ISSUE THREAD

**Issue by ivanortegaalba** [grafana/grafana#73853]
**Why is this needed**:
We have a responsibility to be available for incidents of serious impact to our customers and users.

* [Product DNA](https://docs.google.com/document/d/1XolbnIIFK_ZypEVspUrTIxFAaMyBP9hISeDzGMZ0-zA/edit)
* [Design doc](https://docs.google.com/document/d/1HQgd-94cQvKJ_8EUBFpeuKLrOKXNFmlwPpGUuZ5ucQ4/edit)
* [Delivery plan](https://docs.google.com/document/d/1kT6JDPx7Cu2RhSs88arTuSDDzixPhFSDdYTz4DNt-pQ/edit#heading=h.d5i3jmpwb1hp)

```[tasklist]
### Monitoring on Dashboards as the first team to be on-call
- [ ] Create synthetic checks on Dashboard pages
- [ ] Create Availability alerts on Dashboard synthetic checks
- [ ] Create a runbook with all the monitoring in place for Dashboards
- [ ] Introduce @ivanortegaalba and someone else from NASA in the on-call rotation shadowing for 2 weeks
- [ ] Introduce @ivanortegaalba and someone else from NASA in the on-call rotation for 2 weeks
```

```[tasklist]
### Wargames
- [ ] Create 3 more scenarios for Frontend wargames
- [ ] Run wargames with the Dashboards team
- [ ] Run wargames with all team leads to prepare the leads to run the wargames with the team
```

```[tasklist]
### Extend this to Grafana on-call
- [ ] Update monitoring guide using the dashboard as an example in team good practices
- [ ] Create a generic Grafana frontend runbook
```
