### ISSUE TITLE
DashboardScene: Compatability with current dashboards epic 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#73874]
This issue contains a overview of everything we'll need to tackle to fully migrate our core dashboards to use Scenes. 

## Existing Milestones
- https://github.com/grafana/grafana/issues/73993 

# Overview

## Loading / persisted to runtime scene model 

* [x] Title
* [x] Variables
* [x] Panels
* [x] Rows
* [x] Library panels
* [x] Shared queries
* [x] Panel queries
* [x] Panel Transformations
* [x] Time Range
* [x] Time range options 
* [x] Repeating panels https://github.com/grafana/grafana/pull/74294
* [x] Repeating rows (https://github.com/grafana/grafana/pull/74505)
* [x] Adhoc filters support 
* [ ] Tags  
* [x] Links
* [x] Annotations (needs support in scene lib)
* [ ] Description
* [x] Panel links
* [x] Variables with $__searchFilter (missing support in scene lib)
* [x] Variables without url sync [(needs to be added to scenes)](https://github.com/grafana/scenes/pull/376)
* [x] Interval variable (https://github.com/grafana/scenes/issues/211)
* [x] Timezone and fiscalYearStartMonth, and weekStart  (https://github.com/grafana/grafana/pull/75715
* [x] Shared tooltip options (Dashboard.graphTooltip)
* [x] Some backward compatibility for plugins (and internal code) that access dashboardSrv.getCurrent and dashboardSrv.updatePanels. Something like https://github.com/grafana/grafana/pull/73755  but not a wrapper around old dashboardSrv but around the current dashboard scene.  
* [x] Adhoc filters with label != name (not sure if we really need this)
* [x] templateSrv.getAdHocFilters backward compatability 
* [x] Urls with slugs 

## Saving (runtime scene => persisted model)

* [x] Title
* [x] Tags
* [x] Description
* [x] Panels #73873 
* [x] Panel Queries
* [x] Panel Transformations 
* [x] Rows
* [x] Annotations
* [x] Links
* [x] Panel links
* [ ] Variables
* [x] Shared tooltip options (Dashboard.graphTooltip)

## Runtime behaviors / capabilities 

* [x] Variables multi-select trigger query for every change (https://github.com/grafana/scenes/issues/208
* [x] SceneQueryRunner not passing dashboardUID and panel id https://github.com/grafana/scenes/issues/298
* [x] Use data enricher to set dashboardUID and panelId https://github.com/grafana/grafana/pull/75719
* [x] Improve variable value when many values are selected (https://github.com/grafana/scenes/issues/399)
* [ ] Custom variable values entered manually and not in the options array are not preserved after full page reload (https://github.com/grafana/scenes/issues/387) 
* [ ] Handle many variables UX (flow or collapse to menu) 
* [x] Panel keyboard shortcuts https://github.com/grafana/grafana/pull/76233
* [x] Time keyboard shortcuts 
* [ ] Less critical keyboard shortcuts (toggle all exemplars, toggle all legends, etc)
* [x] TimeSrv compatibility 
* [x] Panel menu action for Explore 
* [x] Panel menu action for Get help (under More..)
* [x] Viewing repeated panel and doing full page reload leads to panel not found as the panel has not been generated yet 
* [x] Creating / editing / deleting annotation events
* [x] Support angular panels https://github.com/grafana/grafana/pull/76072
* [x] Auto-migrate angular panels 
* [x] Alert state hearts in panel headers
* [x] Pie chart legend hover events are not highlighting slices 
* [ ] Autofit panels (low prio) 
* [ ] Support time series annotation migrations [here is the how it works today](https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/timeseries/migrations.ts#L66)
* [ ] Use of panel id https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/timeseries/suggestions.ts#L222
* [x] Getting started panel dismiss (uses both panelId and dashboardSrv to update dashboard) 
* [ ] Dashboard list panel has an option to include all template variables in panel links, means the panel needs to re-render on any variable change. Not sure it does that. (This could be broken in old dashboard page as well).  
* [x] Backward compatability for usage of `templateSrv.getVariables` 
* [x] Playlist works 

## Inspect drawer

* [x] Data tab
* [x] Stats tab
* [x] DS Meta tab
* [x] JSON tab
* [x] Query inspector tab

## Editing

* [x] Panel size & position
* [x] Edit mode and discard 
* [ ] Save current edit to local storage 
* [ ] Adding panels
* [ ] Removing panels 
* [ ] Adding rows
* [ ] Editing row options
* [ ] Deleting rows
* [ ] Panel edit 
* [ ] Variable edit
* [ ] Annotation edit
* [x] Links edit
* [x] Time range options
* [x] Dashboard general settings (title, description, tags etc) 
* [ ] New / Empty dashboard page  

## Sharing

* [x] Link sharing (https://github.com/grafana/grafana/pull/74955)
* [x] Export (https://github.com/grafana/grafana/pull/75640)
* [ ] Embedded solo 
* [ ] Reporting 
* [ ] Public dashboard

**Comment by natellium** [comment]
@dprokop can we close this one?
