### ISSUE TITLE
Improve import dashboard UI

### ISSUE THREAD

**Issue by ivanortegaalba** [grafana/grafana#73896]
![image](https://github.com/grafana/grafana/assets/5699976/93efaaa3-c312-4de0-ae4c-27fe07f389c1)

**NOTE: Do not remove the panel libary**
```[tasklist]
### Tasks
- [ ] Add CTA to import dashboard in dashboard empty state
- [ ] Change copy to "Add library panel"
- [ ] Improve copy to point to template connection
```
