### ISSUE TITLE
i18n: Mark up Explore for translations

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#73979]
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/71535
- [ ] https://github.com/grafana/grafana/issues/73981
- [ ] https://github.com/grafana/grafana/issues/73985
- [ ] https://github.com/grafana/grafana/issues/73984
- [ ] https://github.com/grafana/grafana/issues/74311
- [ ] https://github.com/grafana/grafana/issues/74312
- [ ] https://github.com/grafana/grafana/issues/76095
```

```[tasklist]
### External
- [ ] https://github.com/grafana/grafana/issues/74309
- [ ] https://github.com/grafana/grafana/issues/74307
- [ ] https://github.com/grafana/grafana/issues/74305
- [ ] https://github.com/grafana/grafana/issues/74308
- [ ] https://github.com/grafana/grafana/issues/74310
```
