### ISSUE TITLE
Dashboard Scenes M1: Feature-complete dashboards with layout edit and model persistence  

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#73993]
Milestone Theme: _Arbitrary Grafana dashboard can be rendered using Scenes-based runtime. All current dashboard features are supported. One can modify panels position and save those changes back to Grafana db._

```[tasklist]
### Bugs
- [ ] [Home dashboard may be fetched incorrectly if a dashboard with`home-dashboard` uid has been created](https://github.com/grafana/grafana/pull/76748#discussion_r1374242256)
- [ ] Playlist controls are not visible
- [ ] https://github.com/grafana/grafana/issues/77260
- [x] [Data notices are missing in the panel header](https://github.com/grafana/grafana/pull/79146)
- [x] [timeFrom in share embed is not correct](https://github.com/grafana/scenes/pull/492)
- [ ] https://github.com/grafana/grafana/issues/79233
- [x] [Custom toolbar actions from Enterprise are not shown in the toolbar](https://github.com/grafana/grafana/pull/79139)
- [x] [Some interactions are not reported as they used to be, i.e. `dashboards_panelheader_menu`, `dashboards_panelheader_description_displayed`](https://github.com/grafana/grafana/pull/79078)
- [x] templateSrv.getAdHocFilters backward compatability
- [x] Long titles with alerts hide the menu option ([issue found here](https://github.com/grafana/grafana/pull/77945#pullrequestreview-1727791674))
- [x] **Library panels don't have Panel Menu**
- [x] [Share Modal / Snapshot: Expire options are not visible ](https://github.com/grafana/grafana/pull/77136)
- [x] [Time picker shortcuts are not working](https://github.com/grafana/grafana/pull/78632)
- [x] [ ] https://github.com/grafana/scenes/issues/486
- [x] Legend toggling does not work as it should https://github.com/grafana/scenes/issues/424
- [ ] https://github.com/grafana/grafana/issues/77857
- [x] [Markdown is not rendered in panel description](https://github.com/grafana/scenes/pull/464)
- [x] [System variables for __user, __org does not work](https://github.com/grafana/scenes/issues/448)
- [x] [System variables for __dashboard does not work](https://github.com/grafana/grafana/pull/78172)
- [x] [Viewing Panel A in fullscreen that is sharing query with another panel B. Shows no data when doing full page reload. panel B query runner is waiting for container Width](https://github.com/grafana/grafana/pull/78199)
```

```[tasklist]
### Core scope
- [x] [Scenes: Use Interval variable in DashboardScene](https://github.com/grafana/grafana/issues/75831)
- [x] Angular panels auto migrate (https://github.com/grafana/grafana/pull/76100)
- [x] [Viewer-role dashboards are rendered using Scenes behind a feature flag](https://github.com/grafana/grafana/pull/76748)
- [x] [Dashboard links are rendered in scenes-based dashboards](https://github.com/grafana/grafana/pull/77855)
- [x] [Panel links are rendered in scenes-based dashboards](https://github.com/grafana/grafana/pull/77295)
- [ ] https://github.com/grafana/grafana/issues/75526
- [ ] https://github.com/grafana/grafana/issues/76296
- [x] Critical keyboard shortcuts (https://github.com/grafana/grafana/pull/76233)
- [ ] https://github.com/grafana/scenes/issues/406
- [x] [Annotation queries can be run in scenes-based dashboard](https://github.com/grafana/scenes/issues/313)
- [x] [Handle panel Repeats (Horizontal & Vertical)](https://github.com/grafana/grafana/pull/74294)
- [x] [Handle Row repeats](https://github.com/grafana/grafana/pull/74505)
- [x] [Ad-hoc filters are supported by Scenes library](https://github.com/grafana/scenes/pull/346)
- [x] [Ad-hoc filters integrate with Dashboard Scene](https://github.com/grafana/grafana/pull/76115)
- [x] [Zoom out time range control is functional](https://github.com/grafana/scenes/issues/299)
- [x] @axelavargas [Interval variable is supported by Scenes library](https://github.com/grafana/scenes/issues/211)
- [x] [$__searchFilter is supported by Scenes library](https://github.com/grafana/scenes/issues/208)
- [x] Panel Inspect data tab https://github.com/grafana/grafana/pull/74646
- [x] Panel inspect json tab https://github.com/grafana/grafana/pull/74701
- [x] Panel inspect query tab https://github.com/grafana/grafana/pull/74795
- [x] Panel inspect meta tab (https://github.com/grafana/grafana/pull/74810)
- [x] [Library panels are loaded in scenes-based dashboard](https://github.com/grafana/grafana/pull/73406)
- [x] [Cursor is synchronized between panels](https://github.com/grafana/grafana/pull/73383)
- [x] [Query options (relative time, time shift) are respected in scenes-based dashboard](https://github.com/grafana/grafana/pull/62844)
- [x] Support to render angular panels in scenes https://github.com/grafana/grafana/pull/76072
- [x] TimeSrv compatability
- [x] TemplateSrv compatability
- [x] Panel menu action for explore
- [x] [Backward compatability for usage of templateSrv.getVariables](https://github.com/grafana/grafana/pull/77910)
```

```[tasklist]
### Future milestones prep scope
- [ ] https://github.com/grafana/scenes/issues/213
- [x] Scene-based dashboard can be serialised into Dashboard JSON
- [x] Provide a mechanism to enable/disable dashboard edit mode
- [x] Infrastructure for Panel Edit - a basic architecture for navigation to/from panel edit, basic skeleton of the layout and behaviors
```
