### ISSUE TITLE
Epic: Canvas button

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#74149]
The goal of this epic to reach basic feature parity with the [community button plugin](https://grafana.com/grafana/plugins/cloudspout-button-panel/), support sending Grafana user auth credentials, and improve general UX of the button element. The ideal end result is that the button element made GA as a beta element.

![Screenshot 2023-08-30 at 11 44 14 PM](https://github.com/grafana/grafana/assets/22381771/640b03c9-cf0e-45ed-b6a3-455e600f2f6b)

To use the below dashboard locally, you will need to install the [community button plugin](https://grafana.com/grafana/plugins/cloudspout-button-panel/) locally. 
  - I also recommend installing the other two community button plugins locally to maximize learning
    - https://grafana.com/grafana/plugins/speakyourcode-button-panel/
    - https://grafana.com/grafana/plugins/williamvenner-timepickerbuttons-panel/

[Button POC-1693463700936.json.txt](https://github.com/grafana/grafana/files/12483085/Button.POC-1693463700936.json.txt)

```[tasklist]
### API Editor
- [ ] https://github.com/grafana/grafana/issues/74218
- [ ] https://github.com/grafana/grafana/issues/74220
- [ ] https://github.com/grafana/grafana/issues/74221
- [ ] https://github.com/grafana/grafana/issues/74224
- [ ] https://github.com/grafana/grafana/issues/76293
- [ ] https://github.com/grafana/grafana/issues/76294
- [ ] https://github.com/grafana/grafana/issues/74499
- [ ] https://github.com/grafana/grafana/issues/74229
```

```[tasklist]
### Button UX
- [ ] https://github.com/grafana/grafana/issues/74225
- [ ] https://github.com/grafana/grafana/issues/74222
- [ ] https://github.com/grafana/grafana/issues/74500
- [ ] https://github.com/grafana/grafana/issues/74501
- [ ] https://github.com/grafana/grafana/issues/74226
- [ ] https://github.com/grafana/grafana/issues/76159
- [ ] https://github.com/grafana/grafana/issues/76158
- [ ] https://github.com/grafana/grafana/issues/74223
- [ ] https://github.com/grafana/grafana/issues/76498
```

Once above POC is complete, gather feedback from proserve team.

```[tasklist]
### Feedback / refinement
- [ ] https://github.com/grafana/grafana/issues/74781
- [ ] https://github.com/grafana/grafana/issues/74228
- [ ] https://github.com/grafana/grafana/issues/76306
- [ ] https://github.com/grafana/grafana/issues/76307
- [ ] TBD: address findings from the proserve team here
- [ ] https://github.com/grafana/grafana/issues/74230
- [ ] https://github.com/grafana/grafana/issues/78071
- [ ] https://github.com/grafana/grafana/issues/82041
- [ ] https://github.com/grafana/grafana/issues/79812
- [ ] https://github.com/grafana/grafana/issues/78992
```
