### ISSUE TITLE
Epic: DashGPT generate text features

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#74150]
* [Delivery plan](https://docs.google.com/document/d/1CAAzUmU_FoiK0UZTVyM28YeTH8aQOyN9620xIAfokA0/edit#heading=h.d5i3jmpwb1hp)
* [Figma](https://www.figma.com/file/yBuMIJDWHJbsfujZK2raRo/DashGPT?type=design&node-id=589-11323&mode=design&t=3HvUVKU3g9lpMMZB-0)

```[tasklist]
### UX Tasks
- [ ] https://github.com/grafana/grafana/issues/74155
- [ ] https://github.com/grafana/grafana/issues/74285
- [ ] https://github.com/grafana/grafana/issues/74287
- [x] Describe changes on a dashboard when saving Save as
- [x] Add dashboard title and description in two user flows
- [x] Error handling History refinement fails Generate X CTA fails
- [ ] https://github.com/grafana/grafana/issues/76208
- [ ] https://github.com/grafana/grafana/issues/77023
- [ ] Documenting toggletip UX use case of genAI
```

```[tasklist]
### Development Tasks
- [x] Implement `dashgpt` feature flag ([PR](https://github.com/grafana/grafana/pull/73971))
- [ ] https://github.com/grafana/grafana/issues/75179
- [ ] https://github.com/grafana/grafana/issues/74241
- [ ] https://github.com/grafana/grafana/issues/74242
- [ ] https://github.com/grafana/grafana/issues/74247
- [ ] https://github.com/grafana/grafana/issues/74248
- [ ] https://github.com/grafana/grafana/issues/74249
- [ ] https://github.com/grafana/grafana/issues/74245
- [x] Add analytics to improve component
- [ ] https://github.com/grafana/grafana/issues/75020
- [ ] https://github.com/grafana/grafana/issues/75177
- [ ] https://github.com/grafana/grafana/issues/75366
- [x] Implement warning status when the LLM plugin is not properly configured
- [ ] https://github.com/grafana/grafana/issues/75367
- [ ] https://github.com/grafana/grafana/issues/75698
- [x] https://github.com/grafana/grafana/issues/76211
- [x] Collect feedback and iterate on designs
- [x] "This is a panel.."  It might be great to prompt the ai to omit this obvious fact if possible
- [x] Update the background Toggletip https://github.com/grafana/grafana/pull/76069
- [ ] https://github.com/grafana/grafana/issues/76984
- [ ] https://github.com/grafana/grafana/pull/77895
```
```[tasklist]
### GA
- [ ] https://github.com/grafana/grafana/issues/75217
- [ ] https://github.com/grafana/grafana/issues/75368
- [ ] https://github.com/grafana/grafana/issues/76210
- [ ] https://github.com/grafana/grafana/issues/75797
- [x] Prepare release plan and see if we want blogpost for it
- [ ] https://github.com/grafana/grafana/issues/76066
- [ ] https://github.com/grafana/deployment_tools/pull/99988
- [x] Write blog post around generative AI features in dashboards / development
- [x] Get analytics about engadgement of customers with the toggle enabled
```

**Comment by imatwawana** [comment]
Please don't forget to documentation in these tasks somewhere.

**Comment by ivanortegaalba** [comment]
> Please don't forget to documentation in these tasks somewhere. :-) Just so it doesn't slip and end up out of sync.

Added the task to the list @imatwawana! 👍

**Comment by ivanortegaalba** [comment]
Closing this one in favor of this https://github.com/grafana/grafana/issues/83710 focused only in preparing the feature for GA
