### ISSUE TITLE
DashGPT: Create design for generation history UX

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#74155]
**Goal**
Design the screens for the generation history for title and description generation flows.

**Tasks**

- [x] UX Research guidelines
- [x] Document the UX workflow for title and description generation
- [x] Design mockups for different approaches
- [ ] Get feedback from other UX's and the DashGPT team
- [ ] Deliver the final design to developers

See the consensus design [doc](https://docs.google.com/document/d/1lwQZ1Fj3zLkfE_Hc_1jvfohKjq12oeAmjRyRrJEhvYs/edit#heading=h.5sybau7waq2q)

**Comment by grafanabot** [comment]
@natydej please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:

**Comment by natydej** [comment]
Here is the [Figma file](https://www.figma.com/file/yBuMIJDWHJbsfujZK2raRo/DashGPT?type=design&node-id=589-11323&mode=design) with some proposals
Prototypes for how to display the history
[Prototype link](https://www.figma.com/proto/yBuMIJDWHJbsfujZK2raRo/DashGPT?type=design&node-id=638-2963&t=kK2YafQtjR6GRSQ2-1&scaling=min-zoom&page-id=589%3A11323&starting-point-node-id=638%3A2963&show-proto-sidebar=1&mode=design) - Having an icon in the input and it will appear after the first text generated
[Prototype link](https://www.figma.com/proto/yBuMIJDWHJbsfujZK2raRo/DashGPT?type=design&node-id=638-2521&t=LHMfVxOMcG9zX6eB-1&scaling=min-zoom&page-id=589%3A11323&starting-point-node-id=638%3A2521&show-proto-sidebar=1&mode=design) - Having the same button re-generate as improve to open the history

**Comment by natydej** [comment]
The design that has been decided to have a better UX is the one below:

<img width="542" alt="History-Text-Generated" src="https://github.com/grafana/grafana/assets/51436795/257eddc6-bfac-4631-9c92-a27ad88616ef">

**Comment by ivanortegaalba** [comment]
The team agreed with it, and they started with the implementation 💪
