### ISSUE TITLE
Epic: Transformation UI Improvements

### ISSUE THREAD

**Issue by codeincarnate** [grafana/grafana#74194]
This is for collecting work relating to transformation UI improvements
```[tasklist]
### Transformations, Transformers, Transformalations
- [ ] https://github.com/grafana/grafana/issues/74197
- [ ] https://github.com/grafana/grafana/issues/74199
- [ ] https://github.com/grafana/grafana/issues/74203
- [ ] https://github.com/grafana/grafana/issues/74202
- [ ] https://github.com/grafana/grafana/issues/74208
- [ ] https://github.com/grafana/grafana/issues/74201
- [ ] https://github.com/grafana/grafana/issues/74209
- [ ] https://github.com/grafana/grafana/issues/74206
```

**Comment by codeincarnate** [comment]
Closing as improving the delete flow is the only straggler at this point
