### ISSUE TITLE
Prometheus: Onboarding epic

### ISSUE THREAD

**Issue by bohandley** [grafana/grafana#74689]
This work is a continuation of the Getting Started 
Grafana Goal for 2022. It aligns with Grafana Goal FY24/25 Onboarding new teams. These fixes can also include findings from the CUJ findings.

Ideas suggested as Achievable Q1 Goals in [Research Findings: Getting Started Loki & Prometheus](Research Findings: Getting Started Loki & Prometheus)
- [x] Kick start your query for newbies
- [ ] New category of query patterns for new users.
- [ ] UI Cues

Design and validate minor UI tweaks, such as guiding the user to the "Kickstart your onboarding query starters."
- [ ] Make switching between Code and Builder more discoverable.

General
- [ ] Rename components of the Query builder to help users better understand the features.
- [x] Make it easier to write the first queries by adding more hints.

**Comment by bohandley** [comment]
Closing this as Prometheus has been moved to a new squad and they can decide what onboarding features they would like to pursue.
