### ISSUE TITLE
Common Azure credentials format in Azure Monitor datasource

### ISSUE THREAD

**Issue by kostrse** [grafana/grafana#75123]
Azure Monitor is the last remaining datasource which still uses own custom format for Azure credentials.
The goal is to migrate it to the common credentials format used by other Azure datasources to for better reuse of code and make it easier to introduce new features across the all Azure datasources.

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/pull/62975
- [ ] https://github.com/grafana/grafana/issues/60782
- [ ] https://github.com/grafana/grafana/issues/60781
```
