### ISSUE TITLE
Azure AD Workload Identity support for Azure datasources

### ISSUE THREAD

**Issue by kostrse** [grafana/grafana#75404]
Work involved for support of Azure AD Workload Identity for users who host Grafana in Kubernetes.

Details on Azure AD Workload Identity:
* https://azure.github.io/azure-workload-identity
* https://github.com/Azure/azure-workload-identity

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana-azure-sdk-go/pull/38
- [ ] https://github.com/grafana/grafana/pull/75283
- [x] https://github.com/grafana/grafana/pull/75681 (Azure Monitor and Prometheus)
- [ ] Workload Identity authentication in Azure Data Explorer datasource
```
