### ISSUE TITLE
Add prettier to github plugins

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#75518]
we should make sure prettier is running in the following github repos:
- [x] https://github.com/grafana/github-datasource
- [x] https://github.com/grafana/google-sheets-datasource
- [x] https://github.com/grafana/grafana-csv-datasource
- [x] https://github.com/grafana/grafana-json-datasource
- [x] https://github.com/grafana/grafana-zabbix

**Comment by khushijain21** [comment]
should prettier also work on pre-commit hook?

**Comment by gabor** [comment]
that's a good idea, but i'm not sure how much pre-commit hooks have we set up already, so adding this may mean to setup the whole pre-commit-hook machinery too. we'll keep this in mind, but for now i think the CI stuff is a good first step.

**Comment by gabor** [comment]
prettier added to all of the repos.
