### ISSUE TITLE
Share modal is rendered in DashboardScene

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#75526]
This issue track progress of dashboard share modal migration to Scenes architecture

```[tasklist]
### Tasks
- [ ] <https://github.com/grafana/grafana/pull/75907>
- [x] [Link sharing tab](https://github.com/grafana/grafana/pull/74955)
- [x] [Export tab](https://github.com/grafana/grafana/pull/75640)
- [x] [Snapshot tab](https://github.com/grafana/grafana/pull/76132)
- [x] [Transforming panel and row repeats in DashboardScene to a snapshot](https://github.com/grafana/grafana/pull/76428)
- [x] [Public dashboard tab](https://github.com/grafana/grafana/pull/76837)
- [x] [Panel embed tab](https://github.com/grafana/grafana/pull/77062)
- [ ] [Panel share - Library panel](https://github.com/grafana/grafana/pull/78421)
```

**Comment by khushijain21** [comment]
Hello, is this open for contribution?
