### ISSUE TITLE
Card component [document]

### ISSUE THREAD

**Issue by Aires-Grafana** [grafana/grafana#75547]
```[tasklist]
### Tasks
- [x] Create documentation GDoc
- [x] Add design documentation
- [ ] Add code documentation
- [ ] Add documentation reviewed to Saga site
- [ ] Publish component documentation
```

**Comment by Aires-Grafana** [comment]
Google Doc file with Card documentation to be picked up by a developer to add dev documentation.
https://docs.google.com/document/d/1VwUOZs6P3Ye5ezv3kUOC61tBs7IHFVXgPjUMAwSVKrg/edit?usp=sharing
