### ISSUE TITLE
Card component [build]

### ISSUE THREAD

**Issue by Aires-Grafana** [grafana/grafana#75548]
```[tasklist]
### Figma assets
- [ ] Needed [Global](https://www.figma.com/file/htVIFrTq8e7sx8Olo7L6kZ/Saga-Components--Dark-theme?type=design&node-id=19951-1986&mode=design&t=1lXtR9b2qaEfoP4K-4) card utilities.
- [ ] Needed [Lead](https://www.figma.com/file/htVIFrTq8e7sx8Olo7L6kZ/Saga-Components--Dark-theme?type=design&node-id=19951-2930&mode=design&t=1lXtR9b2qaEfoP4K-4) card utilities.
- [ ] Needed [Main](https://www.figma.com/file/htVIFrTq8e7sx8Olo7L6kZ/Saga-Components--Dark-theme?type=design&node-id=19951-3304&mode=design&t=1lXtR9b2qaEfoP4K-4) card utilities.
- [ ] Needed [Trail](https://www.figma.com/file/htVIFrTq8e7sx8Olo7L6kZ/Saga-Components--Dark-theme?type=design&node-id=19951-3346&mode=design&t=1lXtR9b2qaEfoP4K-4) card utilities.
- [ ] Needed [Footer](https://www.figma.com/file/htVIFrTq8e7sx8Olo7L6kZ/Saga-Components--Dark-theme?type=design&node-id=19951-3494&mode=design&t=1lXtR9b2qaEfoP4K-4) card utilities.
- [ ] New [Card Layout Swapper](https://www.figma.com/file/htVIFrTq8e7sx8Olo7L6kZ/Saga-Components--Dark-theme?type=design&node-id=19947-2938&mode=design&t=1lXtR9b2qaEfoP4K-4) variants
- [ ] New [Card Pattern](https://www.figma.com/file/htVIFrTq8e7sx8Olo7L6kZ/Saga-Components--Dark-theme?type=design&node-id=19947-3293&mode=design&t=1lXtR9b2qaEfoP4K-4) variants
```
```[tasklist]
### Tasks
- [ ] Allow interfaces like `Badges` to be positioned at the bottom of the main content
- [x] Add `Overline` Interface to add smaller text above the title
- [x] Create new `isCompact` property
- [ ] Create new property to control position of the highlight bar
- [ ] Add possibility for multiple cards to be selected and instead of radio button it displays a check box
- [ ] Create new patterns, either as components or templates
```

**Comment by Aires-Grafana** [comment]
Card component final designs [here](https://www.figma.com/file/VW5WsWOgc7PbX8d4qrDB9c/Bruno-Aires---Card-Component?type=design&node-id=8444-13482&mode=design).
On that page, it is possible to also find the [Card Utilities](https://www.figma.com/file/VW5WsWOgc7PbX8d4qrDB9c/Bruno-Aires---Card-Component?type=design&node-id=19947-2670&mode=design&t=S3AkI2o0W1qB6sSB-4) and the two types of cards available:
- [Layout Swapper Card](https://www.figma.com/file/VW5WsWOgc7PbX8d4qrDB9c/Bruno-Aires---Card-Component?type=design&node-id=19947-2938&mode=design&t=S3AkI2o0W1qB6sSB-4)
- [Card Patterns](https://www.figma.com/file/VW5WsWOgc7PbX8d4qrDB9c/Bruno-Aires---Card-Component?type=design&node-id=19947-3293&mode=design&t=S3AkI2o0W1qB6sSB-4)

Find [here](https://www.figma.com/file/VW5WsWOgc7PbX8d4qrDB9c/Bruno-Aires---Card-Component?type=design&node-id=19947-2959&mode=design&t=S3AkI2o0W1qB6sSB-4) an example of the compact card variants.
