### ISSUE TITLE
Instrumentation: Add label to plugin request metrics/logs that defines the source of the error

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#75761]
### Problem
Similar to #68480, here is no easy way to differentiate between user errors (bad requests and wrong configuration), actual errors in the plugin and downstream services a plugin interacts with. This makes it hard to define SLO's for plugin authors since including all of mentioned error types would probably result in plugin authors being notified too often and not specifically when there's a real problem going on.

### Proposal 
Similar to #68480, make it possible for plugin authors to define a source of an error. Suggested to use `plugin` and `downstream` as available sources. The https://github.com/grafana/grafana-plugin-sdk-go/pull/741 includes changes based on this proposal for the query data endpoint and allows `error source` to be set on a data response similar to existing `status` and `error` fields. 

With proposed changes above plugin authors can start implement support for and returning an error source for each data query response. 

It's suggested that Grafana use the error source information and include it as a label named `status_source` on [grafana_plugin_request_*](https://github.com/grafana/grafana/blob/0577c5c8e535d3beaa754b8ef85e1c4a25c81be8/pkg/plugins/backendplugin/instrumentation/instrumentation.go#L19-L23) metrics (and possibly [plugin request logs](https://github.com/grafana/grafana/blob/0577c5c8e535d3beaa754b8ef85e1c4a25c81be8/pkg/services/pluginsintegration/clientmiddleware/logger_middleware.go#L47-L88) as well). Reason naming it `status_source` rather than `error_source` is to follow #68480 conventions.

One query data request could return multiple data responses, each having their own `error`, `status` and `source`. However, the [grafana_plugin_request_*](https://github.com/grafana/grafana/blob/0577c5c8e535d3beaa754b8ef85e1c4a25c81be8/pkg/plugins/backendplugin/instrumentation/instrumentation.go#L19-L23) and logs are tracking each request. Based on discussion in 
https://github.com/grafana/grafana-plugin-sdk-go/pull/741#discussion_r1338850734 it's suggested that we implement some kind of priority of data responses/error sources and pick the highest one (plugin error highest priority).

#### Returned errors

In those cases where an error is returned from the call resource/check health/query data methods rather than a call resource/check health/query data response in the plugin we need a way to include the `error source` of that error. Maybe time to look into making https://github.com/grafana/gerror/ shared between Grafana and the plugin SDK? 
TBD/need investigation

```[tasklist]
### Tasks
- [x] SDK/queryData: https://github.com/grafana/grafana-plugin-sdk-go/pull/741
- [ ] https://github.com/grafana/grafana/pull/76011
- [x] Grafana: Add feature toggle for `status_source` on plugin request metrics/logs
- [x] Grafana: Populate `status_source` label on plugin request metrics https://github.com/grafana/grafana/pull/76236
- [x] Grafana: Populate `status_source` label on plugin request logs https://github.com/grafana/grafana/pull/76676
- [ ] SDK: Figure out if/how we can ease plugin authors life by automatically derive `error source`, e.g. for an outgoing HTTP request/response, or provide better API's to remove code duplication etc
- [ ] Grafana/SDK: Investigate how returned errors can include error source
- [x] https://github.com/grafana/grafana/issues/76769 https://github.com/grafana/grafana/pull/77613
```

```[tasklist]
### Rollout of feature toggle
- [x] Dev
- [x] Staging
- [x] Canary
- [x] Prod
```

**Comment by marefr** [comment]
Closing this for now since the outstanding tasks has become obsolete and/or are handled elsewhere
