### ISSUE TITLE
[EPIC] PromCon Usability Bugs

### ISSUE THREAD

**Issue by bohandley** [grafana/grafana#75851]
From @catherineymgui 

Here is a list of promcon usability feedback, and some other glaring UI issues

- [x] The drawer isn’t scrolling down to the bottom when there’s a new element that shows up

- [x] Conversational blocks are still dark in light mode 
![Image](https://github.com/grafana/grafana/assets/5264102/9e2a8a71-9c27-4839-92c5-fd62ce2cca34)
- [x] Some users clicked the “Refine prompt” multiple times — this list of buttons should become disappear when clicked on
From: 
![Image](https://github.com/grafana/grafana/assets/5264102/d75a29e0-8413-497e-a8fa-6d1417fdc7bc)
To:
![Image](https://github.com/grafana/grafana/assets/5264102/b0bf01ae-9f06-4a60-8e2c-29d42fd40e53)
- [x] Users tried to modify the original “enter a prompt” input field instead of clicking a new button — disable this field once something is submitted
![Image](https://github.com/grafana/grafana/assets/5264102/baa99267-467c-4b31-a6e5-96ee8bebe989)
