### ISSUE TITLE
Chore [Epic]: Replace LegacyForms in core Grafana

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#76107]
**What is the chore?**:
We have a set of legacy form components, which essentially were deprecated over 3 years ago ( #22862). They all have modern replacement components.

We only [have 11 occurences in core left](https://play.grafana.org/d/VEy5UXjmk/grafana-ci-code-stats?orgId=1&from=1680771811847&to=1696583011847&viewPanel=13), so I though I'd make a list:

`grep -r -o 'LegacyForms;' public/app`:

 - [ ] public/app/core/components/Select/MetricSelect.tsx
 - [x] public/app/plugins/datasource/loki/configuration/QuerySettings.tsx https://github.com/grafana/grafana/pull/76331
 - [x] public/app/plugins/datasource/influxdb/components/editor/config/ConfigEditor.tsx https://github.com/grafana/grafana/pull/76382
 - [x] public/app/plugins/datasource/influxdb/components/editor/config/InfluxFluxConfig.tsx https://github.com/grafana/grafana/pull/76495
 - [ ] public/app/plugins/datasource/influxdb/components/editor/config/InfluxInfluxQLConfig.tsx
 - [x] public/app/plugins/datasource/opentsdb/components/OpenTsdbDetails.tsx https://github.com/grafana/grafana/pull/76165
 - [x] public/app/plugins/datasource/elasticsearch/configuration/DataLink.tsx https://github.com/grafana/grafana/pull/76397
 - [x] public/app/features/admin/ldap/LdapPage.tsx https://github.com/grafana/grafana/pull/76156
 - [x] public/app/features/folders/FolderSettingsPage.tsx https://github.com/grafana/grafana/pull/76313
 - [ ] public/app/angular/angular_wrappers.ts

**Is there anything else we need to know?**:
 In some cases just changing the component might not be enough, as it is located in older code. In these cases, removing occurrences of `gf-form` might also be valuable. If you do, please mention #65513.

**Related issues**
https://github.com/grafana/grafana/issues/66479
https://github.com/grafana/oss-plugin-partnerships/issues/222

**Comment by SaurabPoudel** [comment]
Hello !, I am interested in contributing to this issue.

**Comment by tskarhed** [comment]
@SaurabPoudel Awesome! Pick one of the files in the list, and if you want some guidance, maybe this PR that I have open can help you https://github.com/grafana/grafana/pull/76055

**Comment by carlqt** [comment]
Hey, I would like to contribute but I'm having some problems with testing.

I'm trying to remove `Select/MetricSelect.tsx` but I don't even know where it's used to see if there were any issues when I replaced it with the `Select` component. Anyone can help me figure this out?

**Comment by tskarhed** [comment]
@carlqt I've looked around, and it seems it has mainly been used in Angular code, which we have removed most of in core. It might be possible that we can remove the component completely. I'll double check.

**Comment by carlqt** [comment]
Hi @tskarhed maybe I can try and deprecate the other items in the list?

Right now I'm looking at the `feature/FolderSettingsPage.tsx`. Searching the codebase and I do not see this component being used anywhere, I'm not sure if I should just simply replace the `LegacyForms`. Here's my PR and let me know what I missed https://github.com/grafana/grafana/pull/76313

**Comment by tskarhed** [comment]
@carlqt That's great! I can't seem to find any usage of MetricSelect, so you may open a PR removing it

**Comment by shabeebk** [comment]
@tskarhed I have just added the changes for `public/app/plugins/datasource/loki/configuration/QuerySettings.tsx` in #76331

**Comment by Ciggzy1312** [comment]
Made a PR for `public/app/plugins/datasource/elasticsearch/configuration/DataLink.tsx`
PR -> #76397

**Comment by itsmylife** [comment]
@tskarhed Can we use `InlineField, InlineFieldRow`? 
If no then we should handle this again https://github.com/grafana/grafana/pull/76495 (Sorry I merged it before asking this question.)

**Comment by maknik** [comment]
Made PR for `public/app/plugins/datasource/influxdb/components/editor/config/InfluxInfluxQLConfig.tsx` but I see know that there is one already

PR -> https://github.com/grafana/grafana/pull/76751

**Comment by carlqt** [comment]
@tskarhed Just a heads-up. I have a PR for removing the Legacy Forms on the `FolderSettingsPage` component

https://github.com/grafana/grafana/pull/76313

**Comment by tskarhed** [comment]
> @tskarhed Can we use `InlineField, InlineFieldRow`? If no then we should handle this again #76495 (Sorry I merged it before asking this question.)

We should avoid using the inline versions in the config pages, so maybe we need to address this one again

**Comment by itsmylife** [comment]
@tskarhed Sorry for auto-closing the issue 🤦 Github doing it automatically.

**Comment by akozlev** [comment]
Just created a PR https://github.com/grafana/grafana/pull/104973 for Pyroscope Datasoruce.

I think this is also the last place this was used so this could probably closed once the PR is merged.

Grep on PR branch shows the only use in `packages/grafana-ui/src/components/index.ts`:
```
❯ rg LegacyForms
scripts/ci-frontend-metrics.sh
13:LEGACY_FORMS="$(grep -r -oP 'LegacyForms;' public/app | wc -l)"

packages/grafana-ui/CHANGELOG.md
51:In Grafana 7 we have migrated from our old form components to `LegacyForms` namespace. The new components were previously available under the `Forms` namespace.
53:All the following components were moved to the LegacyForms namespace, and some replaced with the new form components:
78:import { LegacyForms } from '@grafana/ui';
80:<LegacyForms.Switch ... />
140:- **Migration**: Final components to LegacyForms. [#23707](https://github.com/grafana/grafana/pull/23707), [@tskarhed](https://github.com/tskarhed)

packages/grafana-ui/src/components/index.ts
290:const LegacyForms = {
300:export { LegacyForms, LegacyInputStatus };
```
