### ISSUE TITLE
NodeGraph: Improvements Q4

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#76605]
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/68540
- [ ] https://github.com/grafana/grafana/issues/63941
- [ ] https://github.com/grafana/grafana/issues/76603
- [ ] https://github.com/grafana/grafana/issues/76604
```
