### ISSUE TITLE
Design POC for the Stop button

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#77023]
Stop request button - common feedback
The most common feedback from both Thanos’ personal experience and conversations with others.

```[tasklist]
### Tasks
- [x] Design screens with the "Stop" button for the text-generation flow
- [x] Prototype
- [x] Present to the Squad
- [x] Gather feedback and refine
```

**Comment by natydej** [comment]
Here are the recordings for the Stop Button proposal designs, for both approaches, we have replaced the main CTA of Auto-generate to change a Stop generating status. For that, we have 2 different options to let the users know about the loading status:

- **Version 1:** Stop generating CTA with the loadingBar inside the input text.
- **Version 2:** Stop generating 

https://github.com/grafana/grafana/assets/51436795/8982aad9-b278-479f-ace8-c4b603a75cfa


https://github.com/grafana/grafana/assets/51436795/c03dd0f8-8291-481a-9d54-554a43feec69

CTA with a fa-spinner icon, instead of the stop icon itself.

[Prototype](https://www.figma.com/proto/yBuMIJDWHJbsfujZK2raRo/DashGPT?type=design&node-id=913-3597&t=0VWyFAySijekmmBy-1&scaling=scale-down&page-id=913%3A3596&starting-point-node-id=913%3A3597&show-proto-sidebar=1&mode=design)

**Comment by natydej** [comment]
The team discussed this in yesterday's daily and it seems like going with the initial approach of #2 Stop generating CTA with a `fa-spinner` icon, instead of the stop icon itself. 
cc @nmarrs Closing this PR to open a new one for the development
