### ISSUE TITLE
Q4 🪵 goals

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#77055]
## Q4 items
-  [x] `feature` Table View: Wrap up, release, document, etc. https://github.com/grafana/grafana/issues/77469 @gtk-grafana 
- [x]  `release` [Easier search and filter: support to match log lines with queries] (https://github.com/grafana/grafana/issues/76129). @matyax  
- [x] `devops` Loki: Decouple frontend https://github.com/grafana/grafana/issues/72631 @ivanahuckova 
- [x] `devops` Elasticsearch: Decouple frontend https://github.com/grafana/grafana/issues/72632  matyax
- [x] `plugins` Logs panel: support for more features outside of Explore. https://github.com/grafana/grafana/issues/20166 / Infinite scrolling / Permalink / Filter buttons in Log details @gtk-grafana @svennergr 
- [x] `feature` Structured metadata - backend + frontend https://github.com/grafana/grafana/pull/77361 @svennergr 

## Niat's backlog
- [ ] `ux` Logs: New logs explore concept https://github.com/grafana/grafana/issues/70002
- [x] `ux` Loki: Move the "show logs"  button in Log browser https://github.com/grafana/grafana/issues/71747

## Q1
- [ ]  `feature` Infinite scroll for logs https://github.com/grafana/grafana/issues/71728 @matyax 

## Q2 maybe
- [ ] `devops` Elasticsearch: Convert to external plugin
- [ ] `devops` Loki: Convert to external plugin
- [ ] `plugins` partner on CloudWatch
- [ ] `feature` Design doc for logs volume improvements
- [ ] `feature` Test predefined operations https://github.com/grafana/grafana/issues/69893
- [ ] `ux` Split new logs explore UI concept/logsapp hackathon project into a smaller features + create issues @ivanahuckova @matyax @svennergr 

## Resources: 
https://miro.com/app/board/uXjVMhnb58s=/

**Comment by grafanabot** [comment]
@matyax please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:
