### ISSUE TITLE
Design system template components

### ISSUE THREAD

**Issue by Clarity-89** [grafana/grafana#77269]
Create ready-to-use templates and pattern for common page types within Grafana.
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/77270
- [ ] https://github.com/grafana/grafana/issues/77363
- [ ] https://github.com/grafana/grafana/issues/77364
- [ ] https://github.com/grafana/grafana/issues/77376
- [ ] https://github.com/grafana/grafana/issues/77986
- [ ] https://github.com/grafana/grafana/issues/78370
- [ ] https://github.com/grafana/grafana/issues/78575
- [ ] https://github.com/grafana/grafana/issues/79556
- [ ] Add analytics
- [ ] https://github.com/grafana/grafana/issues/81128
```

**Comment by yaelleC** [comment]
@Clarity-89 are we good to close this epic as done in Q4?
