### ISSUE TITLE
Grafana UI component libraries

### ISSUE THREAD

**Issue by Clarity-89** [grafana/grafana#77276]
Define ownership of the various components libraries and set guidelines as to what goes where. 

The list of libraries: 
- [grafana/ui](https://github.com/grafana/grafana/tree/46f331e2848e9d85f61bf074aa637707e71ddffd/packages/grafana-ui)
- [grafana/experimental](https://github.com/grafana/grafana-experimental)
- [plugin-ui](https://github.com/grafana/plugin-ui)

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/77185
- [x] Remove `SecretInput` and `SecretTextarea` components from `grafana/experimental` and replace their usage with the components from `grafana/ui`. https://github.com/grafana/grafana-experimental/pull/115
- [ ] https://github.com/grafana/grafana/issues/77541
```
