### ISSUE TITLE
Docs: create shared content for common options in visualizations

### ISSUE THREAD

**Issue by imatwawana** [grafana/grafana#77320]
Many visualizations have the same common options:

```[tasklist]
### Tasks
- [x] Tooltip - PR #86553
- [x] Legend - PR https://github.com/grafana/grafana/pull/86814
- [x] Data links - PR https://github.com/grafana/grafana/pull/86893
- [x] Value mappings - PR https://github.com/grafana/grafana/pull/86996
- [x] Thresholds - PR https://github.com/grafana/grafana/pull/87009
- [x] Overrides - PR https://github.com/grafana/grafana/pull/87197
- [x] Standard options - PR https://github.com/grafana/grafana/pull/87199
- [ ] Panel options - PR https://github.com/grafana/grafana/pull/87258
```

For these options, we should be using as much shared content as possible so that we have one source of truth and contributors don't have to keep rewriting the same content. We have some shared content already, but the goal is to cover all of these in all their varieties. In issue #73954, we did the work of documenting how these options are implemented across visualizations and now we can use that work to complete this task.

[Common options review](https://docs.google.com/document/d/1Vdea4Sca1AEXmOeXAkzC6TtCS_XDKQird6J2Iyw2bVQ/edit?usp=sharing)
[Panel config docs audit observations](https://docs.google.com/document/d/1C5nJayI7s0QF4NvANf0yidxoHIjgyekISCQdLh03mSc/edit#heading=h.h24i3vtjocz6)

Goal: Q4

**Comment by imatwawana** [comment]
In the course of preparing to do add/update shared files to use on visualization pages and link to more in-depth content from there, it's become clear that some of the panel config documentation will need some amount of updating at this stage. This will be a quick effort focused on ensuring the pages are an accurate reflection of the UI and that there aren't major gaps. Full restructuring of these pages is later in the roadmap.
