### ISSUE TITLE
 E2E: Improve support for testing plugins 

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#77484]
**Why is this needed**:

Grafana has its own e2e testing framework that is available to core Grafana developers and plugin developers through the [grafana/e2e package](https://github.com/grafana/grafana/tree/main/packages/grafana-e2e). This framework wraps Cypress and exposes flows that allow plugin developers to test the most common end-user scenarios in their plugins. grafana/e2e is currently using Cypress version 9.5.1. 

There are a few problems related to our current e2e setup. 
* There’s no way for plugin developers to write one test suite that is able to test their plugin across multiple versions of Grafana. This is true for local testing and testing in CI.
* Our homegrown Cypress wrapper adds little value and it’s poorly documented. If we allowed plugin developers to access the Cypress object directly rather than through our wrapper, it would cause less confusion as developers could refer to the Cypress official documentation directly. 
* It’s hard to write isolated e2e tests for plugin specific functionality without testing other parts of Grafana. When an e2e test in a plugin breaks, it’s usually because of a change in Grafana that is unrelated to the SUT. 
For example, while testing the plugin query editor, the test failed because the UI for navigating to a panel changed, causing the “addPanel” flow to break.  
* Plugin developers have no control over Cypress
 grafana/e2e uses an old version of Cypress (9.5.1 was released two years ago) which has many [known limitations](https://docs.google.com/document/d/1GCh-owJSTZrTw5blzuTFDZflAp4xBTjUc1OY71lKQYg/edit#heading=h.hacp0w15ubvu), yet it’s nearly impossible to upgrade to a more recent version since it would break e2e tests in most of our plugins. 
A few examples:
   * [Cypress versions < v10.1.x don’t run natively on ARM chips](https://www.cypress.io/blog/2021/01/20/running-cypress-on-the-apple-m1-silicon-arm-architecture-using-rosetta-2/).
      * Instead, it runs through Rosetta which is much slower.
      * This makes it basically impossible to develop cypress tests locally and causes tests to fail that wouldn’t normally.
   * Cypress v9 has bugs that are fixed in newer versions which cause random timeout failures
   * Cypress >v10 introduces many major breaking changes to the config and other areas.
      * We can’t upgrade the cypress version inside @grafana/e2e because it’ll break tests for all the plugins using this package for their own e2e tests.
      * We can’t maintain compatibility with both cypress 9 and >10 in the same package without introducing a great deal of complexity that will easily break and will be hard to maintain
      * Flows are also affected by API changes in cypress >10.
  * For the external plugins, the e2e package is tied in the package.json. So if we want to test a plugin against different grafana versions lots of configuration tweeks required. [example](https://github.com/grafana/enterprise-datasources/blob/533e66215e889157bb21719e012657a251299f4a/tools/e2e/package.json#L25-L32)
https://www.cypress.io/blog/2021/01/20/running-cypress-on-the-apple-m1-silicon-arm-architecture-using-rosetta-2
  * There’s no way for plugin developers to extend or override Cypress config ([except for the base url](https://github.com/grafana/grafana/blob/main/contribute/style-guides/e2e-plugins.md#commands))
* The way CI currently pulls Grafana version from the version specified for grafana/e2e-selectors in package.json is unintuitive and not documented in the [drone extension](https://github.com/grafana/grafana-drone-extension/tree/main) nor the [plugin e2e docs](https://github.com/grafana/grafana/blob/main/contribute/style-guides/e2e-plugins.md).
* Any change to the Grafana UI can break flows in grafana/e2e. Now that Grafana core is [decoupled from grafana/e2e](https://github.com/grafana/grafana/pull/74084), we no longer dogfood the framework so it’s unlikely that a contributor will ever notice that the change will break e2e tests in external plugins further down the road. 
* When plugin e2e tests run in CI, Grafana can be provisioned with any data sources and/or dashboards from the [plugin-provisioning](https://github.com/grafana/plugin-provisioning) repo. This is very helpful for plugin developers, however it has security implications for OSS plugins (more on that [here](https://docs.google.com/document/d/1t4pqEpy8CVmmYgqRhSyswYVq5pfLcMoIlo9EV05uH6g/edit#heading=h.hacp0w15ubvu)).

**What would you like to be added**:

> New standalone package that supersedes grafana/e2e

We create a new standalone package, grafana/plugin-e2e, which has one purpose and that is to provide plugin E2E testing capabilities across multiple versions of Grafana. We also move grafana/e2e-selectors out of Grafana core and make the selectors version specific. 

One of the main objectives of the grafana/plugin-e2e is to provide ways for plugin authors to write one test suite that works across multiple versions of Grafana. To achieve this, @grafana/plugin-e2e needs to, together with @grafana/e2e-selectors, be as self-contained as possible. Rather than depending on Grafana packages, all the logic necessary for making a test scenario compatible with all recent versions of Grafana needs to be contained in these two packages. 

@grafana/e2e-selectors is moved out of core Grafana so that the package itself is no longer tied to a specific Grafana release. However, the selectors must be changed so that their values are associated with a minimum Grafana version.

```typescript
export const pages = {
 AddDataSource: {
  url: {
   '8.5.0': '/datasources/new',
   '10.1.0': '/connections/datasources/new',
  },
  dataSourcePlugins: {
   '8.5.0': (pluginName: string) => `Data source plugin item ${pluginName}`,
   '9.5.0': (pluginName: string) => `Add new data source ${pluginName}`,
  },
 },
 ...
}	
```
When a plugin executes a command in @grafana/plugin-e2e, the E2E test tool will first retrieve the Grafana version from the bootdata in the current test context. It will then resolve selectors that are valid for the version of Grafana that is currently running. 
![Screenshot 2023-11-01 at 09 12 37](https://github.com/grafana/grafana/assets/2388950/2cba83c1-481b-4cfb-a06d-8a6f0f49400a)

When the UI changes from one version to another, E2E test scenarios that use selectors for that UI will continue to work most of the time. However, when there are larger functional changes in the UI, @grafana/plugin-e2e needs to be the bridge between those different UIs so that the plugin author doesn’t have to write Grafana version specific test suites. An example of such a scenario is when the UI for adding visualizations to new dashboards changed in Grafana 10. 

**Who is this feature for?**
Plugin authors

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/76754
- [ ] https://github.com/grafana/grafana/issues/76755
- [ ] https://github.com/grafana/grafana/issues/76753
- [ ] https://github.com/grafana/grafana/issues/77497
- [x] Create a Github action that enables running E2E tests in multiple versions of Grafana.
- [x] Add exhaustive E2E tests to a core plugin
- [x] Run core plugin E2E tests in CI whenever there's a change in grafana UI
- [x] Write documentation/guidelines on how to write E2E tests in plugins
- [x] Write guideline for how Grafana core contributors can fix broken scenarios in grafana/plugin-e2e
- [ ] Come up with a strategy for how to decouple grafana/e2e-selectors from grafana core and make it a standalone package. Where should this package and grafana/plugin-e2e live? plugin-tools repo?
- [ ] Make sure all selector values in (the decoupled) grafana/e2e-selectors package have a minimal Grafana version associated with it
- [ ] Rewrite our plugin examples so that they use grafana/plugin-e2e
- [ ] Come up with a strategy for how to deprecate grafana/e2e
```

**Comment by sunker** [comment]
I think this is mostly completed now. 
* [grafana/plugin-e2e](https://www.npmjs.com/package/@grafana/plugin-e2e?activeTab=versions) has been released to npm for a long time and it supports most scenarios that were outlined in [this](https://github.com/grafana/grafana/issues/77497) issue
* plugin-e2e docs and guidelines can be found [here](https://grafana.com/developers/plugin-tools/e2e-test-a-plugin/introduction)
* since [this](https://github.com/grafana/grafana/pull/84244) PR, scenario verification e2e tests are run for every PR in core Grafana
* grafana/e2e will be marked as deprecated as soon as we release 1.0.0 of plugin-e2e (very soon)

grafana/e2e-selectors have not been detached from Grafana release cycle yet, but I have created a separate [issue](https://github.com/grafana/grafana/issues/85061) to track that. 

For feature requests and/or bug reports related to plugin-e2e, please refer to the [plugin-tools](https://github.com/grafana/plugin-tools/) repo. Also see [this](https://github.com/grafana/plugin-tools/issues/796) epic where we track new ideas.
