### ISSUE TITLE
Design: UX Research for Sharing Modal options

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#77560]
```[tasklist]
### Tasks
- [x] Audit and analyze each part of the Sharing process
- [x] Identify essential parts for the sharing process
- [ ] https://github.com/grafana/grafana/issues/77703
- [x] Create user’s workflows current vs a proposal of a “happy path”
- [x] Investigate best ux practices to improve this process
- [x] Consolidate research findings
- [x] Share it with my Squad
```
