### ISSUE TITLE
EPIC: PromQAIL

### ISSUE THREAD

**Issue by bohandley** [grafana/grafana#77717]
PromQAIL Q3 

- [x] Win hackathon
- [x] build MVP
- [x] update with UI fixes
- [x] ML changes to hard code historical suggestions
- [x] build rudderstack feedback instrumnetation

Q4 work 

- [x] [Build more rudderstack feedback instrumentation](https://github.com/grafana/grafana/issues/77822)
- [x] ~~refactor/remove out historical suggestions~~ update language for non LLM suggested queries
- [x] small updates https://github.com/grafana/grafana/issues/77753
- [ ] Review feedback and provide either fixes or add known issues to docs
- [x] [set temperature](https://github.com/grafana/grafana/pull/77520)
- [x] [use metric type and if not def use heuristic](https://github.com/grafana/grafana/pull/77702)

Q1

- [ ] plan metric search
- [ ] move [query analysis](https://docs.google.com/spreadsheets/d/1M_GUyVtN5RTnjugyTUIlxvNkcE6hyhRJ8WcpChNeBOU/edit#gid=0) and historical suggestions into Query patterns
- [ ] Workflow to give suggestions when a query has been selected and "used"

**Comment by edwardcqian** [comment]
@bohandley Can we actually disable the feature if this check fails?

`const check = (await llms.openai.enabled()) && (await llms.vector.enabled());`

Currently historical suggestion works without passing this check but as we discussed, it's not really AI.

Even though we are not moving it out until v2 might be nice to just disable the feature when the check fails for now.

**Comment by bohandley** [comment]
@edwardcqian The historical logic will be completely removed!

I'll update the language to make this a clear removal
>  - [ ] refactor out historical suggestions

**Comment by edwardcqian** [comment]
Can we also make this a part of the milestone? (https://github.com/grafana/grafana/pull/77520)

**Comment by bohandley** [comment]
LLM-app provisioning updates for OSS

https://github.com/grafana/grafana-llm-app/pull/151#pullrequestreview-1730906422
The following provisioning file for the LLM-app has shown we need to populate the vectorDB with PromQL templates. With this file, building the plugin in your plugin directory, we get very close to OSS.

```
apiVersion: 1

# run qdrant docker with 
# docker run -p 6334:6334 qdrant/qdrant
apps:
  - type: grafana-llm-app
    jsonData:
      openAI:
        provider: openai
        url: https://api.openai.com
        organizationId: $OPENAI_ORG
      vector:
        enabled: true
        model: text-embedding-ada-002
        embed:
          type: openai
        store:
          type: qdrant
          qdrant:
            address: localhost:6334

    secureJsonData:
      openAIKey: $OPENAI_KEY
```

Next steps, populate the vectorDB with a script.

**Comment by ioanarm** [comment]
Hello @bohandley 👋 
In terms of populating data there is a script already in [vectorapi](https://github.com/grafana/vectorapi/blob/main/scripts/populate_db.py). This will only work for the vectorapi solution which should be our suggestion as well. For now it's test data but inside grafana org in huggingface there is already a dataset with [promql templates](https://huggingface.co/datasets/grafanalabs/promql-templates). We just need to make it public.

**Comment by bohandley** [comment]
- [LLM app docs](https://github.com/grafana/grafana-llm-app) with [vector DB](https://github.com/grafana/vectorapi)docs have been improved
  - [x] Brendan walked through and tested setting up everything locally
- [copy updates have been added](https://github.com/grafana/grafana/pull/77903)
- instrumentation has been added with [dashboard](https://ops.grafana-ops.net/d/a9fd60de-9417-4c60-8911-9ac605fd6c87/prometheus-query-advisor?orgId=1)

Improvements are being made by ML squad on the suggestions, this is a WIP

**Comment by bohandley** [comment]
Closing this as the work has been put on hiatus until LLM get better at handling the complexities of writing queries with all the resources available to specific Prometheus instances.
