### ISSUE TITLE
EPIC: Improve the plugin extensions DX

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#77856]
## The problem
When adding UI extension points in a plugin or in core Grafana, it is really painful to setup the environment so that you properly can test your new extension point. During development there are no extensions registered for the extension **point** under development. 

_(We have seen a couple of different ways to solve this. One option is to create a nested [dummy app plugin](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/app-with-extension-point/src) that register extensions for the new extension point. It is pretty straight forward but adds a lot of new files and unnecessary complexity to the plugin or Grafana repository. Another option is to mock or comment out the `getPluginExtensions*` function call and return dummy data. This is a way simpler but it is really hard to control in a CI environment if you e.g. would like to run tests.)_

## Goals
- **1) Have a way to easily test an extension point** under development (without changing existing code, mocking requests or needing to create dummy app plugins
- **2) Have a way to quickly try out extension ideas** and experiment without needing to spin up the whole environment (in order to lower bar for working with extensions)
- **3) Provide guidance on how to write tests** for UI extensions in your plugin

## Next steps
- [x] **1)** Get feedback regarding our suggested solution below from internal plugin devs on the Office hours meeting 
_(19th of March 2024)_
- [x] **2)** Adjust the list of tasks below according the feedback
- [ ] **3)** Allocate time (~1-3 weeks) for getting our proposed solution into a working and reviewable state
- [ ] **4)** Ship and track usage

```[tasklist]
### Sharing types between plugins
- [ ] [Add a draft title or issue reference here](https://github.com/grafana/grafana/issues/90171)
- [ ] Create a design doc based on the PoC and document the consensus
- [ ] Implement the proposed solution
- [ ] Work together with internal app plugins to implement the solution
```

```[tasklist]
### Extensions admin page
- [x] Create a [draft PR](https://github.com/grafana/grafana/pull/84157)
- [x] Create a [design doc](https://docs.google.com/document/d/110cODMrE5V6dpxmnLwGSpU0LY_XTyK2GopRDSwNtyrk/edit#heading=h.5sybau7waq2q)
- [ ] Figure out a reliable way to identify extensions
- [ ] Make it possible to update extensions that are already in the registry
- [ ] Make it possible to remove extensions from the registry on the fly
- [ ] Add a persistence layer on the client for test-extensions
- [ ] Add a way to enable / disable extensions
- [ ] Add a way to load test extensions on startup from the local persistance layer
- [ ] Add a way to rehidrate registry settings from the local persistance layer on startup
- [ ] Make the admin page only appear while in dev mode
- [ ] Make it possible to enable / disable extensions from the UI
- [ ] Make it possible to enable / disable extension points from the UI
- [ ] Make it possible to add / remove test extensions points from the UI
- [ ] Add an editor with correct syntax highlighting (possible types as well?)
```

```[tasklist]
### Plugin metadata
- [ ] https://github.com/grafana/grafana/issues/92005
- [ ] (consider) move extensions metadata to includes as a more logical place
- [ ] (consider) remove legacy angular component from includes (may cause confusion with UI Ext, need to check for issues resulting from its removal)
```

**Comment by tolzhabayev** [comment]
@leventebalogh could you rewrite this issue to reflect your suggestion (Admin Page https://github.com/grafana/grafana/pull/84157) and what we have discussed in the meeting today.

**Comment by leventebalogh** [comment]
(@tolzhabayev updated the PR description accordingly, please let me know if I have left out something.)

**Comment by tolzhabayev** [comment]
Closing for now as we have follow up EPIC and some of the things here are already a bit obsolete.
