### ISSUE TITLE
Simplify alert route routing

### ISSUE THREAD

**Issue by soniaAguilarPeiron** [grafana/grafana#77928]
Following the UX work done in https://github.com/grafana/gops-ux-team/issues/118, we want to provide a simplified way to link an alert rule directly to a contact point without without having to care about labels, matchers and policies.

As a first iteration, we want to offer users the option to directly select a contact point for sending alert rule instances.
This new option will be only available for **Grafana-managed alerts**.

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/77929
- [ ] https://github.com/grafana/grafana/issues/77930
- [ ] https://github.com/grafana/grafana/issues/77931
- [ ] https://github.com/grafana/grafana/issues/51494
- [ ] https://github.com/grafana/grafana/issues/79792
- [ ] https://github.com/grafana/grafana/issues/81405
- [ ] https://github.com/grafana/grafana/issues/80188
- [ ] https://github.com/grafana/grafana/issues/80189
- [ ] https://github.com/grafana/grafana/issues/84728
```

```[tasklist]
### Backend Tasks
- [x] https://github.com/grafana/grafana/pull/81672
- [x] https://github.com/grafana/grafana/pull/81751
- [ ] https://github.com/grafana/grafana/pull/81011
- [x] Update Alert Rule API to accept notification settings
- [x] Implement generation of routes based on notification settings
- [x] Make sure that user cannot interfere into auto-generate routes via API
- [x] Update provisioning API to support notification settings
- [x] Update file-provisioning to support notification settings in rules
- [ ] https://github.com/grafana/terraform-provider-grafana/pull/1407
- [ ] https://github.com/grafana/grafana/issues/82803
- [ ] https://github.com/grafana/grafana/issues/84073
```
