### ISSUE TITLE
Query Library: Team/Shared History requirements

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#77977]
Explore's query history background:
- Docs: https://grafana.com/docs/grafana/latest/explore/query-management/#query-history
- Before Grafana 9 query history was stored only in the browser storage. Users were unable to see the same query history in different browsers.
- With https://github.com/grafana/grafana/issues/44327 the history got migrated to backend. This way query history for all users is stored in single place enabling further improvements.
- All various documents related to past attempts can be found in https://docs.google.com/document/d/1BdVtoXCxhH0Q6C-O_Z7jKi-u1m5pDoS9_HQKhYu_hEE/edit

```[tasklist]
### Tasks
- [x] [Product DNA](https://docs.google.com/document/d/1c1vbHw9piV4_ve0XNC4sdRA0fp_kxv491BsFxep-5Lw/edit#heading=h.lo4c6e71q7vo)
- [x] UX
- [x] [Packaging / distribution model](https://docs.google.com/document/d/1kdvXy9-5PXqaEVt4OGdP6V7NxUrykhcWCYCwn_31U_g/edit#heading=h.i5lpjjnjul2s)
- [x] [Technical approach](https://docs.google.com/document/d/10TE71D0GFm8izZGy5YKBRMVjP1Yo2UyKCKwJxPclfi0/edit)
```

Final designs:

OSS:
[Latest Prototype](https://www.figma.com/proto/c0r4UCDSM0GGJaa5mFF77Y/Query-Library%3A-OSS?type=design&node-id=2893-16633&t=LePIjfRXNxYODeXK-0&scaling=scale-down&page-id=130%3A12007&starting-point-node-id=2893%3A16633&show-proto-sidebar=1) (Includes both Library and History flows.)
[Figma Files](https://www.figma.com/file/c0r4UCDSM0GGJaa5mFF77Y/Query-Library%3A-OSS?type=design&node-id=130-12007&mode=design&t=UBKG75UG9AFYkKXf-0) (The top file labeled 'Version 5.)

App Plugin:
[Latest Prototype](https://www.figma.com/proto/xW1hXGcTgqo8LnKmVFNK4Y/Query-Library%3A-App-Plugin?type=design&node-id=4465-28198&t=f1DWAUBA1gitizVc-0&scaling=min-zoom&page-id=130%3A12007&starting-point-node-id=4465%3A28198) (Features the full-page Library view with query variable creation flow.)
[Figma Files](https://www.figma.com/file/xW1hXGcTgqo8LnKmVFNK4Y/Query-Library%3A-App-Plugin?type=design&node-id=130-12007&mode=design&t=TxvskOHOhUWSsvw4-0) (The top file labeled 'Version 2.)
