### ISSUE TITLE
DataTrails: Epic 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#78037]
* [x] datatrails feature toggle 
* [x] Initial POC PR https://github.com/grafana/grafana/pull/77019 
* [ ] Remember last used data source and first label filter when creating new trail the second time 
* [ ] Implement storing bookmarks in local storage 
* [ ] Implement storing recent trails in local storage 
* [ ] Refine auto query and write tests for auto query logic (think it could good as the tests work as a way to document the logic) 

Ideas to discuss
* [ ] Make it possible to require some label filters? 
* [ ] limit breakdowns panel count?

**Comment by grafanabot** [comment]
@torkelo please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:
