### ISSUE TITLE
Epic: Scenes Panel Edit roadmap

### ISSUE THREAD

**Issue by kaydelaney** [grafana/grafana#78152]
Remaining issues:

- [ ] One can change visualization type
- [ ] One can edit Panel Options and Field Configuration
- [ ] One can edit Panel Queries
- [ ] One can add/remove Panel Queries
- [ ] One can edit Transformations
- [ ] One can add/remove Transformations

**Comment by natellium** [comment]
closing in favour of https://github.com/grafana/grafana/issues/78389
