### ISSUE TITLE
Design: Add search input

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#78313]
**Background / Why we're doing this**

Public dashboard list is being updated from table to be cards. Now, we want to add **pagination** and a **search bar** to align with other pages like "playlist".

Public dashboard list:
<img width="1504" alt="Screenshot 2023-11-17 at 10 50 02" src="https://github.com/grafana/grafana/assets/51436795/6f1c7649-4070-466b-944b-7092e0bbf435">

Playlist with search bar and pagination:
![screencapture-ops-grafana-ops-net-library-panels-2023-11-17-10_52_44](https://github.com/grafana/grafana/assets/51436795/bec9107a-937b-4b72-878f-e263a3ecf708)

**Tasks**

- [x] Add search bar
- [x] Add the pagination
- [x] Update the card component from our Saga Design System

**Comment by grafanabot** [comment]
@natydej please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:

**Comment by natydej** [comment]
This issue will be addressed when we update these designs -https://github.com/grafana/grafana/issues/82303

**Public dashboard page**
<img width="1440" alt="PublicDashboardPage" src="https://github.com/grafana/grafana/assets/51436795/9771a859-ba93-4b67-ba8f-f6f45f0e2719">

**Playlist page**
<img width="1440" alt="PlaylistPage" src="https://github.com/grafana/grafana/assets/51436795/0ac10b6c-0414-42d2-80fd-2c66a9952a76">
