### ISSUE TITLE
Dashboard Scenes M2: Feature complete dashboard edit and settings

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#78389]
Continuation of https://github.com/grafana/grafana/issues/73993

_Theme: Individual dashboard Scene objects can be modified. One can edit panel and all its options. One can edit queries and transformations. One can edit dashboard settings._

Respective feature toggles:
- `dashboardSceneForViewers` - Enables dashboard rendering using Scenes for viewer roles
- `dashboardSceneSolo` - Enables rendering dashboards using scenes for solo panels
- `dashboardScene` - Enables dashboard rendering using scenes for all roles

```[tasklist]
### General edit experience
- [ ] https://github.com/grafana/grafana/issues/81277
- [x] Changes are detected and save prompt is shown if needed
- [x] Keybindings are applied in the Dashboard
- [ ] https://github.com/grafana/grafana/issues/81447
- [ ] https://github.com/grafana/grafana/issues/82126
- [ ] https://github.com/grafana/grafana/issues/82422
- [x] https://github.com/grafana/grafana/pull/81958
- [ ] https://github.com/grafana/grafana/issues/82317
- [ ] https://github.com/grafana/grafana/issues/83382
- [ ] https://github.com/grafana/scenes/issues/537
- [x] [Be able to generate dashboard description, name and changes message with Dashgpt](https://github.com/grafana/grafana/pull/84649)
```

```[tasklist]
### Track: Dashboard Settings
- [x] Changes applied in Dashboard settings are reflected in Dashboard without the need for refresh
- [x] Be able to remove a dashboard from general settings
- [x] https://github.com/grafana/grafana/pull/78209
- [ ] https://github.com/grafana/grafana/pull/78789
- [ ] https://github.com/grafana/grafana/issues/78530
- [ ] https://github.com/grafana/grafana/issues/80025
- [ ] https://github.com/grafana/grafana/issues/80058
- [ ] https://github.com/grafana/grafana/issues/80064
- [ ] https://github.com/grafana/grafana/issues/81761
- [ ] https://github.com/grafana/grafana/issues/78690
- [ ] https://github.com/grafana/grafana/issues/80891
- [ ] https://github.com/grafana/grafana/issues/78754
```

```[tasklist]
### Track: Panel Edit
- [ ] https://github.com/grafana/grafana/pull/79130
- [ ] https://github.com/grafana/grafana/issues/78937
- [ ] https://github.com/grafana/grafana/issues/79266
- [ ] https://github.com/grafana/grafana/issues/80060
- [ ] https://github.com/grafana/grafana/issues/80809
- [x] [One can edit Field Configuration and Overrides](https://github.com/grafana/grafana/pull/81470)
- [ ] https://github.com/grafana/grafana/issues/81159
- [ ] https://github.com/grafana/grafana/issues/81559
- [x] [Panel Options, Field Config and Overrides are searchable](https://github.com/grafana/grafana/pull/81595)
- [x] [One can browse visualization suggestions](https://github.com/grafana/grafana/pull/82296)
- [ ] https://github.com/grafana/grafana/issues/82311
- [ ] https://github.com/grafana/grafana/issues/82416
- [ ] https://github.com/grafana/grafana/issues/82316
- [ ] https://github.com/grafana/grafana/issues/82462
- [ ] https://github.com/grafana/grafana/issues/83955
- [x] Library panels: Library panel can be added from the Empty dashboard page -> @mdvictor
- [x] Library panels: Respect panel repeat options
- [ ] https://github.com/grafana/grafana/issues/83961
- [ ] https://github.com/grafana/grafana/issues/83606
- [ ] https://github.com/grafana/grafana/issues/83891
- [ ] https://github.com/grafana/grafana/issues/84158
- [x] [Be able to generate panel name and description with Dashgpt](https://github.com/grafana/grafana/pull/84726)
- [ ] https://github.com/grafana/grafana/issues/83890
- [ ] https://github.com/grafana/grafana/issues/82347
```

**Comment by natellium** [comment]
Moved improvements beyond feature parity to https://github.com/grafana/grafana/issues/84834

**Comment by dprokop** [comment]
🥳 

[To be continued!](https://github.com/grafana/grafana/issues/83845)
