### ISSUE TITLE
DashboardScene: General dashboard settings are accessible and functional 

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#78530]
```[tasklist]
### Tasks
- [x] One can navigate to and from dashboard settings.
- [x] https://github.com/grafana/grafana/issues/78735
- [x] Support `nowDelay` as part of Dashboard settings
- [x] Support hidding time picker from settings
- [x] Settings button doesn't show when the dashboard is editing
- [x] The changes related to description, timerange, and refresh are not discarded with the current approach
- [x] Refreshing settings view, the dashboard exit of edit mode
```
