### ISSUE TITLE
DockedMegaMenu rollout

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#78637]
following the rollout plan [here](https://docs.google.com/spreadsheets/d/11Uhu90_WNL5VDnAGoeSXFfPkwId4OYtHTKdHSnwK58U/edit#gid=0)

```[tasklist]
### TODO
- [x] [Enable on staging and dev](https://github.com/grafana/deployment_tools/pull/106065)
- [x] [Smoke test on 50% free instances](https://github.com/grafana/deployment_tools/pull/109685)
- [x] [Rollout to 50% of free + pro instances](https://github.com/grafana/deployment_tools/pull/111453)
- [x] [Rollout to 50% of free + pro + contracted instances](https://github.com/grafana/deployment_tools/pull/114229)
- [x] [GA](https://github.com/grafana/deployment_tools/pull/117340)
```
