### ISSUE TITLE
Epic: [Nested folders] Displaying the 'Shared with me' folder

### ISSUE THREAD

**Issue by zsofiakm** [grafana/grafana#78752]
As part of the nested folders work, we are introducing a new pseudo-folder named 'Shared with me'. This folder is designed to display folders and dashboards that are directly shared with a user, which are currently not visible in the standard dashboards list. This epic captures the remaining work to finalize 'Shared with me' and therefore prepare nested folders General Availability.

Note: in order to rein in scope related to search, we are not going to include "shared with me" as a page. I ([@amy-super](https://github.com/amy-super)) edited the list below in response to that decision. I actually think this helps more clearly distinguish "shared with me" from a folder. We may even want to disable the checkbox as shown in this image.

![Frame 268](https://github.com/grafana/grafana/assets/87499219/a8e1cac9-3557-4993-b987-e6dc27791926)

Tasks in scope:

- [x] **[Backend]** SharedFolderUID is communicated to the frontend through the FrontendSettings struct
- [x] **[Frontend]** Apply a distinct icon to 'Shared with me'
- [x] **[Frontend]** Remove on-hover text decoration from 'Shared with me' text in folder tree view
- [x] **[Frontend]** 'Shared with me' folder sorted to the top of the list
- [x] #79456
- [x] **[Frontend]** 'Shared with me' and its contents should be returned by the folder picker.
- [x] **[Frontend]** 'Shared with me' cannot be selected in the folder picker.
- [x] **[Frontend]** 'Shared with me' should not be clickable and doesn't have a dedicated page. Users cannot jump into the folder.

Other functional requirements:
- 'Shared with me' as a folder name does not show up in the search results

Out of scope:
- Show 'Shared with me' in the command palette
- Show 'Shared with me' in the breadcrumbs

**Comment by joshhunt** [comment]
Fixed by https://github.com/grafana/grafana/pull/80141
