### ISSUE TITLE
Figma library improvements [epic]

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#78761]
Overhaul our designers' Figma component experience by doing:

- [ ] Variables
- [ ] Figma token implementation
- [x] Single component/pattern/template per file
- [x] Community file creation

```[tasklist]
### Key results
- [ ] https://github.com/grafana/grafana/issues/78768
- [ ] https://github.com/grafana/grafana/issues/78769
- [ ] https://github.com/grafana/grafana/issues/78814
- [ ] https://github.com/grafana/grafana/issues/78817
- [ ] https://github.com/grafana/grafana/issues/78833
- [ ] https://github.com/grafana/grafana/issues/78854
- [ ] https://github.com/grafana/grafana/issues/78856
- [ ] https://github.com/grafana/grafana/issues/78855
- [ ] https://github.com/grafana/grafana/issues/78818
- [ ] https://github.com/grafana/grafana/issues/78828
- [ ] https://github.com/grafana/grafana/issues/78829
- [ ] https://github.com/grafana/grafana/issues/78865
```
