### ISSUE TITLE
CloudWatch: Remove core grafana imports

### ISSUE THREAD

**Issue by kevinwcyu** [grafana/grafana#78778]
Remove core grafana imports from the frontend and backend. This issue pertains to following step 1 of this [document](https://docs.google.com/document/d/1Fh6NeI7mNQwmtzPMhawMnmHypWd_PD-ZJQ-bDseRy1g/edit#heading=h.hs0u7nbizdtv).

Tasks
- [x] Remove core grafana imports, there are 3 options mentioned in the document (please see the doc for full details). (1) Move code to a shared library. (2) Copy code to the plugin directory. (3) Migrate to existing SDK functionality.
  - How to replace certain dependencies for the [frontend](https://docs.google.com/document/d/1Fh6NeI7mNQwmtzPMhawMnmHypWd_PD-ZJQ-bDseRy1g/edit#heading=h.s3pve6b6zhdy)
    - [x] https://github.com/grafana/grafana/issues/79150
    - [x] https://github.com/grafana/grafana/issues/79114
    - [x] #79320
    - [x] #79321
    - [x] #80150
    - [x] #80152
    - [x] #80154
    - [x] #80148
    - [x] #80149
    - [x] #80151
    - [x] #80153
    - [x] #80155
    - There may be some imports that are not currently exposed in other packages. For these ones, if there isn't an obvious place for them, we can open up a ticket to keep track of it and discuss it in the Slack channel for decoupling core data sources. Otherwise if you discover a way to fix the issue, please share it in the How to decouple a data source document.
  - How to replace certain dependencies for the [backend](https://docs.google.com/document/d/1Fh6NeI7mNQwmtzPMhawMnmHypWd_PD-ZJQ-bDseRy1g/edit#heading=h.7yk89n2io2w9)
    - [x] #79323
    - [x] #80900
    - [x] #79324
    - [x] #80898
    - [x] #80899
    - [x] #80901
    - [x] #80902
    - [x] #80903
- [ ] Update this [section of the document](https://docs.google.com/document/d/1Fh6NeI7mNQwmtzPMhawMnmHypWd_PD-ZJQ-bDseRy1g/edit#heading=h.num9ff8ztalf) with CloudWatch specific notes

**Open multiple PRs if needed.**

The following is a list of restricted imports found by enabling the lint rule that detects imports from core grafana described in step 2 of the document

<details>
<summary>Backend restricted imports (updated on Jan 19th, 2024)</summary>

```sh
pkg/tsdb/cloudwatch/cloudwatch.go:23:2: import 'github.com/grafana/grafana/pkg/infra/httpclient' is not allowed from list 'coreplugins': Core plugins are not allowed to depend on Grafana core packages (depguard)
	"github.com/grafana/grafana/pkg/infra/httpclient"
	^
pkg/tsdb/cloudwatch/cloudwatch.go:24:2: import 'github.com/grafana/grafana/pkg/infra/log' is not allowed from list 'coreplugins': Core plugins are not allowed to depend on Grafana core packages (depguard)
	"github.com/grafana/grafana/pkg/infra/log"
	^
pkg/tsdb/cloudwatch/cloudwatch.go:25:2: import 'github.com/grafana/grafana/pkg/services/featuremgmt' is not allowed from list 'coreplugins': Core plugins are not allowed to depend on Grafana core packages (depguard)
	"github.com/grafana/grafana/pkg/services/featuremgmt"
	^
pkg/tsdb/cloudwatch/cloudwatch.go:26:2: import 'github.com/grafana/grafana/pkg/services/ngalert/models' is not allowed from list 'coreplugins': Core plugins are not allowed to depend on Grafana core packages (depguard)
	ngalertmodels "github.com/grafana/grafana/pkg/services/ngalert/models"
	^
pkg/tsdb/cloudwatch/cloudwatch.go:27:2: import 'github.com/grafana/grafana/pkg/services/query' is not allowed from list 'coreplugins': Core plugins are not allowed to depend on Grafana core packages (depguard)
	"github.com/grafana/grafana/pkg/services/query"
	^
pkg/tsdb/cloudwatch/cloudwatch.go:28:2: import 'github.com/grafana/grafana/pkg/setting' is not allowed from list 'coreplugins': Core plugins are not allowed to depend on Grafana core packages (depguard)
	"github.com/grafana/grafana/pkg/setting"
	^
pkg/tsdb/cloudwatch/get_dimension_values_for_wildcards.go:8:2: import 'github.com/grafana/grafana/pkg/infra/log' is not allowed from list 'coreplugins': Core plugins are not allowed to depend on Grafana core packages (depguard)
	"github.com/grafana/grafana/pkg/infra/log"
	^
pkg/tsdb/cloudwatch/get_metric_data_executor.go:9:2: import 'github.com/grafana/grafana/pkg/infra/metrics' is not allowed from list 'coreplugins': Core plugins are not allowed to depend on Grafana core packages (depguard)
	"github.com/grafana/grafana/pkg/infra/metrics"
	^
pkg/tsdb/cloudwatch/get_metric_query_batches.go:6:2: import 'github.com/grafana/grafana/pkg/infra/log' is not allowed from list 'coreplugins': Core plugins are not allowed to depend on Grafana core packages (depguard)
	"github.com/grafana/grafana/pkg/infra/log"
	^
pkg/tsdb/cloudwatch/log_actions.go:22:2: import 'github.com/grafana/grafana/pkg/services/featuremgmt' is not allowed from list 'coreplugins': Core plugins are not allowed to depend on Grafana core packages (depguard)
	"github.com/grafana/grafana/pkg/services/featuremgmt"
	^
pkg/tsdb/cloudwatch/resource_handler.go:13:2: import 'github.com/grafana/grafana/pkg/services/featuremgmt' is not allowed from list 'coreplugins': Core plugins are not allowed to depend on Grafana core packages (depguard)
	"github.com/grafana/grafana/pkg/services/featuremgmt"
	^
pkg/tsdb/cloudwatch/test_utils.go:19:2: import 'github.com/grafana/grafana/pkg/setting' is not allowed from list 'coreplugins': Core plugins are not allowed to depend on Grafana core packages (depguard)
	"github.com/grafana/grafana/pkg/setting"
	^
pkg/tsdb/cloudwatch/cloudwatch_integration_test.go:20:2: import 'github.com/grafana/grafana/pkg/setting' is not allowed from list 'coreplugins': Core plugins are not allowed to depend on Grafana core packages (depguard)
	"github.com/grafana/grafana/pkg/setting"
	^
pkg/tsdb/cloudwatch/cloudwatch_test.go:18:2: import 'github.com/grafana/grafana/pkg/infra/httpclient' is not allowed from list 'coreplugins': Core plugins are not allowed to depend on Grafana core packages (depguard)
	"github.com/grafana/grafana/pkg/infra/httpclient"
	^
pkg/tsdb/cloudwatch/get_dimension_values_for_wildcards_test.go:10:2: import 'github.com/grafana/grafana/pkg/infra/log/logtest' is not allowed from list 'coreplugins': Core plugins are not allowed to depend on Grafana core packages (depguard)
	"github.com/grafana/grafana/pkg/infra/log/logtest"
	^
pkg/tsdb/cloudwatch/get_metric_query_batches_test.go:6:2: import 'github.com/grafana/grafana/pkg/infra/log/logtest' is not allowed from list 'coreplugins': Core plugins are not allowed to depend on Grafana core packages (depguard)
	"github.com/grafana/grafana/pkg/infra/log/logtest"
	^
pkg/tsdb/cloudwatch/log_sync_query_test.go:20:2: import 'github.com/grafana/grafana/pkg/services/ngalert/models' is not allowed from list 'coreplugins': Core plugins are not allowed to depend on Grafana core packages (depguard)
	ngalertmodels "github.com/grafana/grafana/pkg/services/ngalert/models"
	^
pkg/tsdb/cloudwatch/log_sync_query_test.go:21:2: import 'github.com/grafana/grafana/pkg/services/query' is not allowed from list 'coreplugins': Core plugins are not allowed to depend on Grafana core packages (depguard)
	"github.com/grafana/grafana/pkg/services/query"
	^
pkg/tsdb/cloudwatch/clients/metrics.go:8:2: import 'github.com/grafana/grafana/pkg/infra/metrics' is not allowed from list 'coreplugins': Core plugins are not allowed to depend on Grafana core packages (depguard)
	"github.com/grafana/grafana/pkg/infra/metrics"
	^
pkg/tsdb/cloudwatch/models/cloudwatch_query_test.go:17:2: import 'github.com/grafana/grafana/pkg/infra/log/logtest' is not allowed from list 'coreplugins': Core plugins are not allowed to depend on Grafana core packages (depguard)
	"github.com/grafana/grafana/pkg/infra/log/logtest"
	^
```

</details>

<details>
<summary>Frontend restricted imports</summary>

```sh
/grafana/public/app/plugins/datasource/cloudwatch/__mocks__/AnnotationQueryRunner.ts
  4:29  error  Unexpected path "app/features/templating/template_srv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths

/grafana/public/app/plugins/datasource/cloudwatch/__mocks__/CloudWatchDataSource.ts
  12:28  error  Unexpected path "app/features/dashboard/services/TimeSrv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths
  13:29  error  Unexpected path "app/features/templating/template_srv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages     import/no-restricted-paths
  14:49  error  Unexpected path "app/features/variables/custom/reducer" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages    import/no-restricted-paths

/grafana/public/app/plugins/datasource/cloudwatch/__mocks__/LogsQueryRunner.ts
  5:37  error  Unexpected path "app/features/dashboard/services/TimeSrv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths
  6:29  error  Unexpected path "app/features/templating/template_srv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages     import/no-restricted-paths

/grafana/public/app/plugins/datasource/cloudwatch/__mocks__/MetricsQueryRunner.ts
  5:29  error  Unexpected path "app/features/templating/template_srv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths

/grafana/public/app/plugins/datasource/cloudwatch/__mocks__/ResourcesAPI.ts
  2:28  error  Unexpected path "app/features/dashboard/services/TimeSrv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths
  3:29  error  Unexpected path "app/features/templating/template_srv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages     import/no-restricted-paths
  4:37  error  Unexpected path "app/features/variables/types" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages             import/no-restricted-paths

/grafana/public/app/plugins/datasource/cloudwatch/components/ConfigEditor/ConfigEditor.test.tsx
  9:32  error  Unexpected path "app/store/configureStore" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths

/grafana/public/app/plugins/datasource/cloudwatch/components/ConfigEditor/ConfigEditor.tsx
  16:27  error  Unexpected path "app/core/actions" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages                     import/no-restricted-paths
  17:24  error  Unexpected path "app/core/config" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages                      import/no-restricted-paths
  18:43  error  Unexpected path "app/core/copy/appNotification" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages        import/no-restricted-paths
  19:34  error  Unexpected path "app/features/plugins/datasource_srv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths
  20:23  error  Unexpected path "app/store/store" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages                      import/no-restricted-paths

/grafana/public/app/plugins/datasource/cloudwatch/components/ConfigEditor/XrayLinkConfig.tsx
  7:34  error  Unexpected path "app/features/datasources/components/picker/DataSourcePicker" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths
  8:34  error  Unexpected path "app/features/plugins/datasource_srv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages                          import/no-restricted-paths

/grafana/public/app/plugins/datasource/cloudwatch/components/QueryEditor/MetricsQueryEditor/MetricsQueryEditor.test.tsx
   7:25  error  Unexpected path "app/features/dashboard/services/TimeSrv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages     import/no-restricted-paths
   8:29  error  Unexpected path "app/features/templating/template_srv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages        import/no-restricted-paths
  10:64  error  Unexpected path "../../../../../../features/variables/types" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths

/grafana/public/app/plugins/datasource/cloudwatch/components/shared/LogGroups/LegacyLogGroupSelector.tsx
  7:27  error  Unexpected path "app/core/actions" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages               import/no-restricted-paths
  8:41  error  Unexpected path "app/core/copy/appNotification" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths
  9:26  error  Unexpected path "app/store/store" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages                import/no-restricted-paths

/grafana/public/app/plugins/datasource/cloudwatch/datasource.ts
  17:37  error  Unexpected path "app/features/dashboard/services/TimeSrv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths
  18:45  error  Unexpected path "app/features/templating/template_srv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages     import/no-restricted-paths

/grafana/public/app/plugins/datasource/cloudwatch/language/cloudwatch-logs/CloudWatchLogsLanguageProvider.ts
  7:32  error  Unexpected path "app/features/templating/template_srv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths

/grafana/public/app/plugins/datasource/cloudwatch/language/cloudwatch-sql/SQLGenerator.test.ts
  1:29  error  Unexpected path "app/features/templating/template_srv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths

/grafana/public/app/plugins/datasource/cloudwatch/language/cloudwatch-sql/SQLGenerator.ts
  1:45  error  Unexpected path "app/features/templating/template_srv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths

/grafana/public/app/plugins/datasource/cloudwatch/migrations/dashboardMigrations.ts
  6:34  error  Unexpected path "app/core/utils/query" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths

/grafana/public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchAnnotationQueryRunner.ts
  4:29  error  Unexpected path "app/features/templating/template_srv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths

/grafana/public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.test.ts
  13:28  error  Unexpected path "app/features/dashboard/services/TimeSrv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths

/grafana/public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchLogsQueryRunner.ts
  34:25  error  Unexpected path "app/features/dashboard/services/TimeSrv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths
  35:29  error  Unexpected path "app/features/templating/template_srv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages     import/no-restricted-paths

/grafana/public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchMetricsQueryRunner.test.ts
  6:43  error  Unexpected path "app/features/variables/types" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths
  7:24  error  Unexpected path "app/store/store" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages               import/no-restricted-paths

/grafana/public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchMetricsQueryRunner.ts
  16:27  error  Unexpected path "app/core/actions" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages                      import/no-restricted-paths
  17:41  error  Unexpected path "app/core/copy/appNotification" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages         import/no-restricted-paths
  18:29  error  Unexpected path "app/features/templating/template_srv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths
  19:23  error  Unexpected path "app/store/store" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages                       import/no-restricted-paths
  20:40  error  Unexpected path "app/types" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages                             import/no-restricted-paths

/grafana/public/app/plugins/datasource/cloudwatch/query-runner/CloudWatchRequest.ts
  12:27  error  Unexpected path "app/core/actions" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages                      import/no-restricted-paths
  13:41  error  Unexpected path "app/core/copy/appNotification" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages         import/no-restricted-paths
  14:29  error  Unexpected path "app/features/templating/template_srv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths
  15:23  error  Unexpected path "app/store/store" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages                       import/no-restricted-paths
  16:40  error  Unexpected path "app/types" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages                             import/no-restricted-paths

/grafana/public/app/plugins/datasource/cloudwatch/resources/ResourcesAPI.ts
  5:29  error  Unexpected path "app/features/templating/template_srv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths

/grafana/public/app/plugins/datasource/cloudwatch/utils/datalinks.test.ts
  3:31  error  Unexpected path "app/features/plugins/datasource_srv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths

/grafana/public/app/plugins/datasource/cloudwatch/utils/templateVariableUtils.ts
  2:29  error  Unexpected path "app/features/templating/template_srv" imported in restricted zone. Core plugins are not allowed to depend on Grafana core packages  import/no-restricted-paths
```
