### ISSUE TITLE
New iconography file

### ISSUE THREAD

**Issue by Aires-Grafana** [grafana/grafana#78814]
A **new Iconography file** is created, leveraging the existing/current icons from the product, and all the needed sizes. Icon labels in Figma will be improved to enhance discoverability within our design libraries.
```[tasklist]
### Tasks
- [x] New Iconography file created
- [x] Select current/needed icons to the new library
- [x] Started exploration with new icon wrapper approach
- [x] Publish the new iconography library in Figma
- [x] Improve Icons labels in Figma to enhance discoverability
```

**Comment by Aires-Grafana** [comment]
A new [Iconography file](https://www.figma.com/file/nYiVUfeDEB1HNj0oLIczDZ/Saga-Iconography?type=design&node-id=0%3A1&mode=design&t=hUeMgwkdiZe9e9OE-1) was created.

**Comment by Aires-Grafana** [comment]
The foundational file was created with a new structure and new icons added.
It was defined as the v1.0.0 for the Iconography in the new Figma structure. More info on the [changelog](https://www.figma.com/file/nYiVUfeDEB1HNj0oLIczDZ/Saga-Iconography?type=design&node-id=2201-159&mode=design) page.
