### ISSUE TITLE
New logos file

### ISSUE THREAD

**Issue by Aires-Grafana** [grafana/grafana#78817]
A **new "Logos" file** is created, leveraging the existing/current and needed logos from the product.
```[tasklist]
### Tasks
- [x] New Logos file created
- [x] Select current/needed logos for the new library
- [x] Publish the new Logos library in Figma
- [x] Update logo names and synonyms to improve discoverability within Figma
```

**Comment by Aires-Grafana** [comment]
A new [Logos file](https://www.figma.com/file/liguCd0ZHSSSfs4Zq7UXnO/Saga-Logos?type=design&node-id=0%3A1&mode=design&t=joSfMBzAJBZDUgct-1) was created.

**Comment by Aires-Grafana** [comment]
The foundational file was created with a new structure and new logos added.
It was defined as v1.0.0 for the Logos library file in the new Figma structure. More info on the [changelog](https://www.figma.com/file/liguCd0ZHSSSfs4Zq7UXnO/Saga-Logos?type=design&node-id=2201-159&mode=design) page.
