### ISSUE TITLE
Create Iconography Tokens

### ISSUE THREAD

**Issue by Aires-Grafana** [grafana/grafana#78872]
According to the [**New Iconography Foundations**](https://www.figma.com/file/nYiVUfeDEB1HNj0oLIczDZ/Saga-Iconography?type=design&mode=design&t=zRDzUoPHjSP2ijfG-1) library, finished and available in the new Saga PoC team, create the needed design tokens using Token Studio in their respective levels/tiers, and sync them with Figma Variables and existent Figma Styles.

```[tasklist]
### Tasks
- [ ] Create Core level Design tokens
- [ ] Create Semantic level Design tokens in Token Studio
- [ ] Sync Design Tokens with Figma Variables (if applicable)
- [ ] Publish Iconography library with new Design Tokens applied
- [ ] Push Design Tokens to the repo (repo: "grafana/design-system", branch: "SagaTokens_v1.0")
```
