### ISSUE TITLE
Docs: Restructure other panel and visualizations pages

### ISSUE THREAD

**Issue by imatwawana** [grafana/grafana#78931]
Complete a page-level restructuring of these docs as required as part of ease of use goals; improve clarity and flow of these pages so that users can more easily find the information they're looking for. Hidden sections will be added so that missing content can be filled in at a later date.

```[tasklist]
### Tasks
- [ ] [Panel editor overview](https://grafana.com/docs/grafana/next/panels-visualizations/panel-editor-overview/)
- [ ] [The panel inspect view](https://grafana.com/docs/grafana/next/panels-visualizations/panel-inspector/)
- [ ] [Query and transform data](https://grafana.com/docs/grafana/next/panels-visualizations/query-transform-data/)
- [ ] [Write expression queries](https://grafana.com/docs/grafana/next/panels-visualizations/query-transform-data/expression-queries/)
- [ ] [Share query results](https://grafana.com/docs/grafana/next/panels-visualizations/query-transform-data/share-query/)
- [ ] [Transform data](https://grafana.com/docs/grafana/next/panels-visualizations/query-transform-data/transform-data/)
- [ ] [Troubleshoot queries](https://grafana.com/docs/grafana/next/panels-visualizations/query-transform-data/troubleshoot-queries/)
- [ ] [Calculation types](https://grafana.com/docs/grafana/next/panels-visualizations/query-transform-data/calculation-types/)
```
