### ISSUE TITLE
DashboardScene: Panel visualization type can be changed

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#78937]
```[tasklist]
### Tasks
- [x] [Implement basic infrastructure for panel type change](https://github.com/grafana/grafana/pull/78477)
- [x] Applying viz type change in panel edit is reflected in the dashboard
- [x] Implement UI for viz picker that matches old panel edit experience
```

**Comment by grafanabot** [comment]
@dprokop please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:
