### ISSUE TITLE
Epic: GG Grafana Hackathon

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#78984]
Epic to organize work for the GG Grafana hackathon

See [WIP PR for reference](https://github.com/grafana/grafana/pull/79048)

```[tasklist]
### Achievement service
- [x] Figure out user account persistence
- [x] Achievements service POC - set up logic to capture events and process logic
- [x] Figure out shape of achievement / "levels" - for now this can just be hard coded object
- [ ] https://github.com/grafana/grafana/issues/79034
- [ ] https://github.com/grafana/grafana/issues/79035
- [ ] https://github.com/grafana/grafana/issues/79036
- [ ] https://github.com/grafana/grafana/issues/79119
- [ ] Stretch: Figure out how to update "external" users to fix demo (ephemeral instance)
```

```[tasklist]
### UI
- [x] Create stubbed achievements page in profile
- [x] Create achievement header section
- [x] Create achievement page level header component (with progress?)
- [x] Create component to list out achievement
- [x] Component for menu bar to show progress / current level https://github.com/grafana/grafana/pull/79088
- [ ] https://github.com/grafana/grafana/issues/79185
- [ ] https://github.com/grafana/grafana/issues/79186
- [ ] https://github.com/grafana/grafana/issues/79160
- [ ] https://github.com/grafana/grafana/issues/79190
- [x] Grot assets for each level (either from excalidraw or a mix from current grot svgs https://raintank-corp.slack.com/archives/C068D6CBT9N/p1701712348000799
- [ ] Stretch: maybe make achievements modal mode for better in context achieving
```

**Comment by nmarrs** [comment]
Closing this out as hackathon is now over :)
