### ISSUE TITLE
One can edit panel data source and query options

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#79266]
```[tasklist]
### Tasks
- [x] [Refactor datasource picker and query options components so that they can be used in scenes architecture](https://github.com/grafana/grafana/pull/79267)
- [x] [Allow query options edit](https://github.com/grafana/grafana/pull/79267)
- [x] [Allow data source change](https://github.com/grafana/grafana/pull/79267)
- [x] [Handle changing data source for panels with transformations](https://github.com/grafana/grafana/pull/79267)
- [x] [Handle Dashboard data source](https://github.com/grafana/grafana/pull/79991)
- [x] Handle Mixed data source
```
