### ISSUE TITLE
UHG a11y audit issues

### ISSUE THREAD

**Issue by ckbedwell** [grafana/grafana#79637]
```[tasklist]
### Critical Impact issues
- [ ] https://github.com/grafana/grafana/issues/79627
- [ ] https://github.com/grafana/grafana/issues/79628
```

```[tasklist]
### High Impact issues
- [ ] https://github.com/grafana/grafana/issues/55797
- [ ] https://github.com/grafana/grafana/issues/66471
- [ ] https://github.com/grafana/grafana/issues/73396
- [ ] https://github.com/grafana/grafana/issues/73693
- [ ] https://github.com/grafana/grafana/issues/74841
- [ ] https://github.com/grafana/grafana/issues/79513
- [ ] https://github.com/grafana/grafana/issues/79517
- [ ] https://github.com/grafana/grafana/issues/79571
- [ ] https://github.com/grafana/grafana/issues/79573
- [ ] https://github.com/grafana/grafana/issues/79585
- [ ] https://github.com/grafana/grafana/issues/79630
- [ ] https://github.com/grafana/grafana/issues/79636
- [ ] https://github.com/grafana/grafana/pull/68065
```

```[tasklist]
### Medium Impact issues
- [ ] https://github.com/grafana/grafana/issues/79521
```

```[tasklist]
### Low Impact issues
- [ ] https://github.com/grafana/grafana/issues/79514
- [ ] https://github.com/grafana/grafana/issues/79516
```

**Comment by taleena** [comment]
Closing this as most of the linked issues are done and these can be found again by searching for the "UAS" label.
