### ISSUE TITLE
One can view and manipulate dashboard version history

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#80058]
The existing Dashboard scene settings views are created here: https://github.com/grafana/grafana/blob/main/public/app/features/dashboard-scene/settings/utils.ts#L64

```[tasklist]
### Tasks
- [x] [One can navigate to Dashboard Settings/Versions tab](https://github.com/grafana/grafana/pull/80190)
- [x] [A list of dashboard versions is fetched and rendered](https://github.com/grafana/grafana/pull/80229)
- [x] [Two versions from the list can be selected and compared](https://github.com/grafana/grafana/pull/80286)
- [x] [Selected version can be restored](https://github.com/grafana/grafana/pull/80600)
```

In general, we try to reuse as many components as possible, so we will try to reuse the existing views.

**Comment by grafanabot** [comment]
@dprokop please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:
