### ISSUE TITLE
EPIC: Improve Plugins Catalogue search function

### ISSUE THREAD

**Issue by academo** [grafana/grafana#80056]
**Why?**
Improve discoverability of plugins in our catalog.

We know that search is the #1 preferred mechanism for users to find the appropriate plugin, adding keywords would be a quick win to improve the results. Gives plugin authors greater control over how their plugin is discovered by users (related request from partners)

**What search are we talking about?**
- Integrated search in [grafana instances](https://play.grafana.org/plugins?filterBy=installed&filterByType=all&q=bigquery)
<img width="914" alt="Screenshot 2024-01-05 at 14 26 42" src="https://github.com/grafana/grafana/assets/580672/0358ed83-5405-4009-9059-e39b4a8f7101">

- Search on [grafana.com](https://grafana.com/grafana/plugins/all-plugins/?search=bigquery) 
<img width="1266" alt="Screenshot 2024-01-05 at 14 26 48" src="https://github.com/grafana/grafana/assets/580672/5b9ad8d5-014f-4689-9afe-eea4f29b97ae">

**What is out of scope?**
- Search in connections console (should follow up afterwards / separate story).

**What areas do we want to explore / add to the current search capabilities?**
- Support searching for `keywords` that are provided by plugin authors in `plugin.json` file (`info`.`keywords`)
   -  Example https://grafana.com/api/plugins/grafana-bigquery-datasource
   - This might require adjustments to GCOM API to provide this information in the [main plugin list api](https://grafana.com/api/plugins)
- Fuzzy search in both `name` and `description` fields
- Fuzzy search for `orgName`

**What do we want to measure (if feasible of course)**
- Returned search results counts
- Click through rate (CTR) - how many click on a search result

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/80711
- [ ] https://github.com/grafana/grafana/issues/80699
- [ ] https://github.com/grafana/grafana/issues/81454
- [ ] https://github.com/grafana/website/pull/18481
- [ ] https://github.com/grafana/grafana/issues/83887
- [ ] https://github.com/grafana/website/pull/18805
- [ ] Add to cloud whats new (with video)
```
