### ISSUE TITLE
One can view and edit Dashboard JSON

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#80064]
The existing Dashboard scene settings views are created here: https://github.com/grafana/grafana/blob/main/public/app/features/dashboard-scene/settings/utils.ts#L64

```[tasklist]
### Tasks
- [x] One can navigate to Dashboard Settings/Dashboard JSON tab
- [x] A dashboard JSON monaco editor is shown in the tab. The JSON shown is a result of the `transformSceneToSaveModel` call
- [x] Changes made to the dashboard JSON can be saved.
```

Saving changes to the dashboard JSON may be non-trivial. We do a similar thing with panel JSON inspection (https://github.com/grafana/grafana/blob/main/public/app/features/dashboard-scene/inspect/InspectJsonTab.tsx#L101) - after applying changes the entire state of the panel is replaced with a new panel. In case of modifying the dasboard JSON we will have to create a new dashboard scene from the updated json (`transformSaveModelToScene`) and update the original scene's state with the updated one. 

In general, we try to reuse as many components as possible, so we will try to reuse the existing views.

**Comment by grafanabot** [comment]
@dprokop please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:
