### ISSUE TITLE
One can add and remove Transformations

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#80060]
The basics of the Transformations tab is implemented in https://github.com/grafana/grafana/blob/main/public/app/features/dashboard-scene/panel-edit/PanelDataPane/PanelDataTransformationsTab.tsx#L12.

```[tasklist]
### Tasks
- [x] When no transformations are defined for a panel, empty Transformations list state is shown
- [x] When a panel has transformations defined, those are rendered in the Transformations tab
- [x] Individual transformation can be disabled, debugged and deleted.
- [x] A new transformation can be added
- [x] Individual transformations can be edited.
- [x] Change order of transformations
- [x] Transformations are applied to the panel when navigating back to a dashboard
```

In general, we try to reuse as many components as possible, so we will try to reuse the existing views

**Comment by grafanabot** [comment]
@dprokop please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:

**Comment by oscarkilhed** [comment]
PR for viewing transformations: https://github.com/grafana/grafana/pull/80372

**Comment by oscarkilhed** [comment]
PR for adding, editing, removing transformations: #80738
