### ISSUE TITLE
Dashboard URL variables: clarify intent of 

### ISSUE THREAD

**Issue by imatwawana** [grafana/grafana#80249]
The intent of this page needs to be made clearer along with other minor fixes.

### Tasks
- [x] Fix missing link in intro
- [x] Change headings to non-gerund version of the verb
- [x] Clarify if this is telling you how to add variables to a dashboard URL or if you create dashboard URLs while there variables are in context, then this is how they'll be represented (maybe both?)
