### ISSUE TITLE
Sharing: Improve structure

### ISSUE THREAD

**Issue by imatwawana** [grafana/grafana#80257]
﻿﻿﻿﻿﻿This page doesn't cover all of the sharing options available and has a structure that's doesn't lend itself to a user trying to only share a panel OR a dashboard. 

### Tasks

- [ ] Add missing sharing options
- [ ] Remove the expression “On the Web"
- [ ] Move information about permissions required for seeing images rendered by a link from intro into sections about each sharing type 
- [ ] Make the bullet list at the top of the page align with the page structure
- [ ] Remove tasks under **Share a dashboard** and **Share a panel** and repeat those steps under under each of the sharing types instead
- [ ] **Share public dashboard** is missing - this should at least link out to the Public dashboard docs; should probably be nested under Share a dashboard (don’t think you can share just a Public panel right?)

**Share a dashboard**
- [ ] **Share a direct link** should be **Share a direct dashboard link**
- [ ] **Publish a snapshot** should be **Publish a dashboard snapshot**
- [ ] **Dashboard export** should be renamed **Export dashboard as JSON** or something more descriptive
- [ ] **Export dashboard as PDF** should be nested under **Share a dashboard**
- [ ] **Create report from dashboard** is missing - this should at least link out to the public dashboard docs

**Share a panel**
- [ ] **Use a direct link** should be **Share a direct panel link**
- [ ] **Publish a snapshot** should be **Publish a panel snapshot**
- [ ] Remove **Library panel**

**Comment by imatwawana** [comment]
Completed as part of redesigned sharing feature
