### ISSUE TITLE
Inspect variables: Fix content/title mismatch

### ISSUE THREAD

**Issue by imatwawana** [grafana/grafana#80254]
The **Inspect variables** page describes actions you can take on the main Variables page in the UI so the rest of the actions you can take on that page should live here as well. Then the title of the page should be updated to be reflect that it's about variables management.

### Tasks
- [x] Change page title to **Manage and inspect variables**
- [x] Add management content from **Add and manage variables** to this page
- [x] Clarify the term "inspect". Is this industry standard or just something we came up with?

**Comment by imatwawana** [comment]
Addressed on [PR 87844 - Docs: Rename variables pages](https://github.com/grafana/grafana/pull/87844)
