### ISSUE TITLE
Reporting: Improve structure and clarity

### ISSUE THREAD

**Issue by imatwawana** [grafana/grafana#80259]
This page is very long and needs to either be broken down into some child pages or at least restructured (some proposals for restructuring are described and shown below, but this hasn't been decided yet). There are also a number of features that have been added to this page over time, but without being rolled into the tasks a user is already performing in creating a report and these need to be merged with the existing content.

### Tasks

- [x] Restructure page (possible approach)
  - **Save as draft** - part of step 7 with Send report being the other option or the whole of step 7
  - **Pause a report** - should be its own H2
  - **Add multiple dashboards** - should just be part of the steps
  - **Embed a dashboard** - should just be part of steps
  - **Export dashboards as PDF** - is just what this feature is and doesn't belong as a step on its own
  - **Send report via API** and **Rendering configuration** are very specific settings that maybe don't belong in this section
- [x] Remove link to blog post
- [ ] Ensure that **Requirements** section applies to both self-managed and Cloud or clarify which it applies to
- [x] Fix broken link under **Access control** section and remove repetition; section repeats what's in the note at the top of the page

**Create or update a report**
- [x] Clarify if you can you control who can create a report without RBAC in Cloud
- [x] Add missing **Zoom** setting under PDF formatting
- [x] Add missing **Time** setting that controls whether it sends now or later; all frequency options except Never have this setting
- [x] Make **Send test email** a separate optional step isn't a setting in the body of the page; add that the option doesn't appear until you enter at least an email address
- [ ] ~~Add that most steps are at the bottom of the page while the last step is at the top~~
- [x] Rename **Preview**; this term could lead users to think they’ll see an actual preview when they’re actually getting a confirmation page (the UI calls the step Confirm)
- [x] Remove version notes from prior to version 8.0
- [x] Update **Report settings** to **Reporting settings** because they're global and not specific to any one report
- [ ] Clarify that **Troubleshoot reporting** is self-managed specific or make it more Cloud friendly; or is this a use case for a different page for Cloud users?

<img width="612" alt="image" src="https://github.com/grafana/grafana/assets/76437239/93d480e4-a4c3-48f1-8047-6bff8f0b9804">
