### ISSUE TITLE
Theme - Tokens [epic]

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#80673]
To support future changes to Grafana's themes, improve new Grafanaista onboarding, and reduce the need for tribal knowledge around themes within Grafana, we are going to provide an end-to-end token structure. 
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/78865
- [ ] https://github.com/grafana/grafana/issues/78866
- [ ] https://github.com/grafana/grafana/issues/78869
- [ ] https://github.com/grafana/grafana/issues/78870
- [ ] https://github.com/grafana/grafana/issues/78871
- [ ] https://github.com/grafana/grafana/issues/78872
- [ ] https://github.com/grafana/grafana/issues/78873
- [ ] https://github.com/grafana/grafana/issues/69184
- [ ] Create a Saga Dark theme
- [ ] Create a Saga Light theme
```
