### ISSUE TITLE
One can view, define and edit Annotation queries

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#80891]
```[tasklist]
### Tasks
- [x] One can navigate to Dashboard Settings/Annotations tab
- [x] A list of annotation queries is shown
- [x] One can re-arange annotation queries
- [x] One can add new annotations query
- [x] One can remove existing annotations query
- [x] One can edit existing annotations query
```
