### ISSUE TITLE
Q1  🪵 goals

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#80907]
## Q1 goals

- [x]  `feature` Infinite scroll for logs https://github.com/grafana/grafana/issues/71728 @matyax 
- [ ] `feature` Table View: Wrap up, release, document, etc. https://github.com/grafana/grafana/issues/77469
- [x] `Grafana 11` Any deprecations we want to mark for G11? Any existing deprecations to remove? Any breaking changes to introduce?

**Comment by matyax** [comment]
Completed.
