### ISSUE TITLE
Epic: DataViz Angular Deprecation

### ISSUE THREAD

**Issue by jennyfana** [grafana/grafana#80983]
An Epic to manage all of the work for Angular Deprecation in DataViz

```[tasklist]
### Analysis and Planning
- [x] Create Dashboard (BigQuery) showing usage of panels
- [x] Agree Scope
- [x] Plan AutoMigration
- [x] Plan Customer Communication
```

```[tasklist]
### Auto Migration
- [ ] https://github.com/grafana/grafana/pull/79369
- [ ] https://github.com/grafana/grafana/pull/84100
```

```[tasklist]
### Forced Migration
- [ ] Add a draft title or issue reference here
```

```[tasklist]
### Graph to Timeseries
- [ ] https://github.com/grafana/grafana/issues/49670
```

```[tasklist]
### Graph to Bar Chart
- [x] X Axis Mode - resembles Bar Gauge
```

```[tasklist]
### Graph to Histogram
- [ ] https://github.com/grafana/grafana/pull/80990
- [x] Stacking
- [ ] https://github.com/grafana/grafana/pull/84693
```

```[tasklist]
### WorldMap to GeoMap
- [ ] https://github.com/grafana/grafana/issues/64057
```

```[tasklist]
### Old Table to Table
- [ ] https://github.com/grafana/grafana/issues/70095
- [ ] Row Formatting
- [ ] Variable Row Height
```

**Comment by jennyfana** [comment]
I am removing Flow Chart from the Scope of the Overall Deprecation work.

**Comment by akenverus** [comment]
Since AngularJS is deprecated, wouldn't it be easier to migrate to Angular, instead of React, since Angular has quite a bunch of tools for smooth, almost automatic migration?
