### ISSUE TITLE
Content Outline v3

### ISSUE THREAD

**Issue by harisrozajac** [grafana/grafana#81101]
```[tasklist]
### General
- [ ] https://github.com/grafana/grafana/issues/79799
- [x] Replace the Expand icon - #79799
- [x] Remove the word "Collapse outline" - part of #79799
- [x] Truncate text in nav if the word exceeds the 160 px width - part of #79799
```

```[tasklist]
### Logs
- [x] Log filtering - #86431
```
