### ISSUE TITLE
Forms: Remove Form, InputControl and FieldArray appearances in Grafana

### ISSUE THREAD

**Issue by Clarity-89** [grafana/grafana#81226]
Usage of `Form`, `InputControl` and `FieldArray` components from grafana/ui has been deprecated and they should be replaced inside Grafana with react-hook-form's components and hooks. 

- `Form` should be replaced with the [Form component from core](https://github.com/grafana/grafana/tree/main/public/app/core/components/Form) a native HTML `form` and the methods of the `useForm` hook should be used instead.
- `InputControl` should be replaced with the `Controller` component from react-hook-form.
- `FieldArray` should be replaced with the methods from the `useFieldArray` hook. 
 
List of files:

- [x] public/app/core/components/AccessControl/AddPermission.tsx https://github.com/grafana/grafana/pull/81261
- [x] public/app/core/components/ForgottenPassword/ChangePassword.tsx https://github.com/grafana/grafana/pull/81263
- [x] public/app/core/components/ForgottenPassword/ForgottenPassword.tsx https://github.com/grafana/grafana/pull/81263
- [x] public/app/core/components/Login/LoginForm.tsx https://github.com/grafana/grafana/pull/81326
- [x] public/app/core/components/SharedPreferences/SharedPreferences.tsx https://github.com/grafana/grafana/pull/81468
- [x] public/app/core/components/Signup/SignupPage.tsx https://github.com/grafana/grafana/pull/81532
- [x] public/app/core/components/Signup/VerifyEmail.tsx https://github.com/grafana/grafana/pull/81532
- [x] public/app/features/admin/AdminEditOrgPage.tsx https://github.com/grafana/grafana/pull/81618
- [x] public/app/features/admin/UserCreatePage.tsx https://github.com/grafana/grafana/pull/81618
- [x] public/app/features/admin/ldap/LdapPage.tsx https://github.com/grafana/grafana/pull/81618
- [x] public/app/features/alerting/components/BasicSettings.tsx https://github.com/grafana/grafana/pull/81681
- [x] public/app/features/alerting/components/OptionElement.tsx https://github.com/grafana/grafana/pull/81681
- [x] public/app/features/alerting/unified/components/admin/ConfigEditor.tsx https://github.com/grafana/grafana/pull/81681
- https://github.com/grafana/grafana/issues/82503
- [x] public/app/features/alerting/unified/components/notification-policies/EditDefaultPolicyForm.tsx https://github.com/grafana/grafana/pull/81758
- [x] public/app/features/alerting/unified/components/notification-policies/EditNotificationPolicyForm.tsx https://github.com/grafana/grafana/pull/81758
- [x] public/app/features/auth-config/FieldRenderer.tsx https://github.com/grafana/grafana/pull/81345
- [x] public/app/features/browse-dashboards/components/NewFolderForm.tsx https://github.com/grafana/grafana/pull/83028
- [x] public/app/features/correlations/Forms/TransformationsEditor.tsx https://github.com/grafana/grafana/pull/83743
- [x] public/app/features/dashboard/components/RowOptions/RowOptionsForm.tsx
- [x] public/app/features/dashboard/components/SaveDashboard/forms/SaveDashboardAsForm.tsx
- [x] public/app/features/dashboard/components/SaveDashboard/forms/SaveDashboardForm.tsx https://github.com/grafana/grafana/pull/84172
- [x] public/app/features/dashboard/components/ShareModal/SharePublicDashboard/ConfigPublicDashboard/ EmailSharingConfiguration.tsx https://github.com/grafana/grafana/pull/84173
- [x] public/app/features/dashboard/components/ShareModal/SharePublicDashboard/CreatePublicDashboard/ CreatePublicDashboard.tsx https://github.com/grafana/grafana/pull/84173
- [x] public/app/features/explore/CorrelationTransformationAddModal.tsx https://github.com/grafana/grafana/pull/83742
- [x] public/app/features/explore/extensions/AddToDashboard/AddToDashboardForm.tsx https://github.com/grafana/grafana/pull/83742
- [x] public/app/features/invites/SignupInvited.tsx https://github.com/grafana/grafana/pull/84537
- [x] public/app/features/manage-dashboards/DashboardImportPage.tsx https://github.com/grafana/grafana/pull/83747
- [x] public/app/features/manage-dashboards/components/ImportDashboardForm.tsx https://github.com/grafana/grafana/pull/83747
- [x] public/app/features/manage-dashboards/components/ImportDashboardOverview.tsx https://github.com/grafana/grafana/pull/83747
- [x] public/app/features/org/OrgProfile.tsx https://github.com/grafana/grafana/pull/84537
- [x] public/app/features/org/UserInviteForm.tsx https://github.com/grafana/grafana/pull/84293
- [x] public/app/features/playlist/PlaylistForm.tsx https://github.com/grafana/grafana/pull/84536 
- [x] public/app/features/profile/ChangePasswordForm.tsx https://github.com/grafana/grafana/pull/84052
- [x] public/app/features/profile/UserProfileEditForm.tsx https://github.com/grafana/grafana/pull/84537
- [x] public/app/features/serviceaccounts/ServiceAccountCreatePage.tsx https://github.com/grafana/grafana/pull/84537
- [x] public/app/features/storage/CreateNewFolderModal.tsx https://github.com/grafana/grafana/pull/84537
- [x] public/app/features/support-bundles/SupportBundlesCreate.tsx https://github.com/grafana/grafana/pull/84537
- [x] public/app/features/teams/CreateTeam.tsx https://github.com/grafana/grafana/pull/82367
- [x] public/app/features/teams/TeamSettings.tsx https://github.com/grafana/grafana/pull/82367
- [x] public/app/plugins/panel/timeseries/plugins/annotations/AnnotationEditorForm.tsx https://github.com/grafana/grafana/pull/84538
- [x] public/app/plugins/panel/timeseries/plugins/annotations2/AnnotationEditor2.tsx https://github.com/grafana/grafana/pull/84538
