### ISSUE TITLE
advancedDataSourcePicker

### ISSUE THREAD

**Issue by Sergej-Vlasov** [grafana/grafana#81251]
```[tasklist]
### Tasks
- [ ] Remove toggle from registry
- [ ] Remove the unused components from the old version
- [ ] Remove the usage of the FF in the code
- [ ] Remove FF from deployment_tools
```
