### ISSUE TITLE
In alert rule contact points testing and overview

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#81267]
This issue tracks adding contact points testing & validation to various places in Grafana Alerting

Context: Related private discussion: https://raintank-corp.slack.com/archives/C035H7HNJDR/p1705940880212149

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/82071
- [ ] https://github.com/grafana/grafana/issues/82108
- [ ] Policies routing - Test selected contat point
- [ ] Notification routing overview on the alert rule detail page
```
