### ISSUE TITLE
Epic: [Deprecation] Flow Chart in Canvas

### ISSUE THREAD

**Issue by jennyfana** [grafana/grafana#81347]
Goal: Create Flow Chart capabilities in Grafana Canvas

Context: Grafana will be turning off its support for Angular in G11 and this means that users will not be able to use the Angular-based Community Plugin for Flow Charting.

There is a strong demand for Grafana to support this capability. See this [petition](https://www.change.org/p/urge-grafanalabs-to-migrate-flowcharting-plugin-from-angular-to-react) and this community issue https://github.com/grafana/grafana/issues/79874.

With this project we are not aiming to provide full feature parity with Flow Charting plugin. Initially draw.io import is not part of the scope of this work.

Scope:
- Connectors improvements to make routing and connecting elements easier
- Adding more basic elements (to support flowcharting)
- Adding additional styling options for connectors and elements
- Improvements to panel options order

```[tasklist]
### TODO
- [x] https://github.com/grafana/grafana/issues/78564
- [x]  #83267
- [x] #83268
- [x] #83269
- [x] #83543
- [x] #83270
- [x] #83271
- [x] https://github.com/grafana/grafana/issues/77526
- [ ] #83544
- [x] #84606
```

```[tasklist]
### Stretch Goals
- [ ] Additional line option (s) would be sweet (dotted, dashed, etc, bonus animated ❤️)
- [ ] Ability to detach arrows / lines and treat them as elements
- [ ] Ability to move / redraw arrows without having to delete them ^ related to above most likely
- [x] https://github.com/grafana/grafana/pull/83295
- [x] #84403
- [x] #84604
```

```[tasklist]
### Refinements / feedback
- [ ] #84334
- [ ] #85031
- [ ] https://github.com/grafana/grafana/issues/84848
- [ ] https://github.com/grafana/grafana/issues/84845
- [x] https://github.com/grafana/grafana/issues/84843
- [x] https://github.com/grafana/grafana/issues/84869
- [x] https://github.com/grafana/grafana/issues/84871
- [ ] https://github.com/grafana/grafana/issues/84956
- [ ] https://github.com/grafana/grafana/issues/84957
- [ ] https://github.com/grafana/grafana/issues/84958
- [ ] https://github.com/grafana/grafana/issues/84959
- [ ] https://github.com/grafana/grafana/issues/84960
- [ ] https://github.com/grafana/grafana/issues/84961
- [ ] #85013
- [ ] #85019
- [ ] https://github.com/grafana/grafana/issues/85037
- [ ] https://github.com/grafana/grafana/issues/85038
- [x] #85416
- [ ] https://github.com/grafana/grafana/issues/85679
- [ ] https://github.com/grafana/grafana/issues/86210
- [ ] https://github.com/grafana/grafana/issues/86379
- [ ] https://github.com/grafana/grafana/issues/86933
- [ ] https://github.com/grafana/grafana/issues/87359
```

Related efforts
- Improving the handling of the rendering engine

**Comment by hicwic** [comment]
Scope:
- alertmanager datasource (as explained in community issue)

**Comment by manuelmaudrich** [comment]
hello @jennyfana ,
I can only support this. The use of flowcharts is existentail for our work. We are currently in the process of updating our Grafana environment. As a result, we realised that the Flowcharts plugin will no longer be supported in the future. Which is really a bit of a nightmare. I then tried to implement the existing flows in Canvas. Unfortunately, I failed. Canvas does not allow you to define different limits for different elements. This is not innovative in my opinion and is therefore unusable for us. It would be really good if a remedy could be found here. We don’t really care in which direction it goes. Whether it is the implementation of Flowcharts in the new environment or Canvas is further developed so that features comparable to those in Flowcharts are available. That would be really great if further developments were made here. If there is no remedy here, then it will be difficult to upgrade.

Thank you in advance

**Comment by drew08t** [comment]
> different limits for different elements

Thanks for your feedback. Can you please expand on what you mean by "different limits for different elements"? Do you have an example we can look at?

**Comment by manuelmaudrich** [comment]
> > different limits for different elements
> 
> Thanks for your feedback. Can you please expand on what you mean by "different limits for different elements"? Do you have an example we can look at?

Hello @drew08t,

We use Flowchart as a slimmed-down HMI for our process visualisation to give our operators a quick indication of the status of our systems. The graphic is based on a P&ID. The system data itself is sent to an SQL database via ODPC. We have connected this database to Grafana and can therefore display plant-specific key figures. 

Example:

![image](https://github.com/grafana/grafana/assets/61205220/58c78fe1-f309-4406-baca-cd4b1ac650db)


This also includes exceeding the limits of individual measurements or the status of individual aggregates. We therefore need the option of defining rules and thresholds for the individual shapes. Unfortunately, this cannot be defined in Canvas for individual elements or shapes. You can only define a threshold globally. If I am wrong about this, please tell me how I can do it. It would be really great if all the functionalities available in Flowcharts could be implemented in Canvas. 

For example:

![image](https://github.com/grafana/grafana/assets/61205220/bd28bbcd-1b6a-4ab9-8a81-0fa8cd1171c4)
![image](https://github.com/grafana/grafana/assets/61205220/41050461-d5e4-41a9-9be1-e22974e399b4)


I hope that it was understandable so far what our wishes are. Here again the links to the documentation. 

https://grafana.com/grafana/plugins/agenty-flowcharting-panel/
https://algenty.github.io/flowcharting-repository/

**Comment by lukasztyrala** [comment]
Hi @manuelmaudrich, thanks for providing a use case.

Indeed, the Canvas panel does not offer this level of per-element options—it is on our radar but not on the backlog yet.

That said, we do allow specifying thresholds (among other options) individually based on, for example, a query or field via [Overrides](https://grafana.com/docs/grafana/latest/panels-visualizations/configure-overrides/). I have attached a short video showing two metric elements in canvas using different thresholds. Maybe this would be something helpful in your case.


https://github.com/grafana/grafana/assets/141744/6520c5c7-5c44-4699-a606-f125867d0e0e

**Comment by nmarrs** [comment]
Hi @xkilian - this comment should be helpful for addressing the first item you have raised :) https://github.com/grafana/grafana/issues/77246#issuecomment-2029369149

**Comment by natellium** [comment]
👋  we consider this issue as completed; if you have any further requests, please open a new issue. Thank you!
