### ISSUE TITLE
Saga Design Library - Figma Community file v1.0

### ISSUE THREAD

**Issue by Aires-Grafana** [grafana/grafana#81366]
After the release of our Saga site to be public, we're receiving multiple requests to access our design libraries in Figma. Currently, the resource links we provide in the Saga site for the Figma libraries, are for internal access and consumption only by Grafana. However, and as part of our plan to make it available to the community as well, we need to provide the state-of-the-art library to the community to be iterated upon new releases in the future.
Below are the needed tasks to be performed to make the v1.0 community file available to the Figma community.
```[tasklist]
### Tasks
- [x] Duplicate [existent component library](https://www.figma.com/file/htVIFrTq8e7sx8Olo7L6kZ/Saga-Components--Dark-theme?type=design)
- [x] cleanup all the internal/private stuff
- [x] Make all component pages consistent
- [x] Write a Welcome message to the file
- [x] Create a Light theme community file
- [x] Publish both [dark](https://www.figma.com/file/ui3cxYkv9xnEWDBmmONalG/Saga-UI-Kit---Dark-theme?type=design&node-id=8443%3A13519&mode=design&t=wuRPqyWEUuE01itt-1) and [light](https://www.figma.com/file/fWJWoMlORrsJRwICRUYNlU/Saga-UI-Kit---Light-theme?type=design&node-id=8443%3A13519&mode=design&t=VqxQL7QkYKk23wpT-1) theme files into Figma community using the [Saga community profile](https://figma.com/@Saga_DS)
- [x] Communicate the release of the files in Slack
- [x] Update Saga site "[resources](https://grafana.com/developers/saga/resources)" page to have the "external" link available for the community
```

**Comment by Aires-Grafana** [comment]
@staton-hyse11 I've created this issue to map all work to make the Saga library available to the Figma community.
Let me know your thoughts and if there is anything else that needs to be mapped in the task list to be performed.
