### ISSUE TITLE
Saga - Communication Updates [epic]

### ISSUE THREAD

**Issue by eledobleefe** [grafana/grafana#81486]
Work on the way Saga is going to communicate its updates to its public.
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/81488
- [ ] Create the Slack Workflow and test it out to ensure it works
- [ ] Develop a 'How to' for designers/engineers to fill out a Slack Workflow to provide details and explanations of their updates.
- [ ] Establish a process for gathering the updates/progress/impact from the team for the more broad audience communications. This could be similar to what @yaelleC has recently created in our Slack channel.
```

**Comment by staton-hyse11** [comment]
Started a transfer to keep all work in one location
