### ISSUE TITLE
One can edit Panel Options

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#81559]
```[tasklist]
### Tasks
- [x] [Title, description, transparency](https://github.com/grafana/grafana/pull/80884)
- [x] [Panel plugin options](https://github.com/grafana/grafana/pull/80884)
- [x] [Panel Links](https://github.com/grafana/grafana/pull/81560)
- [ ] [Repeat options](https://github.com/grafana/grafana/pull/81818)
```
