### ISSUE TITLE
One can view, create and edit Permissions

### ISSUE THREAD

**Issue by mdvictor** [grafana/grafana#81760]
```[tasklist]
### Tasks
- [ ] One can navigate to Dashboard Settings -> Permissions tab
- [ ] The permissions are listed and grouped accordingly
- [ ] One can edit a permission
- [ ] One can add a new permission
- [ ] One can remove an existing permission
```
