### ISSUE TITLE
Return to Previous: Create the release planning and do the rollout

### ISSUE THREAD

**Issue by eledobleefe** [grafana/grafana#81784]
Rollout plan:
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/82190
- [ ] https://github.com/grafana/grafana/issues/82452
- [x] [Smoke Test: 50% Free and Free-trial](https://github.com/grafana/deployment_tools/pull/121968)
- [x] [50% Free, Free-trial and Pro](https://github.com/grafana/deployment_tools/pull/123012)
- [x] [50% Everyone](https://github.com/grafana/deployment_tools/pull/124338)
- [x] [GA: 100% Everyone](https://github.com/grafana/deployment_tools/pull/126072)
```

PRR dashboard: [Grafana Feature Toggle PRR](https://ops.grafana-ops.net/d/48INDsjnk/grafana-feature-toggle-prr?orgId=1&var-Metrics=000000134&var-Logs=OP27Xzxnk&var-feature=returnToPrevious&var-slug=navigation)

**Comment by yaelleC** [comment]
Rollout plan: https://docs.google.com/spreadsheets/d/1ypIL4vklTSBfGYHXR1-SGYWWSWSm2lLYA7MCwFWutrw/edit#gid=0 
Dates to be refined, if we can move it earlier that would be great
