### ISSUE TITLE
epic: plugin details page - links and metadata

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/grafana#81905]
This epic tracks a series of enhancements to the plugins details page, namely administration > plugins & data > plugins > plugin_name.

```[tasklist]
### WIP
- [ ] create new floating/collapsable right-hand section for additional links and metadata
- [ ] extend left hand nav section in grafana.com
- [ ] move existing links to new section
- [ ] provide inferred link to report a bug which can be overridden as necessary
- [ ] provide inferred link to raise feature request which can be overridden as necessary
- [ ] provide inferred link to sponsor/support which can be overridden as necessary
- [ ] provide inferred link to documentation which can be overridden as necessary
- [ ] explore ways to surface changelog for plugin versions or provide inferred link to changelog (explore for given version)
- [ ] provide action/docs on changelog generation
- [ ] create new validator check for changelog and warn on omission
- [ ] provide new `contributions` status for plugins - Welcome (default) | Needed (warning) | Not actively seeking
- [ ] surface license for plugin
- [ ] provide link to report abuse which emails `integrations@grafana.com`
- [ ] surface last commit date for plugin repository
- [ ] surface last updated date for plugin
```

**Comment by tolzhabayev** [comment]
Closing as done
