### ISSUE TITLE
CloudWatch: Audit/Update for multitenancy

### ISSUE THREAD

**Issue by iwysiu** [grafana/grafana#82194]
**What is the chore?**:
Check the CloudWatch code (and its dependencies) to make sure they're secure for multitenancy. Remember to check over the imports from `aws-sdk-go` and how we're using it.

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/pull/83278
- [ ] https://github.com/grafana/grafana/pull/83332
- [ ] https://github.com/grafana/grafana/pull/83333
- [ ] https://github.com/grafana/grafana/pull/83335
```

Notes from initial audit:
- `QueriesTotalCounter` was approved as a global ([slack link](https://raintank-corp.slack.com/archives/C05NHPPPPNE/p1707237005718529))

**Is there anything else we need to know?**:

For reference, the key parts of supporting multi-tenancy are:
- State and sensitive information should only be stored at the instance level
- Code should not reference environment variables
- Code should not access the file system
