### ISSUE TITLE
plugins: improve update experience 

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/grafana#82263]
From an instance details page on Grafana.com a user is able to view a list of installed plugins, update individually or update all

<img width="1054" alt="Screenshot 2024-02-09 at 14 06 11" src="https://github.com/grafana/grafana/assets/19860021/a56073d3-d307-497c-81f1-9069721d5e36">

<img width="1023" alt="Screenshot 2024-02-09 at 14 09 37" src="https://github.com/grafana/grafana/assets/19860021/82498dce-965a-4dff-ab20-a139be8498e7">

In the connections view in Grafana Cloud, when there is an _integration_ with an available update, the user is notified and is able to see a list of these. The view implies that it could include datasources, but it cannot.
<img width="1505" alt="Screenshot 2024-02-09 at 14 07 52" src="https://github.com/grafana/grafana/assets/19860021/f5c53844-a26c-4e86-8b05-4420a1ff631a">

In the plugins catalog (OSS/Cloud) an update available badge is added 

<img width="305" alt="Screenshot 2024-02-09 at 14 37 04"
src="https://github.com/grafana/grafana/assets/19860021/259a4b55-ede0-4140-9342-ee0de9ee1f62">

However, in the OSS connections view `/connections/add-new-connection` there is just the angular badge (and no indication on which is installed... separate problem)

<img width="407" alt="Screenshot 2024-02-09 at 14 37 55" src="https://github.com/grafana/grafana/assets/19860021/fcf53758-4819-4c3f-9844-dead74e03456">

In the /connections/datasources/new (OSS) (installed plugins AND enterprise plugins AND a link to Grafana Cloud) not even the angular badge is shown. 

<img width="1205" alt="Screenshot 2024-02-09 at 14 38 12" src="https://github.com/grafana/grafana/assets/19860021/c52198cf-ebd1-41eb-8170-8cc03ed7147a">
<img width="1203" alt="Screenshot 2024-02-09 at 14 48 59" src="https://github.com/grafana/grafana/assets/19860021/73a91861-7788-43a7-b753-be5442b40fea">

## Tasks

We should:
- [ ] Provide an update all button in `/plugins` (OSS and Cloud)
- [ ] Create a follow up task to better align the Connections view and plugin catalog

We could
- [ ] Provide an "New updates" state filter in `/plugins` (OSS and Cloud)

**Comment by sympatheticmoose** [comment]
Capturing more specific tasks after workshop
