### ISSUE TITLE
Playlist run on Scenes

### ISSUE THREAD

**Issue by ivanortegaalba** [grafana/grafana#82317]
We should match the expected behavior explained in the documentation: https://grafana.com/docs/grafana/latest/dashboards/create-manage-playlists/#start-a-playlist

```[tasklist]
### Tasks
- [x] [Run playlist on Scenes in normal mode](https://github.com/grafana/grafana/pull/83551)
- [ ] Run playlist with autofit enabled
- [ ] Run playlist with TV Mode
- [ ] Run playlist with Kiosk
```
