### ISSUE TITLE
E2C: UI for cloud migration first preview

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#82361]
UI for cloud migration service.

Figma https://www.figma.com/proto/eHBN07eMTnXC2TfC8WOyKN/Migration-Assistant?type=design&node-id=225-5939&t=Q2yW9eisxDhYbD4j-1&scaling=min-zoom&page-id=209%3A1714&starting-point-node-id=225%3A5939&mode=design 

```[tasklist]
### Core flow.
- [ ] https://github.com/grafana/grafana/issues/82313
- [ ] https://github.com/grafana/grafana/pull/83215
- [ ] https://github.com/grafana/grafana/issues/82362
- [ ] https://github.com/grafana/grafana/issues/83180
- [ ] https://github.com/grafana/grafana/issues/83488
- [ ] https://github.com/grafana/grafana/issues/84552
- [ ] https://github.com/grafana/grafana/issues/84553
- [ ] E2C: Use correct permissions
- [ ] https://github.com/grafana/grafana/pull/84654
- [x] E2C: Migrate again button
- [x] Cloud-side: Call createCloudMigrationToken when clicking on [Create Token] button
- [x] Cloud-side: Call getCloudMigrationTokenStatus to check if token already exists (API TODO)
- [x] Cloud-side: Restore [Delete Token] button and call deleteCloudMigrationToken (API TODO)
```
