### ISSUE TITLE
Dashboard scenes: library panels not supported by panel menu.

### ISSUE THREAD

**Issue by oscarkilhed** [grafana/grafana#82416]
The panel menu does not fully support library panels.

```[tasklist]
### Tasks
- [x] View
- [x] Edit
- [x] Share (menu item works, but sharing does not support library panels it seems)
- [x] Explore
- [x] Inspect/Data
- [x] Inspect/Query
- [x] Inspect/Panel JSON (Opens the inspect drawer, but Panel JSON is empty)
- [x] More hide/show legend
- [x] More/New alert rule
- [x] More/Duplicate
- [x] More/Copy
- [ ] More/Get help
- [x] Remove library panel from dashboard
```

**Comment by grafanabot** [comment]
@oscarkilhed please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:
