### ISSUE TITLE
Correlations: Investigate a flaky integration test

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#82520]
```
--- FAIL: TestIntegrationUpdateCorrelation (0.97s)
    correlations_update_test.go:22: Grafana is listening on 127.0.0.1:42567
    --- FAIL: TestIntegrationUpdateCorrelation/should_correctly_update_correlations (0.03s)
        correlations_update_test.go:380: 
            	Error Trace:	/drone/src/pkg/tests/api/correlations/correlations_update_test.go:380
            	Error:      	Not equal: 
            	            	expected: 200
            	            	actual  : 404
            	Test:       	TestIntegrationUpdateCorrelation/should_correctly_update_correlations
FAIL
```

https://drone.grafana.net/grafana/grafana-enterprise/67112/2/9

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/pull/82522
- [x] Investigate / fix / re-enable
- [ ] https://github.com/grafana/grafana/pull/88912
```

**Comment by gelicia** [comment]
Tried to replicate locally by getting Grafana Enterprise running locally then running the entire test suite. 

```
=== RUN   TestIntegrationUpdateCorrelation
    correlations_update_test.go:20: Grafana is listening on 127.0.0.1:61535
=== RUN   TestIntegrationUpdateCorrelation/Unauthenticated_users_shouldn't_be_able_to_update_correlations
=== RUN   TestIntegrationUpdateCorrelation/non_org_admin_shouldn't_be_able_to_update_correlations
=== RUN   TestIntegrationUpdateCorrelation/inexistent_source_data_source_should_result_in_a_404
=== RUN   TestIntegrationUpdateCorrelation/inexistent_correlation_should_result_in_a_404
=== RUN   TestIntegrationUpdateCorrelation/updating_a_read-only_correlation_should_result_in_a_403
=== RUN   TestIntegrationUpdateCorrelation/updating_a_correlation_without_data_should_result_in_a_400
=== RUN   TestIntegrationUpdateCorrelation/updating_a_correlation_pointing_to_a_read-only_data_source_should_work
=== RUN   TestIntegrationUpdateCorrelation/should_correctly_update_correlations
--- PASS: TestIntegrationUpdateCorrelation (2.50s)
    --- PASS: TestIntegrationUpdateCorrelation/Unauthenticated_users_shouldn't_be_able_to_update_correlations (0.01s)
    --- PASS: TestIntegrationUpdateCorrelation/non_org_admin_shouldn't_be_able_to_update_correlations (0.01s)
    --- PASS: TestIntegrationUpdateCorrelation/inexistent_source_data_source_should_result_in_a_404 (0.01s)
    --- PASS: TestIntegrationUpdateCorrelation/inexistent_correlation_should_result_in_a_404 (0.01s)
    --- PASS: TestIntegrationUpdateCorrelation/updating_a_read-only_correlation_should_result_in_a_403 (0.01s)
    --- PASS: TestIntegrationUpdateCorrelation/updating_a_correlation_without_data_should_result_in_a_400 (0.03s)
    --- PASS: TestIntegrationUpdateCorrelation/updating_a_correlation_pointing_to_a_read-only_data_source_should_work (0.01s)
    --- PASS: TestIntegrationUpdateCorrelation/should_correctly_update_correlations (0.06s)
PASS
```

Tried again twice (clearing the test cache between) and had the same results. 

The line that got a 404 instead of a 200 is https://github.com/grafana/grafana/blob/main/pkg/tests/api/correlations/correlations_update_test.go#L382 

which is a test for the update PATCH 
https://github.com/grafana/grafana/blob/main/pkg/services/correlations/api.go#L29
https://github.com/grafana/grafana/blob/main/pkg/services/correlations/api.go#L144

A 404 here indicates a not found error, which means either the correlation or the datasource is not found. What's peculiar is either of those things not existing would have failed the test before that specific test. Given the intermittent nature of this, I'm wondering if its the datasource or the correlation getting deleted while this test is running. I am going to investigate further.

**Comment by sarahzinger** [comment]
Hey folks, sorry to reopen but I think this is still happening.

here's a build where this test failed: https://drone.grafana.net/grafana/grafana/180450/3/8
and here's a build where the test passed: https://drone.grafana.net/grafana/grafana/180452/1/1

the code is the same, and it's rebased off of the latest main.
