### ISSUE TITLE
Design tokens pipeline documentation - Figma

### ISSUE THREAD

**Issue by Aires-Grafana** [grafana/grafana#82679]
Aligned with the work being done for the Design Tokens POC, we need proper documentation to provide clear guidance about the workflow and pipeline that connects designers and devs, and about all the tooling we're using that needs to be triggered to enable design tokens, combined with Figma variables, styles and libraries in Figma.

```[tasklist]
### Tasks
- [x] Create a Figjam file to store the information within the [Saga Foundations & Assets](https://www.figma.com/files/901613520761254364/project/143951533) project in the new Saga PoC team
- [x] Add all the representations of files and libraries that will connect our components with design tokens
- [ ] Create the clear relations between them and write the guidance on how to work with them by leveraging most common use cases
- [ ] Record simple videos (1 min or less) explaining where to find and how to work with the tooling.
```

**Comment by grafanabot** [comment]
@Aires-Grafana please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:

**Comment by Aires-Grafana** [comment]
[Saga Design Tokens pipeline and workflows](https://www.figma.com/file/6mK91Q6WghXir37rbVCbbP/Saga-Design-Tokens-pipeline-and-workflows?type=whiteboard&node-id=0%3A1&t=QseI3LUZ2SGcSamG-1) FigJam file created and pipeline ready for review.
cc @staton-hyse11 and @JoaoSilvaGrafana

**Comment by staton-hyse11** [comment]
I've taken a look at this and it makes sense to me. I think a demo would be beneficial so I can better understand how designers will be impacted this and how they will interact with it all.
