### ISSUE TITLE
chore: plugins are missing descriptions

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/grafana#83447]
The description and keywords field is empty for a number of plugins which impacts their discoverability.

Description is exposed to the user in the plugin details page and provides a quick summary of the plugin, it may be used in the future to impact search rankings. Keywords were used on searches on grafana.com, they have recently been incorporated in searches within grafana.com/plugins as well as within grafana `/connections` and `/plugins`

```[tasklist]
### Add descriptions
- [x] alertmanager
- [x] candlestick
- [x] histogram
- [x] xychart
- [x] grafana-enterprise-logs-app
- [x] grafana-metrics-enterprise-app
- [x] grafana-enterprise-traces-app
- [x] grafana-opensearch-datasource
```
```[tasklist]
### Tasks
- [ ] Update via api
```
