### ISSUE TITLE
Epic: Restore Dashboards

### ISSUE THREAD

**Issue by L-M-K-B** [grafana/grafana#83620]
For years we get requests from users that would like to restore a dashboard they deleted accidentally (e.g. see [this issue](https://github.com/grafana/grafana/issues/9235)). These recurring requests were the starting point of a hackathon project that we want to complete.

The goals of GA are
1) Admins can view a list recently deleted dashboards, and can restore them
2) User who deleted the dashboard can restore it  

**The frontend needs to have the following elements:**
- recently deleted dashboards section which contains a list of restorable dashboards
- ability to filter, search and an option to sort the list
- work flow for restoring a dashboard

### Development
- [x] #87392
- [x] #87393
- [x] https://github.com/grafana/grafana/issues/88389
- [x] https://github.com/grafana/grafana/issues/88557
- [x] #88274
- [x] https://github.com/grafana/grafana/pull/89201
- [x] https://github.com/grafana/grafana/pull/89233
- [x] https://github.com/grafana/grafana/issues/88890
- [x] https://github.com/grafana/grafana/issues/88559
- [x] https://github.com/grafana/grafana/issues/88806
- [x] https://github.com/grafana/grafana/issues/88683
- [x] https://github.com/grafana/grafana/issues/89528
- [x] https://github.com/grafana/grafana/issues/89527
- [x] https://github.com/grafana/grafana/issues/89529
- [x] https://github.com/grafana/grafana/pull/89825
- [x] https://github.com/grafana/grafana/issues/88889
- [x] https://github.com/grafana/grafana/issues/89294
- [x] https://github.com/grafana/grafana/issues/89526
- [x] https://github.com/grafana/grafana/issues/89623
- [x] https://github.com/grafana/grafana/pull/89043
- [x] https://github.com/grafana/grafana/pull/89214
- [x] https://github.com/grafana/grafana/issues/91681
- [x] https://github.com/grafana/grafana/issues/92366
- [x] https://github.com/grafana/grafana/issues/91676
- [x] https://github.com/grafana/grafana/issues/92363
- [x] https://github.com/grafana/grafana/issues/92458
- [x] https://github.com/grafana/grafana/issues/92736
- [x] https://github.com/grafana/grafana/issues/93149
- [x] https://github.com/grafana/grafana/issues/93885
- [x] https://github.com/grafana/grafana/issues/93886
- [x] https://github.com/grafana/grafana/pull/94046
- [x] https://github.com/grafana/grafana/pull/94086
- [x] https://github.com/grafana/grafana/issues/94406
- [x] https://github.com/grafana/grafana/pull/94855

### Backend-only rollout critical
- [x] https://github.com/grafana/grafana/issues/90467
- [x] https://github.com/grafana/grafana/pull/94674
- [x] https://github.com/grafana/grafana/pull/94720

### Backend
- [x] https://github.com/grafana/grafana/pull/89020

### UX
- [x] https://github.com/grafana/grafana/issues/106588

### Release
- [x] https://github.com/grafana/grafana/issues/92003
- [x] https://github.com/grafana/grafana/issues/94205
- [x] https://github.com/grafana/deployment_tools/pull/180194
- [x] https://github.com/grafana/grafana/issues/93150

-------

### Development
- [x] https://github.com/grafana/grafana/pull/105820
- [x] #106434
- [x] #106463
- [x] #106986
- [x] #110509

### Release
- [x] #107673
- [x] https://github.com/grafana/grafana/issues/89369
- [x] #107674
- [x] https://github.com/grafana/grafana/issues/92737
- [ ] #107675
- [x] #107824
- [ ] RestoreDashboards: Remove feature toggle

### Potential Improvements
- [ ] https://github.com/grafana/grafana/issues/93887
- [ ] https://github.com/grafana/grafana/issues/92367
- [x] https://github.com/grafana/grafana/issues/95271

**Comment by L-M-K-B** [comment]
Also see https://github.com/grafana/grafana/issues/9235

**Comment by L-M-K-B** [comment]
Waiting for https://github.com/grafana/grafana/pull/83131 to be merged.

**Comment by tdbishop** [comment]
## Highlight
We're waiting on unified storage to launch mode 3 for dashboards by GSS (Grafana Search and Storage) squad.
## Status:
🟢 
## Next: 
We expect mode 3 to hit dev this month and start roll out in September. We'll draft release notes for "What's New" closer to those dates.

**Comment by tdbishop** [comment]
## Highlight
Unified Storage (the main dependency of this project) was delayed 3-4 weeks from our original delivery plan.
## Status
🟢 
## Next
Delivery pushed back a month. Private Preview in October, Public November, GA January.

**Comment by tdbishop** [comment]
## Highlight
We deployed in Dev this week! We have a rollout [dashboard available](https://ops.grafana-ops.net/d/ee0gb1qrv8d8gc/restore-dashboard-usage?orgId=1&from=now-7d&to=now&timezone=utc&var-env=dev&var-prometheus_ds=2z9d6ElGk&var-bigquery_ds=Wq1zCjRVz&var-query0=&var-dataset_fixed=dev&var-bigquery_dataset=dev&var-bigquery_project=grafanalabs-dev)
## Status
🟢 
## Next
Rollout to free instances in October after Unified Storage gets to production.

**Comment by tdbishop** [comment]
## Highlight
Deployed to Staging and Ops this week!
## Status
🟢 
## Next
Write release notes, RADS process, "What's new", and get this roll out started in October.

**Comment by tdbishop** [comment]
## Highlight
Private Preview is live this week! Grafana Docs are updated. The [What's New](https://grafana.com/whats-new/2025-10-13-restore-deleted-dashboards/) is up. Internally, [check out the dashboard](https://ops.grafana-ops.net/d/ee0gb1qrv8d8gc/restore-dashboard-usage) for watching adoption.
Sheet tracking (7) instances we're looking to include in private preview is [here](https://docs.google.com/spreadsheets/d/1zE-qxmGpnnp24BZNuLVQ9hnZeWbTDp4WKz3U5ddx78A/edit?gid=0#gid=0).

## Status
🟢 
## Next
Some more internal testing with various users and instances. Then roll out private preview.

**Comment by tdbishop** [comment]
## Highlight
We added a "sort by deleted date" and notification adjustments based on user feedback.

## Status
🟢 - but Private Preview date unknown.

## Next
We're still waiting for the Mode 3 rollout to enable the private preview. We decided not to go the Git Sync route to move individual instances to Mode 5 before enabling the toggle, since it's a non-reversible operation and would affect only dev instances, limiting the usefulness of the preview. In addition, some customers mentioned they'd prefer to wait until the feature can be enabled on their production instances.

**Comment by Clarity-89** [comment]
## Highlights (since last update)
- Aligned on an approach for handling the permissions on FE - the UI will show the restored dashboard page and the nav item to all users and backend will determine what the users can see on those pages, based on their permissions.

## Status
🟡 (waiting for mode 5 rollout to start private preview beginning of Feb)

## Next actions
- Implement the permissions changes on frontend
- Prepare the docs updates for public preview

## Risks / asks

Mode5 rollout is not done on time → manually disable the feature for the customers not on mode5, as there are only a few of them (4 atm).

**Comment by Clarity-89** [comment]
## Highlights (since last update)
- [PR](https://github.com/grafana/grafana/pull/116266) with the UI changes for the updated permissions merged
- [PR](https://github.com/grafana/grafana/pull/117240) with the doc changes opened

## Status
🟢 (Mode5 rollout done, only one org left for end of month to migrate)

## Next actions
- Public preview start (100% of free users) planned for Feb 9

## Risks / asks

Mode5 is not enabled for one org only → manually disable the feature for them.

**Comment by marybaldwin** [comment]
@Clarity-89 - should we make a new epic or issue for GA?

**Comment by Clarity-89** [comment]
No, we don't need a new epic, we can use this one until we release the feature and then move all the other leftover issues to a new one.

**Comment by Clarity-89** [comment]
## Highlights (since last update)
- Enabled to a 100% of free instances
- Added an improvement to go back to the restored dashboard.

## Status
🟢 

## Next actions
- Enabling for the paid instances next week

**Comment by Clarity-89** [comment]
## Highlights (since last update)
- The feature has been enabled for all the paid instances except one.

## Status
 🟢 

## Next actions
- Monitoring the feature rollout
- Addressing feedback

**Comment by Clarity-89** [comment]
## Highlights
- **Restore dialog fix** — the restore dialog no longer shows a deleted folder in the folder picker after the folder has been removed ([#122008](https://github.com/grafana/grafana/pull/122008))
- **E2E coverage** — added Playwright tests for restore dashboards and added selectors needed for the search results table and recently deleted page ([#122703](https://github.com/grafana/grafana/pull/122703))
- **Test fix** — fixed a flaky `RestoreModal` test covering 403 validation ([#122819](https://github.com/grafana/grafana/pull/122819))

## Status
🟢 

## Next actions
- Look into enforcing the recently deleted limits.

**Comment by Clarity-89** [comment]
## Highlights
- **Deleted-by attribution** — the Recently Deleted dashboards page now shows who deleted each dashboard and supports sorting by deleter ([#123364](https://github.com/grafana/grafana/pull/123364))
- **Retention-limit warning** — the Recently Deleted page now shows a dismissible warning when the 1000-item soft-delete retention cap is reached ([#123365](https://github.com/grafana/grafana/pull/123365))
- **Sort-state isolation** — Recently Deleted and Browse Dashboards now use separate persisted sort keys, with a one-time guard to clear stale legacy values that could force Browse Dashboards into list view ([#123675](https://github.com/grafana/grafana/pull/123675))
- **GA cleanup** — the `restoreDashboards` feature toggle was removed, so the Recently Deleted route, nav entry, delete notifications, and duplicate-name restore path are no longer gated after GA ([#123997](https://github.com/grafana/grafana/pull/123997))

## Status
🟢 

## Next actions
- The epic has been completed.
