### ISSUE TITLE
Remove old tooltips and annotations

### ISSUE THREAD

**Issue by leeoniya** [grafana/grafana#83632]
before we can remove old tooltips, we need to deploy `newVizTooltips` in HG, and validate parity with old tooltips.

this is a sub-epic of https://github.com/grafana/grafana/issues/68238

we have started rollout of this feature toggle internally to `dev` and `staging` for dogfooding and feedback: https://github.com/grafana/deployment_tools/pull/124451

**DRY**

- [x] Extract `EventBus` publisher and subscriber to plugin instead of duplicating code in each panel's `prepConfig()`
  - [x] Verify bi-directional cursor/hover sync between Table and uPlot-based panels: https://github.com/grafana/grafana/pull/78392
- [x] Rework Heatmap tooltip code to share dataLink logic with other tooltips: https://github.com/grafana/grafana/pull/71016
- [x] Unify and move cursor sync setup into `TooltipPlugin2` from various `prepConfig()`: https://github.com/grafana/grafana/pull/84420

**Verify datalinks work correctly in all panels**

- [ ] StatusHistory, StateTimeline
  - [ ] Re-check https://github.com/grafana/grafana/pull/50226, https://github.com/grafana/support-escalations/issues/932
- [ ] TimeSeries
- [ ] Candlestick
- [ ] Trend
- [ ] BarChart
- [ ] XYChart
- [ ] Heatmap? (only non-numeric heatmap-rows case?)

**Verify exemplars tooltip works correctly**

 - [ ] TimeSeries
 - [ ] Heatmap

**Verify other plugins play nice**

- [ ] KeyboardPlugin (all x=time)
  - [ ] TimeSeries
  - [ ] StateTimeline
  - [ ] StatusHistory
  - [ ] Candlestick
  - [ ] Heatmap
- [ ] OutsideRangePlugin (all x=time)
  - [ ] Fix to check `null` in values, not in timestamps since https://github.com/grafana/grafana/pull/57335
  - [ ] TimeSeries
  - [ ] StateTimeline
  - [ ] StatusHistory
  - [ ] Candlestick
  - [ ] Heatmap
- [ ] ThresholdControlsPlugin
  - [ ] TimeSeries
- [ ] ExemplarsPlugin
  - [ ] TimeSeries

**Remove old tooltip code from panels**

- [ ] StateTimeline
- [ ] StatusHistory
- [ ] BarChart
- [ ] Trend
- [ ] Candlestick
- [ ] TimeSeries
- [ ] Heatmap
- [ ] XYChart

**Remove now-unused components and features**

unserious-but-good reference: https://github.com/grafana/grafana/pull/83557

- [ ] addTooltipSupport
- [ ] PlotTooltipInterpolator
- [ ] AnnotationEditor + AnnotationTooltip https://github.com/grafana/grafana/tree/main/public/app/plugins/panel/timeseries/plugins/annotations
- [ ] AnnotationsPlugin: https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/timeseries/plugins/AnnotationsPlugin.tsx
- [ ] AnnotationEditorPlugin: https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/timeseries/plugins/AnnotationEditorPlugin.tsx
- [ ] ZoomPlugin: https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/uPlot/plugins/ZoomPlugin.tsx
- [ ] TooltipPlugin: https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx
- [ ] ContextMenuPlugin: https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/timeseries/plugins/ContextMenuPlugin.tsx
- [ ] StateTimelineTooltip: https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/state-timeline/StateTimelineTooltip.tsx
- [ ] StatusHistoryTooltip: https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/status-history/StatusHistoryTooltip.tsx
- [ ] HeatmapHoverViewOld: https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/heatmap/HeatmapHoverViewOld.tsx
- [ ] SeriesTable (need to remove single remaining use in PieChart)? https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/VizTooltip/SeriesTable.tsx

**Comment by nmarrs** [comment]
holy issue description batman 😅
