### ISSUE TITLE
Routing: Migrate core to react-router v6

### ISSUE THREAD

**Issue by leventebalogh** [grafana/grafana#83666]
This is an epic that can be completed incrementally. The issue tries following the [official migration guide](https://github.com/remix-run/react-router/discussions/8753) relying on the `react-router-dom-v5-compat` package.

Ideally we would like to follow a "bottom-up" strategy, meaning that we first update the "leaves", and then going up the navigation tree towards the root.

### Flow

**1. Convert `<Route>` to `<CompatRoute>` under `<Switch>` components** and use the new pattern (no `exact`, relative paths, using `element={}`)

**2. Use hooks for accessing routing metadata** - instead of relying on the props, start using the `useParams`, `useLocation` and `useNavigate` hooks

**3. Update `<Link>` and `<NavLink>` components** to use relative links in the `to={}` property

**4. Use `<Routes>` and `<Route>` from the v6 package** and replace `<CompatRoute>` with them once all the underlying navigation is updated

> [!CAUTION]
> Only remove the `<CompatRoute>` from the app plugins URL (`/a/*`) when we are removing support from using react-router v5 in app plugins. 

### Checklist

The following is a list of items to check for when preparing for the router v6 upgrade:

Stop using route props and rely on `useParams()` instead
- [ ] Use `useNavigate()` instead of `props.history`
- [ ] Use relative links in `<Link>` and `<NavLink>`
- [ ] Replace `Redirect` with `Navigate`
- [ ] Move `<Switch>` elements to `<Routes>`

Once all the usages of react-router v5 are updated:

- [ ] Stop using `<CompatRoute>` for app plugins (`/a/*) **breaking change for plugins using react-router v5**
- [ ] Stop sharing `react-router-dom@v5` with plugins ([here](https://github.com/grafana/grafana/blob/0dcdfc261b781df8c604ccac904dc500a63d327b/public/app/features/plugins/loader/sharedDependencies.ts#L140))
- [ ] Remove the `react-router-dom-v5-compat` package and only use v6 in core

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/92062
- [ ] https://github.com/grafana/grafana/issues/92064
- [ ] https://github.com/grafana/grafana/issues/92065
- [ ] https://github.com/grafana/grafana/issues/92066
- [ ] https://github.com/grafana/grafana/issues/92067
- [ ] https://github.com/grafana/grafana/issues/92068
- [ ] https://github.com/grafana/grafana/issues/92069
- [ ] https://github.com/grafana/grafana/issues/92113
- [ ] https://github.com/grafana/grafana/issues/92567
- [ ] https://github.com/grafana/grafana/issues/92569
- [ ] https://github.com/grafana/grafana/issues/92570
- [ ] https://github.com/grafana/grafana/issues/92571
- [ ] https://github.com/grafana/grafana/issues/92573
- [ ] https://github.com/grafana/grafana/issues/76744
- [ ] https://github.com/grafana/grafana/issues/93790
- [ ] https://github.com/grafana/grafana/issues/93795
- [ ] https://github.com/grafana/grafana/issues/94062
- [ ] https://github.com/grafana/grafana/issues/94066
- [ ] https://github.com/grafana/grafana/issues/94151
- [ ] https://github.com/grafana/grafana/issues/95498
```

**Comment by Clarity-89** [comment]
Closing this as the migration to the `react-router-dom-v5-compat` package has been done. The follow up work and actual switch to the router@6 is moved to a [separate Epic](https://github.com/grafana/grafana/issues/95585).
