### ISSUE TITLE
Release DashGPT auto-generate features for G11

### ISSUE THREAD

**Issue by ivanortegaalba** [grafana/grafana#83710]
DashGPT auto-generate features are not ready to be released in v11. The following work is the blocking work to enable this feature for everyone.

```[tasklist]
### Critical
- [ ] https://github.com/grafana/grafana/issues/79611
- [ ] https://github.com/grafana/grafana/issues/76848
- [x] Auto-generate: "Regenerate" button doesn't work
- [x] Auto-generate: "More descriptive" button return a wrong result because the context is missing
- [x] Create a new feature toggle for this feature since it doesn't work as good as auto-generate title and description
- [ ] https://github.com/grafana/grafana/issues/76651
```

```[tasklist]
### Bugs
- [ ] https://github.com/grafana/grafana/issues/76986
- [ ] Auto-generate: Panel description generation mentions "thresholds" needlessly
- [ ] https://github.com/grafana/grafana/issues/78423
- [x] Link LLM plugin docs from different parts from Dashboards docs
```

```[tasklist]
### UX improvements
- [ ] https://github.com/grafana/grafana/issues/84213
- [ ] https://github.com/grafana/grafana/issues/83735
- [ ] https://github.com/grafana/grafana/issues/83733
```

```[tasklist]
### Migrate to Scenes
- [x] Auto-generate: Panel title & Panel description
- [x] Auto-generate: Dashboard title (Settings and saving)
- [x] Auto-generate: Dashboard description (Settings and saving)
- [x] Auto-generate: Consider removing panel description preview
```

**Comment by natellium** [comment]
@ivanortegaalba  can we close this one?

**Comment by ivanortegaalba** [comment]
> @ivanortegaalba can we close this one?

Yes, this issue can be considered as done :) Thank you Natalia!
