### ISSUE TITLE
Dashboard Scenes M2: Bug bash

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#83845]
Extracted from #78389 

```[tasklist]
### Known bugs
- [ ] https://github.com/grafana/grafana/issues/87219
- [ ] https://github.com/grafana/grafana/issues/86963
- [ ] https://github.com/grafana/grafana/issues/87229
- [ ] https://github.com/grafana/grafana/issues/87171
- [ ] https://github.com/grafana/grafana/issues/87169
- [ ] https://github.com/grafana/grafana/issues/87128
- [ ] https://github.com/grafana/grafana/issues/87051
- [ ] https://github.com/grafana/grafana/issues/87135
- [ ] https://github.com/grafana/grafana/issues/87133
- [ ] https://github.com/grafana/grafana/issues/86988
- [ ] https://github.com/grafana/grafana/issues/87167
- [ ] https://github.com/grafana/grafana/issues/87455
```
<details>
<summary>Critical bugs V1</summary>

```[tasklist]
### Critical bugs
- [ ] https://github.com/grafana/grafana/issues/85023
- [ ] https://github.com/grafana/grafana/issues/85139
- [ ] https://github.com/grafana/grafana/issues/85076
- [ ] https://github.com/grafana/grafana/issues/84576
- [ ] https://github.com/grafana/grafana/issues/84830
- [ ] https://github.com/grafana/grafana/issues/84302
- [ ] https://github.com/grafana/grafana/issues/84562
- [ ] https://github.com/grafana/grafana/issues/84568
- [ ] https://github.com/grafana/grafana/issues/84577
- [ ] https://github.com/grafana/grafana/issues/84573
- [ ] https://github.com/grafana/grafana/issues/84575
- [ ] https://github.com/grafana/grafana/issues/85457
- [ ] https://github.com/grafana/grafana/issues/83916
- [ ] https://github.com/grafana/grafana/issues/85737
- [ ] https://github.com/grafana/grafana/issues/85783
```

</details>
<details>
<summary>Known Bugs Completed</summary>

```[tasklist]
### Known Bugs Completed
- [ ] https://github.com/grafana/grafana/issues/87134
- [ ] https://github.com/grafana/grafana/issues/86570
- [ ] https://github.com/grafana/grafana/issues/86420
- [ ] https://github.com/grafana/grafana/issues/86437
- [ ] https://github.com/grafana/grafana/issues/86943
- [ ] https://github.com/grafana/grafana/issues/86966
- [ ] https://github.com/grafana/grafana/issues/84565
- [x] Variable dropdown clips its options
- [ ] https://github.com/grafana/grafana/issues/86576
- [ ] https://github.com/grafana/grafana/issues/86500
- [ ] https://github.com/grafana/grafana/issues/83888
- [ ] https://github.com/grafana/grafana/issues/86559
- [ ] https://github.com/grafana/grafana/issues/86558
- [ ] https://github.com/grafana/grafana/issues/86557
- [ ] https://github.com/grafana/grafana/issues/86556
- [ ] https://github.com/grafana/grafana/issues/86555
- [ ] https://github.com/grafana/grafana/issues/86554
- [ ] https://github.com/grafana/grafana/issues/84807
- [ ] https://github.com/grafana/grafana/issues/85547
- [ ] https://github.com/grafana/grafana/issues/86435
- [ ] https://github.com/grafana/grafana/issues/84727
- [ ] https://github.com/grafana/grafana/issues/81632
- [ ] https://github.com/grafana/grafana/issues/86167
- [ ] https://github.com/grafana/grafana/issues/86158
- [ ] https://github.com/grafana/grafana/issues/82502
- [ ] https://github.com/grafana/grafana/issues/84566
- [ ] https://github.com/grafana/grafana/issues/77260
- [ ] https://github.com/grafana/grafana/issues/86296
- [ ] https://github.com/grafana/grafana/issues/86153
- [ ] https://github.com/grafana/grafana/issues/84578
- [ ] https://github.com/grafana/grafana/issues/85924
- [ ] https://github.com/grafana/grafana/issues/85925
- [ ] https://github.com/grafana/grafana/issues/86039
- [ ] https://github.com/grafana/grafana/issues/84155
- [ ] https://github.com/grafana/grafana/issues/84567
- [ ] https://github.com/grafana/grafana/issues/83908
- [ ] https://github.com/grafana/grafana/issues/78405
- [ ] https://github.com/grafana/grafana/issues/82925
- [ ] https://github.com/grafana/grafana/issues/80454
- [ ] https://github.com/grafana/grafana/issues/81218
- [x] [Navigating to a widget panel edit throws an error.](https://github.com/grafana/grafana/pull/81934)
- [ ] https://github.com/grafana/grafana/issues/80877
- [x] PanelEdit: pageNav model is wrong, breadcrumbs include Page Not Found segment
- [ ] https://github.com/grafana/grafana/issues/81469
- [ ] https://github.com/grafana/grafana/issues/81931
- [ ] https://github.com/grafana/grafana/issues/80434
- [ ] https://github.com/grafana/grafana/issues/81631
- [ ] https://github.com/grafana/grafana/issues/81883
- [ ] https://github.com/grafana/grafana/issues/82137
- [x] Remove debug and "View as dashboard" buttons from the dashboard
- [x] When switching viz type in panel edit mode some vizualization take the whole screen causing panel inspect drawer to disappear
- [ ] https://github.com/grafana/grafana/issues/82907
- [x] Mark dashboard as favorite from the toolbar does not work
- [ ] https://github.com/grafana/grafana/issues/83375
- [ ] https://github.com/grafana/grafana/issues/83477
- [ ] https://github.com/grafana/grafana/issues/83503
- [ ] https://github.com/grafana/grafana/issues/83613
- [ ] https://github.com/grafana/grafana/issues/83624
- [ ] https://github.com/grafana/grafana/issues/83690
- [ ] https://github.com/grafana/grafana/issues/83827
- [ ] https://github.com/grafana/grafana/issues/83912
- [ ] https://github.com/grafana/grafana/issues/83917
- [ ] https://github.com/grafana/grafana/issues/84174
- [ ] https://github.com/grafana/grafana/issues/84194
- [ ] https://github.com/grafana/grafana/issues/84564
- [ ] https://github.com/grafana/grafana/issues/84569
- [ ] https://github.com/grafana/grafana/issues/84570
- [ ] https://github.com/grafana/grafana/issues/84717
- [ ] https://github.com/grafana/grafana/issues/84818
- [ ] https://github.com/grafana/grafana/issues/84199
- [ ] https://github.com/grafana/grafana/issues/85080
- [ ] https://github.com/grafana/grafana/issues/85405
- [ ] https://github.com/grafana/grafana/issues/84212
- [ ] https://github.com/grafana/grafana/issues/84563
- [ ] https://github.com/grafana/grafana/issues/83292
```

</details>

**Comment by axelavargas** [comment]
Moved a few bugs reported during bug bashing to https://github.com/grafana/grafana-org/issues/13 (these bugs did not make it to G11)
