### ISSUE TITLE
UX tweaks

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#83925]
After some UX feedback sessions with other UXs colleagues, I have some improvements that we might want to cover before going to G11

```[tasklist]
### Tasks
- [x] Change the UI style for the text-link component at the bottom of the toggletip for "Grafana LLM plugin"
- [x] Improve placement of custom input on the toggletip.
- [x] Enhance the method for applying current suggestions.
- [x] Optimize placement of history arrows (counter) for better discoverability.
```

**Comment by natydej** [comment]
Here are the main changes by section:

**Content generated**
- Change the placement of the content generated to be at the top

**History arrows (counter)**
- Move the placement of **history arrows** to be below on the **bottom-right** to the content generated

**Actions**
- Move the placement for the **quick actions** _(Event shorter/More descriptive/Regenerate)_ to be next to the main CTA, below the content generated
- Add **leading icons** for the quick actions buttons
- Change the wording of the **"Apply**" button to **"Apply AI text"**. Change the size to be "**sm**" as the other quick actions buttons

**Input**
- Change the placement of the `input` to be at the bottom
- Size of the **height** of the `input` to be `32px` with `8px` of **padding**
- Change the icon to send the message input, to a "**ghost button**" with a leading icon and a label that says **"Send"**

**Information for AI documentation**
- Change the style of the **text-link** of the "Grafana LLM plugin" link to follow our [Saga DS guidelines]


[Figma link](https://www.figma.com/file/yBuMIJDWHJbsfujZK2raRo/DashGPT?type=design&node-id=986-8645&mode=design)

<img width="567" alt="Toggletip_AI_text_generation" src="https://github.com/grafana/grafana/assets/51436795/3f055ba4-b223-49b0-918f-1b798b081720">


cc @ivanortegaalba @nmarrs @adela-almasan @SandersAaronD
