### ISSUE TITLE
I18n: Add pt-br language

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#84307]
We want to add first-class support for Brazilian Portuguese (pt-br) translations of Grafana.

We already have documentation for adding a new language, so as doing this we should make sure this is up to date https://github.com/grafana/grafana/blob/main/contribute/internationalization.md#how-to-add-a-new-language

```[tasklist]
### Tasks
- [x] Arrange new language Translated (invoice / contract)
- [x] https://github.com/grafana/grafana/pull/84458 (Set up language in Crowdin)
- [x] https://github.com/grafana/grafana/pull/84461 (Set up language in code)
- [ ] https://github.com/grafana/grafana/pull/84457
- [ ] Pull in translations from Crowdin (when translated!
```
