### ISSUE TITLE
Prometheus: Improve Code Mode autocomplete performance for large numbers of metric names

### ISSUE THREAD

**Issue by NWRichmond** [grafana/grafana#84612]
**Why is this needed**:

When a Prometheus instance has an enormous number of unique metric names (on the order of many hundreds of thousands, or millions), it takes a long time (single to double-digit seconds) to load metric names to power the autocomplete experience in [Code Mode][code-mode]. Rendering such a large volume of label names in the Monaco editor can freeze the UI.

**What would you like to be added**:

When the number of metric names exceeds threshold value _n_ (10k by default, but configurable by the user), use fuzzy search to provide only the _n_ best metric name matches to the Monaco editor's pool of autocomplete values.

**Who is this feature for?**

Prometheus data source users, especially those with hundreds of thousands to millions of unique metric names.

[code-mode]: https://grafana.com/docs/grafana/latest/datasources/prometheus/query-editor/#code-mode

**Tasks**

- [x] Use fuzzy search to restrict results to the 10k-most relevant metric names
  - [x] Associated tests
- [x] Configure the Monaco editor to update suggestions as input changes, but only when fuzzy search is active
  - [x] Associated tests
- [x] Allow threshold value _n_ to be configurable by the user
- [x] Add tooltip-esque disclaimer when fuzzy search is active
- [x] Put new functionality behind a feature flag

**Comment by 09jvilla** [comment]
> When supplying our own autocomplete values to Monaco (as we do today), it continues to use its own matching algorithm for autocomplete, so there are no guarantees that autocomplete values we provide (which we can filter ourselves depending on the query) will appear in the autocomplete dropdown.

Can you clarify this a bit? Just to be sure I understand...

The full set of values is A, B, C, D, E, F, G. 
We filter that down to A, B, C, D, which we provide to Monaco. 
Monaco does its own matching algorithm on top of that, and may only choose to provide A and B. 

Is that right?

**Comment by NWRichmond** [comment]
@09jvilla your example is spot-on!

**Comment by 09jvilla** [comment]
Thanks for clarifying @NWRichmond !

**Comment by 09jvilla** [comment]
@NWRichmond , I wonder if its worth dropping by the UX feedback session to see about some way to indicate that the list of autocompleted results is not exhaustive because there were so many matches?

**Comment by NWRichmond** [comment]
@09jvilla I totally agree that an indication in the UI would be helpful. @grafana/observability-metrics is privileged to have dedicated product design resources, so with thanks to @catherineymgui's help, we've got a solution: a tooltip-esque disclaimer alongside the Code Mode / Query Builder toggle.

![Image](https://github.com/grafana/grafana/assets/5732000/f21c9b00-989c-44e3-8d54-d48488837590)

The final text will likely be:
> Autocomplete includes only the _n_-most relevant metric names

, where _n_ is either 10k (default) or the user's configured limit.

**Comment by 09jvilla** [comment]
Sweet =) Nice eng<>ux collab and I like what you're proposing!
