### ISSUE TITLE
Scenes powered dashboards enhancements

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#84834]
```[tasklist]
### Improvements
- [ ] https://github.com/grafana/grafana/issues/86974
- [ ] https://github.com/grafana/grafana/issues/81079
- [ ] Standarize buttons across setting pages
- [ ] Unifiy list views in the Dashboard settings
- [ ] Remove link/variables/annotations uses a delete prompt to confirm
- [ ] One can view variables dependency graph
- [ ] https://github.com/grafana/grafana/issues/85744
- [ ] https://github.com/grafana/grafana/issues/86421
- [ ] Dashboard:  [Panel Repeating] Perform repeats when a variable changes to be multi-select even if the dashboard is not saved
- [ ] https://github.com/grafana/grafana/issues/86681
```

**Comment by natellium** [comment]
Moved to https://github.com/grafana/grafana-org/issues/13
