### ISSUE TITLE
DataViz - Bug Bash v11

### ISSUE THREAD

**Issue by adela-almasan** [grafana/grafana#85021]
```[tasklist]
### Table
- [ ] https://github.com/grafana/grafana/issues/85020
```

```[tasklist]
### XYChart2
- [ ] https://github.com/grafana/grafana/issues/85025
- [ ] https://github.com/grafana/grafana/issues/85033
- [ ] https://github.com/grafana/grafana/issues/85035
- [ ] https://github.com/grafana/grafana/issues/85029
- [ ] https://github.com/grafana/grafana/issues/85027
- [ ] https://github.com/grafana/grafana/issues/85032
- [ ] https://github.com/grafana/grafana/issues/85034
- [ ] https://github.com/grafana/grafana/issues/85036
- [ ] https://github.com/grafana/grafana/issues/85030
- [ ] https://github.com/grafana/grafana/issues/85497
- [ ] https://github.com/grafana/grafana/issues/85368
- [ ] https://github.com/grafana/grafana/issues/85389
- [ ] https://github.com/grafana/grafana/issues/85390
```
```[tasklist]
### Canvas
- [ ] https://github.com/grafana/grafana/issues/84957
- [ ] https://github.com/grafana/grafana/issues/85679
- [ ] TODO: See refinements / feedback section of: https://github.com/grafana/grafana/issues/81347
- [ ] https://github.com/grafana/grafana/issues/85299
- [ ] https://github.com/grafana/grafana/issues/85295
- [ ] https://github.com/grafana/grafana/issues/84334
- [ ] https://github.com/grafana/grafana/issues/85031
- [ ] https://github.com/grafana/grafana/issues/84848
- [ ] https://github.com/grafana/grafana/issues/84845
- [ ] https://github.com/grafana/grafana/issues/84958
- [ ] https://github.com/grafana/grafana/issues/84959
- [ ] https://github.com/grafana/grafana/issues/85019
- [ ] https://github.com/grafana/grafana/issues/84960
- [ ] https://github.com/grafana/grafana/issues/84956
- [ ] https://github.com/grafana/grafana/issues/84961
- [ ] https://github.com/grafana/grafana/issues/85013
- [ ] https://github.com/grafana/grafana/issues/85038
- [ ] https://github.com/grafana/grafana/issues/85037
```

```[tasklist]
### Tooltips
- [x] Barchart tooltip regression
- [ ] https://github.com/grafana/grafana/issues/85521
- [ ] https://github.com/grafana/grafana/issues/85370
- [ ] https://github.com/grafana/grafana/issues/85382
- [ ] https://github.com/grafana/grafana/issues/86457
```

**Comment by grafanabot** [comment]
@adela-almasan please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:
