### ISSUE TITLE
Sharing: Redesign the sharing modal

### ISSUE THREAD

**Issue by natydej** [grafana/grafana#85240]
### Goal
Create a more user-friendly sharing experience within the dashboard context.

This is the first iteration, where we are going to use what we have and pass it into the new workflow of sharing

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/85241
- [ ] https://github.com/grafana/grafana/issues/85268
- [ ] https://github.com/grafana/grafana/issues/85653
- [ ] https://github.com/grafana/grafana/issues/85805
- [ ] https://github.com/grafana/grafana/issues/88336
- [ ] https://github.com/grafana/grafana/issues/88337
- [ ] https://github.com/grafana/grafana/issues/88338
- [ ] https://github.com/grafana/grafana/issues/88506
- [ ] https://github.com/grafana/grafana/issues/88576
- [ ] https://github.com/grafana/grafana/issues/88789
- [ ] https://github.com/grafana/grafana/issues/88991
- [ ] https://github.com/grafana/grafana/issues/89143
- [ ] https://github.com/grafana/grafana/issues/89316
- [ ] https://github.com/grafana/grafana/issues/89858
- [ ] https://github.com/grafana/grafana/issues/89962
- [ ] https://github.com/grafana/grafana/issues/90018
- [ ] https://github.com/grafana/grafana/issues/88783
- [ ] https://github.com/grafana/grafana/issues/88989
- [ ] https://github.com/grafana/grafana/issues/88807
- [ ] https://github.com/grafana/grafana/issues/89688
- [ ] https://github.com/grafana/grafana/issues/75963
- [ ] https://github.com/grafana/grafana/issues/91193
```
**Implement drawer in share panel**
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/90493
- [ ] https://github.com/grafana/grafana/issues/90494
- [ ] https://github.com/grafana/grafana/issues/90495
- [ ] https://github.com/grafana/grafana/issues/90496
```
**How to test it**
Enable `newDashboardSharingComponent` FF

**Resources**
[Figma](https://www.figma.com/file/AjvrAorYpnfSoMpU5kwf39/Adoption-of-Sharing?type=design&node-id=3118-42711&mode=design)
[Figma Share panel designs](https://www.figma.com/design/AjvrAorYpnfSoMpU5kwf39/Adoption-of-Sharing?node-id=4560-57369&m=dev)
[Product DNA](https://docs.google.com/document/d/1KsOho6-7FiHXwH991_15VAiUn4W9WhNGoFKfkVrupHE/edit)

### What we have now
![Image](https://github.com/grafana/grafana/assets/51436795/66a423c6-55fb-4622-955c-09bdc1cccaa7)

https://github.com/grafana/grafana/assets/51436795/7924ee79-0190-48b5-b6b0-fd52da7e111a

### What we want to accomplish

![Image](https://github.com/grafana/grafana/assets/51436795/f0947e11-537a-4a7a-8756-ace447cb90eb)

https://github.com/grafana/grafana/assets/51436795/edc8aea3-ddc9-4a78-88f2-1d9181f75118

**Comment by juanicabanas** [comment]
Enable `newDashboardSharingComponent` to see the improvements
