### ISSUE TITLE
Deprecated layout components: get rid of `Layout.tsx` including `HorizontalGroup` and `VerticalGroup`

### ISSUE THREAD

**Issue by eledobleefe** [grafana/grafana#85510]
Although we added new layout components, such as `Box` and `Stack`, there are many places in our code where we can find these deprecated components. The aim here is to list them all and increasingly change `Layout`, `HorizontalGroup` and `VerticalGroup` into `Stack` or the most appropriate new layout component for each case.

Teams, owners of affected code:
1. Alerting Frontend: 
https://github.com/grafana/grafana/issues/86841
2. Dashboards Squad: 
https://github.com/grafana/grafana/issues/86831
3. Dataviz Squad:
https://github.com/grafana/grafana/issues/86844
4. Explore squad: 
https://github.com/grafana/grafana/issues/86839
5. App Platform Squad:
https://github.com/grafana/grafana/issues/86863
6. [Frontend Platform](#frontend)
7. Identity Access Team:
https://github.com/grafana/grafana/issues/86864
8. Observability Logs:
https://github.com/grafana/grafana/issues/86869
9. Observability Metrics:
https://github.com/grafana/grafana/issues/86872
10. Observability Traces and Profiling:
https://github.com/grafana/grafana/issues/86874
11. Partner Datasources:
https://github.com/grafana/grafana/issues/86876
12. Plugins Platform Frontend:
https://github.com/grafana/grafana/issues/86878
13. Sharing Squad:
https://github.com/grafana/grafana/issues/86880

There is also code to modify in *grafana*-*enterprise*:
[Deprecated layout component: get rid of HorizontalGroup](https://github.com/grafana/grafana-enterprise/issues/6451)
___

#### Remove `HorizontalGroup` and `VerticalGroup`
- [x] [packages/grafana-ui/src/components/Button/Button.story.tsx](https://github.com/grafana/grafana/pull/85644)
- [x] [packages/grafana-ui/src/components/IconButton/IconButton.story.tsx](https://github.com/grafana/grafana/pull/85639)
- [x] [packages/grafana-ui/src/components/Table/FilterPopup.tsx](https://github.com/grafana/grafana/pull/86398)
- [x] [packages/grafana-ui/src/components/ThemeDemos/ThemeDemo.tsx](https://github.com/grafana/grafana/pull/85888)
- [x] [packages/grafana-ui/src/components/ToolbarButton/ToolbarButton.story.tsx](https://github.com/grafana/grafana/pull/86067)
#### Remove `HorizontalGroup`
- [x] [packages/grafana-ui/src/components/ConfirmModal/ConfirmModal.tsx](https://github.com/grafana/grafana/pull/85660)
- [x] [packages/grafana-ui/src/components/DateTimePickers/DateTimePicker/DateTimePicker.tsx](https://github.com/grafana/grafana/pull/85663)
- [x] [packages/grafana-ui/src/components/FilterPill/FilterPill.story.tsx](https://github.com/grafana/grafana/pull/85736)
- ~~[ ] packages/grafana-ui/src/components/Forms/FieldArray.story.tsx~~ (Deprecated component)
- [x] [packages/grafana-ui/src/components/Modal/Modal.tsx](https://github.com/grafana/grafana/pull/85756)
- [x] [packages/grafana-ui/src/components/PanelChrome/PanelChrome.mdx](https://github.com/grafana/grafana/pull/85843)
- [x] [packages/grafana-ui/src/components/PanelChrome/PanelChrome.story.tsx](https://github.com/grafana/grafana/pull/85843)
- [x] [packages/grafana-ui/src/components/SecretTextArea/SecretTextArea.tsx](https://github.com/grafana/grafana/pull/85849)
- [x] [packages/grafana-ui/src/components/Table/CellActions.tsx](https://github.com/grafana/grafana/pull/85860)
- ~~[ ] packages/grafana-ui/src/graveyard/Graph/GraphContextMenu.tsx~~(Deprecated component)
- [x] [packages/grafana-ui/src/options/builder/hideSeries.tsx](https://github.com/grafana/grafana/pull/86192)
- [x] [packages/grafana-ui/src/options/builder/stacking.tsx](https://github.com/grafana/grafana/pull/86192)
- [x] [packages/grafana-runtime/src/components/DataSourcePicker.tsx](https://github.com/grafana/grafana/pull/86389)
- [x] [public/app/core/components/ForgottenPassword/ForgottenPassword.tsx](https://github.com/grafana/grafana/pull/86393)
- [x] [public/app/core/components/Login/LoginPage.tsx](https://github.com/grafana/grafana/pull/86068)
- [x] [public/app/core/components/RolePicker/RolePickerMenu.tsx](https://github.com/grafana/grafana/pull/86145)
- [x] [public/app/core/components/RolePicker/RolePickerSubMenu.tsx](https://github.com/grafana/grafana/pull/86145)
- [x] public/app/features/sandbox/TestStuffPage.tsx
- [x] [public/app/features/org/SelectOrgPage.tsx](https://github.com/grafana/grafana/pull/86061)
- [x] [public/app/features/search/page/components/ActionRow.tsx](https://github.com/grafana/grafana/pull/86143)
- [x] [public/app/features/profile/ChangePasswordForm.tsx](https://github.com/grafana/grafana/pull/86061)
- [x] [public/app/plugins/datasource/grafana/components/TimeRegionEditor.tsx](https://github.com/grafana/grafana/pull/86395)
#### Remove `VerticalGroup`
- [x] [packages/grafana-ui/src/components/Alert/Alert.mdx](https://github.com/grafana/grafana/pull/86400)
- [x] [packages/grafana-ui/src/components/Alert/InlineBanner.story.tsx](https://github.com/grafana/grafana/pull/86400)
- [x] [packages/grafana-ui/src/components/Alert/Toast.story.tsx](https://github.com/grafana/grafana/pull/86400)
- [x] [packages/grafana-ui/src/components/Dropdown/Dropdown.story.tsx](https://github.com/grafana/grafana/pull/86521)
- [x] [packages/grafana-ui/src/components/Forms/Checkbox.story.tsx](https://github.com/grafana/grafana/pull/86524)
- ~~[ ] packages/grafana-ui/src/components/InfoBox/InfoBox.story.tsx~~ (Deprecated component)
- [x] [packages/grafana-ui/src/components/Link/TextLink.story.tsx](https://github.com/grafana/grafana/pull/86526)
- [x] [packages/grafana-ui/src/components/Menu/Menu.story.tsx](https://github.com/grafana/grafana/pull/86529)
- [x] [packages/grafana-ui/src/components/PageLayout/PageToolbar.story.tsx](https://github.com/grafana/grafana/pull/86581)
- [x] [packages/grafana-ui/src/components/TagsInput/TagsInput.story.tsx](https://github.com/grafana/grafana/pull/86582)
- [x] [packages/grafana-ui/src/components/Text/Text.story.tsx](https://github.com/grafana/grafana/pull/86584)
- [x] [packages/grafana-ui/src/components/ThemeDemos/EmotionPerfTest.tsx](https://github.com/grafana/grafana/pull/86588)
- [x] [public/app/core/components/AppNotifications/AppNotificationList.tsx](https://github.com/grafana/grafana/pull/86612)
- [x] [public/app/core/components/ForgottenPassword/ChangePassword.tsx](https://github.com/grafana/grafana/pull/86614)
- [x] [public/app/core/components/Login/LoginServiceButtons.tsx](https://github.com/grafana/grafana/pull/86616)
- [x] [public/app/core/components/Login/UserSignup.tsx](https://github.com/grafana/grafana/pull/86616)
- [x] [public/app/features/org/OrgDetailsPage.tsx](https://github.com/grafana/grafana/pull/86621)
- [x] [public/app/features/profile/UserProfileEditPage.tsx](https://github.com/grafana/grafana/pull/86619)
- [x] [public/app/features/sandbox/BenchmarksPage.tsx](https://github.com/grafana/grafana/pull/86621)

**Comment by eledobleefe** [comment]
After merging [this](https://github.com/grafana/grafana/issues/109857), we close this epic as done
