### ISSUE TITLE
QueryService: implement /api/ds/query with /apis/query.grafana.app/

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#86491]
This epic aims to identify the big tasks and open issues while trying to migrate from are single tenant `/api/ds/query` endpoint to a multi-tenant api running as an apiserver.  This epic does not address multi-tenancy, it is just making sure the behavior is the same (or better!) and that we can address multi-tenancy in another issue.

TODO:
- [ ] Support executing queries against the service from the browser
- [ ] Some datasources (graphite?) only look at the first time-range, so using groupd queries is broken.
- [ ] Must verify that datasource security is accurately applied
- [ ] ...

Known differences in behavior:
* The HTTP request payload can include timeRange in each query (previously only possible in gRPC)
* The request objects now support [ResultAssertions](https://github.com/grafana/grafana-plugin-sdk-go/blob/main/experimental/apis/data/v0alpha1/query.go#L420)
* Queries with `hide: true` will not be returned (currently the behavior is inconsistent)
* ...
