### ISSUE TITLE
E2C: Public Preview frontend

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#86861]
This epic tracks frontend work for the next stage of Everyone-to-Cloud Migration project.

Previous epic https://github.com/grafana/grafana/issues/82361

See https://docs.google.com/document/d/1AwMREtGYBP_dIYqT2BEKfAc9mqBPAeraT305o6FGWGI/edit for breakdown and link to sequence diagram

The user flow is largely the same as the current sync workflow. The main differences are terminology and there's now an additional step:
 - User clicks "build snapshot"
 - _frontend polls for status updates_
 - When done, user clicks "upload"
 - _frontend polls for status updates, updates per-resource table_

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/89533
- [ ] https://github.com/grafana/grafana/issues/89534
- [ ] https://github.com/grafana/grafana/issues/89898
- [ ] https://github.com/grafana/grafana/issues/89537
- [ ] https://github.com/grafana/grafana/issues/90039
- [ ] https://github.com/grafana/grafana/issues/90044
- [ ] https://github.com/grafana/grafana/issues/90120
- [ ] https://github.com/grafana/grafana/issues/90121
- [ ] https://github.com/grafana/grafana/issues/90642
- [ ] https://github.com/grafana/grafana/issues/90643
- [ ] https://github.com/grafana/grafana/issues/90644
- [ ] E2C: Show dashboard metadata from status response
```

----

To develop locally, Cloud Migration has a handy developer mode that simulates most interactions with cloud. In your custom.ini,

```ini
[cloud_migration]
developer_mode = true
```

To test the Cloud-side of the pages, enable `is_target = true` config as well.

When running in developer mode, you need a token that just looks correct. You can generate one yourself by enabling `is_target` and creating a token. Or just use this one:

```
eyJUb2tlbiI6ImNvbXBsZXRlbHlfZmFrZV90b2tlbl9jZG9peTFhYzdwdXlwZCIsIkluc3RhbmNlIjp7IlN0YWNrSUQiOiAzODYzLCJTbHVnIjoic3R1Ymluc3RhbmNlIiwiUmVnaW9uU2x1ZyI6ImZha2UtcmVnaW9uIiwiQ2x1c3RlclNsdWciOiJmYWtlLWNsdXNlciJ9fQo=
```

**Comment by mmandrus** [comment]
Marking as done from the Operator Experience perspective, well done 👏

**Comment by ashharrison90** [comment]
marking as done 🥳
