### ISSUE TITLE
DashboardScene: Migrate dashboard e2e tests to scenes

### ISSUE THREAD

**Issue by Sergej-Vlasov** [grafana/grafana#87234]
There are two aspects to this migration:

```[tasklist]
### 1. Migrate e2e test suites
- [x] `dashboard-suite` https://github.com/grafana/grafana/pull/84598
- [x] `smoke-tests-suite` https://github.com/grafana/grafana/pull/84598
- [ ] https://github.com/grafana/grafana/issues/87688
- [ ] https://github.com/grafana/grafana/issues/87724
- [ ] https://github.com/grafana/grafana/issues/88910
- [ ] https://github.com/grafana/grafana/issues/89051
- [ ] https://github.com/grafana/grafana/issues/89295
- [ ] https://github.com/grafana/grafana/issues/87178
- [ ] Adjust plugin E2E selectors
- [ ] adjust old arch e2e after `dashboardScene` is enabled by default
- [ ] investigate and come up with solution for interference between scenes and old arch tests
```

```[tasklist]
### 2. Improve github workflow
- [ ] https://github.com/grafana/grafana/issues/87235
- [ ] https://github.com/grafana/grafana/pull/89297
- [ ] remove github workflow because we integrated in drone
```
