### ISSUE TITLE
Epic: Replace Webpack with Vitejs

### ISSUE THREAD

**Issue by jackw** [grafana/grafana#87308]
**Why is this needed**:

For the past [~7 years](https://github.com/grafana/grafana/pull/9391) Grafana has relied on Webpack for bundling and loading frontend assets (js, css, images). During this time the main problem that bundlers (like Webpack) aimed to solve of authoring and loading modular javascript has become a native feature of browsers thanks to [ES modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules). With ES modules being supported by all major browsers [ViteJS](https://vitejs.dev/) was created in 2020 to help solve the issue bundlers created - performance bottlenecks in javascript based tooling.

A design doc on this subject can [be found here](https://docs.google.com/document/d/15vNpw7EtFcF-05HGZwHYXcL0qCtKK98DHBMifhj2tmM/edit#heading=h.5sybau7waq2q) where I've tried to get down as much as I can about the pros and cons.

By migrating away from Webpack to Vite the frontend-ops working group aims to improve the development experience by greatly improving contributors productivity and happiness when working within the Grafana codebase with:

- Near instant frontend development server startup
- Faster development rebuilds due to rebuilding only the module or it's tree on changes
- Hot Module reloading allowing developers to get faster feedback on their changes in the browser
- Simpler build tooling configuration 

https://github.com/grafana/grafana/assets/73201/df7b1b24-f75b-4f64-92a1-39a4ab23661b

Additionally we move to bundling Grafana as ES modules giving us:

- Improved loading performance with native support for asynchronous and parallel script loading 
- Use modern web standards

Ephemeral instance demo'ing production build can be [found here](https://github.com/grafana/grafana/pull/80664#issuecomment-2085551528) (note it might be down at times).

**What would you like to be added**:

To reach this goal a research PR exists [here](https://github.com/grafana/grafana/pull/80664) to help better understand how to tackle issues. The following are groups lists of tasks that need to be tackled to achieve a migration.

The following are tasks that can be worked on against the research branch to better understand how to solve specific problems. 

```[tasklist]
### Remaining unknowns
- [ ] Env vars. We use `process.env.NODE_ENV`, vite wants to use `import.meta.env`. We need to figure out how best to balance this as Jest for example explodes when switching to use `import.meta.env`.
- [ ] Frontend Sandbox e2e tests fail. Might be related to env vars.
- [ ] Trusted types doesn’t like vite output which breaks e2e tests. This is related to execution order and the trusted types config is being setup after app is executed.
- [ ] Define a chunking strategy. ViteJS does not come with one out the box.
- [ ] Frontend CDN testing to confirm the research branch "solution" works.
- [ ] Node polyfills need addressing. They're not included, cause a load of warnings in console and likely break some core datasources that require them.
- [ ] Kusto loads but its css is lacking at times (e.g. when loading a page where Kusto is used directly).  The vite config might need some worker specific plugins adding to solve this.
```

---

The following are tasks we can do in advance of the migration to vite.

```[tasklist]
### What can be done in advance
- [ ] Enable [`isolatedModules`](https://www.typescriptlang.org/tsconfig/#isolatedModules) in TsConfig and clean up type re-export errors
- [ ] Fix jQuery imports
- [ ] Move tether-drop source code into codebase
- [ ] Bump `react-router-compat` to `^6.18.x` to fix misalignment with `react-router` dependencies
- [ ] Clean up barrel file usage within public/app (potentially this is a nice to have and can be tackled post migration)
- [ ] Clean up circular dependencies within public/app (potentially this is a nice to have and can be tackled post migration)
- [ ] Clean up usage of `??` operator usage to reduce esbuild warnings
- [ ] Clean up dynamic imports that are statically imported elsewhere as this will cause weird execution errors in vite builds
- [ ] Test, merge [grafana/lezer-traceql PR](https://github.com/grafana/lezer-traceql/pull/18) then bump in grafana core
- [ ] Test, merge [grafana/lezer-logql PR](https://github.com/grafana/lezer-logql/pull/60) then bump in grafana core
- [ ] Major Bump [ansicolor](https://github.com/xpl/ansicolor) to >=2.0.3 to solve exports missing types
- [ ] Convert [jsonMarkup.js](https://github.com/grafana/grafana/blob/main/public/app/features/explore/TraceView/components/TraceTimelineViewer/SpanDetail/jsonMarkup.js) into an es module (`imports / exports` instead of `require / module.exports`)
- [ ] Due to vite wanting `"type": "module"` in the root package.json migrate  Levitiate workflow scripts to es modules
- [ ] Due to vite wanting `"type": "module"` in the root package.json migrate betterer configuration to work in an esm environment
- [ ] Due to vite wanting `"type": "module"` in the root package.json migrate  playwright configuration to work in an esm environment
- [ ] Due to vite wanting `"type": "module"` in the root package.json migrate  Cypress configuration to work in an esm environment
```

---

The following is a list of everything we should do for Vite to build in dev and production and support all the nuances of the Grafana code base.

```[tasklist]
### Vite specific tasks
- [ ] ... possibly all the things from **remaining unknowns** task list
- [ ] Backend development and production asset manifest implementation
- [ ] Enterprise dev and prod support
- [ ] Configure Vite for Theme support by making css files entrypoints in config
- [ ] CDN loading support
- [ ] Replace require.context usage with import.meta.glob
- [ ] Write a vite angular template plugin to replace webpack ngtemplate-loader
- [ ] Create a Cors Webworker to replace the custom webpack CorsWorker plugin
- [ ] Delete all webpack related dependencies from root package.json (except webpack and webpack-cli)
```

**Who is this feature for?**

Grafanistas

related: https://github.com/grafana/grafana/issues/76161
related: https://github.com/grafana/grafana/issues/41595

**Comment by tomratcliffe** [comment]
Regarding `import.meta.env`: I've used [vite-plugin-environment](https://www.npmjs.com/package/vite-plugin-environment) successfully before - it means you're explicit about what env vars are passed in, and you then use them as `process.env.foo` anyway

**Comment by bz2** [comment]
@jackw Do you mind making your google docs design doc for this public?

(Also considering moving away from webpack, so would be helpful to see your thinking for grafana)

**Comment by jackw** [comment]
I'm going to close this in favour of a migration to Rspack which gives us much of the same benefits without the effort required. https://github.com/grafana/grafana/issues/128309
