### ISSUE TITLE
Q2 🪵 goals

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#87563]
```[tasklist]
### Loki
- [ ] https://github.com/grafana/grafana/issues/87564
- [ ] https://github.com/grafana/grafana/issues/85483
- [ ] https://github.com/grafana/grafana/issues/78588
- [ ] https://github.com/grafana/grafana/issues/72147
```

```[tasklist]
### Logs visualisations
- [ ] https://github.com/grafana/grafana/issues/87987
- [ ] https://github.com/grafana/grafana/issues/87989
```

```[tasklist]
### Elasticsearch
- [ ] https://github.com/grafana/grafana/issues/65813
- [x] Complete hand off
```

```[tasklist]
### Explore Logs
- [x] Private preview rollout - https://github.com/orgs/grafana/projects/617
- [x] Public Preview Cloud - https://github.com/orgs/grafana/projects/635
- [x] Add explore's logs panel interaction - show only this field
- [ ] Virtualisation of logs panel view
- [x] Table view (exprimental)
- [x] Add explore's logs panel interaction - filter for/out
```

**Comment by matyax** [comment]
Completed.
