### ISSUE TITLE
[Epic]: Notification Banner

### ISSUE THREAD

**Issue by Clarity-89** [grafana/grafana#87610]
Enable Grafana admins to configure a banner that would be visible below the top navigation bar.  

```[tasklist]
### Tasks
- [ ] Create a database to store notification banner-related settings
- [ ] Create an API to manage the banner
- [ ] Add a configuration page for the notification banner
- [ ] Display the configured banner below the top navigation bar
- [ ] Document the notification banner feature
- [ ] Add analytics to trace the usage of the notification banner
- [ ] Integrate the notification banner with Role-Based Access Control (RBAC)
- [ ] Enable configuration of the notification banner through code 
```
