### ISSUE TITLE
Explore: Enable Query Library in ops

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#87900]
Requires:

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/90424
- [ ] Enabling toggles: `grafanaAPIServer`, `queryLibrary` and `queryService` - check how to enable it in ops
- [ ] TBC. Add a note in the UI that data may be lost (see https://raintank-corp.slack.com/archives/C04RVCAG9B5/p1721040617482389)
- [x] Enable in one instance in dev
- [ ] Enable in dev
- [ ] https://github.com/grafana/grafana/issues/91839
```
