### ISSUE TITLE
Alerting: Central alert state history

### ISSUE THREAD

**Issue by soniaAguilarPeiron** [grafana/grafana#88345]
We want to allow users to see all the alert state transitions that happen over the time.

**What problem are we trying to solve?**

- Users can troubleshoot issues by getting a comprehensive view of activities during a specific time frame.

- A view that allows filtering by labels and time periods is invaluable for diagnosing problems, as it shows all alert transitions, not just isolated ones.

- This also helps quickly identify periods of high activity.

**Who can view this feature?**

The idea is that everyone can see this feature as long as this Grafana instance is using Loki implementation for the alert state history.
And another important point is that , we want to show only the alert transitions for the alerts that the user has access to. 
We want to use a new RBAC permission for it.

[Link to the prototype](https://www.figma.com/proto/AYMboJsnYgSAAdYM9hoMLn/Alerting?page-id=3456%3A92979&type=design&node-id=3454-83294&viewport=195%2C58%2C0.22&t=VAIn4EQqqF4X8eFl-1&scaling=min-zoom&starting-point-node-id=3454%3A83294)

Tasks:

- [x] Add the feature toggle
- [x] Add the search and time period inputs
- [x] Add the bar chart for the number of events.
- [x] Add the table for the events with rows collapsed
- [x] Implement the expanded rows detail.
- [x] Use RBAC
- [x]  Be able to add label to the filter by clicking on it
- [x] Filter by current base state (Alerting,Normal or Pending

**Comment by soniaAguilarPeiron** [comment]
**Project Update**

**Highlight**


- The feature was enabled for all users on the cloud starting July 25th. https://github.com/grafana/deployment_tools/pull/159570  
- Docs have been updated by @brendamuir https://github.com/grafana/grafana/pull/91033 
- What's new has been updated by @brendamuir https://grafana.com/docs/grafana-cloud/whats-new/centralized-alert-history-page/
- Enablement video has been added to the What's new field in [here](https://admin.grafana.com/content-admin/#/collections/whats-new/entries/2024-07-26-centralized-alert-history-page) , and now an automated process will ping the proper people from content team to include the video in the what's new post.
- There is `Fullstory` segment for the feature [here](https://app.fullstory.com/ui/o-1CN5TD-na1/segments/c7Z1svwhNEiO/people:search?completeSessions=false) 

**Trending**


🟢 on track


**Next**
Video will be published and included in the What's new post by the content team.
