### ISSUE TITLE
Canvas Cleanup + Refactors

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#88526]
Canvas code has built up some technical debt over the years and some files have become unruly and difficult to manage. The purpose of this epic is to pay down this technical debt, improve our understanding of canvas code, improve maintainability and more.

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/pull/87477
- [ ] https://github.com/grafana/grafana/pull/88010
- [ ] https://github.com/grafana/grafana/pull/88491
- [ ] https://github.com/grafana/grafana/pull/88517
- [ ] Resolve duplicate typescript object issue (i.e. two CanvasElementOptions definitions, two CanvasConnection definitions etc)
- [ ] Refactor / break up ConnectionSVG.tsx file
- [ ] Refactor / break up Connection.tsx file
- [ ] Refactor / break up element.tsx file
- [ ] Refactor / remove basic utils.ts file (not a huge fan of a generic utils file, we can move functions to domain area (i.e. connection calcs can go to connections code area etc)
- [ ] Finish cleaning up canvas betterer issues (missing <Trans> wrappers for text)
```
