### ISSUE TITLE
POC: Make QueryLibrary work everywhere by allowing 2 apps to be rendered side by side

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#88552]
Currently QueryLibrary is both an app and a tight integration in Explore. We want QueryLibrary work everywhere without needing it to be tightly integrated and be still kept as an app that either is installed or not. We can do that by leveraging existing primitives like App Extensions and allowing 2 apps to be open at the same time with something like a split view from Explore.

That way the QueryLibrary can be open next to any other application and use it to import/export queries in different context like, explore, dashboards, alerting or other apps.

### Tasks

- [ ] Lift the split view functionality from explore up in the stack in grafana so that grafana can render split view with different contents anywhere.
- [ ] Make sure we can render an app inside the split view. Currently, it is tightly coupled with explore code so this will probably need to happen together with previous step. In this case mainly it should be able to render the QueryLibrary app with it's list of queries. This will replace the drawer version of the QueryLibrary in explore for the POC.
- [ ] The app extension API should be able to open QueryLibrary app in the second split view and pass context to it, whether it's the query to be added to the library or for example the panel id where we want to import query.
- [ ] A message passing API should allow communication between the 2 apps open. For QueryLibrary it should be able to send message with the new query and panelId to be updated back to the dashboard. Other option is to bake this into the extension point as sort of getResult API after the extension point is triggered.
- [ ] Optionaly a drag and drop API could be used to directly add queries form the QueryLibrary to the dashboard either as new panel or to replace existing queries. Some sort of object schema would need to be defined so that each application can understand what is being dragged and decide what to do with it.

**Comment by evictorero** [comment]
Closing since this is an epic without remaining work.
