### ISSUE TITLE
Restore Dashboards: Rename the new section

### ISSUE THREAD

**Issue by L-M-K-B** [grafana/grafana#88557]
For now we implemented the new section according to the naming from the hackathon project. Since trash section is not a good name we decided to change it to recently deleted.

**TODOs:**
- [x] adjust name in MegaMenu
- [x] adjust name in page headline
- [x] adjust subtitle
- [x] rename folder and component
- [x] move TrashPage to manage dashboards folder
