### ISSUE TITLE
Epic: DataLinks and Actions

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#88578]
Expand all datalinks to include API capability + rethink canvas datalink implementation.

Work order:

```[tasklist]
### Canvas
- [ ] https://github.com/grafana/grafana/issues/88727
- [ ] https://github.com/grafana/grafana/issues/89964
- [ ] https://github.com/grafana/grafana/issues/88729
- [ ] https://github.com/grafana/grafana/issues/89961
- [ ] https://github.com/grafana/grafana/issues/88728
- [ ] https://github.com/grafana/grafana/pull/85430
- [ ] https://github.com/grafana/grafana/issues/90385
- [ ] https://github.com/grafana/grafana/issues/90675
- [x] Actions: Add feature toggle
- [ ] https://github.com/grafana/grafana/pull/93708
```

```[tasklist]
### Field config data links and actions
- [ ] https://github.com/grafana/grafana/issues/92437
- [ ] https://github.com/grafana/grafana/pull/93248
- [ ] https://github.com/grafana/grafana/pull/92874
- [ ] https://github.com/grafana/grafana/issues/93620
```

```[tasklist]
### Table
- [ ] https://github.com/grafana/grafana/issues/90396
- [ ] https://github.com/grafana/grafana/issues/94027
```

```[tasklist]
### Tooltip Plugin 2
- [x] Need to modify how we handle primary link here
```

```[tasklist]
### Later
- [x] Add support for `primary` data link in each panel - timeseries?
```

```[tasklist]
### Design tasks
- [x] DataLinks API : Determine the button location to create the new link type ([DONE](https://www.figma.com/design/f1akLOk39Iu9loyMs4TA7c/Data-Links?node-id=149-5881&t=IaRTS88L1x2UfhGT-0))
- [x] DataLinks API: Create a way to differentiate between data links and commands
- [ ] https://github.com/grafana/grafana/issues/93121
```

```[tasklist]
### Known issues
- [ ] https://github.com/grafana/grafana/issues/91588
- [ ] https://github.com/grafana/grafana/issues/91590
- [ ] https://github.com/grafana/grafana/issues/92337
```

```[tasklist]
### GA
- [ ] https://github.com/grafana/grafana/issues/93621
- [ ] https://github.com/grafana/grafana/issues/79479
- [ ] https://github.com/grafana/grafana/issues/99218
- [ ] https://github.com/grafana/grafana/issues/99220
- [ ] https://github.com/grafana/grafana/issues/99219
- [ ] https://github.com/grafana/grafana/issues/97605
- [ ] https://github.com/grafana/grafana/issues/97604
- [ ] Tooltip: Add cursor styling for one-click
- [ ] https://github.com/grafana/grafana/issues/99921
```

**Notes**
Bar gauge does not have tooltips
Gauge does not have tooltips
Stat supports data links

We will need to go through each visualization that supports data links and modify how their UX works / adheres to the "primary" datalink etc

**Comment by leeoniya** [comment]
> Create a new type of link (command?) that allows you to configure API call via this new type of data link

thinking about this a bit more.

currently the data link editor populates `field.links` array. i dont think we can add a new link type here that doesnt break typings and existing code. we can re-use the editor but internally we may need to manage the commands in a separate new field prop. if that's the case, then we need to make sure you cannot have both a primary link _and_ a primary command.
