### ISSUE TITLE
Epic: Pinning Nav Items

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#88921]
As our navigation keeps growing, we have received various feedback that it can be hard for users to find the page they are looking for. Our first step of a solution is to add a way that lets users pin items to the top of their navigation menu.

```[tasklist]
### Development
- [ ] https://github.com/grafana/grafana/issues/88923
- [ ] https://github.com/grafana/grafana/issues/88922
- [ ] https://github.com/grafana/grafana/issues/89531
- [ ] https://github.com/grafana/grafana/issues/90113
- [ ] https://github.com/grafana/grafana/issues/90118
- [ ] https://github.com/grafana/grafana/issues/90119
- [ ] https://github.com/grafana/grafana/issues/90438
```

```[tasklist]
### Release
- [ ] https://github.com/grafana/grafana/issues/91995
- [ ] https://github.com/grafana/grafana/issues/91996
- [ ] https://github.com/grafana/grafana/issues/91994
- [ ] Pin Nav Items: Remove feature toggle
```

```[tasklist]
### Bugs
- [ ] https://github.com/grafana/grafana/issues/90722
- [ ] https://github.com/grafana/grafana/issues/90981
- [ ] https://github.com/grafana/grafana/issues/91029
- [ ] https://github.com/grafana/grafana/issues/91120
- [ ] https://github.com/grafana/grafana/issues/91196
- [ ] https://github.com/grafana/grafana/issues/92692
```
