### ISSUE TITLE
Sharing Redesign: Change texts

### ISSUE THREAD

**Issue by juanicabanas** [grafana/grafana#88989]
```[tasklist]
### Tasks
- [x] Change backend UI messages mentioning public dashboard. As discussed [here](https://docs.google.com/document/d/1X073gsQ6RIoroVUGfT_4WdH7lO1OskSdgd2oelNehcs/edit), "Public Dashboards" is not a concept anymore.
- [x] Review the UI texts that were included in the new design (@imatwawana)
- [x] Review and change Share Snapshot texts (@juanicabanas)
- [x] Review and change Share Internally texts  (@juanicabanas)
- [x] Review and change Share Externally texts  (@juanicabanas)
- [x] Review and change Export PDF texts (@lucychen-grafana)
- [x] Review and change Export JSON texts (@lucychen-grafana)
- [ ] https://github.com/grafana/grafana/issues/91082
- [ ] https://github.com/grafana/grafana-enterprise/issues/7029
```

**Comment by natydej** [comment]
Updates, adding a description below the page header title

![Image](https://github.com/user-attachments/assets/3c285b49-ef3b-4761-88d6-638ea59984be)


**Changes:**

1. Breadcrumbs title section to Shared dashboard
2. Public dashboard menu item to Shared dashboard
3. Page header title to Share dashboards, and a description below “Manage your organization's externally shared dashboards”
4. Pause sharing label to Pause access
5. View public dashboard tooltip to View shared dashboard
6. Configure public dashboard tooltip to Configure shared dashboard
7. Revoke public URL tooltip to Revoke access

**Comment by imatwawana** [comment]
Do we need to think about this page in Administration:
![image](https://github.com/user-attachments/assets/c9ec79d9-56be-42bd-a049-55b3855f4ee7)

**Comment by natydej** [comment]
About the page in Administration, here is the proposal
<img width="1440" alt="SharedDashboardUsers" src="https://github.com/user-attachments/assets/ccd919ed-05c9-4a61-97bf-8e6a2059b6eb">

This design is using the [Interactive table component](https://developers.grafana.com/ui/latest/index.html?path=/story/experimental-interactivetable--with-pagination)

**Open the modal with the shared dashboards:**
<img width="450" alt="SharedDashboards" src="https://github.com/user-attachments/assets/accd7e1e-9618-4497-ba54-bffe158e1d4d">

**Revoke access modal:**
<img width="450" alt="RevokeAccess" src="https://github.com/user-attachments/assets/dd3a474b-7401-4d7a-bb40-8b7a449ec811">

[Figma link](https://www.figma.com/design/3NVCaLjYM8PYHgVAvNQxBr/Sharing-Squad---Card-component?node-id=1174-6573&t=VoufCBlrYrPRtIY2-1)

**Comment by juanicabanas** [comment]
Task already done
