### ISSUE TITLE
Allow administrators to enable and disable the frontend sandbox for specific plugins on demand.

### ISSUE THREAD

**Issue by academo** [grafana/grafana#89340]
When visiting an installed plugin catalogue page inside Grafana. administrators will have the option to enable the frontend sandbox for that specific plugin.

Some requirements:

*  This should be an on/off runtime switch without the need to change the configuration file or restart Grafana itself.
* No available for Angular plugins
* documentation on known incompatible plugins
* research: highlight plugins we recommend turning the sandbox on

The sandbox as is requires a content security policy (csp) with unsafe-eval, which is the current grafana default as of creation of this issue.

if the grafana instance doesn't have a csp with unsafe-eval:

* the sandbox options won't be available
* sandbox won't run even if previously activated in specific plugins
* a notice (of a kind) will be shown telling users about the existence of the frontend sandbox and either instructions or a link to instructions of how to activate it.
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/93984
- [x] Frontend Sandbox: Implement frontend UI to enable/disable frontend sandbox for specific plugin
- [x] Frontend Sandbox: Only enable frontend sandbox for plugins marked with plugins sandbox on
- [ ] https://github.com/grafana/grafana/issues/94974
```

**Comment by grafanabot** [comment]
@academo please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:

**Comment by academo** [comment]
Finished in https://github.com/grafana/grafana-enterprise/pull/7435
