### ISSUE TITLE
PluginExtension: Refactor the internals to match the new APIs

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#89473]
### Description

When we [introduced](https://github.com/grafana/grafana/pull/87236) the possibility for plugins to expose a component we felt that the names of the API was a bit confusing and unnecessary complicated. So we decided to simplify it by adding the suffix `add` for the functions used when you are configuring a Link or Component for an extension point (`addLink`, `addComponent`). Then we also introduced the `expose` prefix for the function used when exposing a component from a plugin.

In the PR mentioned above, we only changed the public APIs to be able to include the functionality in Grafana 11.1. This issue aims to adress that by cleaning up the internals of the UI extensions functionality to make that code base simpler, more robust and with the proper names.

When we introduced the UI extensions functionality we made the assumption that extension point authors wanted to be able to fetch both Links and Components at the same time, which seems to be incorrect.

### Todo
- [ ] Change so we have three separate registries for `addLinks`, `addComponent` and `exposeComponent`.
- [ ] Change so the `getPluginExtensions` fetches extensions from `addLinks` and `addComponent` registries. This is done only to keep backwards compatibility.
- [ ] Simplify the naming of the types so it correlates with the links and components conventions.

**Comment by mckn** [comment]
This is done in the linked PRs. Closing...
