### ISSUE TITLE
PluginExtensions: Add a reactive log to make it easier to debug extensions

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#89476]
### Description
When adding/exposing `links` or `components` we have a set of rules that needs to be followed when it comes to the format of the `id`, required fields etc. Lots of people seems to get stuck while trying to add an extension due to some small errors (typings, id missmatch etc.)

Today we print a couple of debug logs in the console but due too a lot of noise they are really easy to miss. Instead we are planning to add a proper log that will persist logs from all interactions with the extension registry when you run Grafana in development mode.

We could then expose that log in the extensions admin view to make it really easy to understand why things might not show up the way the developer expected.

### Todo
- [ ] Introduce a reactive log that will store all log events for a user session (maybe have some kind of upper limit).
- [ ] Write a log item when adding things to the registry (info, warn and error).
- [ ] Write a log item when getting things from the registry.

### Related
https://github.com/grafana/grafana/pull/85944
https://github.com/grafana/grafana/issues/77856

**Comment by mckn** [comment]
Follow up ideas:

- Also printing errors to the console.log to make it easier to debug during CI.
- On the first occurring error, while in development, print a message in the console log with a link to the admin log page.
