### ISSUE TITLE
PluginExtensions: Introduce an admin page

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#89480]
### Background

Currently it's quite hard to debug why in certain cases extensions are not rendered, and it's also hard to experiment with new extensions or extension points. We feel that there is a lot we could do to make the developer experience better.

### Initiative
We would like to introduce an admin view in Grafana that, **long term**, could be used to manage UI extensions from different plugins. 

**Features that we think this page could / should have:**
- Discover available extension points
- Discover available extensions (link and component)
- Discover available exposed components
- Enable / disable extensions
- Enable / disable extension points
- Enable / disable exposed components
- Enable / disable a plugin to access the extensions framework
- Logs: show all extensions framework related logs in a single place to make debugging easier
- Experimentation: edit `onClick()` functions and `configure()` functions for link extensions from the UI
- Experimentation: add link / component extensions, or exposed components from the UI

### Implementation
Ideally there are two ways to implement this:
- **Using an app plugin** - we would like to go forward with this one. We think it has the following benefits over the other approach:
  - Release cycle is not strictly bound to Grafana core
  - It can persist the user settings _(changes to extensions or extensions added through the UI)_ in `jsonData`. (This can be migrated later once we have a better storage for plugins.) 
  - It can leverage provisioning, which makes it simpler to share a certain setup
  - Dogfooding - we can try our framework and apis in action
- Implementing the page in Grafana core

### Blockers
- **Make it possible to edit the registry during runtime from a plugin** - this is something that we are working on during the refactoring of the extensions registries: https://github.com/grafana/grafana/pull/92014
- **Add meta information to the `plugin.json` about extensions, extension points and exposed components** - unfortunately if we would like to make these discoverable, then we need to have some metadata available before we would load the plugins. Although automatic meta-extraction is still not completely off the table, probably an easier option for now is to make these fields mandatory by only loading extensions and extension points which are present in the plugin.json - https://github.com/grafana/grafana/issues/92005

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/pull/92014
- [ ] https://github.com/grafana/grafana/issues/92005
- [ ] Figure out how we would like to distribute the app plugin (a built-in app plugin in the Grafana repo, or something that can be added via provisioning). Update the issue description accordingly.
- [ ] Create an app plugin that registers pages under in the left nav menu
- [ ] Add a way to persist admin-page related settings in the jsonData
- [ ] Add a way to collect logs from the extensions framework and visualise them on the admin page
- [ ] Add a way to enable / disable extensions from the admin page
```

**Comment by tolzhabayev** [comment]
Closing this one as done as we have the admin page in place now
