### ISSUE TITLE
RestoreDashboards: Add event tracking

### ISSUE THREAD

**Issue by L-M-K-B** [grafana/grafana#89623]
**We require event tracking for the following:**
- [x] click on restore button
- [x] click on confirm button in restore modal
- [x] click on permanently delete button
- [x] click on confirm button in permanently delete modal

Naming for the events can be found [here](https://docs.google.com/document/d/15KOmlZvruApr5vNmaW5j9re6Jzbqp-FaHD5vri_1ZpE/edit#heading=h.o637wnozuvw8).

**Comment by eledobleefe** [comment]
Addition to the list:
 - Add event to Dashboard browse page 
    - num_selected : number of items selected
    - Deleting from dashboard browse view
    - What kind of items get deleted 
    - Whether the user has the feature toggle turned on

- Add event in dashboard settings → DeleteDashboardModal
    - num_selected: 1
    - Deleting from dashboard settings
    - What kind of items get deleted: dashboard
    - Whether the user has the feature toggle turned on
