### ISSUE TITLE
Navigation: Unified AppChrome bar

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#89840]
See PoC [here](https://github.com/grafana/grafana/pull/89170)
See initial design [here](https://www.figma.com/design/iUay5pce6DfSMq00MXG2vV/Navigation-with-contextbar?node-id=92-19320&node-type=canvas&t=RD2EngTJKCk3Zu45-0)

## Prerequisites
- [x] #89894
- [x] #93652 

## TODO
- [x] #91999
- [x] #93309
- [x] #93895
- [x] #93721
- [x] #93797
- [x] #94052
- [x] #94185
- [x] https://github.com/grafana/grafana/pull/94199
- [x] #94187
- [x] #94307
- [x] https://github.com/grafana/grafana/pull/94812
- [x] #94593
- [x] #94305
- [x] #94325
- [x] #94594
- [x] #95329
- [x] #95338
- [x] #95342
- [x] #95382
- [x] #95383
- [x] https://github.com/grafana/deployment_tools/pull/191340

## Optional
- [x] #94080

## Rollout
https://docs.google.com/document/d/1c4zAWvhJ7CgO1AnpC_kspFg5pOL32kVHzkPaLzli6GI/edit 

## Post-rollout
- [x] https://github.com/grafana/grafana/pull/97937
- [ ] #99380

**Comment by torkelo** [comment]
@ashharrison90 just curious, why is https://github.com/grafana/grafana/issues/89894 a prerequisites?

**Comment by ashharrison90** [comment]
@torkelo i guess it's not really. _but_ we want to do that work as well since it fixes some longstanding issues (see https://github.com/grafana/grafana/issues/13437). 

unfortunately it touches a lot of the same areas, so it probably shouldn't be done at the same time. since we won't start this epic til next quarter, i wanted to get https://github.com/grafana/grafana/issues/89894 done first so listed it as a prereq
