### ISSUE TITLE
Page: Make `<body>` the scrollable element

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#89894]
```[tasklist]
### Tasks
- [x] Kubernetes app https://github.com/grafana/grafana-k8s-plugin/pull/1516
- [x] AWS -> Logs https://github.com/grafana/grafana-aws-app/pull/448
- [x] App O11y https://github.com/grafana/app-observability-plugin/pull/1147
- [x] Frontend O11y https://github.com/grafana/app-o11y-kwl/pull/951
- [x] Connections sticky header https://github.com/grafana/cloud-onboarding/pull/7267
- [ ] https://github.com/grafana/grafana/issues/90930
- [ ] https://github.com/grafana/grafana/issues/90929
- [ ] https://github.com/grafana/grafana/issues/90927
- [ ] https://github.com/grafana/grafana-enterprise/issues/6938
- [x] Check pinned timeseries tooltip works correctly (Ask Josh/Staton/Leon) https://github.com/grafana/grafana/pull/91385
- [ ] https://github.com/grafana/hg-cloud-home-admin/pull/745
```
