### ISSUE TITLE
Plugin Extensions: Investigate how to share types between plugins

### ISSUE THREAD

**Issue by leventebalogh** [grafana/grafana#90171]
**Design doc:** -

### The problem
Currently if plugin devs would like to reuse an exposed plugin component, or if they would like to register an extension to a certain extension point, they need to copy-paste the static types over and over (these are either the types for the component props or for the link context object). It is a recurring request from plugin devs to be able to somehow _share_ these static types, so there is only a single source of truth. 

We are currently looking at two possible options which I detail in the next points.

```[tasklist]
### Tasks
- [x] Create a working PoC of **Option 1)**
- [x] Create a working PoC of **Option 2)**
- [x] Hold an **internal demo** and try to make an internal decision on what we would favour (also discuss what we think we are missing)
- [x] Hold a **demo for internal plugin dev teems**, and ask for their feedback. Revalidate our decision on which option to go forward with.
- [x] Add documentation
```

---

### Option 1) - share types using an NPM package - [PREFERRED]

<img src="https://github.com/grafana/grafana/assets/9974811/e89bf537-168d-493c-a695-a2dbd8e6099e" width="600" />

**Pros**
- Working with packages is common-knowledge
- Relatively easy to discover the package version and what's available in it

**Cons**
- Having an extra package probably needs more maintenance from us
- Might needs extra work from the plugin dev

---

### Option 2) - share types without needing an NPM package

<details>

<summary>📹 Demo screen recordings (2)</summary>

https://github.com/grafana/grafana/assets/9974811/4224ded6-fd1b-4577-a5a1-db9f89d7d25e

https://github.com/grafana/grafana/assets/9974811/7ab2ef88-8292-475a-9bf4-44957e6d4a3e

</details>

**Pros**
- No NPM package involved
- Ideally works seamlessly, by fetching types in the background

**Cons**
- Has a learning curve - it's something custom, that is still not "common knowledge"
- Understanding / discovering what version of the types are available locally can be a bit more complicated

---
