### ISSUE TITLE
EPIC: Unit detection and display

### ISSUE THREAD

**Issue by yangkb09** [grafana/grafana#90294]
**Why is this needed**:

Explore Metrics has a visualization panel generator that configures panels and queries for any given metric, based on that metric name. Based on the type of query we are generating, and the name of the metric, we attempt to configure the visualization panel with suitable units but do not always succeed.

Currently, for well-formed prometheus metric names, we can detect “seconds” and “bytes.” Everything else is represented using the “short” unit. For rate queries, we divide the unit per seconds.

**Who is this feature for?**

Explore Metrics users

**What would you like to be added**:

The following list is based off the cases listed in the [design doc](https://docs.google.com/document/d/1lk7SKP9zHJnj2mjvLwHF5ZL6P4HTkCM7f8FxGQh7slk/edit?usp=sharing)

```[tasklist]
### Tasks
- [ ] Metadata
- [ ] Support additional units
- [ ] Units expressed in recording rules metrics #89669
- [ ] Support unconventional metric name format
- [ ] Support unspecified unit for ambiguous metrics
- [ ] Display the countable “thing”
```

```[tasklist]
### Bug fixes
- [x] Display Grafana unit in Overview Tab https://github.com/grafana/grafana/pull/90002
```

```[tasklist]
### Refactors
- [ ] https://github.com/grafana/grafana/pull/91415
```

**Comment by itsmylife** [comment]
We'll revisit this based on customer request.
