### ISSUE TITLE
Tracking process: Create the schemas in Rudderstack

### ISSUE THREAD

**Issue by eledobleefe** [grafana/grafana#90466]
Create the schemas to follow the new Rudderstack tracking process of:

- [x] [AnnouncementBanner](https://github.com/grafana/grafana-enterprise/blob/main/src/public/announcement-banner/BannerForm.tsx#L72)
- [x] [RestoreDashboard](https://github.com/grafana/grafana/pull/90321)
- [x] [PinningNavItems](https://github.com/grafana/grafana/issues/90438)

**Comment by Clarity-89** [comment]
Should we do the same for the pinning nav items tracking?

**Comment by eledobleefe** [comment]
> Should we do the same for the pinning nav items tracking?

Yes. It's a new process and it's not mandatory right now, but I think it's better to add all this now if we can 🤷‍♀️ 
I'll add Pinning Nav Items to the list ;)

**Comment by eledobleefe** [comment]
The events and their properties on the list have been created, so closing this issue as done! 🎉
