### ISSUE TITLE
Sharing: Implement drawer in share panel

### ISSUE THREAD

**Issue by juanicabanas** [grafana/grafana#90492]
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/90493
- [ ] https://github.com/grafana/grafana/issues/90494
- [ ] https://github.com/grafana/grafana/issues/90495
- [ ] https://github.com/grafana/grafana/issues/90496
```

[Figma designs](https://www.figma.com/design/AjvrAorYpnfSoMpU5kwf39/Adoption-of-Sharing?node-id=4560-57369&m=dev)

**Comment by natydej** [comment]
Something to consider, are the keyboards shortcuts, it could be something like this:
<img width="628" alt="Screenshot 2024-07-17 at 12 49 22" src="https://github.com/user-attachments/assets/0639aaca-42df-4a3f-b92a-d6a1edca8d09">

**Comment by evictorero** [comment]
Added all this information and tasks to the main [epic](https://github.com/grafana/grafana/issues/85240) since this is a dependency of the main epic.
