### ISSUE TITLE
Epic: MultiCombobox

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#90812]
May be done in parallel to #87959. These may share some code, but the functionality will be different.

- [x] #91254
- [x] #91256
- [x] Virtualize list
- [x] #98423 
- [x] Add All value behavior
- [x] Add custom value behavior
- [ ] Apply e2e selectors and tests
- [x] Document component
- [x] Ability to select all values and then deselect some values. Ability to search / filter list and select all that match current search term (and then deselect some). https://github.com/grafana/support-escalations/issues/11893

All non-functional requirements in #87959 applies here too.

## Functionality
- [x] Async option loading
- [x] Clear all button
- [x] Category support
- [x] Can select multiple values without the menu closing
- [x] Custom value possible
- [x] Can remove items while the menu is open
- [x] Uses checkboxes
- [x] Responsive when a lot of chips are used
