### ISSUE TITLE
Prometheus: Label values variable query not returning correct set umbrella issue

### ISSUE THREAD

**Issue by bohandley** [grafana/grafana#91074]
**What is this?**
This is an umbrella issue to keep track of issues around the label_values endpoint calls in the variable query editor

**What happened?**
We support different types and versions of Prometheus. [In Grafana v11 we default to support versions that support using the `label_values` endpoint with the `match[]` param](https://github.com/grafana/grafana/pull/84778). If users are using an older version of Prometheus that does not support this, getting label values with an older version of Prometheus will fail silently and show incorrect values because it requires the `match[]` param to correctly filter. 

**The solution**
Users that experience this issue should set their type and version in the Prometheus data source configuration screen.

![Image](https://github.com/user-attachments/assets/53cf1910-d6e6-41d5-bdd9-84b448e5cba2)

- [x] https://github.com/grafana/grafana/issues/91034
- [x] https://github.com/grafana/grafana/issues/90924
- [x] https://github.com/grafana/grafana/issues/90226
- [x] https://github.com/grafana/grafana/issues/88875

**Comment by bohandley** [comment]
Closing this as we have notified customers of the upgrade and we have provided access to the series endpoint in the Prometheus data source configuration page if they want the old behavior.

https://github.com/grafana/grafana/pull/94443
