### ISSUE TITLE
Topnav: Move breadcrumbs to allow for a toolbar

### ISSUE THREAD

**Issue by L-M-K-B** [grafana/grafana#91733]
@ashharrison90 This description requires more details.

```[tasklist]
### Tasks
- [ ] Create a design doc
- [ ] implement solution
- [ ] instrument user events
- [ ] Create rollout plan
- [ ] Create monitoring dashboard
- [ ] Rollout
```

**Comment by L-M-K-B** [comment]
Duplicate. See #89840 instead
