### ISSUE TITLE
Table: The next generation (NG)

### ISSUE THREAD

**Issue by codeincarnate** [grafana/grafana#91965]
## Rationale

The current table panel is facing a number of shortcomings in terms of functionality. In particular there are a few areas that are difficult to meet with out current architecture:

1. **Styling**: Flexibility of styling has grown in importance over time, however the current table has very complicated styling properties which make it difficult to anticipate how styles will be applied.
2. **Interactivity**: Tables in other projects are more interactive and support things like context menus which we currently lack.
3.  **Filtering/Manipulation**: We're a bit hamstrung by our use of `react-table` as filtering capabilities are somewhat limited. Transformations are also not easy to integrate into the current table architecture despite being closely tied to usage of the table.

| Feature |  Old Table | New Table |
| -------- | ------- | ------- |
| Row Height Selection| ✅ |  |
| Minimum Column Width | ✅ |  |
| Global Column Width| ✅ |  |
| Row Highlighting  |  ✅| |
| Row Formatting  |  ✅| |
| Column Formatting  |  ❌ | |
| Pagination  |  ✅| |
| Column text alignment | ✅ | |
| Column filters  |  ✅| |
| Cell support | ✅ | |
| Table header support  |  ✅| |
| Table footer support  |  ✅| |
| Text wrapping  |  ✅| |
| Cell value inspect  |  ✅| |
| Nested tables  |  ✅| |
| Tree view  |  ❌| |
| Column resizing  |  ✅| |
| Field overrides  |  ✅| |
| Transformation Integration  |  ❌ | |
| Context menu  |  ❌ | |
| Datalinks  |  ✅ | |

```[tasklist]
### Basic (Dirty) PoC
- [ ] https://github.com/grafana/grafana/pull/92615
- [ ] https://github.com/grafana/grafana/issues/91968
- [ ] https://github.com/grafana/grafana/issues/91967
- [ ] https://github.com/grafana/grafana/issues/94264
- [ ] https://github.com/grafana/grafana/issues/94265
```

```[tasklist]
### Messi PoC
- [ ] https://github.com/grafana/grafana/issues/91982
- [ ] https://github.com/grafana/grafana/issues/93590
```

```[tasklist]
### Clean PoC
- [ ] https://github.com/grafana/grafana/issues/91972
- [ ] https://github.com/grafana/grafana/issues/91969
- [ ] https://github.com/grafana/grafana/issues/91970
- [ ] https://github.com/grafana/grafana/issues/91971
- [ ] https://github.com/grafana/grafana/issues/94025
```

## Other
[Design Doc](https://docs.google.com/document/d/13V8QwzBo6x1ZUh-uOnfsBx3kW5bskMwJXmQYE3o5wxs/edit)

**Comment by codeincarnate** [comment]
Also looking at https://github.com/grafana/grafana/issues/93590, which should make the Inspector easier to leverage across components

**Comment by torkelo** [comment]
@codeincarnate is there a doc or issue that outlines the problems we want to solve with a new table component?

**Comment by codeincarnate** [comment]
@torkelo there's a design doc here https://docs.google.com/document/d/13V8QwzBo6x1ZUh-uOnfsBx3kW5bskMwJXmQYE3o5wxs/edit

**Comment by staton-hyse11** [comment]
Closing this epic to track work [here](https://github.com/grafana/grafana/issues/94754)
