### ISSUE TITLE
Plugins: Expand extensions metadata for all extensions and extension points

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/grafana#92005]
Currently our extensions metadata is only for extensions which explicitly register to a given extension point. That is those which use the `addLink()` and `addComponent()` functions. It is required in the plugin.json so that we are able to lazy load plugins as and when they are required.

As we look to provide the admin page or to include extensions information within the plugin details page, we would need all extensions and extension points to be defined in the plugin.json as well. 

This issue is to expand the metadata to cover:
- plugin defined extension points
- exposed components

```[tasklist]
### Tasks
- [x] Update the plugin.json schema to cover the extensions related meta-data
- [ ] https://github.com/grafana/grafana/pull/93429
- [x] Open PRs in internal app plugins for adding the necessary meta-data
```

**Comment by leventebalogh** [comment]
I think we can close this one, right @sympatheticmoose?
