### ISSUE TITLE
Extensions: versioning strategy for extensions

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/grafana#92202]
In our conversations with app developers and in our documentation we recommend declaring a version for an extension point or an exposed extension within it's ID.

For example, in our [reference doc](https://grafana.com/developers/plugin-tools/reference/ui-extensions#addcomponent) we give the example:
```
export const plugin = new AppPlugin<{}>().addComponent({
  targets: ['grafana/user/profile/tab/v1'],
  title: 'New user profile tab',
  description: 'A new tab that shows extended user profile information',
  component: () => {
    return <div>Hello World!</div>;
  },
});
```

However, this could be misleading, as that target extension point is not currently versioned.

Additionally, we need to determine exactly how we want to handle multiple versions within the enums. As suggested by @leventebalogh :

**Working with string ids**
In this case it's relatively easy to understand how it's done, you just add the version string at the end of the id.
```
// Plugin (with extension point) 
const { links } = usePluginLinks({ extensionPointId: "grafana/user/profile/tab/v1" });

// Plugin (registering the extension)
.addLink({
  targets: "grafana/user/profile/tab/v1",
  // ...
})
```

**Working with enums**
```
// @grafana/data
  // Currently
  export enum PluginExtensionPoints {
    UserProfileTab = 'grafana/user/profile/tab',
  }

  // Option 1)
  export enum PluginExtensionPointsV1 {
    UserProfileTab = 'grafana/user/profile/tab/v1',
  }

  // Option 2)
  export enum PluginExtensionPoints {
    UserProfileTabV1 = 'grafana/user/profile/tab/v1',
    UserProfileTabV2 = 'grafana/user/profile/tab/v2',
  }

// Plugin (registering the extension)
.addLink({
  targets: PluginExtensionPoints.UserProfileTabV1,
  // ...
})
```

```[tasklist]
### Tasks
- [ ] Remove versioned references in our docs (or make the extension point id generic like `grafana/area/component/v1`)
- [ ] Reach consensus on handling versions with the exposed enums
- [ ] Add versions to core extension points (inc migration strategy)
- [ ] Document how to version extensions and extension points - including handling new versions
```
