### ISSUE TITLE
AngularMigration: Migrate Graph to BarGauge

### ISSUE THREAD

**Issue by adela-almasan** [grafana/grafana#92434]
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana/issues/92435
- [ ] https://github.com/grafana/grafana/issues/92436
- [ ] Docs: Update BarGauge docs with legend option
```
