### ISSUE TITLE
Project Sidecar

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#92729]
Issue Epic to track implementation of Sidecar features.

See design doc for details https://docs.google.com/document/d/1oI2HiOBShY8B0E4kisLlt1ZPmmc-IYol0CZPhTZQBMw/edit#heading=h.5sybau7waq2q

```[tasklist]
### Grafana API
- [x] https://github.com/grafana/grafana/pull/90759
- [x] https://github.com/grafana/grafana/pull/91648
- [x] https://github.com/grafana/grafana/pull/94074
- [x] https://github.com/grafana/grafana/pull/94820
- [x] https://github.com/grafana/grafana/pull/94860
- [x] https://github.com/grafana/grafana/pull/94979
- [x] Tie the sidecar state to URL state so that sidecar router URL is the source of truth https://github.com/grafana/grafana/pull/96337
- [x] Define sidecar persistence when navigating around. Should sidecar be kept open or should it automatically close in some places? https://github.com/grafana/grafana/pull/96683
- [ ] https://github.com/grafana/grafana/issues/96896
- [ ] Implement promotion of sidecar view to main.
```

```[tasklist]
### Scenes updates
- [x] https://github.com/grafana/scenes/pull/899
```

```[tasklist]
### App implementation
- [ ] https://github.com/grafana/explore-logs/pull/828
- [ ] https://github.com/grafana/grafana/issues/96221
- [ ] https://github.com/grafana/explore-traces/pull/264
- [ ] https://github.com/grafana/grafana/issues/96222
```

```[tasklist]
### Metrics and monitoring
- [ ] https://github.com/grafana/grafana/issues/95389
- [ ] https://github.com/grafana/grafana/pull/96566
- [ ] https://github.com/grafana/grafana/issues/96894
```

**Comment by grafanabot** [comment]
@aocenas please add one or more appropriate labels. Here are some tips:

- if you are making an issue, TODO, or reminder for yourself or your team, please add one label that best describes the product or feature area. Please also add the issue to your project board. :rocket:

- if you are making an issue for any other reason (docs typo, you found a bug, etc), please add at least one label that best describes the product or feature that you are discussing (e.g. `area/alerting`, `datasource/loki`, `type/docs`, `type/bug`, etc). [Our issue triage](https://github.com/grafana/grafana/blob/main/ISSUE_TRIAGE.md#3-categorizing-an-issue) doc also provides additional guidance on labeling. :rocket:

 Thank you! :heart:
