### ISSUE TITLE
Epic: Link to correct documentation version from Grafana

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#93669]
When using Grafana, we want any links from the Grafana UI to Grafana documentation to link out to the correct specific version for your instance.

For example:
 - When running in Grafana Cloud, any docs links should go to the `/next/` version
 - When running a released on-prem version, it should go to the right minor version for your instance, such as `/v11.1/`
 - When running from source it should.... link to `/next/`?

It should be easy to developers to link to the correct version, and we should limit any regressions to hard-coded versions.

- [ ] Figure out business logic to map from grafana version to docs version
- [ ] Create component/utility for all to use to link to docs
- [ ] Add linting to prevent developers from hard coding docs versions in the future

**Comment by jdbaldry** [comment]
I'd like to potentially change the subject of this issue to "Link to the correct documentation from Grafana".

The reason for this is that there is separate documentation for Grafana Cloud and Grafana which can mean that a documentation link for Grafana running in Grafana Cloud could point to either `/docs/grafana/next/<REST>` or `/docs/grafana-cloud/<REST>` where the latter would be preferable. There isn't always a `/docs/grafana-cloud/` link for a given feature or topic so that's when we'd need to instead link to `/docs/grafana/next/<REST>`.

> When running from source it should.... link to `/next/`?

This seems like a reasonable default since it's what is published from the `main` branch where you would assume most source builds use but I'd like to make sure that it's configurable too so that you can either manually override the value or automatically get the right value when you're building from a version branch like `v10.4.x`

**Comment by jdbaldry** [comment]
So that I don't assume anything, what is stopping us from having different URL paths for the links dependent on build configuration?

**Comment by jdbaldry** [comment]
Maybe something like having a data file `links.json`

```json
{
  <LINK REFERENCE>: {
    "_default": "/docs/grafana/latest/foo/bar/",
    "<VERSION BUILD TAG>": "/docs/grafana-cloud/baz/quux/"
  },
}
```

And then code that looks up link references like:

```
var link = links.json["<LINK REFERENCE>"]._default

if links.json["<LINK REFERENCE>"]["<VERSION BUILD TAG>"] then
  link = links.json["<LINK REFERENCE>"]["<VERSION BUILD TAG>"]
fi
```

Another reason that version can't be the only variable part is that information architecture can change between two versions so `/docs/grafana/latest/foo/bar/` may move to `/docs/grafana/next/baz/quux/`.

**Comment by jangaraj** [comment]
Note: `/next` (latest) doc version may not be correct for Grafana Cloud. For example I like to have pinned Grafana Cloud instances, so I may not have latest Grafana version running. 

IMHO: also Grafana Cloud instance should go to the right minor version of that instance, such as `/v11.1/` (But Grafana Cloud versioning is confusing me, which is different topic. I don't have idea which release version am on, so I don't have idea which versioned doc should I check usually. Rolling release channels are even worse - UI is showing that my Grafana is "Fast", so there is missing context - I'm not sure if I should check 11.3, 111.2 doc - at least health endpoint return some version, so maybe that can be used to determine correct doc version).
