### ISSUE TITLE
Epic: Unified History MVP

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#94319]
Have a space that shows the most recent user history and allows you to navigate through it.

POC Designs: https://www.figma.com/design/lyOiBa502WyXeuvT40O0Ve/Unified-History-POC?node-id=2331-6963&node-type=frame&t=QIwqVopvxw6xf2HJ-0
POC: https://github.com/grafana/grafana/pull/94318
Spike ticket: https://github.com/grafana/grafana/issues/91807

```[tasklist]
### Tasks - Q4 2024
- [ ] https://github.com/grafana/grafana/issues/97865
- [x] Unified History: Separate history items by day
- [x] Unified History: Show only last 3 days
- [ ] https://github.com/grafana/grafana/issues/98953
- [ ] https://github.com/grafana/grafana/issues/97961
- [ ] https://github.com/grafana/grafana/issues/98097
- [x] Unified History: Multiple history items highlighted as "current" if same url [UX Flow]
- [x] Unified History: When clicking a history item it adds a new history step
- [ ] https://github.com/grafana/grafana/issues/99155
- [x] Unified History: When user clicks parent nav that has children, history shows '>' but no items after [cannot replicate now]
- [ ] Unified History: Move history section into navigation (Stretch) [Finally not needed]
- [ ] https://github.com/grafana/grafana/issues/99822
- [ ] https://github.com/grafana/grafana/pull/100381
```

```[tasklist]
### Future Tasks
- [ ] Unified History: Event to render a sparkline
- [x] Unified History: Styling for the blue dots
- [ ] Unified History: Store only last 3 days
- [ ] Unified History: Nested history entries
- [ ] Unified History: How it works with the user changing orgs
```

```[tasklist]
### Future Bugs
```

```[tasklist]
### Outstanding UX
- [ ] Unified History: Discussion and testing on where this feature should live
- [ ] Unified History: Testing behaviour when users select a history item, and general interaction flow
```
