### ISSUE TITLE
Epic: Combobox usage in Grafana

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#94681]
This issue keeps track of places we want to use the new Combobox component, and the issues for features that are requirements for adoption

## Combobox
- [x] Basic preferences
- [x] Prometheus QueryEditor (in staging env)
- [ ] Template variables

## MultiCombobox
- [ ] Template variables

## Other
- [ ] Identify props where Combobox can be drop-in replacement for Select

## Functionality
- [ ] Verify that the "short" use case is supported, such as `==`, `!=`
- [ ] Is the id passed properly for tests and accessibility

**Comment by ashharrison90** [comment]
great job team! 👏 🥳
