### ISSUE TITLE
Table: react-data-grid Evaluate library

### ISSUE THREAD

**Issue by drew08t** [grafana/grafana#94754]
Goal: evaluate [react-data-grid](https://github.com/adazzle/react-data-grid) as a replacement of [react-table v7](https://github.com/tanstack/table/tree/v7).

[react-data-grid examples](https://adazzle.github.io/react-data-grid/#/CommonFeatures)

```[tasklist]
### Phase 1 - Feature Parity Required to Evaluate Confidently
- [ ] https://github.com/grafana/grafana/issues/94757
- [ ] https://github.com/grafana/grafana/issues/94758
- [ ] https://github.com/grafana/grafana/issues/94759
- [ ] https://github.com/grafana/grafana/issues/94760
- [ ] https://github.com/grafana/grafana/issues/94763
- [ ] https://github.com/grafana/grafana/issues/94772
- [ ] https://github.com/grafana/grafana/issues/94775
- [ ] https://github.com/grafana/grafana/issues/95107
- [ ] https://github.com/grafana/grafana/issues/95108
- [ ] https://github.com/grafana/grafana/issues/95105
- [ ] https://github.com/grafana/grafana/issues/94765
- [ ] https://github.com/grafana/grafana/issues/94769
- [ ] https://github.com/grafana/grafana/issues/94777
- [ ] https://github.com/grafana/grafana/issues/94776
- [ ] https://github.com/grafana/grafana/issues/95195
```
