### ISSUE TITLE
Design: Panel Edit redesign

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#94970]
During the recent Grafana Frontend offsite, a workshop was ran to identify problem areas with the Panel Edit experience to be addressed. From the workshop, the following areas have been identified and scoped down to be worked on as time allows.

**Docs and resources** 
— [Figma designs](https://www.figma.com/design/smAeKf0r6egSli8lXmrPTz/Panel-Edit?node-id=163-488&t=5DKxdSG56RkRMNdd-1)
— [Planning doc](https://docs.google.com/document/d/1zGZ-gP5RXdYgJs3MY7Vd_D9G6pGC2w8Sqa5V7b7oHh8/edit?tab=t.0#heading=h.bbnrv8fh0hzv)

**Project phases**
###Design phase 1: Control changes and clean up
- [ ] Replace the radio button groups and complex components with dropdown selects
- [ ] Switch to two columns where it is appropriate.
- [ ] Introduce some separation within larger accordions to improve scanability
- [ ] Clean up obvious grouping issues to make sections more distinct.
- [ ] Explore better ways to display toggles, and use them for cases that don’t need selects.
- [ ] Remove 'auto' options in places where they aren’t necessary.
- [ ] Identify panel chunks that can be updated across all panel types
- [x] [PanelEdit: Align chevron direction | grafana#100386](https://github.com/grafana/grafana/pull/100386)

### Development: Implementation
- [ ] Identify UI chunks to roll out the new UI
- [ ] Establish tracking identifiers to monitor improvements
- [ ] Setup activity tracking in Rudderstack/Fullstory

### Design phase 2: Interactions
- [ ] Panel: panel edit inline rename

### Design phase 3: Overrides
- [ ] TBA

### Future
- [ ] Batch actions
- [ ] Data shape
