### ISSUE TITLE
Dashboard: Spike dashboard schema v2

### ISSUE THREAD

**Issue by axelavargas** [grafana/grafana#95538]
This epic will cover all tasks related to the spike about creating dashboard schema v2

@axelavargas 
- [x] Introduce feature toggle https://github.com/grafana/grafana/pull/95536 
- [ ] Transform Dashboard scene to v2 schema
- [ ] Run Dashboard scene with v2 schema. 

@ivanortegaalba 
- [ ] Explore tooling for schema authoring (design doc in [progress](https://docs.google.com/document/d/1jb2aWx9jctKDwmbzjsiisSPYdSLQ_kiCIao17bdCDH8) )

**Comment by axelavargas** [comment]
closing in favor of https://github.com/grafana/grafana-org/issues/239
