### ISSUE TITLE
EPIC: Remove Angular by Grafana 12

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#95822]
**Why?**
https://grafana.com/docs/grafana/latest/developers/angular_deprecation/#when-will-we-remove-angular-support-completely

This epic will combine different other epics and streams of work necessary for angular removal by Grafana 12.

### Core

**Must have:**
- [x] #98896
- [x] Coordinated rollout around release dates + RRC (how to target it for release properly) (plugins platform)

**Should have:**

- [x] Feature parity in panels https://github.com/grafana/grafana/issues/80983 (dataviz)
- [ ] grafana-worldmap-panel - get [customers](https://ops.grafana-ops.net/d/gcIEUkiVz/plugin-usage?orgId=1&from=now-90d&to=now&var-Plugin=grafana-worldmap-panel) off it (dataviz)
- [ ] Grafana [devenv example dashboards](https://github.com/grafana/grafana/tree/main/devenv/dev-dashboards) should be update to not use angular anymore (dashboards, dataviz, datasources)
- [ ] Update cloudwatch datasource [dashboards](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/cloudwatch/dashboards/RDS.json#L149) (datasources)
- [ ] Update prometheus datasource [dashboards] (https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/dashboards/grafana_stats.json#L438) (datasources)
- [ ] Update graphite datasource [dashboards](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/graphite/dashboards/carbon_metrics.json#L115) (datasources)
- [x] Migrate Asserts Dashboards https://github.com/grafana/asserts-app-plugin/issues/194
- [ ] Update azuremonitor datasources [dashboards](https://github.com/grafana/grafana/blob/4f095bcd65a0d1d7e9f436b9e8b6a5a514b1709e/public/app/plugins/datasource/azuremonitor/dashboards/storage.json#L1300) (datasources)
- [ ] Update grafana-servicenow-datasource provided dashboards ([example](https://github.com/grafana/plugins-private/blob/main/plugins/grafana-servicenow-datasource/src/dashboards/servicenow-incident-overview.json#L144), [thread](https://raintank-corp.slack.com/archives/C01C4K8DETW/p1740755404399039)) (datasources)
- [x] Update grafana-testdata-datasource [streaming dashboard](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/grafana-testdata-datasource/dashboards/streaming.json) to not use `graph` anymore. (plugins platform)

**Could have:**
- [ ] https://github.com/grafana/grafana-community-team/issues/227 (Dashboards squad)
- [ ] POC for Angular-compatibility app as an unsupported last resort option (Plugins Platform)

### Grafana Cloud

- https://github.com/grafana/grafana-community-team/issues/253

### To be triaged

- [ ] Alerting: Clean up [RuleEditorCloudOnlyAllowed](https://github.com/grafana/grafana/blob/main/public/app/features/alerting/unified/rule-editor/RuleEditorRecordingRule.test.tsx#L41-L42) and [RuleEditorRecordingRule](https://github.com/grafana/grafana/blob/main/public/app/features/alerting/unified/rule-editor/RuleEditorRecordingRule.test.tsx#L41-L42) tests
- [ ] Dashboards: Clean up [AutoRefreshIntervals](https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/components/DashboardSettings/AutoRefreshIntervals.test.tsx) tests
- [ ] Dashboards: [OptionsPaneOptions](https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/components/PanelEditor/OptionsPaneOptions.tsx) has angular related styles
- [ ] Dashboards: [PanelHeaderTitleItems](https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/dashgrid/PanelHeader/PanelHeaderTitleItems.tsx) has angular related code
- [ ] Dashboards: [variables/utils.ts](https://github.com/grafana/grafana/blob/main/public/app/features/dashboard-scene/variables/utils.ts#L204) has angular related code
- [ ] Datasources / Plugins: [TableModel.ts](https://github.com/grafana/grafana/blob/main/public/app/core/TableModel.ts) has MutableColumn for angular
- [ ] Explore: remove all references to `eventBridge`
- [ ] Frontend Platform: Figure out what to do with [reducers](https://github.com/grafana/grafana/blob/main/public/app/features/datasources/state/reducers.ts#L45-L46) that couldn't use createSlice because of ImmerJs and angular mutating state
- [ ] Frontend Platform: [navigation/patch directory](https://github.com/grafana/grafana/tree/main/public/app/core/navigation/patch) is all about angular
- [ ] Frontend Platform: e2e tests have [isAngularPanel helper](https://github.com/grafana/grafana/blob/main/e2e/old-arch/utils/flows/openPanelMenuItem.ts#L13) [2](https://github.com/grafana/grafana/blob/main/e2e/utils/flows/openPanelMenuItem.ts#L12)
- [ ] Frontend Platform: grafana/ui - [ModalsContext](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Modal/ModalsContext.tsx#L20) has angular related props
- [ ] Frontend Platform: grafana/ui - [Checkbox](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Forms/Checkbox.tsx#L102) has angular related styles
- [ ] Plugins / Frontend Platform: grafana/runtime: [LocationSrv](https://github.com/grafana/grafana/blob/main/packages/grafana-runtime/src/services/LocationSrv.ts#L32) has angular related code
- [ ] Plugins: Remove "angular support enabled" test from [TestLoader_Load_Angular](https://github.com/grafana/grafana/blob/main/pkg/services/pluginsintegration/loader/loader_test.go#L1200)
- [ ] Plugins: Remove "HideAngularDeprecation" config flag and `angular.hideDeprecation` definition plus tests
- [ ] Plugins: Remove angular tests from [PluginListItemBadges](https://github.com/grafana/grafana/blob/main/public/app/features/plugins/admin/components/PluginListItemBadges.test.tsx#L102-L110)
- [ ] Plugins: Clean up all usage of PanelModel.isAngularPlugin
- [ ] Plugins: Clean up all usage of angularDetected in Plugins Catalog
- [ ] Plugins: plugin-configs [webpack.config.ts](https://github.com/grafana/grafana/blob/main/packages/grafana-plugin-configs/webpack.config.ts#L69) still externalises angular and legacy sdk
- [ ] Not sure about codeowner: grafana/data [url.ts](https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/utils/url.ts#L30) has angular related code
- [ ] Not sure about codeowner: Backend - I think [dashdiffs](https://github.com/grafana/grafana/blob/main/pkg/components/dashdiffs/compare.go) backend code is related to angular. Related [angular -> react PR](https://github.com/grafana/grafana/pull/31997).

**Comment by vickyyyyyyy** [comment]
> Grafana [devenv example dashboards](https://github.com/grafana/grafana/tree/main/devenv/dev-dashboards) should be update to not use angular anymore

Discussed with squad and we will need to discuss further with data viz on how we should plan this cc @axelavargas

**Comment by tolzhabayev** [comment]
Moving the contents into epics per Group in Grafana Department
- https://github.com/grafana/grafana/issues/103866
-

**Comment by tolzhabayev** [comment]
Closing this EPIC as done, the followup cleanups will happens via separate issues https://github.com/grafana/grafana/issues/95822#issuecomment-2796609029
